### ISSUE TITLE
doc: improve numeric functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10000]
**Summary**

duckdb is a good example, all functions what we want is on one page(example and result):
https://duckdb.org/docs/sql/functions/numeric

**Comment by Xuanwo** [comment]
#10000!

**Comment by johnhaxx7** [comment]
Current doc includes example of invalid input https://databend.rs/doc/sql-functions/numeric-functions/acos. But we don't have enough space for that in duckdb style doc, since only a few examples can be added. Do you think examples for invalid input are not necessary?

**Comment by BohuTANG** [comment]
@johnhaxx7 We need example and invalid explain, this issue is in low-prority.

**Comment by johnhaxx7** [comment]
Thanks for explanation! I can take this.
