### ISSUE TITLE
Feature: if metasrv start fail print error msg

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#10007]
**Summary**

Feature: if metasrv start fail, then print error msg for fail reason, such as "address already in use" in query server.

**Comment by wzslr321** [comment]
hey @lichuang , I am interested in working on this issue. Could you please provide me with some additional information on how should I tackle this? As of now, I have only found `MetaStartupError` inside `src/meta/types/src/errors/meta_startup_errors.rs`, which I assume is related. I can't find relation to `query server` though. The issue https://github.com/datafuselabs/databend/issues/10193 mentions `meta_node`, which I can find, and which contains most of the aforementioned error references. I am not sure how to proceed further, I'd appreciate a more thorough description.

**Comment by lichuang** [comment]
> hey @lichuang , I am interested in working on this issue. Could you please provide me with some additional information on how should I tackle this? As of now, I have only found `MetaStartupError` inside `src/meta/types/src/errors/meta_startup_errors.rs`, which I assume is related. I can't find relation to `query server` though. The issue #10193 mentions `meta_node`, which I can find, and which contains most of the aforementioned error references. I am not sure how to proceed further, I'd appreciate a more thorough description.

sorry, i test the case, found that this issue has been solved in https://github.com/datafuselabs/databend/pull/11660.
thanks, you could look forward another issues to fix.
