### ISSUE TITLE
bug: the join value is null when use limit 

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#10012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.9.17-nightly-7f532ea(rust-1.68.0-nightly-2023-01-28T16:25:03.956442126Z)

### What's Wrong?

no limit is ok:
![image](https://user-images.githubusercontent.com/35459358/218404469-f558d51f-65b1-4714-864c-4217f8110002.png)

use limit ,the join value "b.name" is null:
![image](https://user-images.githubusercontent.com/35459358/218404651-70a738d9-bbb6-4f3a-a7be-fb5e826abc9b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
What is your deploy mode? Single or Cluster? @WUWEI111222333

**Comment by WUWEI111222333** [comment]
the deploy mode is single

**Comment by xudong963** [comment]
There are some problems with `LimitPushDownJoin` optimization rule.

Btw, I don't suggest using `limit` without `order by`, different databases' output results order may be diff.
