### ISSUE TITLE
[observability] metrics

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1004]
**Summary**

- [ ] shuffle read/write metrics

**Comment by jyz0309** [comment]
Does it mean prometheus metric? If it's, can I try to take this issue? @BohuTANG

**Comment by BohuTANG** [comment]
@jyz0309 right.
You can take the issue by reply:
/assigneme

**Comment by jyz0309** [comment]
Now we have some metric about parser, optimizer, interpreter used time. I think we can add more metrics, and it need more contributors to involve in. So I will cancel my assign(will continue working on it). And welcome other contributors to add. BTW, I think it can be a `good first issue`:)

**Comment by Xuanwo** [comment]
read and write metrics have been added. Let's close.
