### ISSUE TITLE
Feature: internal columns

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#10081]
**Summary**

Description for this feature.

Fuse engine can have some virtual column, it's not in `select *` unless you specify it.

```
row_id
block_name
segment_name
snapshot_name
```

**Comment by xudong963** [comment]
It's useful to support `delete with subquery`

**Comment by leiysky** [comment]
I prefer to call this a `hidden column` or `internal column` rather than `virtual column` since it usually refers to `generated column`.

**Comment by lichuang** [comment]
> I prefer to call this a `hidden column` or `internal column` rather than `virtual column` since it usually refers to `generated column`.

agree

**Comment by sundy-li** [comment]
@lichuang  internal column should have ColumnID, how about make it from `u32::MAX`

**Comment by lichuang** [comment]
> @lichuang internal column should have ColumnID, how about make it from `u32::MAX`

OK

**Comment by sundy-li** [comment]
RowID could be represented by a UInt64 column where the high 32 bits as `BlockID` and the low 32 bits as `row_in_block`
