### ISSUE TITLE
Feature:  list_files table function

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#10126]
**Summary**

compared with `list statement`

- can  naturally use limit、order by,  where clause,  may be useful for **big dir**
    -  e.g. we currently use the `first file` to infer schema  in infer_schema and  `select stage`, but no proper way to know which file is actually used.
- cap use post-process (as subquery), including join (e.g. check/cmp status of 2 file list)

**Comment by xinlifoobar** [comment]
Is this like reading all file names from files_info and returning the result?
https://github.com/datafuselabs/databend/blob/31dfc94fc35e3b92260f1c1a1b68b2f1ed4719a5/src/query/storages/fuse/src/table_functions/infer_schema/table_args.rs

**Comment by youngsofun** [comment]
the result may looks like https://databend.rs/doc/sql-commands/ddl/stage/ddl-show-stages

can accept some param of infer_schema like `pattern`

e.g.

`select * from list_stage('location'=>'stage_or_uri',  pattern= '.*parquet') limit 1`

**Comment by xinlifoobar** [comment]
Got the context.

This is to add the `list_stage` function which has similar to https://databend.rs/doc/sql-commands/ddl/stage/ddl-list-stage but more extended and better integrations.

Can I be assigned?

**Comment by youngsofun** [comment]
you are welcome!  but we need to reach an agreement that we really need it.

cc @BohuTANG @sundy-li @Xuanwo

**Comment by sundy-li** [comment]
We can have it, but it's duplicated with `list @stage:/path`.

So:

1. Could introduce a list_files table function and cover the command list stage.
2. Forward list interpreter into `list_files` table function.

**Comment by xinlifoobar** [comment]
Seems this is doable. Checking the code around there is also another task related to removing the `number_of_files` from the show stages outputs.

https://github.com/datafuselabs/databend/blob/ec61e3af53ec72e313d0f634be81f669fe33a619/src/query/storages/system/src/stages_table.rs#L68

**Comment by xinlifoobar** [comment]
/assignme

Feel free to assign this to me if it is still considered as an imporvement.
