### ISSUE TITLE
feat: change batch remove to opendal batch

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10148]
**Summary**

https://github.com/datafuselabs/databend/blob/786ced7deb4ceffc942af416cc1303c6b21e6e90/src/query/storages/fuse/src/io/files.rs#L39-L76

**Comment by BohuTANG** [comment]
How to convert Operator to BatchOperator here? cc @Xuanwo

**Comment by Xuanwo** [comment]
Let me take this issue~
