### ISSUE TITLE
Feature: numeric constants literal should be parsed as  fixed-point numbers instead of floating-point numbers to avoid losing precision  without notice 

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#10220]
**Summary**

for numeric literal with a point,  two approaches are used most commonly: 

1.  use floating-point as long as there is an  'e'/'E',  used by MySQL, SQL server
2.  use floating-point unless it is too large to fit into decimal (more than 38 digits),  used by PostgreSQL、Impala、snowflake

the second way sounds more reasonable to me.

cc @andylokandy  @sundy-li @BohuTANG

**Comment by BohuTANG** [comment]
Great.

These two examples will work after this issue is solved?
```
mysql> select 58750003716598352816469;
ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.

mysql> select 58750003716598352816469::Decimal(37,0);
ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.
```

**Comment by sundy-li** [comment]
Prefer 2, so we should handle the case of `Literal::BigInt`

**Comment by youngsofun** [comment]
> Great.
> 
> These two examples will work after this issue is solved?
> 
> ```
> mysql> select 58750003716598352816469;
> ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.
> 
> mysql> select 58750003716598352816469::Decimal(37,0);
> ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.
> ```

yes
