### ISSUE TITLE
Better `displayText` name when error

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10253]
**Summary**

```
ERROR 1105 (HY000): Code: 1065, displayText = Unsupported literal value: 58750003716598352816469.
```

It would be better to:
```
ERROR 1105 (HY000): Code: 1065, Text = Unsupported literal value: 58750003716598352816469.
```

**Comment by BohuTANG** [comment]
Hi @rkmdCodes 

Thanks for taking it!

The code line should be:
https://github.com/datafuselabs/databend/blob/c0239ecf74dddfb1333c38d478468a55d4fb9fa4/src/common/exception/src/exception.rs#L168

I am afraid some tests need to be changed as well.

**Comment by haydenflinner** [comment]
As a related topic to this, 500 internal server error is always alarming to see when submitting a streaming upload. But it usually turns out that it's just a column name that's not in the table. 400 would be a better error code for that.
