### ISSUE TITLE
Feature: make regexp initialized at compile time

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#10286]
**Summary**

Description for this feature.

https://github.com/datafuselabs/databend/blob/main/src/query/service/src/servers/federated_helper.rs  will use many regexps to match the query. We can improve this via initializing the regexp at compile time.

**Comment by xinlifoobar** [comment]
/assignme

Something like `
lazy_static! {
    static ref RE: Regex = Regex::new(r"hello (\w+)!").unwrap();
}
` shall work to avoid compiling the regex multiple times.

**Comment by sundy-li** [comment]
Yes, maybe `#[ctor]` could be better. https://docs.rs/ctor/latest/ctor/
