### ISSUE TITLE
Remove Embedded meta

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#10290]
The databend-query includes an embedded meta-service intended mainly for testing purposes. However, its functionality is limited compared to a standalone meta-service; for example, data may be lost when the databend-query server restarts.

Maintaining two implementations of the same API has become a burden and the embedded meta-service does not provide any actual support for databend-query. In fact, it can sometimes confuse users when configuring a databend server.

For quick and easy testing, users can start a real meta-service with the default configuration.

Therefore, it's time to remove the embedded meta-service altogether.

**Comment by drmingdrmer** [comment]
@sundy-li @zhang2014 @BohuTANG

**Comment by sundy-li** [comment]
For me personally, it's OK, but using this can allow developers to only care about one `Databend-Query `process to speed up development and testing.

**Comment by Xuanwo** [comment]
I'm intereted in building an in-memory meta service which will allow:

- Easier testing/evaluating
- Use databend as a lib
- Load meta from somewhere -> do query (read-only serverless!)

**Comment by sundy-li** [comment]
compile  databend on python with `in-memory meta `
```
import databend
...
```
