### ISSUE TITLE
bug: Compact cause OOM on large table

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.9.58

### What's Wrong?
```
 set max_threads=6;set max_storage_io_requests=100;optimize table xx.xx compact
```
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/30121694/222621128-5534755c-38ca-4865-8919-990003831e9c.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhyass** [comment]
@yufan022 https://github.com/datafuselabs/databend/pull/10506 has been merged. You can try if the compact oom problem can be solved.

**Comment by zhyass** [comment]
Closed by https://github.com/datafuselabs/databend/pull/10506
