### ISSUE TITLE
the function version() has some problem 

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#10342]
**Summary**
the deploy mode is single
![d3329f524b9f9557e90302022c4daad7](https://user-images.githubusercontent.com/35459358/222872784-9b0b8680-ae1e-4573-afe1-948912926d77.png)

**Comment by wangjili8417** [comment]
I'd like to work on the issue.

**Comment by arunma** [comment]
To add some details to the issue, this does not work only for the MySQL command line client. When the command is issued from DBeaver, it seems to be alright. 

![image](https://user-images.githubusercontent.com/143679/222879039-43ec0954-f139-43c3-b8fe-66a155fe2fcd.png)

**Comment by sundy-li** [comment]
@ WUWEI111222333

I did not get it, why did the resulting change in the same query ?

**Comment by sundy-li** [comment]
> I'd like to work on the issue.

It's already rewritten to literal in [type checker](https://github.com/datafuselabs/databend/blob/8aa1532ff15d2a6cef99b4d20a2447dbaa6651e8/src/query/sql/src/planner/semantic/type_check.rs)

**Comment by b41sh** [comment]
> @WUWEI111222333
> 
> I did not get it, why did the resulting change in the same query ?

`as` alias does not work, the output is always version(), not the user-specified alias title.

**Comment by WUWEI111222333** [comment]
the difference is the space ,i think...
![微信图片_20230304212153](https://user-images.githubusercontent.com/35459358/222904383-22b737b8-f772-4463-a7d2-74dd56cb691d.png)

**Comment by b41sh** [comment]
> the difference is the space ,i think... !

Both `MySQLFederated` and `ClickHouseFederated` will return version value by regular matching `select version()`, which is different from the return value of the `version` function. This will result in different clients getting different `version` values.

- ClickHouse `8.12.14`
- MySQL `8.0.26-v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
- version function `DatabendQuery v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`

Can we remove the regular matching from both `MySQLFederated` and `ClickHouseFederated`, use the `version` function for all clients? @sundy-li

**Comment by TCeason** [comment]
> > the difference is the space ,i think... !
> 
> 
> 
> Both `MySQLFederated` and `ClickHouseFederated` will return version value by regular matching `select version()`, which is different from the return value of the `version` function. This will result in different clients getting different `version` values.
> 
> 
> 
> - ClickHouse `8.12.14`
> 
> - MySQL `8.0.26-v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> 
> - version function `DatabendQuery v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> 
> 
> 
> Can we remove the regular matching from both `MySQLFederated` and `ClickHouseFederated`, use the `version` function for all clients? @sundy-li 
> 
> 
> 
> @TCeason 
> 
> 
> 
> 

MySQL Fed is hard code with 8.0.26 because some gui will judge MySQL version. 

So the version() is a temp value to pass gui use MySQL driver connect to Databend query.

**Comment by b41sh** [comment]
> > > the difference is the space ,i think... !
> > 
> > 
> > Both `MySQLFederated` and `ClickHouseFederated` will return version value by regular matching `select version()`, which is different from the return value of the `version` function. This will result in different clients getting different `version` values.
> > 
> > * ClickHouse `8.12.14`
> > * MySQL `8.0.26-v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> > * version function `DatabendQuery v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> > 
> > Can we remove the regular matching from both `MySQLFederated` and `ClickHouseFederated`, use the `version` function for all clients? @sundy-li
> > @TCeason
> 
> MySQL Fed is hard code with 8.0.26 because some gui will judge MySQL version.
> 
> So the version() is a temp value to pass gui use MySQL driver connect to Databend query.

@TCeason  Can we remove the version regular match from `MySQLFederated` and `ClickHouseFederated`? Instead, return a different version value in the `version` function based on the type of `SessionType`. This would ensure that the same client calling `version` function in different ways would get the same return value.

**Comment by TCeason** [comment]
> > > > the difference is the space ,i think... !
> 
> > > 
> 
> > > 
> 
> > > Both `MySQLFederated` and `ClickHouseFederated` will return version value by regular matching `select version()`, which is different from the return value of the `version` function. This will result in different clients getting different `version` values.
> 
> > > 
> 
> > > * ClickHouse `8.12.14`
> 
> > > * MySQL `8.0.26-v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> 
> > > * version function `DatabendQuery v0.4.1-alpha-ee44cc6(rust-1.68.0-nightly-2023-03-04T09:33:30.594399Z)`
> 
> > > 
> 
> > > Can we remove the regular matching from both `MySQLFederated` and `ClickHouseFederated`, use the `version` function for all clients? @sundy-li
> 
> > > @TCeason
> 
> > 
> 
> > MySQL Fed is hard code with 8.0.26 because some gui will judge MySQL version.
> 
> > 
> 
> > So the version() is a temp value to pass gui use MySQL driver connect to Databend query.
> 
> 
> 
> @TCeason  Can we remove the version regular match from `MySQLFederated` and `ClickHouseFederated`? Instead, return a different version value in the `version` function based on the type of `SessionType`. This would ensure that the same client calling `version` function in different ways would get the same return value.
> 
> 

I think that's ok. cc@bohutang
