### ISSUE TITLE
bug: 1007: nested type Array(Nullable(String)) cannot be nullable

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10344]
**Summary**

```
CREATE TABLE t1 AS  SELECT * FROM @infer_parquet_decoded/a.parquet limit 0;
```

a.parquet has a `Array(Nullable(String))` type, but Databend does not handle it well:
```
Oops! Something went wrong.
1007: nested type Array(Nullable(String)) cannot be nullable
```

cc @b41sh @youngsofun

**Comment by b41sh** [comment]
Because of a previous bug with `Arrow2` reading and writing nullable nested types, we add a restriction on allowing users to create nullable nested types. Now that `Arrow2` has fixed this bug, we seem to be able to remove this restriction.
