### ISSUE TITLE
Feature: start databend-meta fail without any hint

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#10355]
**Summary**
Howto repeat:

```
# wget https://repo.databend.rs/databend/v1.0.3-nightly/databend-v1.0.3-nightly-x86_64-unknown-linux-musl.tar.gz
# mkdir local_10 & cd local_10
# tar zxvf ../databend-v1.0.3-nightly-x86_64-unknown-linux-musl.tar.gz
# bin/databend-meta --config-file=configs/databend-meta.toml
# ps axu |grep databend
wu         58103  0.0  0.0  12116   720 pts/4    S+   10:53   0:00 grep --color=auto databend
```

Actual logdir, raft_dir not create inf config  file databend-meta.toml 

Expect:
Please report 
- Permission denied 
- logdir, raft_dir not exist

**Comment by drmingdrmer** [comment]
When there is a panic,  our `panic_hook` tries to output panic information to logs.
But when the panic is raised when initializing logging, nothing will be output.

To fix this, the `panic_hook` should also output a message to stderr.
