### ISSUE TITLE
Feature: replace thrift client with volo-thrift

### ISSUE THREAD

**Issue by PureWhiteWu** [datafuselabs/databend#10386]
**Summary**

Databend is using the official apache thrift rust implementation, which seems can only support sync rust and is somehow lack of maintenance. This issue propose to replace it with Volo-Thrift.

Volo is a high-performance and strong-extensibility RPC framework which supports both thrift and grpc in pure rust (includes the compiler and code generator), and supports much more features than the official implementation.

The most significant two benefits to switch to Volo-Thrift is:
1. doesn't need to depend on `thrift` cli, everything is implemented in pure rust and the code generator can be used via build.rs;
2. supports async

Furthermore, Volo is highly optimized for performance, switch to volo may also gain in performance. Volo itself is a community-driven project, all contributions are welcomed. We have also used it in our production environment, so there's no need to doubt for its stability and the follow-up maintenance.

Here's some more detailed information about Volo:
- github: https://github.com/cloudwego/volo
- tutorial: https://www.cloudwego.io/zh/docs/volo/volo-thrift/getting-started/

**Comment by Xuanwo** [comment]
implemented!
