### ISSUE TITLE
improvement: Add Operator cache to avoid building everytime during stage creation

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10397]
**Summary**

When creating an external stage:
```
CREATE STAGE my_s3_stage URL='s3://load/files/' CONNECTION = (ACCESS_KEY_ID = '<your-access-key-id>' SECRET_ACCESS_KEY = '<your-secret-access-key>');
```
We should detect the CONNECTION REGION and save it to StageInfo in the metasrv.

cc @Xuanwo

**Comment by Xuanwo** [comment]
We can add a memory cache `HashMap<StorageParams, Operator>` for operators so that we don't need to build them everytime.

cc @sundy-li for comments.

**Comment by Xuanwo** [comment]
This will add a gloabl locking for runtime, seems not useful.
