### ISSUE TITLE
bug: incorrect snapshot stats after clone to a new table

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#10406]
**Summary**

```

CREATE TABLE `tt` (
  `Time` TIMESTAMP,
) ENGINE=FUSE TRANSIENT='T' ;


insert into tt(`Time`) select now() from numbers(100);

set hide_options_in_show_create_table = 0;

show create table tt; --- and get the SNAPSHOT_LOCATION

CREATE TABLE `tt_v2` (
  `Time` TIMESTAMP,
) ENGINE=FUSE COMPRESSION='lz4' SNAPSHOT_LOCATION='xxxxx';


select count(1) from tt_v2;  -- it's zero, related to empty stats 

explain select count(1) from tt_v2; 
 
```

**Comment by TCeason** [comment]
Get

**Comment by TCeason** [comment]
The table tt_v2 has option with key equal SNAPSHOT_LOCATION.

But in interpreter build request to generate create table req: https://github.com/datafuselabs/databend/blob/11091fb628ca980b30e4e32c368dc4c11e5bacf2/src/query/service/src/interpreters/interpreter_table_create.rs#L180

The statistics is Default::default().

So the bind_base_table will get default

https://github.com/datafuselabs/databend/blob/7183ac6f77c7a2fb12b8a3f17dd4fa7d4d04db21/src/query/sql/src/planner/binder/table.rs#L517

https://github.com/datafuselabs/databend/blob/0113994a876b29a582db2e9a6cecade8caf65bf2/src/query/storages/fuse/src/fuse_table.rs#L529

So I want to modify to this:

```rust
    async fn table_statistics(&self) -> Result<Option<TableStatistics>> {
        let res = if let Some(snapshot) = self.read_table_snapshot().await? {
            Some(
                TableStatistics {
                    num_rows: Some(snapshot.summary.row_count),
                    data_size: Some(snapshot.summary.uncompressed_byte_size),
                    data_size_compressed: Some(snapshot.summary.compressed_byte_size),
                    index_size: Some(snapshot.summary.index_size),
                }
            )
        } else {
            let s = self.table_info.meta.statistics.clone();
            Some(TableStatistics {
                num_rows: Some(s.number_of_rows),
                data_size: Some(s.data_bytes),
                data_size_compressed: Some(s.compressed_data_bytes),
                index_size: Some(s.index_data_bytes),
            })
        };
        Ok(res)
    }
```

But bind_base_table already use `table.table().column_statistics_provider()`.
https://github.com/datafuselabs/databend/blob/7183ac6f77c7a2fb12b8a3f17dd4fa7d4d04db21/src/query/sql/src/planner/binder/table.rs#L476

So it maybe not safe

```
error: future cannot be sent between threads safely
   --> src/query/sql/src/planner/binder/binder.rs:87:5
    |
87  |     #[async_recursion::async_recursion]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: the trait `Send` is not implemented for `dyn ColumnStatisticsProvider`
note: future is not `Send` as this value is used across an await
   --> src/query/sql/src/planner/binder/table.rs:517:52
    |
476 |         let statistics_provider = table.table().column_statistics_provider().await?;
    |             ------------------- has type `Box<dyn ColumnStatisticsProvider>` which is not `Send`
...
517 |         let stat = table.table().table_statistics().await?;
    |                                                    ^^^^^^ await occurs here, with `statistics_provider` maybe used later
...
547 |     }
    |     - `statistics_provider` is later dropped here
    = note: required for the cast from `[async block@src/query/sql/src/planner/binder/binder.rs:87:5: 87:40]` to the object type `dyn std::future::Future<Output = Result<planner::plans::plan::Plan, ErrorCode>> + Send`
    = note: this error originates in the attribute macro `async_recursion::async_recursion` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by TCeason** [comment]
By the way

```sql
mysql> drop table tt;
drop table tt_v2;
CREATE TABLE `tt` (
  `Time` TIMESTAMP
) ENGINE=FUSE ;


insert into tt(`Time`) select now() from numbers(100);

set hide_options_in_show_create_table = 0;

show create table tt; 
Query OK, 0 rows affected (0.08 sec)

Query OK, 0 rows affected (0.10 sec)

Query OK, 0 rows affected (0.13 sec)

Query OK, 100 rows affected (0.15 sec)

Query OK, 0 rows affected (0.01 sec)

+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                           |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tt    | CREATE TABLE `tt` (
  `Time` TIMESTAMP
) ENGINE=FUSE COMPRESSION='lz4' SNAPSHOT_LOCATION='1/4569/_ss/cb75cee1fee44f939fcdeafc5dc7cc76_v2.json' STORAGE_FORMAT='native' |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.05 sec)
Read 0 rows, 0.00 B in 0.034 sec., 0 rows/sec., 0.00 B/sec.


mysql> CREATE TABLE `tt_v2` (
  `Time` TIMESTAMP
) ENGINE=FUSE COMPRESSION='lz4' SNAPSHOT_LOCATION='1/4569/_ss/cb75cee1fee44f939fcdeafc5dc7cc76_v2.json';
Query OK, 0 rows affected (0.15 sec)

mysql> show create table tt_v2;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                              |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tt_v2 | CREATE TABLE `tt_v2` (
  `Time` TIMESTAMP
) ENGINE=FUSE COMPRESSION='lz4' SNAPSHOT_LOCATION='1/4569/_ss/cb75cee1fee44f939fcdeafc5dc7cc76_v2.json' STORAGE_FORMAT='native' |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.06 sec)
Read 0 rows, 0.00 B in 0.041 sec., 0 rows/sec., 0.00 B/sec.

mysql> explain select * from tt_v2 order by Time;
ERROR 1105 (HY000): Code: 1065, displayText = error: 
  --> SQL:1:38
  |
1 | explain select * from tt_v2 order by Time
  |                                      ^^^^ column time doesn't exist

```

**Comment by TCeason** [comment]
> The table tt_v2 has option with key equal SNAPSHOT_LOCATION.
> 
> But in interpreter build request to generate create table req:
> 
> https://github.com/datafuselabs/databend/blob/11091fb628ca980b30e4e32c368dc4c11e5bacf2/src/query/service/src/interpreters/interpreter_table_create.rs#L180
> 
> The statistics is Default::default().
> 
> So the bind_base_table will get default
> 
> https://github.com/datafuselabs/databend/blob/7183ac6f77c7a2fb12b8a3f17dd4fa7d4d04db21/src/query/sql/src/planner/binder/table.rs#L517
> 
> https://github.com/datafuselabs/databend/blob/0113994a876b29a582db2e9a6cecade8caf65bf2/src/query/storages/fuse/src/fuse_table.rs#L529
> 
> So I want to modify to this:
> 
> ```rust
>     async fn table_statistics(&self) -> Result<Option<TableStatistics>> {
>         let res = if let Some(snapshot) = self.read_table_snapshot().await? {
>             Some(
>                 TableStatistics {
>                     num_rows: Some(snapshot.summary.row_count),
>                     data_size: Some(snapshot.summary.uncompressed_byte_size),
>                     data_size_compressed: Some(snapshot.summary.compressed_byte_size),
>                     index_size: Some(snapshot.summary.index_size),
>                 }
>             )
>         } else {
>             let s = self.table_info.meta.statistics.clone();
>             Some(TableStatistics {
>                 num_rows: Some(s.number_of_rows),
>                 data_size: Some(s.data_bytes),
>                 data_size_compressed: Some(s.compressed_data_bytes),
>                 index_size: Some(s.index_data_bytes),
>             })
>         };
>         Ok(res)
>     }
> ```
> 
> But bind_base_table already use `table.table().column_statistics_provider()`.
> 
> https://github.com/datafuselabs/databend/blob/7183ac6f77c7a2fb12b8a3f17dd4fa7d4d04db21/src/query/sql/src/planner/binder/table.rs#L476
> 
> So it maybe not safe
> 
> ```
> error: future cannot be sent between threads safely
>    --> src/query/sql/src/planner/binder/binder.rs:87:5
>     |
> 87  |     #[async_recursion::async_recursion]
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
>     |
>     = help: the trait `Send` is not implemented for `dyn ColumnStatisticsProvider`
> note: future is not `Send` as this value is used across an await
>    --> src/query/sql/src/planner/binder/table.rs:517:52
>     |
> 476 |         let statistics_provider = table.table().column_statistics_provider().await?;
>     |             ------------------- has type `Box<dyn ColumnStatisticsProvider>` which is not `Send`
> ...
> 517 |         let stat = table.table().table_statistics().await?;
>     |                                                    ^^^^^^ await occurs here, with `statistics_provider` maybe used later
> ...
> 547 |     }
>     |     - `statistics_provider` is later dropped here
>     = note: required for the cast from `[async block@src/query/sql/src/planner/binder/binder.rs:87:5: 87:40]` to the object type `dyn std::future::Future<Output = Result<planner::plans::plan::Plan, ErrorCode>> + Send`
>     = note: this error originates in the attribute macro `async_recursion::async_recursion` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

cc @dantengsky

**Comment by dantengsky** [comment]
about compile error, try to add the `Send` constraint to the trait?

~~~.rust
 trait ColumnStatisticsProvider where Self: Send
{
    ...
}

~~~

**Comment by dantengsky** [comment]
`async fn column_statistics_provider(&self) -> Result<Box<dyn ColumnStatisticsProvider + Send>>` may be ok as well, but seems to need more code refactoring.
