### ISSUE TITLE
CI: Enable ` -Zgitoxide` to speed our git deps download speed

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#10466]
**Summary**

`-Zgitoxide` is the cargo's integration with [gitoxide](https://github.com/Byron/gitoxide): An idiomatic, lean, fast & safe pure Rust implementation of Git.

It's much faster than calling `git`:

[![asciicast](https://asciinema.org/a/542159.svg)](https://asciinema.org/a/542159)

We can enable it to speed up our git deps downloading!

Should wait for our next toolchain bump.

**Comment by infdahai** [comment]
I get the info from wechat's article. could I ask whether this task is changed to `gix` where `git clone` is called?

**Comment by Xuanwo** [comment]
> could I ask whether this task is changed to `gix` where `git clone` is called?

Thank you for your interest! This task simply requires enabling `-Zgitoxide` for the cargo command and measuring the difference between them. We want to know how much will it faster than `git`.
