### ISSUE TITLE
[CBO] add min/max scalar value to plan Statistics

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1046]
**Summary**
Add min/max to Statistics:
https://github.com/datafuselabs/datafuse/blob/9de3e9b90a8f893de0bee84b3ed1989619e458d5/common/planners/src/plan_statistics.rs#L5-L13

This is for #997

**Comment by wangzhen11aaa** [comment]
Let me Try.

**Comment by wangzhen11aaa** [comment]
Hi,all , Is min/max the function like max/min(column) or is a member we will defined in the Statistics struct?

**Comment by BohuTANG** [comment]
> Hi,all , Is min/max the function like max/min(column) or a member we will defined in the Statistics struct?

max/min here in `Statistics struct` should be a DataValue, they are used for the store underlying to set if they are exact, then the quey check the `is_exact` to use them or not.

**Comment by wangzhen11aaa** [comment]
![image](https://user-images.githubusercontent.com/7311971/127473877-0b981103-e99d-4d85-aca2-2adcc4cd7cf0.png)

Maybe, I want to get more information. Whether this demand relate to the picture above? Can we discuss it a bit?

**Comment by BohuTANG** [comment]
@wangzhen11aaa 

From your image, I think it's more talking about join not related to this issue.
So, could you tell more what your want ,)

**Comment by wangzhen11aaa** [comment]
I mean the max/min, from the name, it is the value compared or to be used for comparing. From this point, I link this to the query selection problem. While, If not that meaning, what's the meaning of  these two members?

**Comment by wangzhen11aaa** [comment]
> @wangzhen11aaa
> 
> From your image, I think it's more talking about join not related to this issue.
> So, could you tell more what your want ,)

I mean the max/min, from the name, it is the value compared or to be used for comparing. From this point, I link this to the query selection problem. While, If not that meaning, what's the meaning of these two members?

**Comment by BohuTANG** [comment]
Well, the max/min can be set from the data source(such as fusestore) if the is_exact is true.
For example:
```
select max(number) from numbers_mt(100000000) where number > 10000 and number < 20001;
```
So, the ReadDataSourcePlan can set his statistics.max to `20000` by number source on underlying.
Then, we can get the max value from the statistics do not need to read the data and do computing.
See https://github.com/datafuselabs/datafuse/pull/960

**Comment by wangzhen11aaa** [comment]
> Well, the max/min can be set from the data source(such as fusestore) if the is_exact is true.
> For example:
> 
> ```
> select max(number) from numbers_mt(100000000) where number > 10000 and number < 20001;
> ```
> 
> So, the ReadDataSourcePlan can set his statistics.max to `20000` by number source on underlying.
> Then, we can get the max value from the statistics do not need to read the data and do computing.
> See #960

Hi, I have read all the discussions about min/max,  in these contexts, by now, I can only know about that we maybe want to set 
min/max value in the ReadDataSourcePlan only for count(*). 

from code optimizer_statistics_exact.rs 
`            ) if op == "count" && args.len() == 1 => match (&args[0], input.as_ref()) {
                (Expression::Literal { .. }, PlanNode::ReadSource(read_source_plan)
`
I can find that the input is set by set_input() function  in AggregationPartialPlan struct.
`
    pub fn set_input(&mut self, node: &PlanNode) {
        self.input = Arc::new(node.clone());
    }
`
Does the min/max value be set in PlanNode?

Thanks.

**Comment by wangzhen11aaa** [comment]
If this task takes too long, tell me, I may be find some other to do. )

**Comment by BohuTANG** [comment]
> If this task takes too long, tell me, I may be find some other to do. )
That's ok, we can do this later.

**Comment by wangzhen11aaa** [comment]
> > If this task takes too long, tell me, I may be find some other to do. )
> 
> That's ok, we can do this later.

Is my idea right? The idea is that we need to set min/max in the PlanNode.

**Comment by wangzhen11aaa** [comment]
> > If this task takes too long, tell me, I may be find some other to do. )
> 
> That's ok, we can do this later.

ok

**Comment by BohuTANG** [comment]
> > > If this task takes too long, tell me, I may be find some other to do. )
> > 
> > 
> > That's ok, we can do this later.
> 
> Is my idea right? The idea is that we need to set min/max in the PlanNode. When set this member, so we do not scan the data from some source, then we can compute faster on count(*) or count(0)? What's that for?

Here is a example:
https://github.com/BohuTANG/datafuse/commit/bf8b5ee84f8f829aebd30b8fa258fefd4c1498a8

we can set min/max/count from the datasource, and check them in the optimizer.
if the query is extra with: `select count(number)/min(number)/max(number) from numbers_mt`, we can use the extra directly.

**Comment by wangzhen11aaa** [comment]
> set m

Ok, I will rethink it again.

**Comment by wangzhen11aaa** [comment]
> > > > If this task takes too long, tell me, I may be find some other to do. )
> > > 
> > > 
> > > That's ok, we can do this later.
> > 
> > 
> > Is my idea right? The idea is that we need to set min/max in the PlanNode. When set this member, so we do not scan the data from some source, then we can compute faster on count(*) or count(0)? What's that for?
> 
> Here is a example:
> [BohuTANG@bf8b5ee](https://github.com/BohuTANG/datafuse/commit/bf8b5ee84f8f829aebd30b8fa258fefd4c1498a8)
> 
> we can set min/max/count from the datasource, and check them in the optimizer.
> if the query is extra with: `select count(number)/min(number)/max(number) from numbers_mt`, we can use the extra directly.

I think i know this idea, We get this value from the query itself. 
Query->Statements->Plan-> .Set(Statistics in read_plan function). ->.

**Comment by wangzhen11aaa** [comment]
Hi, I came back again.
