### ISSUE TITLE
testing: add long run tests in weekly builds

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#10473]
**Summary**

Currently, Databend's CI tests only cover some basic functionality and do not include testing with large datasets. However, running all tests for each commit is resource-intensive, so we need a long-run test that can be executed on a weekly basis..

Here are some proposed guidelines for this test:

1. We can continue to use current testing frameworks such as SQLlogictest and Databend-test.
2. Only run the test on the release version for x86-64.
3. Cover mainstream datasets such as `hits`, `tpch100`, `ontime` (preferably over 10GB in size).
4. Cover basic data workflows, such as copy into, select, compaction, optimize, alter, delete, and update.

**Comment by TCeason** [comment]
Now we support cloud/loacl benchmark. So maybe we can close this issue?
