### ISSUE TITLE
bug: Query information_schema.COLUMNS is slow

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10489]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.0.9

### What's Wrong?

SELECT 
COLUMN_NAME,
COLUMN_TYPE,
CHARACTER_SET_NAME,
IS_NULLABLE,
COLUMN_KEY,
COLUMN_DEFAULT,
EXTRA,
COLUMN_COMMENT FROM information_schema.COLUMNS
WHERE
  TABLE_SCHEMA = 'xx'
  AND TABLE_NAME = 'xx'
ORDER BY ORDINAL_POSITION;

+-------------------+-----------------+--------------------+-------------+------------+----------------+-------+----------------+
| column_name       | column_type     | character_set_name | is_nullable | column_key | column_default | extra | column_comment |
+-------------------+-----------------+--------------------+-------------+------------+----------------+-------+----------------+
| xx           | BIGINT UNSIGNED |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
| xx         | VARCHAR         |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
| xx           | VARCHAR         |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
..
| xx      | BIGINT UNSIGNED |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
| xx     | BIGINT UNSIGNED |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
..
| xx   | VARCHAR         |               NULL | YES         |       NULL |           NULL |  NULL |           NULL |
+-------------------+-----------------+--------------------+-------------+------------+----------------+-------+----------------+
22 rows in set (15.05 sec)

MySQL [(none)]> select count(1) from information_schema.COLUMNS;
+----------+
| count(1) |
+----------+
|    10179 |
+----------+
1 row in set (7.30 sec)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
This is fixed by https://github.com/datafuselabs/databend/pull/10624
