### ISSUE TITLE
bug: long time spent in beginning of `COPY INTO`

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.0.9

### What's Wrong?

| id                                   | type  | host                | user  | command | database | extra_info                                                                                                                                                                             | memory_usage | data_read_bytes | data_write_bytes | scan_progress_read_rows | scan_progress_read_bytes | mysql_connection_id | time | status |
ac8ee750-c404-4707-811c-dedf8986a105    MySQL   xx:xx     write   Query   default COPY INTO xx from @xx pattern='.*[.]csv$' FILE_FORMAT = (TYPE = 'CSV' FIELD_DELIMITER = '\\t' RECORD_DELIMITER = '\\n') PURGE=true       -242324186      0       0       0       0       9       3482

scan_progress_read_rows=0, It seems that too much time was spent in the list on s3. There are about 100000 files in S3.

100000/3482=28/s

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
v1.0.10:
```
list @stage;

....

195329 rows in set (8.42 sec)
```

23198.2185273 files per second of the list.

**Comment by BohuTANG** [comment]
Just test list a million files:
```
1171905 rows in set (1 min 18.59 sec)
```
list @bomb;
... ...
14834 files per second.

The files generated by:
```
create stage bomb;
copy into @bomb from (select * from numbers(1000000000)) file_format=(type=parquet) max_file_size=32;
```

**Comment by yufan022** [comment]
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/30121694/224382552-651bb95f-1871-49ea-9f83-5f57e34190bd.png">
If there are many files in S3, it will take a long time(more than 3000 seconds) then  SCAN_PROGRESS_ROWS will start to grow.

Is that normal?

**Comment by BohuTANG** [comment]
It seems to purge the file is not in batch in this COPY statement, it's one by one, and it takes time.

**Comment by BohuTANG** [comment]
> It seems to purge the file cost time.
> 
> Just did a test, if we delete 97664 files, it took 11 min 49.74 sec:
> 
> ```
> list @bomb;
> 97664 rows in set (6.43 sec)
> 
> remove @bomb;
> Query OK, 0 rows affected (11 min 49.74 sec)
> ```

Oh, I test it using `remove @stage`, the code is not the same as `COPY ... purge=true`.
With this patch:
https://github.com/datafuselabs/databend/pull/10499

It's fast enough:
```
list @bomb;
97664 rows in set (4.40 sec)

mysql> remove @bomb;
Query OK, 0 rows affected (33.12 sec)
```
But we can make it faster in parallel batch delete.

**Comment by yufan022** [comment]
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/30121694/224465525-b2f2b7a1-095a-45bc-ab68-832123eaa897.png">

take a long time to start scan. At first of execution, not in the end.

**Comment by yufan022** [comment]
list stage 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/30121694/224488405-c2e73fa0-3eea-4d69-ad15-80e7565de0b2.png">


but copy:
![image](https://user-images.githubusercontent.com/30121694/224488409-6eeaf679-5444-4f3c-aed0-85b950c966bf.png)
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/30121694/224488416-4b0a9458-da0d-46a6-b5f1-5178416451c0.png">
SCAN_PROGRESS_ROWS took a long time to start to grow.

**Comment by BohuTANG** [comment]
If the stage has many files, to check whether the file copied or not, the meta API is not in batch:
https://github.com/datafuselabs/databend/blob/ade74d6cc3cd5736ef900452ecddc90efca241c9/src/meta/api/src/schema_api_impl.rs#L1834-L1845

We will improve it to batch.

cc @drmingdrmer

**Comment by BohuTANG** [comment]
```
2023-03-12T09:51:52.376764Z  INFO databend_query::interpreters::interpreter_copy: status: "begin to color copied files"
    at src/query/service/src/interpreters/interpreter_copy.rs:306

  2023-03-12T09:51:59.026306Z  INFO databend_query::interpreters::interpreter_copy: status: "end to color copied files: 292992"
    at src/query/service/src/interpreters/interpreter_copy.rs:322
```

**Comment by BohuTANG** [comment]
stage files `get_splits` slow too, need to improve.

**Comment by BohuTANG** [comment]
@yufan022 

To solve this issue, we did these improvements:
1. https://github.com/datafuselabs/databend/pull/10514 improve the parquet format and get splits
2. https://github.com/datafuselabs/databend/pull/10512 to fast check copied files or not from metasrv in batch
3. https://github.com/datafuselabs/databend/pull/10509 to fast write copied files to metasrv in batch
