### ISSUE TITLE
Feature: add pivot/unpivot function like duckdb

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#10498]
**Summary**
pivot move many rows value into many columns, regards values as columns names
unpivot move many columns  value into many rows , regards columns names  as values  
Description for this feature.

ref https://github.com/duckdb/duckdb/pull/6387#issuecomment-1462364955

**Comment by sundy-li** [comment]
That's a powerful feature, the internal implementation is to:

1. Pivot:  Rewrite SQL using `groupby` and `aggregate if` combinators
2. Unpivot: Rewrite SQL using `UNNEST ` .
