### ISSUE TITLE
bug: databend don't support DECIMAL type for external hive table

### ISSUE THREAD

**Issue by daimashusheng** [datafuselabs/databend#10542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

| version()                                                                                                           |
+---------------------------------------------------------------------------------------------------------------------+
| 8.0.26-v1.0.14-nightly-7c2bcffcf38f253755f8fcdff859a6ecd2279a72(rust-1.70.0-nightly-2023-03-13T11:37:12.318061749Z) |

### What's Wrong?

when I select data from external hive table, databend return "Unsupported data type: DECIMAL(7,2)."

### How to Reproduce?

1. compiling code with param --features hive so that databend support external hive table
2. add [catalogs.hive] configs to databend-query.toml, then start databend-query
3. run a select sql with mysql client connecting databend

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Hive and iceberg need to do mapping with decimal types.
