### ISSUE TITLE
bug: Error occurred while querying the large table

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.0.10

### What's Wrong?

<img width="886" alt="image" src="https://user-images.githubusercontent.com/30121694/224878643-0df0db33-70fe-48fa-9446-14b241049c23.png">
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/30121694/224878818-6ea74a7b-ab05-414e-86bb-d66880c540de.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Please reduce the `max_storage_io_requests` to prevent frequent triggering of AWS S3's slowdowns.

**Comment by yufan022** [comment]
set max_storage_io_requests=64, it's working.
