### ISSUE TITLE
bug: group by to_start_of_five_minutes cause oom

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10586]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.0.14

### What's Wrong?

```
select count(*) from (SELECT uri,ip, count(1) AS cnt FROM time WHERE xx>='2023-02-20 00:00:00' and time < '2023-02-21 00:00:00' GROUP BY uri,ip);
+----------+
| count(*) |
+----------+
|  1205390 |
+----------+
1 row in set (2 min 13.76 sec)
```

group by uri,ip it's ok, group by uri,ip,to_start_of_five_minutes(time) will cause OOM

c5n.9xlarge*5
```
SELECT uri,ip,to_start_of_five_minutes(time) AS five,count(1) AS cnt FROM xx WHERE timestamp>='2023-02-20 00:00:00' and timestamp < '2023-02-21 00:00:00' GROUP BY uri,ip,five;
```

Have to narrow down the time range.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
now group aggregation support out-of-core.
