### ISSUE TITLE
Feature: quantile support list and add functions kurtosis() and skewness()

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#10589]
**Summary**

quantile (list1) returns a list of quantile values with different postions in list1

ref https://duckdb.org/docs/sql/aggregates

**Comment by l1t1** [comment]
why the example of doc ( https://databend.rs/doc/sql-functions/aggregate-functions/aggregate-quantile ) doesn't work? 
```
Server version: 8.0.26-v1.0.8-nightly-70d400a68490ba0e8ad01daa38186ca60c61e573(rust-1.68.0-nightly-2023-03-09T09:44:01.735541531Z) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.


MySQL [(none)]> SELECT QUANTILE(0.6)(number) FROM numbers(10000);
ERROR 1105 (HY000): Code: 1008, displayText = error:
  --> SQL:1:8
  |
1 | SELECT QUANTILE(0.6)(number) FROM numbers(10000)
  |        ^^^^^^^^^^^^^^^^^^^^^ No function matches the given name: quantile
```

**Comment by l1t1** [comment]
duckdb
```sql
D select quantile(i,[0.25,0.5,0.75])from range(1,101)t(i);
┌───────────────────────────────────────────────┐
│ quantile(i, main.list_value(0.25, 0.5, 0.75)) │
│                    int64[]                    │
├───────────────────────────────────────────────┤
│ [25, 50, 75]                                  │
└───────────────────────────────────────────────┘
```

**Comment by wubx** [comment]
The function quantile first pr at Databend v1.0.10. If you want to use quantile please upgrade to Databend-v1.0.18.
It just need to replace databend-query.

**Comment by l1t1** [comment]
quantile_cont is useful too
<html>
<body>


quantile_cont(x,pos) | Returns the intepolated quantile number between 0 and 1 . If pos is a LIST of FLOATs, then the result is a LIST of the corresponding intepolated quantiles.
-- | --



</body>
</html>

**Comment by sundy-li** [comment]
It's an easy task now. Someone interested in it could take this task.

**Comment by l1t1** [comment]
duckdb vs excel 
```
D select quantile_cont(i,[0.25,0.5,0.75])from range(22)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [5.25, 10.5, 15.75]                                │
└────────────────────────────────────────────────────┘

D select quantile_cont(i,[0.25,0.5,0.75])from range(23)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [5.5, 11.0, 16.5]                                  │
└────────────────────────────────────────────────────┘

D select quantile_cont(i,[0.25,0.5,0.75])from range(24)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [5.75, 11.5, 17.25]                                │
└────────────────────────────────────────────────────┘

D select quantile_cont(i,[0.25,0.5,0.75])from range(25)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [6.0, 12.0, 18.0]                                  │
└────────────────────────────────────────────────────┘
```
![quan](https://user-images.githubusercontent.com/23301704/225816259-4a6cef28-e3e6-4f11-9bbe-b124b307fd18.png)

https://zhuanlan.zhihu.com/p/79461597

**Comment by l1t1** [comment]
quantile  value of databend is diffent from duckdb
```
dd:root@localhost/default=> select quantile(0.25)(number)q1,quantile(0.5)(number)q2,quantile(0.75)(number)q3 from numbers(21);
 q1 | q2 | q3
----+----+----
 5  | 10 | 15
(1 row)

dd:root@localhost/default=> select quantile(0.25)(number)q1,quantile(0.5)(number)q2,quantile(0.75)(number)q3 from numbers(22);
 q1 | q2 | q3
----+----+----
 5  | 10 | 15
(1 row)

dd:root@localhost/default=> select quantile(0.25)(number)q1,quantile(0.5)(number)q2,quantile(0.75)(number)q3 from numbers(23);
 q1 | q2 | q3
----+----+----
 5  | 11 | 16
(1 row)

dd:root@localhost/default=> select quantile(0.25)(number)q1,quantile(0.5)(number)q2,quantile(0.75)(number)q3 from numbers(24);
 q1 | q2 | q3
----+----+----
 5  | 11 | 17
(1 row)
```
duckdb
···
D select quantile(i,[0.25,0.5,0.75])from range(1,22)t(i);
┌───────────────────────────────────────────────┐
│ quantile(i, main.list_value(0.25, 0.5, 0.75)) │
│                    int64[]                    │
├───────────────────────────────────────────────┤
│ [6, 11, 16]                                   │
└───────────────────────────────────────────────┘
D select quantile(i,[0.25,0.5,0.75])from range(1,23)t(i);
┌───────────────────────────────────────────────┐
│ quantile(i, main.list_value(0.25, 0.5, 0.75)) │
│                    int64[]                    │
├───────────────────────────────────────────────┤
│ [6, 11, 17]                                   │
└───────────────────────────────────────────────┘
D select quantile(i,[0.25,0.5,0.75])from range(1,24)t(i);
┌───────────────────────────────────────────────┐
│ quantile(i, main.list_value(0.25, 0.5, 0.75)) │
│                    int64[]                    │
├───────────────────────────────────────────────┤
│ [6, 12, 18]                                   │
└───────────────────────────────────────────────┘
D select quantile(i,[0.25,0.5,0.75])from range(1,25)t(i);
┌───────────────────────────────────────────────┐
│ quantile(i, main.list_value(0.25, 0.5, 0.75)) │
│                    int64[]                    │
├───────────────────────────────────────────────┤
│ [6, 12, 18]                                   │
└───────────────────────────────────────────────┘
···

**Comment by l1t1** [comment]
some discuss of quantile https://zhuanlan.zhihu.com/p/79461597 https://zhuanlan.zhihu.com/p/235345817

**Comment by l1t1** [comment]
the duckdb quantile_cont values equals Excel quartile
```
D select quantile_cont(i,[0.25,0.5,0.75])from range(1,22)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [6.0, 11.0, 16.0]                                  │
└────────────────────────────────────────────────────┘
D select quantile_cont(i,[0.25,0.5,0.75])from range(1,23)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [6.25, 11.5, 16.75]                                │
└────────────────────────────────────────────────────┘
D select quantile_cont(i,[0.25,0.5,0.75])from range(1,24)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [6.5, 12.0, 17.5]                                  │
└────────────────────────────────────────────────────┘
D select quantile_cont(i,[0.25,0.5,0.75])from range(1,25)t(i);
┌────────────────────────────────────────────────────┐
│ quantile_cont(i, main.list_value(0.25, 0.5, 0.75)) │
│                      double[]                      │
├────────────────────────────────────────────────────┤
│ [6.75, 12.5, 18.25]                                │
└────────────────────────────────────────────────────┘
```
![quan](https://user-images.githubusercontent.com/23301704/225820228-e218aa7d-9c88-4bba-9bcb-ea80a0842b4c.png)

**Comment by l1t1** [comment]
I found the doc has changed to QUANTILE_CONT() , and the quantile funtion is disappeared. please recover the quantile funciton.
https://databend.rs/doc/sql-functions/aggregate-functions/aggregate-quantile 
The QUANTILE_CONT() function computes the interpolated quantile number of a numeric data sequence.

**Comment by l1t1** [comment]
ref https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.quantile.html
