### ISSUE TITLE
bug: Reopen tcp keep-alive for MySQL

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10641]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.0.21

### What's Wrong?

<img width="584" alt="image" src="https://user-images.githubusercontent.com/30121694/226126062-789163bd-c92d-4b93-a729-3f5dab1d0bbf.png">
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/30121694/226126215-62868ade-d1ce-4d01-b666-deb9007c546b.png">
Connection cannot be released because there is no keep-alive.

We need to rollback socket2 to 0.4, and reopen keep-alive.

See https://github.com/rust-lang/socket2/issues/402, and wait https://github.com/tokio-rs/tokio/pull/5514.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by dantengsky** [comment]
> We need to rollback socket2 to 0.4, and reopen keep-alive.
> 
> See https://github.com/rust-lang/socket2/issues/402, and wait https://github.com/tokio-rs/tokio/pull/5514.

@yufan022  :+1:  thanks
