### ISSUE TITLE
It's strange that the test result contain grant to system.one.

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#10646]
cc @TCeason It's strange that the test result contain grant to system.one.

```
[SQL] SHOW GRANTS FOR 'test-grant'@'localhost'
[Diff] (-expected|+actual)
    GRANT ALL ON 'default'.'default'.* TO 'test-grant'@'localhost'
    GRANT SELECT ON 'default'.'db01'.* TO 'test-grant'@'localhost'
-   GRANT SELECT ON 'default'.'db01'.'tb1' TO 'test-grant'@'localhost'
-   GRANT SELECT ON 'default'.'system'.'one' TO 'test-grant'@'localhost'
+   GRANT SELECT ON 'default'.'db01'.'tb1' TO 'test-grant'@'localhost'
at tests/sqllogictests/suites/base/05_ddl/05_0006_ddl_grant_privilege:49
```

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/10642#issuecomment-1475061861_

**Comment by TCeason** [comment]
Yes and I see this : https://github.com/datafuselabs/databend/blob/7e585941cc7a0130f3b7b79080558fc30091e2b2/src/query/users/src/role_mgr.rs#L84

I think this is by design:

https://github.com/datafuselabs/databend/pull/10040

cc @flaneur2020  @sundy-li

**Comment by sundy-li** [comment]
So why did the tests fail ?

**Comment by TCeason** [comment]
I can't reproduce this in main branch. And after mergify update main the ci test now is passed.

https://github.com/datafuselabs/databend/actions/runs/4458316671/jobs/7830093557

**Comment by TCeason** [comment]
Maybe need pre-execute set role 'public' in test 05_0006_ddl_grant_privilege, I think if we want to do this , better to fix with https://github.com/datafuselabs/databend/issues/10462

**Comment by TCeason** [comment]
So far there has been no reappearance
