### ISSUE TITLE
feat: add query.openai_api_key to config

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10654]
**Summary**

```
USE <your-database>;
SELECT * FROM ai_to_sql('<prompt>');
```

This will use the `query.openai_api_key` in the config file.

**Comment by xinlifoobar** [comment]
Just curious about this feature. Will it treat all tables in a database as context?

**Comment by BohuTANG** [comment]
> Just curious about this feature. Will it treat all tables in a database as context?

Yes.

**Comment by xinlifoobar** [comment]
> > Just curious about this feature. Will it treat all tables in a database as context?
> 
> Yes.

Got that. Also, may I ask one dummy Q, how the decision is typically made when the prompts are not valid SQL syntax?

**Comment by BohuTANG** [comment]
> > > Just curious about this feature. Will it treat all tables in a database as context?
> > 
> > 
> > Yes.
> 
> Got that. Also, may I ask one dummy Q, how the decision is typically made when the prompts' responses are not valid SQL syntax?

Invalid SQL including two cases:
1. Invalid for the openai, it will return an empty SQL
2. Invalid for the Databend(for example, the functions) which returned by openai

For 1, I have no idea.
For 2, I am preferring openai can treat built-in functions as one part of the prompt, but it looks not work now, I will discuss it with them.
