### ISSUE TITLE
Feature: Support change the order of column when add column

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#10685]
**Summary**
is means like : alter table xxx add column xxx **after** xxx
for example:
sync data from mysql to databend,if mysql add column after the specific column, i want add the column to databend automatically by writing some simple code

**Comment by TCeason** [comment]
How about we only compatible with  this syntax but not real implement this feature? Maybe sort cols in column-db is not make sense? cc @BohuTANG  @dantengsky

**Comment by BohuTANG** [comment]
If we have a table:
```
create table t1(c1 INT, c2 INT, c3 INT);
```
The insert is:
```
insert into t1 values(1,2,3)
```

If we have the order:
```
alter table t1 add column c22 after c2
```
The insert is:
```
insert into t1 values(1,2,22,3)
```

The value `22` must be to column `c22`, so we should have an order-id mapping to do that.

**Comment by BohuTANG** [comment]
@lichuang might be more familiar with this because the previously worked on `alter table add/drop column`.
