### ISSUE TITLE
Feature: NTILE function

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#10719]
**Summary**
<html>
<body>

ntile(num_buckets integer) | bigint | An integer ranging from 1 to the argument value, dividing the partition as equally as possible. | ntile(4)
-- | -- | -- | --

</body>
</html>
Description for this feature.

ref https://duckdb.org/docs/sql/window_functions

**Comment by ariesdevil** [comment]
@l1t1 See: #10810
