### ISSUE TITLE
Bug: EmptyShareEndpointConfig, cannot query share databases on SHOW DATABASES

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#10783]
**Summary**

version: v1.0.35-nightly

**Comment by lichuang** [comment]
`share endpoint` now could add\drop accoss sql, see: https://github.com/datafuselabs/databend/pull/10762

later i will add some docs.

**Comment by flaneur2020** [comment]
can this settings be optional? This error can be reproduced on any SHOW DATABASES if not set config about share endpoint.
