### ISSUE TITLE
bug:  create view too slow

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#10802]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.0.34-nightly-c407340261ba33e9edec81a320e39ddc2cc0f0be(rust-1.70.0-nightly-2023-03-25T16:09:35.951514619Z)

the deploy mode is single

### What's Wrong?

**i want to create view with 64 tables,but it locked all the time**

CREATE VIEW `gview`.`gtransport_car_location_all` AS 
SELECT * FROM gtransport.car_location_1
union all 
SELECT * FROM gtransport.car_location_2
union all 
SELECT * FROM gtransport.car_location_3
union all 
SELECT * FROM gtransport.car_location_4
union all 
SELECT * FROM gtransport.car_location_5
union all 
SELECT * FROM gtransport.car_location_6
union all 
SELECT * FROM gtransport.car_location_7
union all 
SELECT * FROM gtransport.car_location_8
union all 
SELECT * FROM gtransport.car_location_9
union all 
SELECT * FROM gtransport.car_location_10
union all 
SELECT * FROM gtransport.car_location_11
union all 
SELECT * FROM gtransport.car_location_12
union all 
SELECT * FROM gtransport.car_location_13
union all 
SELECT * FROM gtransport.car_location_14
union all 
SELECT * FROM gtransport.car_location_15
union all 
SELECT * FROM gtransport.car_location_16
union all 
SELECT * FROM gtransport.car_location_17
union all 
SELECT * FROM gtransport.car_location_18
union all 
SELECT * FROM gtransport.car_location_19
union all 
SELECT * FROM gtransport.car_location_20
union all 
SELECT * FROM gtransport.car_location_21
union all 
SELECT * FROM gtransport.car_location_22
union all 
SELECT * FROM gtransport.car_location_23
union all 
SELECT * FROM gtransport.car_location_24
union all 
SELECT * FROM gtransport.car_location_25
union all 
SELECT * FROM gtransport.car_location_26
union all 
SELECT * FROM gtransport.car_location_27
union all 
SELECT * FROM gtransport.car_location_28
union all 
SELECT * FROM gtransport.car_location_29
union all 
SELECT * FROM gtransport.car_location_30
union all 
SELECT * FROM gtransport.car_location_31
union all 
SELECT * FROM gtransport.car_location_32
union all 
SELECT * FROM gtransport.car_location_33
union all 
SELECT * FROM gtransport.car_location_34
union all 
SELECT * FROM gtransport.car_location_35
union all 
SELECT * FROM gtransport.car_location_36
union all 
SELECT * FROM gtransport.car_location_37
union all 
SELECT * FROM gtransport.car_location_38
union all 
SELECT * FROM gtransport.car_location_39
union all 
SELECT * FROM gtransport.car_location_40
union all 
SELECT * FROM gtransport.car_location_41
union all 
SELECT * FROM gtransport.car_location_42
union all 
SELECT * FROM gtransport.car_location_43
union all 
SELECT * FROM gtransport.car_location_44
union all 
SELECT * FROM gtransport.car_location_45
union all 
SELECT * FROM gtransport.car_location_46
union all 
SELECT * FROM gtransport.car_location_47
union all 
SELECT * FROM gtransport.car_location_48
union all 
SELECT * FROM gtransport.car_location_49
union all 
SELECT * FROM gtransport.car_location_50
union all 
SELECT * FROM gtransport.car_location_51
union all 
SELECT * FROM gtransport.car_location_52
union all 
SELECT * FROM gtransport.car_location_53
union all 
SELECT * FROM gtransport.car_location_54
union all 
SELECT * FROM gtransport.car_location_55
union all 
SELECT * FROM gtransport.car_location_56
union all 
SELECT * FROM gtransport.car_location_57
union all 
SELECT * FROM gtransport.car_location_58
union all 
SELECT * FROM gtransport.car_location_59
union all 
SELECT * FROM gtransport.car_location_60
union all 
SELECT * FROM gtransport.car_location_61
union all 
SELECT * FROM gtransport.car_location_62
union all 
SELECT * FROM gtransport.car_location_63
union all 
SELECT * FROM gtransport.car_location_64;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
What's the content in `gtransport.car_location_*`?

**Comment by xudong963** [comment]
Thanks @WUWEI111222333 

After profiling, it seems to block at parser

<img width="1915" alt="image" @andylokandy ="https://user-images.githubusercontent.com/41979257/228180920-76a9bc37-0efd-49be-beb0-f37d6edf81eb.png">

cc @andylokandy
