### ISSUE TITLE
bug: query can't sync the meta endpoints after metasrv restart

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10829]
**Summary**
![img_v2_08c774ea-7153-4048-a89b-d01379b2d46g](https://user-images.githubusercontent.com/172204/228584782-9c632ff7-9b4a-4daa-9d51-7283414acfbd.jpg)

**Comment by drmingdrmer** [comment]
Redirect from: https://github.com/datafuselabs/databend/pull/10848#issuecomment-1490082349

> I assume the error is raised here:
> https://github.com/datafuselabs/databend/blob/7f408b4ab45b0f6af49c5aa64186bde26cfc50aa/src/meta/client/src/grpc_client.rs#L560-L562
>
> And the root cause is that `unhealthy_endpoints` did not evict unreachable nodes very quickly, the default eviction timeout is 120 seconds(nodes that are in `unhealthy_endpoints` will not be used):
> https://github.com/datafuselabs/databend/blob/7f408b4ab45b0f6af49c5aa64186bde26cfc50aa/src/meta/client/src/grpc_client.rs#L342
>
> In order to address this issue, we should introduce a new configuration item for the timeout of `unhealthy_endpoints` and reduce it to an appropriate value.
