### ISSUE TITLE
bug: copy into table from @my_ Stage error reporting prompt: "bad field end"

### ISSUE THREAD

**Issue by ZhangCanxiang** [datafuselabs/databend#10846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.0.29-nightly

### What's Wrong?

Chinese：
创建表后，如果最后一个字段是数字类型（double或者decimal）。在使用copy into table from @my_stage时报错。报错信息：ERROR 1105 (HY000): Code: 1046, displayText = fail to decode column 26 (arrival_amount Float64): bad field end, remain 1 bytes, next char is <CARRIAGE RETURN>。

English：
After creating the table, if the last field is of numeric type (double or decimal). When using copy into table from @ my_ Stage reported an error. Error message: ERROR 1105 (HY000): Code: 1046, displayText=fail to decode column 26 (arrival_amount Float64): bad field end, remaining 1 bytes, next char is<CARRIAGE RETURN>.

### How to Reproduce?

1. create  the table end with the type double

CREATE TABLE  store_daily_sales (
	dept_code varchar,
	dept_name varchar,
	business_attr varchar,
	area_code varchar,
	area varchar,
	area_name varchar,
	h_date varchar,
	h_year varchar,
	store_status varchar,
	store_flag varchar,
	new_store_flag varchar,
	area_supervisor varchar null default '',
	area_manager varchar null default '',
	division_manager varchar null default '',
	minister varchar null default '',
	one_year_flag varchar,
	open_date varchar,
	amount double default 0,
	profit double  default 0,
	reduction_profit double default 0,
	sales_num double  default 0,
	passenger_num double  default 0,
	amount_remove_joint double  default 0,
	work_days double default 0,
	offset_amount double  default 0,
	delivery_amount double default 0,
	arrival_amount double default 0
) ENGINE=FUSE ;

-- The tested csv data is as follows：

dept_code,dept_name,business_attr,area_code,area,area_name,h_date,h_year,store_status,store_flag,new_store_flag,area_supervisor,area_manager,division_manager,minister,one_year_flag,open_date,amount,profit,reduction_profit,sales_num,passenger_num,amount_remove_joint,work_days,offset_amount,delivery_amount,arrival_amount
10207,宿州万达,加盟店,102,102宿州市,宿州市,2022/11/14,2022/11/1,正常营业,既存店,正常门店,丁帅,李玉,暂无,郭军,开业满一年,2018/9/13,3769.13,658.42,672.11,649,226,3681.13,2,13.69,67.73,3701.4
20908,怀远文苑小区北门店,加盟店,209,209怀远,怀远,2022/12/12,2022/12/1,正常营业,既存店,正常门店,刘一锋,刘一锋,郭军,余庆云,开业满一年,2021/11/14,2151.86,529.41,544.02,343,115,2151.86,2,14.61,454.7,1697.16
10364,淮北24克拉店,加盟店,103,103淮北市,淮北市,2022/7/30,2022/7/1,正常营业,既存店,正常门店,余庆云,张薇,郭军,余庆云,开业满一年,2021/8/31,4466.95,877.24,916.45,690,226,4434.95,2,39.21,4.38,4462.57
10626,商丘神火大道长江路店,直营店,106,106商丘市,商丘市,2022/9/11,2022/9/1,正常营业,既存店,正常门店,程晋轩,刘妍,邵园园,李恩成,开业满一年,2020/3/31,4538.96,941.4,1043.78,720,207,4538.96,2,102.38,18.47,4520.49
11703,临泉万阁花园店,加盟店,117,117临泉县,临泉县,2022/2/6,2022/2/1,正常营业,既存店,正常门店,于庆艳,于庆艳,张超启,郭军,开业满一年,2021/10/18,5873.52,1083.82,1120.04,963,222,5621.52,2,36.22,74.17,5799.35
10917,灵璧翰林苑尚苑南门店,加盟店,109,109灵璧县,灵璧县,2023/1/13,2023/1/1,正常营业,既存店,正常门店,余庆云,马杰,余庆云,余庆云,开业满一年,2021/1/19,3943.57,701.48,704.62,434,142,3940.57,2,3.14,506.97,3436.6
21105,开封大相国寺店,直营店,211,211开封,开封,2022/12/9,2022/12/1,正常营业,既存店,正常门店,徐永杰,黄倩倩,马程程,李恩成,开业满一年,2020/11/5,2379.52,409.97,454.38,284,115,2379.52,2,44.41,82.68,2296.84
10612,商丘中骏雍景台北门店,加盟店,106,106商丘市,商丘市,2022/9/15,2022/9/1,正常营业,既存店,正常门店,程晋轩,刘妍,邵园园,李恩成,开业满一年,2020/8/19,1941.26,330.95,423.43,331.082,101,1941.26,2,92.48,97.88,1843.38
10710,蚌埠金润名都店,直营店,107,107蚌埠市,蚌埠市,2023/1/27,2023/1/1,正常营业,既存店,正常门店,余庆云,蚌埠,余庆云,余庆云,开业满一年,2019/7/14,3700.52,759.31,777.34,458,164,3700.52,2,18.03,429.12,3271.4

2. use the copy command :
    copy into yd.store_daily_sales from @my_stage files=('门店零售类型日商202302.csv') file_format=(type=csv skip_header=1);
3. the result err:
    copy into yd.store_daily_sales from @my_stage files=('门店零售类型日商202302.csv') file_format=(type=csv skip_header=1);
ERROR 1105 (HY000): Code: 1046, displayText = too many fields, expect 27, got 28, split 门店零售类型日商202302.csv(129864454 bytes), row=0=0+0, offset=0=0+0, options=FileFormatOptionsExt { stage: FileFormatOptions { format: Csv, skip_header: 1, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", compression: None, row_tag: "", quote: "\"", name: None }, ident_case_sensitive: false, headers: 0, json_compact: false, json_strings: false, timezone: UTC }, schema=[TableField { name: "dept_code", d

4. When the ending field is modified to a field of type varchar. Can be executed normally。

![image](https://user-images.githubusercontent.com/47653266/228778792-1b8ff741-d2ca-4029-af0d-36f7fe69c00a.png)

![image](https://user-images.githubusercontent.com/47653266/228779083-5ab31d6e-e8d2-450e-bdc9-991197da90ef.png)

    

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
I see you error with: 
```
 next char is <CARRIAGE RETURN>, [column_data]=["3701.4<CARRIAGE RETURN>"],
```
That's mean file  record_delimiter  is '\r\n'
so：
```
file_format=(type=csv skip_header=1 record_delimiter='\r\n')
```
Maybe it will work.

**Comment by ZhangCanxiang** [comment]
Problem solved。 

> I see you error with:
> 
> ```
>  next char is <CARRIAGE RETURN>, [column_data]=["3701.4<CARRIAGE RETURN>"],
> ```
> 
> That's mean file record_delimiter is '\r\n' so：
> 
> ```
> copy into yd.store_daily_sales from @my_stage files=('门店零售类型日商202302.csv') file_format=(type=csv skip_header=1 record_delimiter='\r\n')
> ```
> 
> Maybe it will work.

Problem solved! Thanks!

**Comment by ZhangCanxiang** [comment]
Pay attention to the end of a csv file because the format is not uniform.
the filed end with '\r‘， caused this problem。
file_format=(type=csv skip_header=1 **record_delimiter='\r\n'**) 

Thanks!
