### ISSUE TITLE
[improvement] improve code coverage

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1086]
**Summary**

https://app.codecov.io/gh/datafuselabs/datafuse

![image](https://user-images.githubusercontent.com/172204/126054206-88862515-8214-41c9-9c2e-1e786b4d5e9f.png)

`common` needs more unit tests

**Comment by Xuanwo** [comment]
This issue is too general.

@BohuTANG Please consider split tasks in small pieces and track them by a tracking issue instead.

If there are no actions need to take, I prefer to close it for now.
