### ISSUE TITLE
Feature: Snapshots cause failover when the state machine is large

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10873]
**Summary**

Description for this feature.
![109da6ab-d033-42bf-a309-8e5457c3c39c](https://user-images.githubusercontent.com/30121694/229016475-6fe367d1-cb06-4c58-b93c-6fa857ab5478.jpeg)
![68776ab2-2fa6-4ea6-ba14-e07ff261bc50](https://user-images.githubusercontent.com/30121694/229016496-a376d065-081e-4b1c-9552-413781c78a6e.jpeg)

### Cause:

- Building snapshot requires an exclusive lock to the state-machine, which blocks applying log to state-machine;
- Append-entries request responds to the leader when log is appended, and applied on a follower;

Therefore a heartbeat request(empty append-entries) will timeout when a follower is building a snapshot.

### Solution

Append-entries request should not be blocked by operations on state-machine. It can just respond to the leader as soon as logs are flushed to disk.

**Comment by drmingdrmer** [comment]
Add Cause and Solution...
