### ISSUE TITLE
bug: copy into table with parquet fileformat got error

### ISSUE THREAD

**Issue by jiangzhx** [datafuselabs/databend#10909]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.0.48-nightly-aarch64-apple-darwin

### What's Wrong?
create EXTERNAL_LOCATION  table on minio with 150+ columns.

use copy into command to insert data to table got error message
```
create stage ex_event url='s3://uba/parquet_event/ds=20230101/' CONNECTION=(aws_key_id='minioadmin' aws_secret_key='minioadmin' endpoint_url='http://127.0.0.1:9000');

copy into event from @ex_event PATTERN ='.*[.]parquet' FILE_FORMAT = (TYPE = PARQUET);
```

second sql command response:
```
ERROR 1105 (HY000): Code: 1104, Text = assertion failed: `(left == right)`
  left: `6738`,
 right: `20051`.
```

### How to Reproduce?

create EXTERNAL_LOCATION  table on minio with 150+ columns 
datatype include 
- VARCHAR
- INT
- BIGINT
- ARRAY(STRING)
- DECIMAL(18,3)

```
create stage ex_event url='s3://uba/parquet_event/ds=20230101/' CONNECTION=(aws_key_id='minioadmin' aws_secret_key='minioadmin' endpoint_url='http://127.0.0.1:9000');

copy into event from @ex_event PATTERN ='.*[.]parquet' FILE_FORMAT = (TYPE = PARQUET);
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Hi, Is there a sample data to reproduce this bug? 

The data file could be a very small (10 rows)
