### ISSUE TITLE
Feature: Batch-deletion supports retry

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10947]
**Summary**

I got many errors while batch-delete, it should retry.
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/30121694/230260349-999b806f-6ee2-4599-a91c-63e5f38931e7.png">

**Comment by yufan022** [comment]
cc @Xuanwo

**Comment by Xuanwo** [comment]
Implemented by https://github.com/apache/incubator-opendal/issues/1538, waiting for next release.

**Comment by yufan022** [comment]
Ping @Xuanwo 
Any progress on this?

**Comment by Xuanwo** [comment]
> Any progress on this?

This feature has been released. But we found a new issue that could lead to errors not retried: https://github.com/apache/incubator-opendal/issues/2158

We have fixed it and will release this week.

**Comment by ZhiHanZ** [comment]
cc @Xuanwo , can we close the issue now?

**Comment by Xuanwo** [comment]
Yes, we has released this feature.
