### ISSUE TITLE
test: add some tests which table schemas are nullable

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#10969]
**Summary**
Currently, databend table schema is not nullable by default.

So almost all of tests table shemas are not nullable, we need to add some tests which table schemas are nullable to cover.

**Comment by xudong963** [comment]
Maybe chatgpt can help us 🤣

**Comment by ZhengLin-Li** [comment]
Interested in this! 

@xudong963 Could you guide more on which file shall we add such test cases? I am new to this project and I searched the codebase but not found.

**Comment by xudong963** [comment]
Sorry, this is a legacy issue, I'll close it, thanks for your interest! @ZhengLin-Li
