### ISSUE TITLE
docs: Add role_arn and external_id for s3 services

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#10974]
**Summary**

`role_arn`: specify the `role_arn` that databend used for COPY or STAGE
`external_id`: specify the `external_id` that databend used for COPY or STAGE

More details could be found at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

**Comment by flaneur2020** [comment]
as discussed, we can restrict users can not access the tenant's default bucket to avoid risks about data leakage.

**Comment by soyeric128** [comment]
> Hey @soyeric128, could you please take a look?

Sure. Could you pls provide some COPY or STAGE command samples with the two parameters?

**Comment by Xuanwo** [comment]
LGTM!
