### ISSUE TITLE
bug: function in update will eval for all rows

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10985]
**Summary**

There is only one row:
![image](https://user-images.githubusercontent.com/172204/230712253-9141677a-1bd4-43b3-8201-68c6ce3dc501.png)

When run this query:
```
update elon set embedding = ai_embedding_vector(content) where path='2022-07-05 17:55:09+00:00';
```

The `ai_embedding_vector` will evaluate for all rows:

![image](https://user-images.githubusercontent.com/172204/230712292-d007a626-1ebb-494a-ba6f-96dc9b57eae1.png)

**Comment by BohuTANG** [comment]
This table only has one block with 4190 records:
![image](https://user-images.githubusercontent.com/172204/230716649-28cf39b6-27df-441d-9590-6a7edec411b9.png)

cc @zhyass

**Comment by zhyass** [comment]
> This table only has one block with 4190 

update uses the if function, similar to `if(path='2022-07-05 17:55:09+00:00', cast(ai_embedding_vector(content), ARRAY(FLOAT32)), embedding )`.
It looks like the if implementation needs to calculate all the results of args first, and then calculate them based on cond.
https://github.com/datafuselabs/databend/blob/d201ffb6df37bf0417324c8bba43a1fd6ece2481/src/query/expression/src/evaluator.rs#L828-L832

**Comment by BohuTANG** [comment]
cc @sundy-li for help. From normal, if the condition is true then will eval the expression.

**Comment by sundy-li** [comment]
It's by design, the expression evaluation is vectorized (by column batch unit), and the current update mutation is copy on write.

**Comment by BohuTANG** [comment]
> It's by design, the expression evaluation is vectorized (by column batch unit), and the current update mutation is copy on write.

A question about this optimization: 
Since all functions are executed once, if my 'cond' filters out a large portion of the data, it seems that this would bring greater performance benefits than vectorization.

**Comment by sundy-li** [comment]
If `cond` filters out the whole block(chunk), `if(cond, a, b)`  `a` will not be evaluated.  But `a` will be evaluated if the cond has one or more valid values.

See:   `fn eval_if(`
