### ISSUE TITLE
bug: alter table add column with default value query is not right

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11009]
**Summary**

```
create table answer1(name varchar);
insert into answer1 values('name1'), ('name2');

-- alter add a timestamp
alter table answer1 add column ts TIMESTAMP DEFAULT now();
insert into answer1(name) values('name3'), ('name4');
select * from answer1 order by ts desc;
```

![image](https://user-images.githubusercontent.com/172204/230888629-7fb801b3-1be2-4d5e-84d9-71e8103d1c6c.png)

This looks not correct, `name1` and `name2` rows ts column always get `NOW()` each time.

**Comment by BohuTANG** [comment]
cc @lichuang @sundy-li

**Comment by sundy-li** [comment]
default expression only supports constant value now.

**Comment by BohuTANG** [comment]
If the default expression not a constant value, we can not eval it and return the value for the query?
