### ISSUE TITLE
flaky tests about sharing

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#11064]
flaky tests about sharing: https://github.com/datafuselabs/databend/actions/runs/4689069723/jobs/8310584277?pr=11059

cc @lichuang

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/11059#issuecomment-1506928871_

**Comment by lichuang** [comment]
I have fix it in pr https://github.com/datafuselabs/databend/pull/11056 and has been merged into main.
