### ISSUE TITLE
feat: add Column-Level dynamic data masking support

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11089]
**Summary**

Implement support for dynamic data masking at the column level to enhance data security and privacy.

**Note: This feature might be offered as an Enterprise Edition feature, similar to Snowflake.**

**Background**

Dynamic data masking is a security feature that helps protect sensitive data by automatically masking certain data fields to ensure that unauthorized users cannot access sensitive information. It allows for customizable masking rules, based on user roles or other criteria, without requiring any changes to the underlying data or applications.

**Feature Request**

Add support for dynamic data masking at the column level, similar to the functionality provided by BigQuery and Snowflake Enterprise Edition. This would allow users to define masking policies for specific columns in a dataset, based on user roles, permissions, or other criteria.

**References**
[1. BigQuery: dynamic data masking](https://cloud.google.com/bigquery/docs/column-data-masking-intro)
[2.Snowflake: Using Dynamic Data Masking (ENTERPRISE EDITION FEATURE)]( https://docs.snowflake.com/en/user-guide/security-column-ddm-use)

**Comment by lichuang** [comment]
https://github.com/datafuselabs/databend/issues/11543
