### ISSUE TITLE
doc: SOUND LIKE 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11091]
**Summary**

PR: https://github.com/datafuselabs/databend/pull/11043
Demo: https://github.com/datafuselabs/databend/pull/11043/files#diff-714437434f88ea56b675414598cefa3e0ec79381cd2efaef2d66b77c3f51f4bf

**Comment by Jake-00** [comment]
I am interested in adding the documentation about `sounds like`.
