### ISSUE TITLE
bug: show columns has a bug

### ISSUE THREAD

**Issue by WUWEI111222333** [datafuselabs/databend#11090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.1.1-nightly-1599cc99bf6f47964483cf9c5e65d69ed9d59aa3(rust-1.70.0-nightly-2023-04-14T16:08:53.525598787Z)

### What's Wrong?

if add a database tag like show full columns from "database.table",it will hive some mistake:
![256f26d40234181433dc9b970464f75](https://user-images.githubusercontent.com/35459358/232356698-4e7890b5-3ed8-4e0d-83d1-6c81f291af14.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
Now Databend support
```
show [full] columns from Tb from Db; 
```
We just need support 
```
show [full] columns from Db.Tb; 
```

**Comment by TCeason** [comment]
In mysql the show columns syntax is https://dev.mysql.com/doc/refman/8.0/en/show-columns.html

```
SHOW [EXTENDED] [FULL] {COLUMNS | FIELDS}
    {FROM | IN} tbl_name
    [{FROM | IN} db_name]
    [LIKE 'pattern' | WHERE expr]
```

And we know MySQL support db_name.table_name , but this looks more like MySQL's own bug.

Look at this little experiment: **db.table causes confusion.**

```sql
root@mysqldb 11:38:17 [test]> select version();
+-------------------------+
| version()               |
+-------------------------+
| 8.0.32-0ubuntu0.20.04.2 |
+-------------------------+
1 row in set (0.00 sec)

root@mysqldb 11:39:38 [test]> show create table test.a;
+-------+---------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                  |
+-------+---------------------------------------------------------------------------------------------------------------+
| a     | CREATE TABLE `a` (
  `id` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

root@mysqldb 11:39:44 [test]> show create table test2.a;
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                          |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
| a     | CREATE TABLE `a` (
  `c` int DEFAULT NULL,
  `c2` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+-------+---------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

root@mysqldb 11:39:46 [test]> show columns from test.a from test2;
+-------+------+------+-----+---------+-------+
| Field | Type | Null | Key | Default | Extra |
+-------+------+------+-----+---------+-------+
| c     | int  | YES  |     | NULL    |       |
| c2    | int  | YES  |     | NULL    |       |
+-------+------+------+-----+---------+-------+
2 rows in set (0.01 sec)

root@mysqldb 11:39:59 [test]> show columns from test2.a from test;
+-------+------+------+-----+---------+-------+
| Field | Type | Null | Key | Default | Extra |
+-------+------+------+-----+---------+-------+
| id    | int  | YES  |     | NULL    |       |
+-------+------+------+-----+---------+-------+
1 row in set (0.00 sec)

```

**Comment by TCeason** [comment]
> In mysql the show columns syntax is https://dev.mysql.com/doc/refman/8.0/en/show-columns.html
> 
> ```
> SHOW [EXTENDED] [FULL] {COLUMNS | FIELDS}
>     {FROM | IN} tbl_name
>     [{FROM | IN} db_name]
>     [LIKE 'pattern' | WHERE expr]
> ```
> 
> And we know MySQL support db_name.table_name , but this looks more like MySQL's own bug.
> 
> Look at this little experiment: **db.table causes confusion.**
> 
> ```sql
> root@mysqldb 11:38:17 [test]> select version();
> +-------------------------+
> | version()               |
> +-------------------------+
> | 8.0.32-0ubuntu0.20.04.2 |
> +-------------------------+
> 1 row in set (0.00 sec)
> 
> root@mysqldb 11:39:38 [test]> show create table test.a;
> +-------+---------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                  |
> +-------+---------------------------------------------------------------------------------------------------------------+
> | a     | CREATE TABLE `a` (
>   `id` int DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
> +-------+---------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.01 sec)
> 
> root@mysqldb 11:39:44 [test]> show create table test2.a;
> +-------+---------------------------------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                                          |
> +-------+---------------------------------------------------------------------------------------------------------------------------------------+
> | a     | CREATE TABLE `a` (
>   `c` int DEFAULT NULL,
>   `c2` int DEFAULT NULL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
> +-------+---------------------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.01 sec)
> 
> root@mysqldb 11:39:46 [test]> show columns from test.a from test2;
> +-------+------+------+-----+---------+-------+
> | Field | Type | Null | Key | Default | Extra |
> +-------+------+------+-----+---------+-------+
> | c     | int  | YES  |     | NULL    |       |
> | c2    | int  | YES  |     | NULL    |       |
> +-------+------+------+-----+---------+-------+
> 2 rows in set (0.01 sec)
> 
> root@mysqldb 11:39:59 [test]> show columns from test2.a from test;
> +-------+------+------+-----+---------+-------+
> | Field | Type | Null | Key | Default | Extra |
> +-------+------+------+-----+---------+-------+
> | id    | int  | YES  |     | NULL    |       |
> +-------+------+------+-----+---------+-------+
> 1 row in set (0.00 sec)
> ```

So I think we can close this issue. cc @wubx
