### ISSUE TITLE
Tracking: general window functions.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#11148]
**Summary**

- [x] row_number #10824
- [x] rank #10824
- [x] dense_rank #10824
- [x] percent_rank #11094
- [x] lag #11244 
- [x] lead #11244 
- [x] first_value #11587 
- [x] last_value #11587 
- [x] first(alias first_value) #11587 
- [x] last(alias last_value) #11587 
- [x] cume_dist #11942 
- [x] ntile #11905 
- [x] nth_value #11600

**Comment by gitccl** [comment]
Hi, I'd like to try `first_value` and `last_value` function.

**Comment by ariesdevil** [comment]
Hi @ArberSephirotheca , do you still working on `first_value` and `last_value` ? If not, these will assign to @gitccl .
