### ISSUE TITLE
chore: upgrade Regex to 1.8.0

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11162]
**Summary**

regex 1.8.0 is out! A big release, but a precursor to an even bigger one: 
https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#180-2023-04-20

**Comment by 2022H1030042G** [comment]
Hi, I would like to work on it. Is it available?

**Comment by 2022H1030042G** [comment]
@xudong963 , Can you share some details like where the changes are required and how to implement those changes. I'm new to open source development, it'd be great if someone can help me on this.

**Comment by BohuTANG** [comment]
@2022H1030042G 

Thanks for taking this, this guide may help:
https://databend.rs/doc/contributing/good-pr
