### ISSUE TITLE
bug: Query Node S3 Storage Error: current configured storage is not available

### ISSUE THREAD

**Issue by powerLambda** [datafuselabs/databend#11180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.1.13-nightly-x86_64-unknown-linux-musl
databend-v1.1.14-nightly-x86_64-unknown-linux-musl

### What's Wrong?

I'm trying to deploy new standalone node, strictly following the steps on https://databend.rs/doc/deploy/deploying-databend#deploying-a-query-node. 
After I configured s3 storage and tried to startup Query Node, it output errors as below:
`Databend Query start failure, cause: Code: 3901, Text = current configured storage is not available: config: S3(StorageS3Config { endpoint_url: "https://cos.ap-shanghai.myqcloud.com", region: "", bucket: "databend-1253240642", root: "", disable_credential_loader: false, enable_virtual_host_style: false, role_arn: "", external_id: "", access_key_id: "******U9X", secret_access_key: "******7KG", security_token: "", master_key: "" }), cause: Unexpected (permanent) at Pager::next, context: { response: Parts { status: 400, version: HTTP/1.1, headers: {"content-type": "application/xml", "content-length": "411", "connection": "keep-alive", "date": "Sun, 23 Apr 2023 05:56:25 GMT", "server": "tencent-cos", "x-amz-request-id": "NjQ0NGM4ODlfMzNkMzc2MWVfMTRiNWZfYjBiY2I2Zg==", "x-amz-trace-id": "xx="} }, service: s3, path: / } => S3Error { code: "InvalidArgument", message: "Invalid Argument", resource: "/", request_id: "NjQ0NGM4ODlfMzNkMzc2MWVfMTRiNWZfYjBiY2I2Zg==" }.`

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable>

### How to Reproduce?

Fresh new install as https://databend.rs/doc/deploy/deploying-databend#deploying-a-query-node

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
> cause: Unexpected (permanent) at Pager::next, context: { response: Parts { status: 400, version: HTTP/1.1, headers: {"content-type": "application/xml", "content-length": "411", "connection": "keep-alive", "date": "Sun, 23 Apr 2023 05:56:25 GMT", "server": "tencent-cos", "x-amz-request-id": "NjQ0NGM4ODlfMzNkMzc2MWVfMTRiNWZfYjBiY2I2Zg==", "x-amz-trace-id": "xx="} }, service: s3, path: / 

cc @Xuanwo , I think it's related to the cos API compatibility ？

**Comment by Xuanwo** [comment]
I will upgrade now since the recently released OpenDAL has fixed this issue.
