### ISSUE TITLE
feature request: tools for decoding the new table meta data

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#11200]
> BTW, do we have a tool or functions to decode the compressed bincode meta file?Like we want to check the meta data in it, for json it's easy to do it.

Command-line tool name: databend-meta-decoder

Usage: 
`databend-meta-decoder  -i <INPUT> [-j]  [-o <OUTPUT>] -t <TYPE>`

Description:
Decode and output the encoded metadata to the terminal or file. Supports bincode, MessagePack, and JSON encoding formats.

Options:
-j, --json Output data in JSON format
-i, --input <INPUT> Specify the file path to be decoded
-o, --output <OUTPUT> Specify the output file path for the decoded data. If not specified, output will be displayed on the terminal
-t, --type <TYPE> input data type: segment or snapshot(type only support `sg` or `ss`)

Examples:

1. View metadata information in binary format without saving to a file:
```shell
databend-meta-decoder -i data.bin

Version: x
Encoding: y
Compression: z
Blocks Size: p bytes
Summary Size: q bytes
```

2. Convert metadata information in binary format to JSON format and save it to a file:
```shell
databend-meta-decoder -i data.bin -j -o output.json
```

Note:
If the output file already exists, it will be overwritten.

How about this design?

_Originally posted by @jun0315 in https://github.com/datafuselabs/databend/issues/11015#issuecomment-1505628486_

**Comment by jun0315** [comment]
Apart from the naming (`databend-meta-decoder`) that needs to be changed(Do we have any other names?), I am developing the other parts according to the above design:D

**Comment by dantengsky** [comment]
how about `table-meta-decoder`?

**Comment by jun0315** [comment]
> how about `table-meta-decoder`?

Good Idea! 
@sundy-li @BohuTANG What do you think?

**Comment by sundy-li** [comment]
maybe table-meta-inspector ?
