### ISSUE TITLE
Release Databend as a python Package 

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#11293]
currently , you need docker to install Databend, I think for more market visibility, providing an easy to use pip install databend will have a positive impact on the project long term

**Comment by sundy-li** [comment]
This task has been discussed many times, but it's really very hard for some reasons.

1. Databend needs a meta service but the embedded meta is deprecated in #10290 
2. Databend had many crates that were hard to publish into crates.io
3. ...

**Comment by l1t1** [comment]
1. recover the code:)
