### ISSUE TITLE
CopyInto Need to inject cancel point

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#11302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.1.26

### What's Wrong?

```sql
select sleep(300);
```

when cancel the previous SQL from databend http api through kill, 
```
show processlist
```
still see the query and computing resource is not released.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by flaneur2020** [comment]
@youngsofun help take a look?

**Comment by sundy-li** [comment]
`Duration::from_secs(300)`  was too long, we should panic as soon as possible I think.

**Comment by ZhiHanZ** [comment]
> `Duration::from_secs(300)` was too long to block a thread, we should throw the error as soon as possible.
> 
> Fixed in #11304

Not only sleep could not be killed, copy into SQL could not be killed as well, which may result in non-trivial impact on production use cases

**Comment by sundy-li** [comment]
Ok, CopyInto Need to inject cancel point.

**Comment by youngsofun** [comment]
copy can be killed after the executor is started. 
fail to kill if it is listing file before execut , It will be fixed by check aborting when start executor.

I`ll fix it later.

```
    pub fn kill(&self, cause: ErrorCode) {
        self.set_error(cause.clone());
        self.aborting.store(true, Ordering::Release);

 
        if let Some(executor) = self.executor.read().upgrade() {
            executor.finish(Some(cause));
        }
  }
```

**Comment by BohuTANG** [comment]
Listing file(OpenDAL operation) also need be cancelable, for example:
 Copy from a dir which has many files, the lists may take a long time we can't cancel unitl it finished.

**Comment by sundy-li** [comment]
listing of opendal is in streaming mode, so it could be integrated into the pipeline.

**Comment by youngsofun** [comment]
> listing of opendal is in streaming mode, so it could be integrated into the pipeline.

listing is in read_partition which is before building of pipeline.
