### ISSUE TITLE
<jemalloc>: Unsupported system page size

### ISSUE THREAD

**Issue by xiaomin996** [datafuselabs/databend#11333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.1.12-nightly-aarch64-unknown-linux-musl

### What's Wrong?

<jemalloc>: Unsupported system page size
memory allocation of 2304 bytes failed
CPU&内存
16核(vCPU)32 GiB
操作系统
CentOS 7.9 64位 ARM版
启动query报此问题

### How to Reproduce?

 阿里云ecs

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by everpcpc** [comment]
Hi, what is the instance type for your ECS?
Would you please provide the output of `getconf PAGESIZE`?

**Comment by xiaomin996** [comment]
> 
65536
ecs.c8y.4xlarge 
![image](https://user-images.githubusercontent.com/132739654/236610813-26baede9-4717-481e-9699-f59221e8149b.png)

**Comment by wubx** [comment]
databend-v1.1.33-nightly-aarch64-unknown-linux-musl.tar.gz 

start fail with:
```
<jemalloc>: Unsupported system page size
memory allocation of 2304 bytes failed
```
