### ISSUE TITLE
[store] refactor: Distinguish potentially confusing operation results

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#1139]
**Summary**

There is a problem in the current implementation: we cannot distinguish between failed `add` and successful `delete` operations. 

By adding a `seq` field to results, we can avoid this problem like `UpsertKV`.

BTW: these changes will break the current API

cc @drmingdrmer @dantengsky @sundy-li

**Comment by drmingdrmer** [comment]
> BTW: these changes will break the current API

It breaks the internal API: `MetaNode::write()` returns different values. The incompatibility should be dealt well by action handers. Components outside action handler won't be affacted.

@sundy-li will have nothing to worry about 🤔

**Comment by dantengsky** [comment]
@ariesdevil 
pls break them if needed, proper and ergonomic APIs do worth the costs.

**Comment by drmingdrmer** [comment]
@ariesdevil are you still working on this?

**Comment by ariesdevil** [comment]
Yep, change the database and table to kv operations will cover this issue.

**Comment by drmingdrmer** [comment]
> Yep, change the database and table to kv operations will cover this issue. It Will be done today.

If possible, smaller PR reduces latency and increases concurrency. (Just like the way we do with mutex. 🤔

**Comment by ariesdevil** [comment]
Okay.

**Comment by BohuTANG** [comment]
Ready to close?
