### ISSUE TITLE
Bug: Unsupported file format: Json(JsonFileFormatParams { compression: Auto }) on COPY a .json.gz with COMPRESSION = AUTO

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#11410]
**Summary**

> query error: code: 1001, message: Unsupported file format: Json(JsonFileFormatParams { compression: Auto })" files="415317/415317_2023-05-04_15#1.json.gz]"

> COPY INTO \"xxx\".\"xxx\" FROM 's3://xxxxx' CONNECTION = ( ACCESS_KEY_ID = '**' SECRET_ACCESS_KEY = '**' SESSION_TOKEN = '**' REGION = 'us-west-2') FILES=('4153xx7_2023-05-04_14#1.json.gz') FILE_FORMAT=(TYPE = JSON compression = AUTO)

**Comment by flaneur2020** [comment]
@sundy-li @youngsofun help take a look about this issue?

**Comment by youngsofun** [comment]
we do not support JSON now, try NDJSON?
