### ISSUE TITLE
Feature:  databend-meta detect ip

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#11494]
**Summary**
These two parameters can be very convenient if databend-meta can detect ip.
```
raft_listen_host = "0.0.0.0"
grpc_api_advertise_host = "0.0.0.0"
```

**Comment by wubx** [comment]
later change: https://github.com/datafuselabs/databend/blob/main/scripts/distribution/configs/databend-meta.toml

**Comment by drmingdrmer** [comment]
`raft_listening_host` can use `0.0.0.0` to listen all incoming connection.

But `grpc_api_advertise_host` must be specified by administrator. There could be multiple public network interfaces or the public network IP can not be seen by the server, e.g., in a docker container.
