### ISSUE TITLE
Feature: Enable compression when unloading data to stages.

### ISSUE THREAD

**Issue by pengye91** [datafuselabs/databend#11509]
**Summary**

At present, the `compression = GZIP | ZSTD ...` syntax is supported when using `COPY INTO @stage_name FROM `, 

but the files are not really compressed, they are still of the original file type, like CSV or Parquet.

**Comment by wubx** [comment]
This feature maybe designed in bendsql and driver.

**Comment by flaneur2020** [comment]
this can not be implemented in driver. as the data is transfered within the databend-query's processor, the driver could not touch the data at all.

**Comment by sundy-li** [comment]
Yes, I think this should be done at user's level.

**Comment by wubx** [comment]
That's right. 
Our products need to make users more happy and relaxed, if we can try to educate users as little as possible.
Let's take look snowflake put command,this command only support cli and jdbc:

>Upload 1.csv from the user home to @~

```
SMALL@HITS.PUBLIC>put file://~/1.csv @~;
+--------+----------+-------------+-------------+--------------------+--------------------+----------+---------+
| source | target   | source_size | target_size | source_compression | target_compression | status   | message |
|--------+----------+-------------+-------------+--------------------+--------------------+----------+---------|
| 1.csv  | 1.csv.gz |          34 |          64 | NONE               | GZIP               | UPLOADED |         |
+--------+----------+-------------+-------------+--------------------+--------------------+----------+---------+
1 Row(s) produced. Time Elapsed: 2.434s
```

https://docs.snowflake.com/en/sql-reference/sql/put
![image](https://github.com/datafuselabs/databend/assets/320680/41ad1e80-6739-4a62-bbe6-4c0ff29cf4f3)

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/pull/13067
