### ISSUE TITLE
Feature: Support `intdiv` operator `//`

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#11516]
**Summary**

Description for this feature.

```
select 3 / 2, 3//2;

--> 1.5, 1

```
Parser should add this `//` operator.
Operator `//`  should be resolved as `intdiv` function in [type_checker.rs](https://github.com/datafuselabs/databend/blob/e64908558f141d77a8b6bff93d8a6d4a99547a9f/src/query/sql/src/planner/semantic/type_check.rs)

**Comment by gitccl** [comment]
I'd like to do this task.
