### ISSUE TITLE
Generate a new catalog based on existing data 

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#11525]
**Summary**

create an external tables in S3, everything works fine, the data and metadata is saved in the remote storage, my catalog is saved in the local FS of the VM, made a mistake did not backup my local catalog, how can I recreate the catalog based on the data saved in the remote storage

**Comment by BohuTANG** [comment]
Would like to ping @drmingdrmer for his expert opinion on this issue.

**Comment by djouallah** [comment]
I understand exactly what do you mean, but I would really appreciate something like this

ctx = SessionContext("s3://databend/database",Createcatalog=true) or something like that, I should not know anything about snapshot, not table schema

**Comment by BohuTANG** [comment]
At present, catalog data in Databend is not stored on S3 as it's managed by our meta service. However, we're planning to enable local meta data storage on S3.

**Comment by djouallah** [comment]
@sundy-li as a workaround, can you save the content of the folder as a compressed file, the compression can be low, just for convenience,  backing up one file is easier than a folder
![image](https://github.com/datafuselabs/databend/assets/12554469/c7852f51-a009-4be9-93fc-9aa46830452b)

**Comment by djouallah** [comment]
closing for now, I think I am more interested in this 
https://github.com/datafuselabs/databend/issues/11531
