### ISSUE TITLE
Disk cache nor result cache seems to be working with the Python API

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#11528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.1.41

### What's Wrong?

running queries from data stored in Cloudflare R2, the second run don't seems to be using disk cache nor result cache for that matter.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
disk cache/result cache is not enabled by default.


enable query result cache
```
ctx.sql("set enable_query_result_cache = 1")
```

disk cache should be enabled via configuration, but it's not exported in python api.

**Comment by djouallah** [comment]
@sundy-li can you expose it please :)
