### ISSUE TITLE
Store Databend folder in one compressed file 

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#11531]
**Summary**

for Databend Python API and to make the experience for new users as easy as possible, it will be really nice to have the current folder ".databend" compressed in 1 file, the compression can be 0, it is more about the ease of use

![image](https://github.com/datafuselabs/databend/assets/12554469/b370a7e8-7339-41ca-ad32-9b24b53da8a1)

the result will be something like databend.zip , which contains the exact structure of the current folders.

take for example PowerBI format(pbix), it contains files and folders, but it is compressed to only 1 zip file
![image](https://github.com/datafuselabs/databend/assets/12554469/2f757c7a-c3b4-4f63-915d-56b125d8cb7a)

see content
![image](https://github.com/datafuselabs/databend/assets/12554469/e33f68bb-cd7a-459b-bcfc-b3df74a9da10)

**Comment by sundy-li** [comment]
I'm afraid users should zip the directory manually.

It's hard to have it in databend because we need to zip/unzip the whole directory each time we read or write, it's very heavy.

**Comment by djouallah** [comment]
Thank you, I am sure you will find a clever way to do it :)

**Comment by djouallah** [comment]
maybe it is a silly idea after all :)
