### ISSUE TITLE
chore: apply max_storage_io_requests only for pruning

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11553]
**Summary**

Now, we use `max_storage_io_requests` settings for these:

*  purge https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/storages/fuse/src/operations/gc.rs#L105
* analyze table https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/storages/fuse/src/operations/analyze.rs#L62
* block compact when select target https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/storages/fuse/src/operations/mutation/compact/block_compact_mutator.rs#L110

* merge into https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/storages/fuse/src/operations/merge_into/mutator/mutation_accumulator.rs#L179
* get snapshot segments https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/ee/src/storages/fuse/io/snapshots.rs#L53
* copy align https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/pipeline/sources/src/input_formats/input_pipeline.rs#L196
* **pruning** https://github.com/datafuselabs/databend/blob/1b2e4c841f1177c934180d96e3cba4fd529beeb6/src/query/storages/fuse/src/pruning/fuse_pruner.rs#L137

In the case of `pruning`, the use of `max_storage_io_requests` helps to fast the execution but need more memory. For the remaining operations, it appears we could switch to using `max_threads`.

**Comment by BohuTANG** [comment]
For gc/compact parts, cc @zhyass 
For copy parts, cc @youngsofun

**Comment by BohuTANG** [comment]
For purning and query from fuse columns, we can set `max_storage_io_requests` default to 2*max_threads(now is max_threads),  cc @zhang2014

**Comment by youngsofun** [comment]
> * copy align

`execute_copy_aligned` is not used now.  I am going to remove it in the next refactor.


max_storage_io_requests is used here (not in the list):

https://github.com/datafuselabs/databend/blob/main/src/query/storages/parquet/src/parquet_table/read.rs#L212

I think it is ok to use just the same num of processors as the following pipe. 
to make the pipeline as fast as possible,  we can let each async source  to cache one 'block'.
I can do this part of refactoring @BohuTANG

**Comment by BohuTANG** [comment]
@youngsofun 

I will start this task after your refactor.

**Comment by zhyass** [comment]
https://github.com/datafuselabs/databend/pull/12089 Use max_threads instead of max_storage_io_requests in purge|compact|analyze|table functions

**Comment by youngsofun** [comment]
- [ ] remove unused code https://github.com/datafuselabs/databend/pull/12093
- [ ] use max_threads instead of max_storage_io_requests in copy
