### ISSUE TITLE
unit test build failed 

### ISSUE THREAD

**Issue by littlekuo** [datafuselabs/databend#11619]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.1.44-nigntly

### What's Wrong?

 --- stderr
  CMake Warning at CMakeLists.txt:51 (message):
    Disabling Z3_INCLUDE_GIT_DESCRIBE
  Call Stack (most recent call first):
    CMakeLists.txt:100 (disable_git_describe)

  CMake Warning at CMakeLists.txt:55 (message):
    Disabling Z3_INCLUDE_GIT_HASH
  Call Stack (most recent call first):
    CMakeLists.txt:101 (disable_git_hash)

  In file included from /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/arith_decl_plugin.cpp:19:
  In file included from /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/arith_decl_plugin.h:21:
  /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/ast.h:183:39: error: 'get<int, int, ast *, symbol, zstring *, rational *, double, unsigned int>' is unavailable: introduced in macOS 10.13
      int get_int() const { return std::get<int>(m_val); }
                                        ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/variant:1556:22: note: 'get<int, int, ast *, symbol, zstring *, rational *, double, unsigned int>' has been explicitly marked unavailable here
  constexpr const _Tp& get(const variant<_Types...>& __v) {
                       ^
  In file included from /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/arith_decl_plugin.cpp:19:
  In file included from /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/arith_decl_plugin.h:21:
  /Users/yuchengguo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/z3-sys-0.7.1/z3/src/ast/ast.h:184:41: error: 'get<ast *, int, ast *, symbol, zstring *, rational *, double, unsigned int>' is unavailable: introduced in macOS 10.13
      ast * get_ast() const { return std::get<ast*>(m_val); }

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by akoshchiy** [comment]
Adding this shell variable helped me
`export CXXFLAGS="-D_LIBCPP_DISABLE_AVAILABILITY"`
