### ISSUE TITLE
flaky tests: ydb/select1-1.test

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#11743]
flaky tests

https://github.com/datafuselabs/databend/actions/runs/5253743422/jobs/9491694617?pr=11739

```
query III
select (select count(*) from t1 as x where x.b<t1.b) as col1,
       case when c>(select avg(c) from t1) then a*2 else b*10 end as col2,
       c-d as col3
from t1
order by col2,col3,col1
```

```
    8 1430 1
-   9 1450 -1
+   8 1450 -1
    10 1510 -4
```

_Originally posted by @youngsofun in https://github.com/datafuselabs/databend/issues/11739#issuecomment-1588961307_

**Comment by youngsofun** [comment]
https://github.com/datafuselabs/databend/actions/runs/5253743422/jobs/9492069450

**Comment by xudong963** [comment]
@Dousir9 is checking it

**Comment by zhyass** [comment]
https://github.com/datafuselabs/databend/actions/runs/5253961113/jobs/9492173486
