### ISSUE TITLE
Feature: distributed execution for copy into ....

### ISSUE THREAD

**Issue by JackTan25** [datafuselabs/databend#11752]
**Summary**

Description for this feature.
    for now, our copy into statement is not distributed, this will limit our performance. please finish this.

**Comment by RinChanNOWWW** [comment]
FYI, here are some discussions: https://github.com/datafuselabs/databend/issues/6395

**Comment by JackTan25** [comment]
> FYI, here are some discussions: #6395

thanks

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/databend/pull/11943
