### ISSUE TITLE
Feature: allow specify a LIMIT clause in the OPTIMZE TABLE ... PURGE statement

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#11799]
**Summary**

On scheduling the background tasks (including reclusters, purge, vacuum, etc.), the background task scheduler would hope each task could be executed in a bounded time range.

Currently we support:

```
OPTIMIZE TABLE [database.]table_name PURGE BEFORE (TIMESTAMP => '<TIMESTAMP>'::TIMESTAMP)
```

It would be neat if we can specify a LIMIT clause together.

The query to be executed by the background task scheduler would looks like:

```
OPTIMIZE TABLE [database.]table_name PURGE BEFORE (TIMESTAMP => '1 day ago') LIMIT 100
```

**Comment by ZhiHanZ** [comment]
That is required, it needs around several hours to cleanup relic snapshots in TB scale, if that is executed by a single command, it would introduce non-trivial maintainence risks, and we shoud divide this command in file level (at least in snapshot level)
