### ISSUE TITLE
docs:improvement on_error description 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#11823]
**Summary**
Parquet 
on_error = continue |abort
continue: skip the file
abort: operation abort

csv|ndjson|tsv
on_error=continue|abort|abort_N
continue: skip the error row
abort: operation abort
abort_N: N is int, error row less or equal to the N continue, greater than N to abort operation.

cc @youngsofun

**Comment by youngsofun** [comment]
https://github.com/datafuselabs/databend/pull/11822
