### ISSUE TITLE
Feature:  Support to add random seed on random engine

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#11863]
**Summary**
Create table(t int, time timestamp) Engine=Random(1000)

The sql would create a generate random table with random seed 1000, such feature would deterministically test a lot of cases need randome data

**Comment by infdahai** [comment]
I'd like to take this assignment.

**Comment by blackstar-baba** [comment]
LGTM

**Comment by blackstar-baba** [comment]
@PsiACE  Can we design random table ddl like this:
```
Create table a (t int, time timestamp) 
Engine=Random
Seed=1000
```
i think this ddl has minimal changes.

**Comment by sundy-li** [comment]
Maybe:

Create table a (t int, time timestamp) 
Engine=Random(1000).

**Comment by blackstar-baba** [comment]
other table ddl:
1. icebreg table
```
CREATE TABLE test_iceberg
ENGINE = Iceberg 
LOCATION = 's3://testbucket/iceberg_ctl/iceberg_db/iceberg_tbl/' 
CONNECTION_NAME = 'my_s3_conn';
```
2. fuse table
```
CREATE TABLE table_name (
  column_name1 column_type1,
  column_name2 column_type2,
  ...
) [ENGINE = FUSE] [CLUSTER BY(<expr> [, <expr>, ...] )] [Options];
```
3. memory table
```
CREATE TABLE table_name (
  column_name1 column_type1,
  column_name2 column_type2,
  ...
) ENGINE = Memory;
```
if we add seed property in engine property, table ddl style looks incosistent
