### ISSUE TITLE
feature request: segment-level deletion pruning optimization 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#11861]
reminder: 
> the above optimization is only applied at the block-meta level in this PR. segment-level optimization will be addressed in > another PR.

in pr #11759 , pruning optimization of deletion only applied to block level, it could so be applied to segment level 

recall that, for `delete` statements like

> ~~~
> delete from t where t.c > xxx and t.c < yyy
> ~~~
> 
> there might be blocks of table t that have min/max range [a,b] of column c, where `a >= xxx and b <= yyy`, they could be marked as whole-block-deletion, and we do not need to load the data of column c, table t and filter the rows.

the above principle is also applicable at the segment level and **will be more beneficial, since for large and well-maintained tables, a single segment may have 1k blocks**. 

seems we need a medium or large refactoring of the Pruner components.

the idea is almost the same as pr #11759

during segment-level pruning, we got the candidate segments to perform the deletion, these segments may be deleted totally or partially, to filter out the segment that could be deleted totally by using range index only:

- invert the filter expression
- apply the inverse filter expression to the segment (meta data), using the range index
  - for those segments that need to be deleted totally, they will be filtered out.
  - segments that need to be deleted partially will NOT be filtered out.
  
the relevant code (block level)
 

https://github.com/datafuselabs/databend/blob/6a66544e755dd332fdd0c8bb6d611fe821d1366e/src/query/storages/fuse/src/operations/delete.rs#L337-L366

  
- for the blocks marked as whole-block-deletion in the above pruning phase, we just "remove" them from segments, no need to process the blocks that belongs to this segment.

**Comment by dantengsky** [comment]
askbend:summary

**Comment by JackTan25** [comment]
finish at #11937
