### ISSUE TITLE
Feature: investigate potential optimization of `replace into`

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#11898]
**Summary**

after PR https://github.com/datafuselabs/databend/pull/11885, the cpu bottle-neck of `replace into` "moved" to

`DeletionAccumulator::add_block_deletion`, the maintenance of deletion state ( hashset) seems to take a majority of CPU resources (~66.54%).

![2023-06-27-233248_1644x820_scrot](https://github.com/datafuselabs/databend/assets/22081156/09a5ec70-9d63-44ab-9a80-ac795307d0d0)

although there is always hotspot for meaningful business logic, it will be great if we can optimize this further, since for `replace into` there is always the case that data being ingested involves lots of data to be updated (no matter the table is well clustered or not).

[the CPU profile : replace_into_cpu_profile.html.tar.gz](https://github.com/datafuselabs/databend/files/11884571/replace_into_cpu_profile.html.tar.gz)

--------------

test scenario of the above CPU profiling:

- table schema
~~~
create table t (

id bigint,
id1 bigint,
id2 bigint,
id3 bigint,
id4 bigint,
id5 bigint,
id6 bigint,
id7 bigint,

s1 varchar,
s2 varchar,
s3 varchar,
s4 varchar,
s5 varchar,
s6 varchar,
s7 varchar,
s8 varchar,
s9 varchar,
s10 varchar,
s11 varchar,
s12 varchar,
s13 varchar,

d1 DECIMAL(20, 8),
d2 DECIMAL(20, 8),
d3 DECIMAL(20, 8),
d4 DECIMAL(20, 8),
d5 DECIMAL(20, 8),
d6 DECIMAL(30, 8),
d7 DECIMAL(30, 8),
d8 DECIMAL(30, 8),
d9 DECIMAL(30, 8),
d10 DECIMAL(30, 8),

insert_time datetime,
insert_time1 datetime,
insert_time2 datetime,
insert_time3 datetime,

i int

) CLUSTER BY(id,insert_time);


create table random_source  like t Engine = Random;

~~~

- data ingestion (for example)

~~~
for i in {0..100000};
do
	echo "batch $i"
	mysql -uroot -h127.0.0.1 -P3307 -e "select count() from test_order"
	echo "-- replace into 500000 random rows"
	time mysql -uroot -h127.0.0.1 -P3307 -e "replace into t on(id, insert_time) select * from random_source limit 500000";
done
~~~

- CPU profiling

go tool pprof -http="0.0.0.0:8081" http://localhost:8080/debug/pprof/profile?seconds=30

**Comment by JackTan25** [comment]
after delete optimization, I will reference to ducked.
