### ISSUE TITLE
bug: replace into cause wrong result

### ISSUE THREAD

**Issue by Dousir9** [datafuselabs/databend#11915]
**Summary**
In source file `src/query/pipeline/transforms/src/processors/transforms/transform.rs`, I made the following changes：

<img width="594" alt="截屏2023-06-29 14 19 34" src="https://github.com/datafuselabs/databend/assets/54522439/b1733026-545f-4786-80cd-386cf617d35d">

Then `replace into` will fail the following test:

```sql
drop table if exists test;
CREATE TABLE test(a int);
INSERT INTO test values (1), (2), (3);
REPLACE INTO test ON(a) values (2), (3), (4);
SELECT * FROM test order by a;
```
The correct result is:
```
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
```
The result we get is:
```
+------+
| a    |
+------+
|    1 |
+------+
```

**Comment by sundy-li** [comment]
I can't reproduce it.
