### ISSUE TITLE
feat: attach table allow switching between DatabendCloud and On-Premises

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11959]
**Summary:**

Allows users to easily switch between DatabendCloud and on-premises using a SQL command:
 `ATTACH TABLE xx.xx CONNECTION=(...) ...`. 

This function is particularly useful when a Databend is already running in the user's environment and they want to leverage DatabendCloud for computation, without moving their data.

**Comment by dantengsky** [comment]
@BohuTANG  how about this?


- the sytanx

adapts from 

https://github.com/datafuselabs/databend/blob/f74348a78d5a26c7f631fab1071221ec49f9f785/tests/suites/1_stateful/02_query/02_0001_create_table_with_external_location.sh#L11

~~~
ATTACH table table_external_location_with_location_prefix(a int) 
   's3://testbucket/admin/data/' 
   connection=(aws_key_id='minioadmin' aws_secret_key='minioadmin' endpoint_url='${STORAGE_S3_ENDPOINT_URL}') 
   location_prefix = '11959/11960'
~~~

where  `location_prefix` is NOT optional, and points to the premise deployed table's data directory being attached.

-----

a rough idea about impl

- (try) open 's3://testbucket/admin/data/'last_snapshot_location_hint, and get the location of last snapshot
- open the snapshot file, extract the table schema
- create table new table with storage configuration provided, and 
   - set the table option OPT_KEY_STORAGE_PREFIX to empt string
     which effectively by passed the default storage prefix $db_id/$table_id
     
     please see also https://github.com/datafuselabs/databend/pull/11958
