### ISSUE TITLE
bug: statements error success

### ISSUE THREAD

**Issue by JackTan25** [datafuselabs/databend#12034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main 19635f159a5723695620b74d0211906373a85fe2

### What's Wrong?

statement error 2000
create table t(a int);

in the sqllogictest, this can pass test.

### How to Reproduce?

run sqllogictest locally.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
Related to https://github.com/risinglightdb/sqllogictest-rs/issues/178
