### ISSUE TITLE
TPCH_sf100 Query 18 OOM with 32 GB of RAM 

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12106]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Python Version: 1.2.25

### What's Wrong?

using fuse engine and a local ssd disk, using TPCH_SF100 data in a VM with 32 GB of RAM, Query 18 time out probably an OOM  

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
This is the join order issue, we are planning to solve it.

**Comment by djouallah** [comment]
I feel the issue is elswhere, Datablend works very well know with parquet with small row groups, but it seems parquet generated by Fabric has row group as big as 16 million rows, databend does not works very well with it :(

**Comment by BohuTANG** [comment]
Thanks for feedback, still need to make improvements, and @Dousir9 is working on them.

**Comment by djouallah** [comment]
good works, i can confirm it is fixed now
![image](https://github.com/datafuselabs/databend/assets/12554469/efb27171-68be-4de9-81a1-61f955bcee2e)
