### ISSUE TITLE
Nightly build don't seems to be updated for LInux python

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.1.27

### What's Wrong?

latest version is still 1.1.25 when running pip  install ?

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
https://pypi.org/project/databend/#files

I notice it's `databend 1.2.27` already

**Comment by djouallah** [comment]
using Microsoft Fabric notebook ( it works fine in colab)
![image](https://github.com/datafuselabs/databend/assets/12554469/6f9d7d3b-7bdc-49fb-95fc-586422ce5364)

**Comment by sundy-li** [comment]
it may be cached in the mirror url of `Fabric `settings.

Use this command to debug:
```
❯ pip -v install databend
Using pip 23.1.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple    <---- this is mirror

```

You can use 
```
pip install -i https://pypi.org/simple databend===1.2.27
```

to install from pypi, which is the original url.

**Comment by djouallah** [comment]
![image](https://github.com/datafuselabs/databend/assets/12554469/19d1ab6d-c8ac-47f1-ad65-6c69571e923f)

**Comment by djouallah** [comment]
any updated on this please

**Comment by everpcpc** [comment]
> using Microsoft Fabric notebook ( it works fine in colab)
It seems Microsoft Fabric has an outdated `glibc`.
We changed build image to a newer one since the old image cannot build `croaring`.
ref: https://github.com/datafuselabs/databend/pull/12011/files#diff-ad78ea616c04b8a750670789101964a47a981559beeb80a6ac20018acc293d70R94

**Comment by djouallah** [comment]
Thank you very much, it is fixed now
