### ISSUE TITLE
flake tests: distributed_copy_into_table2_execption

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#12143]
**Summary**

https://github.com/datafuselabs/databend/actions/runs/5597676017/jobs/10236628699?pr=12141

**Comment by dantengsky** [comment]
@JackTan25 PTAL

**Comment by JackTan25** [comment]
get it!

**Comment by JackTan25** [comment]
this is normal. we can't fix it. for example:
create table parquet_table_(a int,b string,c string);
copy into parquet_table_ from @parquet_stage_;

there are many parquets in the parquet_stage_ here, some are two fields, some are three fields.in the bind phase, it will pick the first one to check the schema. if not the same with table schema, it will throw a exception. if not so, it will give the exception at the execution phase. so we can't control the error parquet file order. it's generated randomly.
