### ISSUE TITLE
bug:  select with like  crash contains Chinese 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#12154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

 v1.2.27

### What's Wrong?

```
mysql> create table b01(card_no int, deal_type varchar);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into b01 values(1000,'地铁入站'),(1000,'地铁入站');

mysql> select * from b01 where deal_type  like '地铁%';
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    33
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    34
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
cc @xudong963 [check_prefix](https://github.com/datafuselabs/databend/blob/233420eba6ab923345a2dc18b2b0ec4f3ebdf18f/src/query/sql/src/planner/semantic/type_check.rs#L3217) need to consider not ascii string error
