### ISSUE TITLE
[clickhouse] can't show progress for some query 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1216]
**Summary**

If we run this query in ClickHouse client:
```
SELECT number FROM numbers_mt(10000000000) ORDER BY number DESC LIMIT 100;
```
It can not show the progress, but the group by query is ok:
```
datafuse :) SELECT max(number), sum(number) FROM numbers_mt(1000000000) GROUP BY number % 3, number % 4, number % 5;
```

It seems that only the group by query working.

**Comment by compasses** [comment]
BTW, just kindly remind, I did some performance test against clickhouse follow the guide from https://datafuse.rs/overview/performance/, all use the newest master branch, but i have a very different result with that, mostly clickhouse is better :)

**Comment by BohuTANG** [comment]
> BTW, just kindly remind, I did some performance test against clickhouse follow the guide from https://datafuse.rs/overview/performance/, all use the newest master branch, but i have a very different result with that, mostly clickhouse is better :)

Hi!
Could you give the env and results of your test?

**Comment by compasses** [comment]
Hi, 
Just some case, before i make some mis config, you can just check the two case appeared in this issue.

Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz 48 core:

![image](https://user-images.githubusercontent.com/10161171/127433902-8a564cb3-830c-466f-b7f0-c3ee4dab8863.png)
![image](https://user-images.githubusercontent.com/10161171/127433953-0f9a01e1-8090-4462-9cbd-56d130dcb306.png)

![image](https://user-images.githubusercontent.com/10161171/127434103-f6890899-71d4-4d70-8a12-b638b8e057a0.png)
![image](https://user-images.githubusercontent.com/10161171/127434135-adfb98c5-c72b-4508-8754-3363c8d98756.png)

**Comment by BohuTANG** [comment]
Hmm, how do you build the datafuse?
The performance binary build with `make build`

**Comment by compasses** [comment]
> Hmm, how do you build the datafuse?

Just run with: cargo run --bin fuse-query --release

instead of make build, seems no difference.

**Comment by BohuTANG** [comment]
You could  try 
```
RUSTFLAGS="-C target-cpu=native" cargo build --bin=fuse-query --release
```
and test again.

**Comment by BohuTANG** [comment]
On my local, I have set `set max_threads=16`  for clickhouse, but it seems slower than the default(max_threads=8).
I will re-measure the performance against with the latest version ClickHouse, there is already a task here: https://github.com/datafuselabs/datafuse/issues/1129

Thanks for your report @compasses

**Comment by compasses** [comment]
Yes, that's meet my test to



> 
> ```
> RUSTFLAGS="-C target-cpu=native" cargo build --bin=fuse-query --features allocator --release
> ```

That's not work on my environment:

```
.cargo/registry/src/github.com-1ecc6299db9ec823/snmalloc-sys-0.2.27/snmalloc/src/override/../mem/../mem/../pal/pal_posix.h:294:23: error: ‘getentropy’ was not declared in this scope; did you mean ‘get_entropy64’?
    294 |         if (getentropy(&result, sizeof(result)) != 0)
        |             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
        |             get_entropy64
  make[3]: *** [CMakeFiles/snmallocshim-1mib-rust.dir/src/override/rust.cc.o] Error 1
  make[2]: *** [CMakeFiles/snmallocshim-1mib-rust.dir/all] Error 2
  make[1]: *** [CMakeFiles/snmallocshim-1mib-rust.dir/rule] Error 2
  make: *** [snmallocshim-1mib-rust] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2
```

BTW, where I can find the newest progress of this project? Currently I cannot create a local table and do some insert & query test right ?

**Comment by BohuTANG** [comment]
@compasses 
1. snmalloc has few problems here, what's your os version?
2. We have roadmap to track the progress https://github.com/datafuselabs/datafuse/issues/746
3. local table insert is working, there's a example for the memory engine https://datafuse.rs/sqlstatement/data-manipulation-language-dml/dml-insert/
and, the remote table is working too but has not documents yet, I think it will done soon

**Comment by compasses** [comment]
cool！big thanks, the os version: SMP Debian 4.14.81.
