### ISSUE TITLE
Tracking: Implement Databend UDF Server

### ISSUE THREAD

**Issue by gitccl** [datafuselabs/databend#12177]
This issue is used to tracking the progress of implementing Databend UDF Server.
**RFC:** #12075

## Tasks
- [x] #12168
- [x] #12417
- [x] #12463 
- [x] #12463 
- [ ] #12802

**Comment by flaneur2020** [comment]
hi @gitccl, could you add this issue https://github.com/datafuselabs/databend/issues/12802 into the tracking list? this feature may have some benefits on security when you hope hosting databend-query on a multi-tenant environment. thank you
