### ISSUE TITLE
[Tracking] Refactor `PlanBuilder`

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#1219]
Part of #1217 

## Background
So far, `PlanBuilder` actually takes on the works of `Binder` and part of `Optimizer`(since we don't distinguish logical plan and physical plan for now).

Thus we'd better rethink about the duty of `PlanBuilder`.

My suggestion is to treat `PlanBuilder` as a `Binder`, which takes an AST and produce a logical plan bound with `Catalog`.

## Tasks

Subtasks:

- [ ] Support column binding and type check in `PlanBuilder` with `Catalog`
- [ ] Split `PlanNode`s into logical plans and physical plans

**Comment by BohuTANG** [comment]
Fine, question is that if datafuse supports dataframe, what's the plan builder like?

**Comment by leiysky** [comment]
> Fine, question is that if datafuse supports dataframe api, what's the plan builder like?

Good question.

Spark DataSet API can be regard as a dialect of SQL with some extra functional transforms(UDF).

The SQL dialect part can be transformed into logical plan with specific transformer.

The UDF part is a little bit complicated, but we can still transform it into a logical operator eventually.

So I tend to make the current `PlanBuilder` a `SQLBinder`, and maybe introduce `DataFrameBinder` in the future.

**Comment by leiysky** [comment]
closed by #2983
