### ISSUE TITLE
bug: linux / sqllogic_standalone_base_native

### ISSUE THREAD

**Issue by JackTan25** [datafuselabs/databend#12193]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

[8d922c0](https://github.com/datafuselabs/databend/commit/8d922c00fa0fceb153990a9a85cafa9927351e1d)

### What's Wrong?

https://github.com/datafuselabs/databend/actions/runs/5652730473/job/15312959898?pr=12174

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JackTan25** [comment]
@xudong963  cc

**Comment by sundy-li** [comment]
fixed in https://github.com/datafuselabs/databend/pull/12355
