### ISSUE TITLE
bug: linux / sqllogic_standalone_crdb bug

### ISSUE THREAD

**Issue by JackTan25** [datafuselabs/databend#12191]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

[8d922c0](https://github.com/datafuselabs/databend/commit/8d922c00fa0fceb153990a9a85cafa9927351e1d)

### What's Wrong?
https://github.com/datafuselabs/databend/actions/runs/5652730473/job/15312959538?pr=12174

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
```
statement error 1001
SELECT a FROM t WHERE a <> 2 AND 3 / b = 1 ORDER BY k
```
The SQL is expected to fail, but it successes, maybe it's related to expression check? @sundy-li

**Comment by JackTan25** [comment]
```
0: query is expected to fail, but actually succeed:
[SQL] SELECT a FROM t WHERE a <> 2 AND 3 / b = 1 ORDER BY k
at tests/sqllogictests/suites/crdb/and_or:13

1: query is expected to fail, but actually succeed:
Error: SelfError("sqllogictest failed")
[SQL] SELECT * FROM (onecolumn AS a JOIN othertype AS b USING(x))
at tests/sqllogictests/suites/crdb/join:463

2: query is expected to fail, but actually succeed:
[SQL] SELECT * FROM (onecolumn AS a JOIN othertype AS b USING(x))
at tests/sqllogictests/suites/crdb/runtime_filter_join:465

**Comment by JackTan25** [comment]
https://github.com/datafuselabs/databend/actions/runs/5749630119/job/15585108008?pr=12174 cc @sundy-li

**Comment by sundy-li** [comment]
fixed in https://github.com/datafuselabs/databend/pull/12355
