### ISSUE TITLE
bug:  CREATE ROLE role1 error

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#12235]
**Summary**

```
CREATE ROLE role1;
```

Error:
```
1005:
error: 
  --> SQL:3:13
  |
1 | 
2 | 
3 | CREATE ROLE role1;
  | ------      ^^^^^ expected  or `IF`
  | |            
  | while parsing `CREATE ROLE [IF NOT EXISTS] '']`
```

Doc: https://databend.rs/doc/sql-commands/ddl/user/user-create-role

**Comment by parkma99** [comment]
I am would like work it ! Could you give some suggestion?

**Comment by TCeason** [comment]
Maybe just need modify doc?

We support 

create role 'role1'

**Comment by BohuTANG** [comment]
> Maybe just need modify doc?
> 
> We support
> 
> create role 'role1'

This is a bug, not related to doc.

**Comment by flaneur2020** [comment]
in ANSI SQL, having plain names without special characters is encouraged. I guess this is considered as a bug, and easy to be fixed, just replace the String token into an Identifier token in the parser.

**Comment by parkma99** [comment]
Is just a parse error? Does it need  some work to `DDL expression to  Plan` ?
