### ISSUE TITLE
For Python compatibility, please add show() method 

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12255]
currently, Pyspark, Duckdb, Datafusion all supports show() method

it will be nice if this will be supported too in Databend

something like this

```
ctx.sql('select 42').show()
42
```

**Comment by sundy-li** [comment]
`Show` could be an alias to `__repr__` in dataframe

**Comment by djouallah** [comment]
using 1.2.44 in Google colab
databend.sql('select4").show()
good news it works in the sense that the query is run, but it show no results

**Comment by sundy-li** [comment]
```
>>> ctx.sql("select 4").show()
┌───────┐
│   4   │
│ UInt8 │
├───────┤
│     4 │
└───────┘
>>>
```
