### ISSUE TITLE
Feature: External function support

### ISSUE THREAD

**Issue by pengye91** [datafuselabs/databend#12307]
**Summary**

Can we add support for `External Function`?

It's like the [external function](https://docs.snowflake.com/en/sql-reference/external-functions) in Snowflake but without the limitations of supported platforms, like we can support any authenticated HTTP services instead of just services provided by cloud platforms. 

And it would be great if we can define the external function not only as a scalar function but also a [table function](https://docs.snowflake.com/en/developer-guide/udf/sql/udf-sql-tabular-functions).

Related discussion: https://github.com/datafuselabs/databend/discussions/12075

**Comment by BohuTANG** [comment]
Done https://docs.databend.com/guides/query/external-function
