### ISSUE TITLE
Add PGO notes to the documentation

### ISSUE THREAD

**Issue by zamazan4ik** [datafuselabs/databend#12318]
**Summary**
In https://github.com/datafuselabs/databend/issues/9387 we evaluated PGO optimization on Databend. According to the tests, PGO helps to achieve better performance with Databend. You also wrote an [article](https://databend.rs/blog/profile-guided-optimization) about Databend and PGO.

I suggest the information about PGO on Databend directly to the documentation somewhere in the "Performance" section (if there is no such a chapter - let's create it). I can suggest the following content to include there:
* What amount of performance a user can get with PGO. You can use your own benches or reuse mine from the https://github.com/datafuselabs/databend/issues/9387#issuecomment-1566210063 .
* How to build Databend with PGO. You already described it in the article but having this information in the documentation can help a lot to the users. Also, I can recommend using [cargo-pgo](https://github.com/Kobzol/cargo-pgo) instead of manual flags tweaking

Some examples of how it could be done in the documentation you can check here: [ClickHouse](https://github.com/ClickHouse/ClickHouse/pull/52877), [Nebula](https://docs.nebula-graph.io/3.5.0/8.service-tuning/enable_autofdo_for_nebulagraph/), [Clang](https://llvm.org/docs/HowToBuildWithPGO.html).

By the way, much more materials about PGO you can find [here](https://github.com/zamazan4ik/awesome-pgo).

@PsiACE pinging since you probably could be interested in this topic.

**Comment by PsiACE** [comment]
I tried to introduce it in #12580 , if you are interested, please help review. cc @zamazan4ik
