### ISSUE TITLE
Support distroless docker image

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1237]
**Summary**

Description for this feature.
"Distroless" images contain only your application and its runtime dependencies, does not even contains bash
https://github.com/GoogleContainerTools/distroless, which is desired to build small docker file

**Comment by Xuanwo** [comment]
Already added:

https://github.com/datafuselabs/databend/blob/18af848fbccc294b4a82035156eb1a96eb807dff/.github/workflows/databend-release.yml#L234

Closing.
