### ISSUE TITLE
bug: Using the copy command prompts an error if there are no gaps in the file path and parentheses

### ISSUE THREAD

**Issue by raymondchen-byte** [datafuselabs/databend#12480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.2.51

### What's Wrong?

Using the copy command prompts an error if there are no gaps in the file path and parentheses

### How to Reproduce?

  copy into schema.table
 from (select id  from @ext_stage_hdfs/c000.snappy.parquet) file_format = (type = PARQUET)  => has error

  copy into schema.table
 from (select id  from @ext_stage_hdfs/c000.snappy.parquet   ) file_format = (type = PARQUET)  => not error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
fix by https://github.com/datafuselabs/databend/pull/12781
