### ISSUE TITLE
bug: Failed to Insert with attachment using a different column order 

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#12496]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.2.68-nightly-13b15e6be249232bf69b1e8530fffc5371ae49a7(rust-1.72.0-nightly-2023-08-16T16:35:18.249266000Z)

### What's Wrong?

1. create a table
```
CREATE TABLE if not exists test (x Int32,y VARCHAR)
```
2. presign and upload csv file to stage ~
csv:
```
a,3
```
 
3.  call /v1/query to do insert with attachment

```
curl -d "{'sql': 'INSERT INTO test (y,x) VALUES', 'stage_attachment': {'location': '@~/7f5c7922-f5d5-401d-90e4-8ade92dc593c.csv', 'file_format_options': {'type': 'CSV'}, 'copy_options': {'PURGE': 'False', 'FORCE': 'False', 'SIZE_LIMIT': '0', 'ON_ERROR': 'abort'}}}"  -H 'Content-type: application/json' http://databend:@localhost:8000/v1/query
```
Attention, I change the column order and it is different with schema.

Got an error response:

```
{"error":{"code":"400","message":"parse error: key must be a string at line 1 column 2"}}%
```

4. check the csv file that we have uploaded
<img width="1117" alt="image" src="https://github.com/datafuselabs/databend/assets/7600925/b8c3d00c-1c00-4fe5-8d01-9642b3d40644">

<img width="1312" alt="image" src="https://github.com/datafuselabs/databend/assets/7600925/8b743951-a112-497c-b006-84d1de18b790">

The column 2 is `3` which is an `Int` value.

### How to Reproduce?

Above.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
The request data is not valid json, the correct way is 
```
curl -d '{"sql": "INSERT INTO test (y,x) VALUES", "stage_attachment": {"location": "@~/7f5c7922-f5d5-401d-90e4-8ade92dc593c.csv", "file_format_options": {"type": "CSV"}, "copy_options": {"PURGE": "False", "FORCE": "False", "SIZE_LIMIT": "0", "ON_ERROR": "abort"}}}'  -H "Content-type: application/json" http://databend:@localhost:8000/v1/query
```

**Comment by hantmac** [comment]
> The request data is not valid json, the correct way is
> 
> ```
> curl -d '{"sql": "INSERT INTO test (y,x) VALUES", "stage_attachment": {"location": "@~/7f5c7922-f5d5-401d-90e4-8ade92dc593c.csv", "file_format_options": {"type": "CSV"}, "copy_options": {"PURGE": "False", "FORCE": "False", "SIZE_LIMIT": "0", "ON_ERROR": "abort"}}}'  -H "Content-type: application/json" http://databend:@localhost:8000/v1/query
> ```

Oh It's my fault copy from log print.
I fixed the request data and got the following error:

```
error":{"code":1046,"message":"fail to decode column 1 (x Int32): bad field end, remain 1 bytes, next char is <CARRIAGE RETURN>, [column_data]=[\"3<CARRIAGE RETURN>\"], split 7f5c7922-f5d5-401d-90e4-8ade92dc593c.csv(5 bytes)

``` 
It seems that still does not support insert with attachment using a different column order.

**Comment by sundy-li** [comment]
I just pass this case.
```
❯ curl -d '{"sql": "INSERT INTO test (y,x) VALUES", "stage_attachment": {"location": "@~/a.csv", "file_format_options": {"type": "CSV"}, "copy_options": {"PURGE": "False", "FORCE": "False", "SIZE_LIMIT": "0", "ON_ERROR": "abort"}}}'  -H "Content-type: application/json" http://root:@localhost:8000/v1/query
{"id":"e590f5cd-5ed3-4155-986c-c49a49e23036","session_id":"4045d588-b8e8-42eb-9b21-607ea675f554","session":{},"schema":[],"data":[],"state":"Succeeded","error":null,"stats":{"scan_progress":{"rows":0,"bytes":0},"write_progress":{"rows":0,"bytes":0},"result_progress":{"rows":0,"bytes":0},"total_scan":{"rows":0,"bytes":0},"running_time_ms":3859.711731},"affect":null,"stats_uri":"/v1/query/e590f5cd-5ed3-4155-986c-c49a49e23036","final_uri":"/v1/query/e590f5cd-5ed3-4155-986c-c49a49e23036/final","next_uri":"/v1/query/e590f5cd-5ed3-4155-986c-c49a49e23036/final","kill_uri":"/v1/query/e590f5cd-5ed3-4155-986c-c49a49e23036/kill"}%
❯ cat ~/a.csv
a,3
```
