### ISSUE TITLE
Adding `databaseName`, `tableName`, `catalogName` field in HTTP API response

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#12509]
**Summary**
In Databend JDBC we need to override the `getSchemaName`, `getTableName` method from `java.sql.ResultSetMetaData` so we need to get these fields from API response and set it in `ColumnInfo` by [this code](https://github.com/databendcloud/databend-jdbc/blob/main/databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java#L129).

How about adding these fields into HTTP API response like :

```
{
...
"table": "test",
"database":"db",
"catalog":"xx",
...
}
```

**Comment by sundy-li** [comment]
You can query this via SQL,  `select * from system.columns`

**Comment by hantmac** [comment]
> You can query this via SQL, `select * from system.columns`

Actually, I want to get the `database` and `table` in the current query. `select * from system.columns` will get all the databases information?

**Comment by sundy-li** [comment]
> I want to get the database and table in the current query.

the `database` and `table` is not unique in one query, it may contain many results such like join query

**Comment by hantmac** [comment]
> > I want to get the database and table in the current query.
> 
> the `database` and `table` is not unique in one query, it may contain many results such like join query

Got it. Thanks!
