### ISSUE TITLE
databend-query cluster run queries only on one node?

### ISSUE THREAD

**Issue by Lif0820** [datafuselabs/databend#12584]
### Discussed in https://github.com/datafuselabs/databend/discussions/12583

<div type='discussions-op-text'>

<sup>Originally posted by **Lif0820** August 25, 2023</sup>
I have a databend-query cluster with 3 nodes, which can be found in table `system.clusters`:
name           host                port
HnMW...     10.66.110.37    9091
opIBW...     10.66.110.39    9091
qJHdo...     10.66.110.38    9091

I send a slow query sql (named sql_A) to any one node (e.g. 10.66.110.38:3307) above by mysql client, 
and see cpu usage on linux shell by `top` command, only 10.66.110.37 cpu become busy, and the sql result cost about 10 seconds;

next, i send the sql_A query twice at same time, it stiil seems to only use 10.66.110.37 cpu, and the sql result cost almost 20 seconds;

so, my question is:
1. the databend-query cluster has 3 nodes, why it seems like only the first node in table `system.clusters` will be used? 
2. for one sql query which is sended to databend-query cluster, it will use only any one query-node? or may use all nodes to complete the query like Greenplum?
</div>

**Comment by sundy-li** [comment]
The coordinator (which receives the sql query) node will cost more CPU for aggregation query because it needs to merge the aggregation state.

**Comment by wubx** [comment]
1. You can look up the members of the cluster
```
select * from system.clusters;
```

2. please support explain 
```
explain fragments SQL;
```

**Comment by Lif0820** [comment]
thanks to @wubx @sundy-li , the problem is resolved. the reason is my table only has one segment with 3gb data size, after decrease the table options `block_per_segment` and `block_size_threshold` value, sql query run on all nodes already.

**Comment by Lif0820** [comment]
thanks to @wubx @sundy-li , the problem is resolved. the reason is my table only has one segment with 3gb data size, after decrease the table options block_per_segment and block_size_threshold value, sql query run on all nodes already.

**Comment by wubx** [comment]
after this pr: https://github.com/datafuselabs/databend/pull/12589  support one segment use cluster.
