### ISSUE TITLE
[store] Introduce read function to FileSystem 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#1258]
**Summary**

We need to add a new method that returns a   `dyn io::read + io::Seek`, this could help in reading parquet file with projections.

cc @dantengsky 

https://github.com/datafuselabs/datafuse/blob/master/fusestore/store/src/fs/ifs.rs#L12-L23

**Comment by dantengsky** [comment]
definitely right！we have had this Api before，but removed in a refactoring for simplicity of impl. will be added back soon
