### ISSUE TITLE
Integration test with public datasets 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1266]
As PR #1054 has been merged into master, it is time for testing the functionality, stability, and performance by using datasets from the "real world" in cluster mode,  as a middle step of steadily approaching TPC-H/DS.

This PR is supposed to be a tracking PR.

Coarse-grained descriptions come into my mind for the time being:

- Scenarios
  - business transaction data analysis (mainly focus on funnel model that @sundy-li suggested) 
  - log data analysis (to support dashboard-like application)
- DataSets
Example datasets from clickhouse seem to be a good start:
[https://clickhouse.tech/docs/en/getting-started/example-datasets/](https://clickhouse.tech/docs/en/getting-started/example-datasets/)

**Comment by ZhiHanZ** [comment]
Does fuse-store based cluster management finished?

**Comment by dantengsky** [comment]
> Does fuse-store based cluster management finished?

Not yet, I think PR #883  is working on it

**Comment by Xuanwo** [comment]
Any updates on this issue?

**Comment by PsiACE** [comment]
> Any updates on this issue?

I think our stateful test can be seen as part of the solution to this issue.

**Comment by Xuanwo** [comment]
> I think our stateful test can be seen as part of the solution to this issue.

Great, let's close this issue. Please feel free to start a new one to address the not covered issue.
