### ISSUE TITLE
Integrate bendctl into install script

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1267]
**Summary**
We already have bendctl in release process, and we could incorporate it into install script for simpler deployment experience

**Comment by BohuTANG** [comment]
The script only need to download the datafuse-cli, fuse-query&fuse-store will be download by `datafuse-cli get` command

**Comment by ZhiHanZ** [comment]
> The script only need to download the datafuse-cli, fuse-query&fuse-store will be download by `datafuse-cli get` command

agreed, and I think we should also support multi version management for fuse-query and fuse-store

**Comment by BohuTANG** [comment]
> > The script only need to download the datafuse-cli, fuse-query&fuse-store will be download by `datafuse-cli get` command
> 
> agreed, and I think we should also support multi version management for fuse-query and fuse-store

Indeed.
Now, datafuse-cli is versioned by the tag, every tag is a directory, for example, `test`  namespace tree:
```
tree test/
test/
├── bin
│   └── v0.4.68-nightly
│       └── fuse-query
├── downloads
│   └── v0.4.68-nightly
│       └── datafuse--x86_64-unknown-linux-gnu.tar.gz
└── history.txt

```
