### ISSUE TITLE
Python package was not updated since 15 days

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend==1.2.80

### What's Wrong?

the plan was to have a new version every 10 days, it has been 15 days and no new package was released

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @everpcpc

**Comment by BohuTANG** [comment]
Updated version is in the works:
https://github.com/datafuselabs/databend/releases/tag/v1.2.98-nightly

**Comment by djouallah** [comment]
still nothing ?

**Comment by everpcpc** [comment]
We are only releasing one out of ten versions for python package:
```
release:
    if: endsWith(inputs.tag, '0')
    name: Publish to PyPI
````
cc @sundy-li

**Comment by djouallah** [comment]
still nothing

**Comment by BohuTANG** [comment]
> still nothing

It is working now(databend 1.2.101):
https://pypi.org/project/databend/

**Comment by djouallah** [comment]
did not update since 10 days ago

**Comment by BohuTANG** [comment]
> did not update since 10 days ago

We now only release the stable version. The stable version 1.2.262, was published 10 days ago.

We've just launched version 1.2.275, which is available at https://github.com/datafuselabs/databend/releases/tag/v1.2.275, please wait a few hours :)
