### ISSUE TITLE
bug: `range` function panic if the length is too large

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.99-nightly

### What's Wrong?

`range` function panic if the length is too large
```
panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
```

### How to Reproduce?

```sql
mysql> select range(10, 13870570673167612768);
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    9
Current database: *** NONE ***
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nange** [comment]
I'd like to take this issue.

**Comment by TCeason** [comment]
> I'd like to take this issue.

Better to fix them in one pr.

**Comment by b41sh** [comment]
> Based on the panic message and the document of `Vec::with_capacity` says: `` Panics if the new capacity exceeds `isize::MAX` bytes. `` So I think we should check the range number which should not exceeds `isize::MAX / 8`. However, even if I did that, another panic occurred when I tested with a slightly smaller number. The panic message as blow:
> 
> ```
> panicked at 'memory allocation of 9223372036854767920 bytes failed', src/common/base/src/runtime/ru
> time_tracker.rs:84:9
>    0: common_tracing::panic_hook::log_panic
>              at ./src/common/tracing/src/panic_hook.rs:35:21
>    1: common_tracing::panic_hook::set_panic_hook::{{closure}}
>              at ./src/common/tracing/src/panic_hook.rs:30:9
>    2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic
> info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
>              at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
> ```
> 
> Any suggestion how to reslove this issue? @b41sh @TCeason

I think we can set the maximum amount of values in the array to 1000000 or a similar number, and report an error if it exceeds it so that the execution is guaranteed to be successful and can meet the needs of most cases.
