### ISSUE TITLE
bug: `instr` function panic if the `substr` is empty

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.100-nightly

### What's Wrong?

`instr` function panic if the `substr` is empty
```
panicked at 'window size must be non-zero', src/query/functions/src/scalars/string.rs:270:18
```

### How to Reproduce?

```sql
mysql> select instr('', '');
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    10
Current database: *** NONE ***
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nange** [comment]
I'd like to take this issue.
