### ISSUE TITLE
Feature: support javascript udf

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#12746]
**Summary**

Python UDF will be launched soon: https://github.com/datafuselabs/databend/pull/12729. Thanks, @gitccl 

It will easily support javascript udf.

Ref: https://docs.snowflake.com/en/developer-guide/udf/javascript/udf-javascript-introduction

**Comment by hanxuanliang** [comment]
Recently I saw that rw open source [udf framework](https://github.com/risingwavelabs/arrow-udf), whether can use [arrow-udf-js](https://github.com/risingwavelabs/arrow-udf/tree/main/arrow-udf-js) to achieve this part, I want to try it. Or, I need to see the previous python UDF implementation before making a decision.

**Comment by sundy-li** [comment]
@hanxuanliang 

You can try to add arrow-udf-python, it's easy after #14799 is merged.

**Comment by hanxuanliang** [comment]
NICE. Is there an issue? I want to try it!
