### ISSUE TITLE
feature: table_function inspect_parquet(s)

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#12744]
**Summary**

read and display meta of parquet file, columns

1.  created_by
2. num_columns: 
3. num_rows
4. num_row_groups
5. serialized_size
4. max_row_groups_size_compressed
6. max_row_groups_size_uncompressed
cc @wubx 

like fuse_block and parquet tools

**Comment by zenus** [comment]
@youngsofun  
I'd like to solve this problem, 
Can you provide a PR for a specific reference plan?

**Comment by youngsofun** [comment]
1. you can refer to `infer_schema` which is used for parquet too.
2. both get infos from parquery file meta.
3. but please use parquet_rs instead of parquet2 for function

**Comment by zenus** [comment]
thanks

**Comment by zenus** [comment]
```rust
Test finished, fail fast enabled, 1 out of 153 records failed to run
0: query failed: mysql client error: Server error: `ERROR HY000 (1105): BadArguments. Code: 1006, Text = stage path must start with @, but got data/parquet/tuple.parquet.'
[SQL] select * from inspect_parquet('@data/parquet/tuple.parquet')
at tests/sqllogictests/suites/stage_parquet/inspect_parquet:1
```
@youngsofun  could  you please help me solve this error? I've been confused by it for a hour.
