### ISSUE TITLE
Lost connection to server during query. Service aborted.

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#1274]
**Summary**

Can't connect to server.

**How to reproduce**

- `target/release/fuse-query -c scripts/deploy/config/fusequery-node-1.toml`
- Just run `SELECT number FROM numbers_mt(10000000000) ORDER BY number DESC LIMIT 100` many times, mysql or clickhouse client.

**Error message and/or stacktrace**
There is no valid information at the moment and needs to be added. 

**Additional context**

![mysql-killed](https://user-images.githubusercontent.com/36896360/128112932-cabd6866-d774-4604-864e-507727249d8a.PNG)

![clickhouse-killed](https://user-images.githubusercontent.com/36896360/128112937-05c9a6ab-8063-43eb-b497-bf4e3ce3ac58.PNG)

**Comment by sundy-li** [comment]
OOM caused, need to investigate

**Comment by PsiACE** [comment]
Now, I can't reproduce this problem and I think we can close it.
