### ISSUE TITLE
Query 9, wrong join orders

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

current

### What's Wrong?

datablend generate a wrong join order for Query 9, it is not a big deal with a lot of RAM, but it does crash the system when there is  a small RAM

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Dousir9** [comment]
It will be improved soon.

**Comment by djouallah** [comment]
I moved back to databend==1.2.104 and it is way better the regression was introduced in 105

**Comment by djouallah** [comment]
@BohuTANG can you please check what happen in 1.2.104 , there is definitely a regression ?

**Comment by BohuTANG** [comment]
[1.2.105](https://github.com/datafuselabs/databend/releases/tag/v1.2.105-nightly) has a PR related to the parquet file reading: https://github.com/datafuselabs/databend/pull/12756 cc @RinChanNOWWW

**Comment by BohuTANG** [comment]
* `set use_parquet2=0`(default):
![image](https://github.com/datafuselabs/databend/assets/172204/96ade0a8-8933-496e-a292-dae148c3045b)

* `set use_parquet2=1`:
![image](https://github.com/datafuselabs/databend/assets/172204/283b6948-3b10-4130-80ed-255c803b4d60)

We should consider including a stage with parquet files for benchmarking CI. This will ensure that there are no performance regressions. cc @sundy-li @RinChanNOWWW

**Comment by Dousir9** [comment]
We are not currently collecting parquet-rs statistics, I will add that soon. 
Q9 requires predicate derivation, I'm currently working on it.
@BohuTANG @djouallah

**Comment by djouallah** [comment]
I think it is fixed now
