### ISSUE TITLE
Feature: Add Allowlist in external udf function

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#12802]
**Summary**
In an effort to enhance security and streamline the management of external UDF (User Defined Functions) executions, we propose the integration of an allowlist feature within the system's configuration and settings. This feature will facilitate the restriction of external function executions to only those addresses and functions that are explicitly permitted by the users, thereby preventing unauthorized or potentially malicious function calls.

Details:
enabling users to specify a list of allowed udf functions through the udf_server_allowlist  variable. This variable will accept a list of endpoint URLs and function names that are permitted to execute.

To illustrate, users can specify a list in the following format:
```toml
[query]
...
udf_server_allow_list = [ "https://example.com/python_hello"]
```

this config would only allow python_hello function under https://example.com to execute as databend udf server

**Comment by gitccl** [comment]
How about to only specify an address to enable users create all functions under the address, instead of specify both address and udf function name? e.g.:
```
udf_server_allow_list = [ "https://example.com/"]
```

**Comment by ZhiHanZ** [comment]
> How about to only specify an address to enable users create all functions under the address, instead of specify both address and udf function name? e.g.:
> 
> ```
> udf_server_allow_list = [ "https://example.com/"]
> ```

LGTM

**Comment by wubx** [comment]
I wonder if I can set this as settings better than config.
