### ISSUE TITLE
bug: `max_if` function with a group by return an error message

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12853]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.112-nightly

### What's Wrong?

`max_if`/`min` function with a group by returning an error message

### How to Reproduce?

```sql
mysql> create table test(a boolean not null, b uint8 not null);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into test values(true, 10),(false, 20);
Query OK, 2 rows affected (0.03 sec)

mysql> SELECT max_if(1, a), to_timestamp(5140325614630), 1 FROM test GROUP BY to_timestamp(5140325614630), 1;
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "18446744073709551615". Valid fields: ["0"].

mysql> SELECT min(NULL), 1, a, b FROM test GROUP BY ROLLUP (1, a, b);
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "18446744073709551615". Valid fields: ["0", "1"].
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ariesdevil** [comment]
This seems not a bug, other DBMS also not supported

**Comment by b41sh** [comment]
> This seems not a bug, other DBMS also not supported

We should return an unsupported information, not an error like this, which is clearly an unexpected error.
