### ISSUE TITLE
bug: `arg_min` function with a group by cube panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12852]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.112-nightly

### What's Wrong?

`arg_min` function with a group by cube panic
```
panicked at 'called `Option::unwrap()` on a `None` value', src/query/functions/src/aggregates/aggregate_arg_min_max.rs:262:59
```

### How to Reproduce?

```mysql
mysql> create table test(a boolean not null, b uint8 not null);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into test values(true, 10),(false, 20);
Query OK, 2 rows affected (0.03 sec)

mysql> SELECT arg_min(b, 10), b FROM test GROUP BY CUBE (b);
ERROR 1105 (HY000): PanicError. Code: 1104, Text = called `Option::unwrap()` on a `None` value.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ariesdevil** [comment]
Same as https://github.com/datafuselabs/databend/issues/12853#issuecomment-1722480703

**Comment by sundy-li** [comment]
Related to grouping sets：

```
SELECT arg_min(b, 10), b FROM test GROUP BY GROUPING SETS(b);
```
