### ISSUE TITLE
feature:  Query Level Cache Metric

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#12862]
**Summary**

query level cache metrics, like:
```
bytes_scanned_from_memory_cache -- data scanned from the memory cache
bytes_scanned_from_disk_cache  -- data scanned from the local disk cache
```

**Comment by flaneur2020** [comment]
just watched a similiar metrics from a video about instacart's snowflake cost management which looks like this:

![Screenshot 2023-09-15 at 13 57 04](https://github.com/datafuselabs/databend/assets/129800/03c4851f-1bff-486f-ba9d-78f2c572fdc4)

**Comment by BohuTANG** [comment]
There is a related issue: https://github.com/datafuselabs/databend/issues/12841

**Comment by dantengsky** [comment]
> There is a related issue: #12841

:ok_hand:

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/databend/pull/14313
