### ISSUE TITLE
draw a picture for merge into operation's pipeline

### ISSUE THREAD

**Issue by SkyFan2002** [datafuselabs/databend#12901]
**Summary**
We will draw a picture to clarify execution flow of a complicated DML. For example:
https://github.com/datafuselabs/databend/blob/d64e5f6e21b4f9bb77e8c47aa4efe5043b807c5c/src/query/storages/fuse/src/operations/replace.rs#L46-L76 
@JackTan25 has marked a `todo` in code:
https://github.com/datafuselabs/databend/blob/d64e5f6e21b4f9bb77e8c47aa4efe5043b807c5c/src/query/storages/fuse/src/operations/merge.rs#L30

useful tool:
https://asciiflow.com/

**Comment by ct20000901** [comment]
/assign me

I've been reading the source code of 'merge_into' in the past few days, and I hope to organize this content.

**Comment by ct20000901** [comment]
This is the picture I drew. I have temporarily omitted the Pipeline in MergeIntoSource and the TransformAddComputedColumns operator. Is there any error in the process, and do I need to expand on the content I have omitted?

<img width="1153" alt="image" src="https://github.com/datafuselabs/databend/assets/52696678/7eb26b24-be15-4ffa-a4dd-012e808ffb54">

**Comment by JackTan25** [comment]
there will be a merge between match and not match

**Comment by ct20000901** [comment]
> there will be a merge between match and not match.[databend/src/query/storages/fuse/src/operations/replace.rs](https://github.com/datafuselabs/databend/blob/d64e5f6e21b4f9bb77e8c47aa4efe5043b807c5c/src/query/storages/fuse/src/operations/replace.rs#L46-L76) you can reference to this, give a complete pipeline.

<img width="1067" alt="image" src="https://github.com/datafuselabs/databend/assets/52696678/79d3b73f-ed3d-4021-afb9-7783b93a66a0">

I have rewritten it, including the parts that were previously omitted. I'm not sure if there are any errors.

**Comment by JackTan25** [comment]
maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.

**Comment by ct20000901** [comment]
> maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.

Alright, I previously observed that MergeIntoSource is pretty much similar to HashJoin, so I didn't expand on it. As for the Computed part, I admit I was just being lazy, haha.

**Comment by ct20000901** [comment]
> maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.



> maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.

But isn't the 'fill default' part referring to TransformResortAddOnWithoutSourceSchema? I believe I have already included this part in the diagram.

**Comment by JackTan25** [comment]
> > maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.
> 
> > maybe you can add fill default and computed expr? And also I think you can make it more complete like replace into. you can do it, try your best. Thanks.
> 
> But isn't the 'fill default' part referring to TransformResortAddOnWithoutSourceSchema? I believe I have already included this part in the diagram.

oh, yes, sorry for that.  you are right. just go on.
