### ISSUE TITLE
bug: cast float64 to decimal panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12910]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.118-nightly

### What's Wrong?

cast float64 to decimal panic
```
panicked at 'called `Option::unwrap()` on a `None` value', src/query/expression/src/types/decimal.rs:388:25
```

### How to Reproduce?

```sql
mysql> create table test (a double);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into test values (0.0941881516339449), (0.8833429252655464);
Query OK, 2 rows affected (0.04 sec)

mysql> select try_to_decimal(20, 19)(a) from test;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    20
Current database: *** NONE ***
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zenus** [comment]
I would like to solve this problem. Can you assign it to me?
