### ISSUE TITLE
Bug: failed to COPY a 4 columns CSV into a 5 columns table with one trailing column with DEFAULT

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#12976]
**Summary**

```
CREATE TABLE `people` (
  `id` BIGINT,
  `first_name` VARCHAR,
  `last_name` VARCHAR,
  `age` INT
) ENGINE=FUSE;

// add one column with DEFAULT value
ALTER TABLE people ADD COLUMN age2 INT DEFAULT 0;
```

```
COPY INTO eric.`people`
  PATTERN ='temp1.csv'
  FILE_FORMAT = (TYPE = 'CSV' field_delimiter = '|' record_delimiter = '\n' skip_header = 1 )
 DISABLE_VARIANT_CHECK = TRUE ;
```

Sample data in CSV, it have 4 columns.

```
"1363"|"j"|"j"|"10"
"1364"|"k"|"k"|"11"
"1365"|"l"|"l"|"12"
"1366"|"m"|"m"|"13"
"1367"|"n"|"n"|"14"
"1368"|"o"|"o"|"15"
"1369"|"p"|"p"|"16"
"1370"|"q"|"q"|"17"
```

error:

```
1046=>Number of columns in file (4) does not match that of the corresponding table (5)
```

**Comment by flaneur2020** [comment]
when I try:

```
INSERT INTO people VALUES (1, "a", "b", 12);
```

I got the following error:

```
Table columns count is not match, expect 5, input: 4, expr: [Literal { span: Some(1..2), lit: UInt64(1) }, ColumnRef { span: Some(4..8), database: None, table: None, column: Name(Identifier { name: "li", quote: Some('"'), span: Some(4..8) }) }, ColumnRef { span: Some(10..14), database: None, table: None, column: Name(Identifier { name: "jo", quote: Some('"'), span: Some(10..14) }) }, Literal { span: Some(16..18), lit: UInt64(12) }]
```

but postgres could handle the trailing columns with DEFAULT gracefully:

![Screenshot 2023-09-22 at 18 13 51](https://github.com/datafuselabs/databend/assets/129800/1140e07b-07cd-4227-8564-f2c19351e85b)

**Comment by sundy-li** [comment]
how about making copy support  optional column list like insert?

**Comment by youngsofun** [comment]
> how about making copy support optional column list like insert?

do you mean `copy into t(c1, c2) ... `

we already support it. but @flaneur2020 may hope  that user do not need to provide columns lists, if the missing columns in file is trailing columns of the table.

**Comment by youngsofun** [comment]
> when I try:
> 
> ```
> INSERT INTO people VALUES (1, "a", "b", 12);
> ```
> 
> I got the following error:
> 
> ```
> Table columns count is not match, expect 5, input: 4, expr: [Literal { span: Some(1..2), lit: UInt64(1) }, ColumnRef { span: Some(4..8), database: None, table: None, column: Name(Identifier { name: "li", quote: Some('"'), span: Some(4..8) }) }, ColumnRef { span: Some(10..14), database: None, table: None, column: Name(Identifier { name: "jo", quote: Some('"'), span: Some(10..14) }) }, Literal { span: Some(16..18), lit: UInt64(12) }]
> ```
> 
> but postgres could handle the trailing columns with DEFAULT gracefully:
> 
> ![Screenshot 2023-09-22 at 18 13 51](https://user-images.githubusercontent.com/129800/269908129-1140e07b-07cd-4227-8564-f2c19351e85b.png)

the pg appoach is not safe as a default behavior,  but we can support it with a new format option.

**Comment by BohuTANG** [comment]
> > how about making copy support optional column list like insert?
> 
> do you mean `copy into t(c1, c2) ... `
> 
> we already support it. but @flaneur2020 may hope that user do not need to provide columns lists, if the missing columns in file is trailing columns of the table.

This is more dangerous and not a better solution for many users, they can't grantee the right data into the right column.
