### ISSUE TITLE
Python Binding: support custom path to store data and metadata  

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#12992]
DuckDB, Hyper and Glaredb all support custom path to storage data, AFAIK databend by default use a hidden local folder, can we have the option to have a custom path

see example here

![image](https://github.com/datafuselabs/databend/assets/12554469/9f7e0353-b530-4f34-bd24-6061a6409f41)

https://colab.research.google.com/drive/11Jz3G1oqf8glye5BmNIq5cOdeUQJjImv#scrollTo=MDTt42NXEL5_

**Comment by djouallah** [comment]
any update on this please ?

**Comment by djouallah** [comment]
@BohuTANG @sundy-li  it seems python runtime is not updated yet ?

**Comment by BohuTANG** [comment]
The CI failed, re-running:
https://github.com/datafuselabs/databend/actions/runs/6442168965

**Comment by djouallah** [comment]
still does not work

**Comment by sundy-li** [comment]
I tested and it works, what are your test codes?

**Comment by djouallah** [comment]
CI is broken, the last update is still from 2 days ago

**Comment by BohuTANG** [comment]
Yes, github action is borken, re-try again:
https://github.com/datafuselabs/databend/actions/runs/6448635973

**Comment by djouallah** [comment]
still broken

**Comment by BohuTANG** [comment]
[bindings_python / build-aarch64-unknown-linux-gnu](https://github.com/datafuselabs/databend/actions/runs/6448635973/job/17515348949)
```
The hosted runner: GitHub Actions 4 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

We are try to fix it...

**Comment by djouallah** [comment]
Thanks, it did works
