### ISSUE TITLE
Feature: limit the system database are owned by account_admin by default

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#13032]
**Summary**

currently the system.tables are available to all the users.

however these tables are better to considered as admin-only.

we can leverage the DAC mechanism to limit the access of the system tables to be `account_admin` only (owned by `account_admin`).

**Comment by TCeason** [comment]
Also the information_schema's table?

**Comment by TCeason** [comment]
system.tables, system.databases, system.columns need owned by public.
