### ISSUE TITLE
bug: read decimal values failed in nested array with null value

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13058]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.132-nightly

### What's Wrong?

read decimal  values failed in nested array with null value

### How to Reproduce?

```sql
mysql> create table test(
    ->     c1 TUPLE(ARRAY(ARRAY(DECIMAL(40, 10)) null))
    -> );
Query OK, 0 rows affected (0.04 sec)

mysql> insert into test values (([NULL,NULL]));
Query OK, 1 row affected (0.05 sec)

mysql> select * from test;
ERROR 1105 (HY000): StorageOther. Code: 4000, Text = unexpected deserialization error, no array found for field c1 .
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ariesdevil** [comment]
arrow2 decimal with double nested list can pass the test. https://github.com/jorgecarleitao/arrow2/pull/1572

**Comment by ariesdevil** [comment]
fixed at https://github.com/jorgecarleitao/arrow2/pull/1573
