### ISSUE TITLE
bug: aggregate and window function as the argument of unnest return Unable to get field named

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.132-nightly

### What's Wrong?

aggregate and window function as the argument of unnest return Unable to get field named

### How to Reproduce?

```sql
mysql> select unnest(max(11));
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "18446744073709551615". Valid fields: [].

mysql> select unnest(first_value('aa') OVER (PARTITION BY 'bb'));
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "18446744073709551615". Valid fields: [].
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
cc @andylokandy

**Comment by sundy-li** [comment]
@Freejww can take this issue
