### ISSUE TITLE
bug: Can't run current version on podman. froze on line "Databend HTTP listened at 0.0.0.0:8000"

### ISSUE THREAD

**Issue by YuriyGavrilov** [datafuselabs/databend#13088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.129-nightly

### What's Wrong?

Frozen podman on this line:

```
Databend HTTP
    listened at 0.0.0.0:8000
    usage:  curl -u${USER} -p${PASSWORD}: --request POST '0.0.0.0:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "SELECT avg(number) FROM numbers(100000000)"}'
```

### How to Reproduce?

Just run

`podman run     -p 8000:8000     -e QUERY_DEFAULT_USER=databend     -e QUERY_DEFAULT_PASSWORD=databend     datafuselabs/databend`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
cc @everpcpc

**Comment by everpcpc** [comment]
```
Databend HTTP
    listened at 0.0.0.0:8000
    usage:  curl -u${USER} -p${PASSWORD}: --request POST '0.0.0.0:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "SELECT avg(number) FROM numbers(100000000)"}'
```
This means databend has successfully started rather than freezing.

**Comment by YuriyGavrilov** [comment]
@everpcpc I apologize for disturbing you, I realized what the problem was and figured it out. Thx!

**Comment by everpcpc** [comment]
It's OK, feel free if any further problem.
