### ISSUE TITLE
bug: Databend Query start failure, cause: StorageOther. Code: 4000, Text = invalid input parameter (region for s3 storage is not set and failed to auto detect, please check and set it manually).

### ISSUE THREAD

**Issue by YuriyGavrilov** [datafuselabs/databend#13091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.129-nightly

### What's Wrong?

I am trying to start with s3 support by https://github.com/storj/storj network. They just don't have region for their s3 api. 

tried this one fro here: https://github.com/datafuselabs/databend/tree/main/docker
`docker run \
    -p 8000:8000 \
    -e QUERY_STORAGE_TYPE=s3 \
    -e AWS_S3_ENDPOINT="http://some_s3_endpoint" \
    -e AWS_S3_BUCKET=some_bucket \
    -e AWS_ACCESS_KEY_ID=some_key \
    -e AWS_SECRET_ACCESS_KEY=some_secret \
    datafuselabs/databend`

### How to Reproduce?

just run docker with this 

`docker run \
    -p 8000:8000 \
    -e QUERY_STORAGE_TYPE=s3 \
    -e AWS_S3_ENDPOINT="https://gateway.storjshare.io" \
    -e AWS_S3_BUCKET=test \
    -e AWS_ACCESS_KEY_ID=XXXXXXX \
    -e AWS_SECRET_ACCESS_KEY=XXXXXXX \
    datafuselabs/databend`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by everpcpc** [comment]
Try `-e AWS_REGION=auto`
