### ISSUE TITLE
Feature:  more convenient date function calls: date_part

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#13167]
**Summary**
User migration  GP to Databend want calculate date to weekofyear.  User SQL use date_part. 
Reference: https://docs.snowflake.com/en/sql-reference/functions/date_part 

```
select date_part(yearofweek,now());
```
support full date_or_time_part
https://docs.snowflake.com/en/sql-reference/functions/year

**Comment by TCeason** [comment]
1. support week_of_year to.

2. `EXTRACT((YEAR | QUARTER | MONTH | DAY | HOUR | MINUTE | SECOND) FROM ...)` maybe can replace date_part function.
