### ISSUE TITLE
bug: Cannot start on macOS

### ISSUE THREAD

**Issue by webfrank** [datafuselabs/databend#13174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.2.150-nightly-x86_64-apple-darwin

### What's Wrong?

databend-query does not start with error:

RUST_BACKTRACE=1 bin/databend-query -c configs/databend-query.toml
<jemalloc>: No getcpu support: percpu_arena:percpu
<jemalloc>: option background_thread currently supports pthread only
Databend Query start failure, cause: StorageOther. Code: 4000, Text = Unexpected (permanent) at  => async client build failed, source: builder error: The Trust Settings Record was corrupted..

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::create
   2: backtrace::capture::Backtrace::new
   3: common_exception::exception_backtrace::capture
   4: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::StorageOther
   5: common_exception::exception_into::<impl core::convert::From<opendal::types::error::Error> for common_exception::exception::ErrorCode>::from
   6: common_sharing::share_endpoint::ShareEndpointManager::init
   7: databend_query::global_services::GlobalServices::init_with::{{closure}}::{{closure}}
   8: std::thread::local::LocalKey<T>::with
   9: std::thread::local::LocalKey<T>::with
  10: databend_query::global_services::GlobalServices::init::{{closure}}
  11: std::thread::local::LocalKey<T>::with
  12: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll{{reify.shim}}
  13: std::panicking::try
  14: <common_base::runtime::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll
  15: tokio::runtime::park::CachedParkThread::block_on
  16: tokio::runtime::handle::Handle::block_on
  17: databend_query::main
  18: std::sys_common::backtrace::__rust_begin_short_backtrace
  19: std::rt::lang_start::{{closure}}
  20: std::rt::lang_start_internal
  21: _main

### How to Reproduce?

Download tar.gz from site and follow standalone deployment on macOs

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
databend-v1.2.150-nightly-x86_64-apple-darwin is for x86_64 platform.
Maybe you should use:databend-v1.2.151-nightly-aarch64-apple-darwin
```
wget https://repo.databend.rs/databend/v1.2.151-nightly/databend-v1.2.151-nightly-aarch64-apple-darwin.tar.gz
```

**Comment by webfrank** [comment]
On an intel mac?

Il giorno mer 11 ott 2023 alle 02:02 wubx ***@***.***> ha
scritto:

**Comment by everpcpc** [comment]
This seems like a trust store issue: https://github.com/rustls/rustls-native-certs/issues/4

Maybe you could try with sudo.
