### ISSUE TITLE
bug: inner type of nested type can not be set as not null

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.154-nightly

### What's Wrong?

inner type of nested type can not be set as not null

### How to Reproduce?

```sql
mysql> create table test(a int, b array(int not null));
ERROR 1105 (HY000): SyntaxException. Code: 1005, Text = error:
  --> SQL:1:38
  |
1 | create table test(a int, b array(int not null))
  | ------                   - -----     ^^^ expected `NULL`, `UNSIGNED`, `)`, or `(`
  | |                        | |
  | |                        | while parsing type name
  | |                        while parsing `<column name> <type> [DEFAULT <expr>] [AS (<expr>) VIRTUAL] [AS (<expr>) STORED] [COMMENT '<comment>']`
  | while parsing `CREATE TABLE [IF NOT EXISTS] [<database>.]<ta
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zenus** [comment]
/ assign me

**Comment by zenus** [comment]
@b41sh        the right syntax should be create table test(a int, b array(int) not null);

**Comment by b41sh** [comment]
> @b41sh the right syntax should be create table test(a int, b array(int) not null);

the inner type should also support set null or not null
