### ISSUE TITLE
bug: not check nested call aggregate functions

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.154-nightly

### What's Wrong?

not check nested call aggregate functions

### How to Reproduce?

```sql
mysql> create table test(a int, b date);
Query OK, 0 rows affected (0.25 sec)

mysql> select arg_min(DATE_ADD(MINUTE, COUNT(*), b), a) FROM test;
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "18446744073709551615". Valid fields: ["0", "1"].
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zenus** [comment]
@b41sh What should be the correct result?

**Comment by b41sh** [comment]
> @b41sh What should be the correct result?

should return Semantic Error `aggregate function calls cannot be nested`
