### ISSUE TITLE
doc: databend ENV

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13258]
**Summary**

Add `ENV` list to the deployment.

**Comment by soyeric128** [comment]
We already have a page for this: https://databend.rs/doc/deploy/node-config/environment-variables

**Comment by BohuTANG** [comment]
databend-meta is fine. 
databend-query ENV needs user-relevant examples. @everpcpc found inconsistencies in some ENV naming, beyond just the QUERY prefix.
Please have a check, also cc @PsiACE 

There is a issue from the slack about it:
https://databend.slack.com/archives/C01QT5FFH34/p1697176840414549

**Comment by PsiACE** [comment]
> databend-query ENV needs user-relevant examples. some ENV naming, beyond just the QUERY prefix. Please have a check, also cc @PsiACE

Yes, I mentioned this issue in a blog post about configuration files and corresponding environment variables. Specifically, the corresponding relationship can be understood using the logic of "scope + configuration item", but it is necessary to check the code. 

Perhaps we can provide an English version.  However, do we need a complete mapping table for environment variables, configuration items, and command line parameters?

**Comment by BohuTANG** [comment]
The prefix with the config item is make sense.
The problem is that why the config item with a prefix is not env variables?

**Comment by PsiACE** [comment]
> The prefix with the config item is make sense. The problem is that why the config item with a prefix is not env variables?

This is determined by the form of (de)serialisation it uses, which works fine most of the time and is mainly handled by serfig.

**Comment by PsiACE** [comment]
>  The problem is that why the config item with a prefix is not env variables?

I think this comment can answer some questions.

Query and Meta's own configuration options meet the mapping between environment variables. Users can use the environment variables mentioned by Eric to set them correctly, which also aligns with the default logic in my previous blog post.

However, we did not disable the environment variables that are more closely aligned with user usage habits supported by `resign`. As a result, when the configuration is not set according to our standards, there may be rollbacks. At this time, resign will read some built-in environment variables and if the user has set these environment variables, it can still function properly.

ref: https://github.com/datafuselabs/databend/pull/13290#issuecomment-1769296431 .
