### ISSUE TITLE
can't read databend database stored in google drive

### ISSUE THREAD

**Issue by djouallah** [datafuselabs/databend#13262]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Version: 1.2.160

### What's Wrong?

can't read data saved previously in google drive

### How to Reproduce?

store data in google drive using

```
from google.colab import drive
drive.mount('/mount', force_remount=True)
os.environ["DATABEND_DATA_PATH"] = "/mount/MyDrive/db/databend/"
```
data is saved as expected

close notebook and delete the runtime

try to read the same data using

```
import os
os.environ["DATABEND_DATA_PATH"] = "/mount/MyDrive/db/databend/"
from databend import SessionContext
ctx_bend = SessionContext()
databend = execute_query(ctx_bend, sql)
```

get errors 

Query1
Error: UnknownTable. Code: 1025, Text = Unknown table `default`.`lineitem` in catalog 'default'.
0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
That's weired, I try to reproduce it now.

**Comment by sundy-li** [comment]
Oh, the `SessionContext` is default to use random tenant.

You can specify the tenant name.


```
import os
os.environ["DATABEND_DATA_PATH"] = "/tmp/databend_tmp/"
from databend import SessionContext
ctx_bend = SessionContext("google")

ctx_bend.sql("show tables")
ctx_bend.sql("create table test(a int)").collect()
```

**Comment by djouallah** [comment]
perfect !!!
