### ISSUE TITLE
feat: APPROX_PERCENTILE function

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13305]
**Summary**

https://docs.snowflake.com/en/sql-reference/functions/approx_percentile

**Comment by sundy-li** [comment]
QUANTILE_TDIGEST

**Comment by srsharathreddy-92** [comment]
It will be helpful to add weighed approximate functionality as well.

Referecene : Presto SQL:
approx_percentile(x, w, percentage) → 
Returns the approximate weighed percentile for all input values of x using the per-item weight w at the percentage p. The weight must be an integer value of at least one. It is effectively a replication count for the value x in the percentile set. The value of p must be between zero and one and must be constant for all input rows.

presto [Link](https://prestodb.io/docs/current/functions/aggregate.html) : approx_percentile(x, w, percentage) → [same as x][#](https://prestodb.io/docs/current/functions/aggregate.html#id10)
