### ISSUE TITLE
fix: check database & tables visibilities with ownerships

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#13314]
currently the visibility check logics are privilege only, we need consider ownership together.

the rules:

1. if an user have any privilege on an object, then she can view it.
2. if an user have a visibility about an table, then she can also view the database.
3. if an user owns a database, then she can view any table under it.

**Comment by TCeason** [comment]
Now we use other way https://github.com/datafuselabs/databend/pull/14238 cover this issue. Let's close it.
