### ISSUE TITLE
Enhancement: http handler returns status when running a long query

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13351]
**Summary**

When executing a COPY from a stage containing over 70,000 parquet files, the COPY operation does not provide a status update during its run. This can cause the bendsql to hang if databend-query runs out of memory. 

This issue is also observed in the Cloud.

**Comment by youngsofun** [comment]
long time bind: read parquet metas  to get statitics

https://github.com/datafuselabs/databend/blob/39edeba2cc5e4ae6d0a2de20a5999bf441d2f27f/src/query/storages/parquet/src/parquet2/parquet_table/create.rs#L57

I can run a

**Comment by youngsofun** [comment]
todo

- [ ]  run `plan_sql` async in http handler, not blocking http return
- [ ] copy parquet should not base on select parquet any more

2.

**Comment by BohuTANG** [comment]
> long time bind: read parquet metas to get statitics
> 
> https://github.com/datafuselabs/databend/blob/39edeba2cc5e4ae6d0a2de20a5999bf441d2f27f/src/query/storages/parquet/src/parquet2/parquet_table/create.rs#L57

These cases will be block by this design:
1.  distributed COPY -- it seems no need the meta read
2. distributed read parquet files -- we should each node get the parquet files and read meta

To make distributed **fast**, we should distributed the file first, then do the meta info read.

cc @Dousir9 @RinChanNOWWW

**Comment by youngsofun** [comment]
@BohuTANG 

1. for copy parquet, not need to read metas early. it should has it own impl.
2. for select paruqet,  paruqetTable is read as normal Table, so there are some limits. 
3. so we can do `run plan_sql async in http handler, not blocking http return` first to lighten current problem, and forbind similar problems later. then re-impl copy,

**Comment by youngsofun** [comment]
fixed by https://github.com/datafuselabs/databend/pull/14908
