### ISSUE TITLE
Feature: tweak auto compaction strategy

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#13357]
**Summary**

turns out, auto compaction for `copy/insert` is not "the best practice".

**update(2023-10-31):**

To achieve a balance between the cost of trivial compactions and the convenience of table maintenance, the "auto/implicit compaction" feature should only be triggered when there are a few small blocks present:

- introduce a new setting `auto_compaction_threshold`
  by default, it is set to 1000
- after data has been ingested,  check the number of imperfect-sized blocks.
  i.e table_snapshot.summary.block_count - table_snapshot.summary.perfect_block_count
  trigger the compaction, only if it is larger than `auto_compaction_threshold`.
  

Keep the compaction behaviors as they are when executing "replace/merge into" statements, since optimal performance of them may rely heavily on timely compaction and reclustering.

**Comment by BohuTANG** [comment]
Hi @zenus 

Thank you for taking this. However, I believe there are some considerations before deeming it a suitable issue.
We should:
- Evaluate the performance both when it's enabled and disabled. -- this is complex
- Based on the findings, make an informed decision on whether to disable it.

**Comment by zenus** [comment]
i see

**Comment by dantengsky** [comment]
@wubx @BohuTANG 

Seems the auto-compaction strategy should be adjusted?  Please review the updated PR summary.
