### ISSUE TITLE
bug: query with `\G` always end with "ERROR: No query specified"

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#13352]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

current version

### What's Wrong?

all query with '\G' always end with:

```
ERROR:
No query specified
```

### How to Reproduce?

SELECT * FROM system.functions \G;

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
If user '\G' as end delimiter , should not use ';'.

e.g. 

```sql
-- this will ok
select * from system.functions limit 1\G
```
