### ISSUE TITLE
Feature:  bring back tracings

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#13370]
**Summary**

We used to have the ability to trace, but currently, it appears to be malfunctioning. 

![image](https://github.com/datafuselabs/databend/assets/22081156/cc66e5c8-89db-459f-81ed-c8f288d93940)

let's bring it back?

**Comment by BohuTANG** [comment]
minitrace-jaeger: https://crates.io/crates/minitrace-jaeger

**Comment by andylokandy** [comment]
This feature breakage is caused by the latest port change in jaeger-all-in-one's docker image.
