### ISSUE TITLE
bug: (docs) scroll bar flickering with search modal input

### ISSUE THREAD

**Issue by washanhanzi** [datafuselabs/databend#13395]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

13fe3f9770ad42baf6e3a195137fa0a00a85e74c

### What's Wrong?

https://github.com/datafuselabs/databend/assets/56581242/e593a47c-9d21-48fd-a95c-92d5ef90e7a9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @Chasen-Zhang

**Comment by TCeason** [comment]
Now databend doc is split into https://github.com/datafuselabs/databend-docs
