### ISSUE TITLE
Feature: Show statements support more filter options

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#13407]
**Summary**

Description for this feature.

Introduce a new struct `ShowOptions`:
```
struct ShowOptions { 
    filter: Option<Expr>,
    limit: Option<usize>
}
```
into 

```
ShowSettings, ShowProcessList, ShowMetrics, ShowEngines, ShowFunctions, ShowTableFunctions, ShowIndexes
```

Thus we could use:

```
>  show settings like '%xxx%'
>  show settings where name = 'xxx' and level = 'GLOBAL'; 
>  show metrics limit 3;

etc
```

**Comment by guojidan** [comment]
I'm interested in this, please assign to me

**Comment by guojidan** [comment]
I fork `main` branch and create new branch from `main`, build databend from source, but the query node can not connect meta node, but the `v1.2.184-nightly` work fine, so how should I develop testing, the error log  is as follows：

> panicked at 'run `git fetch --tags` to solve this error,
>    to learn more about this error, please visit https://crates.io/crates/semver: Error("unexpected character 'D' while parsing major version number")', src/meta/client/src/lib.rs:43:28
>   0: common_tracing::panic_hook::log_panic
>             at ./src/common/tracing/src/panic_hook.rs:35:21
