### ISSUE TITLE
bug: Can't skip CSV header with query stage 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#13419]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

 v1.2.175

### What's Wrong?

```
create file format mycsv_sp_h1 type=csv skip_header=1;
select $1,$2 from @t_stage/商铺数据.csv (format_name => 'mycsv_sp_h1') limit 10;
```
<img width="527" alt="image" src="https://github.com/datafuselabs/databend/assets/320680/c3f89a10-26f8-4735-8bf5-119e939613d5">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @youngsofun

**Comment by youngsofun** [comment]
@wubx https://databend.rs/doc/load-data/transform/querying-stage#syntax-and-parameters
argname is  `file_format` not `format_name`

**Comment by youngsofun** [comment]
let us report error about wrong args.

**Comment by BohuTANG** [comment]
We should not allowed the invalid args in the file format instead give the error after the created?
