### ISSUE TITLE
Feature: add translate() funtion

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#13432]
**Summary**

to reduce the nested calls of replace().
eg.
use
translate('abcde','abc','ABC') instead of
replace(replace(replace('abcde','a','A'),'b','B'),'c','C')
ref https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions181.htm
https://www.postgresql.org/docs/current/functions-string.html

Syntax:
```
TRANSLATE( <subject>, <sourceAlphabet>, <targetAlphabet> )
```

Example:
```
SELECT TRANSLATE('abcde','abc','ABC');
+--------------------------------+
| TRANSLATE('abcde','abc','ABC') |
|--------------------------------|
| ABCdef                         |
+--------------------------------+
```

**Comment by guojidan** [comment]
I'm interested in this, please assign to me : )

**Comment by guojidan** [comment]
`replace` function  already support this 
root@localhost:8000/default> SELECT REPLACE('www.mysql.com', 'www', 'Ww');

SELECT
  REPLACE('www.mysql.com', 'www', 'Ww')

┌───────────────────────────────────────┐
│ replace('www.mysql.com', 'www', 'ww') │
│                 String                │
├───────────────────────────────────────┤
│ Ww.mysql.com                          │
└───────────────────────────────────────┘
1 row read in 0.133 sec. Processed 1 row, 1 B (7.52 row/s, 7 B/s)

**Comment by TCeason** [comment]
> `replace` function already support this root@localhost:8000/default> SELECT REPLACE('www.mysql.com', 'www', 'Ww');
> 
> SELECT REPLACE('www.mysql.com', 'www', 'Ww')
> 
> ┌───────────────────────────────────────┐ │ replace('www.mysql.com', 'www', 'ww') │ │ String │ ├───────────────────────────────────────┤ │ Ww.mysql.com │ └───────────────────────────────────────┘ 1 row read in 0.133 sec. Processed 1 row, 1 B (7.52 row/s, 7 B/s)

No. You can see this doc : https://www.postgresql.org/docs/current/functions-string.html

```sql

postgres=# SELECT TRANSLATE('abcde','abe','123');
 translate 
-----------
 12cd3
(1 row)


```

**Comment by TCeason** [comment]
translate ( string text, from text, to text ) → text
```
Replaces each character in string that matches a character in the from set with the corresponding character in the to set. If from is longer than to, occurrences of the extra characters in from are deleted.

translate('12345', '143', 'ax') → a2x5
```

replace ( string text, from text, to text ) → text
```
Replaces all occurrences in string of substring from with substring to.

replace('abcdefabcdef', 'cd', 'XX') → abXXefabXXef
```

**Comment by guojidan** [comment]
like this?

root@localhost:8000/default> select translate('abcdefabcdef', 'dc', 'zy');

SELECT
  translate('abcdefabcdef', 'dc', 'zy')

┌───────────────────────────────────────┐
│ translate('abcdefabcdef', 'dc', 'zy') │
│                 String                │
├───────────────────────────────────────┤
│ abyzefabyzef                          │
└───────────────────────────────────────┘
1 row read in 0.062 sec. Processed 1 row, 1 B (16.07 row/s, 16 B/s)

**Comment by TCeason** [comment]
> like this?
> 
> 
> 
> root@localhost:8000/default> select translate('abcdefabcdef', 'dc', 'zy');
> 
> 
> 
> SELECT
> 
>   translate('abcdefabcdef', 'dc', 'zy')
> 
> 
> 
> ┌───────────────────────────────────────┐
> 
> │ translate('abcdefabcdef', 'dc', 'zy') │
> 
> │                 String                │
> 
> ├───────────────────────────────────────┤
> 
> │ abyzefabyzef                          │
> 
> └───────────────────────────────────────┘
> 
> 1 row read in 0.062 sec. Processed 1 row, 1 B (16.07 row/s, 16 B/s)

Yes

**Comment by guojidan** [comment]
in this doc: https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions181.htm , `to string` cannot empty, so Can `to string` be empty for us?

**Comment by l1t1** [comment]
if  null and ‘’ are not equal in databend, permit empty is better

**Comment by guojidan** [comment]
ok, I tested it, empty can work
