### ISSUE TITLE
improve: create external location table with URL

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13467]
**Summary**

Now:
```
CREATE TABLE [IF NOT EXISTS] [db.]table_name

    <column_name> <data_type> [ NOT NULL | NULL] [ { DEFAULT <expr> }],
    <column_name> <data_type> [ NOT NULL | NULL] [ { DEFAULT <expr> }],
    ...

's3://<bucket>/[<path>]' 
CONNECTION = (
        ENDPOINT_URL = 'https://<endpoint-URL>'
        ACCESS_KEY_ID = '<your-access-key-ID>'
        SECRET_ACCESS_KEY = '<your-secret-access-key>'
        REGION = '<region-name>'
        ENABLE_VIRTUAL_HOST_STYLE = 'true'|'false'
  );
```
https://databend.rs/doc/sql-commands/ddl/table/ddl-create-table#create-table--external_location

Better:
```
CREATE TABLE [IF NOT EXISTS] [db.]table_name

    <column_name> <data_type> [ NOT NULL | NULL] [ { DEFAULT <expr> }],
    <column_name> <data_type> [ NOT NULL | NULL] [ { DEFAULT <expr> }],
    ...

URL = 's3://<bucket>/[<path>]' 
CONNECTION = (
        ENDPOINT_URL = 'https://<endpoint-URL>'
        ACCESS_KEY_ID = '<your-access-key-ID>'
        SECRET_ACCESS_KEY = '<your-secret-access-key>'
        REGION = '<region-name>'
        ENABLE_VIRTUAL_HOST_STYLE = 'true'|'false'
  );
```

Then, this is same style as stage:
https://databend.rs/doc/sql-commands/ddl/stage/ddl-create-stage#externalstageparams
```
externalLocation ::=
  URL = "webhdfs://<endpoint_url>[<path>]"
  CONNECTION = (
        <connection_parameters>
  )
```

This change should be not a breaking change.

**Comment by BohuTANG** [comment]
We can do this in the parser? @andylokandy

**Comment by andylokandy** [comment]
It's possible but I've some questions:

1. Is the `URL =` optional?
2. Can `URL = ...` and `CONNECTION = ...` swap their position?

**Comment by BohuTANG** [comment]
> 1. Is the `URL =` optional? i.e.`[URL =] 's3://<bucket>/[<path>]' `
In this case `URL` is not a option, we must provider.

> 2. Can `URL = ...` and `CONNECTION = ...` swap their position?

Yes. It's same like `stage` syntax;

**Comment by andylokandy** [comment]
> In this case URL is not a option, we must provider.

So it will be a breaking change, right?

**Comment by BohuTANG** [comment]
Not a breaking change, the old way users is in use.
We can supports both?

**Comment by andylokandy** [comment]
Do you mean we support both

```
CREATE TABLE ... 's3://<bucket>/[<path>]'
```

and 

```
CREATE TABLE ... URL = 's3://<bucket>/[<path>]'
```
?

And in the case of 

```
CREATE TABLE ... 's3://foo/aaa' URL = 's3://foo/bbb'
```

an error should be reported.

**Comment by BohuTANG** [comment]
@andylokandy Yes.
