### ISSUE TITLE
I fork `main` branch and create new branch from `main`, build databend from source, but the query node can not connect meta node, but the `v1.2.184-nightly` work fine, so how should I develop testing, the error log  is as follows：

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13501]
I fork `main` branch and create new branch from `main`, build databend from source, but the query node can not connect meta node, but the `v1.2.184-nightly` work fine, so how should I develop testing, the error log  is as follows：

> panicked at 'run `git fetch --tags` to solve this error,
>    to learn more about this error, please visit https://crates.io/crates/semver: Error("unexpected character 'D' while parsing major version number")', src/meta/client/src/lib.rs:43:28
>   0: common_tracing::panic_hook::log_panic
>             at ./src/common/tracing/src/panic_hook.rs:35:21

_Originally posted by @guojidan in https://github.com/datafuselabs/databend/issues/13407#issuecomment-1786319321_

**Comment by BohuTANG** [comment]
@guojidan Could you give more information about your local deploy?

**Comment by guojidan** [comment]
I just modify parse sql code. https://github.com/guojidan/databend/commit/7f1412c27d3e3e2bf31d00e9ab7e7265da1c24c3

**Comment by BohuTANG** [comment]
You changes not releated to this issue.
What's the error when query can not connection to meta? It would be better to give more logs of them.

**Comment by guojidan** [comment]
I start meta-node `target/debug/databend-meta --single --log-level=ERROR`
and then I start query node use this command ` target/debug/databend-query -c scripts/ci/deploy/config/databend-query-node-1.toml`, I got this err log: 

root@dandan:~/code/rust/databend# target/debug/databend-query -c scripts/ci/deploy/config/databend-query-node-1.toml
panicked at 'run `git fetch --tags` to solve this error,
    to learn more about this error, please visit https://crates.io/crates/semver: Error("unexpected character 'D' while parsing major version number")', src/meta/client/src/lib.rs:43:28
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: unwrap_failed
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1651:5
   9: core::result::Result<T,E>::expect
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/result.rs:1033:23
  10: common_meta_client::METACLI_COMMIT_SEMVER::{{closure}}
             at ./src/meta/client/src/lib.rs:43:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  13: once_cell::sync::Lazy<T,F>::force::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1312:28
  14: once_cell::sync::OnceCell<T>::get_or_init::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1122:57
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/imp_std.rs:72:23
  16: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:294:13
  17: once_cell::imp::initialize_or_wait
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/imp_std.rs:196:20
  18: once_cell::imp::OnceCell<T>::initialize
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/imp_std.rs:68:9
  19: once_cell::sync::OnceCell<T>::get_or_try_init
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1163:13
  20: once_cell::sync::OnceCell<T>::get_or_init
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1122:19
  21: once_cell::sync::Lazy<T,F>::force
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1311:13
  22: <once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1378:13
  23: common_meta_client::grpc_client::MetaGrpcClient::make_client::{{closure}}::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:637:17
  24: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  25: common_meta_client::grpc_client::MetaGrpcClient::make_client::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:588:83
  26: <common_base::future::TimingFuture<T,F> as core::future::future::Future>::poll
             at ./src/common/base/src/future.rs:76:19
  27: common_meta_client::grpc_client::MetaGrpcClient::kv_api::{{closure}}::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:985:18
  28: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  29: common_meta_client::grpc_client::MetaGrpcClient::kv_api::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:971:5
  30: <common_base::future::TimingFuture<T,F> as core::future::future::Future>::poll
             at ./src/common/base/src/future.rs:76:19
  31: common_meta_client::grpc_client::MetaGrpcClient::worker_loop::{{closure}}::{{closure}}::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:434:30
  32: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  33: common_meta_client::grpc_client::MetaGrpcClient::worker_loop::{{closure}}::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:522:14
  34: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  35: common_meta_client::grpc_client::MetaGrpcClient::worker_loop::{{closure}}
             at ./src/meta/client/src/grpc_client.rs:382:95
  36: <common_base::runtime::runtime_tracker::UnlimitedFuture<T> as core::future::future::Future>::poll
             at ./src/common/base/src/runtime/runtime_tracker.rs:558:9
  37: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  38: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  39: std::thread::local::LocalKey<T>::try_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  40: std::thread::local::LocalKey<T>::with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  41: async_backtrace::frame::active_frame::with
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  42: async_backtrace::frame::Frame::in_scope
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  43: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  44: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  46: tokio::runtime::task::core::Core<T,S>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  47: tokio::runtime::task::harness::poll_future::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  48: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  49: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  50: __rust_try
  51: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  52: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  53: tokio::runtime::task::harness::poll_future
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  54: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  55: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  56: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  57: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  58: tokio::runtime::task::LocalNotified<S>::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  59: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:487:21
  60: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  61: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  62: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  63: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  64: tokio::runtime::scheduler::multi_thread::worker::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  65: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  66: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  67: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  68: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  69: tokio::runtime::task::core::Core<T,S>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  70: tokio::runtime::task::harness::poll_future::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  71: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  72: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  73: __rust_try
  74: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  75: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  76: tokio::runtime::task::harness::poll_future
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  77: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  78: tokio::runtime::task::harness::Harness<T,S>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  79: tokio::runtime::task::raw::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  80: tokio::runtime::task::raw::RawTask::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  81: tokio::runtime::task::UnownedTask<S>::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  82: tokio::runtime::blocking::pool::Task::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  83: tokio::runtime::blocking::pool::Inner::run
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  84: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  85: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  86: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  87: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  88: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  89: __rust_try
  90: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  91: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  92: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  93: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  94: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  95: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  96: start_thread
             at /build/glibc-BHL3KM/glibc-2.31/nptl/pthread_create.c:477:8
  97: clone
             at /build/glibc-BHL3KM/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Databend Query start failure, cause: MetaServiceError. Code: 2001, Text = meta-client dedicated runtime error: tokio::sync::oneshot::error::RecvError: channel closed while: when recv resp from MetaGrpcClient worker.

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable>

**Comment by guojidan** [comment]
[err-log.txt](https://github.com/datafuselabs/databend/files/13211621/err-log.txt)

this file is err log

**Comment by BohuTANG** [comment]
It's a build issue:
`Error("unexpected character 'D' while parsing major version number")'` 

Make sure the target build version works:
```
databend-query --version
```

**Comment by guojidan** [comment]
thank you for your help 👍 , I succeeded
