### ISSUE TITLE
feat: seperate primary role and secondary role

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#13544]
may looks like: https://docs.snowflake.com/en/sql-reference/sql/use-secondary-roles

- Make secondary roles default as ALL, so every roles' privileges take effect, when you create a database, it's owned by the CURRENT ROLE
- If the secondary roles are NONE, only the privileges of CURRENT ROLE take effect

**Comment by guojidan** [comment]
assign to me : )

**Comment by BohuTANG** [comment]
@guojidan Sorry this not a general issue, it's a complex refactor, we already working on it.

**Comment by guojidan** [comment]
> @guojidan Sorry this not a general issue, it's a complex refactor, we already working on it.

ok, I will choose another one, Do you have any suggestions

**Comment by BohuTANG** [comment]
@guojidan https://github.com/datafuselabs/databend/labels/good%20first%20issue Feel free to discuss and taking :)
