### ISSUE TITLE
feature: support otlp_endpoint for system & query log

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#13617]
**Summary**

Now that we support otlp endpoint for tracing, then we could also add support for sending logs to OTLP endpoint other than file & stderr, for better log collection in stateless environment.

**Comment by flaneur2020** [comment]
https://crates.io/crates/opentelemetry-appender-log it seems that this crate can helps bridge the rust logs with otel q.q

**Comment by ZhiHanZ** [comment]
I think we need to bring necessary fields into the query log when send to the endpoint, as for sidecar/local env it is easy to get its container/host, when send logs to otlp_endpoint, we need to add those info by ourselves, especially for tenant, cluster_id and background.Enabled

**Comment by flaneur2020** [comment]
![img_v2_9be337e9-9f60-4cd3-a73a-a2520dbb9c7g](https://github.com/datafuselabs/databend/assets/129800/ba2eb309-2fce-488e-b89c-829977aebcea)

it will have many benefits on using a daemonset instead of a sidecar to collect the logs.

there're simply too much uncertainty on managing the termination between the main container and the sidecars.

**Comment by flaneur2020** [comment]
it seems that the otel log bridge did not offer any option to pass the contexual metadata:

https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-appender-log/src/lib.rs#L32

but it's possible to pass the attributes in the log record builder:

https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/record.rs#L345

and the attributes is parseable in the vector side.

maybe we can consider copy-paste the log appender inside our project to match our needs to pass the attributes.
