### ISSUE TITLE
ClickHouse style kill query statement

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#1361]
**Summary**

https://github.com/datafuselabs/datafuse/pull/1280#issuecomment-894912653

**Comment by xuyifangreeneyes** [comment]
@zhang2014 can I have a try on the feature?

**Comment by xuyifangreeneyes** [comment]
@zhang2014 @sundy-li @BohuTANG  Hi, I try to implement the feature but I have some problems. ClickHouse style kill query statement is like:
```
KILL QUERY <where expression to SELECT FROM system.processes query>
```
And `system.processes` has the following fields:
- `user`(String)
- `address`(String)
- `elapsed (Float64)
- `rows_read` (UInt64)
- `bytes_read` (UInt64)
- `total_rows_approx` (UInt64)
- `memory_usage` (UInt64)
- `query` (String)
- `query_id` (String)

I think there are two methods to implement the feature:

1. Modify `ProcessesTable` to be consistent with `system.processes` in ClickHouse. Fetch the results of `SELECT * FROM system.processes where xxx` and kill them one by one. 
2. Directly convert `<where expression to SELECT FROM system.processes query>` to some conditions, find and kill the queries satisfying those conditions.  We can check whether those conditions are satisfied through `DatafuseQueryContextShared` or other structs in memory.

Could you give me some suggestions on which way I should follow, thinks a lot!

**Comment by zhang2014** [comment]
Maybe we can do it in interpreter_kill, execute `SELECT id from system.processes where {some predicate}` and kill them
