### ISSUE TITLE
docs: integrate the udf server into docs

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#13613]
**Summary**

currently we have an README about the UDF server, but it cannot be found in the databend.rs docs.

https://github.com/datafuselabs/databend/tree/main/tests/udf-server

there's also a shortcoming in this README, is that which sdk should I install? we'd better release a package into the pypi registry.

**Comment by TCeason** [comment]
Maybe task about doc can migrate to https://github.com/datafuselabs/databend-docs

**Comment by flaneur2020** [comment]
thank you for reminding, migrated to https://github.com/datafuselabs/databend-docs/issues/3
