### ISSUE TITLE
Feature: improve table function fuse_encoding

### ISSUE THREAD

**Issue by SkyFan2002** [datafuselabs/databend#13634]
**Summary**

`fuse_encoding` is first introduced in #13264. It's very difficult to use and has a lot of room for improvement. I believe it would be great if it could be used like this:

Query all encoding scheme of columns of bigint type from database `tpch_sf100`:
```sql
select column_name,level_one,level_two 
from fuse_encoding('tpch_sf100') 
where column_type = "bigint"
group by level_one,level_two
order by column_name;
```
Query compress ratio of columns of bigint type from database `tpch_sf100`:
```sql
select sum(uncompressed_size),sum(compressed_sisze), sum(uncompressed_size) / sum(compressed_sisze) as ratio
from fuse_encoding('tpch_sf100') 
where column_type = "bigint")
group by column_name;
```
Simple implementation idea:
1. make `fuse_encoding` only accepts one parameter，`database_name`.
2. add new columns: `table_name`,  `column_name`, `column_type`.
3. when `fuse_encoding` is queried, `table_name`, `column_name`, `column_type` in filter should be pushed down to the table function implemention.

**Comment by guojidan** [comment]
please assign to me

**Comment by TCeason** [comment]
> please assign to me

Good and keep balance between work and leisure~
