### ISSUE TITLE
[ci] Add MergePullRequest + UnitTests  workflow

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#1373]
**Summary**

Currently, the ci only do tests on the pr brach, we should add `MergePullRequest + UnitTests  workflow` to avoid merge bugs.

**Comment by drmingdrmer** [comment]
CI tests pr + master_1. But when CI finished, master becomes master_2. master_2 + pr is not tested then, but can be merged...

**Comment by sundy-li** [comment]
> CI tests pr + master_1. But when CI finished, master becomes master_2. master_2 + pr is not tested then, but can be merged.

In this case, we should manually fix the problem..

**Comment by Xuanwo** [comment]
We have @mergify now!
