### ISSUE TITLE
bug: stage privilege not cover all Scenes

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#13750]
**Summary**

Now Databend support stage grant object. But we only cover copy into and presign.

And some queries can destroy this behavior.

1. list stage (in plan it rewritten to query liststage)
```rust
Statement::ListStage { location, pattern } => {
                let pattern = if let Some(pattern) = pattern {
                    format!(", pattern => '{pattern}'")
                } else {
                    "".to_string()
                };
                self.bind_rewrite_to_query(bind_context, format!("SELECT * FROM LIST_STAGE(location => '@{location}'{pattern})").as_str(), RewriteKind::ListStage).await?
            }

```
2. select * from stage (table ref support Location)
```rust
pub enum TableReference {
    ...
    Location {
        span: Span,
        location: FileLocation,
        options: SelectStageOptions,
        alias: Option<TableAlias>,
    },
}
```

**Comment by TCeason** [comment]
cc @youngsofun  Please check it. Are there other scenes that I forgot?

**Comment by TCeason** [comment]
cc @wubx Please track this issue.

**Comment by youngsofun** [comment]
table function  infer_schema and inspect_parquet need privilage too. 
https://github.com/datafuselabs/databend/pull/13214
