### ISSUE TITLE
New filter execution framework

### ISSUE THREAD

**Issue by Dousir9** [datafuselabs/databend#13844]
**Summary**

**Preparation**
+ #13873 
+ #13919

**Main**
+ https://github.com/datafuselabs/databend/pull/13846

**After Main**
+ #12753

**Comment by sundy-li** [comment]
reorder filters by stats?

**Comment by Dousir9** [comment]
> reorder filters by stats?

Yes, it is part of the new filter execution framework.

**Comment by xudong963** [comment]
https://github.com/datafuselabs/databend/issues/12753 add this to summary?

**Comment by Dousir9** [comment]
All work has been completed.
