### ISSUE TITLE
feat: compression when data shuffle via flight RPC

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13885]
**Summary**

When Databend shuffles data between cluster nodes via Flight RPC, network bandwidth can become a critical issue.

**Comment by BohuTANG** [comment]
Can not find Flight RPC supports compression flag.

**Comment by sundy-li** [comment]
It's arrow's IPC format, it supposes compression by default.

enabled when compiled with feature `io_ipc_compression`.
