### ISSUE TITLE
bug: set `max_storage_io_requests` as a big number value causing memory allocation panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.234

### What's Wrong?

Set `max_storage_io_requests` as a big number value causing memory allocation panic
We need to set a maximum value for `max_storage_io_requests`

```
panicked at src/common/base/src/runtime/runtime_tracker.rs:84:9:
memory allocation of 6495635026088229384 bytes failed
```

### How to Reproduce?

```sql
mysql> create table tt1(a int, b int);
Query OK, 0 rows affected (0.13 sec)

mysql> UPDATE /*+ SET_VAR(max_storage_io_requests=811954378261028673) */ tt1 SET a=10, b=100;
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 1046 panicked.

mysql> set max_storage_io_requests=811954378261028673;
Query OK, 0 rows affected (0.01 sec)

mysql> UPDATE tt1 SET a=10, b=100;
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 1153 panicked.

mysql> select * from tt1;
ERROR 1105 (HY000): PanicError. Code: 1104, Text = memory allocation of 6495635026088229384 bytes failed
(while in query pipeline init).
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
Does max thread has same issue?

**Comment by b41sh** [comment]
> Does max thread has same issue?

Yes, too many threads can cause execution to fail, we need to set a maximum allowed value for these settings.

**Comment by BohuTANG** [comment]
We can add a max value check option for settings.

**Comment by sundy-li** [comment]
> I think we can add a field `Option<u64> maximum` in `DefaultSettingValue` struct, in fn `unchecked_try_set_u64` check new value < maximum

maybe `Range<u64>` ? defauts to `u64::min`, `u64::max`

> How to determine its(max_storage_io_requests & max_threads) maximum value?

It's hard to determine, maybe an experience value  ( 1..1024) ?
