### ISSUE TITLE
bug: right anti join unable to get field named

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.243-nightly

### What's Wrong?

right anti join unable to get field named

### How to Reproduce?

```sql
mysql> create table tt1(a int, b int);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into tt1 values(1, 1),(2, 2);
Query OK, 2 rows affected (0.17 sec)

mysql> create table tt2(a int, b int);
Query OK, 0 rows affected (0.12 sec)

mysql> insert into tt2 values(1, 1),(2, 2);
Query OK, 2 rows affected (0.13 sec)

mysql> SELECT tt1.a FROM tt1 RIGHT ANTI JOIN tt2 ON tt1.a = tt2.a;
ERROR 1105 (HY000): BadArguments. Code: 1006, Text = Unable to get field named "0". Valid fields: [].
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Dousir9** [comment]
This is not a bug, it is a wrong usage for right anti join, `tt1 RIGHT ANTI JOIN tt2` we cannot return the columns of `tt1`, I will add some tips for our users.
