### ISSUE TITLE
feat: consider use borsh to serde aggregation state

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#13979]
**Summary**

The format of [borsh](https://borsh.io/) is exactly the same as the aggregation state.

Since borsh claims it has better performance than bincode crate, we should verify it.

1. Investigate the performance between borsh and bincode in serde  (Sum, Avg, MinState ) using criterion.
2. If it works, use borsh replace bincode.

**Comment by BohuTANG** [comment]
bincode is not consistency in cricutal cases:
1. different bincode version is not consistency
2. different usage may not consistency
