### ISSUE TITLE
CEIL/floor function decimal point issue

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14027]
**Summary**

`124.0`
`123.0`

query:
```
SELECT 
    ROUND(CAST(123.4567 AS DECIMAL(10,4)), 2) AS round_2,
    CEIL(CAST(123.456 AS DECIMAL(10,3))) AS ceil,
    FLOOR(CAST(123.456 AS DECIMAL(10,3))) AS floor;
```

Databend:
<img width="840" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/69dc927a-4668-4408-9f47-81edb1a7892e">

Snowflake:
<img width="932" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/ad6e0f3c-cd03-42fd-9f39-b5c08a6d7ac3">

DuckDB:
<img width="1059" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/8ef394a6-f02c-4b88-b45e-215f8e6f940a">

**Comment by sundy-li** [comment]
Fixed in latest version.
