### ISSUE TITLE
test: 0_stateless/18_rbac/20_0012_privilege_access.sh

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#14033]
**Summary**

```
20_0012_privilege_access:                                               [ FAIL ] - result differs with:
--- /runner/_work/databend/databend/tests/suites/0_stateless/18_rbac/20_0012_privilege_access.result	2023-12-15 04:45:24.914637083 +0000
+++ /runner/_work/databend/databend/tests/suites/0_stateless/18_rbac/20_0012_privilege_access.stdout	2023-12-15 04:46:56.458616662 +0000
@@ -39,6 +39,7 @@
 information_schema
 system
 test -- show tables
+t1
 test_t
 test -- show tables from system
 one
```

https://github.com/datafuselabs/databend/actions/runs/7217764647/job/19666840065

**Comment by everpcpc** [comment]
cc @TCeason could you help with this? thanks ~

**Comment by TCeason** [comment]
Got

**Comment by TCeason** [comment]
I think we can delete L154 and L155

https://github.com/datafuselabs/databend/blob/4fc87e4b07b8669724a26267cea3935e10d92491/tests/suites/0_stateless/18_rbac/20_0012_privilege_access.sh#L154

It wants to test the user `a` grant select on default.* to a is useful.

But it's duplicate with next test : https://github.com/datafuselabs/databend/blob/4fc87e4b07b8669724a26267cea3935e10d92491/tests/suites/0_stateless/18_rbac/20_0012_privilege_access.sh#L158C7-L158C48
