### ISSUE TITLE
how to  resize S3 size

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend#14035]
**Summary**
the S3 storage
![企业微信截图_17026198323707](https://github.com/datafuselabs/databend/assets/88416508/8f94d307-dec2-49d1-9407-294da2972edd)
the data in databend
![企业微信截图_17026199687467](https://github.com/datafuselabs/databend/assets/88416508/753d4b3a-43b2-4efa-ba49-57da2824fd0b)
optimize table purge  table long time
![企业微信截图_17026200256570](https://github.com/datafuselabs/databend/assets/88416508/83d97b39-c07c-4e0a-8c70-f11742b57fe8)

**Comment by BohuTANG** [comment]
`VACUUM TABLE <your-table> RETAIN 0 HOURS DRY RUN` will be helpful:
https://docs.databend.com/sql/sql-commands/ddl/table/vacuum-table

Note: VACUUM is a EE feature, you can find more information here:
https://docs.databend.com/doc/overview/editions/dee/

**Comment by wubx** [comment]
Here are some things to need notes:
```
show settings; 

>retention_period default is  12 hours. 

If you need delete all of the time travel 

> set global retention_peroid=0;

optimize table T purge ; only can purge time travel. 

if you need delete drop table time travel
you must need: 
> vacuum drop table;
```
So, if you need our EE feature test, Please connact wubx@datafuselabs.com, and provide:
<your company name>
<usage scenario>
<enterprise email>
