### ISSUE TITLE
Feature: `array_fold` function with lambda expression

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#14069]
**Summary**

Description for this feature.

similar to  rust's `fold` function: 
```
 let numbers = [1, 2, 3, 4, 5];

 let mut result = 0;

 // for loop:
 for i in &numbers {
     result = result + i;
 }

 // fold:
 let result2 = numbers.iter().fold(0, |acc, &x| acc + x);
```

in databend, for example:
```sql
select array_fold([], (acc, t) -> acc + t);   --- outputs null
select array_fold([1,2,3], (acc, t) -> acc + t);   --- outputs 6
```

**Comment by b41sh** [comment]
The number of arguments should be the same as the number of params. The example SQL should look like this:
```sql
select array_fold(0, [], (acc, t) -> acc + t);   --- outputs null
select array_fold(0, [1,2,3], (acc, t) -> acc + t);   --- outputs 6
```
See the Clickhouse document:
https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arrayfold

**Comment by sundy-li** [comment]
> The number of arguments should be the same as the number of params. The example SQL should look like this:
> 
> ```sql
> select array_fold([], 0, (acc, t) -> acc + t);   --- outputs null
> select array_fold([1,2,3], 0, (acc, t) -> acc + t);   --- outputs 6
> ```
> 
>

Ok, Let's use this, cc @Freejww

**Comment by sundy-li** [comment]
Let's use rust's style, the acc will default to the first element instead of a new arg.
