### ISSUE TITLE
[plan] move ReadSourcePlan to from parser to SelectInterpreter

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1406]
**Summary**

`ReadSourcePlan = table.read_plan()` will request a long path(MetaStore), it would be better to move it to SelectInterpreter.

**Comment by BohuTANG** [comment]
cc @zhang2014 @sundy-li

**Comment by Xuanwo** [comment]
@BohuTANG Is this issue still valid?

**Comment by BohuTANG** [comment]
Our architect has changed, this issue is stale, let's close
