### ISSUE TITLE
aggregating index limit to aggregate query

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14073]
**Summary**

```
CREATE TABLE agg(a int, b int, c int);
INSERT INTO agg VALUES (1,1,4), (1,2,1), (1,2,4);
CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT a FROM agg; -- OK
```

`.. SELECT a FROM agg` is not a aggregate query and this index is not useful for user, so we should limit it?

The error hints could be:
```
Aggregating index only supports simple queries formatted as: SELECT [SUM|MIN|MAX|COUNT|AVG|APPROX_COUNT_DISTINCT] FROM <table_name> WHERE ... [GROUP BY <column_names>] [HAVING ...]. Note: Complex or non-deterministic functions are not supported.
```

**Comment by BohuTANG** [comment]
Got an error:
```
SQL: CREATE SYNC AGGREGATING INDEX my_agg_index AS SELECT count(a), avg(b), sum(c) FROM agg; 

1601: Currently create aggregating index just support simple query, like: SELECT ... FROM ... WHERE ... GROUP BY ..., and these aggregate funcs: sum,min,max,avg,approx_count_distinct, and non-deterministic functions are not support like: NOW()
```

**Comment by BohuTANG** [comment]
Another issue, aggregating index is not used:
```
CREATE TABLE agg(a int, b int, c int);
insert into agg select number, number%2, number%3 from numbers(1000000000);

CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT  avg(b), sum(c) FROM agg;
```

```
explain select avg(b) from agg;

EvalScalar
├── output columns: [(sum(b) / if((count(b) = 0), 1, count(b))) (#5)]
├── expressions: [sum(b) (#3) / CAST(if(CAST(count(b) (#4) = 0 AS Boolean NULL), 1, count(b) (#4)) AS UInt64 NULL)]
├── estimated rows: 1.00
└── AggregateFinal
    ├── output columns: [sum(b) (#3), count(b) (#4)]
    ├── group by: []
    ├── aggregate functions: [sum(b), count(b)]
    ├── estimated rows: 1.00
    └── AggregatePartial
        ├── output columns: [sum(b) (#3), count(b) (#4)]
        ├── group by: []
        ├── aggregate functions: [sum(b), count(b)]
        ├── estimated rows: 1.00
        └── TableScan
            ├── table: default.default.agg
            ├── output columns: [b (#1)]
            ├── read rows: 1100000003
            ├── read bytes: 138204093
            ├── partitions total: 1121
            ├── partitions scanned: 1121
            ├── pruning stats: [segments: <range pruning: 4 to 4>, blocks: <range pruning: 1121 to 1121, bloom pruning: 0 to 0>]
            ├── push downs: [filters: [], limit: NONE]
            └── estimated rows: 1100000003.00
```

**Comment by ariesdevil** [comment]
> **Summary**
> 
> ```
> CREATE TABLE agg(a int, b int, c int);
> INSERT INTO agg VALUES (1,1,4), (1,2,1), (1,2,4);
> CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT a FROM agg; -- OK
> ```
> 
> `.. SELECT a FROM agg` is not a aggregate query and this index is not useful for user, so we should limit it?↳
> 
> The error hints could be:↳
> 
> ```
> Aggregating index only supports simple queries formatted as: SELECT [SUM|MIN|MAX|COUNT|AVG|APPROX_COUNT_DISTINCT] FROM <table_name> WHERE ... [GROUP BY <column_names>] [HAVING ...]. Note: Complex or non-deterministic functions are not supported.
> ```

I think this is not a problem because we also support no aggregate query, eg:
```
CREATE AGGREGATING INDEX testi AS select c + 1 from t

REFRESH AGGREGATING INDEX testi

SELECT to_string(c + 1) FROM t
```
User should know how to avoid create meaningless agg-index

**Comment by ariesdevil** [comment]
> Another issue, aggregating index is not used:↳
> 
> ```
> CREATE TABLE agg(a int, b int, c int);
> insert into agg select number, number%2, number%3 from numbers(1000000000);
> 
> CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT  avg(b), sum(c) FROM agg;
> ```
> 
> ```
> explain select avg(b) from agg;
> 
> EvalScalar
> ├── output columns: [(sum(b) / if((count(b) = 0), 1, count(b))) (#5)]
> ├── expressions: [sum(b) (#3) / CAST(if(CAST(count(b) (#4) = 0 AS Boolean NULL), 1, count(b) (#4)) AS UInt64 NULL)]
> ├── estimated rows: 1.00
> └── AggregateFinal
>     ├── output columns: [sum(b) (#3), count(b) (#4)]
>     ├── group by: []
>     ├── aggregate functions: [sum(b), count(b)]
>     ├── estimated rows: 1.00
>     └── AggregatePartial
>         ├── output columns: [sum(b) (#3), count(b) (#4)]
>         ├── group by: []
>         ├── aggregate functions: [sum(b), count(b)]
>         ├── estimated rows: 1.00
>         └── TableScan
>             ├── table: default.default.agg
>             ├── output columns: [b (#1)]
>             ├── read rows: 1100000003
>             ├── read bytes: 138204093
>             ├── partitions total: 1121
>             ├── partitions scanned: 1121
>             ├── pruning stats: [segments: <range pruning: 4 to 4>, blocks: <range pruning: 1121 to 1121, bloom pruning: 0 to 0>]
>             ├── push downs: [filters: [], limit: NONE]
>             └── estimated rows: 1100000003.00
> ```
> 
> After refreshing the index also not works:↳
> 
> ```
> refresh AGGREGATING INDEX my_agg_index;
> ```

That's a bug, we store query string when create agg-index, but the `avg` in query will be rewritten `sum/count`, I'll fix it.

**Comment by BohuTANG** [comment]
> > **Summary**
> > ```
> > CREATE TABLE agg(a int, b int, c int);
> > INSERT INTO agg VALUES (1,1,4), (1,2,1), (1,2,4);
> > CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT a FROM agg; -- OK
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `.. SELECT a FROM agg` is not a aggregate query and this index is not useful for user, so we should limit it?↳
> > The error hints could be:↳
> > ```
> > Aggregating index only supports simple queries formatted as: SELECT [SUM|MIN|MAX|COUNT|AVG|APPROX_COUNT_DISTINCT] FROM <table_name> WHERE ... [GROUP BY <column_names>] [HAVING ...]. Note: Complex or non-deterministic functions are not supported.
> > ```
> 
> I think this is not a problem because we also support no aggregate query, eg:
> 
> ```
> CREATE AGGREGATING INDEX testi AS select c + 1 from t
> 
> REFRESH AGGREGATING INDEX testi
> 
> SELECT to_string(c + 1) FROM t
> ```
> 
> User should know how to avoid create meaningless agg-index

Good, so we should document more about it and make the error message more readable.

**Comment by ariesdevil** [comment]
> > > **Summary**
> > > ```
> > > CREATE TABLE agg(a int, b int, c int);
> > > INSERT INTO agg VALUES (1,1,4), (1,2,1), (1,2,4);
> > > CREATE  SYNC AGGREGATING INDEX my_agg_index AS SELECT a FROM agg; -- OK
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `.. SELECT a FROM agg` is not a aggregate query and this index is not useful for user, so we should limit it?↳
> > > The error hints could be:↳↳
> > > ```
> > > Aggregating index only supports simple queries formatted as: SELECT [SUM|MIN|MAX|COUNT|AVG|APPROX_COUNT_DISTINCT] FROM <table_name> WHERE ... [GROUP BY <column_names>] [HAVING ...]. Note: Complex or non-deterministic functions are not supported.
> > > ```
> > 
> > 
> > I think this is not a problem because we also support no aggregate query, eg:↳
> > ```
> > CREATE AGGREGATING INDEX testi AS select c + 1 from t
> > 
> > REFRESH AGGREGATING INDEX testi
> > 
> > SELECT to_string(c + 1) FROM t
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > User should know how to avoid create meaningless agg-index↳
> 
> Good, so we should document more about it and make the error message more readable.↳

Yup, and we should make our agg-index limitation align to Snowflake.

**Comment by BohuTANG** [comment]
Another case is not AVG still not work:
```
CREATE TABLE sales_data (
    id INT,
    category VARCHAR(50),
    value INT,
    timestamp DATE
);

-- Inserting a diverse set of data
INSERT INTO sales_data (id, category, value, timestamp) VALUES
    (1, 'Electronics', 100, '2023-01-01'),
    (2, 'Books', 50, '2023-01-02'),
    (3, 'Electronics', 80, '2023-01-03'),
    -- Additional rows with varying categories and values...
    (100, 'Clothing', 60, '2023-04-10');


CREATE SYNC AGGREGATING INDEX sales_agg_index AS
SELECT
    MIN(value),
    MAX(value),
    COUNT(*),
    AVG(value)
FROM
    sales_data
GROUP BY
    category;
```

Check SQL:
```
EXPLAIN
SELECT
    MIN(value),
    MAX(value),
    COUNT(*)
FROM
    sales_data
GROUP BY
    category;
```

Result:
```
-[ EXPLAIN ]-----------------------------------
AggregateFinal
├── output columns: [MIN(value) (#4), MAX(value) (#5), COUNT(*) (#6), sales_data.category (#1)]
├── group by: [category]
├── aggregate functions: [min(value), max(value), count()]
├── estimated rows: 4.00
└── AggregatePartial
    ├── output columns: [MIN(value) (#4), MAX(value) (#5), COUNT(*) (#6), #_group_by_key]
    ├── group by: [category]
    ├── aggregate functions: [min(value), max(value), count()]
    ├── estimated rows: 4.00
    └── TableScan
        ├── table: default.default.sales_data
        ├── output columns: [category (#1), value (#2)]
        ├── read rows: 4
        ├── read bytes: 125
        ├── partitions total: 1
        ├── partitions scanned: 1
        ├── pruning stats: [segments: <range pruning: 1 to 1>, blocks: <range pruning: 1 to 1, bloom pruning: 0 to 0>]
        ├── push downs: [filters: [], limit: NONE]
        └── estimated rows: 4.00
```

**Comment by RinChanNOWWW** [comment]
```sql
CREATE SYNC AGGREGATING INDEX sales_agg_index AS
SELECT
    MIN(value),
    MAX(value),
    COUNT(*),
    AVG(value)
FROM
    sales_data
GROUP BY
    category;
```

If there is a `GROUP BY` clause, the group by items should also be contained in select targets. @BohuTANG

**Comment by BohuTANG** [comment]
> ```sql
> ```sql
> CREATE SYNC AGGREGATING INDEX sales_agg_index AS
> SELECT
>     MIN(value),
>     MAX(value),
>     COUNT(*),
>     AVG(value)
> FROM
>     sales_data
> GROUP BY
>     category;
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> If there is a GROUP BY clause, the group by items should also be contained in select targets. @BohuTANG
> ```

We should give an error if the AS query is not right for aggregating index, or it's a bug.

**Comment by ariesdevil** [comment]
> > ```sql
> > ```sql
> > CREATE SYNC AGGREGATING INDEX sales_agg_index AS
> > SELECT
> >     MIN(value),
> >     MAX(value),
> >     COUNT(*),
> >     AVG(value)
> > FROM
> >     sales_data
> > GROUP BY
> >     category;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If there is a GROUP BY clause, the group by items should also be contained in select targets. @BohuTANG↳
> 
> We should give an error if the AS query is not right for aggregating index, or it's a bug.↳

After discussing with @RinChanNOWWW , I'll add group by items to select_list when creating agg-index, that will solve this issue.
