### ISSUE TITLE
Flaky test: 01_0013_system_metrics.test

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#14120]
**Summary**

https://github.com/datafuselabs/databend/actions/runs/7289555129/job/19864774839?pr=14115#step:4:531

~~~

[SQL] SELECT sum(to_int32(to_float32(value) > 5)) FROM system.metrics where metric = 'query_success_total'
[Diff] (-expected|+actual)
-   0
+   1
at tests/sqllogictests/suites/base/01_system/01_0013_system_metrics.test:52

~~~

**Comment by BohuTANG** [comment]
again: https://github.com/datafuselabs/databend/actions/runs/7289549247/job/19864427604?pr=14117#step:4:532

I will remove this test.
