### ISSUE TITLE
fuse engine preapre to use parquet_rs instead of parquet2

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14135]
**Summary**

Parquet2 has not been maintained for several months. To minimize risk, we should consider transitioning to parquet_rs(https://github.com/apache/arrow-rs parquet) as an alternative to parquet2 for FUSE engine.

**Comment by BohuTANG** [comment]
cc @dantengsky

**Comment by dantengsky** [comment]
> cc @dantengsky

:ok_hand:

**Comment by BohuTANG** [comment]
We can use the `use_parquet2` setting as a transition, and when a certain version is released we'll ditch this setting completely and use all parquet_rs.
