### ISSUE TITLE
fix: owner field in the SHOW FULL TABLES statement

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#14152]
```
        for tbl in &database_tables {
            owner.push(
                tbl.get_table_info()
                    .meta
                    .owner
                    .as_ref()
                    .map(|v| v.owner_role_name.as_bytes().to_vec()),
            );
```

should be replaced with the ownership kv from meta

**Comment by TCeason** [comment]
SHOW DATABASES also need owner field

**Comment by TCeason** [comment]
cc @guojidan This pr is the same as add `owner` field in show full databases https://github.com/datafuselabs/databend/issues/14153.  If you're interested, this assignment can be claimed. If there are other issues that are more interesting to you, I will assign this issue to myself.

**Comment by guojidan** [comment]
hi @TCeason , you can assign to me : )
