### ISSUE TITLE
Feature: Databend needs to distinguish between DateTime and Timestamp

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#14169]
**Summary**

Generally the format of DateTime type is `2016-06-15 23:00:00` and the Timestamp is `2016-06-15 23:00:00.000000`. So IMHO, Databend should distinguish between these two time type.

**Comment by TCeason** [comment]
https://github.com/datafuselabs/databend/blob/629ee7bab86bf74538814e794122e1fedbbeb288/src/query/expression/src/types/timestamp.rs#L244

pub const TIMESTAMP_FORMAT: &str = "%Y-%m-%d %H:%M:%S%.6f";

Now we convert ts type to this format.

How about add a new FORMAT like this:

pub const DATETIME_FORMAT: &str = "%Y-%m-%d %H:%M:%S%";


And add a new setting like default_display_datetime_format to control timestamp_to_string use which FORMAT?

**Comment by TCeason** [comment]
cc @andylokandy @RinChanNOWWW @b41sh @BohuTANG

**Comment by BohuTANG** [comment]
The .6f is not the issue, let's close this.

**Comment by hantmac** [comment]
@BohuTANG  Maybe we should reopen this issue 😭. 
Now we convert ts type to this format `%Y-%m-%d %H:%M:%S%.6f` mandatorily. So I can't remove the .6f anyway because after converting,  the type need be timestamp, the timestamp type always has .6f ......

**Comment by BohuTANG** [comment]
> https://github.com/datafuselabs/databend/blob/629ee7bab86bf74538814e794122e1fedbbeb288/src/query/expression/src/types/timestamp.rs#L244
> 
> pub const TIMESTAMP_FORMAT: &str = "%Y-%m-%d %H:%M:%S%.6f";
> 
> Now we convert ts type to this format.
> 
> How about add a new FORMAT like this:
> 
> pub const DATETIME_FORMAT: &str = "%Y-%m-%d %H:%M:%S%";
> 
> And add a new setting like `default_display_datetime_format` to control `fn timestamp_to_string` use which FORMAT?

`TIMESTAMP_OUTPUT_FORMAT` is ok, like snowflake.

**Comment by BohuTANG** [comment]
Confirmed, This is not an issue, let's close again.
