### ISSUE TITLE
bug: OSS failed to execute 'bendsql  --query='INSERT INTO default.t1 VALUES;' --format=csv --data=@t1.csv'

### ISSUE THREAD

**Issue by chzhewl** [datafuselabs/databend#14192]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.2.275-x86_64-unknown-linux-musl

### What's Wrong?

1. oss storage：
  type = "oss"

[storage.oss]
bucket = "databendxxx"
endpoint_url = "https://oss-cn-qingdao.aliyuncs.com"
access_key_id = "xxxx"
access_key_secret = "xxx"

2. create  table ok：
CREATE TABLE t1
(
    a int
);

4. ready t1.csv :
111
222
333
444

5. execute：
bendsql --query='INSERT INTO default.t1 VALUES;' --format=csv --data=@t1.csv

6. issue：
Local file data import failed.
“select * from t1”  content is empty。
But changing to "minio" is correct。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
virtual column is enterprise features,  you can obtaining a license: https://docs.databend.com/guides/overview/editions/dee/license#obtaining-a-license

Enterprise Features:
https://docs.databend.com/guides/overview/editions/dee/enterprise-features

**Comment by b41sh** [comment]
Hi @chzhewl Thanks for reporting the bug, is the cause of the error the following?
```
Error: APIError: ResponseError with 3902: storage doesn't support presign operation
```

**Comment by chzhewl** [comment]
> 你好@chzhewl感谢您报告该错误，请问错误原因如下？
> 
> ```
> Error: APIError: ResponseError with 3902: storage doesn't support presign operation
> ```
No error message

but,
Still using aliyun oss,  databend-query.toml  storage type = "s3"，storage.s3 is configured as follows. Executing the above bendsql to import this file can be successful.

[storage.s3]
bucket = "xxx"
endpoint_url = "http://oss-cn-qingdao-internal.aliyuncs.com"
access_key_id = "xxxx"
secret_access_key = "xxxx"
enable_virtual_host_style = true

**Comment by b41sh** [comment]
> > 你好@chzhewl感谢您报告该错误，请问错误原因如下？
> > ```
> > Error: APIError: ResponseError with 3902: storage doesn't support presign operation
> > ```
> 
> No error message
> 
> but, Still using aliyun oss, databend-query.toml storage type = "s3"，storage.s3 is configured as follows. Executing the above bendsql to import this file can be successful.
> 
> [storage.s3] bucket = "xxx" endpoint_url = "http://oss-cn-qingdao-internal.aliyuncs.com" access_key_id = "xxxx" secret_access_key = "xxxx" enable_virtual_host_style = true

It looks like the storage type is `s3` and `minio` both work. If the type is `oss`, will it fail?

**Comment by chzhewl** [comment]
> > > 你好@chzhewl感谢您报告该错误，请问错误原因如下？
> > > ```
> > > Error: APIError: ResponseError with 3902: storage doesn't support presign operation
> > > ```
> > 
> > 
> > 无错误信息
> > 但是，仍然使用aliyun oss，databend-query.toml存储类型=“s3”，storage.s3配置如下。执行上面的bendsql导入该文件即可成功。
> > [storage.s3]bucket =“xxx”endpoint_url =“ http://oss-cn-qingdao-internal.aliyuncs.com ”access_key_id =“xxxx”secret_access_key =“xxxx”enable_virtual_host_style = true
> 
> 看起来存储类型是`s3`并且`minio`两者都有效。如果类型是`oss`，会失败吗？

是的，类型为oss，执行“bendsql --query='INSERT INTO default.t1 VALUES;' --format=csv --data=@t1.csv” 会失败，且无任何错误提示。

**Comment by b41sh** [comment]
Hi, @chzhewl The `oss` storage insert bug has been fixed, you can verify it with the next version of `bendsql`, thanks again for reporting this bug, and welcome to continue using databend!
