### ISSUE TITLE
bug: databend should sustain case-sensitive for query alias names

### ISSUE THREAD

**Issue by jackjoesh** [datafuselabs/databend#14205]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Version: v1.2.174-nightly

### What's Wrong?

databend should sustain case-sensitive for query alias names,  this is very important for mybatis mapping to the java object.
And this function shouldn't be controlled by 'unquoted_ident_case_sensitive'  due to they are not the same thing

### How to Reproduce?

<img width="409" alt="image" src="https://github.com/datafuselabs/databend/assets/28348638/30ec0cfd-d288-4b3b-a01c-6d2d30fd34dc">

If this occurring, mybatis can't map db fields to java object, this is terrible for business system migrating to databend.
And this function shouldn't be controlled by 'unquoted_ident_case_sensitive'  due to they are not the same thing, still needing to convert some where clauses to lower case. 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
Maybe you need:
```
select order_id as `orderId` from blob_test limit 5;
```

**Comment by sundy-li** [comment]
it follows pg style, so we will not fix this.

you can quote it using "orderId" or set `unquoted_ident_case_sensitive` to be 1
