### ISSUE TITLE
databend-query oom

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend#14215]
**Summary**
databend-query 不知道什么原因突然 内存和CPU 都飙升，然后OOM，启动后还是直接OOM
从8C16G 升级到16C32G，升级完勉强抗住，半个小时后 回落到正常水平
在这期间看databend-query监控 每分钟有将近200W行的写入
![1704264713177](https://github.com/datafuselabs/databend/assets/88416508/f6472d89-6c09-4a21-9b7c-a0e685b7094e)

**Comment by blade83lee** [comment]
实际表写入 20多W，
![1704265413604](https://github.com/datafuselabs/databend/assets/88416508/8f37c902-9831-4aa8-85d6-7f232cec3c3d)
多个PipelineExecuto 线程cpu使用率 100%

**Comment by sundy-li** [comment]
是否是写入的时候 开启了 `enable_compact_after_write` ? 这个会在写入的时候 触发compaction

**Comment by blade83lee** [comment]
跟平常不同的是 ，有执行了 alter table  cluster by

**Comment by BohuTANG** [comment]
`alter table cluster by` 请单独节点执行，这样就不会影响。
