### ISSUE TITLE
tracking: CREATE OR REPLACE

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14229]
**Summary**

`CREATE OR REPLACE `means "if the object exists, drop it, then create it", with it we can simple all the object operations:
```
DROP IF EXISTS ....
CREATE ...
```
into one:
```
CREATE OR REPLACE ...
```

**Comment by lichuang** [comment]
- [create or replace database ]

**Comment by PsiACE** [comment]
I want to try implementing some of them. I will try to track in this comment.

- [ ] https://github.com/datafuselabs/databend/issues/14551 for udf

**Comment by BohuTANG** [comment]
Another:
- [ ] CREATE [ OR REPLACE ] WAREHOUSE 
This may need help from @ZhiHanZ

**Comment by PsiACE** [comment]
External Function has been supported in #14551.

**Comment by lichuang** [comment]
`create share` only create a named share, without any other params, i think there is no need to impl `o replace` when create share: https://docs.databend.com/sql/sql-commands/ddl/share/

**Comment by BohuTANG** [comment]
Spilled out https://github.com/datafuselabs/databend/issues/14661, this tracking is all done.
