### ISSUE TITLE
Migrate to async parquet reading

### ISSUE THREAD

**Issue by jorgecarleitao** [datafuselabs/databend#1432]
The arrow2 0.3 and parquet2 0.3 now support reading parquet from an `async` source, which allows reading directly from s3 and others via `AsyncRead + AsyncSeek`. datafuse should be able to leverage this when reading parquet from a network-bounded source.

Note that there are small backward incompatible changes going from `0.2` to `0.3`, documented in the changelog [here](https://github.com/jorgecarleitao/arrow2/releases/tag/v0.3.0).

**Comment by BohuTANG** [comment]
Thank you @jorgecarleitao 
This is really a feature that we need and it's awesome!

**Comment by BohuTANG** [comment]
Thank you @jorgecarleitao 
This is really a feature that we need and it's awesome!

**Comment by BohuTANG** [comment]
This issue ready to close? cc @sundy-li 
Thank you @jorgecarleitao
