### ISSUE TITLE
very slow: select * from system.tables

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14327]
**Summary**

DatabendCloud:

29775 tables will take 2 minutes to fetch:
```
select count(*) from system.tables;
```

```
Query Duration:2m 4.6s
Size:5.25MB
```

**Comment by BohuTANG** [comment]
Looks not make sense? Need your help to check @drmingdrmer

**Comment by drmingdrmer** [comment]
No. Is there a log file for this query?

**Comment by TCeason** [comment]
Will execute Select * from system tables. And then calculate count.

select * that without filter equal table name will access all table meta.

**Comment by BohuTANG** [comment]
> Will execute Select * from system tables. And then calculate count.
> 
> select * that without filter equal table name will access all table meta.

It's not related to the `count(*)`, here is a example, fetch `29775 ` tables from meta is slow.

**Comment by BohuTANG** [comment]
> No. Is there a log file for this query?

Test on the cloud. You can try this script to create many tables and then use BendSQL to reproduce:
https://github.com/datafuselabs/wizard/tree/main/threads

**Comment by drmingdrmer** [comment]
@TCeason 
For each fetched table, it tries to get ownership one by one:
https://github.com/datafuselabs/databend/blob/094e1dba69ec4a2d43430e9a6460c74dc164672f/src/query/storages/system/src/tables_table.rs#L284

Every to meta-service RPC takes about 3ms, which sums up to 2 minutes.

`get_ownership()` should be replaced with a `mget()` based method to enable batch fetch. Refer to:
https://github.com/datafuselabs/databend/blob/b59d6b6ecc170ac670f94ca5bd2ba8cd9b35d7fe/src/meta/api/src/util.rs#L823-L829

**Comment by TCeason** [comment]
> @TCeason 
> 
> For each fetched table, it tries to get ownership one by one:
> 
> https://github.com/datafuselabs/databend/blob/094e1dba69ec4a2d43430e9a6460c74dc164672f/src/query/storages/system/src/tables_table.rs#L284
> 
> 
> 
> Every to meta-service RPC takes about 3ms, which sums up to 2 minutes.
> 
> 
> 
> `get_ownership()` should be replaced with a `mget()` based method to enable batch fetch. Refer to:
> 
> https://github.com/datafuselabs/databend/blob/b59d6b6ecc170ac670f94ca5bd2ba8cd9b35d7fe/src/meta/api/src/util.rs#L823-L829

Get
