### ISSUE TITLE
bug: DATE_FORMAT not throwing error when converting non-date value

### ISSUE THREAD

**Issue by soyeric128** [datafuselabs/databend#14369]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

root@localhost:8000/default> select version();

SELECT
  version()

┌───────────────────────────────────────────────────────────────────────────────────────┐
│                                       version()                                       │
│                                         String                                        │
├───────────────────────────────────────────────────────────────────────────────────────┤
│ DatabendQuery v1.2.279-638686a9ae(rust-1.75.0-nightly-2024-01-02T11:00:05.975634000Z) │
└───────────────────────────────────────────────────────────────────────────────────────┘
1 row read in 0.010 sec. Processed 1 row, 1 B (98.14 row/s, 98 B/s)

### What's Wrong?

root@localhost:8000/default> select date_format('2022-12-234');

SELECT
  date_format('2022-12-234')

┌────────────────────────────┐
│ date_format('2022-12-234') │
│           String           │
├────────────────────────────┤
│ 2022-12-234                │
└────────────────────────────┘
1 row read in 0.010 sec. Processed 1 row, 1 B (104.03 row/s, 104 B/s)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
date_format is alias of to_string.

this func means to_string('string text ')

**Comment by TCeason** [comment]
I think it's not a big. But Cc @andylokandy maybe the alias register need type check?

**Comment by soyeric128** [comment]
root@localhost:8000/default> SELECT DATE_FORMAT('2022-12-25', 'Month/Day/Year: %m/%d/%Y');

SELECT
  DATE_FORMAT('2022-12-25', 'Month/Day/Year: %m/%d/%Y')

┌───────────────────────────────────────────────────────┐
│ date_format('2022-12-25', 'month/day/year: %m/%d/%y') │
│                         String                        │
├───────────────────────────────────────────────────────┤
│ Month/Day/Year: 12/25/2022                            │
└───────────────────────────────────────────────────────┘
1 row read in 0.012 sec. Processed 1 row, 1 B (84.06 row/s, 84 B/s)

root@localhost:8000/default> SELECT DATE_FORMAT('2022-12-257', 'Month/Day/Year: %m/%d/%Y');
error: APIError: ResponseError with 1006: cannot parse to type `TIMESTAMP` while evaluating function `to_timestamp('2022-12-257')`
root@localhost:8000/default>

**Comment by soyeric128** [comment]
It seems the function converts whatever to a string when given only argument, and expects a real date when given two arguments. 

Is that true?

**Comment by andylokandy** [comment]
> date_format is alias of to_string.

seems DATE_FORMAT is not expected to be identical to `to_string`. It'll be better if DATE_FORMAT has its own registration.
