### ISSUE TITLE
Feature:  support function nvl aliase ifnull

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#14381]
**Summary**

Oracle use nvl as ifnull.
We just support ifnull as nvl.

**Comment by BohuTANG** [comment]
nvl2 `NVL2( <expr1> , <expr2> , <expr3> )`

Reference:
[Oracle NVL2](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/NVL2.html#GUID-414D6E81-9627-4163-8AC2-BD24E57742AE)
[Snowflake NVL2](https://docs.snowflake.com/en/sql-reference/functions/nvl2)
