### ISSUE TITLE
databend-meta  cluster change server ip

### ISSUE THREAD

**Issue by blade83lee** [datafuselabs/databend#14387]
**Summary**
1、databend-meta集群 和databend-query集群 部署在3台机器上
2、关闭实例，在3台服务器更改了IP地址信息
3、在3台机器上分别操作
/usr/local/databend/bin/databend-metactl --export --raft-dir /data/databend/meta/raft --db  /data/backup/raftbak
并修改raftbak文件，将ip修改为新的IP
["state_machine/0",{"Nodes":{"key":1,"value":{"name":"1","endpoint":{"addr":"10.49.4.157","port":28103},"grpc_api_advertise_address":"10.49.4.157:9191"}}}]
["state_machine/0",{"Nodes":{"key":2,"value":{"name":"2","endpoint":{"addr":"10.49.4.149","port":28103},"grpc_api_advertise_address":"10.49.4.149:9191"}}}]
["state_machine/0",{"Nodes":{"key":3,"value":{"name":"3","endpoint":{"addr":"10.49.4.33","port":28103},"grpc_api_advertise_address":"10.49.4.33:9191"}}}]
4、将数据恢复到各自的机器上
/usr/local/databend/bin/databend-metactl --import --raft-dir /data/databend/meta/raft --db  /data/backup/raftbak
5、启动3个databend-meta节点，查询状态
![image](https://github.com/datafuselabs/databend/assets/88416508/dbc2c8c7-24c7-4189-9484-315a051804df)

6、启动一个databend-query节点
![企业微信截图_170564694683](https://github.com/datafuselabs/databend/assets/88416508/66921045-82bd-4d5e-baef-307828cdaf6b)
   发现记录无法查询
  error: error happens after fetched 0 rows: APIError: ResponseError with 4000: Unexpected (temporary) at Pager::next, context: { timeout: 60 } => operation timeout
7、 count表的记录可以，但是单查询一条记录不行

**Comment by blade83lee** [comment]
在查看日志的时候 并没有发现明显的error信息

**Comment by blade83lee** [comment]
t_transient_log_allsys 有16亿数据，可以对这个表进行count计算， 可以用insert into 语句进行插入数据， 但是无法用Prepare batch.Exec 插入数据，无法select 数据

**Comment by wubx** [comment]
Use s3cmd to verify that it can transfer large files.

**Comment by blade83lee** [comment]
找到问题， databend集群网络 到S3 之间使用gre隧道，导致大包无法获取
