### ISSUE TITLE
bug: create table bitmap data type with default value cause panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#14391]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.305-nightly

### What's Wrong?

create table bitmap data type with default value cause panic
```
panicked at src/query/sql/src/planner/expression_parser.rs:419:79:
removal index (is 0) should be < len (is 0)
   0: databend_common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
```

### How to Reproduce?

```sql
mysql> CREATE TABLE IF NOT EXISTS t1 (
    ->     a STRING NOT NULL DEFAULT '',
    ->     b BITMAP NOT NULL DEFAULT '0'
    -> );
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 183 panicked.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Let's disallow bitmap types to have default value constraint.
