### ISSUE TITLE
bug: replace function is wrong when dealing reduplicated words

### ISSUE THREAD

**Issue by jackjoesh** [datafuselabs/databend#14399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.292

### What's Wrong?

<img width="559" alt="image" src="https://github.com/datafuselabs/databend/assets/28348638/0eef9064-6e49-44f1-8f84-6f1f307e8375">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @sundy-li

**Comment by b41sh** [comment]
this bug has been fixed after PR #14349 merged
