### ISSUE TITLE
[parquet] change parquet reading from sync to async

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1445]
**Summary**

As issued in https://github.com/datafuselabs/datafuse/issues/1432, it's time to move parquet to async reading:
```
        task::spawn_blocking(move || {
            if let Err(e) = read_file(&file, response_tx, &projection) {
                println!("Parquet reader thread terminated due to error: {:?}", e);
            }
        });
```
https://github.com/datafuselabs/datafuse/blob/master/query/src/datasources/local/parquet_table.rs#L157-L161

**Comment by zhongzc** [comment]
@BohuTANG The code snippet you pointed out it's not a network-bounded source that Arrow2 supports for async. I'm afraid that this is not an appropriate task for newcomers.

**Comment by zhongzc** [comment]
However, I noticed that `Ok(Box::pin(ParquetStream::try_create(response_rx)?))` is just a blocking stream. It doesn't collaborate with the runtime so it will keep running/blocking until done. Would it be better to introduce some really async channel like `tokio::sync::mpsc`?

**Comment by jackwener** [comment]
> Would it be better to introduce some really async channel like `tokio::sync::mpsc`?

I also notice this problem.

**Comment by sundy-li** [comment]
> Would it be better to introduce some really async channel like tokio::sync::mpsc?

Yes, because the ParquestStream was implemented from arrow1. Now we have migrated into arrow2, so it makes sense to change it to be `tokio::sync::mpsc`.

**Comment by Xuanwo** [comment]
Hi, any update on this issue?

**Comment by sundy-li** [comment]
It's already done. Arrow2 supports async parquet reading now.
