### ISSUE TITLE
bug: merge into insert table with default value cause panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#14474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.314-nightly

### What's Wrong?

merge into insert table with default value cause panic
```
panicked at src/query/sql/src/planner/expression_parser.rs:138:36:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

### How to Reproduce?

```sql
mysql> set enable_experimental_merge_into = 1;
Query OK, 0 rows affected (0.03 sec)

mysql> create table tt1 (a bool not null default true, b int not null default 1);
Query OK, 0 rows affected (0.15 sec)

mysql> merge into tt1 using(select false, 10) as tt2(a, b) on (tt1.b = 1) when not matched then insert (b) values (20);
ERROR 1105 (HY000): PanicError. Code: 1104, Text = there is no reactor running, must be called from the context of a Tokio 1.x runtime.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JackTan25** [comment]
I need to refactor the insert for merge into, move the build_expression into pipeline_build phase.
