### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by chzhewl** [datafuselabs/databend#14516]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.2.285-nightly-2429b56fd2(rust-1.75.0-nightly-2024-01-06T01:27:24.485927937Z)

### What's Wrong?

导出数据到对象存储，增加 “OUTPUT_HEADER ” 参数后报错：
COPY INTO @dataunloadai
FROM (
	select .....
)
FILE_FORMAT = (
	TYPE = CSV
	OUTPUT_HEADER = true
);

错误：
SQL 错误 [1105] [HY000]: SyntaxException. Code: 1005, Text = error: 
   --> SQL:16:2
   |
 1 | /* ApplicationName=DBeaver 23.1.4 - SQLEditor <Script-19.sql> */     
 2 |     
 3 | COPY INTO @dataunloadai
   | ---- while parsing `COPY
                INTO { internalStage | externalStage | externalLocation }
                FROM { [<database_name>.]<table_name> | ( <query> ) }
                [ FILE_FORMAT = ( { TYPE = { CSV | JSON | PARQUET | TSV } [ formatTypeOptions ] } ) ]
                [ copyOptions ]`
   .
13 | )
14 | FILE_FORMAT = (
15 |     TYPE = CSV
16 |     OUTPUT_HEADER = true
   |     ^^^^^^^^^^^^^ unexpected `OUTPUT_HEADER`, expecting `SKIP_HEADER`, `TYPE`, `QUOTE`, `FORMAT_NAME`, `NON_DISPLAY`, `NULL_DISPLAY`, `NULL_FIELD_AS`, `ROW_TAG`, `FIELD_DELIMITER`, `COMPRESSION`, `NAN_DISPLAY`, `ERROR_ON_COLUMN_COUNT_MISMATCH`, `RECORD_DELIMITER`, `MISSING_FIELD_AS`, `ESCAPE`, `)`, or `,`

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
v1.2.285 doesn't have this option yet, please upgrade to the version >= v.1.2.230:
<img width="1467" alt="image" src="https://github.com/datafuselabs/databend/assets/172204/2d1805e5-3e14-475f-96d0-e651ac91e077">

**Comment by chzhewl** [comment]
OK tks!
