### ISSUE TITLE
bug: unhex returns error on examples in document

### ISSUE THREAD

**Issue by soyeric128** [datafuselabs/databend#14528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

DatabendQuery v1.2.296-nightly-b9a4726b40(rust-1.75.0-nightly-2024-01-14T02:15:34.749419000Z)

### What's Wrong?

https://docs.databend.com/sql/sql-functions/string-functions/unhex#examples

<img width="914" alt="Screenshot 2024-01-30 at 11 33 30 AM" src="https://github.com/datafuselabs/databend/assets/106025534/f50ffb56-6131-410a-a03a-18cd1457c94f">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
root@localhost:8000/default> SELECT UNHEX(HEX('string'));

SELECT
  UNHEX(HEX('string'))

-[ RECORD 1 ]-----------------------------------
unhex(hex('string')): 737472696e67

1 row read in 0.018 sec. Processed 1 row, 1 B (54.78 row/s, 54 B/s)

root@localhost:8000/default> select version();

SELECT
  version()

-[ RECORD 1 ]-----------------------------------
version(): Databend Query v1.2.318-nightly-56c0a16610(rust-1.77.0-nightly-2024-01-27T01:09:12.988272867Z)

1 row read in 0.009 sec. Processed 1 row, 1 B (105.38 row/s, 105 B/s)

**Comment by sundy-li** [comment]
use

```
 SELECT UNHEX(HEX('hello'))::String;
```

**Comment by soyeric128** [comment]
Updated to latest version of Databend and BendSQL:

<img width="997" alt="Screenshot 2024-01-30 at 9 51 13 PM" src="https://github.com/datafuselabs/databend/assets/106025534/b57cc38a-6f69-4310-a275-1b281e211688">
