### ISSUE TITLE
bug: json_to_string seems NOT an alias for to_string

### ISSUE THREAD

**Issue by soyeric128** [datafuselabs/databend#14529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

DatabendQuery v1.2.296-nightly-b9a4726b40(rust-1.75.0-nightly-2024-01-14T02:15:34.749419000Z)

### What's Wrong?

https://github.com/datafuselabs/databend/blob/243127405a7315f300a6c5d7287266dd37debdf2/src/query/functions/tests/it/scalars/testdata/function_list.txt#L18

<img width="970" alt="Screenshot 2024-01-30 at 12 21 06 PM" src="https://github.com/datafuselabs/databend/assets/106025534/3161a6a0-7983-426d-9296-cf3998deafdb">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by b41sh** [comment]
this bug has be fixed after #14389 merged
