### ISSUE TITLE
bug: keywords FROM and FOR are not accepted by SUBSTR_UTF8, SUBSTRING_UTF8, and MID

### ISSUE THREAD

**Issue by soyeric128** [datafuselabs/databend#14531]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

DatabendQuery v1.2.296-nightly-b9a4726b40(rust-1.75.0-nightly-2024-01-14T02:15:34.749419000Z)

### What's Wrong?

For the alias mappings indicated below:

https://github.com/datafuselabs/databend/blob/243127405a7315f300a6c5d7287266dd37debdf2/src/query/functions/tests/it/scalars/testdata/function_list.txt#L21
https://github.com/datafuselabs/databend/blob/243127405a7315f300a6c5d7287266dd37debdf2/src/query/functions/tests/it/scalars/testdata/function_list.txt#L33
https://github.com/datafuselabs/databend/blob/243127405a7315f300a6c5d7287266dd37debdf2/src/query/functions/tests/it/scalars/testdata/function_list.txt#L35

Syntax errors found when SUBSTR_UTF8, SUBSTRING_UTF8, and MID include keywords FROM and FOR:
<img width="1411" alt="Screenshot 2024-01-30 at 2 48 48 PM" src="https://github.com/datafuselabs/databend/assets/106025534/a451f077-9384-4156-a596-d7d89cf0ef0e">

While keywords FROM and FOR can be accepted by SUBSTRING and SUBSTR:
<img width="991" alt="Screenshot 2024-01-30 at 2 51 43 PM" src="https://github.com/datafuselabs/databend/assets/106025534/bcd2669f-5f1b-4fab-b815-80bc978bf751">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
SUBSTR_UTF8, SUBSTRING_UTF8  is transition, ignore it.
use from N for M needn't to record to docs.
