### ISSUE TITLE
bug: can't revoke privileges from users after upgrade databend-query version to v1.2.321-nightly

### ISSUE THREAD

**Issue by pengye91** [datafuselabs/databend#14566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-query: 

select version()
+----------------------------------------------------------------------------------------+
| version()                                                                              |
+----------------------------------------------------------------------------------------+
| 8.0.26-v1.2.322-nightly-d2a0aee647(rust-1.77.0-nightly-2024-01-30T11:35:07.009189580Z) |
+----------------------------------------------------------------------------------------+

databend-meta: 

v1.2.322-nightly

### What's Wrong?

I upgraded databend query from 1.2.241-nightly, and found that I can't revoke the privileges from a user if the privileges are granted with version 1.2.241-nightly. The revoke works if the privileges are granted with version 1.2.321-nightly.

### How to Reproduce?

to reproduce the issue, you need an old version like 1.2.241-nightly databend-query node.

1. in old version databend-query, `grant insert on test_db.test_table to 'test_user';`
2. upgrade the databend-query version to 1.2.321-nightly.
3. in new version databend-query, `revoke insert on test_db.test_table from 'test_user';`
4. in new version databend-query, `show grants for 'test_user';`, you will find the privilege still exists.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
I will have a look

**Comment by TCeason** [comment]
Thanks for you issue. I will fix it at monment. Now you can recreate the user, and re-grant privilege. Because of we do some thing in store grant object. But not consider the old version.

Because of this pr. https://github.com/datafuselabs/databend/pull/14016

Or wait my fix pr, and then try upgrade to the version that contains my fix pr.

**Comment by TCeason** [comment]
```sql
+---------------------------------------------------------------------+
| Grants                                                              |
+---------------------------------------------------------------------+
| GRANT INSERT ON 'default'.'test_db'.'test_table' TO 'test_user'@'%' |
+---------------------------------------------------------------------+
1 row in set (0.014 sec)

MySQL [(none)]> revoke insert on test_db.test_table from 'test_user';
Query OK, 0 rows affected (0.139 sec)

MySQL [(none)]> show grants for test_user;
Empty set (0.008 sec)

mysql -utest_user -p123  -h127.0.0.1 -P3307                                                                                                                                                                                                                                                  ✔  49m 38s   eason@databend-arch1 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.26-v1.2.321-nightly-0c05f068ea(rust-1.77.0-nightly-2024-02-02T08:24:39.712312567Z) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> insert into test_db.test_table values(1);
ERROR 1105 (HY000): PermissionDenied. Code: 1063, Text = Permission denied, privilege [Insert] is required on 'default'.'test_db'.'test_table' for user 'test_user'@'%' with roles [public].

```

Fixed on my local.

**Comment by pengye91** [comment]
Got it, thanks for the suggestion and the fix.

I'll re-create the use for workaround.
