### ISSUE TITLE
bug: Restart databend-query very slow with disk cache

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#14591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.327

### What's Wrong?

Read node with Disk cache restart is very slow.
```
[cache]
data_cache_storage="disk"
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PsiACE** [comment]
Ignore the disk cache status and allow it to become invalid during restart.
