### ISSUE TITLE
Feature:  drop table T all don't drop table information from meta 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#14692]
```
drop table T all;
```
only truncate table on s3 ，don't drop table meta information, so
```
cat 452-1-54464765-1708408097400.snap | grep __fd_table_by_id/ | wc -l
  197463 
```
meta has many table_id .

**Comment by BohuTANG** [comment]
We should use [vacuum drop table](https://docs.databend.com/sql/sql-commands/ddl/table/vacuum-drop-table), `drop table T all` will deprecated soon since it's not fail-safe.
