### ISSUE TITLE
SIMD Vectorized Hashing for Grouped Aggregation

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#1471]
**Summary**
reference:
https://github.com/datafuselabs/datafuse/pull/1443#issuecomment-898871236

**Comment by ZhiHanZ** [comment]
Just seen in hackernews: 
https://dawn.cs.stanford.edu//2018/01/11/index-baselines/
The SIMD based bucket cuckoo hash seems interesting
https://github.com/stanford-futuredata/index-baselines/blob/master/hashing.cpp
