### ISSUE TITLE
bug: deduplicate_label doesn't work when using mysql client

### ISSUE THREAD

**Issue by SkyFan2002** [datafuselabs/databend#14720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

5c46a271e8ee913f9f8443dafc99b2dd4c803303

### What's Wrong?

Deduplicate_label doesn't work when using mysql client

### How to Reproduce?
```
MySQL [(none)]> CREATE TABLE t1(a Int, b bool);
Query OK, 0 rows affected (0.050 sec)

MySQL [(none)]> INSERT /*+ SET_VAR(deduplicate_label='databend') */ INTO t1 (a, b) VALUES(1, false);
Query OK, 1 row affected (0.090 sec)

MySQL [(none)]> SELECT * FROM t1;
+------+------+
| a    | b    |
+------+------+
|    1 |    0 |
+------+------+
1 row in set (0.049 sec)

MySQL [(none)]> UPDATE /*+ SET_VAR(deduplicate_label='databend') */ t1 SET a = 20 WHERE b = false;
Query OK, 1 row affected (0.162 sec)

MySQL [(none)]> SELECT * FROM t1;
+------+------+
| a    | b    |
+------+------+
|   20 |    0 |
+------+------+
1 row in set (0.044 sec)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
mysql client skip comments by default.  

```
mysql -c 
```
This will preserve comments to server.

**Comment by SkyFan2002** [comment]
@wubx Thanks a lt, it works.👍
