### ISSUE TITLE
Add latest tag revision for docker release

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1474]
**Summary**

Currently revision based on release version works for dockerhub image release, thus far I think we should also add latest revision tag for latest nighly release and maybe add stable tag for stable release patch in the future.
Latest Tag Looks like:
datafuselabs/datafuse:latest

**Comment by BohuTANG** [comment]
Nice.
Datafuse bot should auto backport the bugfix or improvement labeled patch to the stable branch, likes Rust train model.

**Comment by Xuanwo** [comment]
Already added.
