### ISSUE TITLE
Feature: Use ScalarVisitor to refactor codes in `optimizer`

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#14779]
**Summary**

Description for this feature.

There are many places that use `match scalar_expr` to replace/find `scalar_exprs`, better use `ScalarVisitor` to improve these codes.

1. `fn replace_predicate`
2. `fn replace_predicate_column`
3. `fn collect_columns_impl`
4. ...

**Comment by TCeason** [comment]
Got. Now I see privilege part code. Tomorrow I will do this issue.

**Comment by TCeason** [comment]
https://github.com/datafuselabs/databend/pull/15215
