### ISSUE TITLE
Feature: prql dialect support

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#14811]
**Summary**

Description for this feature.

```
SET dialect = 'prql';
...
```

PRQLC could compile prql into SQL:

https://github.com/PRQL/prql/blob/main/prqlc/prqlc/src/lib.rs
```
//! - Compile PRQL queries to SQL at run time.
//!
//!     ```
//!     # fn main() -> Result<(), prqlc::ErrorMessages> {
//!     let sql = prqlc::compile(
//!         "from db.albums | select {title, artist_id}",
//!          &prqlc::Options::default().no_format()
//!     )?;
//!     assert_eq!(&sql[..35], "SELECT title, artist_id FROM albums");
//!     # Ok(())
//!     # }
//!     ```
```

**Comment by hanxuanliang** [comment]
Is the intent of this issue to migrate PRQL to the databend: PRQLC -> databend SQL?

One question above: Where is  `SET dialect = 'prql';` ?

**Comment by sundy-li** [comment]
`SET dialect = 'prql'; `  is common sql, it should be parsed by ast.

If the setting is enabled, we should parse the query using PRQL to sql string and then parse it using current parser.

**Comment by ncuwaln** [comment]
Could assign this issue to me?

**Comment by ncuwaln** [comment]
Hi, I would like to discuss when `set sql_dialect = 'prql';`, should we allow the execution of sql or only allow the execution of set statements to switch dialects?

If we allow sql maybe like this: 

![image](https://github.com/datafuselabs/databend/assets/15335564/89dd4126-be91-41a8-b8c8-6b27753b61e3)

**Comment by sundy-li** [comment]
> should we allow the execution of sql or only allow the execution of set statements to switch dialects

Yes. That's we need.
