### ISSUE TITLE
Feature: Policy return null(string)

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#14816]
**Summary**

https://docs.databend.com/sql/sql-commands/ddl/mask-policy/create-mask-policy#examples
```
CREATE TABLE user_info (
    id INT,
    email STRING
);
```

```
CREATE MASKING POLICY email_mask
AS
  (val string)
  RETURNS string ->
```

ALTER TABLE user_info MODIFY COLUMN email SET MASKING POLICY email_mask;
error: APIError: ResponseError with 1114: Column 'email' data type string null does not match to the mask policy type string

becuse email is varchar null

**Comment by sundy-li** [comment]
```
🐳 :) CREATE MASKING POLICY email_mask
AS
  (val string)
  RETURNS string -> 'a';
processed in (0.045 sec)
```
