### ISSUE TITLE
bug: The results of the NVL function may be incorrect

### ISSUE THREAD

**Issue by guojidan** [datafuselabs/databend#14858]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main branch

### What's Wrong?

because `nvl` rewrite to `if(is_not_null(x), x, y)`, so `x` Expr will calculate twice,  if `x` is volatile like `nullif(rand()>0.5, true)`, The results of the two calculations will be different，example, below sql should be always false, but this bug will make it possible to be true

`select nvl(nullif(rand()>0.5, true), false) is null from (unnest(range(1,10)));`
```
root@localhost:8000/default> select nvl(nullif(rand()>0.5, true), false) is null from (unnest(range(1,10)));

SELECT
  nvl(nullif(rand() > 0.5, TRUE), false) IS NULL
FROM
  (unnest(RANGE(1, 10)))

┌──────────────────────────────────────────────────┐
│ nvl(nullif((rand() > 0.5), true), false) is null │
│                      Boolean                     │
├──────────────────────────────────────────────────┤
│ true                                             │
│ false                                            │
│ false                                            │
│ false                                            │
│ false                                            │
│ false                                            │
│ true                                             │
│ false                                            │
│ true                                             │
└──────────────────────────────────────────────────┘
9 rows read in 0.110 sec. Processed 1 rows, 1 B (9.06 rows/s, 9 B/s)
```

### How to Reproduce?

run sql: select nvl(nullif(rand()>0.5, true), false) is null from (unnest(range(1,10)));

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by guojidan** [comment]
`ifnull` maybe have same bug

**Comment by PsiACE** [comment]
I have written a simple patch, expecting it to fix this issue.
