### ISSUE TITLE
Flaky ci: test_meta_node_replicate_kv_with_expire

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#14879]
https://github.com/datafuselabs/databend/actions/runs/8186693829/job/22385608245?pr=14862

        FAIL [   0.077s] databend-meta::it meta_node::meta_node_kv_api_expire::test_meta_node_replicate_kv_with_expire

running 1 test
3973test meta_node::meta_node_kv_api_expire::test_meta_node_replicate_kv_with_expire ... FAILED
3974
3975failures:
3976
3977failures:
3978    meta_node::meta_node_kv_api_expire::test_meta_node_replicate_kv_with_expire
3979
3980test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 60 filtered out; finished in 0.05s
3981
3982
3983--- STDERR:              databend-meta::it meta_node::meta_node_kv_api_expire::test_meta_node_replicate_kv_with_expire ---
3984[src/meta/service/tests/it/tests/meta_node.rs:158:5] &tc.config.raft_config.raft_dir = "./.databend/meta-29000"
3985thread 'meta_node::meta_node_kv_api_expire::test_meta_node_replicate_kv_with_expire' panicked at src/meta/service/tests/it/meta_node/meta_node_kv_api_expire.rs:92:9:
3986assertion failed: (want..want + 800).contains(&expire_ms)
3987note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
3988

**Comment by TCeason** [comment]
cc @drmingdrmer

**Comment by drmingdrmer** [comment]
Thanks for informing me about this issue:D
