### ISSUE TITLE
Update sqllogictest crate to the latest

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#14874]
**Summary**
https://github.com/risinglightdb/sqllogictest-rs

**Comment by TracyZYJ** [comment]
Please assign me :)

**Comment by xudong963** [comment]
> Hi I modify the toml upgrade sqllogictest to 0.19.1. But it occurs some strange error msg. Could you please have a look?

Yes, you need to track the changelog of sqllogictest and find the places that need to fix.

**Comment by TracyZYJ** [comment]
Sorry, due to busy work lately, we may not be able to complete this task. I will cancel the assignment now
