### ISSUE TITLE
feat: INSERT FIRST WHEN

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14886]
**Summary**

Multi-Table Inserts with Conditions:
```
INSERT FIRST
    WHEN flag = 1 THEN INTO t_1 VALUES (...)
    WHEN flag = 2 THEN INTO t_2 VALUES (...)
    ...

SELECT
    v['flag'] flag,
    ...
    v['id'],
    NOW() create_at
FROM
    json_stream;
```

`INSERT FIRST WHEN` is a construct used for conditional multi-table inserts. It allows you to insert data into different tables based on conditions. The conditions are evaluated sequentially, and the first matching condition triggers the insertion into the corresponding table. Subsequent conditions are not evaluated.

**Comment by sundy-li** [comment]
#15002
