### ISSUE TITLE
feat: show views and desc view

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#14889]
**Summary**
 
show views;

desc | describe view <view_name>;

**Comment by blackstar-baba** [comment]
LGTM, can i do this feature?

**Comment by TCeason** [comment]
> LGTM, can i do this feature?

Absolutely ok. Actually you can pick all issue with good first issue label.

**Comment by blackstar-baba** [comment]
thks

**Comment by rad-pat** [comment]
Also `select * from information_schema.views;` if possible?

**Comment by blackstar-baba** [comment]
Grammar design：
1. `show views`, follow `show tables` grammar:
```
SHOW [ FULL ] VIEWS 
    [ {FROM | IN} <database_name> ] 
    [ HISTORY ] 
    [ LIKE '<pattern>' | WHERE <expr> ]
```
2. `desc vew`, follow `desc table` grammar:
```
DESC|DESCRIBE [VIEW] [ <database_name>. ]<view_name>
```

**Comment by rad-pat** [comment]
Is it possible to also have `SHOW CREATE VIEW` with this issue/PR?

**Comment by blackstar-baba** [comment]
> Is it possible to also have `SHOW CREATE VIEW` with this issue/PR?

Hi, bro, i can add new pr to do this, i changed too many files in this feature.

**Comment by TCeason** [comment]
> Is it possible to also have `SHOW CREATE VIEW` with this issue/PR?

Now Databend has this: 

```sql
show create table v1;
+-------+-------------------------------------------------------+
| Table | Create Table                                          |
+-------+-------------------------------------------------------+
| v1    | CREATE VIEW `default`.`v1` AS SELECT * FROM default.t |
+-------+-------------------------------------------------------+
```
