### ISSUE TITLE
Feature:  support wasm udf

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#14925]
**Summary**

Description for this feature.

crate: https://github.com/risingwavelabs/arrow-udf/

Releated code in databend:  TransformUDFScript.rs

**Comment by shamb0** [comment]
Hi @sundy-li, I'd like to take on this feature implementation. Could you please assign it to me? Thank you.

**Comment by shamb0** [comment]
@sundy-li, 

The initial draft of the code changes is now available for review in [PR#15107](https://github.com/datafuselabs/databend/pull/15107). 

Please disregard the changes related to code tracing, as those were added temporarily for development purposes. I will clean up those changes before the final merge. 

Kindly review the core changes and provide your feedback.
