### ISSUE TITLE
bug: as_array not working properly

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#14923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main 

### What's Wrong?

```
root@localhost:8000/default> SELECT as_array(parse_json('[1,2,3]')) c1, typeof(c1);

SELECT
  as_array(parse_json('[1,2,3]')) c1,
  typeof(c1)

-[ RECORD 1 ]-----------------------------------
        c1: [1,2,3]
typeof(c1): VARIANT --> exepct array

1 row read in 0.010 sec. Processed 1 row, 1 B (99.66 row/s, 99 B/s)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
please check the doc before submit issue.

https://docs.databend.com/sql/sql-functions/semi-structured-functions/as-type
