### ISSUE TITLE
bug: sugger function cannot found when args incorrect

### ISSUE THREAD

**Issue by guojidan** [datafuselabs/databend#14921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main branch

### What's Wrong?

I excute sql `SELECT IFNULL(NULL);` databend prompt me ifnull does not exist

```
root@localhost:8000/default> SELECT IFNULL(NULL);
error: APIError: ResponseError with 1008: error: 
  --> SQL:1:8
  |
1 | SELECT IFNULL(NULL)
  |        ^^^^^^^^^^^^ function `ifnull` does not exist
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by guojidan** [comment]
cc @PsiACE

**Comment by Holly001** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.
> 
> ### Version
> main branch
> 
> ### What's Wrong?
> I excute sql `SELECT IFNULL(NULL);` databend prompt me ifnull does not exist
> 
> ```
> root@localhost:8000/default> SELECT IFNULL(NULL);
> error: APIError: ResponseError with 1008: error: 
>   --> SQL:1:8
>   |
> 1 | SELECT IFNULL(NULL)
>   |        ^^^^^^^^^^^^ function `ifnull` does not exist
> ```
> 
> ### How to Reproduce?
> _No response_
> 
> ### Are you willing to submit PR?
> * [ ]  Yes I am willing to submit a PR!

should be:

SELECT IFNULL(NULL, 'b'), IFNULL('a', 'b');

┌──────────────────────────────────────┐
│ ifnull(null, 'b') │ ifnull('a', 'b') │
├───────────────────┼──────────────────┤
│ b                 │ a                │
└──────────────────────────────────────┘

SELECT IFNULL(NULL, 2), IFNULL(1, 2);

┌────────────────────────────────┐
│ ifnull(null, 2) │ ifnull(1, 2) │
├─────────────────┼──────────────┤
│               2 │            1 │
└────────────────────────────────┘

**Comment by ziwenzhou96** [comment]
> ### 询问前先搜索
> * [x] [我在问题](https://github.com/datafuselabs/databend/issues)中搜索过，没有发现类似的问题。
> 
> ### 版本
> 主枝
> 
> ### 怎么了？
> 我执行sql `SELECT IFNULL(NULL);`databend提示我ifnull不存在
> 
> ```
> root@localhost:8000/default> SELECT IFNULL(NULL);
> error: APIError: ResponseError with 1008: error: 
>   --> SQL:1:8
>   |
> 1 | SELECT IFNULL(NULL)
>   |        ^^^^^^^^^^^^ function `ifnull` does not exist
> ```
> 
> ### 如何重现？
> _没有反应_
> 
> ### 你愿意提交PR吗？
> * [ ] 是的，我愿意提交 PR！

try:

```
SELECT IFNULL(NULL, 'b'), IFNULL('a', 'b');

┌──────────────────────────────────────┐
│ ifnull(null, 'b') │ ifnull('a', 'b') │
├───────────────────┼──────────────────┤
│ b                 │ a                │
└──────────────────────────────────────┘

SELECT IFNULL(NULL, 2), IFNULL(1, 2);

┌────────────────────────────────┐
│ ifnull(null, 2) │ ifnull(1, 2) │
├─────────────────┼──────────────┤
│               2 │            1 │
└────────────────────────────────┘
```
