### ISSUE TITLE
Column pruning disabled in stateless-cluster test setting?

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1495]
Seems in `stateless-tests-cluster` setting, `ReadDataSource` plan ignores the projection operation.

While fixing issue #1487, noticed that
- given a table like this
 ` CREATE TABLE IF NOT EXISTS t1(a UInt32, b UInt64, c String);`
- when executing statement
  `SELECT a from t1;`
- In `ci-run-stateless-tests-standalone` setting --- 1 Query node, 1 Store node 
  the plan passed to `read_partition` is 
> ReadDataSource: scan partitions: [1], **scan schema: [a:UInt32]**
es: 904]
- In `ci-run-stateless-tests-cluster` setting --- 3 Query node, 1 Store node 
  the plan passed to `read_partition` is 
> ReadDataSource: scan partitions: [1], **scan schema: [a:UInt32, b:UInt64, c:Utf8]**

FYI: PR for issue #1487 

- #1489

without this pr, `SELECT a from t1` can be executed happily in  `ci-run-stateless-tests-cluster` setting, but not in `ci-run-stateless-tests-standalone`

**Comment by BohuTANG** [comment]
It looks like a bug in the cluster mode.
I make it as bug here.

**Comment by dantengsky** [comment]
staled
