### ISSUE TITLE
bug: FROM_BASE64 function fails on invalid Base64 string instead of returning NULL.

### ISSUE THREAD

**Issue by dixel** [datafuselabs/databend#14968]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Databend Query v1.2.371-a95ac62303(rust-1.77.0-nightly-2024-03-11T01:08:34.998379960Z)

### What's Wrong?

When the input string is not a valid or partially corrupted base64 string - the function FROM_BASE64 fails and prevents the whole query from execution.
As a mitigation I was looking for some alternative ways for skipping invalid rows (for JSON there is a failsafe function "TRY_PARSE_JSON"), but with no luck.
For this function, as it's pretty standard - simply having `NULL` for invalid strings as per documentation (https://docs.databend.com/sql/sql-functions/string-functions/from-base64) seems sufficient.

### How to Reproduce?

```sql
$: SELECT from_base64('ajsdhjaksjdhkjh123123');
error: APIError: ResponseError with 1006: Encoded text cannot have a 6-bit remainder. while evaluating function `from_base64('ajsdhjaksjdhkjh123123')`
$: SELECT from_base64('ajsdhjaksjdhkjh1231');
error: APIError: ResponseError with 1006: Invalid padding while evaluating function `from_base64('ajsdhjaksjdhkjh1231')`
$: SELECT from_base64('QQ');
error: APIError: ResponseError with 1006: Invalid padding while evaluating function `from_base64('QQ')`
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Maybe we should introduce try_xxx adaptor as failsafe function.
