### ISSUE TITLE
Feature: query table with sample

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#14971]
**Summary**

Description for this feature.

```
SELECT ...
FROM TABLE_NAME SAMPLE [ ROW | BLOCK ] ( { <probability> | <num> ROWS } )
[ ... ]
```

Example:

```
select * from t sample row (10 rows);  -- query sample result to 10 rows
select * from t sample row (90.9);  -- 90.9% possibility data
select * from t sample row (90.9);  -- 90.9% possibility row
```

- ROW: Includes each row with a probability of p/100. Similar to flipping a weighted coin for each row.

- BLOCK: Includes each block of rows with a probability of p/100. Similar to flipping a weighted coin for each block of rows. This method does not support fixed-size sampling.

**Comment by ncuwaln** [comment]
Could assign this issue to me? if it's not urgent

**Comment by ncuwaln** [comment]
For BLOCK, we should push the info to PushDownInfo, and handle it in read_partitions to prune segments.
For ROW, we just push it to where condition, And it may be pushed into prewhere by planner

Is my understanding correct?

**Comment by sundy-li** [comment]
That's correct.

For row maybe you can build a filter with `rand` function.

**Comment by ncuwaln** [comment]
There is a question I would like to discuss. Is the sample for a single table or the entire table?
`FROM a sample BLOCK (90), b sample BLOCK (80)`
or 
`FROM a, b sample BLOCK (90)`

**Comment by sundy-li** [comment]
> FROM a sample BLOCK (90), b sample BLOCK (80)

I think it's for simple table.

**Comment by xudong963** [comment]
@ncuwaln Hi, are you doing the issue?

**Comment by ncuwaln** [comment]
> @ncuwaln Hi, are you doing the issue?
I'm very sorry. I've been quite busy with  my job recently, so I may not be able to handle this issue recently. If you have other schedule, please go ahead.

**Comment by xudong963** [comment]
For some cases, maybe we need stable outputs, so we can consider adding the `seed()` option later. Any thoughts? cc @sundy-li

**Comment by sundy-li** [comment]
>  maybe we need stable outputs, so we can consider adding the seed() option later. 

we can use `select count() between a and b  from (sample_query)` to verify the sample result.

`seed()` option makes the syntax more complex but only help in testing, so I recomment not.
