### ISSUE TITLE
bug: max_col_width does not work when max_width is big enough

### ISSUE THREAD

**Issue by soyeric128** [datafuselabs/databend#15053]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Databend Query v1.2.379-nightly-2c55653af1(rust-1.77.0-nightly-2024-03-17T22:11:30.967419440Z)
bendsql 0.13.2-4419bda(2024-02-02T04:21:46.064145000Z)

### What's Wrong?

The 1st query was presented as expected; In the 2nd query, the `max_col_width` lost control to the col width when the `max_width` was set to a big enough value. 
<img width="1900" alt="Screenshot 2024-03-21 at 12 00 50 AM" src="https://github.com/datafuselabs/databend/assets/106025534/c8db1824-382a-40c2-b630-b068d17dcfb3">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
it's by desgin.
