### ISSUE TITLE
increase `default_wait_time_secs` to be 10 secs

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#15097]
**Summary**

The databend drivers using HTTP API mostly forget to fetch the result after sending requests to the server.

Let us increase `default_wait_time_secs` to 10 secs instead of 1 sec.

Related issue:
https://github.com/datafuselabs/databend-sqlalchemy/issues/23 

cc @hantmac  @youngsofun  @BohuTANG   for comments.

**Comment by youngsofun** [comment]
LGTM
