### ISSUE TITLE
Implement `Visitor` for SQL AST

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#1511]
Part of #1218

**Comment by jackwener** [comment]
I'm willing to take the task up.
But I'm not familiar with rust. It may cost some time.

**Comment by jackwener** [comment]
assignme

**Comment by leiysky** [comment]
> I'm willing to take the task up.
> 
> But I'm not familiar with rust. It may cost some time.

It doesn't matter, you can refer to implementation of `PlanVisitor`.

**Comment by CNLHC** [comment]
let me try implement this feature as well as  #1759

**Comment by jackwener** [comment]
Hi, I notice that it doesn't progress.

If you aren't free to this issue, I can take it up.

**Comment by BohuTANG** [comment]
@jackwener feel free to take it :D
