### ISSUE TITLE
Question: should we return exactly matching functions first?

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#15231]
**Summary**

The `eval_map_index` create `get_expr` using `check_function`:
https://github.com/datafuselabs/databend/blob/13afda707ea2567908d43bcdd3ed10dacbcff6f6/src/query/storages/common/index/tests/it/filters/bloom_filter.rs#L369-L388

here the `map_ty` is `Map(Tuple([Number(UInt8), String]))`, ideally we should get this function signature from `check_function`, let's call it **f1**:
`function: FunctionSignature { name: "get", args_type: [Map(Tuple([Generic(0), Generic(1)])), Generic(0)], return_type: Nullable(Generic(1)) }`

but we get this newly added `get` function because its order is higher, let's call it **f2**:
`function: FunctionSignature { name: "get", args_type: [Map(Tuple([Generic(0), Nullable(Generic(1))])), Generic(0)], return_type: Nullable(Generic(1)) }`

I fix this by adding a new pattern in #15230 :

https://github.com/datafuselabs/databend/blob/13afda707ea2567908d43bcdd3ed10dacbcff6f6/src/query/storages/common/index/src/bloom_index.rs#L605-L606

But I think the root cause is we should return the **f1** as it exactly matches the `map_ty`, we got **f2** here because `check_function` first checks **f2** as its order is higher than **f1** and then `check_function` found `Map(Tuple([Number(UInt8), String]))` can cast to `Map(Tuple([Number(UInt8), Nullable(String)]))`

I think we should check if there is a function that exactly matches, if not found, we then return a cast one. I'm not sure this actually an issue.

**Comment by BohuTANG** [comment]
I would like to ping with @sundy-li and @b41sh. Do you have any suggestions regarding this issue?

**Comment by sundy-li** [comment]
nullable signature should be registered after the non-nullable. I think pr #https://github.com/datafuselabs/databend/pull/15230 is not the correct way to fix double nullable.

**Comment by ariesdevil** [comment]
> nullable signature should be registered after the non-nullable. I think pr ##15230 is not the correct way to fix double nullable.

Yup, that's Adhoc fix, but I think nullable sig after the non-nullable suitable for concrate types, not for Generic type.
