### ISSUE TITLE
Feature: support expression table scan

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#15259]
**Summary**

Currently, databend has `ConstantTableScan` which is mainly used by `Values(...)`.

In https://github.com/datafuselabs/databend/issues/15255, `Values` contains a column that isn't the constant value but expression. To address the issue and improve the ability of `Values(...)`, we should make `ConstantTableScan` more flexible and support `ExpressionTableScan`.

**Comment by inviscid** [comment]
Is there any estimate on when this might get selected for development?

**Comment by Dousir9** [comment]
> Is there any estimate on when this might get selected for development?

I am working on it ~

**Comment by inviscid** [comment]
@Dousir9 Excellent to hear you picked this up.  I was wondering if you had an ETA or need any help with testing.

**Comment by Dousir9** [comment]
@inviscid Thanks for your help, expect a PR within a week.
