### ISSUE TITLE
bug: error using IFNULL or COALESCE in statement

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#15256]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

https://github.com/datafuselabs/databend/releases/tag/v1.2.423-nightly

### What's Wrong?

Get error `no overload satisfies `assume_not_null(NULL)` when adding `IFNULL` or `COALESCE` into statement

See below SQL, if line 
`WHERE IFNULL(base.context, '') = ''`
reads
`WHERE base.context = ''`
Then the SQL works ok, but if COALESCE OR IFNULL used, it raises the exception

### How to Reproduce?

```sql
drop table if exists m1;
drop table if exists j1;
create table m1(id varchar, "context" varchar);
create table j1(id varchar);

WITH base
AS (
	SELECT id, context
	FROM m1
	)
	,src1
AS (
	SELECT base.id
	FROM base
	WHERE IFNULL(base.context, '') = ''
	)
	,join1
AS (
	SELECT id
	FROM j1
	)
SELECT src1.id
FROM src1
LEFT OUTER JOIN join1 ON true;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
To address this issue, I'd like to bring @sundy-li into the investigation.
