### ISSUE TITLE
Feature: Add Flexible Date Parsing in to_timestamp for Better Conversion Support

### ISSUE THREAD

**Issue by inviscid** [datafuselabs/databend#15257]
**Summary**

Enable partial matching of a format string when converting datetime values.  Match as much as possible and default the rest.

**Feature Request**
This is an unfortunate reality from customer data in the wild.  It often is very inconsistent in date formats depending on the system or even the time period that the data was extracted from the system.  Postgres/Greenplum handles the date parsing of inconsistent formats by matching as much as possible from left to right and then defaulting the unfound tokens.  This is a very useful feature when the quality of inbound data can be suspect.

For example:
```
select to_timestamp('2022-04-16T13:01:59', '%Y-%m-%dT%H:%M:%S') --> 2022-04-16 13:01:59.000
select to_timestamp('2022-04-16T13:01:59', '%Y-%m-%d') --> error, not 2022-04-16 00:00:00.000
```

The desired behavior is:
```
select to_timestamp('2022-04-16T13:01:59', 'YYYY-MM-DD"T"HH24:MI:SS') --> 2022-04-16 13:01:59.000
select to_timestamp('2022-04-16T13:01:59', 'YYYY-MM-DD') --> 2022-04-16 00:00:00.000
select to_timestamp('2022-04-16T13:01:59', 'YYYY-MM') --> 2022-04-01 00:00:00.000
select to_timestamp('2022-04-16T13:01:59', 'YYYY') --> 2022-01-01 00:00:00.000

select to_timestamp('16/04/2022 13:01:59', 'DD/MM/YYYY HH24:MI:SS') --> 2022-04-16 13:01:59.000
select to_timestamp('16/04/2022 13:01:59', 'DD/MM/YYYY') --> 2022-04-16 00:00:00.000
```

This is currently hindering our efforts to migrate from Greenplum to Databend because our CSV import testing with real world data is failing.

**Comment by inviscid** [comment]
@TCeason - Issue based on Slack conversation

**Comment by sundy-li** [comment]
But this may cause some problems:

```
select to_timestamp('2022-04-16xxxxxxxxx', 'YYYY-MM-DD') --> xxxxxxxxx is some unexpected value, do you want to have 2022-04-16 00:00:00.000 ? or throw the parse error 
```

**Comment by TCeason** [comment]
As I known:

in sf, not support this: SELECT TO_TIMESTAMP('04/05/2013 01:02:03', 'mm/dd/yyyy');

in MySQL/Postgres support this parse but it will ignore the trailing chars:

```sql
-- MySQL
SELECT STR_TO_DATE("August 2017xx", "%M %d %Y");
-- PG
postgres=# select to_timestamp('2022-04-16T13:01:59xxx', 'YYYY');
      to_timestamp      
------------------------
 2022-01-01 00:00:00+08
(1 row)
```

**Comment by TCeason** [comment]
> As I known:
> 
> in sf, not support this: SELECT TO_TIMESTAMP('04/05/2013 01:02:03', 'mm/dd/yyyy');
> 
> in MySQL/Postgres support this parse but it will ignore the trailing chars:
> 
> ```sql
> -- MySQL
> SELECT STR_TO_DATE("August 2017xx", "%M %d %Y");
> -- PG
> postgres=# select to_timestamp('2022-04-16T13:01:59xxx', 'YYYY');
>       to_timestamp      
> ------------------------
>  2022-01-01 00:00:00+08
> (1 row)
> ```

Maybe we can add a setting to control it. Default not support this parse. If enable the new setting, support it.

**Comment by rad-pat** [comment]
Regarding this issue, I'm currently getting an issue with this SQL with the `parse_datetime_ignore_remainder` setting turned on. This is slightly different in that the year and month match the pattern, but there is no day. Again, similar format in Postgres is working 'YYYY_MM_DD'
```
select to_timestamp('2019_10', '%Y_%m_%d')
to_timestamp('2019_10', '%y_%m_%d')|
-----------------------------------+
                                   |
```
whereas:
```
to_timestamp('2019_10', '%y_%m')|
--------------------------------+
         2019-10-01 00:00:00.000|
```

**Comment by TCeason** [comment]
> select to_timestamp('2019_10', '%Y_%m_%d')

With this wrong string, now we only support this format:

SELECT
  to_timestamp('2019_10', '%Y_%m')

┌──────────────────────────────────┐
│ to_timestamp('2019_10', '%y_%m') │
│             Timestamp            │
├──────────────────────────────────┤
│ 2019-10-01 00:00:00              │
└──────────────────────────────────┘

If must need %d, you can use :

```
root@localhost>  select if(try_to_timestamp('2019_10_01', '%Y_%m_%d') is null, '2019-10-01 00:00:00'::Datetime, try_to_timestamp('2019_10_01', '%Y_%m_%d'));

SELECT
  IF(
    try_to_timestamp('2019_10_01', '%Y_%m_%d') IS NULL,
    '2019-10-01 00:00:00' :: Datetime,
    try_to_timestamp('2019_10_01', '%Y_%m_%d')
  )

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ if(try_to_timestamp('2019_10_01', '%y_%m_%d') is null, '2019-10-01 00:00:00'::timestamp, try_to_timestamp('2019_10_01', '%y_%m_%d')) │
│                                                               Timestamp                                                              │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 2019-10-01 00:00:00                                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row in 0.069 sec. Processed 1 rows, 1B (14.51 rows/s, 14B/s)

root@localhost>  select if(try_to_timestamp('2019-02', '%Y-%m-%d') is null, '2022-02-02'::timestamp, try_to_timestamp('2019-02', '%Y-%m')) ;

SELECT
  IF(
    try_to_timestamp('2019-02', '%Y-%m-%d') IS NULL,
    '2022-02-02' :: timestamp,
    try_to_timestamp('2019-02', '%Y-%m')
  )

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ if(try_to_timestamp('2019-02', '%y-%m-%d') is null, '2022-02-02'::timestamp, try_to_timestamp('2019-02', '%y-%m')) │
│                                                      Timestamp                                                     │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 2022-02-02 00:00:00                                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
1 row in 0.047 sec. Processed 1 rows, 1B (21.24 rows/s, 21B/s)

```

**Comment by rad-pat** [comment]
> > select to_timestamp('2019_10', '%Y_%m_%d')
> 
> With this wrong string, now we only support this format:
> 
> SELECT to_timestamp('2019_10', '%Y_%m')

Unfortunately, these date formats are written by an end user and we are using a converter to make the format work in Databend. If they included the day specifier and it worked in Postgres but now gives nulls in Databend then this will cause silent data issues.

**Comment by rad-pat** [comment]
@TCeason  - new issue https://github.com/datafuselabs/databend/issues/15849
