### ISSUE TITLE
The stateless test fails.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#1527]
https://github.com/datafuselabs/datafuse/pull/1526/checks?check_run_id=3374756012

Seems like some dependency is updated?

**Comment by zhang2014** [comment]
log is broken
```
09_0001_remote_insert  [ FAIL ] - Timeout!
```

@dantengsky
https://github.com/datafuselabs/datafuse/pull/1526/checks?check_run_id=3374756012#step:6:297
https://github.com/datafuselabs/datafuse/pull/1526/checks?check_run_id=3374756012#step:6:444

**Comment by BohuTANG** [comment]
@dantengsky may help on this

**Comment by dantengsky** [comment]
Some unknown test case timed-out(detected by py script datafuse-test), trying to dig it out

**Comment by dantengsky** [comment]
> log is broken
> 
> ```
> 09_0001_remote_insert  [ FAIL ] - Timeout!
> ```
> 
> duplicate [#548 (comment)](https://github.com/datafuselabs/datafuse/issues/548#issuecomment-900989497)
> 
> CC: @dantengsky
> https://github.com/datafuselabs/datafuse/pull/1526/checks?check_run_id=3374756012#step:6:297
> https://github.com/datafuselabs/datafuse/pull/1526/checks?check_run_id=3374756012#step:6:444

got it & thanks

**Comment by dantengsky** [comment]
for who is also investigating this issue:

the raw log

https://pipelines.actions.githubusercontent.com/Zgqden0KhWGRXpIXPBTtTR2O0h9dPB76KbDLD2GlEOYbcWXWjs/_apis/pipelines/1/runs/27817/signedlogcontent/3?urlExpires=2021-08-20T06%3A34%3A59.9726307Z&urlSigningMethod=HMACV1&urlSignature=pdHRq4j%2FeKeypOO6UDwNZldzr65l%2FEl%2F%2Bc3F1IbpdVg%3D

seems indicating that test case `09_0003_remote_drop_table` triggered a timeout:

-----------

2021-08-19T18:12:39.8365727Z 09_0003_remote_drop_table:

.................

2021-08-19T18 **:12:** 40.8805961Z [2021-08-19T18:12:40Z INFO  datafuse_store::api::rpc::flight_service] Receive do_action: GetTableExt(GetTableExtReq { tbl_id: 7, tbl_ver: None })
.......

2021-08-19T18 **:22:** 39.6846493Z [ FAIL ] - Timeout!

-----------



According to the log message, the test case seems being executing  `SELECT * FROM t2`

https://github.com/datafuselabs/datafuse/blob/681efe24288e41adacd9e5ce978f361a6d37ab42/tests/suites/0_stateless/09_0003_remote_drop_table.sql#L24
