### ISSUE TITLE
Constant folding takes too long

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#15293]
**Summary**

When expr is a `contains` function, aka `inlist`, if the list is large, constant fold will take too long to finish.

![image](https://github.com/datafuselabs/databend/assets/41979257/67af4c1a-a3fd-42e9-a7fc-838d6a050f12)

**Comment by sundy-li** [comment]
cc @andylokandy, maybe we should return full domain for large array?

```
Column::Array(col) => {
                if col.len() == 0 || col.values.len() == 0 {
                    Domain::Array(None)
                } else {
                    let inner_domain = col.values.domain();
                    Domain::Array(Some(Box::new(inner_domain)))
                }
            }
```

**Comment by andylokandy** [comment]
Seems like ConstantFolder is trying to evaluate each item in the array. This could be verified if constructing such an big array is also slow.

Maybe the ConstantFolder should stop if timeout.

**Comment by sundy-li** [comment]
> Maybe the ConstantFolder should stop if timeout.

The `ConstantFolder` could be called for each block, timeout may not be the solution.

**Comment by xudong963** [comment]
I think "heavy" filters should be forbidden to fold or be used as the index.
