### ISSUE TITLE
bug: replace into when on fields have bool type will insert a new record

### ISSUE THREAD

**Issue by Caisin** [datafuselabs/databend#15307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

 v1.2.313-nightly-3acb8aaedc(rust-1.77.0-nightly-2024-01-23T22:05:48.341888173Z)

### What's Wrong?

replace into when on fields have bool type will insert a new record

### How to Reproduce?

replace into a on(f1,f2,f3) select f1,f2,f3 from b

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dantengsky** [comment]
@Caisin Thanks for reporting the bug,  it should be fixed by PR #15315 which included in rel [v1.2.433-nightly](https://github.com/datafuselabs/databend/releases/tag/v1.2.433-nightly), Please give it a try and let us know if it resolves the issue.
