### ISSUE TITLE
Unable to run Databend locally

### ISSUE THREAD

**Issue by SanjaySiddharth** [datafuselabs/databend#15396]
I was trying to install databend and followed all instructions from this site : https://docs.databend.cn/doc/contributing/building-from-source/

I installed all the pre-requisite softwares as required and successfully cloned the repository to my local folder. However , while trying to install the dependencies using this command : 
```
make setup -d  
```
I faced an error dump . Attaching the log for more information . 
[log.txt](https://github.com/datafuselabs/databend/files/15213380/log.txt)

Please let me know how to proceed and install it successfully.

**Comment by zhang2014** [comment]
Building `databend` in `windows system` has not been validated. Please use ubuntu to try again.
