### ISSUE TITLE
bug: ignore statement not supported

### ISSUE THREAD

**Issue by MatthewFin** [datafuselabs/databend#15404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.410-4b8cd16f0c

### What's Wrong?

The [docs](https://docs.databend.com/sql/sql-functions/other-functions/ignore) state that an `IGNORE` statement can be used with an INSERT INTO to ignore rows with invalid data.

However, running an insert with this statement fails.

### How to Reproduce?

```
CREATE TABLE example (
    field_1 STRING,
    field_2 STRING
);

INSERT ignore INTO example (field_1, field_2) VALUES ('hello', 'there'), ('123', 'yes')
```

response is 
```
error: APIError: ResponseError with 1005: error:
  --> SQL:1:8
  |
1 | INSERT ignore INTO example (field_1, field_2) VALUES ('hello', 'there'), ('123', 'yes')
  |        ^^^^^^ unexpected `ignore`, expecting `INTO`, `OVERWRITE`, or `/*+`
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Upon further investigation, we have discovered that Databend does not support `IGNORE` option, the documentation is misleading on this point and will be updated shortly to remove any confusion.
