### ISSUE TITLE
feat: unset session <session>

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#15498]
**Summary**

Databend now supports the `unset <settings>` command, which is designed to remove global settings from the metasrv. We plan to expand this functionality with additional unset commands:

```sql
unset [session] <setting>; -- Only unset a setting at the session level.
```

For example:
```
-- load_file_metadata_expire_hours default is 248

set global load_file_metadata_expire_hours=12;
-- show settings like '%load_file_metadata_expire_hours%';
-- 12 global-level

set load_file_metadata_expire_hours=13;
-- show settings like '%load_file_metadata_expire_hours%';
-- 13 session-level

unset session load_file_metadata_expire_hours;
-- show settings like '%load_file_metadata_expire_hours%';
-- 12 global-level
```

**Comment by vaibhawvipul** [comment]
I would like to take this up, if no one is working on this.

**Comment by BohuTANG** [comment]
@vaibhawvipul Thank you for considering this issue. However, it's not a good first issue as it has high priority in our plan, and we have some discussions and decisions to make regarding it.

We do have some other good first issues, but this one is highly recommended at the moment: #15295

Here is a list of all the good first issues:
https://github.com/datafuselabs/databend/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
