### ISSUE TITLE
[Improvement] Move out optimizers and catalogs mod from query to common

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1550]
**Summary**

`optimizers` and `catalogs` may be used externally, e.g. by an optimizer service, they should be a common library.
Consider move them to `common` as:

```
 common
   - catalogs
   - optimizers
```

**Comment by zhang2014** [comment]
It may not be that easy. Datafuse query context is required in optimizer.

**Comment by BohuTANG** [comment]
> It may not be that easy. Datafuse query context is required in optimizer.

Hmm, Optimizer use ctx to get table schema, we can get them from catalogs mod directly.

**Comment by BohuTANG** [comment]
ScattersOptimizers maybe a special case, we can keep it still in the query.

**Comment by zhang2014** [comment]
> Hmm, Optimizer use ctx to get table schema, we can get them from catalogs mod directly.


👍  Maybe optimizer will still use settings (some switches). But the refactoring settings are in my todo list(#1184)

**Comment by PsiACE** [comment]
For catalogs, we can keep the implementation and extract the abstract design to common_catalogs. at the same time, the datasouse::database module should be moved out.

**Comment by BohuTANG** [comment]
As winter said above, due to the query context depends, it's not easy to do, I set the task priority to low.

**Comment by Xuanwo** [comment]
Duplicated to #6180
