### ISSUE TITLE
feat: add query query_hash and query_parameterized_hash to query log

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#15524]
**Summary**

To categorize and examine similar queries in the query history, utilize a hash of the query text. 

## query_hash

The `query_hash` ensures that repeated queries with variations only in white space or comments share the same hash. 
For example:
```sql
SELECT * FROM t1 WHERE name = 'jim'
SELECT *  FROM t1 WHERE name  = 'jim'
```
Both have the same `query_hash`.

## query_parameterized_hash

The `query_parameterized_hash` is used when literals are part of a comparison predicate using operators such as `=`, `!=`, `>=`, or `<=`. Despite different literals, these queries share the same hash:
```sql
SELECT * FROM t1 WHERE name = 'data'
SELECT * FROM t1 WHERE name = 'bend'
```

Ref: https://docs.snowflake.com/en/user-guide/query-hash

**Comment by BohuTANG** [comment]
Can we get the two hash during the SQL parsing phase? @sundy-li

**Comment by sundy-li** [comment]
see: 

```
let key = gen_result_cache_key(self.formatted_ast.as_ref().unwrap()); 
```
