### ISSUE TITLE
[feature] projection alias with filter expression

### ISSUE THREAD

**Issue by ygf11** [datafuselabs/databend#1553]
**Summary**

Following sql does not supported in datafuse, but supoported in clickhouse.
```
datafuse :) select a as id from test where id = 1;

SELECT a AS id
FROM test
WHERE id = 1

Query id: 6f468eac-2904-430b-96c1-ddac4c4f4be7


0 rows in set. Elapsed: 0.011 sec.

Received exception from server (version 2021.5.0):
Code: 6. DB::Exception: Received from 0.0.0.0:9001. DB:Exception. Unable to get field named "id". Valid fields: ["a"].
```

I trace the execution of this sql, find that `FileterTransform` directly use alias(Expression) to find the column in data source, then throw this exception.

#1390 need do some sql, like following:
`SELECT name AS Database FROM system.databases WHERE Database = 'ss' ORDER BY name`.

**Comment by zhang2014** [comment]
Maybe we should reconsider #574

CC: @leiysky @sundy-li @BohuTANG

**Comment by sundy-li** [comment]
> SELECT name AS Database FROM system.databases WHERE Database = 'ss' ORDER BY name.
Currently You can use `SELECT name AS Database FROM system.databases WHERE name = 'ss' ORDER BY name.` instead 

> it is allowed in ClickHouse and can be very useful
Yes, it's very useful though it's not standard and it also not works in MySQL, but I do prefer to add it.

**Comment by ygf11** [comment]
> Currently You can use SELECT name AS Database FROM system.databases WHERE name = 'ss' ORDER BY name. instead

@sundy-li  Yeah, you are right.

**Comment by leiysky** [comment]
The problem here is that in SQL semantic, aliases in `SELECT` clause is not visible in `WHERE` clause, since selection algebra will be applied before producing result set.

The more idiomatic way is using `table alias` to achieve this renaming:
```SQL
select id from test as t(id) where id = 1;
```



> Maybe we should reconsider #574.
> It is not an SQL standard (but it is allowed in ClickHouse and can be very useful)
> 
> CC: @leiysky @sundy-li @BohuTANG

Consider this case:
```
create table t (a int, b int);
insert into t values(1, 2);
select a as b from t where b = 2; 
```

ClickHouse will return empty:
```
leiysky-MS-7B89 :) create table t (a int, b int) engine = MergeTree() order by a;

CREATE TABLE t
(
    `a` int,
    `b` int
)
ENGINE = MergeTree
ORDER BY a

Query id: f7465fb8-d11e-45b6-be05-555d89551f31

Ok.

0 rows in set. Elapsed: 0.003 sec.

leiysky-MS-7B89 :) insert into t values(1, 2);

INSERT INTO t VALUES

Query id: 5b5b0a91-8731-49ee-ba33-2ee84e28a6f0

Ok.

1 rows in set. Elapsed: 0.002 sec. 

leiysky-MS-7B89 :) select a as b from t where b = 2;

SELECT a AS b
FROM t
WHERE b = 2

Query id: f2c9e547-4ec5-4178-80cc-071abd0e1a4e

Ok.

0 rows in set. Elapsed: 0.002 sec. 

```

While both MySQL and PostgreSQL will return result like:
```
leiysky=# create table t (a int, b int);
CREATE TABLE
leiysky=# insert into t values(1, 2);
INSERT 0 1
leiysky=# select a as b from t where b = 2;
 b 
---
 1
(1 row)
```

**Comment by zhang2014** [comment]
> The problem here is that in SQL semantic, aliases in SELECT clause is not visible in WHERE clause, since selection algebra will be applied before producing result set.
> 
> The more idiomatic way is using table alias to achieve this renaming:

Table alias is a great method, but let's consider several actual scenarios: NYC taxi (51 columns), OnTime (109 columns), GitHub event (19 columns and dozens of event structures). We may not be able to provide a complete list of columns. and this problem may not be limited to where, for example: ` SELECT a as B FROM table GROUP BY B HAVING B > 0 order by B`

by the way, MySQL only supports `select id from subquery as table(id)`


> Consider this case:

For this example, ClickHouse may better understand the needs of users ?
by the way, this query will throw error (no ambiguity): ` SELECT a AS b, b FROM t WHERE b = 2`

**Comment by leiysky** [comment]
@zhang2014 Well, it's better to explicitly specify the result set, or you can use a subquery instead to do the alias😂.

Anyway, IMHO, we should follow the standard.

**Comment by BohuTANG** [comment]
Snowflake also performance like mysql/pg does:
```
create table t (a int, b int);
insert into t values(1, 2);
select a as b from t where b = 2; 
```

Result is:
```
B
---
 1
```

I think `ease to use` is the first, standards second, this alias is helpful in many cases, we should revisit the issue, cc @leiysky @xudong963

**Comment by xudong963** [comment]
```sql
postgres=# select * from t;
 a | b
---+---
 1 | 2
 2 | 3
(2 rows)

postgres=# select a as c from t where c = 2;
ERROR:  column "c" does not exist
LINE 1: select a as c from t where c = 2;
                                   ^
postgres=#
```

**Comment by xudong963** [comment]
> Snowflake also performance like mysql/pg does:
> 
> ```
> create table t (a int, b int);
> insert into t values(1, 2);
> select a as b from t where b = 2; 
> ```
> 
> Result is:
> 
> ```
> B
> ---
>  1
> ```

We also support the case, `where` uses `b` in table not alias in selection

**Comment by BohuTANG** [comment]
Resolved, let's Close.
