### ISSUE TITLE
bug:   to_yyyymmddhh has bug

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#15600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```
root@localhost:8000/default> SELECT
  to_yyyymmddhh('2023-11-12 09:38:18.165575');

SELECT
  to_yyyymmddhh('2023-11-12 09:38:18.165575')

-[ RECORD 1 ]-----------------------------------
to_yyyymmddhh('2023-11-12 09:38:18.165575'): 2023111200

1 row read in 0.007 sec. Processed 1 row, 1 B (136.63 rows/s, 136 B/s)
```
https://docs.databend.com/sql/sql-functions/datetime-functions/to-yyyymmddhh

It doesn't match the doc.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
Support arg as date/timestamp type. Default is date type.

You can use this:

```
SELECT   to_yyyymmddhh(to_timestamp('string'));
```

**Comment by TCeason** [comment]
Let's modify the doc.

**Comment by TCeason** [comment]
https://github.com/datafuselabs/databend-docs/pull/801
