### ISSUE TITLE
bug: `replace into` not work as expected 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#15655]
**Summary**

`replace into test on(c) select sum(c) as c from source group by v` not work as expected in multi-nodes deployment.

failed with err msg: ResponseError with 1104: assertion failed: self.fragment_exchanges.is_empty()

query node version:  [v1.2.495-nightly](https://github.com/datafuselabs/databend/releases/tag/v1.2.495-nightly)

how to reproduce:

~~~
create or replace table test (c int);
create or replace table source (c int, v string);


insert into source select number as c, number::string from numbers(100000);

replace into test on(c) select sum(c) as c from source group by v; 
~~~

**Comment by TCeason** [comment]
Before fix can try this sql:

replace into test(c) on(c) select sum(c) as c from source group by v;
