### ISSUE TITLE
feat: remove streaming upload?

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#15706]
**Summary**

it is only used to load *local* files to Databend. 
instead user can 
1. upload to stage and run `copy into table instead`.
2. if server runs locally only for test,  user can copy into table from `fs://`

cons compare with copy:

1.  slow because of only one ONE stream can be used, and can not ultilize cluster (unless user run multi post by himself)
2.  for parquet files, can not read the meta at file end until.
3.  it is a `insert`, so no tracking of file paths like in copy.

**Comment by BohuTANG** [comment]
Yes, but it would be better to introduce a settings like `enable_streaming_upload`, default is `false`.
