### ISSUE TITLE
bug: COPY INTO from compressed archive should ignore PAX metadata

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#15716]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.507-nightly

### What's Wrong?

When loading data via COPY INTO from compressed archive tar.gz in PAX format, the decompression should ignore metadata such as @PaxHeader instead of attempting to load and issuing errors such as this:
```
(databend_sqlalchemy.errors.Error) Code: None. APIError: ResponseError with 1006: invalid digit found in string while evaluating function `to_int32('././@PaxHeader0000000000000000000000000000003400000000000010212 xustar0028 mtime=1717411618.9266722')`
```

### How to Reproduce?

Create a tar.gz file of some CSV files, using PAX format (default format in Python 3.8+), then try to import using the COPY INTO statement similar to below.

```python
with tarfile.open('some_archive.tar.gz') as tar:
    for f in file_list:
        tar.add(f)
```

Ensure first column is Int/Decimal/Date to force the error.

```sql
COPY INTO "mydb"."mytable"
FROM (SELECT $1, $2, $3
FROM 'gcs://bucket/folder1/folder2/file1/'
CONNECTION = (CREDENTIAL = 'base64creds'))
PATTERN = '*.*'
FILE_FORMAT = (TYPE = CSV, RECORD_DELIMITER = '\n', FIELD_DELIMITER = ',', QUOTE = '"', ESCAPE = '', SKIP_HEADER = 0, COMPRESSION = AUTO )
FORCE = TRUE
```

**Comment by rad-pat** [comment]
Perhaps my issue is that Gzipped TAR archives are not supported?

**Comment by sundy-li** [comment]
> Perhaps my issue is that Gzipped TAR archives are not supported?

I think yes, tar contains multiple files, we only support gz compressed single file.

**Comment by rad-pat** [comment]
> I think yes, tar contains multiple files, we only support gz compressed single file.
OK, thanks, good to know

**Comment by rad-pat** [comment]
Closing, TAR archive not supported
