### ISSUE TITLE
bug: LATERAL VALUES ignores NULL values

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#15722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

datafuselabs/databend-query:v1.2.507-nightly

### What's Wrong?

When using Lateral values statement, NULL values are excluded from results. This is a follow-up from testing with fix for https://github.com/datafuselabs/databend/issues/15255

### How to Reproduce?

```sql

drop table if exists rates;	
create table rates(origin varchar, dest varchar, distance int, "r2023" decimal(38,10), "r2022" decimal(38,10), "r2021" decimal(38,10));
insert into rates values ('a', 'b', 500, 2023.12, 2022.23, 2021.34);
insert into rates values ('a', 'c', 500, 2023.11, null, null);

WITH source AS(
	SELECT origin, 
		dest,  
		distance, 
		"r2023", 
		"r2022",
		"r2021"
	FROM "rates"
)
SELECT r.origin, r.dest, r.rates, r.values
FROM (
	SELECT source.origin, 
		source.dest, 
		v.rates,
		v.values
	FROM source 
	JOIN LATERAL (
		VALUES 
			(source."distance", 'distance'), 
			(source."r2023", 'r2023'), 
			(source."r2022", 'r2022'),  
			(source."r2021", 'r2021')
	) AS v ("values", "rates") ON true
) AS r
```

Expected Results:
```
origin|dest|rates   |values |
------+----+--------+-------+
a     |b   |distance|  500.0|
a     |b   |r2023   |2023.12|
a     |b   |r2022   |2022.23|
a     |b   |r2021   |2021.34|
a     |c   |distance|  500.0|
a     |c   |r2023   |2023.11|
a     |c   |r2022   |   null|
a     |c   |r2021   |   null|
```

Actual Results:
```
origin|dest|rates   |values |
------+----+--------+-------+
a     |b   |distance|  500.0|
a     |b   |r2023   |2023.12|
a     |b   |r2022   |2022.23|
a     |b   |r2021   |2021.34|
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @b41sh

**Comment by Dousir9** [comment]
We need to support `is distinct from` for the correlated columns of Expression Scan.

**Comment by inviscid** [comment]
Just a friendly check-in on this task.  Is there an ETA on when a fix might be in place?

**Comment by Dousir9** [comment]
> Just a friendly check-in on this task. Is there an ETA on when a fix might be in place?

I'm working on it and it'll be done in 3 days.

**Comment by Dousir9** [comment]
@inviscid Done.

**Comment by rad-pat** [comment]
@Dousir9 please see https://github.com/datafuselabs/databend/issues/15886
