### ISSUE TITLE
bug: conflict resolve context:ModifiedSegmentExistsInLatest occurred when using replace into statement in jdbc for existing data

### ISSUE THREAD

**Issue by clearz32** [datafuselabs/databend#15824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1.2.530

### What's Wrong?

when executing replace into xxx on existing data in jdbc, following error is thrown:
Error executing query: SQL: replace into settlement_lite(`id`,`code`,`tenant_no`,`record_time`) on (id) values(?,?,?,?) Query failed: Optional[{"id":"b0c3c9a0-3fbd-4570-9c89-ae82097df510","session_id":"7dea72b5-574a-4458-9d53-e8c2e0ef2e67","node_id":"xqnvlJd9jCia3LSbv7ohI7","state":"Failed","session":{"database":"testdb","role":"public","settings":{},"txn_state":"AutoCommit","last_server_info":{"id":"xqnvlJd9jCia3LSbv7ohI7","start_time":"2024-06-18T09:22:29.680+08:00"},"last_query_ids":["b0c3c9a0-3fbd-4570-9c89-ae82097df510"]},"error":{"code":4001,"message":"conflict resolve context:ModifiedSegmentExistsInLatest(SnapshotChanges { appended_segments: [(\"13/19133/_sg/ce8796eb61514696b7af43512cc5b36d_v4.mpk\", 4)], replaced_segments: {0: (\"13/19133/_sg/60af105cd4ae4db083765e0136ad12f0_v4.mpk\", 4)}, removed_segment_indexes: [], merged_statistics: Statistics { row_count: 82000, block_count: 2, perfect_block_count: 0, uncompressed_byte_size: 3545679, compressed_byte_size: 1111083, index_size: 204580, col_stats: {1: ColumnStatistics { min: String(\"FJJGBM0000102021\"), max: String(\"ZRYWPZ202203040 \"), null_count: 0, in_memory_size: 2551429, distinct_of_values: None }, 3: ColumnStatistics { min: Date(18500), max: Date(19713), null_count: 378, in_memory_size: 338250, distinct_of_values: None }, 0: ColumnStatistics { min: Number(32_i32), max: Number(100416_i32), null_count: 0, in_memory_size: 328000, distinct_of_values: None }, 2: ColumnStatistics { min: Number(666666_i32), max: Number(666666_i32), null_count: 0, in_memory_size: 328000, distinct_of_values: None }}, cluster_stats: None }, removed_statistics: Statistics { row_count: 82000, block_count: 1, perfect_block_count: 0, uncompressed_byte_size: 3545671, compressed_byte_size: 1108266, index_size: 203326, col_stats: {1: ColumnStatistics { min: String(\"FJJGBM0000102021\"), max: String(\"ZRYWPZ202203040 \"), null_count: 0, in_memory_size: 2551421, distinct_of_values: None }, 3: ColumnStatistics { min: Date(18500), max: Date(19713), null_count: 378, in_memory_size: 338250, distinct_of_values: None }, 0: ColumnStatistics { min: Number(32_i32), max: Number(100416_i32), null_count: 0, in_memory_size: 328000, distinct_of_values: None }, 2: ColumnStatistics { min: Number(666666_i32), max: Number(666666_i32), null_count: 0, in_memory_size: 328000, distinct_of_values: None }}, cluster_stats: None } })","detail":""},"warnings":[],"has_result_set":true,"schema":[{"name":"id","type":"Int32"},{"name":"code","type":"Nullable(String)"},{"name":"tenant_no","type":"Int32"},{"name":"record_time","type":"Nullable(Date)"}],"data":[],"affect":null,"stats":{"scan_progress":{"rows":1000,"bytes":47936},"write_progress":{"rows":2000,"bytes":43242},"result_progress":{"rows":0,"bytes":0},"total_scan":{"rows":9587,"bytes":47936},"running_time_ms":201},"stats_uri":"/v1/query/b0c3c9a0-3fbd-4570-9c89-ae82097df510","final_uri":"/v1/query/b0c3c9a0-3fbd-4570-9c89-ae82097df510/final","next_uri":"/v1/query/b0c3c9a0-3fbd-4570-9c89-ae82097df510/final","kill_uri":"/v1/query/b0c3c9a0-3fbd-4570-9c89-ae82097df510/kill"}] cause: null
	at com.databend.jdbc.DatabendStatement.internalExecute(DatabendStatement.java:215) ~[databend-jdbc-0.2.7.jar:c65c22d-dirty]
	at com.databend.jdbc.DatabendPreparedStatement.executeBatchByAttachment(DatabendPreparedStatement.java:299) ~[databend-jdbc-0.2.7.jar:c65c22d-dirty]
	at com.databend.jdbc.DatabendPreparedStatement.executeBatch(DatabendPreparedStatement.java:384) ~[databend-jdbc-0.2.7.jar:c65c22d-dirty]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127) ~[HikariCP-5.1.0.jar:na]

### How to Reproduce?

1. create table settlement_lite(id int, code varchar(32), tenant_no varchar(32), record_time timestamp);
2. insert into the table with replace into sql statement in batch size 1000 for 10000 rowsj;
3. execute the batch replace into statement again

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
Did you have any null value inert?

**Comment by dantengsky** [comment]
@clearz32 

In your scenario, could "replace into settlement_lite ..." be executed concurrently? If it is executed concurrently, then the error you observed is expected.

**Comment by clearz32** [comment]
> Did you have any null value inert?

No null value. I carefully checked the source data.

**Comment by clearz32** [comment]
> @clearz32
> 
> In your scenario, could "replace into settlement_lite ..." be executed concurrently? If it is executed concurrently, then the error you observed is expected.

At first I indeed run it with multi tasks concurrently. During the issue investigation I turn to run it with only one thread and the error still occurred, even if I set batchsize to 1, and optimize the table, restart databend.
I'll try to write a simple java program so that you can reproduce it easily.

**Comment by clearz32** [comment]
> Did you have any null value inert?

From the reported error message there are indeed some null values for data fields. But the id is unique and no null values since it's primary key in the source database.

**Comment by zcl32** [comment]
> @clearz32
> 
> In your scenario, could "replace into settlement_lite ..." be executed concurrently? If it is executed concurrently, then the error you observed is expected.

This issue is confirmed that it's caused by executing tasks concurrently. 
We run the data ingesting tasks in async mode and caused this issue although we limit only one thread.  The issue disappeared after we remove the async annotation.

Now we just wonder how it is triggered since we did not update the same row.
