### ISSUE TITLE
bug: alter database rename/alter table rename make stream not work

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#15830]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

error: APIError: ResponseError with 2733: Cannot get base table 'db01'.'tb01' from stream 'db01'.'s1_tb01', cause: Unknown database 'db01'

```
create database db01;
use db01;
create table tb01(c1 int);
create stream s1_tb01 on table tb01;

alter database db01 rename to db01_bak;

use db01_bak;
select * from s1_tb01; -> database not found db01

show streams;

SHOW streams

-[ RECORD 1 ]-----------------------------------
Streams_in_db01_bak: s1_tb01
           table_on: db01.tb01
               mode: append_only



```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dantengsky** [comment]
fixed by https://github.com/datafuselabs/databend/pull/15843
