### ISSUE TITLE
Bug: prefer table names defined by CTE

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#15845]
**Summary**

For the case, the last query has cte named source, ideally, the query `SELECT * FROM source` should use the table of cte, but it uses the table `source` defined before.

```sql
create table source(a int);
insert into source values(1);
select * from source;

select * from  (WITH source AS (select 1 as e) SELECT * FROM source) A,   (WITH source AS (select 2 as e) SELECT * FROM source) B;
```

**Comment by Vasanth-96** [comment]
@xudong963  can i work on this issue?

**Comment by Vasanth-96** [comment]
@BohuTANG i'm new to this code base if possbile can you help me with the start or some idea about the files i should look into.

**Comment by BohuTANG** [comment]
@Vasanth-96
Hi, this guide is helpful https://docs.databend.com/guides/community/contributor/good-pr

**Comment by xudong963** [comment]
You can read the file: https://github.com/datafuselabs/databend/blob/main/src/query/sql/src/planner/binder/bind_table_reference/bind_table.rs#L36.

**Comment by xudong963** [comment]
The issue has been solved by https://github.com/datafuselabs/databend/pull/15941
