### ISSUE TITLE
Feature: Implement Support for External Dictionaries (OSPP)

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#15901]
**Summary**

- [x] Writing an RFC for the implementation of External Dictionaries https://github.com/datafuselabs/databend-docs/pull/996
- [x] Support parse create/drop/show dictionary stmt.
- [x] Support dictionary meta api.
- [x] Support common functions, such as accessing data in dictionaries via the `dict_get` function.
- [x] Support `Redis` as data sources and implement related DDL.
- [x] Support `MySQL` as data sources and implement related DDL.

Mentor @b41sh

**Comment by Winnie-Hong0927** [comment]
Hello!!(*^▽^*)

**Comment by b41sh** [comment]
@Winnie-Hong0927 Congratulations. We've done all tasks.

**Comment by BohuTANG** [comment]
@b41sh Can we add an new external dictonary: PostgreSQL? Someone from the slack only want to do this in Databend: `CREATE TABLE FROM ... <postgresql tables>` ?
