### ISSUE TITLE
CI Configuration for AWS Credentials

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1590]
**Summary**

In PR 

- #1442

Unit test for aws s3 are supposing env vars `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` exist.

- Do we already have some configuration mechanism to safely config these parameters in CI?
- Or any suggestions of correctly/safely configuring aws s3 credentials ?

NOTE: This is NOT an urgent requirement

**Comment by dantengsky** [comment]
> It would be better after the issue: #1420
> And we can use a mock s3 server for test?
> Such as https://github.com/datenlord/s3-server

Thanks! did not know that, I will try it

**Comment by ZhiHanZ** [comment]
https://rohanverma.net/blog/2021/02/09/minio-github-actions/ seems fine, in TPC benchmark, I think we could also use local disk to mock on object storage for affordable CI

**Comment by dantengsky** [comment]
@ZhiHanZ 

Thanks, I will take a look at it as well.

**Comment by dantengsky** [comment]
As suggested by @ZhiHanZ, minio is being used in stateful tests. issue being closed
