### ISSUE TITLE
Feature:  support create user and alter user  option   MUST_CHANGE_PASSWORD = TRUE 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#15956]
**Summary**

create user |alter user need user login first change password.

The user password was expired login, first must change the password.

> https://docs.snowflake.com/en/sql-reference/sql/create-user

**Comment by TCeason** [comment]
If User create a password policy , all option has a default value. But it maybe not reasonable 

Because maybe I just want to set password expire time but it'll limit the password length

**Comment by TCeason** [comment]
I think better to wait this pr merged https://github.com/datafuselabs/databend/issues/15961 cc @b41sh
