### ISSUE TITLE
bug: copy into can't use session variables in SQL Script Engine 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#16057]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```
EXECUTE IMMEDIATE
$$
BEGIN
let batch := 1;
copy into t01 from @~/t01/ pattern='.*[.]parquet' file_format=(type=parquet) purge=true max_files= :batch;
END;
$$;
```

error: APIError: ResponseError with 1005: error:
  --> SQL:3:100
  |
1 | BEGIN
2 | let batch := 1;
3 | copy into t01 from @~/t01/ pattern='.*[.]parquet' file_format=(type=parquet) purge=true max_files= :batch;
  |                                                                                                    ^ unexpected `:`, expecting `END`, <LiteralInteger>, <MySQLLiteralHex>, or <PGLiteralHex>

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Ok, so it's by design, we will not support variables to replace non-expr param.
