### ISSUE TITLE
bug: strange behaviour with regexp statements/cte

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#16074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.571-nightly-a76267466a

### What's Wrong?

Depending on the order of results, derived years may or may not report null, It should report the same regardless of the order

### How to Reproduce?

I'm attempting to write something to parse an interval string, but the query yields different/incorrect results depending on the order
```
WITH interval_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS interval_str 
  UNION ALL 
  SELECT '2 hours 10 minutes 5 seconds' AS interval_str 
  UNION ALL 
  SELECT '4:05:06' AS interval_str
)

SELECT
  interval_str
  , CAST(NULLIF(regexp_replace(regexp_substr(interval_str, '(-?\\d+)\\s*y'), '\\D', ''), '') AS INT) AS years
FROM interval_data
 ORDER BY interval_str desc; -- fails
-- ORDER BY interval_str; -- works
```
When I run this, sometimes it will correctly parse the years for the first example as 1, or it sometimes reports null. This seems to depend on the order of the results and can be changed by altering the order BY. 

Incorrect:
```
interval_str                |years|
----------------------------+-----+
4:05:06                     |     |
2 hours 10 minutes 5 seconds|     |
1 y 2 mo 3 d 04:05:06.789   |     |
```

Correct:
```
interval_str                |years|
----------------------------+-----+
1 y 2 mo 3 d 04:05:06.789   |    1|
2 hours 10 minutes 5 seconds|     |
4:05:06                     |     |
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
I can't reproduce in my local (main branch)

**Comment by rad-pat** [comment]
OK, thanks for trying, I'll pull the latest nightly, try my full SQL and report back.

**Comment by rad-pat** [comment]
This is still happening for me at v1.2.574-nightly-1e49403c2a with this query
```
WITH interval_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS interval_str 
  UNION ALL 
  SELECT '2 hours 10 minutes 5 seconds' AS interval_str 
  UNION ALL 
  SELECT '4:05:06' AS interval_str
)

SELECT
  interval_str
  , CAST(NULLIF(regexp_replace(regexp_substr(interval_str, '(-?\\d+)\\s*y'), '\\D', ''), '') AS INT) AS years
FROM interval_data
ORDER BY interval_str desc;

interval_str                |years|
----------------------------+-----+
4:05:06                     |     |
2 hours 10 minutes 5 seconds|     |
1 y 2 mo 3 d 04:05:06.789   |     |
```

**Comment by BohuTANG** [comment]
What's the client are you using?

On Databend Cloud with Databend Query v1.2.572-nightly-4700b417e5(rust-1.78.0-nightly-2024-07-17T22:11:05.245657006Z):
<img width="969" alt="image" src="https://github.com/user-attachments/assets/5bc3cb96-3461-4622-a421-c901fe2cf9b3">

**Comment by rad-pat** [comment]
I'm using DBeaver with JDBC driver

**Comment by BohuTANG** [comment]
Can you try it with bendsql?  https://docs.databend.com/guides/sql-clients/bendsql/

**Comment by rad-pat** [comment]
It does indeed work with bendsql. I'm not sure where to log this anomaly then, JDBC?
