### ISSUE TITLE
Return json null for nullable values in http api response data

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#16111]
cc @sundy-li 

It seems https://github.com/datafuselabs/databend/issues/15960 should be reverted? cc @youngsofun 

## Server

- [x] https://github.com/datafuselabs/databend/pull/16120

## Clients

- [x] bendsql: https://github.com/datafuselabs/bendsql/pull/465
- [x] databend-go: https://github.com/datafuselabs/databend-go/pull/133

**Comment by youngsofun** [comment]
@everpcpc no need to revert，the old JsonBlock only use json::Value::String, null is output as "NULL" like output format, change it to StringBlock is more clear.

the problem is  https://github.com/datafuselabs/databend/issues/16076.

**Comment by hantmac** [comment]
databend-jdbc no need to modify because the `data`  context defined as an `object`. 
https://github.com/datafuselabs/databend-jdbc/blob/main/databend-client/src/main/java/com/databend/client/QueryResults.java#L48
