### ISSUE TITLE
bug: substr does not evaluate

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#16150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.583-nightly

### What's Wrong?

substr reports cannot evaluate due to incorrect types

### How to Reproduce?

```
WITH string_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
)
select SUBSTRING(some_str, 0, length(some_str) - 8) as thing
from string_data
```
```
SQL Error: Error executing query: SQL: WITH string_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
)
select SUBSTRING(some_str, 0, length(some_str) - 8) as thing
from string_data Query failed: QueryErrors{code=1065, message=error: 
  --> SQL:4:8
  |
1 | WITH string_data AS (
2 |   SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
3 | )
4 | select SUBSTRING(some_str, 0, length(some_str) - 8) as thing
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no function matches signature `substr(String, UInt8, Int64)`, you might need to add explicit type casts.

candidate functions:
  substr(String, Int64, UInt64) :: String                      : unable to unify `Int64` with `UInt64`
  substr(String NULL, Int64 NULL, UInt64 NULL) :: String NULL  : unable to unify `Int64` with `UInt64`

} cause: null
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rad-pat** [comment]
It looks like I have the start parameter wrong, should be 1, but still fails
```
WITH string_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
)
select SUBSTRING(some_str, 1, length(some_str) - 8) as thing
from string_data
```
SQL Error: Error executing query: SQL: WITH string_data AS (
  SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
)
select SUBSTRING(some_str, 1, length(some_str) - 8) as thing
from string_data Query failed: QueryErrors{code=1065, message=error: 
  --> SQL:4:8
  |
1 | WITH string_data AS (
2 |   SELECT '1 y 2 mo 3 d 04:05:06.789' AS some_str 
3 | )
4 | select SUBSTRING(some_str, 1, length(some_str) - 8) as thing
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no function matches signature `substr(String, UInt8, Int64)`, you might need to add explicit type casts.

candidate functions:
  substr(String, Int64, UInt64) :: String                      : unable to unify `Int64` with `UInt64`
  substr(String NULL, Int64 NULL, UInt64 NULL) :: String NULL  : unable to unify `Int64` with `UInt64`

} cause: null
```

```

**Comment by rad-pat** [comment]
The signature of these functions should not need to be so prescriptive. Presumably this applies to many other functions too that should also be checked?

**Comment by sundy-li** [comment]
`length(some_str) - 8` may be negative., but  `substring` don't accept negative num as the third arg.

It's better to use `(length(some_str) - 8)::UInt64`

**Comment by rad-pat** [comment]
The usage of substring is from an end user, they are not going to know to write `::UInt64`. If we have to wrap every database function with casts to ensure the params are correct, that is surely too much for a client application?

**Comment by sundy-li** [comment]
Now datatype uint64 can auto-cast to datatype int64, but int64 can't auto-cast into uint64.

The function's sig only accepts uint64 datatype now. 

Solutions:

1. change the sig into int64 datatype, but it may lead extra cast for uint64 arg.  
2. keep two sigs which cover both int64 and uint64 , the codes may be redundant




 We are considering a better cast rule which
