### ISSUE TITLE
[security] consider to use axum server for tls reloading

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1618]
**Summary**
https://github.com/programatik29/axum-server enhances TLS configurations for axum server and provide a way for TLS reloading which is desired(because we do not want user to restart query or stores when new TLS certificates updated).
Once the library provide full support TLS(CA, SNI etc), we could consider migration

**Comment by Xuanwo** [comment]
We are using poem now, this issue is out-of-date, let's closing.
