### ISSUE TITLE
Problem deploying databend cluster

### ISSUE THREAD

**Issue by javiercj93** [datafuselabs/databend#16209]
I am trying to deploy a databend cluster in k8s. and I have the following:

```
echo "check if my service is running and run commands ";
if [[ $POD_NAME =~ (.*)-([0-9]+)$ ]]
then
  ID=${BASH_REMATCH[2]}
  NAME=${BASH_REMATCH[1]}
  echo "ID: $ID" "NAME : $NAME"
  case ${BASH_REMATCH[2]} in
  0)
    echo "initialize leader node";
    exec /databend-meta --id ${ID} --config-id ${ID} \
        --single \
        --raft-advertise-host "${POD_NAME}.databend-meta.${POD_NAMESPACE}" \
        --grpc-api-advertise-host "${POD_NAME}.databend-meta.${POD_NAMESPACE}" \
        --config-file /etc/databend/meta.yaml
    ;;
  *)
    echo "initialize follower node";
    exec /databend-meta --id ${ID} --config-id ${ID} \
        --join "${NAME}-0.databend-meta.${POD_NAMESPACE}:28004" \
        --raft-advertise-host "${POD_NAME}.databend-meta.${POD_NAMESPACE}" \
        --grpc-api-advertise-host "${POD_NAME}.databend-meta.${POD_NAMESPACE}" \
        --config-file /etc/databend/meta.yaml
    ;;
  esac
else
  echo pod name $POD_NAME is not valid && exit 1
fi
```

So I am expecting each node of the meta cluster to advertise itself with `${POD_NAME}.databend-meta.${POD_NAMESPACE}`.

```
2024-08-07T17:19:50.044546Z  WARN openraft::replication: mod.rs:259 error replication to target=0 error=Unreachable node: tonic::transport::error::Error: transport error source: error trying to connect: dns error: failed to lookup address information: Name or service not known source: dns error: failed to lookup address information: Name or service not known source: failed to lookup address information: Name or service not known while: make_client target: 0, addr: http://databend-meta-0.databend-meta.databend-meta.svc.cluster.local:28004
```

Why is it still trying to find other members under `.svc.cluster.local` when it should be just `http://databend-meta-0.databend-meta.databend-meta:28004`

Basically, question would be why it keeps adding the suffix `svc.cluster.local`? 

I am using `datafuselabs/databend-meta:v1.2.530`

Thanks in advance

**Comment by sundy-li** [comment]
cc @drmingdrmer

**Comment by drmingdrmer** [comment]
There is not `svc.cluster.local` in our code. Can you find `svc.cluster.local` in your configuration or something else?

**Comment by drmingdrmer** [comment]
> It ended up being a misconfiguration on my side, I had a wrong selector and the pods were not receiving the right dns configuration and then they defaulted to `svc.cluster.local` suffix
> 
> Apologies for the confusion and thanks for taking a look, appreciate your help!

Glad to hear that you have this issue addressed!
