### ISSUE TITLE
bug: SQL Query Unexpectedly Executes Without Errors

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#16257]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

## Test Preparation
create table t011(c1 varchar);
create table t01(name varchar);

## Case 1
select name from t01 where name in (select name from t011);  
> This SQL is expected to produce an error , but it runs  without any error message.  

## Case 2

select name from t011 ; -> error
root@localhost:8000/default> select name from t011 ;
error: APIError: ResponseError with 1065: error:
  --> SQL:1:8
  |
1 | select name from t011
  |        ^^^^ column name doesn't exist

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
Case 1 's behavior is ok because it's a correlated subquery.

Pg, duckdb, etc allow the behavior all.
