### ISSUE TITLE
Sharing test failure

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#16284]
**Summary**

```
Error: APIError: ResponseError with 1063: Permission denied: privilege [Select] is required on 'share_catalog'.'provider_db'.'v' for user 'owner'@'%' with roles [public,r_0002]
```

https://github.com/datafuselabs/databend/actions/runs/10454363303/job/28948964761

**Comment by BohuTANG** [comment]
cc @TCeason

**Comment by TCeason** [comment]
I test on local, and find the err first occurs in pr https://github.com/datafuselabs/databend/pull/16218
