### ISSUE TITLE
Feature: Enable runtime adjustment of attached table metadata refresh timeout

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#16292]
**Summary**

Currently, the timeout for refreshing attached table metadata is hardcoded, which lacks flexibility. 

https://github.com/datafuselabs/databend/blob/6703714bb705bbbd0d36f98929b405d0b840b008/src/query/storages/factory/src/storage_factory.rs#L182-L185

We need a new setting that allows users to adjust the timeout value at runtime.

**Comment by wubx** [comment]
After  pr:  https://github.com/datafuselabs/databend/pull/16276, This problem is gone.
