### ISSUE TITLE
bug: COPY INTO <location> does not support tables that need quoting

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend#16294]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.618-nightly

### What's Wrong?

Trying to COPY INTO gcs from table with dashes in name gives error. Works fine for table with no dashes

### How to Reproduce?

```sql
CREATE table t1 (c1 int null);
CREATE table "t-2" (c1 int null);

select * from default.t1;

COPY INTO 'gcs://projects/tables/t1'
CONNECTION = (
	CREDENTIAL = '<snip>'
)
FROM default.t1
FILE_FORMAT = (TYPE = PARQUET);

select * from default."t-2";

COPY INTO 'gcs://projects/tables/t-2'
CONNECTION = (
	CREDENTIAL = '<snip>'
)
FROM default."t-2"
FILE_FORMAT = (TYPE = PARQUET);
```
```
SQL:1:32
  |
1 | SELECT * FROM default.default.t-2
  |                                ^ unexpected `-`, expecting `AT`, `CHANGES`, `WITH`, <Ident>, <LiteralString>, `IDENTIFIER`, `AS`, `PIVOT`, `UNPIVOT`, `SAMPLE`, `ROW`, `BLOCK`, `(`, `LiteralAtString`, `LATERAL`, `NATURAL`, `INNER`, `LEFT`, `SEMI`, `RIGHT`, `ANTI`, `FULL`, `CROSS`, `JOIN`, `ON`, `USING`, `,`, `WHERE`, `GROUP`, `HAVING`, `WINDOW`, `QUALIFY`, `UNION`, `EXCEPT`, `INTERSECT`, `FROM`, `SELECT`, `VALUES`, `ORDER`, `LIMIT`, `OFFSET`, `IGNORE_RESULT`, `FORMAT`, or `;`

} cause: null
```
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rad-pat** [comment]
I am able to run the following SQL, is this going to perform the same?
```sql
COPY INTO 'gcs://projects/tables/t-2'
CONNECTION = (
	CREDENTIAL = '<snip>'
)
FROM (SELECT * FROM default."t-2")
FILE_FORMAT = (TYPE = PARQUET);
```

**Comment by Dousir9** [comment]
> I am able to run the following SQL, is this going to perform the same?
> 
> ```sql
> COPY INTO 'gcs://projects/tables/t-2'
> CONNECTION = (
> 	CREDENTIAL = '<snip>'
> )
> FROM (SELECT * FROM default."t-2")
> FILE_FORMAT = (TYPE = PARQUET);
> ```

Yeah.
