### ISSUE TITLE
Database, Tables and Columns with UpperCase inside double quotes throws Error

### ISSUE THREAD

**Issue by Shanmugavel-J** [datafuselabs/databend#16381]
**Summary**

- I have edp database and it works when given in small case, If i provide any table column as well in uppercase it fails inside double quotes.
- Uppercase fails inside double quotes for the tables, databases & columns as far i had taken a look.
- Uppercase works fine if provided without double quotes.

Please find the below steps,

1. `CREATE DATABASE EDP` - This Works
2. `CREATE TABLE EDP.TEST(ID INT)` - This Works
3. `CREATE TABLE "EDP".TEST(ID INT)` 
```
SQL Error [1003]: Query failed (#e4e81c52-3951-4cff-9eab-0151029efd02): Unknown database 'EDP'
```

4. `SELECT * FROM EDP.TEST` - This Works
5. `SELECT "ID" FROM EDP.TEST`
```
SQL Error [1065]: Query failed (#7001e98c-1c7d-4173-9a59-b5d49d786ddf): error: 
  --> SQL:1:8
  |
1 | SELECT "ID" FROM EDP.TEST
  |        ^^^^ column ID doesn't exist, do you mean 'ID'?
```
6. `SELECT ID FROM EDP."TEST"`
```
SQL Error [1025]: Query failed (#34ab2039-c67c-40f6-bcc6-60b3906d0797): error: 
  --> SQL:1:16
  |
1 | SELECT ID FROM EDP."TEST"
  |                ^^^^^^^^^^ Unknown table "default".EDP."TEST" .
``` 

Snowflake considers everything uppercase when without double qoutes, when given inside `double quotes` it considers exact case, without double quotes it considers as Uppercase by default.

Is there any setting for the same?

**Comment by sundy-li** [comment]
@dosubot  is right. This is the default behavior which works like pg. And we will not change this.

You can use `set global unquoted_ident_case_sensitive = 1;` 

Please refer to the settings of 'unquoted_ident_case_sensitive' and 'quoted_ident_case_sensitive' in  https://docs.databend.com/sql/sql-reference/sql-identifiers#identifier-casing-rules

**Comment by Shanmugavel-J** [comment]
Okay, Thanks for the setting.
