### ISSUE TITLE
bug(query): behavior not like MySQL when set LIMIT 0

### ISSUE THREAD

**Issue by scbizu** [datafuselabs/databend#16399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.629-nightly

### What's Wrong?

As [MySQL documented](https://dev.mysql.com/doc/refman/8.4/en/limit-optimization.html):

> LIMIT 0 quickly returns an empty set. This can be useful for checking the validity of a query. It can also be employed to obtain the types of the result columns within applications that use a MySQL API that makes result set metadata available.

In databend , when set LIMIT 0 (or LIMIT 0,0) , the EXPLAIN (I paste it in Slack) said databend still performs full table data scan instead of only extracting the metadata . Some of client-drivers and SQL frameworks use this feature to check SQL validation and do extract the metadata to the ORM-based structure . With too much data scanning , the performance will step down in this case.

### How to Reproduce?

```
SELECT ... FROM  my_table WHERE 1=1 LIMIT 0,0;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
Maybe you need ignore result?

SELECT number FROM numbers(2) IGNORE_RESULT;

https://docs.databend.com/sql/sql-commands/query-syntax/query-select#ignore_result

**Comment by BohuTANG** [comment]
This is a optimizer issue? cc @xudong963

**Comment by BohuTANG** [comment]
> Maybe you need ignore result?
> 
> SELECT number FROM numbers(2) IGNORE_RESULT;
> 
> https://docs.databend.com/sql/sql-commands/query-syntax/query-select#ignore_result

No, this still scan full tables but ignore the result.

**Comment by sundy-li** [comment]
Join is blocking operator, so limit return early will not be reached. 

`limit 0` should be optimized it's input to be empty result scan.

**Comment by Dousir9** [comment]
> Join is blocking operator, so limit return early will not be reached.
> 
> `limit 0` should be optimized it's input to be empty result scan.

Yes.
