### ISSUE TITLE
[Refactor] improve dev_setup.sh

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1650]
**Summary**
dev_setup.sh scripts would install rust dependencies and tools to run datafuse tests.
here I think here should have 2 improvements:
1. each installation logic should be separated(current setup would confuse developers https://github.com/datafuselabs/datafuse/pull/1637#discussion_r697804376)
2. install all needed dependencies for unit tests and integration tests(such as python3, mysql-client) by default

**Comment by Xuanwo** [comment]
All tasks has been done. Closing.
