### ISSUE TITLE
[doc] Document the plugable catalog and datasource design

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1675]
**Summary**

After PR https://github.com/datafuselabs/datafuse/pull/1652, Datafuse Catalog and Datasource is plugable, we can add more datasource such as MySQL and etc.

Document them in https://datafuse.rs

**Comment by Xuanwo** [comment]
@BohuTANG Is this issue still valid? If so, please provide more information so that @soyeric128 can get involved in.

**Comment by BohuTANG** [comment]
It's invalid, let's close.
Thank you for reminding.
