### ISSUE TITLE
Support DataGrip

### ISSUE THREAD

**Issue by edokan** [datafuselabs/databend#1678]
**Support DataGrip**

DataGrip by IntelliJ is a wonderful Database IDE I use. However, it fails to connect to DataFuse using MySql throwing "CLIENT_SECURE_CONNECTION is required" error. As a workaround I used MariaDB connector using username and password root/root and it failed to connect since it tried to set sql_mode which Datafuse does not recognize. I set `jdbcCompliantTruncation` property to `false` to skip this step only to fail at following statement which IDE runs silently to learn about server

``` mysql
SHOW VARIABLES WHERE Variable_name in ('max_allowed_packet','system_time_zone','time_zone','auto_increment_increment')
```

I do not know how to skip this. Please make Datafuse work with DataGrip.

**Comment by TCeason** [comment]
I will test it.

**Comment by TCeason** [comment]
https://github.com/datafuselabs/databend/issues/4581

Now Databend can be queried on DBeaver.

**Comment by dufferzafar** [comment]
@TCeason Databend might be supporting DBeaver. But I'm still not able to connect via IntelliJ Datagrip.
