### ISSUE TITLE
data panel user and database on metastore api

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#1700]
In the datafuse(data panel), all the user is normal user, not tenant, we can get the databases by the user name(or id).
In the control panel, the tenant may have many users, it feels like a user management system, expressed in our metastore :)

_Originally posted by @BohuTANG in https://github.com/datafuselabs/datafuse/issues/1692#issuecomment-910403999_

**Comment by zhang2014** [comment]
Tenants are managed by Datafuse cli and users are managed by Datafuse query. Maybe they shouldn't be relevant?

**Comment by BohuTANG** [comment]
The api looks great for the data panel.
@zhang2014 tenant is the control panel, they are in different panel, so not actually related.

**Comment by zhang2014** [comment]
> The api looks great for the data panel.
> @zhang2014 tenant is the control panel, they are in different panel, so not actually related.

😂 I tried to move comment to https://github.com/datafuselabs/datafuse/issues/1692#issuecomment-911165136 (ignoring this). 

I understand.

**Comment by BohuTANG** [comment]
Hi @drmingdrmer ,
It looks that we still need a tenant prefix for the user, looks issue https://github.com/datafuselabs/datafuse/issues/1723

**Comment by drmingdrmer** [comment]
> It looks that we still need a tenant prefix for the user, looks issue #1723

You mean that meta-store stores `tenant, user, database, table` in a four-levels tree,
not that `<tenant>` is a string prefix of a `<username>` right?

**Comment by BohuTANG** [comment]
Hello @drmingdrmer ,
Not sure how metastore stores the <tenant, <users>> and <user, <databases>> two mapping(sorry if not using prefix), I think all is ok if we can get them from the user api, the requirements is mainly two api: get_users(tenant) and get_databases(user)

**Comment by zhang2014** [comment]
Maybe we need to save the following data in metastore:

- users_info
- catalog_info
- cluster_nodes_info
- metadata_root_info(index)?

Users use namespaces to uniquely identify datafuse query clusters, but different namespaces may access the same data (catalog_info, user, metadata_root_data). We may first need to define what tenants are and at what level resources are shared(uniquely identify datafuse query cluster or uniquely data?)

**Comment by BohuTANG** [comment]
@zhang2014 

`namespace` is only for constructing the cluster(compute resource), It has no binding relationship with the data.
`tenant` is binding the data resource, `tenant` has many users, each user has many databases, each databases have many tables, each table has many partition files.

For example, if a login user A(A is a control panel user, here we talked all is about data panel) has 3 clusters:
* C1: tenant:t1, namespace:n1, 3-nodes
* C2:tenant:t1, namespace:n2, 3-nodes
* C3:tenant:t3, namespace:n3, 3-nodes

C1 and C2 are sharing the same data resources, but not compute resources.

**Comment by zhang2014** [comment]
> namespace is only for constructing the compute resources(cluster), It has no binding relationship with the data, but it belongs to a tenant.
> tenant is binding the data resource, tenant has many users, each user has many databases, each databases have many tables, each table has many partition files.

Perfect. 

Consistent with my understanding. 
BTW: we still use the key/value level API to access metastore,  which hasn't changed, right?

**Comment by BohuTANG** [comment]
@zhang2014 
At that time we did not consider tenant and user when we designing the user api at common/management/user, I think now we can make some changes according to the requirements, this requirement query is more clear, let's design it.


@drmingdrmer 
I and @zhang2014 will design the common api first based on our management/user mod, then let's see how the underlying metastore should support(prefix api only).

Thanks all.

**Comment by BohuTANG** [comment]
@zhang2014 
This API should meet the namespace store/load needs:

```
pub trait NamespaceApi {
    // Create a new tenant's namespace.
    async fn add_namespace(&mut self, tenant: String, namespace: Namespace) -> Result<u64>;

    // Get the tenant's namespace.
    async fn get_namespace(
        &mut self,
        tenant: String,
        namespace_id: String,
        seq: Option<u64>,
    ) -> Result<SeqValue<Namespace>>;

    // Get the tenant's all namespaces.
    async fn get_all_namespaces(
        &mut self,
        tenant: String,
        seq: Option<u64>,
    ) -> Result<Vec<SeqValue<Namespace>>>;

    // Check tenant's namespace exists or not.
    async fn exists_namespace(
        &mut self,
        tenant: String,
        namespace_id: String,
        seq: Option<u64>,
    ) -> Result<bool>;

    // Update the tenant's namespace.
    async fn update_namespace(
        &mut self,
        tenant: String,
        namespace: Namespace,
        seq: Option<u64>,
    ) -> Result<Option<u64>>;

    // Drop the tenant's one namespace by id.
    async fn drop_namespace(
        &mut self,
        tenant: String,
        namespace_id: String,
        seq: Option<u64>,
    ) -> Result<()>;
}
```

https://github.com/datafuselabs/datafuse/pull/1727/files#diff-d4805c6e724d1ac7205c5e848906b3d8febac5b62fb02fc17df0dee4b3d3eb24

**Comment by drmingdrmer** [comment]
> BTW: we still use the key/value level API to access metastore, which hasn't changed, right?([#1700 (comment)](https://github.com/datafuselabs/datafuse/issues/1700#issuecomment-911103724) it confused me)

Personally I prefer using a type-specific APIs(without any rational reasons 🤔 ).
Accessing meta-data with pure kv api just reduces the meta-store complexity, thus neither way will bother me at all.

**Comment by BohuTANG** [comment]
> > BTW: we still use the key/value level API to access metastore, which hasn't changed, right?([#1700 (comment)](https://github.com/datafuselabs/datafuse/issues/1700#issuecomment-911103724) it confused me)
> 
> Personally I prefer using a type-specific APIs(without any rational reasons  ).
> Accessing meta-data with pure kv api just reduces the meta-store complexity, thus neither way will bother me at all.

Aha, this is how we do it and can construct our own table based on the metastore kv api, `management/user` and `management/namespace` something is a table like.
