### ISSUE TITLE
[feature] add user and password auth  for MySQL/ClickHouse handler

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1704]
**Summary**

1. MySQL  auth
2. ClickHouse auth

First we should get the user and password hash in the MySQL/ClickHouse server handler.

**Comment by ZhiHanZ** [comment]
I think after it is finished with end user TLS authentication, security part should be ready for alpha stage

**Comment by BohuTANG** [comment]
It seems like we need an API for InteractiveWorker like:
```
on_auth(socket, user, password_hash) -> Result<()>
```

CC: @zhang2014 @sundy-li

**Comment by zhang2014** [comment]
> It seems that we need an API for InteractiveWorker like:

Yes, we need add them to ClickHouse and MySQL InteractiveWorker

**Comment by sundy-li** [comment]
So  `Flight-service` needs auth too?

**Comment by BohuTANG** [comment]
> So `Flight-service` needs auth too?

The flight-service have the `handshake` method already, in the datafuse-store:
https://github.com/datafuselabs/datafuse/blob/master/store/src/api/rpc/flight_service.rs#L96

The flight between datafuse-query in a cluster can be controled by the control panel, such as VPC, it's in low priority.
