### ISSUE TITLE
[feature] system.user table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1723]
**Summary**

### Schema
Add system.user table to get the user information, table schema:

|  Column 	|  Type 	|   Description	|
|---	|---	|---	|
|  host 	|  String 	|   Host	|
|  user 	|   String	|  User accounts |
|  authentication_string 	|   String	|  Hashed password 	|
|   password_last_changed	|   Datatime	|   	|
|   auth_plugin	|   String	|  Auth type 	|
|   quotas	| String  	|   Quotas	|
|   privileges	| String  	|   Privileges	|

### Datasource

`system.user` datasource from `common/management/user`,  the data in the user table is obtained by querying by tenant identifier (tenant key) .

tenant key is from https://github.com/datafuselabs/datafuse/issues/1724
### Usage

For the user auth from the MySQL/ClickHouse client:
SELECT * FROM system.user WHERE host='xx' AND user = 'xx' AND authentication_string='xxxxx'

**Comment by jyz0309** [comment]
Can I try it? But maybe I need some time to finish it.😂
/assignme 
If this is a P0 issue. Just cancel my assign.

**Comment by BohuTANG** [comment]
> Can I try it? But maybe I need some time to finish it.😂
> If this is a P0 issue. Just cancel my assign.

Thank you for taking 👍 
I think we have enough time to do it because there are some changes that need on the auth side as well, such as https://github.com/datafuselabs/datafuse/issues/1704

**Comment by jyz0309** [comment]
It seems that we can only get the user and hashed pwd from
```
pub struct UserInfo {
    pub name: String,
    pub password_sha256: [u8; 32],
    pub salt_sha256: [u8; 32],
}
```
How to get others. Or I put those 2 fields into table first?

**Comment by BohuTANG** [comment]
This is not ready now, it still have many other tasks Todo: user store/getvin the query.
When it ready I will ack here.
Thank you

**Comment by jyz0309** [comment]
okay. Maybe we can add name and `password_sha256` in `system.users` first?

**Comment by BohuTANG** [comment]
> okay. Maybe we can add name and `password_sha256` in `system.users` first?

I think we can wait for @sundy-li  to do auth first to see what is needed https://github.com/datafuselabs/datafuse/issues/1704

**Comment by BohuTANG** [comment]
@jyz0309 
Hello, this issue is ready for launch again :)

**Comment by BohuTANG** [comment]
> It seems that the `UserInfo` only contain name and pwd and auth_type? Does the `user` table only display these 3 columns?
> 
> ```
> pub struct UserInfo {
>     pub name: String,
>     pub password: Vec<u8>,
>     pub auth_type: AuthType,
> }
> ```

That's right

**Comment by Xuanwo** [comment]
`system.users` table has been added. Let's close.
