### ISSUE TITLE
Add `explain ast` statement

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#1759]
**Summary**

Something like
```
pc :) explain ast select 3 +3 > 5 where 4 > 3 + 1;

EXPLAIN AST
SELECT (3 + 3) > 5
WHERE 4 > (3 + 1)

Query id: 2fbbf917-4d58-49e0-9e3a-ca5adfbb64dd

┌─explain────────────────────────────┐
│ SelectWithUnionQuery (children 1)  │
│  ExpressionList (children 1)       │
│   SelectQuery (children 2)         │
│    ExpressionList (children 1)     │
│     Function greater (children 1)  │
│      ExpressionList (children 2)   │
│       Function plus (children 1)   │
│        ExpressionList (children 2) │
│         Literal UInt64_3           │
│         Literal UInt64_3           │
│       Literal UInt64_5             │
│    Function greater (children 1)   │
│     ExpressionList (children 2)    │
│      Literal UInt64_4              │
│      Function plus (children 1)    │
│       ExpressionList (children 2)  │
│        Literal UInt64_3            │
│        Literal UInt64_1            │
└────────────────────────────────────┘

18 rows in set. Elapsed: 0.009 sec.
```

**Comment by jyz0309** [comment]
Seem that relate to #1511 ?

**Comment by sundy-li** [comment]
> Seem that relate to #1511 ?

Yes.

**Comment by CNLHC** [comment]
Are there anyone working on this issue?  I am interested in working on it.

**Comment by jyz0309** [comment]
@CNLHC It seems that you need to wait #1511 be done. You can ask @jackwener for this issue.

**Comment by jackwener** [comment]
> Are there anyone working on this issue? I am interested in working on it.

@CNLHC ,  Hi, #1511 block this progress of this issue. Are you interested in #1511 ? If you are willing to take it up, you can try. I'm sorry about block due to I can't finish it in time.

**Comment by BohuTANG** [comment]
@jackwener Thank you.

**Comment by jackwener** [comment]
Hi, @sundy-li .
I implement the `explain ast` according to `explain pipeline`.
But, I found that `test_local_pipeline_build` use the `PlanParser::create(ctx.clone()).build_from_sql` parse sql.
But there's a problem.
`build_from_sql()` parse sql and output node, because it call `sql_statement_to_plan` inside.

**Comment by jackwener** [comment]
Now, I need the `statement` after `explain ast` is held, because it's need to call `visit` function of `Statment`.

**Comment by sundy-li** [comment]
`build_from_sql ` seems not used anymore in the latest code.

You can call ` DfParser::parse_sql(query)` to parse into `df_statement`.

@leiysky  I think  `TransformerSqlparser` should address `df_statement` instead of  `sqlparser::ast::Statement` then we can transform into our own `Statement`.

**Comment by Xuanwo** [comment]
@leiysky @andylokandy Is this this still valid?

**Comment by leiysky** [comment]
> @leiysky @andylokandy Is this this still valid?

I think we can deprecate this now.
