### ISSUE TITLE
Create release channel on slack for changelog updates

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1761]
**Summary**
To let more people know about the development progress and API changes,  we should let more people know about api changes, release notes, and update notes(how to update from older version to newer version, which part in deployment should be modified etc)

**Comment by Xuanwo** [comment]
Creating a release channel can't address the questions raised in this issue.

- People who want to know about our releases and `watch` our releases. 
- API changes, release notes have been covered by our release workflow.
- how to update from older version to newer version should be covered by our docs.

In a word, no action is to be taken. Let's close.
