### ISSUE TITLE
[test] add MySQL driver intergration test

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1766]
**Summary**

Add Java/PHP/Go/Python driver intergration test.

**Comment by ZhiHanZ** [comment]
actually in previous operators I added golang mysql and clickhouse driver in integration tests and maybe we could reuse helm for rudimental deployment without operator and add those driver for integration tests?

**Comment by BohuTANG** [comment]
Added python driver intergration test.
