### ISSUE TITLE
[CI] add k8s based integration test on CI

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1773]
**Summary**
what needs to be tested:
1. deployment with mTLS support on k8s cluster
2. third party client (mysql, clickhouse, java, go, python etc) connectivity with datafuse cluster
3. DAL availability in cloud providers like S3

what do not needs to be tested in the integration test:
1. large cluster performance test(similar to perf test, it should be triggered by bot with member permission)

Some considerations to short CI time:
previously we do not run docker build CI in PR check because it tooks a lot of time, the root cause came from slow build time on docker based rust image(mitigated by previous PRs) and slow networking speed for docker image upload and download.
In k8s based test, I think we could do the following optimizations to decrease docker related costs:
1. prefer local image registry instead of public image registry to minimize networking cost
2. reuse built binaries during each CI and pack them as datafuse docker images
3. could refactor on current helm charts for this CI

**Comment by ZhiHanZ** [comment]
cc @PsiACE @drmingdrmer @BohuTANG  what do you think?

**Comment by BohuTANG** [comment]
This means we will run the tests on our hosted?

**Comment by ZhiHanZ** [comment]
> This means we will run the tests on our hosted?

it could be hosted on our runners especially for cluster mode deployment,  and for single instance deployment, we could use github hosted runner

**Comment by PsiACE** [comment]
I do agree, but I guess a cyclical test plan is probably sufficient for now.

**Comment by drmingdrmer** [comment]
> 3\. DAL availability in cloud providers like S3

We need to fake a s3 service in such a test right?

**Comment by ZhiHanZ** [comment]
> > 3. DAL availability in cloud providers like S3
> 
> We need to fake a s3 service in such a test right?

depends, we could open small scale cloud provided S3 service during integration test for better delivery guarantee
