### ISSUE TITLE
fuse table implementations

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1780]
**Summary**

- Data Ingestion
  - [x] #2193
  - [x] #2194
  - [x] #1781
  - [x] #1783
  - [x] #1785
    - [x] #2361
    - [x] #2383
- Data Scanning
  - [x] Integration with Indexing
     - [x] #1782
     - [x] #1801
     - [x] #2362
     - [x] "optimise" the min/max value if necessary (keep the size of values of boud reasonable, sacrifices some accuracy) 
  - [x] #1784
       Consider caching the following items
       - Table Snapshot
       - Table SegmentInfo
       - Parquet Meta Section
       - Column Data (of a block)
- Compact
  - [x] distributed insertion 
  - [x] #3121
  - [x] #3147
  - [x] #3144 
  - [x] #3176
  - [x] #2946
  - [x] fine-grained compaction
- misc
  - [x] tracings  
- Refactoring
  - [x] #2378 
- Testing

  - Unit tests
  - Integration Tests
    - [x] Local FileSystem
    - [x] Mock S3 Service (MinIO?)

**Comment by Xuanwo** [comment]
@dantengsky Most work on this tracking issue has been implemented. How about closing it and start a new one if needed?

**Comment by dantengsky** [comment]
> @dantengsky Most work on this tracking issue has been implemented. How about closing it and start a new one if needed?

let close it :)
