### ISSUE TITLE
Enable caching in  table data readers 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1784]

**Comment by Veeupup** [comment]
"cache" mentioned here is in memory or on disk(on query node SSD)?

**Comment by flaneur2020** [comment]
> "cache" mentioned here is in memory or on disk(on query node SSD)?

good question 🤔

**Comment by dantengsky** [comment]
> "cache" mentioned here is in memory or on disk(on query node SSD)?

ideally, there should be tiers of cache, (1) for hot data, like frequently accessed table metadata and blocks, they should be cached in memory, (2) for cold(relatively) data, which evicted from the hot tier, put them on disk (SSD of computing node).

but, we can go with the in-memory cache first and improve the cache layer step by step.
