### ISSUE TITLE
[feature] runningDifference function

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1787]
**Summary**

Calculates the difference between successive row values ​​in the data block.

Like a table `repo_stars`:
| date      | stars |
| ----------- | ----------- |
| 2021-09-10      | 1035       |
| 2021-09-09      | 1021        |
| 2021-09-08      | 1000        |

```
SELECT date, runningDifference(start) as delta FROM repo_stars
```
| date      | delta |
| ----------- | ----------- |
| 2021-09-10      | 14       |
| 2021-09-09      | 21        |
| 2021-09-08      | 0        |

**Comment by ygf11** [comment]
It seems runningDifference function should consider null value case, and the behavior in clickhouse looks like:
>1.  if row[i] is null, then the result is null.
>2.  if row[i] is not null, and row[i-1] is null, then the result is 0.

is this the expected logic?
