### ISSUE TITLE
Add database to dbdb.io

### ISSUE THREAD

**Issue by abraithwaite** [datafuselabs/databend#1818]
**Summary**

Not sure how databases get on this website, but it's a great resource for discovery of new databases like this one.

https://dbdb.io/

In particular, it highlights the design choices made for each particular database using standard terminology.

Looking forward to the progress on this DB!  Keep it up!

**Comment by wubx** [comment]
Thks.  I wrote an mail to dbdb.io to ask how to subbmit it.

**Comment by BohuTANG** [comment]
Done! https://dbdb.io/db/databend
