### ISSUE TITLE
[CI] remove unneeded CI file 

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#1824]
**Summary**
Currently this CI hangs during each PR https://github.com/datafuselabs/databend/blob/master/.github/workflows/performance-tests-standalone.yml which is not needed Since we have already adopted https://github.com/datafuselabs/databend/blob/master/.github/workflows/datafuse-performance-dispatch.yaml for performance benchmark(single machine)

**Comment by PsiACE** [comment]
I have disabled this workflow and will remove it later
