### ISSUE TITLE
[question] Distributed query execution

### ISSUE THREAD

**Issue by lideen999** [datafuselabs/databend#1856]
Make sure to check documentation https://databend.rs first. 
hi,大家好!为了更好的描述问题,所以用中文.
https://github.com/datafuselabs/databend/blob/master/query/src/pipelines/processors/processor_merge.rs#L63
1,对于pipeline的计算依赖调度, 对数据源查询,怎么去作parts,分片?
2,粗略的浏览了下代码, 是否对于数据源的拉取,都是在一个节点完成的呢?如果是,针对上千个小文件,通过单节点的线程并法,会不会有问题.
https://github.com/datafuselabs/databend/blob/master/query/src/datasources/database/remote/remote_table.rs#L73
3,数据源 _partitions 感觉都没有起作用

**Comment by zhang2014** [comment]
Current implementation(cluster mode):
1. In optimizer, we try use StagePlan to mark some PlanNode as distributed [ScattersOptimizer](https://github.com/datafuselabs/databend/blob/master/query/src/optimizers/optimizer_scatters.rs)
2. In interpreter,  we try use flight API to split these stages and submit them for execute [SelectInterpreter](https://github.com/datafuselabs/databend/blob/master/query/src/interpreters/interpreter_select.rs)(repartition for nodes)


> 1,对于pipeline的计算依赖调度, 对数据源查询,怎么去作parts,分片?
> 2,粗略的浏览了下代码, 是否对于数据源的拉取,都是在一个节点完成的呢?如果是,针对上千个小文件,通过单节点的线程并法,会不会有问题.

we will repartition by cluster nodes list.

https://github.com/datafuselabs/databend/blob/0f2b61e258d2ede21b6e781ae14aded76fc6ab85/query/src/interpreters/plan_scheduler.rs#L802-L813

**Comment by ives9638** [comment]
Thanks, i have seen it
