### ISSUE TITLE
New testing style  in Rust crate

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#1866]
**Summary**

Description for this feature.

Databend used Golang testing style currently,  but there is a more rustacean testing style of cargo, refer to https://matklad.github.io/2021/02/27/delete-cargo-integration-tests.html

**Comment by jorgecarleitao** [comment]
I moved all tests in `arrow2` to a separate location and it made it much faster to write new tests, as we do not need to re-compile the crate. It also made it clear when a certain API was only "public" within the module (and not to users of the crate). Highly recommend!

**Comment by PsiACE** [comment]
I prefer the Rust style.

**Comment by BohuTANG** [comment]
Thank you @jorgecarleitao , your information is important, Databend test is getting slower and will continue on.
@PsiACE It's time to start doing it, go Rust style.
