### ISSUE TITLE
[feature] Meta store auth

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1883]
**Summary**

Support auth for meta store.

**Comment by ariesdevil** [comment]
@youngsofun Is your works related to this issue?

**Comment by youngsofun** [comment]
@ariesdevil  my previous works on auth is user based.

**Comment by ariesdevil** [comment]
> @ariesdevil my previous works on auth is user based.

Got.

**Comment by ariesdevil** [comment]
We now have management-mode that uses query node access metasrv, so that metasrv no need exposed to users directly. This issue can be closed. cc @BohuTANG @drmingdrmer

**Comment by BohuTANG** [comment]
After a moment thinking, meta also need auth , databend-query management mode also have authorization when  connect to metasrv, re-open the issue:
https://github.com/datafuselabs/databend/blob/12f5b5804865dc732810321cd9b57a5c59fffad8/query/src/configs/config_meta.rs#L45

**Comment by BohuTANG** [comment]
This issue is stale, will open a new one, closed it.
