### ISSUE TITLE
Test not run?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#1884]
The spawned task may be dropped as soon as it is created.
And `srv.start()` blocks for ever.

https://github.com/datafuselabs/databend/blob/befe6a52b12071ba8f4074c451ca22501754ce3e/store/src/api/http_service_test.rs#L48-L62

**Comment by drmingdrmer** [comment]
Fix this after #1879 is done.

**Comment by drmingdrmer** [comment]
@sundy-li why close? Is there anything I missed?

**Comment by drmingdrmer** [comment]
The spawned task should block until client receives the `resp`.

**Comment by Xuanwo** [comment]
@drmingdrmer Are there any actions we can take on this issue?

**Comment by drmingdrmer** [comment]
`srv.start()` won't block any more.
