### ISSUE TITLE
DatabendStore README

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1888]
**Summary**
After PR https://github.com/datafuselabs/databend/pull/1879 , store README is no longer:
DatabendStore is a transactional metadata store service

It should be:
DatabendStore is a (distributed) file system store service.
For on-perm deployment, if we don't have cloud shared storage like S3, this Store can be used.

**Comment by drmingdrmer** [comment]
`˙∆˙` Thanks man!
