### ISSUE TITLE
Simplify local/remote switch in MetaStoreCatalog

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#1895]
If the local/remote mode switching is impl in `MetaBackend`, as described in #1894 , `MetaStoreCatalog` shouldn't bother to do it again.

https://github.com/datafuselabs/databend/blob/257698eae705165d5f2c9ec3f42670ce87dcf2d6/query/src/catalogs/impls/catalog/metastore_catalog.rs#L63-L74

**Comment by drmingdrmer** [comment]
@BohuTANG @dantengsky

**Comment by dantengsky** [comment]
agree :+1:

**Comment by drmingdrmer** [comment]
`EmbeddedMetaBackend` and `RemoteMeteStoreClient` can be merged into one struct `MetaSync` with different backend `MetaApi`.
- Thus this issue will be closed when #2284 is done
