### ISSUE TITLE
meta_service startup failure

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#1901]
**Summary**

```
Sep 21 09:21:34.321 ERROR common_tracing::panic_hook: panicked at 'open global sled::Db: Io(Other, "could not acquire database file lock")', metasrv/src/meta_service/raft_db.rs:61:30 panic.file="metasrv/src/meta_service/raft_db.rs" panic.line=61 panic.column=30
```

**Comment by drmingdrmer** [comment]
It seems there is another `metasrv` or `store` running. Killing them would solve this issue.

BTW, what did you do to have this error?

**Comment by zhang2014** [comment]
> BTW, what did you do to have this error?

This problem occurs when I execute `./scripts/deploy/databend-query-standalone.sh`

**Comment by Xuanwo** [comment]
Hi, any updates on this issue?

**Comment by drmingdrmer** [comment]
Does it happen recently? @zhang2014

**Comment by zhang2014** [comment]
Can't reproduce. let's close it.
