### ISSUE TITLE
Change the handler mock user to kv service

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1920]
**Summary**
For ClickHouse/MySQL handler auth, now we mock a user map, consider move them to the common/management/user api, get user from the kv service.

**Comment by BohuTANG** [comment]
Since the UserMgr  `new` is:
```
 pub fn new(kv_api: Arc<dyn KVApi>, tenant: &str) -> Self 
```

In the query, call it like:
```
fn session_new(config) -> Result<Session> {
   let kv_backend = here_prefered_a_function_with_the_config(it provides local or kvserice via the config)?;
   let user_mgr = UserMgr::new(kv_backend)
}
```

then we can test the session_new as:
```
[test]
fn test_session_new() -> Result<()> {
   let config = Config::default();
   let session = session_new(config)?;
   ...

  Ok(())
}
```

**Comment by dantengsky** [comment]
```
fn session_new(config:Config) -> Result<Session> {
   let kv_backend = here_prefered_a_function_with_the_config(it provides local or kvserice via the config)?;
   let user_mgr = UserMgr::new(kv_backend)
}
```

could be implemented as

```
async fn session_new(config: Config) -> Result<Session> {
    let kv_backend = StoreApiProvider::new(config.into())
        .try_get_kv_client()
        .await?;
    let user_mgr = UserMgr::new(kv_backend, "tid");
}
```

**Comment by BohuTANG** [comment]
Thank you.

`KVApiProvider` is better here?
```
async fn session_new(config: Config) -> Result<Session> {
    let kv_backend = KVApiProvider::new(config.into())
        .try_get_kv_client()
        .await?;
    let user_mgr = UserMgr::new(kv_backend, "tid");
}
```

**Comment by BohuTANG** [comment]
Have see the code, StoreApiProvider is for meta/kv and storage, the name is make sense, i will have a try.

**Comment by dantengsky** [comment]
roger.

but split StoreApiProivder into separated $Service$ApiProviders do make sense, since `store` is being refactored into serval services.

Let me consider this, I will fire a PR is necessary

**Comment by BohuTANG** [comment]
> roger.
> 
> but split StoreApiProivder into separated $Service$ApiProviders do make sense, since `store` is being refactored into serval services.
> 
> Let me consider this, I will fire a PR if necessary

Ok.
Btw, `async` -> `sync` is better here, session method all is sync and it is also called by the sync method.

**Comment by dantengsky** [comment]
> Btw, `async` -> `sync` is better here, session method all is sync and it is also called by the sync method.

roger, let me fix this

**Comment by dantengsky** [comment]
@BohuTANG Is `UserMgr` supposed to be used in a sync context as well?

**Comment by BohuTANG** [comment]
> @BohuTANG Is `UserMgr` supposed to be used in a sync context as well?

Yes

**Comment by dantengsky** [comment]
@BohuTANG  I am starting to add sync style methods for `UserMgr` and `NamespaceMgr`, should the async style methods be kept?

**Comment by BohuTANG** [comment]
please sync :)
