### ISSUE TITLE
 Enhencements of kv service API for meta operations

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1921]
**Summary**

As we are going to implement database meta data management by using kv service,  we need some enhancements of kv apis to express atomic batch (perhaps conditional) operations; like these:

https://github.com/datafuselabs/databend/blob/0c82e29f7c7584b1687103bd6a837504469efd0b/metasrv/src/raft/state_machine/sm.rs#L434-L468

any other suggestions (like organizing the metadata in a way that simple KV API can cover all the metadata management requirements) are also welcome

**Comment by dantengsky** [comment]
cc @drmingdrmer  @ariesdevil @BohuTANG

**Comment by dantengsky** [comment]
FYI:

https://etcd.io/docs/v3.3/learning/api/#transaction

https://redis.io/topics/transactions

**Comment by dantengsky** [comment]
and please re-considering  the signature of kv apis:

```
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
pub struct UpsertKVActionResult {
    /// prev is the value before upsert.
    pub prev: Option<SeqValue<KVValue>>,
    /// result is the value after upsert.
    pub result: Option<SeqValue<KVValue>>,
}
```
maybe it could be more user friendly, and network traffic economy

**Comment by drmingdrmer** [comment]
> FYI:
> 
> https://etcd.io/docs/v3.3/learning/api/#transaction
> 
> https://redis.io/topics/transactions

Nice!
If there are requirements for batch or transactional operation, these will be a good guide.

**Comment by drmingdrmer** [comment]
> and please re-considering the signature of kv apis:
> 
> ```
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq)]
> pub struct UpsertKVActionResult {
>     /// prev is the value before upsert.
>     pub prev: Option<SeqValue<KVValue>>,
>     /// result is the value after upsert.
>     pub result: Option<SeqValue<KVValue>>,
> }
> ```
> 
> maybe it could be more user friendly, and network traffic economy

Do you have any better ideas?

**Comment by dantengsky** [comment]
A reference

https://github.com/etcd-io/etcd/blob/release-2.3/etcdserver/etcdserverpb/rpc.proto

**Comment by dantengsky** [comment]
> Nice!
> If there are requirements for batch or transactional operation, these will be a good guide.

maybe we can start from the current implementation of database metadata management?

**Comment by BohuTANG** [comment]
Duplicated with https://github.com/datafuselabs/databend/issues/5064
