### ISSUE TITLE
Refactor and split databend store

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#1925]
**Summary**

Refactor and split current implementation of Databend Store for better support cloud-native deployment.

![databend store (1)](https://user-images.githubusercontent.com/7812909/134560994-f09a6164-8308-4060-b596-60bae8a0622b.png)
> Note: The components with the light blue background are stand-alone deployment units that provide services.

**Related Issues**
* [x] Split current implementation to KV service and Store(DFS) service.
* [x] Refactor `MetaBackend`.
    * [ ] Change `MetaBackend` from trait to struct. 
          #1894 
          #1924
    * [ ] Work with Catalog and KV service.
    * [ ] Distinguish local or remote KV service.
* [ ] ~~Implementation Store(DFS) service.~~
* [x] Consider deprecate dfs and remote table  https://github.com/datafuselabs/databend/issues/1994

Feel free to add sub-issue to those issue lists.

**Comment by ariesdevil** [comment]
cc @drmingdrmer @dantengsky @BohuTANG

**Comment by dantengsky** [comment]
added issue #1924 to Summary cc @ariesdevil

**Comment by drmingdrmer** [comment]
I'm introducing a crate `kvlocal` for local only kv storage. What bout renaming `metasrv` to `kvsrv`?

So, shall we rename `store` to `dfs`?

**Comment by BohuTANG** [comment]
> I'm introducing a crate `kvlocal` for local only kv storage. What bout renaming `metasrv` to `kvsrv`?
> 
> So, shall we rename `store` to `dfs`?

Make sense.

**Comment by dantengsky** [comment]
> I'm introducing a crate `kvlocal` for local only kv storage. What bout renaming `metasrv` to `kvsrv`?
> 
> So, shall we rename `store` to `dfs`?

could not agree more.

but a top level crate `kvlocal` seems not that neat, especially the `kvlocal` is mainly for unit/integration tests

**Comment by BohuTANG** [comment]
@dantengsky 
Actually.
Should we wrap the kvlocal behind a factory, and then move it from the top to one directory?

**Comment by dantengsky** [comment]
- `KVLocalStore` is behind `StoreApiProvider` now.
-  moving it to some sub dir/crate is preferred. I think @drmingdrmer  will find the proper place after/during the refactoring of store

**Comment by BohuTANG** [comment]
Add:
Consider deprecate dfs and remote table https://github.com/datafuselabs/databend/issues/1994

**Comment by BohuTANG** [comment]
This task should be closed, if there are some un-finished tasks, we can track them in other issues :)
Thank you all!
