### ISSUE TITLE
Consider replacing `metasrv` flight API with bare grpc?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#1927]
To access meta data(purely key-value API), it does not need to follow the arrow-flight protocol, which is designed for both meta data and stream data transfer.

**Comment by BohuTANG** [comment]
arrow flight is for data transfer.
For metasvr, grpc + timeout is ok(a big change).

**Comment by dantengsky** [comment]
make sense

**Comment by ariesdevil** [comment]
closed by #3606
