### ISSUE TITLE
crate raft-store may depend on common-dfs-api rather than the sdk

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#1967]
> > common-management has to indirectly depends on store-api-sdk because of one of its dependency.
> may i ask which one? I do not have a laptop at hand now

> > common-management has to indirectly depends on store-api-sdk because of one of its dependency.

find it,  it is `kvlocal`.  
`common-management` need not depend on `kvlocal` except for `dev-dependencies`, seems you are working on it.

`raft-store` seems to be able to migrate to depend on API only, let me try it

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/issues/1940#issuecomment-927023556_

**Comment by BohuTANG** [comment]
Let's clear the definition:
1. raft-store is?
2. dfs is?

If the DFS is on-perm deployment file system, the raft-store why depends it?
Confused here

**Comment by dantengsky** [comment]
I think it is a working-in-progress refactoring, after the dependency graph been migrated to a more reasonable shape, there will be further refactoring.  @drmingdrmer  may have the whole picture in mind

**Comment by dantengsky** [comment]
o, the dfs-api  is the former block transfer operations (for remote-table) in disguise, not the real DFS stuff.

**Comment by BohuTANG** [comment]
@dantengsky 
Got it.
At final, store is a DFS which may used by dal(other is s3/local and etc.) layer?

**Comment by dantengsky** [comment]
> common-dfs-api is the block transfer services in disguise, which should be migrated to real dfs client latter

@see https://github.com/datafuselabs/databend/pull/1952

**Comment by dantengsky** [comment]
> @dantengsky
> Got it.
> At final, store is a DFS which may used by dal(other is s3/local and etc.) layer?

yeah, I think so

**Comment by drmingdrmer** [comment]
`raft-store` impl the storage for raft. It is the underlying store of `kvsrv`(previously `metasrv`). It is moved out to a standalone crate because the **local-kv** depends on it too.

`raft-store` depends on the `KVApi`, which is previous part of store API. That's way `raft-store` depends on it.
This dependency will be soon replaced with some `xxx-api`, such as `kvapi`, `metaapi` etc such that `raft-store` wont depends on any **store** related crates.

**Comment by drmingdrmer** [comment]
> there will be further refactoring. @drmingdrmer may have the whole picture in mind

Sorry to say that but I do not have something like a picture.

I just try to find terms that no longer reflect its actual work, and rename it or else.
I do not know what next to do until finishing the one I'm working on.
