### ISSUE TITLE
[improvement] add socket address to authenticate api

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1984]
**Summary**

For ClickHouse/MySQL auth:
```
    fn authenticate(
        &self,
        auth_plugin: &str,
        username: &[u8],
        salt: &[u8],
        auth_data: &[u8],
    ) -> bool 
```
and 
```
fn authenticate(&self, user: &str, password: &[u8]) -> bool 
```

It would be better to add a client address here:
```
fn authenticate(&self, client_address:&str, .....
```
we can log the address if auth failed and check the auth is from remote or local in the server side.

**Comment by Veeupup** [comment]
I'm new to databend and I want to try this @BohuTANG

**Comment by BohuTANG** [comment]
Thank you @Veeupup
