### ISSUE TITLE
[improvement] user name escape

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1985]
**Summary**

Original comments by winter:
https://github.com/datafuselabs/databend/pull/1978#discussion_r717135608

**Comment by GrapeBaBa** [comment]
also I don't understand why username need this escape?

**Comment by GrapeBaBa** [comment]
@BohuTANG Is this issue still active?

**Comment by BohuTANG** [comment]
Thank you for ping.
It is done in https://github.com/datafuselabs/databend/pull/4363, closing
