### ISSUE TITLE
[improvement] add storage sub config group

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1987]
**Summary**

query/config group `store` change to:

```
[storage]
    default_storage = "dfs|disk|s3"

    [storage.dfs]
      store_address = "0.0.0.0:9191"
      store_username = "root"
      store_password = "root"

    [storage.disk]
      data_path = "/path/on/disk"

    [storage.s3]
      # Region for S3 storage
      region = "MY_AWS_REGION"

      # Access Key for S3 storage
      key = "MY_AWS_ACCESS_KEY_ID"

      # Secret Key for S3 storage
      secret = "MY_AWS_SECRET_ACCESS_KEY"

      # S3 Bucket to use for storage
      bucket = "MY_S3_BUCKET_NAME"
```

**Comment by BohuTANG** [comment]
cc @dantengsky @ZhiHanZ 

This `storage` config group for `dal` read/write with shared(local) storage.

**Comment by dantengsky** [comment]
roger

**Comment by ZhiHanZ** [comment]
I think default_storage could be renamed as current_storage, which means the storage plan query component will be used

**Comment by BohuTANG** [comment]
> I think default_storage could be renamed as current_storage, which means the storage plan query component will be used

Since we can only choose one storage type, so the default storage is the current storage.
