### ISSUE TITLE
[improvement] Consider deprecate dfs and remote table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#1994]
**Summary**

For the Alpha version, we prioritised support for Disk and S3 storage type.
There are still a few things that need to be addressed:
- [ ] To reduce the hassle, deprecate the dfs mod (we may consider adding it in a later version if we need)
- [ ] Remove `common/dfs-apis` 
- [ ] Deprecate `remote` mod and change to `fuse` table
- [ ] #1999
- [ ] Integrate `databend-kvsvr` as the meta backend for query integration test

**Comment by BohuTANG** [comment]
cc @dantengsky @drmingdrmer @ariesdevil

**Comment by dantengsky** [comment]
> Deprecate remote mod and change to fuse table
roger

**Comment by dantengsky** [comment]
I will disable UT/IT of RemoteTable first, so that, they will not block the refactoring of related services/components

**Comment by BohuTANG** [comment]
> I will disable UT/IT of RemoteTable first, so that, they will not block the refactoring of related services/components

I will have a try on it:
skip the remote stateless tests who prefix with `09_`

**Comment by BohuTANG** [comment]
Move to #2059
