### ISSUE TITLE
meta service refactor summary

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2030]
Goal: 
- impl meta api in `metasrv`, make it a complete meta data store service.
- `common/meta/local-store` which is a wrapper of raft-state-machine, should provide the same `MetaApi` and should be used directly as a local meta store.

### Cleanup API definition
  - [x] #2017 
  - [x] #2032
  - [x] #2039
  - [x] #2040
  - [x] #2182 
  - [x] #2184
  - [x] #2390
### Complete unit test:
  - [x] #2391
### Refactor State Machine
  - [x] #2202
### Add `MetaApi` support to StateMachine:
  - [x] #2028 
  - [x] #1919
  - [x] #2244
  - [x] #2246
  - [x] #2029
  - [x] #2508
  - [x] #2520
  - [x] #2523
### Upgrade `Catalog` to adapt the latest MetaApi impl:
  - [x] #1894 
  - [x] #2278
  - [x] #2304
  - [x] #2305
  - [x] #2310
  - [x] #2319
  - [x] #2321
  - [x] #2325
  - [x] #2326
  - [x] #2396
  - [x] #2392
  - [x] #2284
  - [x] #1895 
  - [x] #2591
### Refactor callers
  - [x] Rename `StoreClient` to `MetaClient`.
### Cleanup 
  - [x] #2016 
### Non critical tasks
  - [x] #2081 
  - [x] #2082 
  - [x] #1894 
  - [x] #2180 
  - [x] #1904 
  - [x] #2205
  - [x] #2364
  - [x] #2367
  - [x] #2031

**Comment by drmingdrmer** [comment]
@BohuTANG @ariesdevil @dantengsky

**Comment by drmingdrmer** [comment]
Closing.

- Other unfinished issues are moved to #2306

**Comment by BohuTANG** [comment]
Great job
Give a big :rocket:
