### ISSUE TITLE
`MetaBackend::get_table_by_id()` does not use `table_version` at all. Consider removing it.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2031]

**Comment by jyz0309** [comment]
It seem that `RemoteMeteStoreClient` still need table_version to get table info from cache:
```
fn get_table_by_id(
        &self,
        db_name: &str,
        table_id: MetaId,
        table_version: Option<MetaVersion>,
    ) -> Result<Arc<TableInfo>> {
        if let Some(ver) = table_version {
            let mut cached = self.table_meta_cache.lock();
            if let Some(meta) = cached.get(&(table_id, ver)) {
                return Ok(meta.clone());
            }
        }
```

**Comment by drmingdrmer** [comment]
You are right. It is a just a proposal not a decision yet.

I was proposing to remove it but it is the national day holiday thus I tried not to bother people right now.
Some investigation has to be made before making it a decision.

A first thought is that the `table_version` in `get_table_by_id` can be removed too.
But I need some related developers to confirm that.
