### ISSUE TITLE
Why does ReadDataSourcePlan need  `db` and `table` in it?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2041]
https://github.com/datafuselabs/databend/blob/3480c4467db391d1ac61b2d7a98951ce006c1640/common/planners/src/plan_read_datasource.rs#L30-L47

There are 2 usages:

https://github.com/datafuselabs/databend/blob/3480c4467db391d1ac61b2d7a98951ce006c1640/query/src/interpreters/plan_scheduler.rs#L783-L792

https://github.com/datafuselabs/databend/blob/3480c4467db391d1ac61b2d7a98951ce006c1640/query/src/optimizers/optimizer_scatters.rs#L282-L302

It seems internally we could just use `table_id` to identify a table without `db` and `table_name`.

**Comment by drmingdrmer** [comment]
@dantengsky

**Comment by BohuTANG** [comment]
If it is not used elsewhere, I think it is due to historical reasons for db and table still here.

**Comment by drmingdrmer** [comment]
- The one of the usages is: https://github.com/datafuselabs/databend/issues/2046
