### ISSUE TITLE
trait `Table` tries to do too much than it should do

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2051]
Trait `Table` defines two sets of jobs:
- What a table is,
- and how to operate the data in it, such as building a `ReadDataSourcePlan` from a table.

This results in the `table-plan` dependency cycle mentioned in
- #2046 

https://github.com/datafuselabs/databend/blob/3480c4467db391d1ac61b2d7a98951ce006c1640/query/src/catalogs/table.rs#L30-L83

A `plan` should know about the table from which it is built, e.g. the `what a table is` part. But a `plan` cares nothing about what else a table can do with its data.

A proposal is:
- Split trait `Table` into two trait:
- `Table`: defines `what  a table is`. A `plan` may have a reference to it if needed:
  ```
     fn name(&self) -> &str; 
     fn database(&self) -> &str; 
     fn engine(&self) -> &str; 
     fn as_any(&self) -> &dyn Any; 
     fn schema(&self) -> Result<DataSchemaRef>; 
     fn get_id(&self) -> MetaId; 
     fn is_local(&self) -> bool; 
  ```
- `TableExecutor`(maybe some better name): defines what a table can do, such as how to build a `ReadDataSourcePlan` from a `Table`:
  ```
     // Get the read source plan. 
     fn read_plan( 
         &self, 
         ctx: DatabendQueryContextRef, 
         push_downs: Option<Extras>, 
         partition_num_hint: Option<usize>, 
     ) -> Result<ReadDataSourcePlan>; 
  
     // Read block data from the underling. 
     async fn read( 
         &self, 
         ctx: DatabendQueryContextRef, 
         source_plan: &ReadDataSourcePlan, 
     ) -> Result<SendableDataBlockStream>; 
  
     // temporary added, pls feel free to rm it 
     async fn append_data( 
         &self, 
         _ctx: DatabendQueryContextRef, 
         _insert_plan: InsertIntoPlan, 
     ) -> Result<()> { 
         Err(ErrorCode::UnImplement(format!( 
             "append data for local table {} is not implemented", 
             self.name() 
         ))) 
     } 
  
     async fn truncate( 
         &self, 
         _ctx: DatabendQueryContextRef, 
         _truncate_plan: TruncateTablePlan, 
     ) -> Result<()> { 
         Err(ErrorCode::UnImplement(format!( 
             "truncate for local table {} is not implemented", 
             self.name() 
         ))) 
     } 
  ```

**Comment by drmingdrmer** [comment]
@BohuTANG @dantengsky

**Comment by BohuTANG** [comment]
Sounds good.

**Comment by leiysky** [comment]
Sounds good to me. I prefer to have a structure like `TableMeta` to describe metadata of a table, and another structure like `TableHandle` to help generate executor for `TableScan`.

**Comment by BohuTANG** [comment]
> Sounds good to me. I prefer to have a structure like `TableMeta` to describe metadata of a table, and another structure like `TableHandle` to help generate executor for `TableScan`.

Ok, will consider them when refactoring.

**Comment by sundy-li** [comment]
About `ReadDataSourcePlan`, I don't think it's good to make Table aware of `LogicalPlan`.

`SelectInterepter` can build the  `ReadDataSourcePlan` from table's properties/method.

**Comment by drmingdrmer** [comment]
> About `ReadDataSourcePlan`, I don't think it's good to make Table aware of `LogicalPlan`.
> 
> `SelectInterepter` can build the `ReadDataSourcePlan` from table's properties/methods.

@sundy-li 
Agreed. I'm trying to extract `plan` related concept off trait `Table`, so that a table does not need to know about a `plan`.
And **maybe** let a `plan` know of the table from which it is built.

Sounds good? 🤔

**Comment by leiysky** [comment]
@drmingdrmer IMO, the relationship between components should look like:
- `Plan` can depend on `TableMeta`
- `Processor` can depend on `TableHandle`
- `TableHandle` can be built with `TableMeta`

And the function of current `ReadSourcePlan` can be covered by `TableMeta`.

**Comment by drmingdrmer** [comment]
> @drmingdrmer IMO, the relationship between components should look like:
> 
> * `Plan` can depend on `TableMeta`
> * `Processor` can depend on `TableHandle`
> * `TableHandle` can be built with `TableMeta`
> 
> And the function of current `ReadSourcePlan` can be covered by `TableMeta`.

Sounds accordant with my understanding too!

- `TableMeta`: what a table is
- `TableHandle`: what a table can do
- `Processor`: when to do sth with a table.
- `xxxPlan`:  the output of the above steps.

**Comment by dantengsky** [comment]
can not agree more.

btw, the current `TableMeta` should be removed, or replaced by `TableInfo` IMO.

**Comment by drmingdrmer** [comment]
Did not find an elegant way to separate `data` and `operation`. 😞 Give up.
