### ISSUE TITLE
Extract a trait `TrySpawn` out of `DatabendQueryContext`, so that a crate that needs the runtime in `query` to spawn tasks does not need to depends on `query`.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2061]

**Comment by BohuTANG** [comment]
I think @zhang2014 may have some suggestions here :)

**Comment by drmingdrmer** [comment]
The modification would be like this:
https://github.com/drmingdrmer/databend/commit/860331fa84476bc83c7e0975204e1c6aac86220b
