### ISSUE TITLE
Missing runtime dependencies in Docker

### ISSUE THREAD

**Issue by nntp4** [datafuselabs/databend#2063]
**Summary**
The image should contain all runtime dependencies. 

**How to reproduce**
 OS: macOS BigSur 11.6
```sh
cd databend/
make docker
docker run -d  datafuselabs/databend-query:latest --name databend-query
```

**Error message and/or stacktrace**

> /databend-query: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
> /bootstrap.sh: line 13:     8 Illegal instruction     /databend-dfs --single true &> /tmp/databend-dfs.log

**Comment by BohuTANG** [comment]
Please try `make setup` first?

**Comment by nntp4** [comment]
> Please try `make setup` first?

But it contains redundant dependencies which make the Docker image very large.
