### ISSUE TITLE
Consider removing stat report in `NumbersTable::read_plan`?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2082]
NumbersTable is the only one that reports statistics when building a `ReadDataSourcePlan`.
This makes the trait `Table` has to reference `DatabendQueryContext` in its arguments.

Can line 128 and 129  be removed? Or move these stat-reporting to other phase?

https://github.com/datafuselabs/databend/blob/aa8705fe225f5de5871937acc04dff7a70f294ce/query/src/datasources/table_func/numbers_table.rs#L118-L129

**Comment by sundy-li** [comment]
Fixed by #2218
