### ISSUE TITLE
Improve ParquetStream

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#209]
**Summary**
We already have an asynchronous producer-consumer model, see here:
https://github.com/datafuselabs/datafuse/blob/a6f918f369492f2c94ab13bd3b0c99c1f6271d5e/fusequery/query/src/processors/processor_merge.rs#L53-L71

So there is no need stream_parquet(using tokio::wrapper::ReceiverStream instead):
https://github.com/datafuselabs/datafuse/blob/a6f918f369492f2c94ab13bd3b0c99c1f6271d5e/fusequery/query/src/datastreams/stream_parquet.rs

Cc @sundy-li

**Comment by sundy-li** [comment]
Yes， I noticed that yesterday, I'll create a patch to fix that.

**Comment by Xuanwo** [comment]
@sundy-li Are you still working on this?

**Comment by sundy-li** [comment]
Sorry, this is fixed, we don't have ParquetStream anymore, it's in Source trait named `source_parquet`.
