### ISSUE TITLE
`Table::read()` does not need a `ReadDataSourcePlan`.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2107]
Seems like the trait method `Table::read(&self, ctx: DatabendQueryContextRef, source_plan: &ReadDataSourcePlan)` does not need `source_plan`:

- Before `Table::read()` is called, `source_plan.parts` has been pushed into `DatabendQueryContextRef.try_set_partitions()`
- The table information in `source_plan` can be found in the table itself.
- The only field that is actually used is `source_plan.push_down`(for now), such as in `TracingTable`:

https://github.com/datafuselabs/databend/blob/62b168ee8d4606aafb809df64913129949683faa/query/src/datasources/database/system/tracing_table.rs#L111-L130

- It seems like the under-developing `FuseTable` does not need other fields in `source_plan`  either.

So... what about remove argument `source_plan` and only leave something necessary such as `push_down` etc.
This way `trait Table` will no longer depends on crate `common/planner`.

**Comment by dantengsky** [comment]
It may depend on the way of fixing issue #2051, roughly, during executing the `read` method of `Table` or `TableHandle`, it should know/be able to access:
- the table metadata, at least `table_id` and `table_version`
- the partitions being requested (via ctx or plan)
- the push_downs

**Comment by dantengsky** [comment]
> Then Table::read() will be called several times(meanwhile, max_theads() times). And only one of the Table::read() will successfully acquire a part from partition_queue. Others should just return.

I am afraid that `Table::read()` will not be called several times (for one query node). `read` returns a stream, which will dequeue partition identifiers from ctx, and fetch/generate data blocks accordingly. numbers_table and numbers_stream may be a good references.

**Comment by BohuTANG** [comment]
> > Let say, during `read_plan`, 3 partitions are detected by the table, later, the scheduler decides to split the task of fetching those parts into 3 sub-tasks, and assigns 1 task for each query node. the query node needs to tell the table, which partition is being requested, or the table should try to de-queue some identities of partitions from ctx (the counterpart of `DatabendQueryContextRef.try_set_partitions()` you mentioned ).
> 
> AFAIK, the first step is on the leader node(the one received a SQL), it split the `ReadDataSourcePlan` into 3, each of them has only one part in it(part-a in plan-a, part-b in plan-b...).
> 
> Then these 3 `ReadDataSourcePlan`s are sent to 3 nodes node-a,node-b,node-c.
> 
> Before executing the plan, the `PipelineBuilder` on each node copies `ReadDataSourcePlan.parts` into query context, i.e. by calling `DatabendQueryContext.try_set_partitions()`. At this step, every node has 1 part in its `DatabendQueryContext.partition_queue`, `node-a.partition_queue = [part-a]`, `node-b.partition_queue = [part-b]`...
> 
> Then `Table::read()` will be called several times(meanwhile, `max_theads()` times). And only one of the `Table::read()` will successfully acquire a `part` from `partition_queue`. Others should just return.
> 
> Thus `Table::read()` only needs the `DatabendQueryContext` to retrieve parts. The `source_plan` is actually not used, except `source_plan.push_down`.
> 
> Hoping I missed nothing 🤔 @BohuTANG @dantengsky

You are right for normal query, for join or subquery I think @zhang2014 may interested in it since he was the planner scheduler designer

**Comment by drmingdrmer** [comment]
> I am afraid that `Table::read()` will not be called several times (for one query node). `read` returns a stream, which will dequeue partition identifiers from ctx, and fetch/generate data blocks accordingly. numbers_table and numbers_stream may be a good references.

You are right! Thank you bro! @dantengsky 

The number of SourceTransform is limited to the number of parts: 
https://github.com/datafuselabs/databend/blob/b188fde5eeaaa31ed1506f74a5afd5a14d802905/query/src/pipelines/processors/pipeline_builder.rs#L298-L312

Except this false statement, is there other concern about that a `Table::read()` does not need a whole `ReadDataSourcePlan`?

**Comment by dantengsky** [comment]
> is there other concern about that a Table::read() does not need a whole ReadDataSourcePlan?

nothing else from me. but it is more about planning/schedule which I have only quite limited knowledge about

**Comment by drmingdrmer** [comment]
> > is there other concern about that a Table::read() does not need a whole ReadDataSourcePlan?
> 
> nothing else from me. but it is more about planning/schedule which I have only quite limited knowledge about

Me too. A lot to learn and to do. 😆
