### ISSUE TITLE
[Perf tool] cross compiled  perf-tool does not work in test infra

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#2119]
**Summary**
issue looks like `cannot open /lib/ld-linux-aarch64.so.1 ` happened when running official perf-tool image`datafuselabs/perf-tool:latest` on test-infra

**How to reproduce**

**Error message and/or stacktrace**

**Additional context**
Currently whole infra runs in AMD64 system, use normal build instead of cross-compile should be fine

**Comment by Xuanwo** [comment]
Do we still use `perf-tool`?

**Comment by PsiACE** [comment]
> Do we still use `perf-tool`?

We can close it off, our perf is supported by databend cloud and databend-perf.
