### ISSUE TITLE
Performance status error

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#2137]
**Summary**

http://test-1306375239.cos.accelerate.myqcloud.com/report/2114/11b2696870d2f1b4afd52f0a0d0406347136f75b/13ebbe56-1bd3-42e0-9fdc-16204b52accd/performance.html

***Expect***:
When current_score > ref_score, this status should is faster, otherwise it is slow.

CC: @ZhiHanZ

**Comment by sundy-li** [comment]
> `When current_score > ref_score, this status should is faster, otherwise it is slow.`

This is incorrect,  `current_score(before_score)` means the score of the latest releaser, `ref_score(after_score)` means the score of current pr, maybe we should uniform the names.

**Comment by Xuanwo** [comment]
Is this issue still valid?

**Comment by sundy-li** [comment]
Migrated into databend-perf
