### ISSUE TITLE
[Feature] CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password'

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2160]
**Summary**

Support:
```
CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password'
```
Tasks:
1. sql parser supports the syntax
2. create user planner
3. create user interpreter
4. Write user info to meta store

**Comment by sundy-li** [comment]
@GrapeBaBa 

```
CREATE USER 'newuser'@'localhost' IDENTIFIED [WITH auth_plugin] BY 'password'  
```
Full create user statement refer to https://dev.mysql.com/doc/refman/8.0/en/create-user.html

**Comment by GrapeBaBa** [comment]
I found there are two similar sql parser code in package `sql`, which is currently used? @sundy-li

**Comment by sundy-li** [comment]
Currently, https://github.com/datafuselabs/databend/blob/main/query/src/sql/sql_parser.rs#L87 is used.

**Comment by GrapeBaBa** [comment]
@BohuTANG For Drop/Alter User, can you create separate issues?
