### ISSUE TITLE
[Functions] Digest functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2162]
**Summary**

- [ ] MD5
- [ ] SHA1
- [ ] SHA256

**Comment by PsiACE** [comment]
MD5 has been cryptographically broken and considered insecure.

**Comment by BohuTANG** [comment]
> MD5 has been cryptographically broken and considered insecure.

These encryption functions will be used by the user not databend itself need.
Such as `SELECT md5(name) as hex from xx`
