### ISSUE TITLE
Lift the meta api to apis

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2164]
**Summary**

Now, meta have two api trait:
KvApi and MetaApi, and they are in kv and flight,consider lifting them to one.

**Comment by dantengsky** [comment]
`common/management` does not depend on MetaApi though

**Comment by BohuTANG** [comment]
> `common/management` does not depend on MetaApi though

Ok, we will have a undeps check patch for all the crates, issues https://github.com/datafuselabs/databend/issues/2106
