### ISSUE TITLE
Consider decouple databend-query from async-raft

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#2170]
**Summary**

Technically, `databend-query` need not to depend on `async-raft `. 
but it is not a big problem now, we may fix this later.  

async-raft v0.6.1 (https://github.com/datafuse-extras/async-raft?tag=v0.6.2-alpha.14#8cd24ba0)
├── common-meta-raft-store v0.1.0 (../workspace/fuse-query/common/meta/raft-store)
│   ├── common-meta-local-store v0.1.0 (../workspace/fuse-query/common/meta/local-store)
│   │   └── databend-query v0.1.0 (../workspace/fuse-query/query)

**Comment by BohuTANG** [comment]
cc @PsiACE may interested in this

**Comment by dantengsky** [comment]
I tried to decouple them for a while, it seems feasible but needs a "medium" refactoring, maybe it would be trivial for @drmingdrmer
