### ISSUE TITLE
`trait Database` does not need to provide `get_table_by_id`, if `table_id` are globally unique.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2180]
If `(table_id, table_version)` is just enough to find a table, as `MetaApi` and `Catalog` allows to get a `Table` by just `(table_id, table_version)`, then a `Database` does not need to provide `get_table_by_id()`:

`trait Database`:
https://github.com/datafuselabs/databend/blob/d951c3d351e81bc6d38460e010adbaf468da31a7/query/src/catalogs/database.rs#L35-L39

`trait MetaApi`:
https://github.com/datafuselabs/databend/blob/d951c3d351e81bc6d38460e010adbaf468da31a7/common/meta/api/src/meta_api.rs#L52-L57

`trait Catalog`:
https://github.com/datafuselabs/databend/blob/d951c3d351e81bc6d38460e010adbaf468da31a7/query/src/catalogs/catalog.rs#L52-L56

BTW, the `globally unique table_id` is just a way to embed some `db_id` into `table_id`.

**Comment by drmingdrmer** [comment]
@BohuTANG @dantengsky

**Comment by BohuTANG** [comment]
Looks good.
@dantengsky What do you think?

**Comment by dantengsky** [comment]
looks good to me. 

I've not thought about it thoroughly, intuitionally,  there **might** be a .. "handful" of tasks there to remove it from `Database`.

If we could drop the concept of `database engine`,  things might be easier (for this case only).  for reference only @drmingdrmer
