### ISSUE TITLE
[Deserialization] flatten configs cannot be deserialized by serde

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#2226]
**Summary**

Query use flatten for configuration management, however, serde itself would not compile it and would NOT throw error information

**Additional context**
to relieve this issue, current approach is to parse each flattened areas separately which works for now, we should track on upstream for complete fixes or write down some encoding and decoding methods to avoid this issue
https://github.com/nox/serde_urlencoded/issues/33

**Comment by Xuanwo** [comment]
Already addressed by newly designed config format.
