### ISSUE TITLE
Consider the version compatibility of data for the meta service

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2273]
How do we ensure the compatibility between difference version when databend-meta upgrade?

**Comment by BohuTANG** [comment]
cc @drmingdrmer

**Comment by BohuTANG** [comment]
cc @dantengsky 
We also face this problem when our storage and index formats change.
For example, how the old format can work properly if the new version format changed?
I think their solution is similar to the meta.

**Comment by drmingdrmer** [comment]
🤔 At sled level, export old data and feed them into the new version:
```
[dependencies]
sled = "0.32"
old_sled = { version = "0.31", package = "sled" }
```

```rust
let old = old_sled::open("my_old_db")?;
let new = sled::open("my_new_db")?;

let export = old.export();
new.import(export);
```

🤔 At the business level, we could adopt a similar way:  export data with an old version `meta-store` impl and import it with a new version one.

🤔 TODO
- We need a solid way to save the version somewhere in `_meta`.
- When new incompatible version is publishing, an old version of `meta-store` should be kept as an additional sub-crate(or publish old version on crates.io). E.g.:
  When v0.3 is released, the dir layout maybe look like:
  ```
  databend/common/meta-store-0.1
  databend/common/meta-store-0.2
  databend/common/meta-store // current version
  ```

**Comment by PsiACE** [comment]
> old_sled = { version = "0.31", package = "sled" }

We need a tool to make migrations between Sled versions or different compression settings.

**Comment by drmingdrmer** [comment]
> Does it mean in this way we need a config of the `prefix` path and need to make other path a relative path? 🤔 

If I understood it correctly, there is a concern that some user may want to have **meta** and **log** in different paths mounted on different devices.

**Comment by BohuTANG** [comment]
Sorry for the confusion comments.
For an example as you said above store them in multiple paths:
If the metasrv version now is 0.5, we upgrade it to 0.6 and the store format has some changes, so how could we handle the v0.5 and v0.6 meta datas on the disk?
From my understanding, the v0.6 version only hanlde his version, can not hanlde data format in the v0.5 path.

**Comment by drmingdrmer** [comment]
> Sorry for the confusion comments. For an example as you said above store them in multiple paths: If the metasrv version now is 0.5, we upgrade it to 0.6 and the store format has some changes, so how could we handle the v0.5 and v0.6 meta datas on the disk? From my understanding, the v0.6 version only hanlde his version, can not hanlde data format in the v0.5 path.

If there is a 0.5 installed already and one wants to upgrade to 0.6:
```
/etc/databend/0.5.0/meta/...
```

When the new 0.6 binary starts, it should be able to detect if there are older version data saved on disk.
In this case, it found there is data from `0.5` in the dir `/etc/databend/0.5.0/`.
And the 0.6 binary should migrate meta data in the `0.5` format to `0.6` format, then continue on the start up process.

**Comment by BohuTANG** [comment]
> > Sorry for the confusion comments. For an example as you said above store them in multiple paths: If the metasrv version now is 0.5, we upgrade it to 0.6 and the store format has some changes, so how could we handle the v0.5 and v0.6 meta datas on the disk? From my understanding, the v0.6 version only hanlde his version, can not hanlde data format in the v0.5 path.
> 
> If there is a 0.5 installed already and one wants to upgrade to 0.6:
> 
> ```
> /etc/databend/0.5.0/meta/...
> ```
> 
> When the new 0.6 binary starts, it should be able to detect if there are older version data saved on disk. In this case, it found there is data from `0.5` in the dir `/etc/databend/0.5.0/`. And the 0.6 binary should migrate meta data in the `0.5` format to `0.6` format, then continue on the start up process.

Good idea, mvcc!

**Comment by BohuTANG** [comment]
> * backward-compatiable,

I second add a version to 'backward-compatiable', since the huge datas can not converted by time.

**Comment by Xuanwo** [comment]
Already implemented, closing.
