### ISSUE TITLE
Move method `create_table()` and `drop_table()` from Database to Catalog

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2326]

**Comment by drmingdrmer** [comment]
There will be some other relatively small and obvious issues related to `catalog` and `meta-data` management.
If you are still interested then, you'll be in the first class cabin.

**Comment by yufan022** [comment]
@drmingdrmer Oh, what a pity, if there is a similar task you are welcome to assign me, I think this is a good opportunity to understand the structure of the code
