### ISSUE TITLE
Building a cluster plan at the first place?

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2380]
The `ReadDataSourcePlan` is built twice.
The second time building it, it just run `read_plan()` again with different `partition_num_hint`.

**Is it possible at the first place, to just check `table.is_local()` and build a plan ready for cluster?**

First time to build the plan:
https://github.com/datafuselabs/databend/blob/e77bfe3e9f43de2a6a29a7456d61f069ce5cbe2b/query/src/sql/plan_parser.rs#L803-L818

Rebuild plan to scatter data part to several nodes:
https://github.com/datafuselabs/databend/blob/e77bfe3e9f43de2a6a29a7456d61f069ce5cbe2b/query/src/interpreters/plan_scheduler.rs#L785-L802
https://github.com/datafuselabs/databend/blob/e77bfe3e9f43de2a6a29a7456d61f069ce5cbe2b/query/src/interpreters/plan_scheduler.rs#L848-L858

**Comment by zhang2014** [comment]
Now we can get the push down through the statement analyzer analysis layer. I will begin to work for this task.
