### ISSUE TITLE
Support create table as/like query

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2457]
**Summary**

```
mysql> create table test_b like test_a ;
ERROR 1105 (HY000): Code: 1002, displayText = sql parser error: Expected end of statement, found: like.
mysql>  create table (number UInt64) as select number from numbers(100);
ERROR 1105 (HY000): Code: 1002, displayText = sql parser error: Expected identifier, found: (.
```

Refer: https://dev.mysql.com/doc/refman/8.0/en/create-table-like.html

**Comment by sundy-li** [comment]
@junli1026  seems `create table as ` is not finished, would u want to continue?

**Comment by junli1026** [comment]
> @junli1026 seems `create table as ` is not finished, would u want to continue?

Sure. If I understand correctly, differently from "CREATE LIKE" , the query 'CREATE TABLE t1  as SELECT * FROM t2' also copy data from t2 to t1. It does more than creating table. 

Surely, will keep working on that.
