### ISSUE TITLE
Checklist proposal: Nightly v0.6

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2525]
**Summary**
Please add `v0.6` label to your issue if you want to release it in 6 weeks, release name: v0.6-nightly, get in the train now :hand: 

# Checklist

**Stable checklist**
- [x] #2561 
- [x] HTTP handler API works with all the queries which databend support(DONE)
- [x] #1434 

**Experimental checklist**

- [x] #2162 
- [x] #2627
- [x] #2679
- [x] #2868
- [ ] #2526
- [ ] #2894 

**Meta Service checklist**
- [x] #2667
- [ ] #2422 

**Testing checklist**
- [x] #1866  

# What Databend nightly v0.6 can do?
- You can experience with `ontime` test suite with fuse table engine(local/s3)

# Archive releases
- [x] #2257

# Reference
[What's Databend release channels?](https://github.com/datafuselabs/databend/issues/2559)
Nightly v0.6 is part of our [Roadmap 2021](https://github.com/datafuselabs/databend/issues/746)
Community website: [https://databend.rs](https://databend.rs/)

# Thank

Thank you everyone for all the issues and PRs that will be resulted in this release.

**Comment by flaneur2020** [comment]
do we need include the plan of databend-operator in this checklist? it's in a stand-alone repository

**Comment by ZhiHanZ** [comment]
> do we need include the plan of databend-operator in this checklist? it's in a stand-alone repository

I think so, we should add at least two things:
1. refactor databend-operator for meta service and DAL storage
2. add test infra to test databend-operator on different cloud providers( AWS, GKE etc)

it would be nice to have the following experimental features:
1. monitoring demo(add prometheus to databend_cluster)
2. Autoscaling with keda
3. multi-cluster scheduling with admiralty or karmada etc.

**Comment by ZhiHanZ** [comment]
Plus, we should also support bendctl integration with operator for basic logging, debugging and visualization supports

**Comment by ZhiHanZ** [comment]
Besides in CI and e2e test part, we should add the following tests to guarantee our OOS quality.
1. regular stateful test for local and Object storage(mocking)
2. Test kubernetes operator integration part and demo part before release get published during stable channel release.
3. Periodically test the kubernetes operator and helm part reside in different providers and clusters (perhaps once a day)

Not sure about when would us ready to run TPC-H benchmarks on large cluster, but we could prepare it on test infra.
1. Cluster size and estimated cost plan
2. test infra CI scripts to run TPC-H on GKE or graviton EKS
3. TPC-H dataset preparation and query part

**Comment by flaneur2020** [comment]
adding a `system.columns` table with a `SHOW COLUMNS table` syntax: https://github.com/datafuselabs/databend/issues/2608

**Comment by flaneur2020** [comment]
HTTP API with polling based incremental body response & progress metadata

**Comment by flaneur2020** [comment]
a new databend-playground with a modern SQL IDE

**Comment by drmingdrmer** [comment]
Update metasrv tasks

**Comment by BohuTANG** [comment]
Add Experimental checklist:
- [ ] #2679

**Comment by youngsofun** [comment]
@BohuTANG 


>  HTTP handler API works with all the queries which databend support(need issue)

It seems no extra work is required to support "all the queries".  

So I only need to add tests for each interpreter?

By the way, why insert result is  "0 rows affected" now?

**Comment by BohuTANG** [comment]
> @BohuTANG
> 
> > HTTP handler API works with all the queries which databend support(need issue)
> 
> It seems no extra work is required to support "all the queries".
> 
> So I only need to add tests for each interpreter?

Ok.

> By the way, why insert result is "0 rows affected" now?

I guess there is something wrong with the status(http handler), we could check it from the MySQL client.

**Comment by BohuTANG** [comment]
Progress report:
- [ ] #3181 
- [ ] #3143 

Once these two issues are finshed, we are ready to release v0.6 :rocket: 

**Note**
Other unfinished tasks will be rolled to the next version(Nightly v0.7)

**Comment by BohuTANG** [comment]
This  release is ready and will be released as scheduled :rocket:
