### ISSUE TITLE
Can't get the correct system.credits and system.contributors tables

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#2541]
**Summary**

When using the release version, can't get the correct system.credits and system.contributors tables 

**How to reproduce**

Use bendctl to create the cluster and then execute the relevant queries

**Error message and/or stacktrace**

![图片](https://user-images.githubusercontent.com/36896360/139520735-b06cb3f1-5f15-44e1-a343-60b57f5da1d9.png)

![图片](https://user-images.githubusercontent.com/36896360/139520766-75724381-21ba-4303-bf28-3f5bca93d847.png)

**Additional context**

Maybe hard-coded files should be generated instead of getting the information at build time

**Comment by BohuTANG** [comment]
It seems it's the github release issue, my local `make build` binary works.
