### ISSUE TITLE
`databend-meta` graceful shutdown when killed

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2543]
**Summary**

When `kill -9 <databend-meta pid>`, it always performance as:
```
bohu      114085  0.1  0.0      0     0 pts/5    Z+   12:18   0:11 [databend-meta] <defunct>
```
and never exit.

**Comment by BohuTANG** [comment]
It seems that the `databend-meta` service also need graceful shutdown like `databend-query`:
https://github.com/datafuselabs/databend/blob/c02796f43a64a507467fb63594c7c79836c58974/query/src/bin/databend-query.rs#L70-L86

**Comment by sunisdown** [comment]
> It seems that the `databend-meta` service also need graceful shutdown like `databend-query`:
> 
> https://github.com/datafuselabs/databend/blob/c02796f43a64a507467fb63594c7c79836c58974/query/src/bin/databend-query.rs#L70-L86

we have stop_handler in `common/base`, which is not being used.

https://github.com/datafuselabs/databend/commit/e54d122a0a74603bc94ce0590bca638906b3a64f

May I know why `meta` and `query` implement the graceful shutdown separately, instead of implement a generic lib in `databend/common` ?

**Comment by BohuTANG** [comment]
Good question, perhaps @zhang2014 can help us

**Comment by zhang2014** [comment]
> May I know why meta and query implement the graceful shutdown separately, instead of implement a generic lib in databend/common ?

The shutdown handler in query depends on some query components, and we need some refactor (it may not be simple).

**Comment by sunisdown** [comment]
> > May I know why meta and query implement the graceful shutdown separately, instead of implement a generic lib in databend/common ?
> 
> The shutdown handler in query depends on some query components, and we need some refactor (it may not be easy).
> 
> Maybe you're interested in trying it?
Let me try : )

**Comment by sunisdown** [comment]
Hi @drmingdrmer , I am trying to add graceful shutdown to `metasrv` and would like to know why it is not implemented for metasrv when the `stoppable` library is created? Is there any concerns?

**Comment by drmingdrmer** [comment]
> Hi @drmingdrmer , I am trying to add graceful shutdown to `metasrv` and would like to know why it is not implemented for metasrv when the `stoppable` library is created? any concerns?

Nothing is concerned but it is just a matter of time...

Haven't yet got time to do it. 🤔

**Comment by drmingdrmer** [comment]
@sunisdown
And as I recalled there is some adjustment that has to be applied to metasrv before using the stoppable framework.
