### ISSUE TITLE
[CLI] Change the `bendctl up` `ontime` engine to fuse table engine

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2562]
**Summary**

https://github.com/datafuselabs/databend/blob/2c45fe418d3bea8c7327421727f22f51c9353b4c/cli/src/cmds/ups/up.rs#L154

**Comment by ZhiHanZ** [comment]
I think we should define basic data loading api in bendctl to resolve this issue

**Comment by BohuTANG** [comment]
> I think we should define basic data loading api in bendctl to resolve this issue

Right.

@zhang2014 @sundy-li  any thoughts?

**Comment by zhang2014** [comment]
> I think we should define basic data loading api in bendctl to resolve this issue

+1
