### ISSUE TITLE
`chrono` crate unmaintained consider replace it with `time-rs/time`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2565]
**Summary**

chrono is unmaintained and has security issues.
https://www.reddit.com/r/rust/comments/qamgyh/is_the_chrono_crate_unmaintained/

time:
https://github.com/time-rs/time/blob/main/CHANGELOG.md

RUSTSEC-2020-0159:
https://rustsec.org/advisories/RUSTSEC-2020-0159.html

**Comment by PsiACE** [comment]
/assignme

Although I took this issue, collaborators are still welcome.

**Comment by PsiACE** [comment]
I will close it now, chrono is also common upstream.

I think we do not currently have the bandwidth to handle it.
