### ISSUE TITLE
Stable cluster query

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#2573]
**Summary**
- [ ] Support retry when node offline during query
- [x] Supports the transfer of different types of data between cluster nodes(log, metrics, progress)
- [x] Use graph to describe processors
- [x] Cluster query task scheduling based on processors
- [x] #3379
- [ ] Support visualization for query plan
    - [ ] Print processors with [graphviz](https://www.graphviz.org/) format 
    - [ ] Display the local query plan using graph(figure 1)
    - [ ] Display the distribute query plan using graph(figure 2)
    - [ ] Display the run-time data(progress) in the graph edge(#2628)

**figure 1**
<img width="1439" alt="local_graph" src="https://user-images.githubusercontent.com/8087042/139638781-dcb81d7a-03d6-425e-8eb0-3f3e06120834.png">
**figure 2**
<img width="1282" alt="cluster_graph" src="https://user-images.githubusercontent.com/8087042/139638794-e942f1d1-872d-48be-9ee3-bd5d09d20ff6.png">

**Comment by BohuTANG** [comment]
We have profile now, let's close this.
