### ISSUE TITLE
post json instead of sql in  /v1/statement/  

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#2604]
**Summary**

the first version of http handler,  post raw sql statement to   /v1/statement/.
I think it is better to post json instead to carry more context info.

```
{
"sql": "select * from number(10)" 
}
```

## reasons  

1.  one place to organize all context infos.
2. header and params are key-value, need other effort to embed complex info 
3. params and header have encode requirements  and length limitation.

## how

since  /v1/statement/  is used in  cli and playground. we need to discuss the way to do it.

1.  let  /v1/statement/ accept  json only 
3. add a new endpoint /v1/query,   abandon  /v1/statement/
4. add a new endpoint /v1/query for main use,  keep  /v1/statement/ for simple cases.

## possible reason to reserve the raw_sql api: 

1.  make it easy to write for tools like curl.
2.  it looks like the presto protocol (but it is difficult to be really compatible)
3. click house use it to insert data (but we will have other api for data import)

sorry for not thinking  it clearly to begin with.

@flaneur2020 @ZhiHanZ 

## related issue

https://github.com/datafuselabs/databend/issues/2241

**Comment by youngsofun** [comment]
trino v2 plan to use json too

https://github.com/trinodb/trino/wiki/Trino-v2-client-protocol

**Comment by flaneur2020** [comment]
the trino v2 protocol is much better IMO 🤔

**Comment by ZhiHanZ** [comment]
I prefer json schema. post json  data provided advanced security guarantees and would be good to integrate needed fields without missing, on contrary, add a lot of queries in get would be quite messy

**Comment by youngsofun** [comment]
snow flake:

https://docs.snowflake.com/en/developer-guide/sql-api/index.html

**Comment by youngsofun** [comment]
@ZhiHanZ  which do you prefer

> 1. let /v1/statement/ accept json only
> 2. add a new endpoint /v1/query, abandon /v1/statement/
> 3. add a new endpoint /v1/query for main use, keep /v1/statement/ for simple cases.

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ which do you prefer
> 
> > 1. change  /v1/statement/ directly to accept json only
> > 2. add a new endpoint /v1/query, abandon /v1/statement/
> > 3. add a new endpoint /v1/query for main use, keep /v1/statement/ for simple cases.

case 3 looks make sense, `v1/statement` is for debugging and simple demo, `v1/query` works for cloud platform
