### ISSUE TITLE
Fix Table version mismatched error.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2605]
```
---- servers::clickhouse::clickhouse_handler_test::test_clickhouse_insert_to_fuse_table stdout ----
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Code: 2407, displayText = targeting version 1, current version 2.
```

https://github.com/datafuselabs/databend/runs/4077452057?check_suite_focus=true

- A first guess is that `MetaCached` cached table info thus no updated table can be re-fetched in a CAS-loop. This is fixed in #2603 . Keep watching other CI to see if this exception disspears.
- Another issue is the `TableVersionMissMatch` error is not dealt with. The following TODO is meant to get this done:

https://github.com/datafuselabs/databend/blob/088f8bbb95d2a7c04cd0fe67df795765cd23ce3f/query/src/datasources/table/fuse/table_do_append.rs#L70-L96

**Comment by drmingdrmer** [comment]
@dantengsky

**Comment by dantengsky** [comment]
roger, digging into it. can not re-produce in local dev yet. 

I guess `ClientHandle::insert` is executed asyncly, even if 
`insert(&mut handler, &test_tbl_name, block).await?;` is used in test case

**Comment by dantengsky** [comment]
> I guess ClientHandle::insert is executed asyncly, even if insert(&mut handler, &test_tbl_name, block).await?; is used in test case

No, it is not the case, just confirmed with @sundy-li

**Comment by drmingdrmer** [comment]
Roger that, and:
- close this and track this issue in #2589
