### ISSUE TITLE
Allow get the fields of a table in a easy parsed format

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#2608]
**Summary**

currently we can get the table schema by `show create table xxx`, but it's in a sql format:

```
mysql> mysql> show create table system.metrics;
+---------+--------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                             |
+---------+--------------------------------------------------------------------------------------------------------------------------+
| metrics | CREATE TABLE `metrics` (
  `metric` String,
  `kind` String,
  `labels` String,
  `value` String,
) ENGINE=SystemMetrics |
+---------+--------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
Read 0 rows, 0 B in 0.000 sec., 0 rows/sec., 0 B/sec.
```

it's human friendly, but hard for machine to interpret the table schema.

currently I want build a sql IDE for databend, it has a explorer panel allowing user to view a table's fields, and searchable, but there's no way to easily discover the table fields yet.

there's a `system.columns` table in clickhouse: https://clickhouse.com/docs/en/operations/system-tables/columns/

maybe we could take a similar approach

**Comment by BohuTANG** [comment]
This is a general requirement not only `system.tables` case, we should support define the output format with `FORMAT JSON`.
See
https://clickhouse.com/docs/en/interfaces/formats/#json

@zhang2014 any suggestions?

**Comment by sundy-li** [comment]
> Perhapes we can add a OutputFormatStream to handle it.

That's a big work: formats for input/output data, we can address it if necessary.

But this is not related to this issue.

`show create table`  outputs data with fields: `Table` and `Create Table`, I guess it's to be compatible with MySQL's behavior.

**Comment by flaneur2020** [comment]
the behaviour of `show create table` should not be touched, what we might try is adding infomation about the fields outside.

I think @zhang2014 's comment in https://github.com/datafuselabs/databend/pull/2609#issuecomment-957366951 is a good idea, a JSON formatted field is pretty tricky 🤔

**Comment by zhang2014** [comment]
`SHOW COLUMNS db.table` statement also should be allowed

**Comment by flaneur2020** [comment]
there's a `DESCRIBE {db}.{table}` syntax which already met my needs 😂, sorry for interrupt.

https://databend.rs/sqlstatement/describe-commands/describe-table/
