### ISSUE TITLE
Support `copy` command to load csv/parquet or s3 file into table

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2627]
**Summary**

Description for this feature.

 support copy command to load csv file into table.
 
 ```
COPY table_name FROM '/path/to/test.csv'
```

task list:

- [x] support copy stage csv/parquet file into table #2878 
- [x] support async read stream to parse formats #2786
- [x] #3082 

Reference:
https://www.postgresql.org/docs/13/sql-copy.html
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html
https://duckdb.org/docs/sql/statements/copy

**Comment by ZhiHanZ** [comment]
I think it should be a query semantic in http handler?

**Comment by sundy-li** [comment]
>  I think it should be a query semantic in http handler?

But we need to upload localfile, how could http handler handle this?

**Comment by BohuTANG** [comment]
> > I think it should be a query semantic in http handler?
> 
> But we need to upload localfile, how could http handler handle this?

1. http handler provides a put file(like `xx_yy.csv`) command to a path as `tmp_dir` which configed in the query -- this upload a file to the internal stage
2. query supports the `COPY` command: `COPY table_name FROM 'xx_yy.csv'` -- query read the file from the internal stage

https://docs.snowflake.com/en/sql-reference/sql/put.html
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#loading-files-from-an-internal-stage

**Comment by flaneur2020** [comment]
> > > I think it should be a query semantic in http handler?
> > 
> > 
> > But we need to upload localfile, how could http handler handle this?
> 
> 1. http handler provides a put file(like `xx_yy.csv`) command to a path as `tmp_dir` which configed in the query -- this upload a file to the internal stage
> 2. query supports the `COPY` command: `COPY INTO table_name FROM 'xx_yy.csv'` -- query read the file from the internal stage
> 
> https://docs.snowflake.com/en/sql-reference/sql/put.html https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#loading-files-from-an-internal-stage

the csv file have to located on the bend-query instance's local filesystem? 🤔

**Comment by flaneur2020** [comment]
how about copy file from a s3 or hdfs path? like:

```
COPY INTO table_name FROM 's3://xx_yy.csv?s3_token=xxxx'
```

**Comment by sundy-li** [comment]
> how about copy file from a s3 or hdfs path? like:
> 
> ```
> COPY INTO table_name FROM 's3://xx_yy.csv?s3_token=xxxx'
> ```


Yes, we can judge the protocol like "s3", "http", "hdfs", "file". I'll implement a base version to support local filesystem.

**Comment by BohuTANG** [comment]
Are there any more tasks for this issue?
