### ISSUE TITLE
Make `create user` works

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2630]
**Summary**

After https://github.com/datafuselabs/databend/pull/2550, we should add the interpreter_create_user to make it works.

**Comment by GrapeBaBa** [comment]
I am working on it. Need another issue here?

**Comment by BohuTANG** [comment]
> I am working on it. Need another issue here?

Oh my, I have just implemented `create user`, but still need to implement `drop user/alter user` etc.

**Comment by GrapeBaBa** [comment]
Yes, i am working on update user function. Well, I can pull your updates.

**Comment by BohuTANG** [comment]
> Yes, i am working on update user function. Well, I can pull your updates. Can this PR merge first or I checkout this PR?

Right, thank you!
