### ISSUE TITLE
Fuse engine seems ignore the projection column prune.

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2632]
**Summary**

Description for this bug.

From @ZhiHanZ  wechat image.

![image](https://user-images.githubusercontent.com/3325189/140051618-7f56ef5e-ebd2-4d30-8935-541948cd22ab.png)

```
>>> 3.79 * 1048576 * 1024 / 4284928
949.7199283068467  bytes/row
>>>
```

**Comment by dantengsky** [comment]
is `ReadDataSourcePlan::push_downs.projection` supposed to be used in this case?

**Comment by sundy-li** [comment]
Yes

**Comment by dantengsky** [comment]
roger
