### ISSUE TITLE
[Test/Integration/Tracking] implement generic test framework for integration test

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#2647]
**Summary**
Similar to integration test in kubernetes and kubebuilder https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html
For local test:
1, we use cargobin to ensure binaries on desired local and bootstrap cluster through code similar to bendctl basic test.
2. For stateless and stateful test we could choose desired number of query instance to run and deploy test them uniformly on test_env.
The test framwork would be
```bash
├── integration
│   ├── Cargo.toml
│   └── src
│       ├── framework
│       │   └── local
│       ├── lib.rs
│       └── sql
```
For cluster test:
we need to ensure some third party kubernetes dependencies and do the same thing

- [ ] #3844

**Comment by PsiACE** [comment]
> 
> ```shell
> ├── integration
> │   ├── Cargo.toml
> │   └── src
> │       ├── framework
> │       │   └── local
> │       ├── lib.rs
> │       └── sql
> ```
>

```shell
├── integration
│   ├── Cargo.toml
｜   ├── sql # If it is large, we can keep only a subset
│   └── src
│       ├── framework
│       │   └── local
│       └── lib.rs
> ```

**Comment by Xuanwo** [comment]
Come on, Let's go! I expect that we can remove all python scripts after this issue implemented.

**Comment by Xuanwo** [comment]
I'm not interested in this issue any more. Feel free to take it :rocket:

**Comment by leiysky** [comment]
Is it possible to support error check in this framework? 

The current integration tests relies on hint to specify the error code, which is not a good method.

**Comment by ZhiHanZ** [comment]
> Is it possible to support error check in this framework? 
> 
> The current integration tests relies on hint to specify the error code, which is not a good method.

PTAL at the new framework,  https://github.com/datafuselabs/databend/pull/5048 
It should support error regex matching . Retry and result sorting in the new framework

**Comment by PsiACE** [comment]
Now we have a new sql logic test framework
