### ISSUE TITLE
`alter user` statement

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2657]
**Summary**

`ALTER USER USER() IDENTIFIED BY 'auth_string'`

For example:
`ALTER USER 'jeffrey'@'localhost' IDENTIFIED BY 'new_password'`

**Comment by GrapeBaBa** [comment]
@BohuTANG Where could we get current user?

**Comment by flaneur2020** [comment]
maybe we need add an user field into the Session struct? 🤔
https://github.com/datafuselabs/databend/blob/a598d928d50644ee0bbddd8c9b36d837b1c7044a/query/src/sessions/session.rs#L49

**Comment by BohuTANG** [comment]
> maybe we need add an user field into the Session struct? thinking https://github.com/datafuselabs/databend/blob/a598d928d50644ee0bbddd8c9b36d837b1c7044a/query/src/sessions/session.rs#L49..L58

Indeed, we should bind user to the session.
