### ISSUE TITLE
Migrate Axum to Poem

### ISSUE THREAD

**Issue by sunli829** [datafuselabs/databend#2666]
**Summary**

I think [`Poem`](https://github.com/poem-web/poem) is more concise and easy to use, and its performance is also very good.
If you want, I will open a PR, and this will be done soon. 😁

**Comment by ZhiHanZ** [comment]
Hi @sunli829 , thank you for your interest on our project. Here is something I considered for migration:
1. For tls management, axum_server could handle with tls rotation(https://github.com/programatik29/axum-server/blob/master/examples/tls_reload.rs) and support rustls related feature such as client-auth which is essential for production security, does poem want to support those feature?
2. Does poem support to manage low-level hyper http stream api(we need to handle those part for abort handling, where some issue and resource leaking occured(https://github.com/datafuselabs/databend/issues/2407)

**Comment by GrapeBaBa** [comment]
There are so many friends in Wuhan

**Comment by sunli829** [comment]
> There are so many friends in Wuhan

Welcome to Wuhan.😁
