### ISSUE TITLE
Consider using `objcopy` to reduce the binary size in release build

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2677]
#1959 used `link-arg=-Wl,--compress-debug-sections=zlib-gabi` as build flags to reduce the binary size.

1. It has a bad impact on debug build which will make debug building slow.
2. It adds  `.cargo/config` into git control which makes developers hard to have their own local config.

`objcopy` seems to be a good util tool to reduce debug info in linux env, refer to tikv's build script: https://github.com/tikv/tikv/blob/master/Makefile#L207-L215

cc @PsiACE

**Comment by PsiACE** [comment]
> 1. It has a bad impact on debug build which will make debug building slow.

Okay, it may not be greatly affected in my local, but it does exist

> 2. It adds  `.cargo/config` into git control which makes developers hard to have their own local config.

Makes sense. But many other repos also contain this file, and I think there should be a better way to deal with it.

> `objcopy` seems to be a good util tool to reduce debug info in linux env

I will investigate it. And do a try and compare.
