### ISSUE TITLE
User Privileges

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2678]
**Summary**

User privileges defined the queries what a user can execute, here is an initial list:
- [x] #2679  
      Enables executing `set` statement, such as `set max_threads=4`

**Comment by flaneur2020** [comment]
I added an issue about RBAC: https://github.com/datafuselabs/databend/issues/2793  maybe can be tracked in this bigger issue?

i'd prepare an RFC document in the first step

**Comment by BohuTANG** [comment]
> I added an issue about RBAC: #2793 maybe can be tracked in this bigger issue?
> 
> i'd prepare an RFC document in the first step

Sure, thank you @flaneur2020

**Comment by BohuTANG** [comment]
Move to #2793
