### ISSUE TITLE
Failed to create users with different hostnames

### ISSUE THREAD

**Issue by Junnplus** [datafuselabs/databend#2695]
**Summary**
Failed to create users with different hostnames.

**How to reproduce**

```
mysql> SHOW USERS;
+------+-----------+----------+-----------+
| name | hostname  | password | auth_type |
+------+-----------+----------+-----------+
| test | localhost | password |         3 |
+------+-----------+----------+-----------+
1 row in set (0.00 sec)
Read 1 rows, 70 B in 0.000 sec., 2.01 thousand rows/sec., 140.85 KB/sec.

mysql> CREATE USER 'test'@'127.0.0.1' IDENTIFIED BY 'password';
ERROR 1105 (HY000): Code: 3001, displayText = User already exists, seq [1634](while add user)..
```

**Error message and/or stacktrace**

**Additional context**

**Comment by Junnplus** [comment]
Should we use like `__fd_users/test/localhost` as the key in [add_user](https://github.com/datafuselabs/databend/blob/main/common/management/src/user/user_mgr.rs#L52) to support create users with different hostnames.

**Comment by BohuTANG** [comment]
Account name syntax is `'user_name'@'host_name'`, the `@'host_name'` part is optional.
So, `test@localhost` and `test@127.0.0.1` is the different account, we should use both `'user_name'@'host_name'` as the key not `user_name` only.
