### ISSUE TITLE
metasrv: add http api for monitoring etc

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2702]
Something like v1/cluster to return a list of members

**Comment by drmingdrmer** [comment]
Thank you man for taking this issue!

FYI:
There are two kinds of nodes: voters and non-voters. `MetaRaftStore::list_non_voters()` is a good reference about these concepts.
- Voters AKA `members` can be retrieved with `get_membership_config()`.
- Non-voters are stored in a sled sub tree `StateMachine::nodes()`.

**Comment by sunisdown** [comment]
@drmingdrmer  thanks for the reminder.

I originally thought it was just to show the information, but when I glanced at the code I found that the http server currently can't get the sled instance, and probably needs more code changes than I had expected. the basic idea is:

1 Add a context to the http/rpc/metrics server
2 The context needs to hold the sled (metastore) instance.
3 Read the context metastore data in the http handler and return the result.

do you have any suggestion?

**Comment by drmingdrmer** [comment]
The chain of these components in metasrv is:
```
FlightServer -> MetaNode -> MetaRaftStoe -> StateMachine -> SledTree
```

`membership` is only understood by `MetaRaftStore` and `MetaNode`.
Thus to retrieve a list of voters or non-voters, it's better to get it done in `MetaNode`, instead of accessing SledTree directly.

To your questions:
- The http server needs a reference to `MetaNode`. But for now the creation process for `MetaNode` is inside `FlightServer::serve()`. We need to refactor this part:  move the creation of `MetaNode` out of `FlightServer::serve`.
- Then let `HttpServer` have a clone of `MetaNode` so that it's able to get anything it needs.

**Comment by sunisdown** [comment]
@drmingdrmer  


> * Voters AKA `members` can be retrieved with `get_membership_config()`.
> * Non-voters are stored in a sled sub tree `StateMachine::nodes()`.

Hi bro, May I know where can we get the IP for the voters?

**Comment by drmingdrmer** [comment]
`MetaNode.sto.get_node_addr(id)` is what you want XDDD

**Comment by sunisdown** [comment]
If I understand correctly, then `MetaNode.sto` contains all the nodes, which are divided into two kinds, the `voters` in the `membership_config`, and the `non-vonters` if they are not in the `membership_config`.

**Comment by drmingdrmer** [comment]
> If I understand correctly, then `MetaNode.sto` contains all the nodes, which are divided into two kinds, the `voters` in the `membership_config`, and the `non-vonters` if they are not in the `membership_config`.

Absolutely definitely and surely correct.

**Comment by sunisdown** [comment]
@drmingdrmer When I was writing the code, I considered returning a map, similar to `{"non-voters": [nodeList...], "voters": [nodeList...]} , but felt that this would put too much functionality into one API. So the final implementation just returns a list of all the nodes.

**Comment by drmingdrmer** [comment]
@sunisdown 
Returning all nodes may not be enough.

I believe the original requirement is to monitor or to manage the metasrv cluster.
The health of voter nodes defines the health of the cluster. Thus there should at least be a list of voters in the returned valued.

BTW, which node is the leader is also an important info.
