### ISSUE TITLE
[security] make csv/parquet engine work with dal

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2730]
**Summary**

Now csv/parquet engine can only work with a local file. However, it allows users to read any file with permission in the query node.

This is dangerous, such as: `/etc/passwd`, `/etc/sudoers`.

We should make these engines work with dal.

**Comment by BohuTANG** [comment]
1. For local file
we should introduce a `tmp_dir`, all the files in this directory can be accessed.
During reading:
read('file_label_name') -- read from '/tmp_dir/file_label_name'

2. For the cloud
   user puts their local file to a s3 storage bucket(we will give a address then), and using the `COPY ... FROM S3(...)` command to read.

**Comment by sundy-li** [comment]
How about reuse the `Config.Storage` in query node, there is a config named `data_path` that can be used.

If we delopy as cloud-native serverless , the local file did not make sense.

**Comment by BohuTANG** [comment]
> How about reuse the `Config.Storage` in query node, there is a config named `data_path` that can be used.
> 
> If we delopy as cloud-native serverless , the local file did not make sense.

Looks great :100:

**Comment by Xuanwo** [comment]
Any updates on this?

**Comment by BohuTANG** [comment]
> Any updates on this?

We don't have plan for it in the future time, I think we should close it first.
