### ISSUE TITLE
[Monitoring] add label in monitor metrics

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#2744]
**Summary**
label on tenant and cluster_name would be nice to filter stat metrics through promql
https://docs.rs/metrics/0.17.0/metrics/struct.Label.html

**Comment by GrapeBaBa** [comment]
What need to do next?

**Comment by ZhiHanZ** [comment]
> What need to do next?

Hi @GrapeBaBa , please check out the issue https://github.com/datafuselabs/databend/issues/2756 for next stage monitoring plan.

**Comment by BohuTANG** [comment]
And after this issue finished the user level metrics will be ready:
https://github.com/datafuselabs/databend/issues/2779

**Comment by GrapeBaBa** [comment]
Seems tasks are all in progress. Right?

**Comment by BohuTANG** [comment]
> Seems tasks are all in progress. Right?

That's right.

**Comment by BohuTANG** [comment]
Plan to use system.query_log table instead the metrics https://github.com/datafuselabs/databend/issues/2868
