### ISSUE TITLE
[Cluster API] provide dns resolution on flight rpc

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#2755]
**Summary**
Currently, flight rpc could only get connected through ip, it would be nice to have dns resolution to cover more information in cluster status( for example, k8s namespace)

**Comment by zhang2014** [comment]
We have implemented DNSResolver for flight RPC(https://github.com/datafuselabs/databend/blob/main/common/flight-rpc/src/dns_resolver.rs)

**Comment by ZhiHanZ** [comment]
> We have implemented DNSResolver for flight RPC(https://github.com/datafuselabs/databend/blob/main/common/flight-rpc/src/dns_resolver.rs)

agreed. for audit log on group lifecycle, we may provide another api on meta service
