### ISSUE TITLE
Session metrics for cost 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2756]
**Summary**

To measure a cost of a query, there are many metrics need addressed:
1. Binding tenant_id and cluster_id to session for identifiy who own the session.
2. Binding a tokio runtime to session for memory usage and cpu limited.
3. Binding read_bytes/write_bytes/execution_time to the session for the last query

The struct of the Session need refactored for the fine-grained resource managing.

**Comment by ZhiHanZ** [comment]
we should also stat on request per sec, io( disk + s3) and label them all with tenant and cluster_name

**Comment by BohuTANG** [comment]
> we should also stat on request per sec, io( disk + s3) and label them all with tenant and cluster_name

Sure, the k8s layer should provide a cost model? like: https://github.com/kubecost/cost-model/blob/develop/kubecost-exporter.md

**Comment by ZhiHanZ** [comment]
> > we should also stat on request per sec, io( disk + s3) and label them all with tenant and cluster_name
> 
> Sure, the k8s layer should provide a cost model? like: https://github.com/kubecost/cost-model/blob/develop/kubecost-exporter.md

need to investigate on possible integration with the cost model
