### ISSUE TITLE
How binding session with dal request?

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2766]
In order to do a pricing model, we should know how much cost(object requests/read_bytes/write_bytes etc.) for a tenant_id and cluster_id, now we can do it in query by the metric label: https://github.com/datafuselabs/databend/issues/2744 and PR:https://github.com/datafuselabs/databend/pull/2760

Since `dal` crate there is no tenant related with it, so what's the best way to do it?
Move `dal` to `query` and add session(Now tenant_id and cluster_id binding to the session)?

cc @dantengsky , welcome thoughts :)

- [x] #2804
- [x] #2806

**Comment by drmingdrmer** [comment]
IMHO, it may be feasible to let `dal` defines the api for reporting, and `query` impl the api and bind the `session` to the impl:

- `dal` defines a trait(something like `trait ReportMetric{ fn report(bytes_read: usize); }`  for reporting metric data.
- `query` impl the trait, e.g. `struct query::TenantMetric { tenant_id: u64 ... }`.
- When creating a `dal.DataAccessor`, `query` creates a `dyn TenantMetrics` and passes it to: `fn DataAccessor::new(bla: Bla, metric: Option<Arc<dyn ReportMetric>>)`.

**Comment by flaneur2020** [comment]
can we get how much io bandwidth a query consumed in the flight? 

during the query executing, the HTTP api can return the bytes/rows it scanned, I think the DAL statistics might be similiar, it's a statistic which collected during the query execution, not necessarily a prometheus metric?

**Comment by drmingdrmer** [comment]
> can we get how much io bandwidth a query consumed in the flight?
> 
> during the query executing, the HTTP api can return the bytes/rows it scanned, I think the DAL statistics might be similiar, it's a statistic which collected during the query execution, not necessarily a prometheus metric?

Sounds good to me.

Since the cost of most storage services is charged by traffic not bandwidth.
Is the total bytes transferred is enough to your need?

**Comment by BohuTANG** [comment]
We are working on it, based on the metric label feature, it likes a probe than a object binding, see #2821

**Comment by flaneur2020** [comment]
> > can we get how much io bandwidth a query consumed in the flight?
> > during the query executing, the HTTP api can return the bytes/rows it scanned, I think the DAL statistics might be similiar, it's a statistic which collected during the query execution, not necessarily a prometheus metric?
> 
> Sounds good to me.
> 
> Since the cost of most storage services is charged by traffic not bandwidth. Is the total bytes transferred is enough to your need?

sorry it's traffic not bandwidth, i misused the word >.<

besides the cost billing, tracking how many bytes transfered by a query and record the traffic infomation into the query log might be useful for us to diagnose the traffic outliers and make optimizations in the future

**Comment by BohuTANG** [comment]
> > > can we get how much io bandwidth a query consumed in the flight?
> > > during the query executing, the HTTP api can return the bytes/rows it scanned, I think the DAL statistics might be similiar, it's a statistic which collected during the query execution, not necessarily a prometheus metric?
> > 
> > 
> > Sounds good to me.
> > Since the cost of most storage services is charged by traffic not bandwidth. Is the total bytes transferred is enough to your need?
> 
> sorry it's traffic not bandwidth, i misused the word >.<
> 
> besides the cost billing, tracking how many bytes transfered by a query and record the traffic infomation into the query log might be useful for us to diagnose the traffic outliers and make optimizations in the future

We can do it in the monitor side, it's a sql as : sum(read_bytes) ... group by time ....
