### ISSUE TITLE
[flaky test] servers::http::v1::http_query_handlers_test::test_simple_sql

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#2767]
**Summary**

```bash
---- servers::http::v1::http_query_handlers_test::test_simple_sql stdout ----
thread 'servers::http::v1::http_query_handlers_test::test_simple_sql' panicked at 'internal error: entered unreachable code', query/src/servers/http/v1/query/execute_state.rs:73:27
```

see: https://github.com/datafuselabs/databend/runs/4197693711?check_suite_focus=true#step:5:890

**Comment by BohuTANG** [comment]
There is also many `unwrap` in http handler need to be addressed and return the err, like:
https://github.com/datafuselabs/databend/blob/f4517719e7b222c3b7c6ea07375fd992e7513856/query/src/servers/http/v1/query/execute_state.rs#L120
https://github.com/datafuselabs/databend/blob/f4517719e7b222c3b7c6ea07375fd992e7513856/query/src/servers/http/v1/query/execute_state.rs#L161
https://github.com/datafuselabs/databend/blob/f4517719e7b222c3b7c6ea07375fd992e7513856/query/src/servers/http/v1/query/result_data_manager.rs#L96

**Comment by youngsofun** [comment]
@BohuTANG terribly sorry

**Comment by BohuTANG** [comment]
> @BohuTANG terribly sorry

That's OK, man~
