### ISSUE TITLE
Deduplicate calculations in the ExpressionExecutor

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#2775]
**Summary**

Expression in the same plan will lead to some repeated calculations. for example(column_a + 1 is duplicated):
```
SELECT column_a + 1 AS column_b FROM table_a GROUP BY column_b, column_b + 1;
```

**Comment by Thearas** [comment]
Hi @zhang2014, I'm interested in databend and I'd like to take this issue. Could you give me some hints on how to test the effect?

**Comment by zhang2014** [comment]
> Hi @zhang2014, I'm interested in databend and I'd like to take this issue. Could you give me some hints on how to test the effect?

We only need to build `ExpressionDAG`(it needs to be implemented, same expression does not create a new node in the `DAG`) for `Vec<Expression>`, and use `DAG` topological sorting result as `ExpressionChain`. and we can use unit tests to test it.

**Comment by Thearas** [comment]
Thanks for your reply. Maybe this issue is a little hard for me, I would choose an easier issue 😂.

But I'm still curious about `Deduplicate calculations`. According to the document <https://databend.rs/rfcs/query/0002-plan-expression/#materialized-expression>, `column_a + 1` will only be calculated once.

**Comment by zhang2014** [comment]
> Thanks for your reply. Maybe this issue is a little hard for me, I would choose an easier issue 😂.
> 
> But I'm still curious about Deduplicate calculations. According to the document https://databend.rs/rfcs/query/0002-plan-expression/#materialized-expression, column_a + 1 will only be calculated once.

It's Ok. You can implement this before it is assigned to others if you are interested when you're familiar enough :)

The RFC is about how to deduplicate calculations of expression in multiple plans

**Comment by BohuTANG** [comment]
Outdated.
