### ISSUE TITLE
Return Err instand unwrap in http handler

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2776]
**Summary**

There are many `unwrap` in http handler, we should address and return the Err instead.
Seach `unwrap` in `query/src/servers/http/`

**Comment by youngsofun** [comment]
@BohuTANG I saw some  `unwap` in unit test other mods.
do we need to fix them too?

**Comment by BohuTANG** [comment]
> @BohuTANG I saw some `unwap` in unit test other mods.
> do we need to fix them too?

unit tests unwrap is ok, most of them by design, no need to fix.

**Comment by flaneur2020** [comment]
> @BohuTANG I saw some `unwap` in unit test other mods. do we need to fix them too?

i think unwrap() in test cases is ok, we can take it as some sort of `assert` in test cases

in the production code, maybe there're two conditions are ok to unwrap(): 

- on starting up, fail fast if there're something wrong about the configs
- we strongly believe it's nearly impossible to occur, such as this tweet describes: https://twitter.com/ospopen/status/1458082697327235072

**Comment by Xuanwo** [comment]
Any updates on this issue? Is there any actionable task?

**Comment by youngsofun** [comment]
no unwrap in original in /v1/query
but introduced some new  unwrap in load.rs

**Comment by Xuanwo** [comment]
> but introduced some new unwrap in load.rs

How about closing this issue and creating a new one like `Remove unwrap in load.rs`? (of course, mark it as `good first issue`)

**Comment by youngsofun** [comment]
lgtm

**Comment by Xuanwo** [comment]
Replaced by https://github.com/datafuselabs/databend/issues/5458
