### ISSUE TITLE
Bind user to session

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2779]
**Summary**

There are a few tasks need to do:
- [x] Add user name to InteractiveWorker when the auth is passed
- [ ] Add user name to https://github.com/datafuselabs/databend/blob/e595993705ce9b719b0df78a4e1013a02fd77510/query/src/sessions/sessions.rs#L100
- [x] Get user info by user name and bind the user info to the session

Any thoughts are welcome ~

**Comment by BohuTANG** [comment]
cc @zhang2014

**Comment by flaneur2020** [comment]
@zhang2014 can i take this issue? I'm working on a draft on RBAC, want get some practises on the code base of the priviledge stuffs 🙏

**Comment by zhang2014** [comment]
> @zhang2014 can i take this issue? I'm working on a draft on RBAC, want get some practises on the code base of the priviledge stuffs 🙏

@flaneur2020 Good job. I'm unassigned.

**Comment by flaneur2020** [comment]
/assignme

@zhang2014 thank you
