### ISSUE TITLE
RBAC privileges

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#2793]
**Summary**

## Tasks

- https://github.com/datafuselabs/databend/issues/3877
- https://github.com/datafuselabs/databend/issues/2815 
- https://github.com/datafuselabs/databend/issues/3799
- https://github.com/datafuselabs/databend/issues/4187
- https://github.com/datafuselabs/databend/issues/4193
- https://github.com/datafuselabs/databend/issues/4201
- https://github.com/datafuselabs/databend/issues/4202

## references:

- https://dev.mysql.com/doc/refman/8.0/en/roles.html
- https://docs.snowflake.com/en/user-guide/security-access-control-privileges.html

**Comment by BohuTANG** [comment]
Add: 
- [ ] #2815
