### ISSUE TITLE
Add `multi-tenancy` mode for internal usage

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2794]
**Summary**

Such as `database/table create`, `user create`, these operation only related to the metasrv, but we want use SQL to do them for difference tenant.
Here introduce a new query config `multi-tenancy`(boolean):
true  - enalble `set tanent_id=xx`
false - disable `set tanent_id=xx`

This is a internal usage, such as a account init in the cloud platform, we can set `multi-tenancy` on a special databend-query as a global proxy, to do the meta operation with metasrv from the special databend-query.

**Comment by BohuTANG** [comment]
Another way is that let's metasrv provides RPC api.

**Comment by Xuanwo** [comment]
@BohuTANG Is this issue still valid?

**Comment by BohuTANG** [comment]
Outdated, thank you!
