### ISSUE TITLE
Move `dal` to `query`

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#2804]
tasks:

- [x] #2835

     `source_csv` will be placed at `query/src/datasources/table/csv`
     
     `source_parquet` will be placed at `query/src/datasources/common`
      since `ParquetSource` is supposed to be reused by fuse table (see issue #2807)
      
     `common-streams` should no longer depend on `common-dal`

- [ ] <del>move  `common/context ` and `common/dal` into query</del>

     `common/context` will be placed at `query/src/datasources/common/context`
      
     `common/dal` will be placed at `query/src/datasources/dal`

any suggestions/concerns, please let me know

**Comment by dantengsky** [comment]
It's not gonna work, since crate `common-stream` depends on `common-dal` (and `query` depends on `common-stream`).

thanks @sundy-li for reminding me.

but I think
- issue #2766

can still be implemented without this refactoring

**Comment by BohuTANG** [comment]
I guess it's `common-context` depends on `common-dal`:
https://github.com/datafuselabs/databend/blob/412834ce5caaef3ae46fd9ddd8d0414755b98699/common/context/Cargo.toml#L16

Keep `dal` in `common` is ok, there is another question here:
If we move `dal` to `query`, `common/context` is no need anymore? It looks a adapter context between query and dal crate.
@dantengsky @drmingdrmer

**Comment by dantengsky** [comment]
> It looks a adapter context between query and dal crate, the codes looks more cleaner

is `TableIOContext` the **adapter context** you mentioned above? frankly speaking, I'd prefer to use `DatabendQueryContext` directly.

`common-streams` depends on `common-dal` too

https://github.com/datafuselabs/databend/blob/412834ce5caaef3ae46fd9ddd8d0414755b98699/common/streams/Cargo.toml#L21

**Comment by BohuTANG** [comment]
I think it's time to move `dal` to `query` crate, actually the `stream` should not depends the `dal` layer.
`dal`  crate in the common just adds complexity and no other advantages for now.

**Comment by dantengsky** [comment]
> dal crate in the common just adds complexity and no other advantages for now.

agree, a rough idea:

1. move `common/streams/sources/source_[parquet|csv].rs` into `query`
    although `source_csv.rs` does not depend on `DataAccessor` currently, @sundy-li is planning a refactoring so that `CsvSource` will use `DataAccessor` to read data as well (like `ParquetSource`)
2. move `common/context` into `query`, so that there will be no cross crate circular dependency
    but keep `TableIOContext` as it is at this stage
3. finally,  move `common/dal` into `query/datasource`

what do you think? @BohuTANG @sundy-li

**Comment by sundy-li** [comment]
CsvSource/Parquet sources must depend on dal, because we must implement  `COPY INTO TABLE from dal_streams`.

**Comment by dantengsky** [comment]
> CsvSource/Parquet sources must depend on dal, because we must implement COPY INTO TABLE from dal_streams.

shall we move [Csv|ParquetSource] to `query/datasource/table/[csv|parquet] accordingly?

**Comment by BohuTANG** [comment]
> > dal crate in the common just adds complexity and no other advantages for now.
> 
> agree, a rough idea:
> 
> 1. move `common/streams/sources/source_[parquet|csv].rs` into `query`
>    although `source_csv.rs` does not depend on `DataAccessor` currently, @sundy-li is planning a refactoring so that `CsvSource` will use `DataAccessor` to read data as well (like `ParquetSource`)
> 2. move `common/context` into `query`, so that there will be no cross crate circular dependency
>    but keep `TableIOContext` as it is at this stage
> 3. finally,  move `common/dal` into `query/datasource`
> 
> what do you think? @BohuTANG @sundy-li

This refactor will conflict with @sundy-li `copy into` patch, please make sure the roads are clear :smile:

**Comment by sundy-li** [comment]
> shall we move [Csv|ParquetSource] to `query/datasource/table/[csv|parquet] accordingly?

Agree

**Comment by dantengsky** [comment]
> This refactor will conflict with @sundy-li copy into patch(#2682 ?) ...
got it

**Comment by drmingdrmer** [comment]
> I guess it's `common-context` depends on `common-dal`:
> 
> https://github.com/datafuselabs/databend/blob/412834ce5caaef3ae46fd9ddd8d0414755b98699/common/context/Cargo.toml#L16
> 
> Keep `dal` in `common` is ok, there is another question here: If we move `dal` to `query`, `common/context` is no need anymore? It looks a adapter context between `query` and `dal` crate, the codes looks more cleaner. @dantengsky @drmingdrmer

Not quite sure about this.
IOContext was meant to define a minimized API set for methods in Table. DatabendQueryContext is too powerful.

This is up to you guys. It won't bother me.

**Comment by drmingdrmer** [comment]
If in future GC or block-merge tasks will be standalone processes, `dal` would be better a standalone crate.

**Comment by BohuTANG** [comment]
> If in future GC or block-merge tasks will be standalone processes, `dal` would be better a standalone crate.

This is a big point to consider, 服you :+1:

**Comment by BohuTANG** [comment]
As drmingdrmer said above, I think we should skip `move common/context and common/dal into query` this task for now, what do you think @dantengsky

**Comment by dantengsky** [comment]
:D 

GC/Compaction tasks may be standalone processes, but will they be  ... the "databend-query" processes (in a distributed manner)?

or, it would be nice, if those tasks can be "manually assigned",   by using SQLs like ` vacuum t1 ...` or `optimize t1...`, and driven by the same MPP engine.

**Comment by dantengsky** [comment]
> As drmingdrmer said above, I think we should skip move common/context and common/dal into query this task for now, what do you think @dantengsky

I am ok with it, this is not an urgent task.

**Comment by BohuTANG** [comment]
> :D
> 
> GC/Compaction tasks may be standalone processes, but will they be ... the "databend-query" processes (in a distributed manner)?
> 
> or, it would be nice, if those tasks can be "manually assigned", by using SQLs like ` vacuum t1 ...` or `optimize t1...`, and driven by the same MPP engine.

Yes, this is in databend-query side operated by manual.
If move `dal` to `query`, it will hard come back to common :cry:

**Comment by BohuTANG** [comment]
Thank you all @drmingdrmer @dantengsky

**Comment by dantengsky** [comment]
shall we close this issue  @BohuTANG

**Comment by dantengsky** [comment]
mission abort :)
