### ISSUE TITLE
consider re-use `common::streams::ParquetSource` in fuse table 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#2807]
**Summary**

`ParquetSource` read parquet file in as DataBlock

https://github.com/datafuselabs/databend/blob/8b480244305cffe8e64e1d15c25091dc8214cb19/common/streams/src/sources/source_parquet.rs#L70-L74

It will be better to replace `block_reader::do_read`  with the `ParquetSource` in `FuseTable::do_read`
https://github.com/datafuselabs/databend/blob/f86c34b49d9e1620c1214eb3f6a3caffcd13f585/query/src/datasources/table/fuse/io/block_reader.rs#L59-L66

https://github.com/datafuselabs/databend/blob/12e4bb0f29b44873ffa3a48f6c0f3f346b7695f9/query/src/datasources/table/fuse/read.rs#L70-L72

**Comment by dantengsky** [comment]
@Veeupup 
hi, there will likely be some merge conflicts here, since fixing issue #2835 needs to move `source_parquet.rs` around.
hope that will not bring too much inconvenience to you

**Comment by Veeupup** [comment]
@dantengsky got it. It seems not that urgent to fix this issue now, I will try to fix it after #2835  is finished.

**Comment by dantengsky** [comment]
@Veeupup issue #2835 has been closed/canceled, please do not take it into account anymore
