### ISSUE TITLE
Role Management

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2815]
**Summary**

Databend uses roles to control access to objects as:
* Roles are granted access privileges for objects in the system (databases, tables, etc.).
* Roles are granted to users to enable them to create, modify, and use the objects for which the roles have privileges.
* Roles can be granted to other roles to support defining hierarchical access privileges. (we can support it later)

Tasks:
- [x] #2816
      - `create role myrole`
- [x] #2819
      - `grant select,insert on database db1 to role myrole`
- [x] #2818
- [ ] ALTER ROLE [ IF EXISTS ] <name> RENAME TO <new_name>
- [x] DROP ROLE [ IF EXISTS ] \<name\>
- [x] #4392

Reference:
https://docs.snowflake.com/en/sql-reference/ddl-user-security.html#role-management
https://dev.mysql.com/doc/refman/8.0/en/roles.html

**Comment by flaneur2020** [comment]
could i take this issue? i'd make some investigation on the RBAC system

**Comment by BohuTANG** [comment]
> could i take this issue? i'd make some investigation on the RBAC system

Absolutely!

**Comment by flaneur2020** [comment]
before working on RBAC, the fine grained privileges on database or tables might be a prelude: https://github.com/datafuselabs/databend/issues/2894

**Comment by Xuanwo** [comment]
Most work on this issue have been done. Let's close.
