### ISSUE TITLE
Flaky test: servers::http::v1::http_query_handlers_test::test_async

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2828]
```
---- servers::http::v1::http_query_handlers_test::test_async stdout ----
thread 'servers::http::v1::http_query_handlers_test::test_async' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<0
>3
```

https://github.com/datafuselabs/databend/runs/4228310126?check_suite_focus=true
https://github.com/datafuselabs/databend/actions/runs/1468058672

**Comment by BohuTANG** [comment]
@youngsofun may interested in this :)

**Comment by youngsofun** [comment]
@BohuTANG roger thanks！

**Comment by youngsofun** [comment]
@drmingdrmer how many times have you seen this test_fail,  no club for now, is it blocking you pr?

**Comment by drmingdrmer** [comment]
The odds are not high. I saw it only once. It does not block. Running the CI it passed.
