### ISSUE TITLE
sum on fuse engine  make databend crash 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#2837]
**Summary**
select sum(no_first_col)  on table ,  server will be crash .

mysql> select sum(b) from t2;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: wubx

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: wubx

ERROR 2013 (HY000): Lost connection to MySQL server during query

**How to reproduce**

create table t2(a int, b int, c int) engine = fuse;

insert into t2 values(1,1,1), (2,2,2),(3,3,3);

mysql> select * from t2;
+------+------+------+
| a    | b    | c    |
+------+------+------+
|    1 |    1 |    1 |
|    2 |    2 |    2 |
|    3 |    3 |    3 |
+------+------+------+
3 rows in set (0.02 sec)
Read 3 rows, 36 B in 0.008 sec., 385.73 rows/sec., 4.63 KB/sec.

#select sum on first col is ok 
mysql> select sum(a) from t2;
+--------+
| sum(a) |
+--------+
|      6 |
+--------+
1 row in set (0.02 sec)
Read 3 rows, 12 B in 0.008 sec., 397.08 rows/sec., 1.59 KB/sec.

#select sum on other col will be crash server
mysql> select sum(b) from t2;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8

**Error message and/or stacktrace**

mysql> select * from system.tracing where level=50 limit 5;

+------+----------------+----------------------------------------------------------------------------------------------------------------+-------+---------------+-------+----------------------------------+
| v    | name           | msg                                                                                                            | level | hostname      | pid   | time                             |
+------+----------------+----------------------------------------------------------------------------------------------------------------+-------+---------------+-------+----------------------------------+
|    0 | databend-query | panicked at 'crash me function', common/functions/src/scalars/udfs/crash_me.rs:63:9                            |    50 | 192.168.1.5   | 89508 | 2021-11-09T06:32:13.341278+00:00 |
|    0 | databend-query | panicked at 'index out of bounds: the len is 1 but the index is 1', common/datablocks/src/data_block.rs:104:17 |    50 | 192.168.1.5   |  6857 | 2021-11-17T01:45:00.691876+00:00 |
|    0 | databend-query | panicked at 'index out of bounds: the len is 1 but the index is 1', common/datablocks/src/data_block.rs:104:17 |    50 | 192.168.1.5   |  6857 | 2021-11-17T01:47:02.135675+00:00 |
|    0 | databend-query | panicked at 'index out of bounds: the len is 1 but the index is 1', common/datablocks/src/data_block.rs:104:17 |    50 | 192.168.1.5   |  6857 | 2021-11-17T01:50:58.080872+00:00 |
|    0 | databend-query | panicked at 'crash me function', common/functions/src/scalars/udfs/crash_me.rs:63:9                            |    50 | wubx-pc.local | 11211 | 2021-11-17T01:55:42.704620+00:00 |
+------+----------------+----------------------------------------------------------------------------------------------------------------+-------+---------------+-------+----------------------------------+
5 rows in set (0.01 sec)
Read 5 rows, 1.38 KB in 0.006 sec., 824.88 rows/sec., 227.67 KB/sec.

**Additional context**

This crash about fuse engine.

**Comment by sundy-li** [comment]
The latest version seems did not panic, but got:
```

mysql>  select sum(b) from t2;
+--------+
| sum(b) |
+--------+
|   NULL |
+--------+
1 row in set (0.03 sec)
```
