### ISSUE TITLE
Execution of “create database system” succeeded

### ISSUE THREAD

**Issue by miamia0** [datafuselabs/databend#2860]
**Summary**

I tried to create a database with the same name as the system database, but it was successfully created. 

**How to reproduce**

**Error message and/or stacktrace**

![image](https://user-images.githubusercontent.com/25542995/142237058-386b1765-3020-46fe-a504-aba53ba395ff.png)
![image](https://user-images.githubusercontent.com/25542995/142241305-7fd32464-2e11-4fbb-a46a-25243b970ef8.png)

[How to get the server logs](https://databend.rs/development/how-to-get-server-logs/)

**Additional context**

**Comment by BohuTANG** [comment]
This is a bug here:
https://github.com/datafuselabs/databend/blob/9c2e1d606688bbac5134eaaee33dfb3b798dfb8d/query/src/catalogs/impls/catalog/overlaid_catalog.rs#L189-L195

For the catalog, it has two layers: 1) upper layer is read-only, such as system database and 2) bottom layer for the user's database, they are defined here:
https://github.com/datafuselabs/databend/blob/9c2e1d606688bbac5134eaaee33dfb3b798dfb8d/query/src/catalogs/impls/catalog/overlaid_catalog.rs#L44-L51

To create a database, we should check if it exists in the upper layer first.
