### ISSUE TITLE
Export metrics to json

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2864]
**Summary**

Databend using [metrics](https://github.com/metrics-rs/metrics) to collect metrics in the server side, we sitll need a json exporter, not sure the https://github.com/metrics-rs/metrics/tree/main/metrics-exporter-tcp is suite for that or not.

**Comment by BohuTANG** [comment]
It seems that the metrics can do it since we have a query id(UUID) label, we can print the log to file and filter by the [vector](https://github.com/vectordotdev/vector)

**Comment by BohuTANG** [comment]
tracing subscriber is another way

**Comment by BohuTANG** [comment]
Another way is to add a self-host metrics table: https://github.com/datafuselabs/databend/issues/2868

**Comment by flaneur2020** [comment]
is it possible to record the query history inside a system table? 🤔

like: https://clickhouse.com/docs/en/operations/system-tables/query_log/

**Comment by BohuTANG** [comment]
> is it possible to record the query history inside a system table? thinking
> 
> like: https://clickhouse.com/docs/en/operations/system-tables/query_log/

Please see #2868
