### ISSUE TITLE
Proposal: Add DalContext to `dal` crate

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2869]
This issue should be considered a continuation of this issue [How binding session with dal request? ](https://github.com/datafuselabs/databend/issues/2766)

## Background 

Just re-think this issue again, it's very helpful for us to impl  #2868 
Now the biggest problem is:
how can we get the object(such as metrics) from the dal or others `who` is outside the `query` crate?

Just throw some ideas here:
1. Each crate such as `dal` should have his own context to track of the object whole life time
2. We can get the `context` and his object metrics from the `query` crate 

For example:
* Create a `DalContext` in `common/context`,  structs like
``` 
pub struct DalContext {
pub metrics: Metrics
...other fields if need...
}

impl DalContext {
   pub fn add_metrics(..) ...
   pub fn get_metrics()
}
```
* When `Dal` creates we should give a `DalContext` in `query` crate, and bind the context to the session
* Each `Dal` objects bind with the `DalContext`, and update the metrics with `ctx.add_metrics()` if they need
* `query` crate get the from ctx.get_metrics()

## Advantage

The advantage is that we can link these `crate`s through a context and we can do more things like metrics or others

## What needs to change
* `dal` crate needs to bind his context to each object

**Comment by BohuTANG** [comment]
@dantengsky @drmingdrmer @zhang2014 @sundy-li Comments and suggestions are most welcome

**Comment by dantengsky** [comment]
> how can we get the object(such as metrics) from the dal or others who is outside the query crate?

can we solve this by labeling metrics with something like `source' or `component_tag`?

```
pub struct DalContext {
pub metrics: Metrics
...other fields if need...
}
```

is `Metrics` something like 

```
struct Metrics {
   xxx_hist: Histogram,
   xxx_counter: Counter,
   xxx_guage: Guage,
...
}
```

**Comment by BohuTANG** [comment]
> > how can we get the object(such as metrics) from the dal or others who is outside the query crate?
> 
> can we solve this by labeling metrics with something like `source` or `component_tag`?
> 
> > ```
> > pub struct DalContext {
> > pub metrics: Metrics
> > ...other fields if need...
> > }
> > ```
> 
> is `Metrics` something like
> 
> ```
> struct Metrics {
>    xxx_hist: Histogram,
>    xxx_counter: Counter,
>    xxx_guage: Guage,
> ...
> }
> ```

`metrics` only one of our requirements, such as we want introduce a `throttle`(such as how often for a s3 get/put) for the `dal` later, we can configure or setting for a tenant from the `query` crate.

`metrics` crate can not solve our problem is that:
if we add a uuid query_id, it will keep as a key in his internal, it will cause OOM as the queries grow.
`metrics` design for the aggregated metric or the monitor not the query history.

**Comment by dantengsky** [comment]
oh, I should have taken a look at `system.tenant_metrics`

seems the responsibilities could be separated without introducing `DalContext`, rough idea:

assuming `metrics` and `throttle` things are inside the `query` crate, and take the responsibilities of recording metrics r logging (passively).
- move `common/dal/metrics` back to  crate `query`, so that the above components can be accessed by DalWithMetrics
- `DalWithMetrics` reports to the above components while intercepting the operations of the real underlying/wrapped Dal
- `system.tenant_metrics` fetch data from metrics/loggers (but do not touch Dal or DalContext)

but the above idea depends on what are we supposed to intercept, for `get/put`, it is ok; but for things inside the `get/put`, it not gonna work(currently)

**Comment by BohuTANG** [comment]
I still perfer to introduce a context for tracking, like we are doing in query `QueryContext`, it looks more cleaner.

```
pub struct DalContext {
 pub    throttle: Arc<RwLock<Throttle>>,
 pub    metrics: Arc<RwLock<Metrics>>,
 ....
}
```

When to create a context and bind to the session:
In query crate when a session created:
```
let dal_ctx = DalContext::new(...)
session.set_dal_ctx(dal_ctx);
let dal_accessor = DalAccessor::new(dal_ctx);
...
```

When setting a throttle from sql:
```
set throttle.requests = 100;
```

in the setting interepter:
```
session.dal_ctx.throttle.request_update(100)
...
```

This looks like we have the whole link open and can do processing at object level.

**Comment by dantengsky** [comment]
Thanks for clarifying, it does help, especially the `SettingInterpreter` part.

`DalContext` does make sense

Few questions and suggestions:


- are `Throttle` and `Metrics` supposed to be `query` specific concepts?  
   if it does, we have to move at least `common/dal/metric` to `query` (and rename it)
-  if functionalities of throttling and metrics can be implemented as an interceptor of a given instance of `DataAccessor`, then 
    - trait `DataAccessor` need not depend on `DALContext`
    - implementations for storage services(S3, AzureBlob) need not depend on `DALContext`
    - implementations as interceptors, such like `DalWithMetric` shall depend on `DALContext`
    
suggestion:

 - rename `DalWithMetric` to something like ... `DalInterceptor`, give it a new constructor, sth like:

 `pub fn new(tenant_label: TenantLabel, da: Arc<dyn DataAccessor>, dal_ctx: DalContext) -> DalWithMetric`

 - if `DalContext` will contains `query` specific concept, move `DalWithMetric` into `query` (and the `DataAccessorBuilder`, `InputStreamWithMetric`)

**Comment by BohuTANG** [comment]
Thank you for suggesstion! 

> Thanks for clarifying, it does help, especially the `SettingInterpreter` part.
> 
> `DalContext` does make sense
> 
> Few questions and suggestions:
> 
> * are `Throttle` and `Metrics` supposed to be `query` specific concepts?
>   if it does, we have to move at least `common/dal/metric` to `query` (and rename it)

If we add DalContext with our metrics spec, the `metrics` crate should be removed from `dal` crate here, we no need them anymore.
We initially wanted to use this for query log history and for billing, but it is currently not meeting our demand, the reason I have talked above, please correct me if i miss something :) 

> * if functionalities of throttling and metrics can be implemented as an interceptor of a given instance of `DataAccessor`, then
>   
>   * trait `DataAccessor` need not depend on `DALContext`
>   * implementations for storage services(S3, AzureBlob) need not depend on `DALContext`
>   * implementations as interceptors, such like `DalWithMetric` shall depend on `DALContext`

:+1: 
My mistake here, some place no need the context indeed, if so we can ignore them here.

> 
> suggestion:
> 
> * rename `DalWithMetric` to something like ... `DalInterceptor`, give it a new constructor, sth like:
> 
> `pub fn new(tenant_label: TenantLabel, da: Arc<dyn DataAccessor>, dal_ctx: DalContext) -> DalWithMetric`
> 
> * if `DalContext` will contains `query` specific concept, move `DalWithMetric` into `query` (and the `DataAccessorBuilder`, `InputStreamWithMetric`)

The suggestions are helpful, the metrics will undo.

The final consensus we reached was that we agreed to add the `DalContext` to do that :100:

**Comment by BohuTANG** [comment]
Going a little deeper into this discussion, we might merge the `TableIOContext` into the `DalContext`

**Comment by dantengsky** [comment]
> Going a little deeper into this discussion, we might merge the `TableIOContext` into the `DalContext`
I am not how to merge them.
 @drmingdrmer may have suggestions about this.

**Comment by BohuTANG** [comment]
> > Going a little deeper into this discussion, we might merge the `TableIOContext` into the `DalContext`
> 
> I am not sure how to merge them. @drmingdrmer may have suggestions about this.

Sorry, ignore them, they are different Context and with no overlap fields.

**Comment by drmingdrmer** [comment]
What about leaving DAL-interceptor outside `query`?
The interceptor should only define how to report metrics.
How to store and use the metrics is not part of its job.

crate `dal`:
```rust
trait DALContext {
  fn add_metrics(&self, stat: u64);
  fn get_throttle(&self) -> u64;
}

struct DalInterceptor {
   ctx: Arc<dyn DALContext>,
   inner: Arc<dyn DataAccessor>,
}

impl DataAccessor for DalInterceptor {
  fn get(&self) {
    if self.get_throttle() <= 0 { return; }
    self.inner.get();
    self.ctx.add_metrics();
  }
}
```

crate `query`:
```rust
struct DALContextImpl {
    tenant_label: String,
}
impl DALContext<DALContextImpl> for DALContextImpl {
  fn add_metrics(&self, stat: u64) {
    update(self.tenant_label, stat)
  }
}
```

**Comment by drmingdrmer** [comment]
BTW, `common/stream` depends on `dal`, thus `common/stream` has to depend on `DALContext`.

**Comment by BohuTANG** [comment]
Proposal commit to entry log, closed
