### ISSUE TITLE
In `query`, `force shutdown` won't work

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2870]
Looks like there is a different issue with `query`, `force shutdown` won't work:
- `shutdown` takes a `&mut self`, it can be called only once before it returns.
- And graceful shutdown blocks for ever, if a graceful shutdown did not finish, there is no way to call it again with `graceful=false`, to trigger a force shutdown.

https://github.com/datafuselabs/databend/blob/76eb8624b005a29a0abc3ebbb43e5a690dc47140/query/src/servers/server.rs#L61-L69

```rust
    async fn shutdown_services(&mut self, graceful: bool) {
        let mut shutdown_jobs = vec![];
        for service in &mut self.services {
            shutdown_jobs.push(service.shutdown(graceful));
        }
        futures::future::join_all(shutdown_jobs).await;
    }
```

```rust
// service.shutdown:
    async fn shutdown(&mut self, graceful: bool) {
        self.shutdown_handler.shutdown(graceful).await;
    }
```

```rust
// shutdown_handler.shutdown:
    pub async fn shutdown(&mut self, graceful: bool) {
        if graceful {
            if let Some(abort_handle) = self.abort_handle.take() {
                let _ = abort_handle.send(());
            }
            if let Some(join_handle) = self.join_handle.take() {
                if let Err(error) = join_handle.await {
                    log::error!(
                        "Unexpected error during shutdown Http Server {}. cause {}",
                        self.service_name,
                        error
                    );
                }
            }
        } else if let Some(join_handle) = self.join_handle.take() {
            join_handle.abort();
        }
    }
```

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/pull/2858#issuecomment-972548930_

**Comment by BohuTANG** [comment]
I think this issue can be closed? @drmingdrmer

**Comment by sunisdown** [comment]
I haven't had my Laptop device to write code on lately and won't be able to pick this up until the new Mac Studio is delivered to me. sorrrrry

**Comment by zhang2014** [comment]
It cannot be reproduce in the main branch. let's close this issue : )
