### ISSUE TITLE
Add DalContext to dal crate

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2872]
**Summary**

Task
- [x] #2873
- [x] #2884
- [x] #2874
- [x] #2875 

Reference:
#2869

**Comment by drmingdrmer** [comment]
Does this issue need an update? 

DalContext was moved into crate `query` by your last PR and for now it seems there is no way to move metrics reporting out of crate `dal`.

**Comment by BohuTANG** [comment]
> Does this issue need an update?
> 
> DalContext was moved into crate `query` by your last PR and for now it seems there is no way to move metrics reporting out of crate `dal`.

In query/session/context.rs, add a new method will do it:
```
   /// Get the dal metrics.
    pub fn get_dal_metrics(&self) ->  DalMetrics{
        self.shared.dal_ctx.get_metrics().clone()
    }
```

**Comment by drmingdrmer** [comment]
> > Does this issue need an update?
> > DalContext was moved into crate `query` by your last PR and for now it seems there is no way to move metrics reporting out of crate `dal`.
> 
> In query/session/context.rs, add a new method will do it:
> 
> ```
>    /// Get the dal metrics.
>     pub fn get_dal_metrics(&self) ->  DalMetrics{
>         self.shared.dal_ctx.get_metrics().clone()
>     }
> ```

Hm...
Comprehensive and reasonable. 🤔
