### ISSUE TITLE
Make databend-test work in docker-compose node

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2877]
**Summary**

Description for this feature.

Currently `databend-test` depends on

1.   python env
2.  1-N `databend-query` processors
3.  1-N `databend-meta` processors
4.  Mocked s3/azure env like [minio](https://github.com/minio/minio) to simulate cloud services
5.  aws/azure cmd cli ...
5.   .... in the future

So it's better to migrate the testing tools into `docker-compose`  files to prepare the env.

`dev_setup.sh` is good to set up development env, but for testing, I think it may be not enough.

**Comment by ZhiHanZ** [comment]
I think we do not need to maintain another Infrastructure, kubernetes could do the same job with no dependencies, except some small cluster such as k3d or minikube + kubectl.
