### ISSUE TITLE
Developers can assign themselves by using `/assignme` and `/assign`

### ISSUE THREAD

**Issue by jackwener** [datafuselabs/databend#2890]
**Summary**

Now, Developers only can assign themselves by using `/assignme`. It would be better to use `/assignme` and `/assign` simultaneously.

I can't find key word `assignme` in dir of `.github`.

**Comment by jackwener** [comment]
It's a little problem, but it's can reduce the useless comment due to mistaking command `/assign`.

**Comment by ZhiHanZ** [comment]
I think it is related to https://github.com/datafuselabs/fusebots, and feel free to open a PR ：）
