### ISSUE TITLE
Support create/describe stage

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2900]
**Summary**

Description for this feature.

Support create/describe stage.

`Stage` is a special table with some specific storage config.

We can upload files into the stage or unload the data from tables into files in the stage.

Refer to snowflake's stage doc: https://docs.snowflake.com/en/sql-reference/sql/create-stage.html

Firstly we implement the first stage command like:
```

CREATE [ OR REPLACE ]  STAGE [ IF NOT EXISTS ] <stage_name>
  stage_params
  [ FILE_FORMAT = ( FORMAT =  {CSV | JSON | PARQUET} [ formatOptions ] ) } ]
  [ COMMENT = '<string_literal>' ]
  
  stage_params ::= 
  -- for S3 currently
	URL = 's3://<bucket>[/<path>/]'
	ACCESS_KEY_ID='<string_literal>'
	AECRET_ACCESS_KEY='<string_literal>'
	
  formatOptions ::= 
  -- If TYPE = CSV
  	COMPRESSION = AUTO | GZIP | BZ2 | BROTLI | ZSTD | DEFLATE | RAW_DEFLATE | NONE
     	RECORD_DELIMITER = '<character>' | NONE
  -- If TYPE = Parquet
	COMPRESSION = AUTO | LZO | SNAPPY | NONE

```

**Comment by sundy-li** [comment]
@GrapeBaBa 
Hi, did you still work on this? I would like to continue it myself before releasing v0.6.

**Comment by GrapeBaBa** [comment]
@sundy-li I think I can finish it by the end of this week. If it is not ok, you can take it.

**Comment by sundy-li** [comment]
Ok, I'll wait for it, feel free to submit a draft pr then I'll try to collaborate with you.

**Comment by GrapeBaBa** [comment]
> Ok, I'll wait for it, feel free to submit a draft pr then I'll try to collaborate with you.

@sundy-li need one more day to add tests
