### ISSUE TITLE
Add unit tests for sessions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2920]
**Summary**

https://github.com/datafuselabs/databend/tree/ac2164eac76b6c3c12d694127fc5d47f25b96000/query/src/sessions

**Comment by miamia0** [comment]
hi, I'd like to take this issue, but it may take a week or two. Is that ok? (*^▽^*)

**Comment by BohuTANG** [comment]
> hi, I'd like to take this issue, but it may take a week or two. Is that ok? (_^▽^_)

Welcome, thank you @miamia0

**Comment by Xuanwo** [comment]
Hi @miamia0, any updates here? Do you need some help?

**Comment by miamia0** [comment]
> Hi @miamia0, any updates here? Do you need some help?

@Xuanwo sorry I missed the message _(:з」∠)_,  I've been busy in school recently,  I'll come back in July to continue fixing this issue, if it is Ok.

**Comment by Xuanwo** [comment]
> I'll come back in July to continue fixing this issue, if it is Ok.

We are always welcome for any contribution!

I will remove the assignment first so that:

- Others who are interested in this issue can take part in
- You can come back as your wish without any burden :love_letter:

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/tree/main/src/query/service/tests/it/sessions
