### ISSUE TITLE
Proposal: Change the catalog to two parts: ImmutableCatalog and MutableCatalog

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2925]
**Summary**

## Background

Now, the catelog has two catagory:
* upper layer: this is readonly layer, now only one `system` database, we can not register another one, such as `information_schema` database
* bottom layer: this is metastore hosted layer, user can create/drop database/table, for now it's only one type:MetaCatalog, all the Catalog trait is following the MetaCatalog logic, we can not register another one like `github` database to it.

This makes the catalog is more flexible, a user case is:https://github.com/datafuselabs/databend/pull/2897#issuecomment-974612473

## Proposal

Change the catalog to two parts:
* ImmutableCatalog: a read-only type database catalog collection, like `system` and `information_schema` etc system who requires the read-only can be registered to the ImmutableCatalog
* MutableCatalog: a self-host type database catalog collection, like `fuse type database` and `github type database` can be registered to the MutableCatalog

**Comment by BohuTANG** [comment]
The whole work seems to bring back the `database` trait...

**Comment by dantengsky** [comment]
spiral evolution？
