### ISSUE TITLE
Improve databend-test

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#2937]
**Summary**

Description for this improvement.

`databend-test` is a very useful testing tool based on the idea and codes of `clickhouse-test`.
Now it's time for us to improve it.

- [x] refactor `databend-test` codes to be more OOD (TestSuit, TestCase, TestResult).
- [x] support python jinja template to generate SQL and results.
- [x] support test tags

**Comment by sundy-li** [comment]
BTW I think It's ok to refactor `databend-test` into rust.

**Comment by BohuTANG** [comment]
> BTW I think It's ok to refactor `databend-test` into rust. But it'll make build a little bit slower.

Agree!

**Comment by ZhiHanZ** [comment]
I think this issue could be closed, since new test framework is finished?
