### ISSUE TITLE
Proposal: introducing table functions that export fuse table meta

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#2946]
**Summary**

introducing system table functions, which export fuse table's segment/block metadata 

The "semantics" of this function:
- grab a snapshot of the given table `db_name.tbl_name` (by using catalog)
- list all the segment infors of the given table
  
<del>about the schema of resultset, use `DataType::Struct` for nested data structure and  `Struct::List` for map.</del>
EDIT: let's start what flatten table first

later
-  we may use the above function(s) to verify the effect of compaction/GC
-  or even, as the upstream datasource of the distributed GC pipeline

------------

- [x] #3301

**Comment by Veeupup** [comment]
maybe with HTTP api to return `json` result with segments statistics will be more clear ? Because fuse meta data will have some complicated nested structure which can be described by nested `json`. @dantengsky

**Comment by dantengsky** [comment]
addressed by PR #3301
