### ISSUE TITLE
OpenTelemetry: use of rust's tracing ecosystem

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#295]
**Summary**

Use of Rust's tracing ecosystem to tracing events to Jaeger for distributed request correlation.
1. tracing crate https://docs.rs/tracing/0.1.25/tracing/index.html
2. opentelemetry crate https://docs.rs/opentelemetry/0.13.0/opentelemetry/index.html

**Comment by hulunbier** [comment]
3. https://github.com/tikv/minitrace-rust  calims to be **high-performance, ergonomic**

**Comment by BohuTANG** [comment]
@hulunbier 

Thanks for the reminder.
We will not use it in the hot path(such as compute function), only for some gerenal case tracing.
minitrace-rust cool, one of the options.
