### ISSUE TITLE
'select * from system.processes'  deadlock

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#2963]
**Summary**

**How to reproduce**

```select * from system.processes```

**Error message and/or stacktrace**

block forever

**Additional context**

the reason seems to be lock mutable_state twice:

the query does using DatabendQueryContextShared.runtime to run.
when getting ProcessInfo of current session with mutable_state locked,  a runtime is created.  mutable_state is lock again in get_settings.

```

pub fn process_info(self: &Arc<Self>) -> ProcessInfo {
    let session_mutable_state = self.mutable_state.lock();   // <--- 1st lock
    self.to_process_info(&session_mutable_state)
}


fn to_process_info(self: &Arc<Self>, status: &MutableStatus) -> ProcessInfo {
    if let Some(shared) = &status.context_shared {
        if let Ok(runtime) = shared.try_get_runtime() {
          …
        }
    }
}

pub fn try_get_runtime(&self) -> Result<Arc<Runtime>> {
    let mut query_runtime = self.runtime.write();

    match &*query_runtime {
        Some(query_runtime) => Ok(query_runtime.clone()),
        None => {
            let settings = self.get_settings();
        }
    }


pub fn get_settings(self: &Arc<Self>) -> Arc<Settings> {
    self.mutable_state.lock().session_settings.clone(). // <-- second lock
}

```

is it suitable to bypass the current session which is running  "select * from system.processes"?

**Comment by sunisdown** [comment]
> is it suitable to bypass the current session which is running "select * from system.processes"?

I prefer to show the process for current session. When we execute this query, current process executing the query is also part of the processlist being queried.

**Comment by youngsofun** [comment]
another choice is to not try to init runtime in "to_process_info()".

**Comment by BohuTANG** [comment]
The problem here is that the same lock is nested in different places and this usage is not recommended.

**Comment by BohuTANG** [comment]
I think there is a deadlock detection somewhere, like:
https://github.com/p-avital/no-deadlocks

**Comment by BohuTANG** [comment]
cc @zhang2014

**Comment by BohuTANG** [comment]
It seems `mutable_state` should change to a `RwLock`, the mutex is risk here

**Comment by BohuTANG** [comment]
This issue has fixed in this PR:https://github.com/datafuselabs/databend/pull/2966

In #2966, We make the MutableStatus as a unit, and the unit has his own get/set operation within the constraints of the RwLock, not constraintsby a global Mutex in the Session, this is a coarse-grained lock.
This is fine-grained vs. coarse-grained on lock, we should always follow the fine-grained way :D
