### ISSUE TITLE
Proposal: Add a `#[serde(default)] ` attribute for `common/meta/types`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2970]
**Summary**

`common/meta/types` crate is a protocol for meta and query talking, if we have already serialized a type on meta and the structure adds a new field, the deserialization may report an error at this point, so suggestion to add a default value for the types.

https://github.com/datafuselabs/databend/blob/8737082bd71e028f2368a453005f576dbdc61ca2/query/src/configs/config_query.rs#L44-L52

**Comment by BohuTANG** [comment]
cc @drmingdrmer , @ZhiHanZ bendctl cli config also need it

**Comment by drmingdrmer** [comment]
LGTM
