### ISSUE TITLE
[feature] github as datasource

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#2975]
Summary
this is the follow-up on #1788 and #2925 , as discussion here https://github.com/datafuselabs/databend/issues/2897#issuecomment-974608050 makes more possibility on github as datasource. 
we can create a database which presents the organizations name, and then this database will have all repos and extended repos as its table.
```sql
mysql> create databse datafuselabs engine=github; -- the database is org name
mysql> use datafuselabs;
```

After creating a database with github engine, we will automatically create the extended table as follows. Fox example, we create the following table for each repo(maybe extended more)
- Each github engine based database will create four tables for each repo
  - [reponame] // such as `databend`
  - [reponame]_issues // such as `databend_issues`
  - [reponame]_prs // such as `databend_prs`
  - [reponame]_comments // such as `databend_comments`

For more details, here are examples of how to use
```sql
mysql> create databse datafuselabs engine=github; -- the database is org name
mysql> use datafuselabs;
mysql> show tables; -- show all the repos info, 
/*
+--------------+
| table     
+--------------+
| databend           * get basic statistical info about this repo
| databend_issues    * get all issues basic info
| databend_prs        * get all prs basic info
| databend_comments   * get all comments in this repo
| fusebots
| fusebots_issues
| fusebots_prs
| fusebots_comments
...
+--------------+
*/
```

1. Repo specified table: Basic info about this repo
```sql
mysql> create databse datafuselabs engine=github; -- the database is org name
mysql> use datafuselabs;
...
mysql> select * from databend; -- basic info only one row
/*
+------------------------+----------+------------+------------+-------------+----------------+-------------------+-------------------+----------------------+
| reposiroty             | language | license    | star_count | forks_count | watchers_count | open_issues_count | subscribers_count | created_at           |
| databend               | Rust     | apache-2.0 |       2530 |         227 |           2530 |               308 |                64 | 2020-10-10T06:04:42Z |
*/
```

2. Get issues infos
> [Issues - GitHub Docs](https://docs.github.com/en/rest/reference/issues#list-repository-issues)
> Note: GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" > endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key.
So here, we will list all issues and pulls in this table. There are basic info about issues.
mysql> select * from databend_issues; -- get all issue info
```sql
/*
+-------------------------+--------------+------------------------------------------
| number  | title                | state | user       | labels     | assigness | comments | 
+-------------------------+--------------+------------------------------------------
| 2968    | "benctl cluster..."  | open  | youngsofun | c-bug      | BohuTang  | 4        |
| 2238    | "byyyyyyyyyyyyr..."  | open  | youngsofun | c-frature  | veeupup   | 4        |
| 1398    | "xxxxxxxxxxxxxr..."  | closed| youngsofun | c-bug      | veeupup   | 4        |
...
*/
```

3. Get pr infos, basic pr infos in this repo.
```sql
mysql> select * from databend_prs; -- get all issue info
/*
+-------------------------+--------------+------------------------------------------
| number  | title                | state | user       | labels | assigness | comments | 
+-------------------------+--------------+------------------------------------------
| 2968    | "benctl cluster..."  | open  | youngsofun | c-bug  | veeupup   | 4        |
| 2238    | "byyyyyyyyyyyyr..."  | open  | youngsofun | c-bug  | veeupup   | 4        |
| 1398    | "xxxxxxxxxxxxxr..."  | closed| youngsofun | c-bug  | veeupup   | 4        |
...
*/
```

4. Get comments, there will be all comments in one repo on issues and pull requests.(maybe too many rows)
```sql
mysql> select * from databend_comments limit 100;
/*
+-------------------------+--------------+--------------------------------------------------------
| related issue  | user      | created_at           | body                       |
+-------------------------+--------------+--------------------------------------------------------
| 3              | BohuTang  | 2020-11-23T07:59:37Z | LGTM, welcome the first contribution.\r\n |
| 1              | BohuTang  | 2021-11-23T07:59:37Z | OK, I won't notify you again about this release, but will get in touch when a new version is available.\n\nIf you change your mind, just re-open this PR and I'll resolve any conflicts on it..\r\n |
| 991            | BohuTang  | 2020-11-23T07:59:37Z | LGTM, welcome the first contribution.\r\n |
| 1972           | BohuTang  | 2020-11-23T07:59:37Z | LGTM, welcome the first contribution.\r\n |
...
*/
```

for now, there will be the above extended table usage in four aspects
welcome disscussions.

**Comment by BohuTANG** [comment]
Like the idea and looking forward to it

**Comment by BohuTANG** [comment]
Feel free to take it away https://github.com/datafuselabs/databend/issues/2936 if needed

**Comment by Veeupup** [comment]
github api has rate limiting https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
> For API requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used. This means that all OAuth applications authorized by a user share the same quota of 5,000 requests per hour when they authenticate with different tokens owned by the same user.
>
> For users that belong to a GitHub Enterprise Cloud account, requests made using an OAuth token to resources owned by the same GitHub Enterprise Cloud account have an increased limit of 15,000 requests per hour.
>
> When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository. For organizations that belong to a GitHub Enterprise Cloud account, this limit is 15,000 requests per hour per repository.
>
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

if we want this feature works good, so we will need user to specify their `GITHUB_TOKEN` or basic OAuth.
