### ISSUE TITLE
Add system.query_log

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2978]
## Summary

`system.query_log` is a read-only in memory table, it stores all the query logs under the schema:

```
mysql> desc query_log;
+---------------------+------------+------+
| Field               | Type       | Null |
+---------------------+------------+------+
| type                | Int8       | NO   |
| tenant_id           | String     | NO   |
| cluster_id          | String     | NO   |
| sql_user            | String     | NO   |
| sql_user_privileges | String     | NO   |
| sql_user_quota      | String     | NO   |
| client_address      | String     | NO   |
| query_id            | String     | NO   |
| query_text          | String     | NO   |
| query_start_time    | DateTime32 | NO   |
| query_end_time      | DateTime32 | NO   |
| written_rows        | UInt64     | NO   |
| written_bytes       | UInt64     | NO   |
| read_rows           | UInt64     | NO   |
| read_bytes          | UInt64     | NO   |
| result_rows         | UInt64     | NO   |
| result_result       | UInt64     | NO   |
| memory_usage        | UInt64     | NO   |
| cpu_usage           | UInt32     | NO   |
| exception_code      | Int32      | NO   |
| exception           | String     | NO   |
| client_info         | String     | NO   |
| current_database    | String     | NO   |
| databases           | String     | NO   |
| columns             | String     | NO   |
| projections         | String     | NO   |
| server_version      | String     | NO   |
+---------------------+------------+------+
```

This issue mainly for the system.query_log implemention,  the data source of the query_log table will be addressed in another issue.

**Comment by BohuTANG** [comment]
cc @ZhiHanZ @flaneur2020 
If some columns needed, feel free to add it ...

**Comment by BohuTANG** [comment]
@SGZW Thank you for taking it

**Comment by BohuTANG** [comment]
Hello,
Any progress on this task? If no progress I'd love to take it and released it in our 0.6 version:D

**Comment by SGZW** [comment]
> Any progress on this task? If no progress I'd love to take it and released it in our 0.6 version:D

I will finish it this week，Is it too late?

**Comment by BohuTANG** [comment]
> > Any progress on this task? If no progress I'd love to take it and released it in our 0.6 version:D
> 
> I will finish it this week，Is it too late?

That's ok, thank you

**Comment by SGZW** [comment]
Is the querylog table bound to the session or a single query process?

**Comment by BohuTANG** [comment]
> Is the querylog table bound to the session or a single query process?

It's a global table as others system table.

**Comment by SGZW** [comment]
> > Is the querylog table bound to the session or a single query process?
> 
> It's a global table as others system table.

thanks
