### ISSUE TITLE
[functions] more functions working with string

### ISSUE THREAD

**Issue by Junnplus** [datafuselabs/databend#3004]
**Summary**

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html

Tasks list:

If you are interested in one or more tasks in this issue, you can comment like: /assignme in the subtask issue  to make this subtask assigned to you.

- [x] #3014
- [x] #3015
- [x] #3016
- [x] #3017
- [x] #3018
- [x] #3019
- [x] #3020
- [x] #3021
- [x] #3022
- [x] #3023
- [x] #3024
- [x] #3025
- [x] #3028
- [x] #3034
- [x] #3041
- [x] #3043
- [x] #3044
- [x] #3011
- [x] #3046
- [x] #3049
- [x] #3051
- [x] #3059
- [x] #3060
- [x] #3010
- [x] #3058
- [x] #3061
- [x] #3064
- [x] #3066
- [x] #3067
- [x] #3074
- [x] #3070
- [x] #3072
- [x] #3075
- [x] #3073
- [x] #3071
- [x] #3069
- [x] #3065
- [x] #3056
- [x] #3055
- [x] #3054
- [x] #3053
- [x] #3052
- [x] #3050
- [x] #3048
- [x] #3047
- [x] #3045
- [x] #3040
- [x] #3039
- [x] #3037
- [x] #3035
- [x] #3033
- [x] #3032
- [x] #3030
- [x] #3012
- [x] #3031
- [x] #3013

Lower Priority:
- [ ] #3062
- [ ] #3063
- [ ] #3042
- [ ] #3026
- [ ] #3057

Ref:
[more functions working with number](https://github.com/datafuselabs/databend/issues/2563)
[How to write scalar functions](https://databend.rs/development/how-to-write-scalar-functions/)

**Comment by Junnplus** [comment]
@sundy-li Help add a `good first issue` label.

**Comment by Xuanwo** [comment]
/assignme LOWER LCASE UPPER UCASE

They are similar functions, so I think it's OK to take them at the same time.

**Comment by zhang2014** [comment]
> /assignme LOWER LCASE UPPER UCASE
> They are similar functions, so I think it's OK to take them at the same time.

I converted them as issues. CC: @Xuanwo

**Comment by Veeupup** [comment]
@sundy-li may pin #3967  on the board and make this unpin?

**Comment by sundy-li** [comment]
This task is almost done! The rest functions will be taken as low priority (We can add them anytime if users need them).
