### ISSUE TITLE
[doc] add `current_user()` document

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#3006]
**Summary**

add `current_user()` in document.

parent issue:

- https://github.com/datafuselabs/databend/issues/2779

related:

- https://github.com/datafuselabs/databend/issues/2994

**Comment by Xuanwo** [comment]
@soyeric128 Can you take a look of this issue?

**Comment by soyeric128** [comment]
Seems that the function has been already documented at https://databend.rs/doc/reference/functions/context-functions/current_user
