### ISSUE TITLE
LCASE() | Synonym for LOWER()

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#3011]

**Comment by Xuanwo** [comment]
/assignme

> Take https://github.com/datafuselabs/databend/issues/3004#issuecomment-977774256 for reference.

**Comment by Xuanwo** [comment]
I'm working on https://github.com/jorgecarleitao/arrow2/issues/635 to add required support in arrow.

Here is the checklist for work on arrow2 side:

- https://github.com/jorgecarleitao/arrow2/pull/641
- Add upper support
