### ISSUE TITLE
FORMAT() | Return a number formatted to specified number of decimal places

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3028]

**Comment by eastfisher** [comment]
In MySQL, FORMAT() is defined as `FORMAT(X,D[,locale])`.

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_format

If no locale is specified, the default is 'en_US' (in fact, it is related to variable @@lc_time_names).

https://dev.mysql.com/doc/refman/8.0/en/locale-support.html

So the questions are:

1. Should we add variable @@lc_time_names first?
2. Should we support all the locale values?

**Comment by sundy-li** [comment]
Let's use `en_US` by default.

And support:
1. `FORMAT(X,D)`
2. `FORMAT(X,D, locale)`

**Comment by sundy-li** [comment]
Just support `en_US` & `zh_CN`, both are commonly used.

**Comment by eastfisher** [comment]
Hi! I have submitted a PR related to this issue. However, some stateless tests are not pass and I don't know why.

test cases in 02_0041 which are not pass:

```
SELECT FORMAT(12332.123456, 4, "en_US");
SELECT FORMAT(12332.123456, 4, "zh_CN");
SELECT FORMAT(12332.123456, 4, "");
SELECT FORMAT(12332.123456, 4, NULL);
```

and the errors:

```
@@ -7,7 +7,7 @@
 NULL
 NULL
 NULL
-12,332.1235
-12,332.1235
-12,332.1235
+ERROR 1105 (HY000) at line 10: Code: 58, displayText = Unknown column en_US.
+ERROR 1105 (HY000) at line 11: Code: 58, displayText = Unknown column zh_CN.
+ERROR 1105 (HY000) at line 12: Code: 58, displayText = Unknown column .
 12,332.1235
```

**Comment by sundy-li** [comment]
Hi, databend currently using single quota for Strings.
`SELECT FORMAT(12332.123456, 4, 'en_US');`
