### ISSUE TITLE
SOUNDS LIKE | Compare sounds

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#3042]

**Comment by neil4dong** [comment]
I noticed SOUNDEX had already been implemented.  
`[expr1 SOUNDS LIKE expr2]
 is the same as [SOUNDEX(expr1) = SOUNDEX(expr2)]`

can I try to implement it?

**Comment by sundy-li** [comment]
> can I try to implement it?

Yes, you can look at  https://github.com/datafuselabs/databend/blob/0130fd131abcd408c99cfa591dff093d7f083d5d/src/query/sql/src/planner/semantic/type_check.rs

**Comment by neil4dong** [comment]
> > can I try to implement it?
> 
> Yes, you can look at https://github.com/datafuselabs/databend/blob/0130fd131abcd408c99cfa591dff093d7f083d5d/src/query/sql/src/planner/semantic/type_check.rs

It looks like we need to modify the parser to extend a new BinaryOperator for "SOUNDS LIKE".

**Comment by BohuTANG** [comment]
Closed by #11043
