### ISSUE TITLE
LOAD_FILE() | Load the named file

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3059]

**Comment by xiaozongyang** [comment]
Hi @sundy-li, I want to make it clear about details of this feature,
1. Do we need support multiple charset encoding? Or just utf-8 is enough
2. Is there a limit about file size? And is there a limit or contract about the extension name of the file?
3. The expected implementation is streaming or batching?
    - streaming: an iterator will be returned, and every time it's called some piece of string will be got, e.g 1KB
    - batching: all bytes of the file will be returned once

**Comment by Xuanwo** [comment]
@xiaozongyang Welcome help review the draft PR: https://github.com/datafuselabs/databend/pull/4170 :laughing:

**Comment by xiaozongyang** [comment]
@BohuTANG @Xuanwo It seems that this issue is duplicated, should I close this it?

**Comment by sundy-li** [comment]
Yes, Let's move to stage style.
