### ISSUE TITLE
[CI] merge CI files for better resource utilization

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#3076]
**Summary**
We could merge CI files to use fewer resources on repeated building process for faster CI speed and less CI machine utilization
1. Merge docker build to one process (currently perf-tool and regular docker are separated)
2. Merge audit processes to one file
3. Merge lint to one file

**Comment by ariesdevil** [comment]
I think we should only run MacOS tests when merging to the main branch, not every time a pull request is made
