### ISSUE TITLE
Continuous Benchmarking

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3084]
**Summary**

DuckDB's benchmarking are very professional here https://duckdb.org/benchmarks/index.html, thanks to DuckDB for providing such a good testing style :D

Follow the style, databend can also integrate tests:
- [x] #3263
- [ ] Provide the hardware(container) for the runner, this can be based on our perf test 
- [ ] Run the runner for each nightly version and collect the results to a database(DuckDB using itself for this result stored)
- [ ] Show the results on the website for each nightly

References:
1. [DuckDB website scripts](https://github.com/duckdb/duckdb-web/tree/master/scripts)
2. [DuckDB benchmark runner](https://github.com/duckdb/duckdb/tree/master/benchmark)

**Comment by ZhiHanZ** [comment]
Possible settings:
* 2 workers (4vCPU + 4Gi RAM) run on cloud to benchmark on a medium size dataset (ontime small is fine for now)
Need to test the following spec
1. test the performance on S3 storage type (COPY， INSERT， aggregation)
2. test the performance on local disk (INSERT, aggregation)

**Comment by sundy-li** [comment]
https://perf.rust-lang.org/

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/databend-perf/ contains [`numbers`](https://github.com/datafuselabs/databend-perf/blob/main/benchmarks/numbers.yaml) and [`ontime`](https://github.com/datafuselabs/databend-perf/blob/main/benchmarks/ontime.yaml) benchmarks, run on a XXXLarge machine, and [collects performance data](https://github.com/datafuselabs/databend-perf/tree/main/collector) for nightly releases.

- [x] Provide the hardware(container) for the runner, this can be based on our perf test 
- [x] Run the runner for each nightly version and collect the results to a database

**Comment by ZhiHanZ** [comment]
I think it could be closed? @BohuTANG
