### ISSUE TITLE
`INSERT INTO a VALUES (-1)` then select returns `0`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3095]
**Summary**

Description for this bug.

**How to reproduce**

```
mysql> CREATE TABLE a (value Int8) engine=Memory;
Query OK, 0 rows affected (0.03 sec)
Read 0 rows, 0 B in 0.017 sec., 0 rows/sec., 0 B/sec.

mysql> INSERT INTO a VALUES (-1);
Query OK, 0 rows affected (0.01 sec)
Read 0 rows, 0 B in 0.001 sec., 0 rows/sec., 0 B/sec.

mysql> select value from a;
+-------+
| value |
+-------+
|     0 |
+-------+
1 row in set (0.02 sec)
Read 1 rows, 1 B in 0.008 sec., 131.76 rows/sec., 131.76 B/sec
```

Server version:
```
[2021-11-25T08:25:54Z INFO  databend_query] DatabendQuery v-0.1.0-74fcdd5-simd(1.57.0-nightly-2021-11-23T04:59:51.298247505+00:00)

```

**Comment by BohuTANG** [comment]
It looks like it's the mysql handler bug, ClickHouse client works well

**Comment by sundy-li** [comment]
After the `sqlparser` `-1` will be formatted as  `- 1`  (a space in the middle), so it failed to parse into an integer.

I'd like to change this into:

`Insert into a values  Vec< Vec<Expr> >  `   ==> `insert into a select    Vec< Vec<Expr> > `

Then we can reuse `insert into select `.

Also we can handle Expr inside the values, eg:  `insert  into a values(now()), (rand())`
