### ISSUE TITLE
Howto use bendctl change databend version?

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#3113]
**Summary**

Today  I want change databend to yestoday version,   so to do like : 

[local] [admin]> package switch v0.5.26-nightly
[ok] ✅ Package switch to v0.5.26-nightly

[local] [admin]> package list
+-----------------+-------------------------------------------------+---------+
| Version         | Path                                            | Current |
+-----------------+-------------------------------------------------+---------+
| v0.5.27-nightly | /Users/wubx/.databend/local/bin/v0.5.27-nightly |         |
| v0.5.26-nightly | /Users/wubx/.databend/local/bin/v0.5.26-nightly |    ✅   |
+-----------------+-------------------------------------------------+---------+
[local] [admin]> quit
Bye

[wubx@192 11:48:47 /Users/wubx]
$ps axu |grep databend
wubx             90198   0.0  0.0 34253868    928 s006  S+   11:48上午   0:00.00 grep databend
wubx             90107   0.0  2.4 36364840 1632600 s006  S    11:44上午   0:17.34 /Users/wubx/.databend/local/bin/v0.5.27-nightly/databend-query
wubx             90106   0.0  0.0 34345760  17528 s006  S    11:44上午   0:00.41 /Users/wubx/.databend/local/bin/v0.5.27-nightly/databend-meta

*but there is found v0.5.27 is running ,  after restart databend as follow*

[wubx@192 11:48:49 /Users/wubx]
$bendctl
[local] [sql]> \admin
Mode switched to admin mode
[local] [admin]> cluster stop
[ok] ⚠ Start to clean up local services
[ok] ⚠ Stopped query service with config in /Users/wubx/.databend/local/configs/local/query_config_0.yaml
[ok] ⚠ Stopped meta service with config in /Users/wubx/.databend/local/configs/local/meta_config_0.yaml
[ok] 🚀 Stopped all services

[local] [admin]> cluster create
[ok] ✅ Databend cluster pre-check passed!
[ok] ✅ Successfully started meta service with rpc endpoint 127.0.0.1:9191
[ok] ✅ Local data would be stored in /Users/wubx/.databend/local/data
[ok] ✅ Successfully started query service.
[ok] ✅ To run queries through bendctl, run: bendctl query 'your SQL'
[ok] ✅ For example: bendctl query 'SELECT sum(number), avg(number) FROM numbers(100)'
[ok] ✅ To process mysql queries, run: mysql -h127.0.0.1 -P3307 -uroot
[ok] ✅ To process clickhouse queries, run: clickhouse client --host 127.0.0.1 --port 9000 --user root
[ok] ✅ To process HTTP REST queries, run: curl --location --request POST '127.0.0.1:8000/v1/statement/' --header 'Content-Type: text/plain' --data-raw 'your SQL'
[local] [admin]> package list
+-----------------+-------------------------------------------------+---------+
| Version         | Path                                            | Current |
+-----------------+-------------------------------------------------+---------+
| v0.5.27-nightly | /Users/wubx/.databend/local/bin/v0.5.27-nightly |    ✅   |
| v0.5.26-nightly | /Users/wubx/.databend/local/bin/v0.5.26-nightly |         |
+-----------------+-------------------------------------------------+---------+

**How to reproduce**

 above

**Comment by BohuTANG** [comment]
```
[local] [admin]> package help
Cannot get subcommand matches: package 

Package manage databend binary releases

USAGE:
    package [SUBCOMMAND]

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    fetch     Fetch the given version binary package
    help      Print this message or the help of the given subcommand(s)
    list      List all the packages
    switch    Switch the active databend to a specified version

```

**Comment by wubx** [comment]
package switch not take  effect
