### ISSUE TITLE
bendctl `version` command request http://127.0.0.1:8080/v1/health

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3117]
**Summary**

```
bohu@thinkpad:~/Downloads$ bendctl 
[local] [sql]> version
[failed] ❌ Query command precheck failed, error Unknown("cannot connect to healthiness probe: http://127.0.0.1:8080/v1/health"), please run `bendctl cluster create` to create a new local cluster or '\admin' switch to the admin mode
```

The command `version` should not check the health here

**Comment by BohuTANG** [comment]
`sql` profile should check the `admin` profile command, and returns the error hint

**Comment by Xuanwo** [comment]
Agreed.  I think we should follow https: //clig.dev/ for our cli design.

**Comment by BohuTANG** [comment]
> Agreed. I think we should follow https://clig.dev/ for our cli design.

Nice guidelines 👍
