### ISSUE TITLE
Server never responds when the queries are sent from client libraries

### ISSUE THREAD

**Issue by suzaku** [datafuselabs/databend#3138]
**Summary**

Description for this bug.

**How to reproduce**

Use client libraries of Go/Python to connect Databend as `clickhouse` or `mysql`.

We can use `pymysql` as an example here, but I have observed similar situation when using the Go standard library.

```python
import pymysql
conn = pymysql.Connection(host='localhost', user='root', port=3307)
c = conn.cursor()
c.execute("SELECT avg(number) FROM numbers(1000000);")
```

**Error message and/or stacktrace**

```
[2021-11-28T06:45:49Z INFO  databend_query::servers::mysql::mysql_handler] MySQL connection coming: Ok(172.17.0.1:64158)
[2021-11-28T06:46:04Z DEBUG databend_query::servers::mysql::mysql_interactive_worker] SELECT avg(number) FROM numbers(1000000);
```

The logs show that Databend has received the query, but it just stops there and seems to be waiting for some kind of event to happen.

If I use the Go standard library which retries every minute I'll observe the following logs:

```
[2021-11-28T06:34:55Z DEBUG common_clickhouse_srv] Handle New session
[2021-11-28T06:34:55Z DEBUG databend_query::servers::clickhouse::interactive_worker_base] SELECT VERSION()

[2021-11-28T06:35:55Z INFO  databend_query::servers::clickhouse::clickhouse_handler] ClickHouse connection coming: Ok(172.17.0.1:55228)
[2021-11-28T06:35:55Z DEBUG common_clickhouse_srv] Handle New session
[2021-11-28T06:35:55Z DEBUG databend_query::servers::clickhouse::interactive_worker_base] SELECT VERSION()



[2021-11-28T06:36:55Z INFO  databend_query::servers::clickhouse::clickhouse_handler] ClickHouse connection coming: Ok(172.17.0.1:55232)
[2021-11-28T06:36:55Z DEBUG common_clickhouse_srv] Handle New session
[2021-11-28T06:36:55Z DEBUG databend_query::servers::clickhouse::interactive_worker_base] SELECT VERSION()
```

**Comment by ZhiHanZ** [comment]
Hi @suzaku , not sure about your  databend version for testing third party clients.
I have tested it manually on my local machine， and pymysql snippet works
Init a single node cluster
```bash
make cluster
# check on cluster healthiness
make cluster_view
```

Run python3 client query
![image](https://user-images.githubusercontent.com/25170437/143767767-9bd076fb-c9f8-481c-a315-e2b8049fbb3c.png)

Client library integration test is very important, which has not been finished yet and there are several issues related to it.
https://github.com/datafuselabs/databend/issues/1766
https://github.com/datafuselabs/databend/issues/1773

feel free to take those part if you are interested :)

**Comment by suzaku** [comment]
The Databend server I connected was started with `docker run --init --rm -p 9001:9001 -p 9191:9191 -p 3307:3307 datafuselabs/databend`.

**Comment by suzaku** [comment]
I would love to help, but it takes too long to compile a Rust project on my laptop and it starts to feel like a waste of time 🤣

**Comment by sundy-li** [comment]
It's true that the first time to build a large rust projection takes a long time.  But it'll be faster for increment building.
On my MacBook pro-2021, it needs 1-2 minutes to `make debug` from zero caches.

Thanks for the report, I'll try to reproduce it from your steps.

**Comment by sundy-li** [comment]
```
docker run --init --rm -p 9001:9001 -p 9191:9191 -p 3307:3307 datafuselabs/databend
```

logs:
```
[2021-11-28T13:12:46Z INFO  databend_query] DatabendQuery v-0.1.0-9533dd1-simd(1.57.0-nightly-2021-10-26T01:51:09.305927968+00:00)
```

Seems the docker image is out of date, is this because we forgot to change the branch from master to main in `databend-docker.yml`? @ZhiHanZ

**Comment by ZhiHanZ** [comment]
please update the docker repo, which should be updated

> ```
> docker run --init --rm -p 9001:9001 -p 9191:9191 -p 3307:3307 datafuselabs/databend
> ```
> 
> logs:
> 
> ```
> [2021-11-28T13:12:46Z INFO  databend_query] DatabendQuery v-0.1.0-9533dd1-simd(1.57.0-nightly-2021-10-26T01:51:09.305927968+00:00)
> ```
> 
> Seems the docker image is out of date, is this because we forgot to change the branch from master to main in `databend-docker.yml`? @ZhiHanZ

please update latest docker repo, which should get updated

**Comment by suzaku** [comment]
Thanks. I'll try later. I guess in most cases, I don't really have to do extra setup to integrate Databend, right? I can just use it like a clickhouse server.

**Comment by ZhiHanZ** [comment]
> Thanks. I'll try later. I guess in most cases, I don't really have to do extra setup to integrate Databend, right? I can just use it like a clickhouse server.

we maintain mysql and clickhouse protocol by default, feel free to open any issues on compatibility part.

**Comment by suzaku** [comment]
Good to know that, thanks.
