### ISSUE TITLE
Document http handler api

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3143]
**Summary**

Document databend HTTP REST API: Methods, Parameters and samples

**Comment by youngsofun** [comment]
@BohuTANG add a file in  https://github.com/datafuselabs/databend/tree/main/website/databend/docs/api?

**Comment by BohuTANG** [comment]
> @BohuTANG add a file in https://github.com/datafuselabs/databend/tree/main/website/databend/docs/api?

Ok
