### ISSUE TITLE
remove unnecessary progress stream in InsertIntoIterprepter

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#3161]
**Summary**

the `ProgressStream` that was created in `InsertIntoIterprepter` seems unnecessary, let's remove it. 

https://github.com/datafuselabs/databend/blob/42494457ef9619412b2937f21e5a20839fcfd77c/query/src/interpreters/interpreter_insert_into.rs#L96-L99

**Comment by sundy-li** [comment]
Why it is unnecessary, seems we need it in  https://github.com/datafuselabs/databend/blob/main/cli/src/cmds/queries/query.rs#L313-L338

**Comment by dantengsky** [comment]
oops, my fault, did not notice that.

I thought it was mistakenly merged by me during resolving conflicts
