### ISSUE TITLE
Numbers in the `u64` range are converted to `Float64`, resulting in loss of precision

### ISSUE THREAD

**Issue by dust1** [datafuselabs/databend#3175]
**Summary**

When I test the `bin` function, and exec it:
```
select bin(13835058055282163712);
select bin(-9223372036854775808);
```
`13835058055282163712` in the range of u64, `-9223372036854775808` in the range of i64;
but in the `DataColumnsWithField`, when i check the DataType, it tell me the data type is `Float64`, and when I checked the values, I found that they did not correspond:
```
13835058055282163712 =>  1.3835058055282164e19 = 13835058055282164000
-9223372036854775808 => -9.223372036854776e18 = -9223372036854776000
```
I am using the `BIGINT` data type in Mysql

**Comment by sundy-li** [comment]
I think it may be the sqlparser parse it as Float number.

```
:) select toTypeName(a) from (select 13835058055282163712 as a);
+---------------+
| toTypeName(a) |
+---------------+
| Float64       |
+---------------+
1 row in set (0.01 sec)
Read 1 rows, 1 B in 0.002 sec., 517.74 rows/sec., 517.74 B/sec.
```

**Comment by dust1** [comment]
> I think it may be the sqlparser parse it as Float number.
> 
> ```
> :) select toTypeName(a) from (select 13835058055282163712 as a);
> +---------------+
> | toTypeName(a) |
> +---------------+
> | Float64       |
> +---------------+
> 1 row in set (0.01 sec)
> Read 1 rows, 1 B in 0.002 sec., 517.74 rows/sec., 517.74 B/sec.
> ```

Is this a problem that should be fixed？

**Comment by sundy-li** [comment]
Yes， need to investigate, maybe you can help it.

**Comment by dust1** [comment]
No problem, this looks like I can do it. I will try
