### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#319]
**Summary**
Initial tasks:
- [ ] join sql parser (almost done, but need to convert to plan)
- [ ] join plan
- [ ] join transform(hash)
- [ ] reshuffle mode
     - [ ]  FuseQuery reshuffle: Reshuffle transform
            1. a unified reshuffle transform that can be used for group-by or others who needs reshuffle
     - [ ]  FuseStorage reshuffle? 
            1. push down a hash expression to storage, like `join_key_a%5=3 AND join_key_b%5=3`
            2. FuseQuery node do local join
            3. FuseQuery do final merge

**Comment by BohuTANG** [comment]
Cool, it's not started yet, welcome RFC

**Comment by leiysky** [comment]
I just wrote a draft proposal #465, welcome to comment.

By the way, I found it's hard to discuss about the detailed part in this RFC. Thus I'm going to write another RFC about implementation of hash join algorithm.

**Comment by BohuTANG** [comment]
021-05-01-join-framework-design.md moved  to website/datafuse/docs/rfcs at #501 
Cc @leiysky

**Comment by Xuanwo** [comment]
Join has been supported, closing.
