### ISSUE TITLE
Make parquet reader works with only one stream reader.

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3225]
**Summary**

Description for this feature.

Currently, we are unable to stream load parquet files into databend since the parquet source need `Dal` to generate streams multiple times(parallel column reading from parquet column need it).

https://github.com/datafuselabs/databend/blob/f3ecaf16b5290fbc26870660efb2b8d059299442/common/streams/src/sources/source_parquet.rs#L101-L118

Sometimes the input stream may come from outside, like HTTP body streaming in 

https://github.com/datafuselabs/databend/blob/f3ecaf16b5290fbc26870660efb2b8d059299442/query/src/servers/http/v1/load.rs#L84-L97

@dantengsky  @jorgecarleitao  any comments to help it are welcome.

**Comment by jorgecarleitao** [comment]
There is an example that I have been using [here](https://github.com/jorgecarleitao/arrow2/tree/main/examples/s3). It has 3 components:

1. something that implements "AsyncRead + AsyncSeek" from an s3 API (using byte-range) with some buffering
2. something that consumes "AsyncRead + AsyncSeek"

"1." is implemented in the example for s3 with the help of an utility struct that I recently published in [crates.io](https://crates.io/crates/range-reader)

"2." arrow2 currently offers such an API for parquet (for non-nested types only)

**Comment by dantengsky** [comment]
there seem to be two things that blocking the way:

1. as you mentioned, `source_parquet.rs` currently read columns parallelly.

    if we are going to decouple `source_parquet` from `DataAccessor` like `source_csv` did, we need some refactoring about it.
    which is feasible imo.
    
2.  as @jorgecarleitao mentioned

   `read_metadata_async` and `get_page_stream` need reader  that implements `AsyncRead + AsyncSeek`.
   
   unfortunately, the reader we could get from `poem` is `AsyncRead` (which is reasonable, seeking around in the HTTP upload stream is not that sensible)
   
https://github.com/datafuselabs/databend/blob/f3ecaf16b5290fbc26870660efb2b8d059299442/query/src/servers/http/v1/load.rs#L85-L87


   As metadata of parquet file is at the end of the file, and reading pages/columns depends on the knowledge of metadata, the parquet format seems not to be a good candidate as CSV to be processed streamingly.
    
   maybe `copy into ...` is more proper for parquet files?

**Comment by Xuanwo** [comment]
@jorgecarleitao Implementing `AsyncRead + AsyncSeek` seems not suitable for storage services like s3 and azblob. I'm wondering if it is possible to remove the dependences on `seek`?

For example:

- We can use `stat` (HeadObject on s3) to get the object size.
- We can use `pread` (GetObject with Range on s3) to get the object content.

In this way, we can have more control over the behavior of underlying storage behavior.

Does this idea look good to you? I'm willing to draft a proposal and implement it for `parquet2`.

**Comment by jorgecarleitao** [comment]
Sorry, I missed the previous comment :/

afaik those two necessary and sufficient to implement `AsyncRead + AsyncSeek`:

* `stat` yields the total file size, which allows `SeekFrom::End` (to reach the file's metadata)
* `pread` is basically `AsyncRead`.

In the example I linked, you have:

* `stat` to get the files' size: https://github.com/jorgecarleitao/arrow2/blob/main/examples/s3/src/main.rs#L18
* `pread` declaring the s3-specific call to create a ranged query from `start` and `length`: https://github.com/jorgecarleitao/arrow2/blob/main/examples/s3/src/main.rs#L22
* using a struct that implements `AsyncRead + AsyncSeek` based on these: https://github.com/jorgecarleitao/arrow2/blob/main/examples/s3/src/main.rs#L42
* using arrow2's to read the metadata using the struct: https://github.com/jorgecarleitao/arrow2/blob/main/examples/s3/src/main.rs#L44

Note that parquet is not a streaming format, but streaming != async: we usually want `async` to read from blob to not block the thread, and streaming to not have to load all data at once (e.g. to apply filter and projection pushdown).

**Comment by Xuanwo** [comment]
> using a struct that implements `AsyncRead + AsyncSeek` based on these: https://github.com/jorgecarleitao/arrow2/blob/main/examples/s3/src/main.rs#L42

I don't quite understand why we still need `AsyncSeek`, can you explain it in more detail? Thanks in advance.

**Comment by jorgecarleitao** [comment]
Ahh, sure: a simplified view of a parquet file is as follows: `[column 1][column 2]...[column N][footer][footer_size as 4 bytes]`

You can think of "column X" as bytes for a given type (e.g. a `Vec<u8>` that can be transmuted to `Vec<i64>`, for a INT64 column).

The physical type of every column is stored in the footer. The position of each column chunk is also stored in the footer. 

Supposed that we want to read a column of the file. We do:

* seek to the end of the file (`file_size - 4`)
* read 4 bytes to get the footer size `footer_size`
* seek to the beginning of the footer (`file_size - 4 - footer_size`)
* read the footer (so, `[file_size - 4 - footer_size, file_size - 4]`)
* deserialize the footer to get the file's schema and position of each column chunk
* seek to the beginning of the column chunk
* read the column to memory
* (decompress+)deserialize the column to the target physical type

You can already see why seek is needed: we need to seek to different positions in the file to read the footer, the columns, etc.

This is a simplification of the parquet format (e.g. no pages nor row groups), but I hope it illustrates the reason for the Seek requirement.
