### ISSUE TITLE
hugeint support

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#3237]
**Summary**
such as int128 and int256

**Comment by l1t1** [comment]
the doc page https://databend.rs/sqlstatement/data-types/data-type-integer-number/

**Comment by Xuanwo** [comment]
Cc @sundy-li, what do you think?

**Comment by sundy-li** [comment]
Yes, it's needed, it will be done after we migrate to new-expression.

**Comment by izaakschroeder** [comment]
Any news on this one? 😄

**Comment by sundy-li** [comment]
We can use `Decimal(38,0)` instead

**Comment by izaakschroeder** [comment]
@sundy-li out of curiosity, what does `Decimal(38,0)` look like internally? Would it have the same performance characteristics of, say, an explicit `INT128` or `INT256` type? And if so, would it make sense to have other int types (e.g. `INT64`) represented by `Decimal(n, 0)` as well?

One potential use case of `INT128` is `uuid` and ipv6 address types for logging HTTP request ids and requester addresses. Is this a sensible use of `Decimal(38,0)`?

**Comment by sundy-li** [comment]
Decimal is using Int128 as its physical value internally.   So for the performance issue, they are almost the same.
