### ISSUE TITLE
Improve `system.functions` 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3258]
**Summary**

```
SELECT * FROM system.functions;
┌─────────────────────┬───────────────┬─────────────┬─────────────┬────────────────────┬─────────────────┬─────────────────┐
│    function_name    │ function_type │ description │ return_type │     parameters     │ parameter_types │ monotonicity    │
├─────────────────────┼───────────────┼─────────────┼─────────────┼────────────────────┼─────────────────┼─────────────────┤
│ numbers_mt          │ table         │ NULL        │ NULL        │ [N]                │ []              │[monotonict json]│
│ log10               │ scalar        │ NULL        │ DOUBLE      │ [col0]             │ [DOUBLE]        │[...]            │
│ sum                 │ aggregate     │ NULL        │ INT64       │ []                 │ []              │[...]            │
└─────────────────────┴───────────────┴─────────────┴─────────────┴────────────────────┴─────────────────┴─────────────────┘
```

This feature requires functions to provide a metadata field trait, such as `function_type`, `description`, `return_type`, `monotonicity`, maybe need some refactors

**Comment by PsiACE** [comment]
/assignme

I would love to do this. It will be broken down into smaller tasks:
- first we need to add all the functions to the table, and get `function_type` , which means a small refactor.
- Then try to add the `descriptions`, for scalar and table functions it might be easy, I'm not sure how to do this without creating aggregate functions.

cc @zhang2014 , I would like to know your opinion, I noticed that we have an `AggregateFunctionDescription` structure

**Comment by BohuTANG** [comment]
@sundy-li have some thoughts on it :)

**Comment by sundy-li** [comment]
Yes, `AggregateFunctionDescription ` is enough to do it, it's not required to create aggregate functions.

**Comment by zhang2014** [comment]
Some functions have different return types when the arguments type are different. such as: `CAST`?

**Comment by BohuTANG** [comment]
> Some functions have different return types when the arguments type are different. such as: `CAST`? Maybe it's hard to get a list of overloads for all functions into this table?

If the return type is dynamic, return N/A is OK.
