### ISSUE TITLE
Improve performance in functions working with String

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3259]
**Summary**

Description of this feature.
Most functions working with String are not optimized well.

1. Unnecessary Extra copy inside the iteration loop.
2. Validity checks which break CPU branch prediction.

cc @mshauneu  may be interested in this.

Refer :

https://github.com/jorgecarleitao/arrow2/pull/651
https://github.com/jorgecarleitao/arrow2/pull/646

**Comment by Veeupup** [comment]
maybe we should add benches for `common/functions` ? so we can bench functions that concerns.

**Comment by BohuTANG** [comment]
> maybe we should add benches for `common/functions` ? so we can bench functions that concerns.

+1
We plan to introduce a `new` benchmark in https://github.com/datafuselabs/databend/issues/3084

If you are interested in it, let's do it.
