### ISSUE TITLE
Benchmark runner

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#3263]

**Comment by ZhiHanZ** [comment]
I think you could take a look at the runner on test-infra

**Comment by ZhiHanZ** [comment]
FYI, the runner controller version is outdated, bump runner version would be nice as well

**Comment by Veeupup** [comment]
It seems test-infra runner can be used for SQL bench? 

here I mean that we could bench for some functions in `common/functions` , such as `aggregate` and `scalars` functions. And now we have benches in `query/benches`, maybe we could combine them( SQL bench, function bench and maybe more performence sensitive components in future) all together in `databend`?

do we need to combine them together ?
cc @sundy-li @BohuTANG

**Comment by ZhiHanZ** [comment]
test-infra could do the following things:
1. Remote build and containerization support
2. provision temporary k8s cluster to compare target commit with reference commit(main, master, other commits etc)
3. upload compare results to S3 repo

perf-tool is another containered wrapper for databend-benchmark binary, it supports:
1. run performance test again given input queries(https://github.com/datafuselabs/databend/blob/main/tests/perfs/perfs.yaml)
2. generate html form reports

**Comment by ZhiHanZ** [comment]
I think we need to finish the following parts for continuous benchmark
1. support to provision eks as the temporary k8s cluster to host query workload
2. run workload on given cluster after each nightly release
3. upload result html to website

**Comment by sundy-li** [comment]
`SQL bench` is enough for database benchmarks.
`query/benches` are aimed to bench unit function benchmark, but it needs to code manually, yet it is hard to cover the performance in SQL's lifetime.

**Comment by PsiACE** [comment]
https://github.com/boa-dev/criterion-compare-action 

We can try to support this action with test-infra

**Comment by BohuTANG** [comment]
For the benchmark and output with a uniform output format, I think https://github.com/datafuselabs/databend/blob/main/query/src/bin/databend-benchmark.rs can do it well.

So, the runner here is that how we run the difference benchmarks with the test-infra, @ZhiHanZ has give some suggestions above.

**Comment by BohuTANG** [comment]
> `SQL bench` is enough for database benchmarks. `query/benches` are aimed to bench unit function benchmark, but it needs to code manually, yet it is hard to cover the performance in SQL's lifetime.

Does the `query/benches` no used anymore? It seems a long time we not run them

**Comment by PsiACE** [comment]
I think this task is obsolete and we now have a working benchmark mechanism.
