### ISSUE TITLE
[CI] concurrency control on workflow for push commits

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#3264]
**Summary**
github action support to kill pending jobs if new job come in to queue, I think it could help us mitigate CI execution pressure if many tasks get merged at the same time.
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

**Comment by Xuanwo** [comment]
The feature is not easy to be used correctly. 

Please take https://github.com/beyondstorage/go-storage/blob/b7ddd274821893274ca546c8ea6492bc8d6f145c/.github/workflows/services-test-s3.yml#L3 as an example.

**Comment by Xuanwo** [comment]
This issue should be fixed by https://github.com/datafuselabs/databend/pull/3344

**Comment by ZhiHanZ** [comment]
I think it is resolved by #3443
