### ISSUE TITLE
Consider remove `pub mod series` from common/datavalues/src/lib.rs

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3266]
**Summary**

Since we have exported them in `common/datavalues/src/prelude.rs`.

**Comment by Veeupup** [comment]
it seems `datavalues/series/series_debug.rs` functions we do not use anymore, we can remove this file?
@BohuTANG

**Comment by BohuTANG** [comment]
> it seems `datavalues/series/series_debug.rs` functions we do not use anymore, we can remove this file? @BohuTANG

cc @sundy-li

**Comment by sundy-li** [comment]
Ok!
