### ISSUE TITLE
reduce aarch64 binary size 

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3268]
**Summary**

Now, we can't use `objcopy` properly to reduce the binary size of the aarch64 build. There are currently two options:

- setup aarch64-unknown-linux-gnu-objcopy, or
- use the `RUSTFLAGS` environment variable when building

**Comment by Xuanwo** [comment]
CI failed for `objcopy: Unable to recognise the format of the input file `./target/aarch64-unknown-linux-gnu/release/databend-benchmark'`

ref: https://github.com/datafuselabs/databend/runs/4428502575?check_suite_focus=true

**Comment by PsiACE** [comment]
> CI failed for:
> 
> ```
> objcopy: Unable to recognise the format of the input file `./target/aarch64-unknown-linux-gnu/release/databend-benchmark'
> ```
> 
> It looks we need some extra work to make objcopy work as expected.
> 
> ref: https://github.com/datafuselabs/databend/runs/4428502575?check_suite_focus=true

fixed by #3272
