### ISSUE TITLE
[refactoring]: rename `fuse/index` to `fuse/pruning`

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#3269]
**Summary**

- rename `fuse/index` to `fuse/pruning`
  since there is also a `storage/index` module, it is a little bit confusing. 
  but @BohuTANG, if merging `storage/index` into `fuse/index` is preferred, pls let me know, I'd like to do the refactorings.
- refactoring of `fuse/statistics`
  cleaning up accumulators and routine functions
- refactoring of `fuse/io`
  cleaning up & some preparations for cache-aware-readers

**Comment by BohuTANG** [comment]
I have deep the draft PR, all looks good to me, thank you @dantengsky
