### ISSUE TITLE
Why don't we use conditional compilation? such as: `cargo features`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3293]
Why don't we use conditional compilation? such as: `cargo features`

_Originally posted by @zhang2014 in https://github.com/datafuselabs/databend/issues/3276#issuecomment-987553234_

**Comment by Xuanwo** [comment]
We are using it now for hive and hdfs. There is no actionable task to take, how about closing this issue?

(Yep, I'm from [I'm feeling lucky](https://link.databend.rs/i-m-feeling-lucky))
