### ISSUE TITLE
And I think it's time to add `transfrom_from_primitive` function.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3304]
I think it's time to add `transfrom_from_primitive` function.

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/pull/3288#pullrequestreview-826481925_

**Comment by Veeupup** [comment]
@sundy-li 
Does `transfrom_from_primitive` is tranform from `PrimitiveArray` to `BinaryArray`?
If so, it seems that we can update the `arrow2` from upstream because your work https://github.com/jorgecarleitao/arrow2/pull/651 , and it will call `primitive_to_binary` then.

**Comment by sundy-li** [comment]
Yes，the first task is to bump up arrow2 dep.

But `primitive_to_binary ` is not enough, we should introduce custom transform lambda Fn.
