### ISSUE TITLE
Add Benchmarks

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#331]
**Summary**

- [x] benches [#412  ]
- [x] nyctaxi [#352 #357 ]
- [ ] tpch
 Like what apache arrow  does:[Apache Arrow Rust Benchmarks](https://github.com/apache/arrow/tree/master/rust/benchmarks)

**Comment by Veeupup** [comment]
@BohuTANG  It seems that [apache-arrow](https://github.com/apache/arrow) now does not have rust benchmarks.

**Comment by Xuanwo** [comment]
The last part has been covered by #6060, closing now.
