### ISSUE TITLE
Add function argument types  pre-check

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#332]
**Summary**

Add function signature, defines the function's supported argument types.
From VectorSQL:
https://github.com/vectorengine/vectorsql/blob/master/src/expressions/expression_validator.go

From datafusion:
```
/// A function's signature, which defines the function's supported argument types.
#[derive(Debug, Clone, PartialEq)]
pub enum Signature {
    /// arbitrary number of arguments of an common type out of a list of valid types
    // A function such as `concat` is `Variadic(vec![DataType::Utf8, DataType::LargeUtf8])`
    Variadic(Vec<DataType>),
    /// arbitrary number of arguments of an arbitrary but equal type
    // A function such as `array` is `VariadicEqual`
    // The first argument decides the type used for coercion
    VariadicEqual,
    /// fixed number of arguments of an arbitrary but equal type out of a list of valid types
    // A function of one argument of f64 is `Uniform(1, vec![DataType::Float64])`
    // A function of one argument of f64 or f32 is `Uniform(1, vec![DataType::Float32, DataType::Float64])`
    Uniform(usize, Vec<DataType>),
    /// exact number of arguments of an exact type
    Exact(Vec<DataType>),
    /// fixed number of arguments of arbitrary types
    Any(usize),
    /// One of a list of signatures
    OneOf(Vec<Signature>),
}
```

**Comment by Xuanwo** [comment]
@sundy-li Do we still need this feature now?

**Comment by sundy-li** [comment]
I think `return_type` already covered this check.

https://github.com/datafuselabs/databend/blob/dc058c9d22baa9e61763661f77cd10ec62c87c48/common/functions/src/scalars/strings/concat.rs#L51-L56

**Comment by Xuanwo** [comment]
Let's close this issue. @sundy-li Feel free to open a new issue if there are place for improvements.

**Comment by sundy-li** [comment]
> Let's close this issue. @sundy-li Feel free to open a new issue if there are place for improvements.

Ok, I think it can be enhanced when [typed-type-exercise-in-rust](https://github.com/andylokandy/typed-type-exercise-in-rust/) is merged into databend  in the future.
