### ISSUE TITLE
CI speed improvement

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3320]
## Summary

The `Push to Dockerhub` workflow is always the slowest.

- Maybe we can use the built binary in other workflows? (with the support of [Upload-Artifact](https://github.com/actions/upload-artifact))
- Maybe we don't need to build and push to dockerhub for every commit in main? How about only building the tagged version?
- Maybe we can push our image to ghci.io instead of dockerhub? (NOTICE: dockerhub require's paid plan to download images that over the limit)?

**Comment by BohuTANG** [comment]
Great, just do it :)

**Comment by flaneur2020** [comment]
> Maybe we don't need to build and push to dockerhub for every commit in main? How about only building the tagged version?

maybe we could make a workflow for both docker and binary release:

```
build binary -> save artifact --> release binary 
                             \--> release docker
```

the built artifact may get reused among the releasing binary or docker steps 🤔

**Comment by Xuanwo** [comment]
This issue has been blocked for GitHub doesn't support sharing artifacts between workflows.

> Downloading files: You can only download artifacts that were uploaded during the same workflow run. When you download a file, you can reference it by name.
>
> Reference: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts

We need to find an another way to meet our needs.

**Comment by Xuanwo** [comment]
Let's refactor into actions instead.
