### ISSUE TITLE
Normalization copyright

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#3333]
**Summary**

The Copyright info should be changed to `Copyright (c) 2020-present, Datafuse Labs.  All rights reserved.`
With this change, we no longer need to change it every year. 2022 coming soon:)

**Comment by BohuTANG** [comment]
`The year in the copyright notice refers to the year of first publication`
https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work

If a new file be created in the year 2022 in the future, it should be 2022.

**Comment by ariesdevil** [comment]
I was reading Facebook’s rocksdb code recently and found that its copyright is in this format. 
So it seems they have the wrong format, just close this issue.
