### ISSUE TITLE
github statistical data visualization

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#3335]
**Summary**

With `github-based` database https://github.com/datafuselabs/databend/pull/3093 finished, we can do something interesting.

We can integrated with grafana and show some statistical data with fancy charts, maybe like what cncf-tiki did.

[cncf-tikv-grafana](https://tikv.devstats.cncf.io/d/19/open-pr-age-by-repository-group?orgId=1)

**Comment by Xuanwo** [comment]
We have removed github database. Let's close.
