### ISSUE TITLE
Can not return the error to the MySQL client

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3345]
**Summary**

https://github.com/datafuselabs/databend/blob/85599e683e22f747dcb02fb12404a9cee0c33afd/query/src/servers/mysql/writers/query_result_writer.rs#L173-L177

This error returns to `msql-srv` will cause panic(unwrap()):
https://github.com/datafuse-extras/msql-srv/blob/master/src/resultset.rs#L183-L187

**Comment by Xuanwo** [comment]
Is this issue still valid?
