### ISSUE TITLE
'root'@'localhost' superuser account for localhost

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3348]
**Summary**

https://github.com/datafuselabs/databend/blob/85599e683e22f747dcb02fb12404a9cee0c33afd/query/src/users/user_mgr.rs#L32-L40

For the user name `default` and `root`, we should check the host is `localhost` or `127.0.0.1`, 'root'@'localhost' superuser account that has all privileges and can do anything.

**Comment by BohuTANG** [comment]
cc @flaneur2020 FYI

**Comment by silathdiir** [comment]
Hi, could I try to fix this issue?

**Comment by BohuTANG** [comment]
@silathdiir Sure, thank you!
