### ISSUE TITLE
Continue to reduce the binary size

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3382]
**Summary**

Now we use `objcopy` or `rustflags` to reduce the binary size, with the `--compress-debug-sections` option.

We need to

1. provide a separate `make` command for size reduction. rather than mixed in the compile phase.
2. further reduce the size of the release: e.g. by using `strip` and `upx`.

Ideally, the size of bendctl will be further reduced by 90%; databend-query and databend-meta will be reduced by 75%.

**Comment by Xuanwo** [comment]
I am not interested anymore. Feel free to take this issue.

**Comment by PsiACE** [comment]
I prefer to close it for now.
