### ISSUE TITLE
Unit test `flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read` failed on macos-11

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3416]
**Summary**

https://github.com/datafuselabs/databend/runs/4502135708?check_suite_focus=true

**Comment by drmingdrmer** [comment]
Got it. Let me have a look at the logs!

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/runs/4513899687?check_suite_focus=true

```
failures:

---- meta_node::meta_node_all::test_meta_node_cluster_write_on_non_leader stdout ----
Error: timeout after 500ms when replicated log .last_log_index -> 3 latest: RaftMetrics { id: 1, state: NonVoter, current_term: 1, last_log_index: 0, last_applied: 0, current_leader: Some(0), membership_config: MembershipConfig { members: {1}, members_after_consensus: None }, snapshot: LogId { term: 0, index: 0 }, leader_metrics: None }

Stack backtrace:
```

**Comment by drmingdrmer** [comment]
> https://github.com/datafuselabs/databend/runs/4513899687?check_suite_focus=true
> 
> ```
> failures:
> 
> ---- meta_node::meta_node_all::test_meta_node_cluster_write_on_non_leader stdout ----
> Error: timeout after 500ms when replicated log .last_log_index -> 3 latest: RaftMetrics { id: 1, state: NonVoter, current_term: 1, last_log_index: 0, last_applied: 0, current_leader: Some(0), membership_config: MembershipConfig { members: {1}, members_after_consensus: None }, snapshot: LogId { term: 0, index: 0 }, leader_metrics: None }
> 
> Stack backtrace:
> ```

Got it...
But this is another issue
