### ISSUE TITLE
Newly released bendctl started failed for libssl.so.1.0.0 not found

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3423]
**Summary**

```shell
ubuntu@ip-xxxx:~/xxx/github/databend$ bendctl cluster create
bendctl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Cause**

Our release build uses `libssl 1.0.0` but the most recent ubuntu uses `libssl 1.1.0` instead. They are not compatible, so they are using the different soname.

In order to address this problem, we need to:

- Option 1: Use vendored openssl: https://docs.rs/openssl/latest/openssl/
- Option 2: Upgrade our build-tools to ubuntu 20.04 or upper.

**Comment by sticnarf** [comment]
I think it's the most trouble-free solution to statically link OpenSSL in case different users can have different versions of OpenSSL installed in their system.

**Comment by Xuanwo** [comment]
I start a new proposal to address this problem, PTAL: https://github.com/datafuselabs/databend/discussions/3597
