### ISSUE TITLE
Database sharing

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3430]
## Summary

Tasks:
- [ ] CREATE SHARE \<name\>
- [ ] GRANT USAGE ON DATABASE \<name\> TO SHARE \<share_name\>
- [ ] ALTER SHARE \<share_name\> ADD|REMOVE ACCOUNTS=\<orgname.accountname1\>,\<orgname.accountname2\>
- [ ] SHOW SHARES
- [ ] DROP SHARE

**Comment by ZhiHanZ** [comment]
I think share could be so

**Comment by flaneur2020** [comment]
there're a few sentences about data sharing in the snowflake's blog:

> A powerful feature such as Snowflake Data Sharing is also achieved by a metadata-only operation. The data share object is created containing references to the source and destination catalog objects and access control objects. Data sharing does not copy data from the provider, it exposes the data to the consumer via the data share object.

https://www.snowflake.com/blog/how-foundationdb-powers-snowflake-metadata-forward/

**Comment by BohuTANG** [comment]
For share createing it's metadata-only:

```
create share share1; // create a share in metasrv: /tenant/share/share1
grant usage on database db1 to share share1; // grant privileges and database object to the share
alter share share1 add accounts=tenant1;      // create a share in tenant1, but the direction is InBound
```

The hard parts is that how we check the privileges on db1 when we accessing it.

**Comment by flaneur2020** [comment]
there might have some hard works needs to be addressed before working on shares, including:

- a global metadata which across multiple regions
- managinge organization & accounts in the metadata center (currently there's no organization in the databend-query's view)

**Comment by lichuang** [comment]
https://github.com/datafuselabs/databend/issues/6973
