### ISSUE TITLE
[metasrv] add pool of persistent connections.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#3432]
**Summary**

A `connect()` takes several dozens of milliseconds, which reduces raft performance a lot.

The raft `Network` impl should keeps the connected channel to each node.
So that an RPC such as vote or append entry reuse the connection:

https://github.com/datafuselabs/databend/blob/c5b0a4cb83c23d14cb71b67586db97ee5f12903a/metasrv/src/meta_service/network.rs#L37-L54

According to the tonic docs, just `clone()` a client is quite enough and ecouraged:
https://docs.rs/tonic/latest/tonic/client/index.html

**Comment by lichuang** [comment]
seens this has been merged:

[common/containers] feature: add conn pool
- common_containers::Pool caches Channel and indexes them by addresses.

3d686365e5e412cc7976ab991152bcbc443a8034

@drmingdrmer

**Comment by drmingdrmer** [comment]
Right. close it.
