### ISSUE TITLE
refactor: common/clickhouse-srv

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3438]
**Summary**

- [ ] move clickhouse-rs into common
- [ ] integrate, extract the common part as clickhouse-common

**Comment by zhang2014** [comment]
Maybe move `clickhouse-rs` into databend-query/servers/clickhouse is better? because it's only used here

**Comment by PsiACE** [comment]
> Maybe move clickhouse-rs into databend-query/servers/clickhouse is better? because it's only used here

now, clickhouse-rs is used only for databend-benchmark.

**Comment by BohuTANG** [comment]
Why we still use `clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "fe0406b" }` in query crate?

**Comment by PsiACE** [comment]
> Why we still use `clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "fe0406b" }` in query crate?

```toml
[[bin]]
name = "databend-benchmark"
path = "src/bin/databend-benchmark.rs"
```

**Comment by PsiACE** [comment]
Since we currently rely on clickhouse_driver instead of clickhouse-rs, I will close it for now.
