### ISSUE TITLE
Add alter table 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#3461]
**Summary**

some time not think ok , there maybe design wrong column type or lose column

We need add alter table add column or remove column , change column.

**Comment by dantengsky** [comment]
@sundy-li  is it reasonable/proper to introduce another filed, let say, `column_id` to `DataField`?

**Comment by sundy-li** [comment]
What does column_id mean? Is it something like `table_id` to identify unique column ?

**Comment by dantengsky** [comment]
> What does column_id mean? Is it something like table_id to identify unique column ?

yes, all the columns are uniquely identified by column_id, and 

- `column_id` never changes, if the column is renamed.
- `column_id` increased monotonically, if a new column was added.  
-  `column_id` will not be re-used, if a column is dropped

**Comment by dantengsky** [comment]
oh, forget to say, 

columns are uniquely identified by column_id **in the scope of a given table**

columns of different tables,  may have same column id

**Comment by dantengsky** [comment]
@sundy-li let me try to address this issue without touching the `DataField`
