### ISSUE TITLE
Add a field `n_retries` to `Pool` to specify the number of times to retry when getting a pool-item

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#3469]
Add a field `n_retries` to `Pool` to specify the number of times to retry when getting a pool-item:

- `n_retries` has to be non-zero.
- Add test to ensure this behavior

https://github.com/datafuselabs/databend/blob/9c7b86f841a66f9e8bde7bced234947c7d041179/common/base/src/containers/pool.rs#L78-L85

https://github.com/datafuselabs/databend/blob/9c7b86f841a66f9e8bde7bced234947c7d041179/common/base/src/containers/pool.rs#L131-L157

---

> I prefer `n_retry` as a parameter with default value 3

_Originally posted by @ariesdevil in https://github.com/datafuselabs/databend/pull/3468#discussion_r768890671_

Maybe make it a configureable struct field?

**Comment by junaire** [comment]
May I try this? Looks interesting to me  ;) CC @Xuanwo

**Comment by Xuanwo** [comment]
This issue may be out-of-date. Ping @drmingdrmer for confirmation.

**Comment by drmingdrmer** [comment]
Forward ping request to @ariesdevil ...

**Comment by ariesdevil** [comment]
> May I try this? Looks interesting to me ;) CC @Xuanwo

Thx, refactoring is always welcome.
