### ISSUE TITLE
async-raft hangs log replication until next heart beat

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#3474]
async-raft leader does not forward logs until next heartbeat.
It seems like the LeaderState is not notified somehow.

This issue results in a slow log replication: every log takes 1 sec to commit( heartbeat interval is 1 sec)

**Comment by lichuang** [comment]
https://github.com/datafuselabs/openraft/pull/53

the pr has been merged into openraft,but seens that `has_more_log` and `tokio::select` has the same effect.

**Comment by drmingdrmer** [comment]
@lichuang the latest openraft has not yet been updated in databend... please keep it open...
