### ISSUE TITLE
Support auth plugin

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3476]
**Summary**

- [x] #3480 
- [x] #3482

**Comment by flaneur2020** [comment]
jwt might be a promising authentication option, like: https://trino.io/docs/current/security/jwt.html

**Comment by youngsofun** [comment]
better way for rust is to use enum？

enum {
   Password（type PasswordType，password vec）
   Ldap（config string）
}

**Comment by BohuTANG** [comment]
Ok, enum looks make sense.

**Comment by youngsofun** [comment]
ok, it will do it

**Comment by flaneur2020** [comment]
@youngsofun can take this issue assigned to yourself by /assignme  :)

**Comment by youngsofun** [comment]
plan with 3 pr:

- [ ] refactor auth with enum (user table, create/alter users parser and tests) 
- [ ] continue to refactor auth framework and support simple JWT and HTTP basic(use existing password)
- [ ] store password as hashed value as it should be

**Comment by Xuanwo** [comment]
All work has been done. Let's close.
