### ISSUE TITLE
introduce `purge` argument for truncate statement

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#3510]
**Summary**:

introduce `purge` argument for truncate statement

- by default, `truncate` will keep the historical data (snapshot/segment/block)
- `truncate table purge` will physically remove all the historical data, except the data (snapshot/segment/block) referenced by the last snapshot

------------------

Originally  disscussion:

> We will do the snapshot history delete(not truncate the data) in another PR?

snapshot history deletion is done implicitly by statements `drop table` and `truncate table` in this PR.
no explicit statement for `history deletion ` in this PR. will be addressed in another PR

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/issues/3506#issuecomment-995788261_

**Comment by BohuTANG** [comment]
Hi, 
One question:
1. Why drop table still keeps history data? 🤔

**Comment by dantengsky** [comment]
> Why drop table still keeps history data (snapshot/segment/block)?

sorry for the delayed response. u r right, without time-traveling, `drop table` should purge the history data.
