### ISSUE TITLE
Optimize to ser/deserialize  bytes arrays/vectors length  in varint encoding

### ISSUE THREAD

**Issue by ygf11** [datafuselabs/databend#3539]
Yes, but I don't want it to be a global setting.

Could it be possible to just write the `offsets`/ `length`   of (vectors,  byte arrays ) in variant encoding?
For other integers, we just use native encoding.

This is because we always know that the vector state has small size ranges, so it benefits a lot to use variant encoding. But for other integers, the range may be random, it's better to use native encoding.

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/3465#issuecomment-993429044_

**Comment by ygf11** [comment]
@sundy-li You are right, it's better to use a forked bincode crate.
How about adding a config to set bytes arrays/vectors length writing in varint encoding?
```rust
let config = bincode::DefaultOptions::new()
        .with_varint_encoding()
        // .with_fixint_length_encoding();
        .with_varint_length_encoding();
```

**Comment by sundy-li** [comment]
Yes，that's absolutely what I want.
