### ISSUE TITLE
bendctl>cluster create; failure

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#3555]
**Summary**

first install  bendctl  cluster create is ok, next day  bendctl cluster create Will get latest vesion , get latest vesion is ok ,
finally up failure . 

**How to reproduce**

today: bentctl cluster create 

next day: bentclt cluster create -> failure 

**Error message and/or stacktrace**

$tail -f -n 100 *

==> databend-query.2021-12-20-02 <==
{"v":0,"name":"databend-query","msg":"Config { config_file: \"\", query: QueryConfig { tenant_id: \"test\", cluster_id: \"test_cluster\", num_cpus: 8, mysql_handler_host: \"127.0.0.1\", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: \"127.0.0.1\", clickhouse_handler_port: 9000, http_handler_host: \"127.0.0.1\", http_handler_port: 8000, flight_api_address: \"127.0.0.1:9090\", http_api_address: \"127.0.0.1:8080\", metric_api_address: \"127.0.0.1:7070\", http_handler_tls_server_cert: \"\", http_handler_tls_server_key: \"\", http_handler_tls_server_root_ca_cert: \"\", api_tls_server_cert: \"\", api_tls_server_key: \"\", api_tls_server_root_ca_cert: \"\", rpc_tls_server_cert: \"\", rpc_tls_server_key: \"\", rpc_tls_query_server_root_ca_cert: \"\", rpc_tls_query_service_domain_name: \"localhost\", table_engine_csv_enabled: false, table_engine_parquet_enabled: false, table_engine_memory_enabled: true, table_engine_github_enabled: true, wait_timeout_mills: 5000, max_query_log_size: 10000, table_cache_enabled: false, table_memory_cache_mb_size: 256, table_disk_cache_root: \"_cache\", table_disk_cache_mb_size: 1024 }, log: LogConfig { log_level: \"INFO\", log_dir: \"/Users/wubx/.databend/local/logs/local_query_0\" }, meta: {meta_address: \"127.0.0.1:9191\", meta_user: \"root\", meta_password: \"******\"}, storage: StorageConfig { storage_type: \"disk\", disk: DiskStorageConfig { data_path: \"/Users/wubx/.databend/local/data\", temp_data_path: \"\" }, s3: {s3.storage.region: \"\", s3.storage.endpoint_url: \"\", s3.storage.bucket: \"\", }, azure_storage_blob: {Azure.storage.container: \"\", } } }","level":30,"hostname":"192.168.1.5","pid":4758,"time":"2021-12-20T02:39:38.98076Z","target":"databend_query","line":65,"file":"query/src/bin/databend-query.rs"}
{"v":0,"name":"databend-query","msg":"DatabendQuery v-0.1.0-14d1203-simd(1.59.0-nightly-2021-12-19T16:29:53.229302+00:00)","level":30,"hostname":"192.168.1.5","pid":4758,"time":"2021-12-20T02:39:38.98078Z","target":"databend_query","line":66,"file":"query/src/bin/databend-query.rs"}
{"v":0,"name":"databend-query","msg":"use remote meta","level":30,"hostname":"192.168.1.5","pid":4758,"time":"2021-12-20T02:39:38.980879Z","target":"databend_query::catalogs::impls::mutable_catalog","line":86,"file":"query/src/catalogs/impls/mutable_catalog.rs"}

==> std_err.log <==
Error: Code: 4007, displayText = Raft is shutting down.

"   0: backtrace::capture::Backtrace::create\n   1: backtrace::capture::Backtrace::new\n   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   3: <databend_meta::api::rpc::flight_service::MetaFlightImpl as arrow_format::flight::service::flight_service_server::FlightService>::do_action::{{closure}}::{{closure}}\n   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\n   7: <tonic::transport::service::grpc_timeout::ResponseFuture<F> as core::future::future::Future>::poll\n   8: <tonic::transport::server::SvcFuture<F> as core::future::future::Future>::poll\n   9: <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll\n  10: tokio::runtime::task::harness::poll_future\n  11: tokio::runtime::task::raw::poll\n  12: tokio::runtime::thread_pool::worker::Context::run_task\n  13: tokio::runtime::thread_pool::worker::run\n  14: tokio::runtime::task::raw::poll\n  15: std::sys_common::backtrace::__rust_begin_short_backtrace\n  16: core::ops::function::FnOnce::call_once{{vtable.shim}}\n  17: std::sys::unix::thread::Thread::new::thread_start\n  18: __pthread_start\n"

==> std_out.log <==
2021-12-20T02:39:38.980681Z  INFO databend_query: Config { config_file: "", query: QueryConfig { tenant_id: "test", cluster_id: "test_cluster", num_cpus: 8, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, http_handler_host: "127.0.0.1", http_handler_port: 8000, flight_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", http_handler_tls_server_cert: "", http_handler_tls_server_key: "", http_handler_tls_server_root_ca_cert: "", api_tls_server_cert: "", api_tls_server_key: "", api_tls_server_root_ca_cert: "", rpc_tls_server_cert: "", rpc_tls_server_key: "", rpc_tls_query_server_root_ca_cert: "", rpc_tls_query_service_domain_name: "localhost", table_engine_csv_enabled: false, table_engine_parquet_enabled: false, table_engine_memory_enabled: true, table_engine_github_enabled: true, wait_timeout_mills: 5000, max_query_log_size: 10000, table_cache_enabled: false, table_memory_cache_mb_size: 256, table_disk_cache_root: "_cache", table_disk_cache_mb_size: 1024 }, log: LogConfig { log_level: "INFO", log_dir: "/Users/wubx/.databend/local/logs/local_query_0" }, meta: {meta_address: "127.0.0.1:9191", meta_user: "root", meta_password: "******"}, storage: StorageConfig { storage_type: "disk", disk: DiskStorageConfig { data_path: "/Users/wubx/.databend/local/data", temp_data_path: "" }, s3: {s3.storage.region: "", s3.storage.endpoint_url: "", s3.storage.bucket: "", }, azure_storage_blob: {Azure.storage.container: "", } } }
2021-12-20T02:39:38.980774Z  INFO databend_query: DatabendQuery v-0.1.0-14d1203-simd(1.59.0-nightly-2021-12-19T16:29:53.229302+00:00)
2021-12-20T02:39:38.980871Z  INFO databend_query::catalogs::impls::mutable_catalog: use remote meta

[How to get the server logs](https://databend.rs/development/how-to-get-server-logs/)

**Additional context**

rm ~/.databend 
reinstall bendctl everything is ok.

**Comment by wubx** [comment]
[local] [sql]> \admin
Mode switched to admin mode
[local] [admin]> cluster create
[ok] ✅ Databend cluster pre-check passed!
[ok] ✅ Cannot find databend binary path in version latest, start to download from Some(CustomMirror { base_url: "https://repo.databend.rs/databend/tags.json", databend_url: "https://repo.databend.rs/databend", databend_tag_url: "https://repo.databend.rs/databend/tags.json", playground_url: "https://repo.databend.rs/databend" })
[ok] ✅ Arch x86_64-apple-darwin
[ok] ✅ Tag v0.6.43-nightly
[ok] ✅ Successfully started meta service with rpc endpoint 127.0.0.1:9191
[ok] ✅ Local data would be stored in /Users/wubx/.databend/local/data


[failed] ❌ Cannot provison query service, error: Unknown("cannot connect to healthiness probe: http://127.0.0.1:8080/v1/health"), please check the logs output by: tail -n 100 /Users/wubx/.databend/local/logs/local_query_0/*

**Comment by BohuTANG** [comment]
Please also see https://github.com/datafuselabs/databend/issues/3990 , it seems enough for local test cc @Xuanwo
