### ISSUE TITLE
Rename table statement

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3557]
**Summary**

```
RENAME TABLE old_table TO new_table;
```
https://dev.mysql.com/doc/refman/8.0/en/rename-table.html

**Comment by kevinw66** [comment]
Is `alter_table` function needed in MetaApi ?

**Comment by BohuTANG** [comment]
> Is `alter_table` function needed in MetaApi ?

Yes, looks like we need.
But it seems we only update the database/table name with the db_id/table_id,  @drmingdrmer and @dantengsky may help here

**Comment by Junnplus** [comment]
> Is alter_table function needed in MetaApi ?

@kevinw66 @chenyukang 
The last hurdle has been cleared at https://github.com/datafuselabs/databend/pull/4288 , sorry to finish so late. :(

**Comment by kevinw66** [comment]
@BohuTANG @Junnplus The multiple table rename should support in meta api or I have to call api multiple times?

**Comment by Junnplus** [comment]
@kevinw66 I guess they can be non-atomic.

refer to https://clickhouse.com/docs/en/sql-reference/statements/rename/#misc_operations-rename_table
> If you rename multiple tables in one query, the operation is not atomic. It may be partially executed, and queries in other sessions may get Table ... does not exist ... error.
