### ISSUE TITLE
make github database immutable

### ISSUE THREAD

**Issue by Junnplus** [datafuselabs/databend#3559]
**Summary**

todo of https://github.com/datafuselabs/databend/pull/3542

> github datasource is a database engine, we should create it as:
> ```
> create database datafuselabs engine=github; -- datafuselabs must be your org name
> ```

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/discussions/3421#discussioncomment-1796350_

We should disable create table in github database.

**Comment by BohuTANG** [comment]
There is a case:
github database data source is from the remote, it's easy to materialized them into a local fuse engien table:
create table xx_comments_fuse select * from xx_comments;

If the database is immutable we must create a new database to do that.

Back to the issue, why we `make github database immutable`? :thinking:

**Comment by Junnplus** [comment]
When I say immutable, I mean `ImmutableCalalog`, https://github.com/datafuselabs/databend/blob/main/query/src/catalogs/impls/immutable_catalog.rs#L45-L48
like system database, we can't create tables or delete tables in query sql.

**Comment by Junnplus** [comment]
We may have other database engines in the future, like clickhouse's mysql/sqlite database engine, they also seem `immutable`.

**Comment by BohuTANG** [comment]
Thank you.
 Immutable github engine(and some others) here makes sense.
