### ISSUE TITLE
bendctl: Support `bendctl generate --dataset ontime`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3560]
**Summary**

Now we have 3 steps to guide user how to create and load ontime datasets to a databend cluster and do some tests.
It would be better to add one command: `bendctl generate --dataset ontime`, it will do:
1. Download ontime datasets from https://repo.databend.rs/dataset/stateful/ontime.csv
2. Create ontime database and table, schemas like ./tests/suites/0_stateful/ontime/create_table.sql
3. Load raw datas to ontime table

**Comment by ZhiHanZ** [comment]
consider more generic UX?
```bash
bendctl generate --dataset ontime
```

**Comment by BohuTANG** [comment]
> consider more generic UX?
> 
> ```shell
> bendctl generate --dataset ontime
> ```

Good idea

**Comment by kevinw66** [comment]
Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?

**Comment by BohuTANG** [comment]
> Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?

`ontime` is one of the test datasets.
There are many other datasets, for reference:
https://clickhouse.com/docs/en/getting-started/example-datasets/

**Comment by kevinw66** [comment]
> > Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?
> 
> `ontime` is one of the test datasets. There are many other datasets, for reference: https://clickhouse.com/docs/en/getting-started/example-datasets/

What's the rule for the download url, just concat with argument like `"https://repo.databend.rs/dataset/stateful/" + ${arg} + ".csv` ?

**Comment by kevinw66** [comment]
> > Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?
> 
> `ontime` is one of the test datasets. There are many other datasets, for reference: https://clickhouse.com/docs/en/getting-started/example-datasets/

How to locate the database and table schema file base on `arg` like `./tests/suites/0_stateful/ontime/create_table.sql` ?

**Comment by BohuTANG** [comment]
> > > Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?
> > 
> > 
> > `ontime` is one of the test datasets. There are many other datasets, for reference: https://clickhouse.com/docs/en/getting-started/example-datasets/
> 
> How to locate the database and table schema file base on `arg` like `./tests/suites/0_stateful/ontime/create_table.sql` ?

We can create a new ontime SQL file(or emabed the schema to rust code) in bendctl.

**Comment by kevinw66** [comment]
> > > > Is the parameter `dataset` only accept `ontime` as argument and download sql from https://repo.databend.rs/dataset/stateful/ontime.csv specifically or should it be dynamic?
> > > 
> > > 
> > > `ontime` is one of the test datasets. There are many other datasets, for reference: https://clickhouse.com/docs/en/getting-started/example-datasets/
> > 
> > 
> > How to locate the database and table schema file base on `arg` like `./tests/suites/0_stateful/ontime/create_table.sql` ?
> 
> We can create a new ontime SQL file(or emabed the schema to rust code) in bendctl.

@BohuTANG Is the dataset file already uploaded to `https://repo.databend.rs/dataset/stateful/` or should I use the url from clickhouse document directly ?

**Comment by BohuTANG** [comment]
Yes,
https://repo.databend.rs/dataset/stateful/ontime.csv

**Comment by kevinw66** [comment]
> Yes, https://repo.databend.rs/dataset/stateful/ontime.csv

Where can I found other datasets ?

**Comment by kevinw66** [comment]
@BohuTANG What should we do about the `up` command? should `generate` keep the same behavior like `up`? bootstrap the cluster first?

**Comment by BohuTANG** [comment]
> @BohuTANG What should we do about the `up` command? should `generate` keep the same behavior like `up`? bootstrap the cluster first?

Right.
