### ISSUE TITLE
Show create database statement

### ISSUE THREAD

**Issue by Junnplus** [datafuselabs/databend#3561]
**Summary**

After https://github.com/datafuselabs/databend/pull/3542, we should support `SHOW CREATE DATABSE` statement to show engine options.

```
mysql> create database datafuselabs engine=github(token='xxxxx');
mysql> show create database  datafuselabs;
CREATE DATABASE `datafuselabs` ENGINE=GITHUB(token='xxxxx');
```

https://dev.mysql.com/doc/refman/8.0/en/show-create-database.html

**Comment by sundy-li** [comment]
Ok, but let's apply the mask to the secret token or other entry options.

**Comment by Junnplus** [comment]
> Ok, but let's apply the mask to the secret token or other entry options.

IMHO, this shouldn't be needed, we should control by permissions. The same goes for clickhouse.
