### ISSUE TITLE
[Build] replace openssl libc dynamic linking

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#3570]
**Summary**
Currently openssl libc linking issue occurs when people installed incompatible libssl-dev version and maintain on openssl related building dependency cost a lot of attentions.
We could take a trial to replace openssl related dependencies with rustls(https://github.com/rustls/rustls)
Ref:
https://msfjarvis.dev/posts/building-static-rust-binaries-for-linux/

**Comment by ZhiHanZ** [comment]
cc @Xuanwo @PsiACE

**Comment by Xuanwo** [comment]
Let's resolve them via https://github.com/datafuselabs/databend/discussions/3597

**Comment by Xuanwo** [comment]
OpenDAL doesn't depend on `openssl` anymore since v0.17.

Maybe we can clean up all deps on `openssl` so that we don't need `openssl` anymore. 

Cc @PsiACE, what do you think?

**Comment by PsiACE** [comment]
> Maybe we can clean up all deps on openssl so that we don't need openssl anymore.

If it works, that would be great. I'm just concerned that there may be other dependencies that still require `openssl`.

**Comment by Xuanwo** [comment]
We have moved to musl by default. Let's close for now.
