### ISSUE TITLE
build source code on centos 7 objcopy: option '--compress-debug-sections' doesn't allow an argument

### ISSUE THREAD

**Issue by QuintinTao** [datafuselabs/databend#3591]
I got this error when I run "make run". I think the command objcopy does not match with the requirement.
![image](https://user-images.githubusercontent.com/72123724/147030254-fd91d690-5d6a-4b85-a52e-ab7c6aea9485.png)

**Comment by QuintinTao** [comment]
May I get the QR Code of the wechart group?

**Comment by BohuTANG** [comment]
`make build`

**Comment by BohuTANG** [comment]
> May I have the QR Code of the wechart group?

cc @wubx

**Comment by QuintinTao** [comment]
> `make build`
> `./target/release/databend-query`
I ran like you mentioned. but it didn't work.
I want to change script with the command "objcopy --compress-debug-sections=zlib-gnu" in somewhere 
remove the parameter =zlib-gnu. but I can't find where it is.

I can see those commands in the *yml file.

**Comment by wubx** [comment]
> May I have the QR Code of the wechart group?

Please use wechart add: Databend

**Comment by BohuTANG** [comment]
> > `make build`
> > `./target/release/databend-query`
> > I ran like you mentioned. but it didn't work.
> > I want to change script with the command "objcopy --compress-debug-sections=zlib-gnu" in somewhere
> > remove the parameter =zlib-gnu. but I can't find where it is.
> 
> I can see those commands in the *yml file.

Please search `objcopy` in Makefile

**Comment by Xuanwo** [comment]
Hi, It's highly possible that your `objcopy` is too old that doesn't support `--compress-debug-sections=zlib-gnu`. Can you provide your Linux os-release version (run `lsb_release -a`)?

We will address this issue in the near future within https://github.com/datafuselabs/databend/discussions/3419.

To workaround this problem, you can use `cargo build --release` instead.

**Comment by QuintinTao** [comment]
> Makefile

Thanks

**Comment by QuintinTao** [comment]
> lsb_release -a

thanks

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

**Comment by Xuanwo** [comment]
Hi, @QuintinTao, is this issue still bored you?

**Comment by Xuanwo** [comment]
Let's close this stale issue.
