### ISSUE TITLE
Improved performance of arithmetic functions

### ISSUE THREAD

**Issue by zhyass** [datafuselabs/databend#3618]
Discussion: https://github.com/datafuselabs/databend/discussions/3614
Move arithmetic from datavalues to functions.
The type is no longer converted before the calculation, but is converted during the calculation.

Tasks:
- [x] #3620
- [x] #3651

**Comment by zhyass** [comment]
TODO: support div intdiv mul minus module, remove the unused code

**Comment by BohuTANG** [comment]
> TODO: support div intdiv mul minus module, remove the unused code

Ok.
I add a sub task to track them.

**Comment by Xuanwo** [comment]
Does this discussion https://github.com/datafuselabs/databend/discussions/3614 relate to this issue?

Add a link in the description will be nice!

**Comment by zhyass** [comment]
> Does this discussion #3614 relate to this issue?
> 
> Add a link in the description will be nice!

Yes, added.
