### ISSUE TITLE
Consider remove local CSV and Parquet engine

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3624]
### Discussed in https://github.com/datafuselabs/databend/discussions/3623

<div type='discussions-op-text'>

<sup>Originally posted by **BohuTANG** December 23, 2021</sup>
## Summary

Currently these two engines are almost useless, but them hinder our architectural design.
Let's rewrite and redesign if needed someday.

@sundy-li what do you think?</div>

**Comment by sundy-li** [comment]
Should we migrate it into Cloud style like

```
CREATE TABLE db1.test1 LIKE db2.test2 ENGINE = Parquet location = 's3_url' 
```

Then db1.test1 is an external table.

OR just remove these two engines.
