### ISSUE TITLE
bug: `export_set()` function's first parameter only support constant type

### ISSUE THREAD

**Issue by BlackSmith96** [datafuselabs/databend#3641]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

export_set() function

```
mysql>select * from ages;
+------+
| age  |
+------+
|   5  |
+------+
mysql> select export_set(age,'Y','N',',',5) from ages;
ERROR 1105 (HY000): Code: 7, displayText = Expected args a const, an expression, an expression, a const and a const.
```

select export_set(age,'Y','N',',',5) from Persons;

### What You Expected?

The Output should be `Y,N,Y,N,N`

### How to Reproduce?

As above.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BlackSmith96** [comment]
@BohuTANG If this is a bug, I can help.

**Comment by sundy-li** [comment]
I think it's ok to just use `Constant` value.

As the document said in  https://github.com/datafuselabs/databend/blob/62600b97e386dd039fbb6f61885269f189f4eebf/website/databend/docs/user/sql-statement/string-functions/export_set.md:

```
## Arguments

| Arguments   | Description |
| ----------- | ----------- |
| bits | The const integer. |
| on | The expression string. |
| off | The expression string. |
| separator | The const string. |
| number_of_bits | The const integer. |
```

It suits most cases, since there are 5 arguments, it will get  2^5 = 32 combinations if you allow all arguments to be not constant or constant. This is hard for use to review and maintain the codes.

**Comment by BlackSmith96** [comment]
> I think it's ok to just use `Constant` value.
> 
> As the document said in https://github.com/datafuselabs/databend/blob/62600b97e386dd039fbb6f61885269f189f4eebf/website/databend/docs/user/sql-statement/string-functions/export_set.md:
> 
> ```
> ## Arguments
> 
> | Arguments   | Description |
> | ----------- | ----------- |
> | bits | The const integer. |
> | on | The expression string. |
> | off | The expression string. |
> | separator | The const string. |
> | number_of_bits | The const integer. |
> ```
> 
> It suits most cases, since there are 5 arguments, it will get 2^5 = 32 combinations if you allow all arguments to be not constant or constant. This is hard for us to review and maintain the codes.
> 
> But you can create a pr to improve this by using `column.to_array()`.
