### ISSUE TITLE
bug: $ ./target/debug/databend-query can't print logs

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3646]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

$ ./target/debug/databend-query canot print logs

### What You Expected?

Print the INFO level logs

### How to Reproduce?

make build-debug
$ ./target/debug/databend-query

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
It's caused by https://github.com/datafuselabs/databend/pull/3628/files#diff-70102cdaf35815e79ef98fdea67bb462ae8292abc9061268e683b2e178fccfbbR61

@dantengsky  Why we change it to init_global_tracing?

**Comment by BohuTANG** [comment]
It seems we can merge `init_global_tracing` and `init_tracing_with_file` to one.

**Comment by dantengsky** [comment]
> @dantengsky Why we change it to init_global_tracing?

oops

https://github.com/datafuselabs/databend/blob/bbbb0d53e59111ced2e45b1aebb65d87ed95a144/query/src/bin/databend-query.rs#L60-L61

I should have uncomment line 60, an comment(remove) line 61 instead.

My Fault!
