### ISSUE TITLE
Introduce `parallel_read_threads` to Settings

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3648]
## Summary

https://github.com/datafuselabs/databend/blob/5bffc73861444c4c9ffcfc058b376acc09d65c07/query/src/storages/fuse/operations/read.rs#L55-L64

Default is 1, it needs configured in the settings.

**Comment by dantengsky** [comment]
shall we introduce another "setting" as well, like `max_block_size`, such that, we can tweak(and check) the parameter at runtime by using the `set [session] key = val` and `show settings` statements. (for standalone mode), we can also adjust the parallelism of reading blocks on the fly (without restarting)

**Comment by BohuTANG** [comment]
> 

Settings looks better.

**Comment by BohuTANG** [comment]
> shall we introduce another "setting" as well, like `max_block_size`, such that, we can tweak(and check) the parameter at runtime by using the `set [session] key = val` and `show settings` statements. (for standalone mode), we can also adjust the parallelism of reading blocks on the fly (without restarting)

Settings looks better, thank for the suggestions.

**Comment by BohuTANG** [comment]
I have update the title(parallel_read_threads is better to understand) and change it as a setting config. 
cc @dantengsky

**Comment by BohuTANG** [comment]
I am working on it :)
