### ISSUE TITLE
docs: Get Started Guide for developers

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#3657]
Part of https://github.com/datafuselabs/databend/discussions/3419

---

The new guide will cover the following topics:

- How to set up the environment?
  - direct way
  - docker
  - use the `dev_setup.sh`
- How to build/check/test?
- How to send issues?
- How to submit PRs?

**Comment by flaneur2020** [comment]
i think docker is a good build tool to make an immutable deployment, but it's a little hard to use as the daily development environment. also, developing rust is CPU consuming, i guess most people are developing rust in a bare-mental physical machine instead of a vm or container 🤔

**Comment by Xuanwo** [comment]
Docker has no CPU overhead (I/O, network does), I think it's OK to use docker as a build tool. Maybe we can put the docker option to the last one :laughing:

**Comment by flaneur2020** [comment]
> Docker has no CPU overhead (I/O, network does), I think it's OK to use docker as a build tool. Maybe we can put the docker option to the last one 😆

yep, docker is no cost in the building environment. i remember in a macbook the docker has to start up a linux virtual machine then start linux containers inside the vm, i guess it might slower the rust compilation during the daily development.

**Comment by Xuanwo** [comment]
> i guess it might slower the rust compilation during the daily development.

I got what you concerning. How about adding a NOTE for MacOS users on the docker option so that we can please both Linux and MacOS users?

**Comment by BohuTANG** [comment]
> > i guess it might slower the rust compilation during the daily development.
> 
> I got what you concerning. How about adding a NOTE for MacOS users on the docker option so that we can please both Linux and MacOS users?

I guess no mac guys use docker as development, this maybe a bad idea :D

**Comment by BohuTANG** [comment]
Suggest we should give the most for user's development environment but not the final(this is very hard) is ok, if the user environment is special they will solve it by themself with our new guide.
Save the time let them codes on databend as soon as possbile is the final.

**Comment by BohuTANG** [comment]
Suggest we should give the most for user's development environment but not the final(this is very hard) is ok, if the user environment is special they will solve it by themself with our new guide.
Save the time let them codes on databend as soon as possbile is the final.
