### ISSUE TITLE
Consider making UDF global between cluster and as a object of query

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3663]
## Summary
After #3655 checked in, we have the framework of user defined functions, thanks @lianghanzhen :tada: 

There are some works to improve it:
1. UDF should be object not a normal function(scalar function and aggregation function), user may grants UDF privileges
2. UDFFactory is a local cache not cluster,  we should think of it as an object(Like user/share/cluster) in metasrv and used in query

**Comment by lianghanzhen** [comment]
Hi @BohuTANG,

1. UDF is already an object I think, it's stored in Meta KV as user stages, correct me if I'm wrong?
2. Since the #1, it should be available in cluster right? We transform the UDFs in `analyze_expr` phase recursively, since rust async doesn't support recursion, we need `UDFFactory` as a local cache to avoid getting UDF from Meta KV.

**Comment by BohuTANG** [comment]
> Hi @BohuTANG,
> 
> 1. UDF is already an object I think, it's stored in Meta KV as user stages, correct me if I'm wrong?

Yes.
UDF as object, it should be binding with query, and the user can grant UDF privileges, so I think it's better to move udf from `common/functions/src/udfs` to `query/src/functions/udf`, we can do them easy with the QueryContext.


> 2. It should be available in cluster because of the first point right? We transform the UDFs in `analyze_expr` phase recursively, since rust async doesn't support recursion, we need `UDFFactory` as a local cache to avoid getting UDF from Meta KV.

The problem is that we load all udfs when the sessions creating, if someone create one udf in another node, we can not get that.

I will push an example PR, welcome to give some comments.

BTW, #3655 patch is very well, thank you very much, Iove it.

**Comment by lianghanzhen** [comment]
> The problem is that we load all udfs when the sessions creating, if someone create one udf in another node, we can not get that.

UDFs are also registered/unregistered when users create/drop functions.

> I will push an example PR, welcome to give some comments.

Sure.

**Comment by BohuTANG** [comment]
To get the udf globally, the useful part is the udf_manager.rs :
https://github.com/datafuselabs/databend/pull/3667/files#diff-6a57baa4c540a5ae254d5b37822f3cd0b474f484b695dbb0dadb5c30f003b754

Another benefit may be that we don't need `common/sql` crate if we move udf to the query crate.

**Comment by BohuTANG** [comment]
Move to https://github.com/datafuselabs/databend/issues/3738
