### ISSUE TITLE
Move Nullable to be a DataType

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3664]
### Discussed in https://github.com/datafuselabs/databend/discussions/3460

Let's introduce `DataType::Nullable(DataType)` support.

1. Add DataType `DataType::Nullable(DataType)`
2. Add `DataType::Nothing`
3. Migrate `DataType::Null` into `DataType::Nullable(Nothing)`

For table column query:

1.  `column UInt32 not null` will create column with datatype `DataType::UInt32` .
2.  `column UInt32` will create column with datatype `Nullable(DataType::UInt32)` .

**Comment by zhang2014** [comment]
We also should consider merging `function::nullable` and `function::return_ type`

**Comment by junli1026** [comment]
Some tasks I can think of:
- [ ] Remove function's method ```nullable```. The method ```return_type``` should return ```DataTypeAndNullable```, which carries both ```data_type``` and ```nullable``` -- thus we know the nullable information of the return value.
- [ ] Arithmetic and comparison functions should support ```DataTypeAndNullable```
- [ ] Add new data_type ```Nullable(Box<DataType>)``` or ```NotNull(Box<DataType>)```  -- this new type is to replace ```DataTypeAndNullable```
- [ ] Match Mysql/Clickhouse type with new ```Nullable```

**Comment by junli1026** [comment]
@sundy-li maybe we can close this one.
