### ISSUE TITLE
bug: cannot show tables after exec `use system` via http server

### ISSUE THREAD

**Issue by kevinw66** [datafuselabs/databend#3681]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main branch

### What's Wrong?

When I run `use system` and then `show tables`, no tables were shown in response body

### What You Expected?

get tables

### Anything Else?

![image](https://user-images.githubusercontent.com/31196226/147566076-1609e25f-9c96-40d5-a4c1-06fe5990c70d.png)

![image](https://user-images.githubusercontent.com/31196226/147566049-34f74732-9e7e-44fe-ba94-fde4241be167.png)

I found every new query from http client will create new session via session_manager in picture 1.
So after I run `use system`, the next query from http client still cannot locate the right database.
Why don't use cookie to keep session state?
Picture 2 point out the place when session create.(My code still has many problems, I didn't quite familiar with `poem` framework, And don't know how to use cookie currently. Can I ask for some help if needed?)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
> Why don't use cookie to keep session state?

Cookies are stored inside the Browser. On Databend's server-side, it can't control this.

**Comment by kevinw66** [comment]
> > Why don't use cookie to keep session state?
> 
> Cookies are stored inside the Browser. On Databend's server-side, it can't control this.

Can we extract session from cookie like normal web application?

**Comment by Junnplus** [comment]
Maybe you need https://github.com/datafuselabs/databend/pull/2580

**Comment by kevinw66** [comment]
> Maybe you need #2580

I noticed that, But I first found this problem is when I'm using `bendctl` and it cannot work correctly(just like I described in this issue), So I tracked into the `query` module and found the session problem

**Comment by kevinw66** [comment]
@sundy-li @Junnplus
![image](https://user-images.githubusercontent.com/31196226/147578133-65d1e8d1-cdf4-444f-bb71-4f3cb6d9a1c5.png)
![image](https://user-images.githubusercontent.com/31196226/147578180-e3dd1b65-53ee-4398-9c81-61b07e7c3aee.png)

**Comment by BohuTANG** [comment]
@kevinw66 
Hi, http handler mainly for non interaction, and(including bendctl) still some improvement, thank you for the information.
I suggest you connect with MySQL/ClickHouse client to experiment after the databend-query started by bendctl.

**Comment by Junnplus** [comment]
> I noticed that, But I first found this problem is when I'm using `bendctl` and it cannot work correctly(just like I described in this issue), So I tracked into the `query` module and found the session problem

I thank we can temporarily save the specified db in the bendctl, and bring it on next request.

**Comment by kevinw66** [comment]
> > > I noticed that, But I first found this problem is when I'm using `bendctl` and it cannot work correctly(just like I described in this issue), So I tracked into the `query` module and found the session problem
> > 
> > 
> > I thank we can temporarily save the specified db in the bendctl, and bring it on next request.
> 
> Actually, we don't recommend users use bendctl to do query, there are lots work to do.

I'd like to study the framework by improve the feature. Is there anything I can help with ?

**Comment by kevinw66** [comment]
@BohuTANG

**Comment by BohuTANG** [comment]
> > > > I noticed that, But I first found this problem is when I'm using `bendctl` and it cannot work correctly(just like I described in this issue), So I tracked into the `query` module and found the session problem
> > > 
> > > 
> > > I thank we can temporarily save the specified db in the bendctl, and bring it on next request.
> > 
> > 
> > Actually, we don't recommend users use bendctl to do query, there are lots work to do.
> 
> I'd like to study the framework by improve the feature. Is there anything I can help with ?

Sorry for later.
Feel free to improve bendctl or others in databend, just file an issue and let's do it.
