### ISSUE TITLE
Conflict between python2 and python3 when running locally

### ISSUE THREAD

**Issue by yihong0618** [datafuselabs/databend#3689]
As pic shows.

When run locally it may `pip as python3` and run as python2 and raise the import error 

![image](https://user-images.githubusercontent.com/15976103/147624460-b0f83873-0a15-4b3a-b2a5-4222421ac47f.png)

something like.
![image](https://user-images.githubusercontent.com/15976103/147624591-43447a07-2bb5-43ab-bca4-df28787056a2.png)

**Comment by PsiACE** [comment]
closed by #3690

also, I don't think we would consider supporting Python2.

**Comment by yihong0618** [comment]
@PsiACE I think the code [wait_tcp](https://github.com/datafuselabs/databend/blob/main/scripts/ci/wait_tcp.py) is running in Python2 do you want to make it to Python3?

**Comment by PsiACE** [comment]
> @PsiACE I think the code [wait_tcp](https://github.com/datafuselabs/databend/blob/main/scripts/ci/wait_tcp.py) is running in Python2 do you want to make it to Python3?

Certainly. It is well known that python2 is at the end of its life cycle.

**Comment by yihong0618** [comment]
> > @PsiACE I think the code [wait_tcp](https://github.com/datafuselabs/databend/blob/main/scripts/ci/wait_tcp.py) is running in Python2 do you want to make it to Python3?
> 
> Certainly. It is well known that python2 is at the end of its life cycle.

Cool, can I take a try?

**Comment by PsiACE** [comment]
> Cool, can I take a try?

Thank you for your willingness to help, please feel free to submit a PR
