### ISSUE TITLE
UDF: CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2; ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

mysql> CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2;
ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.

### What You Expected?

Supports AS  or as 

### How to Reproduce?

mysql> CREATE FUNCTION mean2number as (x,y)-> (x+y) / 2;
ERROR 1105 (HY000): Code: 5, displayText = sql parser error: Expected AS, found: as.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kevinw66** [comment]
Let me try this
