### ISSUE TITLE
stateless-test `06_0002_show_create_database.sql` sometimes run slow

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#3704]
In stateless-test, when running `06_0002_show_create_database.sql`, sometimes stuck.
cc @drmingdrmer

**Comment by drmingdrmer** [comment]
It may be caused by a unexpected delay in metasrv when replicating raft logs:
Sometimes a metasrv only forwards logs when `heartbeat` is triggered, i.e., every second.

If it's the same issue I'm gonna get it fixed next time upgrade our openraft engine.
