### ISSUE TITLE
bug: cargo build raise "datafuse-extras/clickhouse_driver/ Repository not found."

### ISSUE THREAD

**Issue by cadl** [datafuselabs/databend#3705]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

commit bf989b9bae6234518937814e57692ae5a9313205

### What's Wrong?

`cargo metadata` and `cargo build` don't work.

``` bash
~/Workspace/opensource/databend(main*) » cargo build                                                                             
    Updating git repository `https://github.com/datafuse-extras/clickhouse_driver/`
error: failed to get `clickhouse-driver` as a dependency of package `databend-query v0.1.0 (/Users/cadl/Workspace/opensource/databend/query)`

Caused by:
  failed to load source for dependency `clickhouse-driver`

Caused by:
  Unable to update https://github.com/datafuse-extras/clickhouse_driver/?rev=6e0ecb2#6e0ecb27

Caused by:
  failed to clone into: /Users/cadl/.cargo/git/db/clickhouse_driver-14b1cd034b32028f

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'https://github.com/datafuse-extras/clickhouse_driver/' '+refs/heads/*:refs/remotes/origin/*' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
  --- stderr
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
```

### What You Expected?

build success

### How to Reproduce?

- cleanup cargo `datafuse-extras/clickhouse_driver` cache
``` bash
$ rm $CARGO_HOME/git/db/clickhouse_driver-*
$ rm $CARGO_HOME/git/checkouts/clickhouse_driver-*
```
- ensure git fetch the repo via ssh protocol
``` bash
git config --global url."git@github.com:".insteadOf https://github.com/
```
- run `cargo build`

### Anything Else?

It looks like we should remove the trailing slash https://github.com/datafuselabs/databend/blob/0d514bf1b202a6a34f6e278e0023e97b71875dd7/query/Cargo.toml#L55 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
I can't reproduce this issue on my local ubuntu OS(Our CI also works).

**Comment by cadl** [comment]
> I can't reproduce this issue on my local ubuntu OS(Our CI also works).

@BohuTANG 
Sorry, there is something wrong with the reproduction step. I have fixed it.

`git config url."https://github.com".insteadOf https://github.com`(origin) -> `git config --global url."git@github.com:".insteadOf https://github.com/`

Now I can reproduce on my MacOS(git version 2.32.0) and ubuntu OS.

**Comment by sundy-li** [comment]
Did you check it works by removing the  trailing slash?

**Comment by cadl** [comment]
> Did you check it works by removing the  trailing slash?

yes, it works by removing the trailing slash.

**Comment by sundy-li** [comment]
Ok, @cadl Feel free to send a pr to improve this.
