### ISSUE TITLE
Aggregate index

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3711]
## Summary

Table schema:
```
CREATE TABLE tbl (col1 INT, col2 INT, col3 INT);
```

## Aggregate Indexes

```
CREATE AGGREGATE INDEX idx_name ON tbl (sum(col1), max(col2))
```

**Comment by BohuTANG** [comment]
The index here is similar to the materialized view not like the index in OLTP.
For OLTP index, it maintains a primary key each row point to the base table, we won't need it.

**Comment by flaneur2020** [comment]
i guess the same side with the OLTP indexes is it also requires transaction as its fundamental, on writing a row in the main table, the derived tables is also get updated in an ACID manner.

**Comment by jiaoew1991** [comment]
after databend supported view，maybe use` materialized view` statement to implement this feature is more suitable

**Comment by BohuTANG** [comment]
Now the databend view is a query alias, and the aggregate index is something like `[min, max]` index stored in the s3, but we don't have an RFC yet.
