### ISSUE TITLE
bug: bendctl can not run on ubuntu 18.04

### ISSUE THREAD

**Issue by yihong0618** [datafuselabs/databend#3714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest

### What's Wrong?

![image](https://user-images.githubusercontent.com/15976103/147806628-6b380f0d-c702-4a1e-8a35-3681103cc603.png)

### What You Expected?

run success

### How to Reproduce?

wsl 
![image](https://user-images.githubusercontent.com/15976103/147806673-a6b4bd59-5f85-4616-9c48-67c6e7141374.png)

### Anything Else?

try to find some solution
seems build on ubuntu 18.04 works 

see 
https://github.com/JoshuaWise/better-sqlite3/pull/631

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
`ldd --version` will get the GLIBC version.
bendctl requires GLIBC >= 2.28

**Comment by yihong0618** [comment]
cool got it.

**Comment by yihong0618** [comment]
1.
