### ISSUE TITLE
bug: databend-benchmark can't work

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

- Databend Git Version - 11fa94b
- Fedora 35 (5.15.11-200 x86_64 GNU/Linux)

### What's Wrong?

Executing any query with a proper connection to databend's clickhouse server will cause databend-benchmark to hang.

### What You Expected?

Execute the query and get the correct benchmarking results.

### How to Reproduce?

```shell
echo "select avg(number) from numbers(1000000)" |  ./target/debug/databend-benchmark -c 1  -i 10 -p 9001
```

### Anything Else?

It looks like the problem was caused when the [clickhouse-driver](https://github.com/datafuse-extras/clickhouse_driver/) was introduced. ( #3682 )

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
I got:
```
 echo "select avg(number) from numbers(1000000)" |  ./target/debug/databend-benchmark -c 1  -i 10 -p 9001
Queries 0, QPS: NaN, RPS: NaN, MiB/s: NaN.

0.000%		thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', query/src/bin/databend-benchmark.rs:279:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
