### ISSUE TITLE
Migrate to new planner framework

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#3747]
The new planner framework was introduced in #2983 .

Here's the tracking list of migration tasks from original planner to new planner:
- #3748 
- #3749 
- Scalar expression binding: #1537 #1538
- #5134
- Add a setting item to switch between planners #4989 
- #5163
- #5210
- #5203
- #5202
- #5235
- https://github.com/datafuselabs/databend/issues/5240
- #5259 
- #5343
- #5350
- #5353 
- #5360
- #5367
- #5351 
- https://github.com/datafuselabs/databend/issues/5536
- https://github.com/datafuselabs/databend/issues/5647
- https://github.com/datafuselabs/databend/issues/5651
- #5773

**Comment by xudong963** [comment]
Seems we can close the issue

**Comment by leiysky** [comment]
> Seems we can close the issue

I'll close this after new planner is enabled by default.

**Comment by Xuanwo** [comment]
@leiysky The migration has been done, let's go further.
