### ISSUE TITLE
Test framework for new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#3752]
We need a test framework to help testing the correctness of new planner.

The function of the framework may include but not limited to:
- Customize input relational expression in a convenient and clear way
- Specify the rule set to be applied and record the change of memo for each transformation to help debug
- Human friendly visualization

**Comment by ZhiHanZ** [comment]
Can I take the issue?

**Comment by leiysky** [comment]
> Can I take the issue?

Of course.

The tester of CockroachDB optimizer is a good example. They designed a DSL to explain input and expected output of test cases.

Here's their test data of rules related to scan operator: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/opt/xform/testdata/rules/scan

The tester can take `EXPLAIN` result or memo structure as its output, and it can also specify the rules to apply with specified exploration results, which is amazing.

**Comment by leiysky** [comment]
@ZhiHanZ Would you like to write a brief RFC so we can discuss about the detail then?
