### ISSUE TITLE
test: metasrv too many spans logs

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3755]
## Summary

Run the commands in local:
```
make unit-test
```

There are so many span logs from metasrv(LOG_LEVEL=DEBUG), databend-query LOG_LEVEL is INFO, so that no useful information can be scrolled in the screen if a test case failed.
There are some options for metasrv:
1. `make unit-test` runs in ERROR log level
2. github CI run in DEBUG log level

@drmingdrmer what do you think?

**Comment by drmingdrmer** [comment]
Quite nice to me.

🤔

**Comment by BohuTANG** [comment]
Done in https://github.com/datafuselabs/databend/pull/3776/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
