### ISSUE TITLE
configure different console ports for query and meta

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3758]
**update 2021-01-07**

I think just modifying the documentation will be enough. There is no need to add more complexity to the configuration for now.

---

After #3739 , we can explore and diagnose with tokio-console.

> Note that diagnostics are currently only supported for a single program, so please ensure that **only one** program has a log level of `TRACE`. Otherwise, only the first program to occupy the port will be monitored.

Consider configuring different ports for console-subscriber. Maybe it looks like this?

```rust
init_global_tracing(app_name: &str, dir: &str, level: &str, <port in config>);

let console_layer = ConsoleLayer::builder()
    // set the address the server is bound to
    .server_addr(([127, 0, 0, 1], <port in config>))

let subscriber = subscriber.with(console_layer);
```

Of course, new fields will also need to be added to the config.

**Comment by PsiACE** [comment]
emmm, one additional piece of information: it is possible to specify a different port for the program with TOKIO_CONSOLE_BIND. 

```shell
TOKIO_CONSOLE_BIND=localhost:6667 some-app
```

But it is also good to define it in the configuration. I think we can update this in the documentation.

**Comment by BohuTANG** [comment]
If our new processor async runtime will not tokio, the tokio-console is not useful for databend-query?

**Comment by PsiACE** [comment]
> If our new processor async runtime will not tokio, the tokio-console is not useful for databend-query?

I'm afraid so, for the moment, the console and tokio appear to be bound.
