### ISSUE TITLE
MetaApi supports multi tenant

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3759]
## Summary

It seems MetaApi is a global view, can not get a tenant database/table:

https://github.com/datafuselabs/databend/blob/dd7a004b6b9158769d79bd0502e4802bb53490a7/query/src/catalogs/backends/impls/meta_remote.rs#L79-L137

The KVApi works well with a prefix.

**Comment by drmingdrmer** [comment]
With tenant id, the namespace for a table would be `tenant_id/user_id/database/table` or `tenant_id/database/table`? 
I.e., is it legal that two `user` have database with the same database name?

**Comment by ariesdevil** [comment]
IMO yes, two tenants can have the same database name and a tenant can have multiple users.
Correct me if I was wrong.

**Comment by BohuTANG** [comment]
For databend use case, `tenant_id/database/table` is ok, there is no user_id from catelog.
