### ISSUE TITLE
Add `Partitions scanned` to system.query_log

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3771]
## Summary

Partitions scanned --  all partitions were scanned

**Comment by dantengsky** [comment]
hi, shall we log the number of the partitions that were scanned or their names?

**Comment by BohuTANG** [comment]
> hi, shall we log the number of the partitions that were scanned or their names?

I think we should not do that, because there are so many partitions and not useful for us.
BTW, where is the best place to get partitions numbers in DAL(or others)?

**Comment by dantengsky** [comment]
> I think we should not do that, because there are so many partitions and not useful for us.

got it 


> BTW, where is the best place to get/compute partition numbers in DAL(or others)?

to get the number of partitions/blocks after pruning : 

https://github.com/datafuselabs/databend/blob/b4c0215a625f1f7415079822a64f4cc7ddba3901/query/src/storages/fuse/operations/read_plan.rs#L43-L45

`block_metas.len()` is the number of blocks being scanned.

**Comment by dantengsky** [comment]
@BohuTANG need you help:

currently , the type of `QueryContextShared::scan_progress` is `Arc<Progress>`,  the same as `QueryContextShared::result_progress`.

as we are going to add more metrics of scanning  (and insertion see issue #3635), shall we 
 - add new fields to  `Progress` to hold the extra information
 - or use a new Data Structure to hold them

feels the latter might be better,   like `DalContext`. any suggestions?

**Comment by BohuTANG** [comment]
> @BohuTANG need you help:
> 
> currently , the type of `QueryContextShared::scan_progress` is `Arc<Progress>`, the same as `QueryContextShared::result_progress`.
> 
> as we are going to add more metrics of scanning (and insertion see issue #3635), shall we
> 
> * add new fields to  `Progress` to hold the extra information
> * or use a new Data Structure to hold them
> 
> feels the latter might be better, like `DalContext`. any suggestions?

DalContext is better here
