### ISSUE TITLE
Add `walk` visitor to PlanNode

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3778]
## Summary

For a sql example:
```
SELECT created_on, name FROM system.tables where database = 'db1' ORDER BY database, name
```

After the sql parsed to PlanNode, if I want to check:
1. Which database does this PlanNode all have
2. Which columns does this PlanNode all have

trait:
```
pub fn walk(visit: Visit, node: PlanNode) -> Result<bool> 
```

Usage(demo):
```
let mut databases = vec![];
_ = walk(fn (node: PlanNode) ->Result<bool> {
			if node is projection node {
			    databases.append(projection.database)
                        }
			Ok(true)
		}, node)
```

Reference:
1. vitess visitor patern: https://pkg.go.dev/vitess.io/vitess/go/vt/sqlparser#Walk
2. databend PlanNode visit_plan_node: https://github.com/datafuselabs/databend/blob/3ae18dba409ea6d8a8f5460e33ae424c323aaa7c/common/planners/src/plan_visitor.rs#L107

**Comment by Tangruilin** [comment]
I'd like to know if there is someone trying to solve the problem

**Comment by flaneur2020** [comment]
@Tangruilin feel free to take it :)

**Comment by Xuanwo** [comment]
The new planner uses `Plan` to replace `PlanNode`, maybe this issue is not valid anymore.

ping @leiysky for confirmation.
