### ISSUE TITLE
[proposal] Databend dependency management

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#3785]
Currently, between 800 and 1000 dependencies need to be compiled per full build/test of Databend.

**dependent-bot is not applicable**

- update one dependency at a time
- take up a lot of ci resources
- also require developer attention

## Dependency Management

1. a batch update of dependencies at the beginning of each month
    - cargo upgrade
    - cargo udeps
    - manually update dependencies that break changes
2. updates to specific dependencies as required
    - cargo audit
    - development needs

As there is currently no suitable tool to update dependencies in batch, we will perform this process manually. (The main problem is the lack of a simple way to roll back specific packages based on reported errors.)

**Comment by BohuTANG** [comment]
The fisrt task is to remove the dependsbot from databend :)

**Comment by sundy-li** [comment]
If we update dependencies in batch, how could we know which new dependency is not valid?

**Comment by PsiACE** [comment]
> If we update dependencies in batch, how could we know which new dependency is not valid?

We had to deal with these potential problems manually.

**Comment by Xuanwo** [comment]
Please take https://docs.renovatebot.com/rust/ into consideration.

`renovatebot` will update all crates in batch and have more behavior config than dependabot (which means more complex).

**Comment by BohuTANG** [comment]
We should find/make a action that can do the update in batch.
Dependabot has a disscusstion on it:
https://github.com/dependabot/dependabot-core/issues/2174
