### ISSUE TITLE
Add escape for management key

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3792]
## Summary

Cluster already has the escape for the key:
https://github.com/datafuselabs/databend/blob/b80c460048cbf64eb4dd2f5c7d905df4fc9b677f/common/management/src/cluster/cluster_mgr.rs#L62-L83

stage/udf/user also need.

**Comment by BohuTANG** [comment]
Hello, @BlackSmith96 
Any progress for this issue? We add this issue to v0.7(plan to release in the mid of this month).
Thanks.

**Comment by BlackSmith96** [comment]
@BohuTANG Sorry for delay.  I'll create a PR these two days.

**Comment by BohuTANG** [comment]
Thank you.
