### ISSUE TITLE
[RBAC] cache the roles data

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#3799]
## Tracking issue

https://github.com/datafuselabs/databend/issues/2793

## Summary

https://github.com/datafuselabs/databend/pull/3710/files#r776930739

some ideas:

- seperate a PrivilegeManager which responsible of cache all the privileges from roles, and current user
- factor out the privilege check logic to PrivilegeManager instead of UserGrantSet, or move UserGrantSet out of meta types, leave the metadata types plain data objects.

**Comment by BohuTANG** [comment]
Because we have the gran sets in the UserInfo now:
https://github.com/datafuselabs/databend/blob/46b89bbac5d60eee9fa7e5679906d02ad2e6f579/query/src/sessions/session_status.rs#L36

Why we still need a PrivilegeManager?

**Comment by flaneur2020** [comment]
this issue has a lower privilege than the issue about RBAC design. it might be a step in the RBAC implementation.
