### ISSUE TITLE
Refine the Exception Code to category

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3801]
## Summary

From the https://github.com/datafuselabs/databend/blob/main/common/exception/src/exception.rs

The ErrCode number range is no category, a bit mess for the user, need to improve.

Reference from MySQL:
https://dev.mysql.com/doc/mysql-errors/8.0/en/error-reference-introduction.html

1. Server Error Message, [1002, ... ]
2. Client Error Message , which range [2000, ...]
3. Global Error Message [1, 100]

**Comment by BohuTANG** [comment]
cc @zhang2014

**Comment by zhang2014** [comment]
+1 It is very useful.

**Comment by BohuTANG** [comment]
Let me have a try for the first version
