### ISSUE TITLE
Consider splitting sql_parser.rs to many small files into `parsers`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3808]
#Summary

Now, the `sql_parser.rs` file is bigger and bigger as our statements more and more:
https://github.com/datafuselabs/databend/blob/ab67d0191affff0d17466b5d50705cf461ce0fa4/query/src/sql/sql_parser.rs

Consider splitting the `sql_parser.rs` file into many pieces:
```
- parsers/
- parsers/parser_database.rs
- parsers/parser_use.rs
... ...
```

**Comment by PsiACE** [comment]
#4141
