### ISSUE TITLE
bug: Unable to get field named "number". Valid fields: ["(number % 2)"] (while in select before projection).

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3823]
## Summary

``` sql
mysql> select number%2 as c1, number%3 as c2 from numbers(10) group by c1;
ERROR 1105 (HY000): Code: 6, displayText = Unable to get field named "number". Valid fields: ["(number % 2)"] (while in select before projection).
```

` Unable to get field named "number"` -- wrong error hints.

ClickHouse:
```
Received exception from server (version 21.12.2):
Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `number` is not under aggregate function and not in GROUP BY: While processing number % 2 AS c1, number % 3 AS c2. (NOT_AN_AGGREGATE)

```

**Comment by wangzhen11aaa** [comment]
Hi, BohuTANG.

I am tracing this problem. 
Some help wanted.
When we create new_data_fileds from the expr, like ("number%2", "number%3", "c1", "c2"), why not combine these fileds with filed ("number")?

**Comment by wangzhen11aaa** [comment]
/assignme 

Let me try.

**Comment by wangzhen11aaa** [comment]
select number%2 as c1, number%3 as c2 from numbers(10) group by c;

The SQL is 

select number%2 as c1, number%3 as c2 from numbers(10) group by (number%2);

and 

This sql is wrong.  the c2 is not in the group by key.

mysql> select number%2 as c1, sum(number) from numbers(10) group by (c1);
+------+-------------+
| c1   | sum(number) |
+------+-------------+
|    0 |          20 |
|    1 |          25 |
+------+-------------+
2 rows in set (2.30 sec)
Read 10 rows, 80 B in 0.609 sec., 16.43 rows/sec., 131.41 B/sec.

In my view,  this is not a good issue. @BohuTANG

**Comment by wangzhen11aaa** [comment]
> 

So, we want to fix this wrong error hint problem.
