### ISSUE TITLE
Support for `GROUP BY ALL`/`ORDER BY ALL`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3824]
## Summary

```sql
SELECT state, COUNT(*) as population
FROM people
GROUP BY ALL
ORDER BY ALL;
-- GROUP BY state
-- ORDER BY state, population
```

**Comment by GrapeBaBa** [comment]
@BohuTANG can you give a brief suggestion？

**Comment by BohuTANG** [comment]
Ping @zhang2014 may help here

**Comment by BohuTANG** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver15

```
GROUP BY ALL column-expression [ ,...n ]

This syntax is provided for backward compatibility only. **It will be removed in a future version**. Avoid using this syntax in new development work, and plan to modify applications that currently use this syntax.
```

Note: **It will be removed in a future version**.

This issue will be closed, if we need this feature the ClickHouse way looks more powerful and flexible:
https://github.com/ClickHouse/ClickHouse/blob/694ad1f45274d569a4f42635b52e1e8f82f42b90/tests/queries/0_stateless/01470_columns_transformers.sql#L12

```
SELECT * EXCEPT(i) APPLY(sum) from columns_transformers;
```
