### ISSUE TITLE
support bloom filter 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#3832]
Massive data eq query ,  the query would be slow without bloom filter .

reference
https://docs.databricks.com/delta/optimizations/bloom-filters.html
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#available-types-of-indices

**Comment by junli1026** [comment]
are we planning to add bloom index file by default for every column ? I started a discussion here:
https://github.com/datafuselabs/databend/discussions/3130

Just copy the content as follows: 

1. Snowflake
I went through some Snowflake tech talk and doc, only found this one. https://nattaylor.com/blog/2019/snowflake-internals/
It says: ```Per file min/max values, #distinct values, #nulls, bloom filters etc.``` -- That is to say, Snowflake default create a bloom filter file for every data file.

2. Databricks:
Databricks take the same approach with Snowflak, see this doc: https://docs.microsoft.com/en-us/azure/databricks/delta/optimizations/bloom-filters
  ```
  A Bloom filter index is an uncompressed Parquet file that contains a single row. 
  Indexes are stored in the _delta_index subdirectory relative to the data file and 
  use the same name as the data file with the suffix index.v1.parquet.
  ```

**Comment by junli1026** [comment]
I propose:
1. creating a bloom.idx parquet file for every single column.
2. support multi-column bloom filter with sql as follows:
 ``` 
CREATE BLOOMFILTER INDEX
ON TABLE bloom_test
FOR COLUMNS(a, b, c);
```

**Comment by BohuTANG** [comment]
Looks good, cc @zhyass @dantengsky

**Comment by Xuanwo** [comment]
Close for implemented.
