### ISSUE TITLE
[Tracking] introduce docker build sandbox

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#3844]
Currently we encountered a lot of build issues for developers and our setup scripts become much more complex. here by, we should introduce some easy way to let all people with minimized dependency requirements to get hands on coding experiences.
The most simple way is to introduce a docker sandbox, which is served as a plugin, 
```bash
BUILD_WITH_DOCKER=true make build
```
would mount source code and target directory to a docker sandbox and produce target release binary files under target directory, which should provide uniform experience during cross-compile(replace cross)
Reference:
https://github.com/datafuselabs/databend/discussions/3819

- [x] #3845
- [ ] replace CI setups with dev container

**Comment by Xuanwo** [comment]
Already implemented.
