### ISSUE TITLE
Contributing is not friendly

### ISSUE THREAD

**Issue by dz85** [datafuselabs/databend#3880]
The contributing webpage is : https://databend.rs/dev/contributing/

I think it's not friendly for contributors, cos' there is nothing about what kind of commit is for issues and what kind for discussions.

e.g.: I wanna push some code to add some build tools or lint tools for a sub project. Then there is no information about:
1. should be issue or discussion
2. should be which type of issue/discussion
3. etc.

Maybe these famous cases can git us some inspirations:
1. https://docs.brew.sh/ - The docs for the brew community (seeing parts: Contributors & Maintainers)
2. https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type - The type for the commit from angular  

In the end:
Strongly suggest to build a template for the issue. 

Go for it and Keep it up!

**Comment by Xuanwo** [comment]
Awesome feedback!

I am currently working on some improvements to these areas, related issues including:

- #3657 
- https://github.com/datafuselabs/databend/discussions/3419

I expect to have a better get started docs which covers

- How to get databend built and running?
- How send patches and how to start a discussion about an RFC

Welcom for any comments!
