### ISSUE TITLE
It seems wrong codes in `website`

### ISSUE THREAD

**Issue by dz85** [datafuselabs/databend#3881]
When I review the code for website, it seems some wrong codes like this:
```js
// website/src/plugins/pxToVw.js
module.exports = function (context, options) {
  return {
    configurePostCss(postcssOptions) {
      postcssOptions.plugins.push(
        require('postcss-px-to-viewport-8-plugin')({
          exclude: [/node_modules/],
          minPixelValue: 1,
          unitPrecision: 7,
          mediaQuery: true,
          viewportWidth: 1920,
          selectorBlackList: ['::-webkit-scrollbar', '[ignore]'],
        })
      )
      return postcssOptions
    },
  }
}
```
but `postcss-px-to-viewport-8-plugin` should be listed in the project's dependencies, not devDependencies; pls check it?

**Comment by wubx** [comment]
@Chasen-Zhang

**Comment by Chasen-Zhang** [comment]
> When I review the code for website, it seems some wrong codes like this:
> 
> ```js
> // website/src/plugins/pxToVw.js
> module.exports = function (context, options) {
>   return {
>     configurePostCss(postcssOptions) {
>       postcssOptions.plugins.push(
>         require('postcss-px-to-viewport-8-plugin')({
>           exclude: [/node_modules/],
>           minPixelValue: 1,
>           unitPrecision: 7,
>           mediaQuery: true,
>           viewportWidth: 1920,
>           selectorBlackList: ['::-webkit-scrollbar', '[ignore]'],
>         })
>       )
>       return postcssOptions
>     },
>   }
> }
> ```
> 
> but `postcss-px-to-viewport-8-plugin` should be listed in the project's dependencies, not devDependencies; pls check it?

postcss-px-to-viewport-8-plugin is a devDependencies, It is a unit converter, and actually the line is not required. I think it's ok to put it in the devDependencies configuration item. Can you tell me what the problem is?   You can see how it's installed
[https://github.com/xian88888888/postcss-px-to-viewport-8-plugin#usage](url)

**Comment by dz85** [comment]
Cos' postcss-px-to-viewport-8-plugin  in dev-deps, so require('postcss-px-to-viewport-8-plugin') may throw an error. So I suggest to add a try catch with it.

**Comment by Chasen-Zhang** [comment]
> Cos' `postcss-px-to-viewport-8-plugin` in `dev-deps`, `require('postcss-px-to-viewport-8-plugin')` may throw an error. So I suggest to add a `try...catch` with it and check the return value.

oops, thank you! What you said is right. I wasn't very thoughtful, Can you propose a PR for us?

**Comment by Xuanwo** [comment]
Maybe it's better to add `postcss-px-to-viewport-8-plugin` as dependencies?

**Comment by Chasen-Zhang** [comment]
> Maybe it's better to add `postcss-px-to-viewport-8-plugin` as dependencies?

I'll just change it

**Comment by dz85** [comment]
both are ok. cos' the error we can ignore it by catching without deal with.

**Comment by Chasen-Zhang** [comment]
> both are ok. cos' the error we can ignore it by catching without deal with. and move `postcss-px-to-viewport-8-plugin` to `devDependencies` is the fast way.
Thank you for your carefulness. I know how to handle this😁
