### ISSUE TITLE
How to get statistics from underlying storage like fuse engine

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3895]
There are some levels:
1. Table and partitions level: a)number of rows and b)size in bytes
2. Column level: a)min&max, b)null count and c)distinct count

Need api/function to get them.

**Comment by BohuTANG** [comment]
cc @dantengsky

**Comment by dantengsky** [comment]
maybe we can start with the meta readers? 



https://github.com/datafuselabs/databend/blob/b5f96d2896382a2d6a1ded8220f6da2829aa3bc1/query/src/storages/fuse/io/meta_readers.rs#L73-L97

- `TableSnapshotReader` reads the table's snapshot meta data, which 
  -  contains table level  statistics
 https://github.com/datafuselabs/databend/blob/e97dae760dfffa79e77369fd59257e4b5b0bfb8d/query/src/storages/fuse/meta/snapshot.rs#L60-L69
  - and references to the segments (partitions)
  https://github.com/datafuselabs/databend/blob/e97dae760dfffa79e77369fd59257e4b5b0bfb8d/query/src/storages/fuse/meta/snapshot.rs#L41-L47
  
  
- `SegmentInfoReader` reads the table's segment metadata(given the location), which contains
  -  segment level statistics
  https://github.com/datafuselabs/databend/blob/7096d74f44dcada6ed945fa370f81920d435c83d/query/src/storages/fuse/meta/segment.rs#L21-L29
  - and statistics of all the blocks belong to segments
   
   
   https://github.com/datafuselabs/databend/blob/5ab545637914667196ff435c9c3d0d6674ddce9d/query/src/storages/fuse/meta/block.rs#L23-L30
   https://github.com/datafuselabs/databend/blob/416efd118c822454709428ff4ab44555c6114eee/query/src/storages/index/range_filter.rs#L36-L41

**Comment by BohuTANG** [comment]
From the user side(let's ignore the implementation details), how we get them? function or?

**Comment by dantengsky** [comment]
for the end-users? then, it should be sql statements. 
- general `select` statements, query data from specific system tables
- or dedicated sql statements.

**Comment by dantengsky** [comment]
for optimizer or cloud-services, that would be other stories, IMO.

**Comment by dantengsky** [comment]
any specific scenarios are being considered?

**Comment by BohuTANG** [comment]
> for optimizer or cloud-services, that would be other stories, IMO.

Right

**Comment by BohuTANG** [comment]
This mainly for cost-optimizer

**Comment by dantengsky** [comment]
> This mainly for cost-optimizer

got it. is @leiysky working on the cost-optimizer?

**Comment by dantengsky** [comment]
I suggest using the cached metadata readers apis `databend/query/src/storages/fuse/io/meta_readers.rs` to fetch the statistics, as they mitigate the relevant cost of io operations.

But, cost-optimizer might want to work with catalog apis (not an table engine specific api)...

**Comment by BohuTANG** [comment]
> I suggest using the cached metadata readers apis `databend/query/src/storages/fuse/io/meta_readers.rs` to fetch the statistics, as they mitigate the relevant cost of io operations.
> 
> But, cost-optimizer might want to work with catalog apis (not an table engine specific api)...

catalog api looks ok.
BTW, we have not to start optimizer yet.

**Comment by leiysky** [comment]
> got it. is @leiysky working on the cost-optimizer?

Haven't started yet, since we don't have enough alternative algorithms to leverage the cost model.

> cost-optimizer might want to work with catalog apis

That's right. The statistics accessor can be associated with `Table` object.

**Comment by dantengsky** [comment]
> That's right. The statistics accessor can be associated with Table object.

roger

**Comment by leiysky** [comment]
@dantengsky Correct me if I am wrong, as I know, we only maintain statistics information inside each partition(the parquet file). Shall we maintain aggregated statistics for each table like storing them in meta service?

**Comment by dantengsky** [comment]
There are aggregated statistics at segment and table level 

https://github.com/datafuselabs/databend/blob/5ab545637914667196ff435c9c3d0d6674ddce9d/query/src/storages/fuse/meta/snapshot.rs#L30-L42


https://github.com/datafuselabs/databend/blob/5ab545637914667196ff435c9c3d0d6674ddce9d/query/src/storages/fuse/meta/segment.rs#L21-L28

Besides, are there scenarios that the statistics should be "evaluated" dynamically?

**Comment by leiysky** [comment]
> Besides, are there scenarios that the statistics should be "evaluated" dynamically?

Not required, I think. 

The statistics are allowed to be inaccurate sometimes, therefore we can provide different policies to collect statistics to balance cost of computing statistics and accuracy of statistics. "Dynamic evaluation" can be one of them.

**Comment by dantengsky** [comment]
got it

**Comment by BohuTANG** [comment]
The `explain` syntax can do it now.
