### ISSUE TITLE
Add `partitions_total`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3898]
We already have the `partitions_scanned`(this is the partitions after pruning):
https://github.com/datafuselabs/databend/blob/6bd00e35892e7f6cdf529dcc134f7b943e89a616/common/dal/src/context.rs#L34

We still need the `partitions_total` to show how many partitions we have before pruning.

**Comment by BohuTANG** [comment]
cc @dantengsky

**Comment by dantengsky** [comment]
got it
