### ISSUE TITLE
Support Semi-structured Data Types (like json format)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3916]
### Discussed in https://github.com/datafuselabs/databend/discussions/3911

<div type='discussions-op-text'>

<sup>Originally posted by **ZhiHanZ** January 19, 2022</sup>
clickhouse json format is especially helpful for logging and monitoring application and we could support it
https://clickhouse.com/docs/en/interfaces/formats/#jsoneachrow
https://clickhouse.com/docs/en/sql-reference/functions/json-functions/
https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html
</div>

**Comment by BohuTANG** [comment]
If we support `Semi-structured Data Types` like snowflake :
https://docs.snowflake.com/en/sql-reference/data-types-semistructured.html

We can make the functions more powerful and streamlined, for example, clickhouse URLS functions:
https://clickhouse.com/docs/en/sql-reference/functions/url-functions/

We can only use a `parse_url -> Object` to do all the URLS funcstion in clickhouse:
```
select parse_url('https://www.snowflake.com/'):scheme;
"https"

select parse_url('https://www.snowflake.com/'):topLevelDomain;
"com"
```

**Comment by ZhiHanZ** [comment]
interesting papers:
https://db.in.tum.de/people/sites/durner/papers/json-tiles-sigmod21.pdf

**Comment by BohuTANG** [comment]
Note:
Format is 'YYYY-MM-DD hh:mm:ss[.fraction]', the range for DATETIME values is '1000-01-01 00:00:00.000000' to '9999-12-31 23:59:59.999999'.
