### ISSUE TITLE
integrate new processor framework

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#3931]
- [x] integrate standalone select query with new processor
    - [x] integrate numbers table with new processor
    - [x] integrate systems table with new processor
    - [x] #4345
- [x] #4471
- [x] #4799

**Comment by xudong963** [comment]
Hi @zhang2014 , I've read through the processor code in general, If you don't mind, I'll take the final task (integrate insert query with new processor). I think the last task can be developed in parallel with #4471, right?

**Comment by sundy-li** [comment]
Actually, I just want to start to work on it(not ready yet).   You can take the task~

**Comment by BohuTANG** [comment]
This is ready, let's close it.
