### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#3933]
```
SET GLOBAL max_block_size = 30;
-- We should store the settings in meta service and get this for cluster other nodes of the tenant.
```

Tasks:
- [x] Refine the session: change mutable status to session context
- [x] Add `settings` set in meta
- [ ] Write/Read global settings for settings 
- [ ] `SET GLOBAL xx=yy` statement

**Comment by BohuTANG** [comment]
The meta key is:__df_settings/tenant/cluster_name/settting_name?

**Comment by BohuTANG** [comment]
From the experience of snow, it seems that the settings should bind with tenant not the cluster, from the user side, he shouldn't know what's the cluster is.
So, what is the purpose related to the cluster setting here?

**Comment by zhang2014** [comment]
> From the experience of snow, it seems that the settings should bind with tenant not the cluster, from the user side, he shouldn't know what's the cluster is.
> So, what is the purpose related to the cluster setting here?

This can be useful when opening the features of different warehouses. For example, on user side, the test cluster (read-only) and the online cluster may share the same data, but they have different settings. But it seems that global is more suitable for tenants.

Possible solutions:
```
SET GLOBAL max_block_size = 30; -- tenants
SET WAREHOUSE max_block_size = 30; -- namespace
```

**Comment by BohuTANG** [comment]
I think we can restart the task now.
