### ISSUE TITLE
Use buffered-reader to read table metadata

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#3938]
Currently, fuse table's metadata, namely the table snapshot, segment information, and the FileMetaData of parquet are all read from underlying storage(e.g S3) by using the non-buffered "bare-mental" readers. Since there are lots of scattered reads for the reading of those metadata, especially for the FileMetaData, this leads to a bad performance. A recent experiment shows that a table of common settings, with several billion rows, may take about 20s to load these metadata (they are likely to be cached for a long period of time afterward though).

Thus, buffered reading is needed for them.

This is where the InputStream is provided for the MetaReaders.

https://github.com/datafuselabs/databend/blob/a89b24cbbefa2e07c1143311ea4fb29ada0f6889/query/src/storages/fuse/io/meta_readers.rs#L161-L166

The `InputStream` is just a boxed AsyncRead + AsyncSeek + Send + Unpin in disguise.

And the above `InputStream` is needed to be wrapped by a `BufReader`, as the BlockReader did.

https://github.com/datafuselabs/databend/blob/a89b24cbbefa2e07c1143311ea4fb29ada0f6889/query/src/storages/fuse/io/block_reader.rs#L105-L108

The settings of the size of read buffer could be obtained from context, like this:

https://github.com/datafuselabs/databend/blob/a89b24cbbefa2e07c1143311ea4fb29ada0f6889/query/src/storages/fuse/operations/read.rs#L68

**Comment by Xuanwo** [comment]
related to https://github.com/datafuselabs/databend/pull/3934

**Comment by GrapeBaBa** [comment]
@Xuanwo #3934 already merged, can this task start?

**Comment by Xuanwo** [comment]
Let's go!
