### ISSUE TITLE
datavalues2 && string functions  (some of them are already done, you can take the example in `fn register2`)

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#3975]
- [x] bin
- [x] hex
- [x] oct
- [x] repeat
- [x] mid
- [x] substr
- [x] substring
- [x] substring_index
- [x] unhex
- [x] locate
- [x] position
- [x] instr
- [x] insert
- [x] field
- [x] concat
- [x] replace
- [x] strcmp

Please feel free to comments here to take part of them.

**Comment by Xuanwo** [comment]
Let's rock!

**Comment by Xuanwo** [comment]
- [x] ascii
- [x] bit_length
- [x] octet_length
- [x] char_length
- [x] character_length
- [x] ord
- [x] length

PR https://github.com/datafuselabs/databend/pull/4070 resolved all upper functions.

- [ ] bin
- [ ] hex
- [ ] oct
- [ ] repeat
- [ ] mid
- [ ] substr
- [ ] substring
- [ ] substring_index
- [ ] unhex
- [ ] locate
- [ ] position
- [ ] instr
- [ ] insert
- [ ] field
- [ ] concat
- [ ] replace
- [ ] strcmp
- [ ] left
- [ ] right
- [ ] concat_ws
- [ ] elt
- [ ] space
- [ ] lpad
- [ ] rpad
- [ ] export_set
- [ ] find_in_set
- [ ] format
- [ ] char

Please feel free to comments here to take part of them.

**Comment by sundy-li** [comment]
I'll take functions from `left` to `char`.

**Comment by Veeupup** [comment]
@likg227 maybe u can take the following function to have some fun!
- [ ] locate
- [ ] position

**Comment by sundy-li** [comment]
I will take:

- [ ] instr
- [ ] insert
- [ ] field
- [ ] concat
- [ ] replace
- [ ] strcmp
