### ISSUE TITLE
[Monitoring] prefer structured log instead of unstructured logs

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#3983]
it would be nice to provide structured logs instead of unstructured one for downstream monitoring, tracing etc, as reference (https://kubernetes.io/blog/2020/09/04/kubernetes-1-19-introducing-structured-logs/)
sample structured log.
```json
{
  "ts": 1580306777.04728,
  "msg": "Http query request",
  "component": "http handler",
  "description": "select count(*) from numbers(10000);"
  "status": "ready"
}
```

some interesting discussions in tracing.rs
https://github.com/tokio-rs/tracing/discussions/1789#discussion-3757553

**Comment by BohuTANG** [comment]
Does it mean the server log? We already have json format:
https://github.com/datafuselabs/databend/blob/b48725f82905c7c62b42e28f4c9c769a3cceb27e/common/tracing/src/logging.rs#L98

```
cat  _logs/databend-query-@127.0.0.1\:3307.2022-01-25-05 
{"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"Config { config_file: \"\", query: QueryConfig { tenant_id: \"\", cluster_id: \"\", num_cpus: 16, mysql_handler_host: \"127.0.0.1\", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: \"127.0.0.1\", clickhouse_handler_port: 9000, http_handler_host: \"127.0.0.1\", http_handler_port: 8000, flight_api_address: \"127.0.0.1:9090\", http_api_address: \"127.0.0.1:8080\", metric_api_address: \"127.0.0.1:7070\", http_handler_tls_server_cert: \"\", http_handler_tls_server_key: \"\", http_handler_tls_server_root_ca_cert: \"\", api_tls_server_cert: \"\", api_tls_server_key: \"\", api_tls_server_root_ca_cert: \"\", rpc_tls_server_cert: \"\", rpc_tls_server_key: \"\", rpc_tls_query_server_root_ca_cert: \"\", rpc_tls_query_service_domain_name: \"localhost\", table_engine_csv_enabled: false, table_engine_parquet_enabled: false, table_engine_memory_enabled: true, database_engine_github_enabled: true, wait_timeout_mills: 5000, max_query_log_size: 10000, table_cache_enabled: false, table_cache_snapshot_count: 256, table_cache_segment_count: 10240, table_cache_block_meta_count: 102400, table_memory_cache_mb_size: 256, table_disk_cache_root: \"_cache\", table_disk_cache_mb_size: 1024, management_mode: false }, log: LogConfig { log_level: \"INFO\", log_dir: \"./_logs\" }, meta: {meta_address: \"\", meta_user: \"\", meta_password: \"******\"}, storage: StorageConfig { storage_type: \"disk\", disk: DiskStorageConfig { data_path: \"_data\", temp_data_path: \"\" }, s3: {s3.storage.region: \"\", s3.storage.endpoint_url: \"\", s3.storage.bucket: \"\", }, azure_storage_blob: {Azure.storage.container: \"\", } } }","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.963586174Z","target":"databend_query","line":70,"file":"query/src/bin/databend-query.rs"}
{"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"DatabendQuery v-0.1.0-f735fdc-simd(1.59.0-nightly-2022-01-22T05:24:44.994504491+00:00)","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.96370915Z","target":"databend_query","line":71,"file":"query/src/bin/databend-query.rs"}
{"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"use embedded meta","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.964464115Z","target":"databend_query::catalogs::impls::mutable_catalog","line":81,"file":"query/src/catalogs/impls/mutable_catalog.rs"}

```

**Comment by ZhiHanZ** [comment]
> Does it mean the server log? We already have json format:
> 
> https://github.com/datafuselabs/databend/blob/b48725f82905c7c62b42e28f4c9c769a3cceb27e/common/tracing/src/logging.rs#L98
> 
> ```
> cat  _logs/databend-query-@127.0.0.1\:3307.2022-01-25-05 
> {"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"Config { config_file: \"\", query: QueryConfig { tenant_id: \"\", cluster_id: \"\", num_cpus: 16, mysql_handler_host: \"127.0.0.1\", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: \"127.0.0.1\", clickhouse_handler_port: 9000, http_handler_host: \"127.0.0.1\", http_handler_port: 8000, flight_api_address: \"127.0.0.1:9090\", http_api_address: \"127.0.0.1:8080\", metric_api_address: \"127.0.0.1:7070\", http_handler_tls_server_cert: \"\", http_handler_tls_server_key: \"\", http_handler_tls_server_root_ca_cert: \"\", api_tls_server_cert: \"\", api_tls_server_key: \"\", api_tls_server_root_ca_cert: \"\", rpc_tls_server_cert: \"\", rpc_tls_server_key: \"\", rpc_tls_query_server_root_ca_cert: \"\", rpc_tls_query_service_domain_name: \"localhost\", table_engine_csv_enabled: false, table_engine_parquet_enabled: false, table_engine_memory_enabled: true, database_engine_github_enabled: true, wait_timeout_mills: 5000, max_query_log_size: 10000, table_cache_enabled: false, table_cache_snapshot_count: 256, table_cache_segment_count: 10240, table_cache_block_meta_count: 102400, table_memory_cache_mb_size: 256, table_disk_cache_root: \"_cache\", table_disk_cache_mb_size: 1024, management_mode: false }, log: LogConfig { log_level: \"INFO\", log_dir: \"./_logs\" }, meta: {meta_address: \"\", meta_user: \"\", meta_password: \"******\"}, storage: StorageConfig { storage_type: \"disk\", disk: DiskStorageConfig { data_path: \"_data\", temp_data_path: \"\" }, s3: {s3.storage.region: \"\", s3.storage.endpoint_url: \"\", s3.storage.bucket: \"\", }, azure_storage_blob: {Azure.storage.container: \"\", } } }","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.963586174Z","target":"databend_query","line":70,"file":"query/src/bin/databend-query.rs"}
> {"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"DatabendQuery v-0.1.0-f735fdc-simd(1.59.0-nightly-2022-01-22T05:24:44.994504491+00:00)","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.96370915Z","target":"databend_query","line":71,"file":"query/src/bin/databend-query.rs"}
> {"v":0,"name":"databend-query-@127.0.0.1:3307","msg":"use embedded meta","level":30,"hostname":"thinkpad","pid":7903,"time":"2022-01-25T05:39:49.964464115Z","target":"databend_query::catalogs::impls::mutable_catalog","line":81,"file":"query/src/catalogs/impls/mutable_catalog.rs"}
> ```

As a recommended way to improve observability pipeline, logging information(millions of lines) would be collected for latter analysis, thus, it require services to provide high cardinal(unique value unit) structured information to describe each logs.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1602-structured-logging/README.md
to handle it, what we should do :
1. classify log to their relevant modules (lexer, parser, planner etc), tenant name, cluster name, execution time,  status, query endpoint etc...
2. deriving logging schema for each modular units

an example refactor
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1602-structured-logging/README.md#example-of-migrating-klog-call

**Comment by flaneur2020** [comment]
after talking with @ZhiHanZ , it seems we can make a common labels for loggings, like:

- cluster
- tenant id
- query id
- etc

so we can collect the logs to loki or other logging system, and aggregate/filter logs by the common labels.

**Comment by sundy-li** [comment]
We have `system.query_log` for query log.

Maybe we can have `system.trace_log` for tracing.

**Comment by everpcpc** [comment]
> We have `system.query_log` for query log.
> 
> Maybe we can have `system.trace_log` for tracing.

I think trace log which might be rotated periodically is not as closely related to the core database system as query log, and would be a burden to the warehouse itself since it has much more flexibility than query log. Perhaps a logging system outside would be enough and better for it.

**Comment by everpcpc** [comment]
Actually there are already both `system.query_log` and `system.tracing` but only on single instance, we need to aggregate them with loki for later tracing & analysis.
