### ISSUE TITLE
bendctl start-single-node

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3990]
The problem:
bendctl is bit complex for local test(start databend-meta and check, then start databend-query), we should simple them to one command `start-single-node`

Golas:
1. Download (or check) databend-query binary, if not download, download the latest databend-query
2. Start databend-query with embedded meta

No sql and Interactive mode

**Comment by Xuanwo** [comment]
Is it a good idea to ship all our binaries together into one? 

- cockroachdb ship all features in one binary (cockroach).
- yugabytedb ship all binaries in the same archive (yb-master, yb-tserver).

It's a bit wired to me to download new binaries via tool.

**Comment by BohuTANG** [comment]
Do you mean we archive databend-meta and databend-query to one tar? It looks good to me,

**Comment by BohuTANG** [comment]
But we should consider how the user(local test) to upgrade their local databend-query, so here back again to download databend-query binary.

**Comment by Xuanwo** [comment]
Also ping @ZhiHanZ @PsiACE for discussion.

**Comment by PsiACE** [comment]
I basically agree with @Xuanwo's opinions. 

It should be noted, however, that one of the original purposes of bendctl was to be able to manage multiple versions of the databend-query and databend-meta instances. In this way, it may be the equivalent of nvm rather than a traditional client.

**Comment by Xuanwo** [comment]
> It should be noted, however, that one of the original purposes of bendctl was to be able to manage multiple versions of the databend-query and databend-meta instances. In this way, it may be the equivalent of nvm rather than a traditional client.

I'm a bit confused about this. Why users (including ourselves) will have multiple versions of databend-{query, meta} instead of upgrading to same version?

**Comment by BohuTANG** [comment]
For the user, databend-{meta, query} are the same version, we need to provide the ability to upgrade to the new version all of them.

**Comment by Xuanwo** [comment]
> they maybe often upgrade databend-query only(databend-meta may don't have priority updates and databend-meta deploy on the different region)

There are two problems:

1. Will `databend-query` && `databend-meta` must be the same version?
2. Will `databend-query` in the same cluster must be the same version?

For problem 1, it's possible and there are solutions.

For problem 2, I'm confused. If such statuiation doesn't exist, I believe we can remove multi-version features from bendctl and let package manager to handle them.

**Comment by BohuTANG** [comment]
> > they maybe often upgrade databend-query only(databend-meta may don't have priority updates and databend-meta deploy on the different region)
> 
> There are two problems:
> 
> 1. Will `databend-query` && `databend-meta` must be the same version?
No, but they are certainly compatible with api

> 2. Will `databend-query` in the same cluster must be the same version?
Yes

> 
> For problem 1, it's possible and there are solutions.
> 
> For problem 2, I'm confused. If such statuiation doesn't exist, I believe we can remove multi-version features from bendctl and let package manager to handle them.

**Comment by BohuTANG** [comment]
Back to this issue, sugesst that we focus on how users to test on locally with `start-single-node`, this is the easiest way.
For the production, we can discuss it in another issue.I am sure there will be a lot to consider, the good side is that there are already many options to reference.

**Comment by Xuanwo** [comment]
bendctl has been deprecated via https://github.com/datafuselabs/databend/issues/4426, let's close this issue.
