### ISSUE TITLE
Refactor 0_stateless

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3995]
**The problem**

https://github.com/datafuselabs/databend/tree/main/tests/suites/0_stateless
has more and more tests, it's hard to category a new test case to the right group.

**Goals**
1. Add sub directory to `0_stateless` for group
`00_dummy` -- dummy
`01_system` -- system tables test
`02_function` -- functions test
`03_dml` -- dml test
`04_ddl` -- ddl test
`05_show` -- show test
`06_use` -- use test
`07_meta` -- meta related test
`08_fuse` -- fuse engine test

**Comment by BohuTANG** [comment]
This issue should after datavalues-dev checked in.

**Comment by wangzhen11aaa** [comment]
> This issue should after datavalues-dev checked in.

Ok.

**Comment by wangzhen11aaa** [comment]
I think the structure of  stateless tests is not very neat and clean-organized. And test is part of the system, good-organized structure is good for maintainance. Thank you.

The definitions about these categories can be refered in the following link.
https://www.geeksforgeeks.org/sql-ddl-dql-dml-dcl-tcl-commands/

cc @BohuTANG

**Comment by BohuTANG** [comment]
The new `docs` layout more senses now:
https://github.com/datafuselabs/databend/tree/84ea295a604a0d68dc910b7b2545b23ed4d675c4/docs/user/01-sql-statement

stateless-test can be referenced to it.
