### ISSUE TITLE
[metasrv] Refactor metasrv errors

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#4000]
Now we use ErrorCode as the error return type for most of metasrv's functions, but this makes it difficult to get the underlying error, and we would like to remove ErrorCode and only wrap it to ErrorCode when it is returned to the query side.

*  use `thiserror` defines some concrete error type with a `MetaError` for including these error types just like `ErrorCode`.
*  handle the type conversion, convert to other error types only when necessary
*  tests

**Comment by lichuang** [comment]
https://github.com/datafuselabs/databend/pull/4023

https://github.com/datafuselabs/databend/pull/4090
