### ISSUE TITLE
bug: databend-bot usually give duplicate comments in PR

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#4009]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

newest

### What's Wrong?

databend-bot sometimes gives duplicate comments in PR
![image](https://user-images.githubusercontent.com/26339429/151399936-f9ecc1f0-a255-4259-9772-2a842edf457e.png)

### What You Expected?

databend-bot give only one unique comment

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Occurred at https://github.com/datafuselabs/databend/pull/4146 too, I will fix it.

/assignme
