### ISSUE TITLE
Can we make the ci tests on local machine more friendly?

### ISSUE THREAD

**Issue by wangzhen11aaa** [datafuselabs/databend#4026]
Hi everyone, 
 Before we launch a new tests begin, can we use some scripts to clean the old meta data and make databend-query be ready to make a brand new test. Otherwise we need to delete the (user/database) meta data manully, that's not friendly.
  Or we have trick to complete this task.

**Comment by BohuTANG** [comment]
`make clean` will do that.

Maybe the bette way is that we should write all the data to a directory like `_test_datas` for all the tests, and auto clean this directory when the new tests setup.

**Comment by wangzhen11aaa** [comment]
> `make clean` will do that.
> 
> Maybe the better way is that we should write all the data to a directory like `_test_datas` for all the tests, and auto clean this directory when the new tests setup.

ok, got it.
