### ISSUE TITLE
bug: comparison type coercion error

### ISSUE THREAD

**Issue by junli1026** [datafuselabs/databend#4040]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

laster master

### What's Wrong?

```
>> select 1 = false;
>> ERROR 1105 (HY000): Code: 1007, displayText = Can not compare UInt8 with Boolean.
```

### What You Expected?

```select 1 = false ``` should return false/0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by likg227** [comment]
`select -1 = true `should also return false/0, just like MySQL?

**Comment by junli1026** [comment]
> `select -1 = true `should also return false/0, just like MySQL?

Maybe we should stick with strict typing, ```select 1 = false``` returning error actually makes sense to me... Jus tried Postgre, it just returns error in this case.

**Comment by likg227** [comment]
> > `select -1 = true `should also return false/0, just like MySQL?
> 
> Maybe we should stick with strict typing, `select 1 = false` returning error actually makes sense to me... Just tried Postgre, it returns error in this case.

Boolean can't be compared with an integer in PostgreSQL, in contrast to MySQL.  Actually, the constants TRUE and FALSE evaluate to 1 and 0 in MySQL, so `select -1 = true` will return false. My question is should we behave like MySQL?

**Comment by junli1026** [comment]
> > > `select -1 = true `should also return false/0, just like MySQL?
> > 
> > 
> > Maybe we should stick with strict typing, `select 1 = false` returning error actually makes sense to me... Just tried Postgre, it returns error in this case.
> 
> Boolean can't be compared with an integer in PostgreSQL, in contrast to MySQL. Actually, the constants TRUE and FALSE evaluate to 1 and 0 in MySQL, so `select -1 = true` will return false. My question is should we behave like MySQL?

We are talking about the same thing, a strict and strong typed SQL lang or not.

But I mistook this behavior for another one, which caused the comparison between Integer and Boolean -- I thought the root cause is type coercion. 

Close this bug because the behavior is by design.

**Comment by junli1026** [comment]
I thought it was this type coercion bug that caused another one I met. But obviously the type coercion has its design philosophy and the one I met was caused by a different reason. 
So close this bug.
