### ISSUE TITLE
Add comments for codes to increase readability.

### ISSUE THREAD

**Issue by wangzhen11aaa** [datafuselabs/databend#4044]
Hi, all. 
  Good comments are as good/important as codes, they are good abstraction and summray for a bunch of codes, though codes can express themselves. For the `Maintainability` and `Readability` especially for new one.
   RFC.

**Comment by wangzhen11aaa** [comment]
How about prefixing "_"  in to variable name whoes life will end out local scope?

**Comment by wangzhen11aaa** [comment]
Need some help.

`pub struct Series(pub Arc<dyn SeriesTrait>);`

impl<'a> AsRef<(dyn SeriesTrait + 'a)> for Series {
    fn as_ref(&self) -> &(dyn SeriesTrait + 'a) {
        &*self.0
    }
}

I think the `pub struct Series(pub Arc<dyn SeriesTrait>);` here needs some comments, This kind of code not found in the rust programming. PLS give some references. 

@BohuTANG

**Comment by wangzhen11aaa** [comment]
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by BohuTANG** [comment]
> Hi, all. For the code style part, the references below may help.
> 
> Code row length: https://www.python.org/dev/peps/pep-0008/#maximum-line-length Comment part: https://www.python.org/dev/peps/pep-0008/#comments
> 
> We may can draw on theses good styles. RFC. Please give more advance.

Thank you for your suggestions, looks like we could use rustfmt comment_width to normalize them.

**Comment by wangzhen11aaa** [comment]
> > Hi, all. For the code style part, the references below may help.
> > Code row length: https://www.python.org/dev/peps/pep-0008/#maximum-line-length Comment part: https://www.python.org/dev/peps/pep-0008/#comments
> > We may can draw on theses good styles. RFC. Please give more advance.
> 
> Thank you for your suggestions, looks like we could use rustfmt comment_width to normalize them.

Do not find the option or argument named `comment_width `, and I tried the rustfmt with one line containing 400+ characters, running it does not give any change. That's awkward. :(

**Comment by BohuTANG** [comment]
> 

It works with to `rustfmt.toml`:
```
comment_width = 100
wrap_comments = true
```

There is a document about it here:
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#comment_width

**Comment by wangzhen11aaa** [comment]
> > 
> 
> It works with `rustfmt.toml`:
> 
> ```
> comment_width = 100
> wrap_comments = true
> ```
> 
> There is a document about it here: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#comment_width

Then, Do we need to set some value and refact those codes.

**Comment by BohuTANG** [comment]
Let's do it :D

**Comment by wangzhen11aaa** [comment]
> Let's do it :D

WIP
