### ISSUE TITLE
table/database meta also need ModifiedOn

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4060]
@BohuTANG Do we also need ModifiedOn?

_Originally posted by @ariesdevil in https://github.com/datafuselabs/databend/issues/4056#issuecomment-1030633613_

**Comment by Xuanwo** [comment]
Hi @LiuYuHui, are you still on this issue? Do you need some help?

**Comment by LiuYuHui** [comment]
Hi @Xuanwo, thanks for your remainer, I am still working on this issue, I will finish it ASAP

**Comment by LiuYuHui** [comment]
Hi @Xuanwo, I checked the implementation and find that there is a `updated_on` field in table meta, Is it the same as `ModifiedOn`?
https://github.com/datafuselabs/databend/blob/6af10774ae0929eeedeb845bf5fc12262068cf4f/common/meta/types/src/table.rs#L151

**Comment by BohuTANG** [comment]
Yes, thank you for checkout @LiuYuHui  
Closed.
