### ISSUE TITLE
Upgrade packed_simd to 3.6.7 for arrow2

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4062]
packed_simd v3.6.7 fixed the llvm_asm issue:
https://github.com/rust-lang/packed_simd/commit/6d3c23e0d289c4d5553f3e1582f17b5c78debf8d

After the upgrade, we can upgrade rust toolchain now.

**Comment by BohuTANG** [comment]
cc @jorgecarleitao

**Comment by jorgecarleitao** [comment]
Thanks! arrow2 depends on `0.3`, so the patch bump should work out of the box.

Note that I am fixing portable-simd here https://github.com/rust-lang/portable-simd/pull/238 to allow arrow2 to depend on it (see https://github.com/jorgecarleitao/arrow2/pull/747 and last comment there)
