### ISSUE TITLE
Sticky IPs for MetaSrv when MetaSrv restart

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#4089]
**Summary**
Currently metasrv boot and join nodes using IP address, this way will cause problems when metasrv restart and the leader IP is changed. When MetaSrv restarted and the leader IP is changed, the followers still try to connect with the leader with old IPs.

We should join nodes using hostname, then store them and connect through DNS resolver. 

PS: As we already have gRPC DNS resolver, so I think this is an easy task:)

**Comment by wangzhen11aaa** [comment]
The metasrv  boots using 0.0.0.0,  ` (cfg.metric_api_address, "0.0.0.0:8000");` which seems not like a concrete ip address.
