### ISSUE TITLE
COPY INTO <table> FROM

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4104]
**Summary**

Loads data from staged files to an existing table.

Tasks:
 - [x] #3586
 - [x] Copy INTO \<table\> from name internal stage #4437 
 - [x] LIST { internalStage | externalStage } [ PATTERN = '<regex_pattern>' ]  #4472 
 - [x] Streaming REST API put file to the stage

Reference:
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html

**Comment by BohuTANG** [comment]
cc @Xuanwo 
Since you are working on New DAL redesign tasks, feeling you will be interested in this task :D

**Comment by Xuanwo** [comment]
I'm interested in letting the data flow freely :smile:
