### ISSUE TITLE
Enhancement: Add sha256sum check for ontime.csv

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#4105]
In stateful test `01_0000_streaming_load`, we use scripts like the following to download test fixtures:

```shell
if [ ! -f /tmp/ontime.csv ]; then
    wget -P /tmp "https://repo.databend.rs/dataset/stateful/ontime.csv" > /dev/null 2>&1
fi
```

There are many problems:

- Download incomplete: If we `Ctrl+C` during the stateful test, we will never get the correct file again.
- Source file changed: `repo.databend.rs` is an s3 service, the file `ontime.csv` could be changed at any time.

So it's better for us to add sha256sum for `ontime.csv`. We can add an `ontime.sha1sum.txt` under `tests` and check the sha256sum every time we run the test.

**Comment by xihuanyuyetsinghua** [comment]
assign me

**Comment by sundy-li** [comment]
But this's just a hash number,  is it deserved another file `ontime.sha1sum.txt` ?
I think just put it into shell is enough.

**Comment by RainnyNightLover** [comment]
I try to download the onetime.csv file and its hash file onetime_hash.sha256 at the same time, the hash file is so small that it has a low chance of failure.
 compare the hash value before running the test
1、prepare the file by
sha256sum ontime.csv > **ontime_hash.sha256**
its content is:
429c47cdd49b7d75eec9b9244c8b1288edd132506203e37d2d1e70e1ac1eccc7  ontime.csv
2、I will check it by
cat **ontime_hash.sha256**| sha256sum  --check

BUT
how to upload the hash file to the webServer?
@Xuanwo

**Comment by PsiACE** [comment]
> BUT how to upload the hash file to the webServer? 

According to the description, we may not need to put it on the server and simply need to check it.

> We can add an ontime.sha1sum.txt under tests and check the sha256sum every time we run the test.
