### ISSUE TITLE
bug: make docker may not work properly

### ISSUE THREAD

**Issue by ClSlaid** [datafuselabs/databend#4123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

https://github.com/datafuselabs/databend/tree/f40e411ed1117aea8b1aa83e3f14fe289b84419e

### What's Wrong?

After forking and cloning the repo to my laptop, I tried building from source and running in docker.
```bash
make build-release
make docker
```
and then run it
```bash
docker run --init --rm -p 11451:3307 -p 9000:9000 -p 8001:8001 datafuselabs/databend-query
```
However, it logged:
```text
docker run --init --rm -p 11451:3307 -p 9000:9000 -p 8001:8001 datafuselabs/databend-query:latest
# /databend-meta: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
# /databend-query: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Try connect:
```bash
mysql -h 127.0.0.1 -P 11451 -u root                      
# ERROR 2013 (HY000): Lost connection to server at 'handshake: reading initial communication packet', system error: 11

clickhouse client --host 127.0.0.1 --port 9000
# ClickHouse client version 21.12.3.32 (official build).
# Connecting to 127.0.0.1:9000 as user default.
# Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)

curl --location --request POST '127.0.0.1:8001/v1/statement/' --header 'Content-Type: text/plain' --data-raw 'SELECT avg(number) FROM numbers(1000000000)'
# curl: (56) Recv failure: connection reset by peer.

```

### What You Expected?

`databend-query` was healthily pumped up and running in docker, as same as `datafuselabs/databend:latest` pulled from dockerhub.
![图片](https://user-images.githubusercontent.com/44747719/153713333-0b47f142-e5ab-40ed-ab3a-c903f2b58c59.png)

Try to connect:
> `clickhouse` client is still unusable.
![图片](https://user-images.githubusercontent.com/44747719/153714937-92422b01-eaa1-4c63-8907-d2a993439953.png)

### How to Reproduce?

Exactly as I described in `What's Wrong?`

### Anything Else?

Though knowing little about docker, after looking up `databend/docker/Dockerfile` and `dockerhub`, I consider `debian:buster` the one be to blame.
```dockerfile
# databend/docker/Dockerfile
FROM debian:buster
```
However, [`rootfs.manifest`](https://github.com/debuerreotype/docker-debian-artifacts/blob/de5fb2efd50a009baa2aaccd2b7874ec728bd7a9/buster/rootfs.manifest) of `debian:buster` contains nothing like `openssl` or `libssl`, this might be the cause.

Knowing nowhere to get the dockerfile of `datafuselabs/databend`, I don't know why `datafuselabs/databend` could work properly, neither...

```text
system: Arch Linux x86_64
kernel: Linux 5.15.19-1-lts
CPU: AMD Ryzen 7 5800H
rust toolchain: nightly 2022-02-07
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by ZhiHanZ** [comment]
Hi @ClSlaid , thank you for notification, command `make docker` mainly used to provide a docker for demo purpose and in production we use scripts from `make k8s-docker` to build databend-meta and databend-query separately and run them on production level kubernetes.
I think there are two tasks should be done for the demo dockerfile fix.
1. as you said, bump docker base image to debian:bullseye
2. incorporate the latest configuration file in both databend-query(https://github.com/datafuselabs/databend/blob/main/scripts/ci/deploy/config/databend-query-node-1.toml) and databend-meta(https://github.com/datafuselabs/databend/blob/main/scripts/ci/deploy/config/databend-meta-node-1.toml) for dockerfile binary configuration

**Comment by ClSlaid** [comment]
You almost told me the answer, 🤣
I'll PR this morning.

**Comment by ClSlaid** [comment]
> Hi @ClSlaid , thank you for notification, command `make docker` mainly used to provide a docker for demo purpose and in production we use scripts from `make k8s-docker` to build databend-meta and databend-query separately and run them on production level kubernetes. I think there are two tasks should be done for the demo dockerfile fix.
> 
>     1. as you said, bump docker base image to debian:bullseye
> 
>     2. incorporate the latest configuration file in both databend-query(https://github.com/datafuselabs/databend/blob/main/scripts/ci/deploy/config/databend-query-node-1.toml) and databend-meta(https://github.com/datafuselabs/databend/blob/main/scripts/ci/deploy/config/databend-meta-node-1.toml) for dockerfile binary configuration

`debian:bullseye` does not contain `GLIBC 2.32` and `GLIBC 2.33`, which makes the two programs not runnable, maybe use `ubuntu:22.04` instead.
