### ISSUE TITLE
Bug: `use database` in management mode

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4132]
**Summary**

Start the databend-query under management mode:
```
./scripts/ci/deploy/databend-query-management-mode.sh
```

Test:
```
> mysql -uroot -h127.0.0.1  -P3307

SUDO USE TENANT 'tenant1';
CREATE DATABASE IF NOT EXISTS tenant1_db;
USE tenant1_db; -- error here
```

**Comment by BohuTANG** [comment]
Maybe you are interested in this @TCeason :/

**Comment by TCeason** [comment]
Yeah, that’s a good issue.

**Comment by TCeason** [comment]
I see the code in `query/src/catalogs/impls/database_catalog.rs`, and find some other err.

```
root@mysqldb 11:40:33 [(none)]> use tenant1_db;
No connection. Trying to reconnect...
Connection id:    8
Current database: *** NONE ***

ERROR 1105 (HY000): Code: 1003, displayText = Cannot USE 'tenant1_db', because the 'tenant1_db' doesn't exist.
root@mysqldb 11:40:40 [(none)]> show databases;
ERROR 1105 (HY000): Code: 1101, displayText = Tenant can not empty(while get table).
root@mysqldb 11:40:50 [(none)]> create database tenant1_db;
ERROR 1105 (HY000): Code: 1101, displayText = Tenant can not empty(while create database).
root@mysqldb 11:41:08 [(none)]> drop database tenant1_db;
ERROR 1105 (HY000): Code: 1101, displayText = Tenant can not empty(while drop database).

```
And if I reconnect the server, and execute these cmd `show databases` | `create database` | `drop database` directly, all of them are work.

**Comment by TCeason** [comment]
And I have some question : 
a > why the show databases will return the err: Tenant can not empty(while `get table`). not `get database`
b > the management mode disables the SelectPlan? `Access denied for operation:"SelectPlan" in management-mode.`

**Comment by BohuTANG** [comment]
> And I have some questions:  a > why the show databases will return the err: Tenant can not empty(while `get table`). not `get database` 

We should add some logs to make we can trace them, like:
1. which tenant create database
2. which tenant show databases

> b > the management mode disables the SelectPlan? `Access denied for operation:"SelectPlan" in management-mode.`

Yes, the management mode only let the meta operation, it likes a meta client to talk with our metasrv(Or embedded).
Check is here:
https://github.com/datafuselabs/databend/blob/86fab7e1e46ced7806a5a20669b45369f6ec6668/query/src/interpreters/access/management_mode_access.rs#L33-L85

**Comment by TCeason** [comment]
I got the question. In management mode: we get tenant use this function:

```
    // Get current database.
    // If is management mode, return the current_tenant
    // Others return the config tenant config.
    pub fn get_current_tenant(&self) -> String {
        if self.conf.query.management_mode {
            let lock = self.current_tenant.read();
            lock.clone()
        } else {
            self.conf.query.tenant_id.clone()
        }
    }
```

But if use MySQL Typ, 
will create session: https://github.com/datafuselabs/databend/blob/main/query/src/servers/mysql/mysql_handler.rs#L83

we get tenant with the conf use MySQL Typ: 

https://github.com/datafuselabs/databend/blob/main/query/src/sessions/session_mgr.rs#L143

```
    pub fn create_session(self: &Arc<Self>, typ: impl Into<String>) -> Result<SessionRef> {
        let mut sessions = self.active_sessions.write();
        match sessions.len() == self.max_sessions {
            true => Err(ErrorCode::TooManyUserConnections(
                "The current accept connection has exceeded mysql_handler_thread_num config",
            )),
            false => {
                let session = Session::try_create(
                    self.conf.clone(),
                    uuid::Uuid::new_v4().to_string(),
                    typ.into(),
                    self.clone(),
                )?;
```

**Comment by BohuTANG** [comment]
Let's interactive with management mode with call function like `call SYSTEM$CREATE_TABLE(<tenant_id>, 'SQL format?')`.
