### ISSUE TITLE
test_management_mode test actually not running

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4134]
**Summary**

There are 2 issues for test_management_mode:
1. `test_management_mode test` actually not running, the CI pass is in wrong status:
https://github.com/datafuselabs/databend/runs/5172713388?check_suite_focus=true

2. Add `test_management_mode test` to production(now only run in Developing)
https://github.com/datafuselabs/databend/blob/9b004e0bc2969c42ee1658e2c3a11552cb9fead9/.github/workflows/developing.yml#L97-L106

**Comment by TCeason** [comment]
Got I’ll have a look

**Comment by TCeason** [comment]
> **Summary**
> 
> There are 2 issues for test_management_mode:
> 
> 1. `test_management_mode test` actually not running, the CI pass is in wrong status:
>    https://github.com/datafuselabs/databend/runs/5172713388?check_suite_focus=true
> 2. Add `test_management_mode test` to production(now only run in Developing)
>    https://github.com/datafuselabs/databend/blob/9b004e0bc2969c42ee1658e2c3a11552cb9fead9/.github/workflows/developing.yml#L97-L106

For Q1:
   [this yml](https://github.com/datafuselabs/databend/blob/e293ca21f9c6d6d6dd0f57265c19e87e1056db2a/.github/actions/test_management_mode/action.yml#L46) means just `matrix.config.os != 'ubuntu-latest'`, run the management mode test, but in the [dev yml](https://github.com/datafuselabs/databend/blob/93b70b3392f3fa506e2fb08cf7c844dbb9c5246a/.github/workflows/developing.yml#L114) the matrix.config.os is `ubuntu-latest`. So the test not run.

For Q2:

 Should add to [produce yml](https://github.com/datafuselabs/databend/blob/e20fd1561099fd097a273dbbcda6b705adb2e490/.github/workflows/production.yml#L119) and add publish_image.need.
