### ISSUE TITLE
Feature: dal2 layer metrics

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4140]
**Summary**
It would be nice to monitor on file system or S3 volume changes through dal2 metrics.
some of the metrics suggestions
 Metric name| Metric type | Labels/tags | Description
| ---------- | ----------- | ----------- | -------- |
| dal.s3.read_bytes | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| total read bytes on S3 given tenant and cluster|
| dal.s3.read_ops | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| number of read operation on S3 given tenant and cluster|
| dal.s3.write_bytes | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| total write bytes on S3 given tenant and cluster|
| dal.s3.write_ops | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| number of write operation on S3 given tenant and cluster|
| dal.fs.read_bytes | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| total read bytes on fs given tenant and cluster|
| dal.fs.read_ops | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| number of read operation on fs given tenant and cluster|
| dal.fs.write_bytes | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| total write bytes on fs given tenant and cluster|
| dal.fs.write_ops | Gauge | `tenant`=&lt;tenant-name&gt;  `cluster`=&lt;cluster-name&gt;  <br>| number of write operation on fs given tenant and cluster|

**Comment by ZhiHanZ** [comment]
I think it should be migrated to https://github.com/datafuselabs/opendal

**Comment by Xuanwo** [comment]
`opendal` has `Layer` support, so we can just implement inside databend without touching `opendal`.

**Comment by Xuanwo** [comment]
OpenDAL already has the following metrics (via [MetricsLayer](https://opendal.databend.rs/opendal/layers/struct.MetricsLayer.html))

- opendal_requests_total(service, operation)
- opendal_requests_duration_seconds(service, operation)

For example:

```rust
async fn stat(&self, args: &OpStat) -> Result<ObjectMetadata> {
    increment_counter!(
        METRIC_REQUESTS_TOTAL,
        LABEL_SERVICE => self.meta.scheme().into_static(),
        LABEL_OPERATION => Operation::Stat.into_static(),
    );

    let start = Instant::now();
    let result = self.inner.stat(args).await;
    let dur = start.elapsed().as_secs_f64();

    histogram!(
        METRIC_REQUESTS_DURATION_SECONDS, dur,
        LABEL_SERVICE => self.meta.scheme().into_static(),
        LABEL_OPERATION => Operation::Stat.into_static(),
    );

    result
}
```

---

And I'm interested in adding more metrics, as mentioned here.

The only question left to me is: Is the `tenant` and `cluster` labels must be set from the code? Or can we set them at the collector level?

@ZhiHanZ @flaneur2020

**Comment by ZhiHanZ** [comment]
For now, we do not have to add tenant and cluster labels as we could collect them by customized prometheus settings

**Comment by Xuanwo** [comment]
Cool! I will add them in opendal directly.

**Comment by Xuanwo** [comment]
This issue will be addressed by https://github.com/datafuselabs/opendal/issues/527

**Comment by Xuanwo** [comment]
Already fixed. @flaneur2020 @ZhiHanZ PTAL.

https://github.com/datafuselabs/opendal/blob/0b1ddb25592ec315162fb7ed9a702e3595e7fbff/src/layers/metrics.rs#L55-L65
