### ISSUE TITLE
bug:  Compile times double between v0.6.65-nightly vs v0.6.66-nightly

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4186]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.6.66-nightly

### What's Wrong?

build release:

Before:
    Finished release [optimized + debuginfo] target(s) in 6m 50s
    
After:
    Finished release [optimized + debuginfo] target(s) in 11m 31s

### What You Expected?

 x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PsiACE** [comment]
/assignme

For now, adding `common-functions = { codegen-units = 4 }` to `Cargo.toml` is a possible solution. 

> before:   Finished release [optimized + debuginfo] target(s) in 19m 45s
after:      Finished release [optimized + debuginfo] target(s) in 7m 57s


More investigation is needed and maybe I will find a better solution later.

**Comment by sundy-li** [comment]
I think it may relate to two fat matches of numeric datatypes in `pow`, `log` ...

**Comment by PsiACE** [comment]
https://users.rust-lang.org/t/5-hours-to-compile-macro-what-can-i-do/36508/3

**Comment by PsiACE** [comment]
> Great, so the main reason may be code bloat of [trigonometric](https://github.com/datafuselabs/databend/blob/dc058c9d22baa9e61763661f77cd10ec62c87c48/common/functions/src/scalars/maths/trigonometric.rs) ?

But trigonometric functions were not refactored in v0.6.66.

Need to check if, strings related, and interval functions

**Comment by sundy-li** [comment]
v0.6.65-nightly:  `Finished release [optimized + debuginfo] target(s) in 3m 53s`
 [v0.6.78-nightly](https://github.com/datafuselabs/databend/releases/tag/v0.6.78-nightly):  `Finished release [optimized + debuginfo] target(s) in 6m 54s`
 
Closing because it's better now after we upgrade to new datavalues.
