### ISSUE TITLE
bug: [Build] arm64 based release k8s docker build without libssl library dependencies

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4188]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.6.66

### What's Wrong?

currently we use cross(https://github.com/cross-rs/cross) for arm64 based cross compile and wrap them into a docker image, but seems like the base image has no libssl related library which introduce failure

### What You Expected?

clean vendored library dependency management, supposed to have some tests against release build docker images

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Should be fixed via musl static binaries.
