### ISSUE TITLE
performance drop 3 times after bump up opendal

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Before: DatabendQuery v-0.1.0-d2256c1-simd(1.60.0-nightly-2022-02-16T01:58:34.837999309+00:00)  
Current :  2022-02-17 latest version

### What's Wrong?

ontime datasets
Query:
```
SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue FROM lineorder_flat ;
```

Before:  0.143 sec
After: 0.407 sec

### What You Expected?

x

### Anything Else?

x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
@Xuanwo

**Comment by Xuanwo** [comment]
It's quite wired, in opendal v0.0.3 we introduce a fix which improve the performance on s3 a lot.

Can you provide the following details so that I can figure out what happened and find a solution:

- dataset
- SQL to create the table
- the test env: which storage scheme are you using? (fs? on tmpfs? local SSD?)

**Comment by sundy-li** [comment]
It's benched on Local SSD， I think any dataset(such as ontime)  using fuse engine can encounter this issue.

**Comment by BohuTANG** [comment]
This may be helpful https://databend.rs/learn/lessons/analyze-ontime-with-databend-on-ec2-and-s3
Note: This guidance is for s3 storage, if we not set the env, it will use the local disk.
cc @Xuanwo

**Comment by Xuanwo** [comment]
SeekableReader is not suitable for local fs, I'm working on a solution.

**Comment by Xuanwo** [comment]
Benchmark results:

## Old Query

DatabendQuery v-0.1.0-d2256c1-simd(1.60.0-nightly-2022-02-16T01:58:34.837999309+00:00)

![image](https://user-images.githubusercontent.com/5351546/154628712-2128120f-70f5-45c5-829c-a06d5dcda44b.png)

## Current main

```
commit d9b80226a616070079357d4f498c17913d711f9e (HEAD -> main, origin/main, origin/HEAD)
Merge: 980d3f022 e9d13f25a
Author: BohuTANG <overred.shuttler@gmail.com>
Date:   Fri Feb 18 08:40:04 2022 +0800

    Merge pull request #4192 from Veeupup/refactor_in

    refactor function in basic
```

![image](https://user-images.githubusercontent.com/5351546/154628804-7f3e4c6d-8fef-4ab8-bd06-36c1f7a75052.png)

## After optimized

![image](https://user-images.githubusercontent.com/5351546/154628853-7fbbbd7a-264a-4a63-ade5-9c3d577496e7.png)

---

Let me find a better way to organize the code layout, PRs will come later.

cc @sundy-li @BohuTANG
