### ISSUE TITLE
Add processor level profiling

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4238]
## Summary

To measure the performance of every processor, the profiles including:
* How much time each processor cost
* The total rows before processing
* The total rows after processing
* The total bytes before processing
* The total bytes after processing

Note:
We have did some work related to the processor profiling in the context query level, it's not an elegant solution.
E.g. get DALMetrics from query context, this should get from the Source Processor.

## Example

```
select count(YEAR), avg(ARRTIME) from ontime group by year;

Source Processor ----> Aggregate Processor --> Sink Processor
```

### Source Processor ⇢

* Attributes: [Full table name, Columns (2 / 109)]
* Statistics: [Scan progress, Bytes scanned, Percentage scanned from cache, Partitions scanned, Partitions total]
* Profile Overview: [Processing, Local Disk I/O, Remote Disk I/O]
<image src="https://user-images.githubusercontent.com/172204/155469285-3023d2ef-7ae4-4165-a79f-3fab7b576478.png" width="500">

### ⇢ Aggregate Processor ⇢

* Attributes: [Aggregate Functions, Grouping Keys]
* Profile Overview: [Processing]
<image src="https://user-images.githubusercontent.com/172204/155469607-1fd37322-1f07-47eb-9e93-b1385822df77.png" width="500">

### ⇢ Sink Processor

* Attributes: [List of Expressions]

<image src="https://user-images.githubusercontent.com/172204/155473126-bec7a920-3d07-42dc-b8aa-06bb92faac17.png" width="500">

## TODO

1. What's the format of all processor profile data (including DAG)?
2. How to get all the processor profile datas from the query context?

**Comment by BohuTANG** [comment]
Feel free to comments if have any thoughts @zhang2014

**Comment by sandflee** [comment]
is there any progress?

**Comment by zhang2014** [comment]
> is there any progress?

In progress. It's depend some refactor(we need to hold pipeline executor in query ctx).

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/pull/13637
