### ISSUE TITLE
Feature: Investigate the possibility to have `small_vec` into databend

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4248]
**Summary**

Description for this feature.

- small_vector in folly: https://github.com/facebook/folly/blob/main/folly/small_vector.h
- small_vector in rust: https://docs.rs/smallvec/latest/smallvec/

zhihu: https://www.zhihu.com/question/41691246/answer/1980691302

Maybe `small_vec` can be used in openkv.  cc @drmingdrmer 

I do not know any number of performances gained if we introduce `small_vec` into databend.

Maybe there are some places to replace `Vec` using `small_vec`

- `HashMethodSerializer::HashKey` to be `small_vec<u8>`
-  ....

Need deep investigation, just an issue marked here.

**Comment by drmingdrmer** [comment]
Great!

It seems that a lot of allocations on the heap will be saved with a proper config.

**Comment by sundy-li** [comment]
Addressed in #4353
