### ISSUE TITLE
num_cpus not logical cpus on AWS EC2

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4250]
**Summary**

EC2(c5.4xlarge ) is VCPU, `num_cpus::get()` returns `physical_cpus` not `logical_cpus`.
Instance type `c4.4xlarge` is ok.

**Comment by sundy-li** [comment]
It's because of `cgroup` limit.

https://github.com/seanmonstar/num_cpus/blob/master/src/linux.rs#L125-L150
