### ISSUE TITLE
bug: `SELECT number FROM numbers_mt(10) WHERE number > 8 LIMIT 2` returns 0 rows

### ISSUE THREAD

**Issue by platoneko** [datafuselabs/databend#4258]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend v0.6.74-nightly

### What's Wrong?

```
databend :) SELECT number FROM numbers_mt(10) WHERE number > 8 LIMIT 2

SELECT number
FROM numbers_mt(10)
WHERE number > 8
LIMIT 2

Query id: f69fb15f-4bf8-49c9-b79b-669d1138a71d

Ok.

0 rows in set. Elapsed: 0.034 sec.
```

### What You Expected?

```
┌─number─┐
│      9 │
└────────┘
```

### Anything Else?

```
databend :) SELECT number FROM numbers_mt(10) WHERE number > 8 LIMIT 10

SELECT number
FROM numbers_mt(10)
WHERE number > 8
LIMIT 10

Query id: 574d132e-964b-47bb-998e-1dbaa6350df1

┌─number─┐
│      9 │
└────────┘

1 rows in set. Elapsed: 0.034 sec. 
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Good catch！
I guess(haven't test on other engines e.g. Memory or Fuse yet) it's the numbers table bug.

If so, this will be helpful:
https://github.com/datafuselabs/databend/pull/4215

We can c

**Comment by sundy-li** [comment]
Limit pushdown should be rejected if filter is Some.
