### ISSUE TITLE
Feature: Make Pipeline work with Chunk instead of Block

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4260]
**Summary**

Description for this feature.

Since we already know the schema in Plan stage, so it's useless to have the schema inside the data pipeline.  cc @zhang2014   

-   Transformers
-   Source && AsyncSouce
-  Sink && AsyncSink

**Comment by zhang2014** [comment]
Added this to todo, but this may be a low priority task.

**Comment by BohuTANG** [comment]
This issue can be closed?

**Comment by sundy-li** [comment]
> This issue can be closed?

Still make sense, but in low-priority.
