### ISSUE TITLE
Improve the Exception subsystem: Databend-meta Address already in use [2]

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4280]
there is two issues about databend-meta  config :
$cat etc/databend-meta.toml
```
log_dir            = "/usr/local/databend/logs/_logs1"
metric_api_address = "0.0.0.0:28100"
admin_api_address  = "0.0.0.0:28101"
grpc_api_address   = "0.0.0.0:9191"

[raft_config]
id            = 1
raft_dir ="/usr/local/databend/data/_meta1"
raft_api_port = 28103
raft_listen_host = "127.0.0.1"
raft_advertise_host = "127.0.0.1"

# Start up mode: single node cluster
single        = true
```

# first 
nc -l 9191

/usr/local/databend/bin/databend-meta --config-file=/usr/local/databend/etc/databend-meta.toml

2022-03-01T00:13:23.910477Z  INFO databend_meta::api::grpc_server: metasrv returned res: Err(tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 48, kind: AddrInUse, message: "Address already in use" })))

**Want fix**
Error with port 

# second

nc -l 28103 

start databent-meta  without error
/usr/local/databend/bin/databend-meta --config-file=/usr/local/databend/etc/databend-meta.toml

```
$lsof -i:28103
COMMAND     PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
nc        41764 wubx    3u  IPv4 0x4265038ede80281      0t0  TCP *:28103 (LISTEN)
databend- 41826 wubx   44u  IPv4 0x4265038eb8397e1      0t0  TCP localhost:28103 (LISTEN)
```

**Want fix**
Error hint with port 

previously  https://github.com/datafuselabs/databend/issues/4231  thanks @[wangzhen11aaa](https://github.com/wangzhen11aaa)

**Comment by drmingdrmer** [comment]
interesting...
