### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4290]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest

### What's Wrong?

```
[ FAIL ] - result differs with:
--- /home/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.result	2022-03-01 15:23:47.195060096 +0000
+++ /home/runner/work/databend/databend/tests/suites/0_stateless/09_fuse_engine/09_0008_fuse_optimize_table.stdout	2022-03-01 15:37:35.486449100 +0000
@@ -6,7 +6,8 @@
 5
 6
 7
-1
+ERROR 1105 (HY000) at line 27: Code: 1024, displayText = fail to read block 29/70/_b/855b6a3b52c9401ab5314e68d6df5003.parquet, Code: 1024, displayText = External format error: underlying IO error: unexpected end of file..
+0
 5
 6
 7
```

### What You Expected?

*

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
https://github.com/datafuselabs/databend/runs/5377553663?check_suite_focus=true#step:3:1279

**Comment by Xuanwo** [comment]
The root cause is https://github.com/datafuselabs/opendal/issues/141, already fixed.
