### ISSUE TITLE
CALL: Trait for system function

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#4295]
**Tracking**

https://github.com/datafuselabs/databend/issues/4267

**Summary**

add a trait definition for system functions, allowing add system functions easily. 

some requirements:

- allow passing arbitrary arguments
- allows access control with privileges
- allows hide the function if current user do not have permission to this function

**Comment by ZhiHanZ** [comment]
I think it could be closed? cc  @Junnplus

**Comment by Junnplus** [comment]
@ZhiHanZ I think so. cc @flaneur2020
