### ISSUE TITLE
Improve: keep git history during workflow checkout

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#4300]
**Summary**

Due to the lack of git history, the release does not have access to contributors.

The solution to this problem is:
- upgrade actions/checkout to v3, and
- refer https://github.com/actions/checkout#usage to ensure that git history is available

Related: #2541

**Comment by PsiACE** [comment]
Of course, considering that checkout also takes time, we can also consider hard-coding. This requires an evaluation of the workflow time spent.

**Comment by drmingdrmer** [comment]
What about periodically building a list of contributors and saving it in a file?

**Comment by PsiACE** [comment]
> What about periodically building a list of contributors and saving it in a file?

I would like to avoid manual maintenance as much as possible.

**Comment by Xuanwo** [comment]
How about getting that info via GitHub API instead: https://docs.github.com/en/rest/reference/repos#list-repository-contributors

For example:

```shell
> curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/datafuselabs/databend/contributors
```

**Comment by PsiACE** [comment]
> How about getting that info via GitHub API instead

Good idea
