### ISSUE TITLE
Improve: generate a Rust file to save the credits

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#4301]
**Summary**

We currently use [cargo-license](https://github.com/onur/cargo-license) to generate [credits table](https://databend.rs/user/sql-statement/system-tables/system-credits).

This solution requires `Cargo.lock`, so it will be lost during the release process. It may be better to generate a hard-coded file directly.

Related: https://github.com/datafuselabs/databend/issues/2541

**Comment by Xuanwo** [comment]
What does "it will be lost during the release process" mean?

**Comment by PsiACE** [comment]
> What does "it will be lost during the release process" mean?

Sorry, I made a mistake here. It should read, "The release does not contain Cargo.lock or Cargo.toml, so it cannot get the credits correctly".

**Comment by Xuanwo** [comment]
Is there any block here that prevents us from adding `Cargo.lock` into the release? Generate a new file seems not good to me.

**Comment by PsiACE** [comment]
> Is there any block here that prevents us from adding `Cargo.lock` into the release? Generate a new file seems not good to me.

I think downloading Cargo.lock might be enough. Or we can try to embed it using rust-embed.

**Comment by Xuanwo** [comment]
Ohh, I got it. `release` here means our release binaries instead of the release process.

So this issue intends to generate a file during the release process and embed it into our release?
