### ISSUE TITLE
Feature: Support to use http handler restful api to fetch process lists given query node 

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4309]
**Summary**
In trinoDB, they support GET on  /v1/task, which returns
JSON document containing the list of TaskInfo for all tasks.

In databend-query, we could also support it in our http handler through GET /v1/query interface, and return processlists given node.

Alternative:
RPC interface also make sense

**Comment by youngsofun** [comment]
@ZhiHanZ Can I close this issue？

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ Can I close this issue？

For now, it is fine
