### ISSUE TITLE
Feature: metasrv: add API to return metrics

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#4311]
Add API to return raft metrics in:
https://github.com/datafuselabs/databend/blob/16e06e414c4680f0d640abada631af89369be877/metasrv/src/api/http_service.rs#L46-L57

The metrics can be retrieved from `HttpService.meta_node.raft.metrics()`

**Comment by RinChanNOWWW** [comment]
Hello @LiuYuHui , are you still working on this issue?

**Comment by LiuYuHui** [comment]
Hi @RinChanNOWWW , thanks for your reminder, please go ahead, sorry for the inconvenience.

**Comment by drmingdrmer** [comment]
Thanks man!

**Comment by drmingdrmer** [comment]
@lichuang 
Does the following PR fix this issue?
- #5376
