### ISSUE TITLE
Support LIMIT n BY expressions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#432]
**Summary**

ClickHouse:
https://clickhouse.tech/docs/en/sql-reference/statements/select/limit-by/

**Comment by TennyZhuang** [comment]
I'd like to try it

**Comment by TennyZhuang** [comment]
In [ClickHouse's implementation](https://github.com/ClickHouse/ClickHouse/blob/5dda97bef1f783964b8a57a69de16e8163cc1fc9/src/Processors/Transforms/LimitByTransform.cpp#L37), it seems that they use a hash based policy to group limit_by keys. It's difficult in current datafuse due to lack of value hash infrastructure. Is there some WIP works?

**Comment by TennyZhuang** [comment]
Oh, I find something useful in GroupByFinalTransform, I will take a try.

**Comment by BohuTANG** [comment]
@TennyZhuang 
block has add a groupby function, may be helpful: https://github.com/datafuselabs/datafuse/blob/e4e43319b9772a1cc29f7b0ccd1020e646da394d/common/datablocks/src/kernels/data_block_groupby.rs

**Comment by BohuTANG** [comment]
siphash is here: https://github.com/datafuselabs/datafuse/pull/694

**Comment by TennyZhuang** [comment]
@BohuTANG Currently, I've finished the planner and executor, and it works well. The only work remaining is to support it on parser. Unfortunantly, sqlparser doesn't support LIMIT BY cause, and sqlparser is lack of dialact support.

While more clickhouse dialact will be supported in the future, we will encounter the same problems many times.

We have two options now:

1. like datafusion, use custom data structure wrapped with sqlparser's data structure. https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/sql/parser.rs . There will be many refactor works.
2. Fork sqlparser and maintain it by ourselves.

And another question is that, it seems that Both works are non-trivial and I think we should implement it in a separate PR, should I submit my PR now with `LimitByPlan`, `LimitByTransform` and `LimitByStream` compiled and test passed?

**Comment by BohuTANG** [comment]
@TennyZhuang 
Thanks a lot, nice work.
For the customize sql datafuse has https://github.com/datafuselabs/datafuse/blob/master/fusequery/query/src/sql/sql_parser.rs and there are many examples can be referenced.

It's make sense to split a big patch to many pieces if it needs.
FYI, the limit by parser is not very complicated and recommended to be done in one patch.
What do you think?

**Comment by BohuTANG** [comment]
@TennyZhuang 

All is ok to me for `should I submit my PR now with LimitByPlan, LimitByTransform and LimitByStream compiled and test passed?`.
Let's Pull Request it.

**Comment by sundy-li** [comment]
cc @TennyZhuang , sqlparser is move into https://github.com/datafuse-extras/sqlparser-rs  in #753. 

Feel free to refactor the parser.

**Comment by TennyZhuang** [comment]
> cc @TennyZhuang , sqlparser is move into https://github.com/datafuse-extras/sqlparser-rs in #753.
> 
> Feel free to refactor the parser.

Got it, I will finish it.

**Comment by BohuTANG** [comment]
@TennyZhuang 
Hi!
We plan to restart this issue(next week this issue will be reset, or someone can take it) .
Thanks again for your work, if you have any questions we are always happy to talk.

**Comment by BohuTANG** [comment]
Thank you for your preliminary work @TennyZhuang , we are ready to restart this task and welcome any feedback :)

**Comment by Xuanwo** [comment]
@leiysky Is this issue still valid now?

**Comment by leiysky** [comment]
> @leiysky Is this issue still valid now?

We have supported this now, I'll close the issue.
