### ISSUE TITLE
Feature: Add graceful shutdown API for query nodes 

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4332]
**Summary**
Similar to trino https://trino.io/docs/current/admin/graceful-shutdown.html, which provided a RESTful interface to terminate a query node properly, we should also provide it for more predictable behaviors
Shutdown steps:
1. Once receive shutdown signal, it would not allow to access new coming queries
2. query node would continue to process unfinished plans
3. once all plans get finished, it would disconnect from the query cluster and shutdown given grace period

It is largely an internal call, put into RPC interface similar to cockroach drain make senses.

**Comment by GrapeBaBa** [comment]
@ZhiHanZ AFAIK, the query plans will distribute to multi query nodes; we need consider a crossing nodes check.Right?

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ AFAIK, the query plans will distribute to multi query nodes; we need consider a crossing nodes check.Right?

in desired， each node contains a state, if the node is under terminated state, it should be able to process the rest of the plan under the node, and would not be able to accept new requests or plan, after the rest of the plans are finished, it then shutdown.
But for current part, we could skip the hardest part about multi node communication, and do the rest of the two things.
1. Stop accept query
2. Remove it from cluster.

Since we could use query log table to check current process lists under a node, and only shutdown nodes which have no running plan

**Comment by zhang2014** [comment]
> Stop accept query.
this is supported.

**Comment by GrapeBaBa** [comment]
> > Stop accept query.
> 
> this is supported. Maybe we need support admin$graceful_shutdown procedure

I read the codes and found server shutdown already support graceful, and abort_handle will reject accept connection once    
shutdown invoked. So for this task, we only need add an admin$graceful_shutdown procedure to trigger server shutdown.Right? @zhang2014 
```rust
    pub async fn shutdown(&mut self, mut signal: SignalStream) {
        self.shutdown_services(true).await;
        self.sessions
            .get_cluster_discovery()
            .unregister_to_metastore(&mut signal)
            .await;
        self.sessions.graceful_shutdown(signal, 5).await;
        self.shutdown_services(false).await;
    }
```

**Comment by zhang2014** [comment]
> I read the codes and found server shutdown already support graceful, and abort_handle will reject accept connection once
shutdown invoked. So for this task, we only need add an admin$graceful_shutdown procedure to trigger server shutdown.Right? @zhang2014

Yes, I think it is. CC: @ZhiHanZ
