### ISSUE TITLE
Feature: record parse time，analyze time，execute time in a query_context and query_log

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#4338]
**Summary**

- more specific 
- http handler can use it directly (instead of record them itself)
- may help to find some bugs

**Comment by ZhiHanZ** [comment]
in duckDB, profiling time could be parsed as a json file, I think we could also provide some json uri for the profiling graph and shouw uri location in query log.
https://duckdb.org/dev/profiling

**Comment by BohuTANG** [comment]
@ZhiHanZ , This will be addressed in our new processor level profiling.

**Comment by GrapeBaBa** [comment]
@BohuTANG any work need to do for this issue?

**Comment by BohuTANG** [comment]
Databend now has a powerful profie. Let's close this.
