### ISSUE TITLE
Feature: dynamically configuration updates on tenant and custer id through CALL command

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4344]
**Summary**
By dynamic config on tenant and cluster id, it is possible to build a pool of pods serve as prewarm pool for faster startup time

**Comment by BohuTANG** [comment]
Which RPC? Could you give an example for the RPC api looks like.

**Comment by ZhiHanZ** [comment]
Personally I prefer to wrap all admin settings as an RPC server serving for cluster management issues, similar to the settings in cockroach, they provided similar approach for multi-tenant environment
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20211106_multitenant_cluster_settings.md
https://github.com/cockroachdb/cockroach/pull/74268/files

With the help of admin RPC interfaces, we could possiblely
1. dynamically update on tenant, and cluster id for query node
2. drain query node for graceful shutdown https://github.com/datafuselabs/databend/issues/4332
3. fetch cluster informations such as process list, query logs for administration decisions(auto scaling) https://github.com/datafuselabs/databend/issues/4309

**Comment by BohuTANG** [comment]
Does the `call function` like `call admin$tenant_reset('xx', 'yy')` address it?

**Comment by BohuTANG** [comment]
The admin settings looks is the global level not the session, so the hard part is that how we know the compute has others body using it now?

**Comment by ZhiHanZ** [comment]
> Does the `call function` like `call admin$tenant_reset('xx', 'yy')` address it?

It should be a good idea

**Comment by ZhiHanZ** [comment]
> The admin settings looks is the global level not the session, so the hard part is that how we know the compute has no others using it now?

it should be resolved by upper layer
