### ISSUE TITLE
bug: config overwrite when specify `--config` and any other command line args.

### ISSUE THREAD

**Issue by DCjanus** [datafuselabs/databend#4362]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

git commit ID: a6b2d4db98492ebfa871f277d57616e7f0335110

### What's Wrong?

For example, with [those lines](https://github.com/datafuselabs/databend/blob/a6b2d4db98492ebfa871f277d57616e7f0335110/query/src/bin/databend-query.rs#L37-L49), if we specify command line arguments like this `--config config.toml --log_level DEBUG`, the log level would not be `DEBUG`, if not specified from other source.

### What You Expected?

Merge command line arguments with other configuration sources.

### Anything Else?

There is a [crate](https://docs.rs/config/latest/config/) provide multiple configuration sources support, but to combine with `clap`, there would be a lot of job to be done.

To resolve this issue, maybe we should discuss about whole config system.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by DCjanus** [comment]
If someone trying to fix this, feel free to assign yourself.

**Comment by BohuTANG** [comment]
Currently, `Config::load_from_args` and `Config::load_from_toml` are exclusive, for this issue, we should do some merge between them.

**Comment by DCjanus** [comment]
Sorry for delay, there is so many boring jobs in my official job to lose energy. I've noticed that my friend @Xuanwo  has been took this issue, that's really great.

About this issue, there is draft in my mind: keep config types that drived with `clap::Parser` or `clap::Args`, and implement `config::Source` to `databend_query::config::Config`, and then, code would be like this:

```rust
impl Config {
    pub fn load() -> anyhow::Result<Self> {
        let c = Config::parse();

        let mut cfg_builder = ::config::Config::builder();

        let clap_source = ::config::Config::try_from(&c)?;
        cfg_builder = cfg_builder.add_source(clap_source);

        if !c.config_file.is_empty() {
            let config_file = Path::new(&c.config_file);
            let file_source = ::config::File::from(config_file);
            cfg_builder = cfg_builder.add_source(file_source);
        }

        let c = cfg_builder.build()?.try_deserialize()?;

        Ok(c)
    }
}
```

And boom, now we've able to load config from env, cli and local config file, with order.

**Comment by Xuanwo** [comment]
I happen to have similar thoughts: https://github.com/mehcode/config-rs/issues/315
