### ISSUE TITLE
Feature: switch to nexttest in ci

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4376]
**Summary**

Description for this feature.

Refer:  https://nexte.st/book/installing-from-source.html

**Comment by PsiACE** [comment]
In my limited experience, it may not currently work properly in databend.

may need wait https://github.com/nextest-rs/nextest/issues/29

**Comment by Xuanwo** [comment]
Wow, wait, `nextest` has native support for skipped tests?

**Comment by PsiACE** [comment]
> Wow, wait, `nextest` has native support for skipped tests?

The problem we are currently experiencing is that an error is reported about `--exact` not being supported, which prevents us from completing the test correctly with nextest.

But in fact, we don't explicitly use the `--exact` option to skip tests.

**Comment by Xuanwo** [comment]
metasrv unit tests can't pass if using `nextest`.
