### ISSUE TITLE
Feature: [metasrv]: add API watch

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#4393]
**Summary**

A client requests metasrv to create a stream to receive events about a key.

A good reference of watching API is: etcd-v3 watch API: https://etcd.io/docs/v3.2/learning/api/#watch-api

- [ ] Add grpc API to create watch stream to `meta.proto`: 
    ```
      rpc Watch(WatchRequest) returns (stream WatchReply) {}
    ```
- [ ] When metasrv receives a `WatchRequest`, it subscribes to a queue for apply events.
- [ ] #4607

**Comment by drmingdrmer** [comment]
TODO: split into sub issues

**Comment by flaneur2020** [comment]
can we take advantage of the Watch API to make a distributed lock? maybe there are cases like a distributed task (https://docs.snowflake.com/en/sql-reference/sql/create-task.html), each task has to be executed ONCE in a query instance, avoiding two query instances get executed in the same time.

**Comment by drmingdrmer** [comment]
Yes, a lock can be implemented with **watch**.

But the execute-exactly-once semantic can not be implemented with just a `lock`. You still need some stateful service to store if the task has already been executed.

**Comment by BohuTANG** [comment]
This issue seems can be closed after https://github.com/datafuselabs/databend/pull/4779 @drmingdrmer
