### ISSUE TITLE
Feature: Support CALL RELOAD_CONFIG

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#4398]
**Summary**

Reload items:
- [ ] Tenant config
- [ ] Cluster config
- [ ] Meta service config
- [ ] clear caches.

CC: @ZhiHanZ

**Comment by ZhiHanZ** [comment]
we shoud also support to reload data access layer with the help of https://github.com/datafuselabs/opendal/issues/140

**Comment by BohuTANG** [comment]
> we shoud also support to reload data access layer with the help of [datafuselabs/opendal#140](https://github.com/datafuselabs/opendal/issues/140)

Did it in the databend(PR #4407):
https://github.com/datafuselabs/databend/pull/4407/files#diff-05e190acf915432f50b78d25482d816df331623745159f6e235f255aa4c73516R384
