### ISSUE TITLE
Feature: Improve insert into performance

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4413]
**Summary**

Description for this feature.

Query:

```
INSERT INTO `books` VALUES ('Transaction Processing','Jim Gray', 1992),('Readings in Database Systems','Michael Stonebraker', 2004);
```

The entire SQL goes into SQL parser and expression-executor, because we can have expression inside VALUES, eg:

```
INSERT INTO `books` VALUES ('Transaction Processing','Jim Gray', now() - 3),('Readings in Database Systems','Michael Stonebraker', 2004);
```

To support expressions, this insert SQL works really slow. We can improve the performance by:

1. Use [source_values](https://github.com/datafuselabs/databend/blob/v0.6.26-nightly/common/streams/src/sources/source_values.rs) by default.
2. If error happens, fall back to current way.

**Comment by ygf11** [comment]
@sundy-li I find a way to address the lifetime, will create a draft pr soon.
