### ISSUE TITLE
bug: Use mariadb-client to connect databend-query will results in buggy behavior

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#4429]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-query built via `07b14ceacef62eb8b5fba1fb8a74abcaee4db0dc`

### What's Wrong?

It seems that the query has been buffered wrongly.

> `mysql` is alias to `mariadb-client` on Archlinux.

```sql
:) mysql -uroot -h127.0.0.1 -P3307
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.26-0.1.0-e661ee7-simd(1.61.0-nightly-2022-03-13T11:45:52.777998283+00:00) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> use db;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MySQL [db]> select * from t;
ERROR 2027 (HY000): Received malformed packet
MySQL [db]> select * from t;
<content here>
9705 rows in set (0.003 sec)
```

NOTE: `select * from t` should be time consuming query that will take at least **6s**.

For the first `select * from t` query:

- Error `Received malformed packet` returned as soon as possible
- `databend-query` keeps output logs, seems that the query is still running on.

For the second `select * from t` query:

- The query returns in `0.003s` (it's impossible)

If I start via `mysql -uroot -h127.0.0.1 -P3307 -A`, everything works fine:

```sql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.26-0.1.0-e661ee7-simd(1.61.0-nightly-2022-03-13T11:45:52.777998283+00:00) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> use db;
Database changed
MySQL [db]> select * from t;
<content here>
9705 rows in set (13.852 sec)
```

### What You Expected?

`databend-query` works the the same both `mysql -uroot -h127.0.0.1 -P3307 -A` and `mysql -uroot -h127.0.0.1 -P3307`

### How to Reproduce?

- Create db
- Connect with mariadb client

### Anything Else?

MariaDB-clients version

```shell
:) paru -Q mariadb-clients
mariadb-clients 10.7.3-1
:) mysql --version
mysql  Ver 15.1 Distrib 10.7.3-MariaDB, for Linux (x86_64) using readline 5.1
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
not fixed yet,  some clue：

when client user execute `Use <database>`, server receive these commands

- with - A 
  - Query(select database()).   # not supported, but not further either caused by it
  - Init(use <database>) 
- Without -A 
  - Query(select database())
  - Init(use <database>) 
  - Query(show databases)
  - Query(show table)
  - ListFields(_)   # not implemented

**Comment by Junnplus** [comment]
Seems to be caused by invalid column definitions
https://github.com/datafuselabs/opensrv/blob/main/mysql/src/lib.rs#L564-L575

**Comment by Junnplus** [comment]
@Xuanwo I make a draft PR https://github.com/datafuselabs/databend/pull/4626 for fix this, can you help me test it?

**Comment by Xuanwo** [comment]
Of course, I will test against the draft PR.

**Comment by Xuanwo** [comment]
@Junnplus, I confirmed that #4626 fixed this issue, thanks for debugging!
