### ISSUE TITLE
Default column to `NOT NULL`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4435]
**Summary**

1. For performance
2. For the user experience: simple to do when creating table
3. If user want null(Assume who knows what's the NULL is), explicit `<column_name> <column_type> [NULL]`

**Comment by BohuTANG** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
Tasks to do:

- [ ] Support  `<column_name> <column_type> [NULL]` in SQL Parser
- [ ] Fix unit tests && stateless tests after this refactor.
