### ISSUE TITLE
Mask storage.s3  `access_key_id` and `secret_access_key`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4436]
**Summary**

```
mysql> select * from system.configs where name like 's3%';
+--------------------------+--------------------------+---------+-------------+
| name                     | value                    | group   | description |
+--------------------------+--------------------------+---------+-------------+
| s3.region                |                          | storage |             |
| s3.endpoint_url          | https://s3.amazonaws.com | storage |             |
| s3.access_key_id         |                          | storage |             |
| s3.secret_access_key     |                          | storage |             |
| s3.enable_pod_iam_policy | false                    | storage |             |
| s3.bucket                |                          | storage |             |
| s3.root                  |                          | storage |             |
+--------------------------+--------------------------+---------+-------------+
```

**Comment by Xuanwo** [comment]
As a best practise, we often mask `access_key_id` and `secret_access_key` to `<redacted>`.

To avoid confusing users, it's better to mask it as `<empty>` if the value is empty.

And we should implement `Debug` manually for a struct that contains credentials to avoid printing them into logs. (Or implement in logger instead)

**Comment by Xuanwo** [comment]
Something optional: we can also redact `endpoint` and `bucket` so that the user's bucket will not be leaked publicly. This can prevent the user's bucket from maliciously sending requests to create huge orders.

However, this change could make debugging more complex. Maybe we can enforce redacting `access_key_id` and `secret_access_key`, but leave `bucket` and `endpoint` configurable.

**Comment by BohuTANG** [comment]
We have done some works on meta config:
https://github.com/datafuselabs/databend/blob/6a3a7c3d9a8b40dd43978b0abe889b20d75e27b5/query/src/configs/config_meta.rs#L141-L148

**Comment by RinChanNOWWW** [comment]
> Something optional: we can also redact `endpoint` and `bucket` so that the user's bucket will not be leaked publicly. This can prevent the user's bucket from maliciously sending requests to create huge orders.
> 
> However, this change could make debugging more complex. Maybe we can enforce redacting `access_key_id` and `secret_access_key`, but leave redacting `bucket` and `endpoint` configurable.

If redacting `bucket` and `enpoint` can be configured, for example, configured by `hide_bucket` and `hide_endpoint`, should `hide_bucket` and `hide_endpoint` be shown in the table `system.configs`?

**Comment by BohuTANG** [comment]
I think we can only mask them, like `*****[XXX]`, and keep the 3-byte suffix for verify.

**Comment by BohuTANG** [comment]
BTW, `system.configs` only accessed by the root user, we mask part of them to avoid copy out.
