### ISSUE TITLE
Feature:  CreateTable validation

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4441]
**Summary**

Description for this feature.

These all work but are incorrect, can be avoided in `InterpreterCreateTable`.
```
 create table t (a UInt32)  Engine = Fuse1;
 create table t2 (a UInt32)  Engine = Fuse SNAPSHOT_LOC_XXX  ='1/22/_ss/55577ee30e8347a48f57a304daa2a715';
```

**Comment by chienguo** [comment]
Can you be more specific about what kinds of validation we can do? Except this unknown table engine here. Thanks.

**Comment by sundy-li** [comment]
AFAIK:

1. Unknow engine name.
2. Unknow Engine Properties for a specific engine.

**Comment by chienguo** [comment]
I created a PR https://github.com/datafuselabs/databend/pull/4495, tring to add this feature.
