### ISSUE TITLE
[ci] Stateful tests did not run on StorageType S3

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4442]
**Summary**

https://github.com/datafuselabs/databend/blob/aa7223ef386dda92601cf4ddba435aeab9b63776/scripts/ci/ci-run-stateful-tests-standalone-s3.sh#L11-L21

Though we set `STORAGE_TYPE=s3` in env, the deploy scripts start `databend-query` with config, so it will run  on local disk...

**Comment by wubx** [comment]
effect me

**Comment by BohuTANG** [comment]
After https://github.com/datafuselabs/databend/blob/85878247b295863000134ab569205ae7a9247b08/query/src/sessions/session_mgr.rs#L371 need load from env? cc @zhang2014

**Comment by BohuTANG** [comment]
I have check the main branch, it works for me.
For the config load, we first load from the file then try to load from env:
https://github.com/datafuselabs/databend/blob/85878247b295863000134ab569205ae7a9247b08/query/src/bin/databend-query.rs#L38-L51

**Comment by BohuTANG** [comment]
Check steps:
1. env
```
 export STORAGE_TYPE=s3 
 export S3_STORAGE_BUCKET=testbucket 
 export S3_STORAGE_ROOT=admin 
 export S3_STORAGE_REGION=us-east-1 
 export S3_STORAGE_ENDPOINT_URL=http://127.0.0.1:9900 
 export S3_STORAGE_ACCESS_KEY_ID=minioadmin 
 export S3_STORAGE_SECRET_ACCESS_KEY=minioadmin 
```

2. start databend-query
```
 ./target/debug/databend-query -c scripts/ci/deploy/config/databend-query-embedded-meta.toml 

```

3. check the config from the server log
```
storage: StorageConfig { storage_type: "s3", storage_num_cpus: 0, disk: DiskStorageConfig { data_path: "stateless_test_data", temp_data_path: "" }, s3: {s3.storage.region: "us-east-1", s3.storage.endpoint_url: "http://127.0.0.1:9900", s3.storage.bucket: "testbucket", }, azure_storage_blob: {Azure.storage.container: "", } 
```
