### ISSUE TITLE
ALTER TABLE [ IF EXISTS ] <name> RENAME TO <new_table_name>

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4459]
**Summary**

After https://github.com/datafuselabs/databend/pull/4425 merged, it's time to add:
```
ALTER TABLE [ IF EXISTS ] <name> RENAME TO <new_table_name>
```

**Comment by kevinw66** [comment]
Sorry, I have a question.
Should we translate to rename table entity like `statement` or `plan` in a step.
Or we copy the code from `rename table interpreter` to `alter table interpreter`?

**Comment by BohuTANG** [comment]
I think we can rewrite the `ALTER TABLE [ IF EXISTS ] <name> RENAME TO <new_table_name>` to rename plan and interpreter.

**Comment by BohuTANG** [comment]
Translate the `ALTER TABLe RENAME TO` to `PlanNode::RenameTable` here:
https://github.com/datafuselabs/databend/blob/3b21104535dc96344176bf714888472f8418274a/query/src/sql/statements/statement_rename_table.rs#L38-L54

**Comment by kevinw66** [comment]
@Junnplus Should we add `if exists` check on meta api ?

**Comment by kevinw66** [comment]
> @BohuTANG @Junnplus Should we add `if exists` check on meta api ?

I'll try to add the check.
