### ISSUE TITLE
Feature: auto rotate old log files

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#4467]
**Summary**

add config for log retention days

**Comment by ZhiHanZ** [comment]
![image](https://user-images.githubusercontent.com/25170437/158532235-6205800c-3ccd-447b-bb7a-229f0a66a617.png)
in a long running meta service, log file occupid 95% storage space, which is worth optimization, I think raft data could also have some optimizations as well? @drmingdrmer

**Comment by drmingdrmer** [comment]
> I think raft data could also have some optimizations as well?

I do not get it. What kind of optimization do you mean? 🤔

**Comment by ZhiHanZ** [comment]
> > I think raft data could also have some optimizations as well?
> 
> I do not get it. What kind of optimization do you mean? thinking

Here I mean about add some rotation and compression for smaller raft directory size

**Comment by drmingdrmer** [comment]
Should this be done inside metasrv process? I suppose there will be some maintaining script cleaning up logs for both query and metasrv or other processes.

**Comment by ZhiHanZ** [comment]
> Should this be done inside metasrv process? I suppose there will be some maintaining script cleaning up logs for both query and metasrv or other processes.

This feature request mainly derived from our discussion in here: https://github.com/datafuselabs/databend/pull/4462/files#r827667010, I think we should run regular maintainence scripts in combine with the effort from meta service and query service.
As an example, etcd provides the following features
1. configure auto-compaction retention (like set compaction for 1 hour)
2. provide snapshot backup (with the help from etcdctl)

**Comment by drmingdrmer** [comment]
metasrv uses `common_tracing::init_global_tracing()` in which the logs will be rotated the same as https://github.com/datafuselabs/databend/pull/4462/files#r827667010

Have you had a metasrv that does not split log files hourly?


> As an example, etcd provides the following features https://etcd.io/docs/v3.4/op-guide/maintenance/
> 
> 1. configure auto-compaction retention (like set compaction for 1 hour)


This is about the raft log, which is part of the raft, being stored in `./data/raft` in this case, not the logging log.

> 2. provide snapshot backup (with the help from etcdctl)

Snapshot backup is a little bit out of topic, maybe we could discuss it in another issue?

**Comment by ZhiHanZ** [comment]
It could be closed, we implemented some sidecar for log rotation :)
