### ISSUE TITLE
Consider removing management mode

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4474]
**Summary**

Because we have `admin$func`, the management mode is no used anymore.
We need more admin procedure to do it.

**Comment by BohuTANG** [comment]
cc @flaneur2020 @Junnplus

**Comment by ZhiHanZ** [comment]
I think we still need management mode to interact with meta service if no query mode is up.
Possible use cases:
1. Bootstrap tenant info
2. Manage object metadata with permission control

**Comment by BohuTANG** [comment]
Ok, but we don't need:
1. `sudo set tenant` statement
2.  Access check:
https://github.com/datafuselabs/databend/blob/76251a1ce74f5cf6efb695f113ff9ea41c71d7e6/query/src/interpreters/access/management_mode_access.rs#L34
