### ISSUE TITLE
Feature: ColumnBitmap support

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4487]
**Summary**

Description for this feature.

- Support Column Bitmap:  `pub type  BitmapColumn = ObjectColumn<RoaringBitmap>;`,  refer [here](https://github.com/datafuselabs/databend/blob/8173f0a1d4d8c7875f809291106bdb96c6916677/common/datavalues/src/columns/object/mod.rs)
- Use [Roaring-rs](https://github.com/RoaringBitmap/roaring-rs)

**Comment by PsiACE** [comment]
/assignme

I want to try
