### ISSUE TITLE
stage: remove stage files

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4491]
Removes files from either an external (external cloud storage) or internal stage.
Synatx:
```
REMOVE stage [ PATTERN = '<regex_pattern>' ]
```

Where
```
stage ::=
    @[<stage_name>[/<file>]
```

**Comment by sundy-li** [comment]
Is it `test1` ?

**Comment by Kikkon** [comment]
> Is it `test1` ?
I wrote the wrong list command which should be
`list @my_int_stage`

**Comment by sundy-li** [comment]
Reproduced.

```
:) list @my_int_stage;
Empty set (0.05 sec)

:) list @my_int_stage/test1;
ERROR 1105 (HY000): Code: 3001, displayText = entity not found (object error: (op: stat, path: admin/stage/my_int_stage/test1, source: response part: Parts { status: 404, version: HTTP/1.1, headers: {"accept-ranges": "bytes", "content-length": "0", "content-security-policy": "block-all-mixed-content", "server": "MinIO", "strict-transport-security": "max-age=31536000; includeSubDomains", "vary": "Origin", "vary": "Accept-Encoding", "x-amz-request-id": "16F481175D5EE268", "x-content-type-options": "nosniff", "x-xss-protection":
:)
```

But minio has this file in web view.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3325189/171412279-a7091bf2-43de-4423-9e77-c8aabfb91ac2.png">

@Xuanwo  Can you help this issue ?

**Comment by Kikkon** [comment]
> It's a bug inside databend-query's `get_abs_path`, I will fix it.

@Xuanwo  When you fix it, you can ping me again, thx 🤣

**Comment by Xuanwo** [comment]
> @Xuanwo  When you fix it, you can ping me again, thx 🤣

I will link to this issues :love:

**Comment by Xuanwo** [comment]
Hi, I believe #5727 should fix the problem

Given stage:

![image](https://user-images.githubusercontent.com/5351546/172035860-cee36d90-d290-4817-8d68-e0c94c444f15.png)

List in SQL:

![image](https://user-images.githubusercontent.com/5351546/172035858-3d373c1c-1cec-4b78-8afe-e73fd78921d6.png)
