### ISSUE TITLE
Unloading data into stage

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4498]
**Summary**

* Unloading into a Databend Internal Stage
* Unloading into a Databend External Stage

```
COPY INTO { internalStage | externalStage | externalLocation }
     FROM { [<database_name>.]<table_name> | ( <query> ) }
[ FILE_FORMAT = ( { TYPE = { CSV | JSON | PARQUET } [ formatTypeOptions ] } ) ]
[ copyOptions ]
[ VALIDATION_MODE = RETURN_ROWS ]
```

Reference:
https://docs.snowflake.com/en/user-guide-data-unload.html

**Comment by BohuTANG** [comment]
Seems we need a Input and Output Format crate with write&read trait? Now, the csv/parquet only has read,  cc @sundy-li

**Comment by BohuTANG** [comment]
For parquet Input/Output format, fuse engine can re-use it too.

**Comment by wubx** [comment]
if  use CSV, JSON support zip?

**Comment by BohuTANG** [comment]
> if use CSV, JSON support zip?

Sure
