### ISSUE TITLE
The develop demo lost : create if not exists book_db

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4510]
https://databend.rs/doc/develop/golang

https://databend.rs/doc/develop/python

expect:
add : create if not exists book_db;

**Comment by Milittle** [comment]
I put some simple impl, pls help me review it.
https://goplay.tools/snippet/zSsN8tQMmBd

**Comment by BohuTANG** [comment]
@Milittle Thank you, welcome the PR

**Comment by Milittle** [comment]
> @Milittle Thank you, welcome the PR

Okay, I will pull new one. :)

**Comment by Milittle** [comment]
https://github.com/datafuselabs/databend/pull/4512
pr is here
