### ISSUE TITLE
Refine the implementation of fuse table optimize

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#4523]
**Summary**

Currently, the impl of table optimization may accumulate too much memory unnecessarily. Seems that some intermediate allocations of `Vector`s could be  avoided by using streams.

**Comment by dantengsky** [comment]
tacking back to issue #4922

**Comment by youngsofun** [comment]
when execute `select * from ontime`

is it possible the handler receives a block of 600k rows of data?

@dantengsky 

HTTP handler long-pulling resp to a req once >= 10000 rows accumulate,  expecting  the Datablock not be much large than this.
