### ISSUE TITLE
Feature: Avoid string clone in `QueryContextShared.get_query_str`

### ISSUE THREAD

**Issue by ygf11** [datafuselabs/databend#4539]
**Summary**

Sql may be very long, such as `insert into` with many rows as values, 

We can wrap `String` as `Arc<String>` to avoid string clone here.

https://github.com/datafuselabs/databend/blob/7597424ad08213f8d019a544e73b45691627b0f4/query/src/sessions/query_ctx_shared.rs#L69

https://github.com/datafuselabs/databend/blob/7597424ad08213f8d019a544e73b45691627b0f4/query/src/sessions/query_ctx_shared.rs#L226-L229

**Comment by BohuTANG** [comment]
If a sql larger than 10K, we can truncate it?
I think the large case almost is insert with values.

**Comment by ygf11** [comment]
> If a sql larger than 10K, we can truncate it?
I think the large case almost is insert with values.

Yes, it is insert with values.

I'm doing #4497. We can get `Values-String` from two source:
1. From `Vec<Vec<Expr>>`
2. `QueryContextShared.get_query_str()`

To avoid extra `clone` or `traverse` here , the `second` can be a workable choice if we do not have a better idea.

**Comment by sundy-li** [comment]
We need some ugly lifetime mark here, but it's needed.

**Comment by BohuTANG** [comment]
@sundy-li 
Looks good.
Large values is like a csv/parquet/json stream, and only allow from http handler.

**Comment by ygf11** [comment]
> What about to have a new WrapInsertStatement

I am not really get it. Could you go into more detail?

**Comment by sundy-li** [comment]
```
enum WrapInsertStatement {
      SqlInsertStmt(StatementWithSql) /// ---> to_go_to_values_source
      Parser(InsertStatement)  /// ---> Vec<Vec<Expr>>
}
```

1. For example, a big insert SQL,  `let insert_sql: &str =  "insert into table values (xxx), (xxx), (xxx) ..."`

2. When it goes into SQLParse, we parse it into `StatementWithSql` by default:

```
StatementWithSql<'a> {
	db : String,
	table : String,
	sql: &'a str, // the whole insert_sql sql
	values: &'a str // (xxx), (xxx), (xxx)
}
```

3. Then we parse field `values` into DataBlock using `values_source`

4. If any error happens in parsing 3, then we fall back to parse the SQL into `InsertStatement` (current behavior).

5. I think it can work with above steps.

**Comment by ygf11** [comment]
Great idea. 

I think we can avoid `lifetime` here, because all operations are done in `sql Parser`, so `StatementWithSql(or other name)` can like:
```
StatementWithSql {
        db : String,
	table : String,
        ...
        Vec<DataBlock>,
}
```

**Comment by BohuTANG** [comment]
Now the insert sql will apply short_sql function.
