### ISSUE TITLE
Feature: reload tls configurations during reload call

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4546]
**Summary**
To enhance multi-tenant security, it requires to reload per tenant based tls configurations during CALL reload command
(https://github.com/datafuselabs/databend/blob/fda08c2f3a8da2a697e1df6e11b92010fa240d16/query/src/sessions/session_mgr.rs#L398)

**Comment by uran0sH** [comment]
I have some questions. 
```
        let config = {
            let mut config = self.conf.write();
            let config_file = config.config_file.clone();
            *config = Config::load()?;
            config.config_file = config_file;
            config.clone()
        };
```
These codes seems to reload tls configurations. What's the meaning of 'reload per tenant based the tls configurations'?

**Comment by Xuanwo** [comment]
We have removed `reload_config`. Let's close.
