### ISSUE TITLE
Feature:  a way to run init command which write to meta,  from only one query-node 

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#4557]
**Summary**

e.g.

1. init SQLs in config
2. internal usage（not limited to SQL）:
     3.  suppose we want to create root or change the password of root based on config
  
without this feature， we need either

1.  run from all query-node： require the command to idempotent，or use try_set
     -  work for the create-root case, with try_set
     -  maybe also work for most init SQLs like `set` 
     -  just wonder is there a better way？
3.  another step to initialize， after query started， connected
     -   not work for the root-user case

**Comment by youngsofun** [comment]
@drmingdrmer @ariesdevil

**Comment by drmingdrmer** [comment]
If I get your needs correctly:

The simplest way to do this is to store some initializing SQL statements in metasrv through the KV API.
And then let every query node load this SQL and run them.

To publish new SQL after query nodes start, query nodes have to **watch** the interested key-values.
Then a query node will be notified when a new SQL statement is published by updating the watched key-value record.

Reference:
- #4393

**Comment by youngsofun** [comment]
> And then let every query node load this SQL and run them.

do you mean the SQL is loaded and consumed(deleted) by only one query node?

> store some initializing SQL statements in metasrv through the KV API.

can metasrv read them from config and store in itself when start?
or do we still need a tool to store after the meta started?

**Comment by drmingdrmer** [comment]
> do you mean the SQL is loaded and consumed(deleted) by only one query node?

I mean every query node. Not just one of them.

> can metasrv read them from config and store in itself when start?
> or do we still need a tool to store after the meta started?

If there is only one metasrv node, it can be done this way, although I will never suggest doing it in this way.
If it is a metasrv cluster, different configurations on different metasrv will mess up the consistency.

**Comment by youngsofun** [comment]
suppose we want to create the root user in meta on start.

I can only let all query nodes try to create it on start.   
the first succeeds, the others make sure it failed because `user already exists.

is it sound ok to you?

@drmingdrmer

**Comment by drmingdrmer** [comment]
> I can only let all query nodes try to create it on start.
the first succeeds, the others make sure it failed because user already exists.

It's totally OK. Such failure already happens every minute.
