### ISSUE TITLE
Proposed: support DBeaver connect Databend

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4581]
Developers most use GUI apps connect Database and OPS data. So we need to support one GUI app connect. 

dbeaver is mutli-platfrom database tool for developers(free).  

Statements that need support:
```
SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout;

SELECT WORD FROM INFORMATION_SCHEMA.KEYWORDS WHERE RESERVED=1 ORDER BY WORD

SHOW CHARSET;

SHOW COLLATION;

SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server;

SHOW VARIABLES LIKE 'lower_case_table_names';

SELECT * FROM information_schema.TABLES t WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS';

SELECT @@session.transaction_read_only;

```
I think we'd better support information_schema， support MySQL protocol better. 

Tasks:

- [ ] DROP SCHEMA `book_db`

**Comment by BohuTANG** [comment]
We have `federated_server_setup_set_or_jdbc_command`: 

https://github.com/datafuselabs/databend/blob/d95adc1059facbe46f4a0f24b7c95b5da9572d87/query/src/servers/mysql/mysql_interactive_worker.rs#L254-L268

@wubx , please provide the server log error here, it's easy to check which sql not supportted.

**Comment by TCeason** [comment]
> Developers most use GUI apps connect Database and OPS data. So we need to support one GUI app connect.
> 
> dbeaver is mutli-platfrom database tool for developers(free).
> 
> Statements that need support:
> 
> ```
> SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout;
> 
> SELECT WORD FROM INFORMATION_SCHEMA.KEYWORDS WHERE RESERVED=1 ORDER BY WORD
> 
> SHOW CHARSET;
> 
> SHOW COLLATION;
> 
> SELECT @@GLOBAL.character_set_server,@@GLOBAL.collation_server;
> 
> SHOW VARIABLES LIKE 'lower_case_table_names';
> 
> SELECT * FROM information_schema.TABLES t WHERE t.TABLE_SCHEMA = 'information_schema' AND t.TABLE_NAME = 'CHECK_CONSTRAINTS';
> 
> SELECT @@session.transaction_read_only;
> ```
> 
> I think we'd better support information_schema， support MySQL protocol better.

Some ide software need sql result to do some config. Maybe at first we can judge why we not support these sql?

**Comment by TCeason** [comment]
> We have `federated_server_setup_set_or_jdbc_command`:
> 
> https://github.com/datafuselabs/databend/blob/d95adc1059facbe46f4a0f24b7c95b5da9572d87/query/src/servers/mysql/mysql_interactive_worker.rs#L254-L268
> 
> @wubx , please provide the server log error here, it's easy to check which sql not supportted.

This func return empty result but the ide needs set some bar value according to these sql result.

So could we support some mock functions to suitable these queries or we can support these var in datafuse?

**Comment by wubx** [comment]
@TCeason  Your approach may also work. Let's try your way.

**Comment by TCeason** [comment]
> 

I try to do some test , and maybe your driver is `com.mysql.jdbc.Driver` that is mysql jdbc 5.1.

And if you use `com.mysql.cj.jdbc.Driver` it will not occur this err.

![image](https://user-images.githubusercontent.com/33082201/160322061-fefb0f40-2ce6-47ba-ac75-9ec33c91fdea.png)

**Comment by TCeason** [comment]
dbeaver will inner execute

 /* ApplicationName=DBeaver 22.0.1 - SQLEditor <Script.sql> */ SET SQL_SELECT_LIMIT=200


when execute `show tables`

**Comment by TCeason** [comment]
LINK ISSUE: #4697, #4698

**Comment by wubx** [comment]
link issue:  https://github.com/datafuselabs/databend/issues/4708  


commit;
rollback;
SHOW VARIABLES LIKE 'sql_mode'

Test:
```
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
engine = create_engine('mysql+pymysql://root:@192.168.2.10:3307/default', encoding="utf-8")
con = engine.connect()
rs = con.execute('select * from ontime limit 1')
```

**Comment by TCeason** [comment]
> SHOW VARIABLES LIKE 'sql_mode'

Need value of sql_mode to do what?

**Comment by TCeason** [comment]
![image](https://user-images.githubusercontent.com/33082201/162677962-b4820dc0-26a1-4ac8-9af0-70faa4c69d0d.png)

Hi, @BohuTANG  @wubx Now we can use DBeaver select data.

**Comment by BohuTANG** [comment]
From my test, databend main branch is working with DBeaver on my ubuntu now 🚀 
@wubx Would like your test on your macos

**Comment by wubx** [comment]
Using user root connect is ok. 
If  you create user like:
```
create user 'wubx'@'%' identified by 'wubxwubx';
grant all privileges on *.* to 'wubx'@'%';
```

use DBeaver connection Databend will have worry:
 
>Authenticate failed, user: "wubx", auth_plugin: "mysql_native_password"

**Comment by TCeason** [comment]
> Link To ISSUE: can not create a database on dbeaver. more info inside: #4813

Also link to #4828

**Comment by BohuTANG** [comment]
Drop database has some issues:
```
Normal query: /* ApplicationName=DBeaver 22.0.2 - Main */ DROP SCHEMA `book_db`:
OnQuery Error: Code: 1005, displayText = sql parser error: Expected drop statement, found: SCHEMA.
```

**Comment by TCeason** [comment]
> Drop database has some issues:
> 
> ```
> Normal query: /* ApplicationName=DBeaver 22.0.2 - Main */ DROP SCHEMA `book_db`:
> OnQuery Error: Code: 1005, displayText = sql parser error: Expected drop statement, found: SCHEMA.
> ```

yes, this is a known problem.

**Comment by BohuTANG** [comment]
Databend has support DBeaver GUI :rocket:
