### ISSUE TITLE
copy into don't support special filename

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.6.102-nightly-9e4c5ae-simd

### What's Wrong?

mysql> copy into ontime   from 's3://repo.databend.rs/m_ontime_1/'  file_format = (type = 'CSV' field_delimiter = ','  record_delimiter = '\n' skip_header = 1);
ERROR 1105 (HY000): Code: 3006, displayText = Object { kind: ObjectPermissionDenied, op: "stat", path: "m_ontime_1/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_1987_10.csv", source: response part: Parts { status: 403, version: HTTP/1.1, headers: {"x-amz-request-id": "DK37DP3TQAB0KFP3", "x-amz-id-2": "4s4h6EGUV/GdVrby/4stczRnjCHW06McLV8rrQCNzzwn2LEAgQ3zYkPdz5Fuee5Pme6Ytv0l+NA=", "content-type": "application/xml", "date": "Sat, 26 Mar 2022 09:30:42 GMT", "server": "AmazonS3"} }, body: "" }.

### What You Expected?

support special filename

### How to Reproduce?

Databend use s3 
mysql> copy into ontime   from 's3://repo.databend.rs/m_ontime_1/'  file_format = (type = 'CSV' field_delimiter = ','  record_delimiter = '\n' skip_header = 1);

**Comment by BohuTANG** [comment]
Databend supports special files with `FILES = ( 'file_name' [ , 'file_name' ... ] )`, please see document of COPY:
https://databend.rs/doc/reference/sql/dml/dml-copy#files---file_name---file_name---

**Comment by wubx** [comment]
> Databend supports special files with `FILES = ( 'file_name' [ , 'file_name' ... ] )`, please see document of COPY: https://databend.rs/doc/reference/sql/dml/dml-copy#files---file_name---file_name---

You see the error report:  **kind: ObjectPermissionDenied**, but the repo.databend.rs is a public bucket. 

error log：
```
2022-03-27T00:30:43.986759Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 3006, displayText = Object { kind: ObjectPermissionDenied, op: "stat", path: "m_ontime_1/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_1987_11.csv", source: response part: Parts { status: 403, version: HTTP/1.1, headers: {"x-amz-request-id": "EYXMMRB8KBJ76RA8", "x-amz-id-2": "CjzmBVjSeCb92JPpv0W5c/w1qWxfgHS+rEU2pOyrRK3AjtOe7aWizce6i7kWU/UVaMxWn3GTNp8=", "content-type": "application/xml", "date": "Sun, 27 Mar 2022 00:30:43 GMT", "server": "AmazonS3"} }, body: "" }.
```

**Comment by wubx** [comment]
[query.log](https://github.com/datafuselabs/databend/files/8356636/query.log)
subbmit debug log

**Comment by BohuTANG** [comment]
I don't see your special file in your command, you are accessing a directory, it's not support now:
```
copy into ontime from 's3://repo.databend.rs/m_ontime_1/' file_format = (type = 'CSV' field_delimiter = ',' record_delimiter = '\n' skip_header = 1);
```

You must use :
1. Using the files to special the files name [Files](https://databend.rs/doc/reference/sql/dml/dml-copy#files---file_name---file_name---) :
  ` copy into ontime from 's3://repo.databend.rs/m_ontime_1/' files=('y_ontime.csv') file_format = (type = 'CSV' field_delimiter = ',' record_delimiter = '\n' skip_header = 1);`
2. pattern to special some files, [Pattern](https://databend.rs/doc/reference/sql/dml/dml-copy#pattern--regex_pattern)
  ` copy into ontime from 's3://repo.databend.rs/m_ontime_1/' pattern='y_ontime.*csv' file_format = (type = 'CSV' field_delimiter = ',' record_delimiter = '\n' skip_header = 1);`

**Comment by Xuanwo** [comment]
Maybe related to `reqsign`, let me check it out.

**Comment by Xuanwo** [comment]
Should be fixed by https://github.com/Xuanwo/reqsign/pull/47
