### ISSUE TITLE
bug: Load Data from Local File System

### ISSUE THREAD

**Issue by JasonLi-cn** [datafuselabs/databend#4598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

version: master
Latest commit [6553588]

### What's Wrong?

**On MacOS：**
echo curl -H \"insert_sql:insert into books format CSV\" -H \"skip_header:0\" -H \"field_delimiter:,\" -H \"record_delimiter:\n\" -F  \"upload=@./books.csv\" -XPUT http://127.0.0.1:8081/v1/streaming_load|bash

throws this error:
`Code: 1046, displayText = Parse csv error at line 3, cause: CSV error: record 3 (line: 1, byte: 21): found record with 3 fields, but the previous record has 1 fields.%`

### What You Expected?

https://github.com/datafuselabs/databend/blob/de611468c778d78a837bfb56f0dd3a46bacfa2e9/docs/doc/02-load-data/00_local.md?plain=1#L76

` -H \"field_delimiter:,\"` should be ` -H \"field_delimiter:','\"`
`-H \"record_delimiter:\n\"` should be `-H \"record_delimiter:'\n'\"`

### How to Reproduce?

no

### Anything Else?

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Oh, thank you!
Looks like it only the document issue, that would be great if you give a PR:
https://databend.rs/doc/contributing/good-pr
