### ISSUE TITLE
two-level hashmap optimization

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4602]
Yes, as the number of stored keys increases we did not have the two-level hashmap optimization like ClickHouse.
It can be enhanced in the future.

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/discussions/4600#discussioncomment-2446491_

**Comment by GrapeBaBa** [comment]
Except ClickHouse any other database implement this optimization?

**Comment by sundy-li** [comment]
> Except ClickHouse any other database implement this optimization?

I don't know. This looks very common in hashmap implementation.
