### ISSUE TITLE
SQL Statement Support for preparetion

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4620]
**Summary**

Some drivers and connectors support the ability to send a SQL statement for preparation before execution.  
Such as :
 -  SELECT
 -  DML
 -  show <objects>

Relation issue：
[#4618](https://github.com/datafuselabs/databend/issues/4618)

**Comment by wubx** [comment]
MySQL prepare statement:
```
PREPARE stmt_name FROM preparable_stmt
```

execute Statement:
```
EXECUTE stmt_name
    [USING @var_name [, @var_name] ...]
```

**Comment by sundy-li** [comment]
No plan to support prepare stmt in SERVER.  It should be done on the client side.
