### ISSUE TITLE
Support for information_schema database 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4659]
**Summary**

Some MySQL driver/GUI(like dbeaver) always access `information_schema` to fetch some meta information, `information_schema` tables are actually views, after the view(https://github.com/datafuselabs/databend/pull/4628) checked in, it's time to support the `information_schema` database, let the GUI easy to connect to Databend.

Tasks:
- [ ] Add `information_schema` database
- [ ] Impl some immutable views for `information_schema` which dbeaver need

**Comment by BohuTANG** [comment]
@TCeason may have some views information what's dbeaver used.

**Comment by TCeason** [comment]
Yes, the dbeaver now needs these views in `information_schema`:

information_schema.COLUMNS
information_schema.TABLES
INFORMATION_SCHEMA.KEYWORDS

And SQL 

- [x] show full tables (has already support on local)
- [ ] show table status
