### ISSUE TITLE
Bug: read stale data after `insert overwrite ` (fuse engine)

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#4674]
**Summary**

(on behalf of @everpcpc )

stateless test case `09_0010_remote_insert_overwrite` failed occasionally. 

~~~
INSERT INTO t1 (a,b,c,d) VALUES(1, 1, 1, 'origin'), (2, 2, 2, 'origin');
INSERT INTO t2 (a,b,c,d) VALUES(3, 3, 3, 'change'), (4, 4, 4, 'change');

select * from t1;
INSERT OVERWRITE t1 select * from t2;
select * from t1; // <- failure
~~~

CI logs:   https://github.com/datafuselabs/databend/runs/5798269334?check_suite_focus=true

~~~
09_0010_remote_insert_overwrite:                                        [ FAIL ] - result differs with:
--- /workspace/tests/suites/0_stateless/09_fuse_engine/09_0010_remote_insert_overwrite.result	2022-04-02 07:21:04.501275353 +0000
+++ /workspace/tests/suites/0_stateless/09_fuse_engine/09_0010_remote_insert_overwrite.stdout	2022-04-02 07:25:20.105301442 +0000
@@ -1,6 +1,6 @@
 1	1	1	origin
 2	2	2	origin
-3	3	3	change
-4	4	4	change
+1	1	1	origin
+2	2	2	origin
 5	5	5	change2
 6	6	6	change2
~~~

some context:

- more likely occur in Linux + release build
- ./scripts/ci/ci-run-tests-embedded-meta.sh

**Comment by BohuTANG** [comment]
Happen again: https://github.com/datafuselabs/databend/runs/5805968003?check_suite_focus=true#step:3:321

**Comment by BohuTANG** [comment]
Again:
https://github.com/datafuselabs/databend/runs/5832383396?check_suite_focus=true#step:3:316

**Comment by dantengsky** [comment]
got them

**Comment by dantengsky** [comment]
Progress update:

**Summary**

Can not reproduce it in the dev box yet. keep investigating.

------------

In a local dev box `09_0010_remote_insert_overwrite.sql` is extracted into a standalone test suite and keeps being tested (in an infinite loop,  break if the case failed).

- OS: Linux
- revision:  not fixed, typically the latest main branch in the morning.
- build: release

--------------

trying to test a fixed commit (#8632465) to  reproduce the error

**Comment by BohuTANG** [comment]
Reproduced:
```
--- /workspace/tests/suites/0_stateless/09_fuse_engine/09_0002_remote_truncate_table.result	2022-04-08 16:24:32.588952676 +0000
+++ /workspace/tests/suites/0_stateless/09_fuse_engine/09_0002_remote_truncate_table.stdout	2022-04-08 16:27:49.557235184 +0000
@@ -1,2 +1,4 @@
 1	v1
 2	v2
+1	v1
+2	v2
```

https://github.com/datafuselabs/databend/runs/5888432952?check_suite_focus=true#step:3:326

**Comment by dantengsky** [comment]
roger.  adds `09_0002_remote_truncate_table` to the local standalone test suite

**Comment by dantengsky** [comment]
this flaky test no longer occurs, closing
