### ISSUE TITLE
Improvement: Remove dependency `parquet-format-async-temp`

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#4675]
**Summary**

currently `parquet-format-async-temp` (0.2.0) is explicitly dependent.

which introduces troubles in the upgrading of crate `parquet2` (which depends on parquet-format-async-temp 0.3.0 now).

and also, It seems that we should use the interfaces exported by `arrow2` to manipulate parquet.

**Comment by Xuanwo** [comment]
Fixed in #4726, closing now.
