### ISSUE TITLE
bug: CSV import and  data consistency issue or encoding issue

### ISSUE THREAD

**Issue by alitrack** [datafuselabs/databend#4676]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.7.3

### What's Wrong?

import from csv may  be  garbled .

<img width="552" alt="image" src="https://user-images.githubusercontent.com/20972179/161379769-28a92213-9b73-4b05-813d-e5a3fe383259.png">

### What You Expected?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/20972179/161379757-713aa003-8237-4f51-ad8f-098da02979e7.png">

### How to Reproduce?

- create table
```sql
create table books
(
    title VARCHAR(255),
    author VARCHAR(255),
    date VARCHAR(255)
);
```
- import data 

```bash
echo curl -H \"insert_sql:insert into book_db.books format CSV\" -H \"skip_header:0\" -H \"field_delimiter:','\" -H \"record_delimiter:'\n'\" -F  \"upload=@./books_gbk.csv\" -XPUT http://127.0.0.1:8081/v1/streaming_load|bash

```

[books.zip](https://github.com/datafuselabs/databend/files/8402326/books.zip)

### Anything Else?

- need encoding check
- ontime has the same issue, because data of  year 2001 and month 10  have no ascii
- had better support compressed csv, for example gzip, bzip2
- unaccent support

<img width="791" alt="image" src="https://user-images.githubusercontent.com/20972179/161379844-bce090f1-57e5-4b8e-acd3-26bbe88f0d78.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
1. You can use ` iconv -f GBK -t UTF-8  a_gbk.csv -o b_utf8.csv` to convert into utf8 format, databend can't detect the character encoding.

2. Compression`gzip`, `bzip2` can be supported in the future.

**Comment by alitrack** [comment]
> 1. You can use ` iconv -f GBK -t UTF-8  a_gbk.csv -o b_utf8.csv` to convert into utf8 format, databend can't detect the character encoding.
> 2. Compression`gzip`, `bzip2` can be supported in the future.

if only support UTF-8, had better mention in the manual, and the tutorial also should do the conversion, the ontime csv is iso-8859-1, has non ascii. 

btw, books_gbk.csv is converted with  iconv for testing.
