### ISSUE TITLE
Feature: support compression method in streaming load & copy

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4679]
**Summary**

Description for this feature.

Support setting:  `compression = gzip`, `compression =  bzip2` etc.

**Comment by sundy-li** [comment]
#4676

**Comment by Xuanwo** [comment]
maybe related to https://github.com/datafuselabs/opendal/issues/70

**Comment by Xuanwo** [comment]
Related with https://github.com/datafuselabs/databend/issues/5380

**Comment by Xuanwo** [comment]
Implemented in https://github.com/datafuselabs/databend/pull/5655
