### ISSUE TITLE
Insert into Datetime64 column the result is not correct

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4680]
**Summary**

main branch:
```
mysql> create table t(d32 datetime32, d64 datetime64);

mysql> insert into t values('2022-04-02 15:10:28', '2022-04-02 15:10:28');
mysql> insert into t values('2022-04-02 15:10:28.221', '2022-04-02 15:10:28.221');

mysql> select * from t;
+---------------------+-------------------------+
| d32                 | d64                     |
+---------------------+-------------------------+
| 2022-04-02 15:10:28 | 1970-01-20 02:01:52.228 |
| 2022-04-02 15:10:28 | 1970-01-20 02:01:52.228 |
+---------------------+-------------------------+
```

**Comment by alitrack** [comment]
maybe related to [arrow-rs/issues/1459](https://github.com/apache/arrow-rs/issues/1459)

**Comment by sundy-li** [comment]
> maybe related to [arrow-rs/issues/1459](https://github.com/apache/arrow-rs/issues/1459)

It's not.  It's related to [custom precision](
https://github.com/datafuselabs/databend/blob/d4cc9f3a1edf7485d7609565036cf73841172a23/common/datavalues/src/types/deserializations/date_time.rs). I'm refactoring the deserilization now.
