### ISSUE TITLE
Feature: Support limit n, m

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#4709]
**Summary**

Now if execute SQL: 

```SQL
SELECT * FROM `default`.t
LIMIT 0, 200
```

will return err:
 ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1005, displayText = sql parser error: Expected end of statement, found: ,.

**Comment by TCeason** [comment]
After watching the code, I find we support limit n offset m.
```
SELECT * FROM `default`.NewTable LIMIT 3 offset 200;
Query OK, 0 rows affected (0.03 sec)
Read 0 rows, 0 B in 0.006 sec., 0 rows/sec., 0 B/sec.
```

So, if we want to support `limit n, m` we need to do some conversion?

Maybe can use this func `parse_sql_with_dialect` but I'm not sure.

**Comment by BohuTANG** [comment]
cc @sundy-li may help here

**Comment by sundy-li** [comment]
It's easy.
https://github.com/datafuse-extras/sqlparser-rs/blob/f8b7300c5dca02012e41d8fac04b459489c49545/src/parser.rs

```
  let limit = if self.parse_keyword(Keyword::LIMIT) {
        self.parse_limit()?
    } else {
        None
    };

    let offset = if self.parse_keyword(Keyword::OFFSET) {
        Some(self.parse_offset()?)
    } else {
    // ADD :  else if self.consume_token(&Token::Comma) {    Some(self.parse_offset()?)  } 

    // Then: reverse limit offset,   let limit ,offset = offset, limit;
        None
    };
```

**Comment by TCeason** [comment]
> It's easy. https://github.com/datafuse-extras/sqlparser-rs/blob/f8b7300c5dca02012e41d8fac04b459489c49545/src/parser.rs
> 
> ```
>   let limit = if self.parse_keyword(Keyword::LIMIT) {
>         self.parse_limit()?
>     } else {
>         None
>     };
> 
>     let offset = if self.parse_keyword(Keyword::OFFSET) {
>         Some(self.parse_offset()?)
>     } else {
>     // ADD :  else if self.consume_token(&Token::Comma) {    Some(self.parse_offset()?)  } 
> 
>     // Then: reverse limit offset,   let limit ,offset = offset, limit;
>         None
>     };
> ```

Ok, I will have a look.
