### ISSUE TITLE
Feature: CREATE TABLE syntax compatible with MySQL

### ISSUE THREAD

**Issue by gpfeng** [datafuselabs/databend#4712]
**Summary**

Syntax in MySQL CREATE TABLE not supported or not compatible：
- index definition, not supported
- Engine=InnoDB, not supported
- JSON data type, supported but not compatible
- DEFAULT value, lost in definition  https://github.com/datafuselabs/databend/issues/4670
- DEFAULT NULL, lost in definition, which makes NULL value not permitted 
- DEFAULT charset, not supported
- maybe more...

hope that table can be correctly created in databend directly from MySQL table definition.

**Comment by gpfeng** [comment]
example table definition from MySQL 5.7

CREATE TABLE `_idb_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `app_module` varchar(64) DEFAULT NULL,
  `user` varchar(64) NOT NULL DEFAULT 'guest',
  `log_level` varchar(16) NOT NULL DEFAULT 'INFO',
  `log_message` varchar(20000) DEFAULT NULL,
  `extended` json, 
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_app_module` (`app_module`),
  KEY `idx_created` (`created`),
  KEY `idx_log_level` (`log_level`)
) ENGINE=InnoDB AUTO_INCREMENT=15058436 DEFAULT CHARSET=utf8;

**Comment by wubx** [comment]
> * DEFAULT charset, not supported
Databend only  support utf8

**Comment by wubx** [comment]
if you need null please use:
```
CREATE TABLE _idb_log (
id int(11) NOT NULL AUTO_INCREMENT,
app_module varchar(64) NULL DEFAULT NULL,
user varchar(64) NOT NULL DEFAULT 'guest',
log_level varchar(16) NOT NULL DEFAULT 'INFO',
log_message varchar(20000) DEFAULT NULL,
extended json,
created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
)
```
About null : https://github.com/datafuselabs/databend/issues/4435

**Comment by sundy-li** [comment]
Thanks for the issue.

> hope that table can be correctly created in databend directly from MySQL table definition.

databend is not MySQL alternative, so it will not support full features or behaviors like MySQL.

- index definition, not supported. A:  Yes, we will have our own index definition in the future.
- Engine=InnoDB, not supported.  A:  No plan to add this Engine.
- JSON data type, supported but not compatible. A: No Plan to be full compatible with MySQL.

- DEFAULT value  #4727
- DEFAULT NULL   #4727
- DEFAULT charset  A: TODO Enhancement

**Comment by xudong963** [comment]
> databend is not MySQL alternative, so it will not support full features or behaviors like MySQL.

So is databend compatible with postgres? Or is there not a clear compatible database?

**Comment by BohuTANG** [comment]
Indeed, it needs well documented.
Databend SQL syntax is very easy to use, for `create table` the reference:
https://databend.rs/doc/reference/sql/ddl/table/ddl-create-table

**Comment by sundy-li** [comment]
I think we will have our own SQL syntax and make the protocol close to MySQL or Postgres etc.

**Comment by BohuTANG** [comment]
Hi @gpfeng ,

Thanks for the feedback.
As we talked above, Databend has its own SQL syntax on `CREATE TABLE`, the goal is to make it easier to use, more details please refer: [CREATE TABLE](https://databend.rs/doc/reference/sql/ddl/table/ddl-create-table)

**Your case is definitely working in Databend**, but it needs some simplification:

### `_idb_log` table

__Create table__
```
CREATE TABLE _idb_log (
id int(11) NOT NULL,
app_module varchar(64) NULL DEFAULT NULL,
user varchar(64) DEFAULT 'guest',
log_level varchar(16) DEFAULT 'INFO',
log_message varchar(20000) NULL DEFAULT NULL,
extended Variant,
created timestamp NOT NULL DEFAULT NOW()
); 
```

__Desc table__
```
mysql> desc _idb_log;
+-------------+------------+------+---------+
| Field       | Type       | Null | Default |
+-------------+------------+------+---------+
| id          | Int32      | NO   | 0       |
| app_module  | String     | YES  | NULL    |
| user        | String     | NO   | guest   |
| log_level   | String     | NO   | INFO    |
| log_message | String     | YES  | NULL    |
| extended    | Variant    | NO   | null    |
| created     | DateTime32 | NO   | NOW()   |
+-------------+------------+------+---------+
```

* NULL or NOT NULL please see [Column Nullable](https://databend.rs/doc/reference/sql/ddl/table/ddl-create-table#column-nullable)
* Default value please see [Default Values](https://databend.rs/doc/reference/sql/ddl/table/ddl-create-table#default-values)
* NOW() function please see [NOW()](https://databend.rs/doc/reference/functions/datetime-functions/now)

__Show create table__
```
mysql> show create table _idb_log;
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                                                                                                                               |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| _idb_log | CREATE TABLE `_idb_log` (
  `id` Int32,
  `app_module` String NULL DEFAULT NULL,
  `user` String DEFAULT 'guest',
  `log_level` String DEFAULT 'INFO',
  `log_message` String NULL DEFAULT NULL,
  `extended` Variant,
  `created` DateTime32 DEFAULT NOW(),
) ENGINE=FUSE 
```

### Insert into `_idb_log` table

Insert a value with other columns by default value/expression:
```
insert into _idb_log(id, extended) values(1, '{"a":1,"b":2}');
```

### Query from `_idb_log` table

```
mysql> select * from _idb_log;
+------+------------+-------+-----------+-------------+---------------+---------------------+
| id   | app_module | user  | log_level | log_message | extended      | created             |
+------+------------+-------+-----------+-------------+---------------+---------------------+
|    1 | NULL       | guest | INFO      | NULL        | {"a":1,"b":2} | 2022-04-10 05:13:50 |
+------+------------+-------+-----------+-------------+---------------+---------------------+
```

__Select from `extended` JSON__
```
mysql> select get(parse_json(extended), 'b') from _idb_log;
+--------------------------------+
| get(parse_json(extended), 'b') |
+--------------------------------+
| 2                              |
+--------------------------------+

```

This will be more simpler after  https://github.com/datafuselabs/databend/pull/4780 checked in:
```
select extended:b from _idb_log;
```


Also cc @wubx
