### ISSUE TITLE
Add `validate_privilege` to COPY interpreter

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4717]
**Summary**

Add `validate_privilege` to COPY interpreter.
https://github.com/datafuselabs/databend/blob/3d2f4bb94ef8c6fa616bb6bba131c8dbd085472a/src/meta/types/src/user_privilege.rs#L34-L63

Add a new privileges type: `COPY`? cc @flaneur2020

**Comment by BohuTANG** [comment]
Updated the summary.
This issue aims to add some privileges for `COPY`.

**Comment by TCeason** [comment]
COPY has limit by WRITE and READ privileges. Close this issue.
