### ISSUE TITLE
bug(use database):  use  "``"  behavior 

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#4723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

4ef6f03abd38072e53444f6d3ca8480824e52660

### What's Wrong?

``` use `` ``` no error, db not changed, but report `Database changed`.

### What You Expected?

choices:

1.  show `not changed`
2.  change to default
3. (prefer) report error (like mysql)

mysql:

```sql
mysql> use ``;
ERROR 1046 (3D000): No database selected
```

### How to Reproduce?

```sql
mysql> use system;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> use ``;
Database changed
mysql> select database();
+------------+
| database() |
+------------+
| system     |
+------------+
1 row in set (0.03 sec)
Read 1 rows, 1 B in 0.002 sec., 447.19 rows/sec., 447.19 B/sec.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Junnplus** [comment]
Seems to be a bug introduced by https://github.com/datafuselabs/databend/pull/4586/files#diff-3530d226419d50b772120427cb17d727ab72a6b5ccd06f042c3bc34941ffc1c2R364-R366

**Comment by BohuTANG** [comment]
👍 
1 look good to me
