### ISSUE TITLE
Feature: Semi-structured data function object_construct/object_construct_keep_null

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#4724]
**Summary**

Add support Semi-structured Data Function `OBJECT_CONSTRUCT` and `OBJECT_CONSTRUCT_KEEP_NULL`.

https://docs.snowflake.com/en/sql-reference/functions/object_construct.html
https://docs.snowflake.com/en/sql-reference/functions/object_construct_keep_null.html

**Comment by kevinw66** [comment]
It may take few weeks

**Comment by Xuanwo** [comment]
Any updates on this issue?

**Comment by kevinw66** [comment]
> Any updates on this issue?

@Xuanwo Sorry, I don't have time working on this anymore
