### ISSUE TITLE
bug: cannot build in mac aarch64 with channel 'nightly-2022-04-03'

### ISSUE THREAD

**Issue by doki23** [datafuselabs/databend#4725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

[b0f90cc](https://github.com/datafuselabs/databend/commit/b0f90cc1af89a3b010ff07bc04dc406cef1a3bd5)

### What's Wrong?

Build failed in my mac m1.

### What You Expected?

Build successfully.

### How to Reproduce?

1 macbook m1
just clone the master branch, cd databend and run `make build-release`

### Anything Else?

I changed the channel to 'nightly' and the build could normally run.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by everpcpc** [comment]
Are there any detailed error of the failure build? I tried on my mac m1, and built successfully.

**Comment by doki23** [comment]
Many compile errors, not found type in std lib, some examples: 
```
error[E0412]: cannot find type `Option` in this scope
   --> /Users/doki/.cargo/registry/src/github.com-1ecc6299db9ec823/autocfg-1.0.1/src/lib.rs:421:23
    |
421 |     cargo_target_dir: Option<OsString>,
    |                       ^^^^^^ not found in this scope

error[E0412]: cannot find type `OsString` in this scope
   --> /Users/doki/.cargo/registry/src/github.com-1ecc6299db9ec823/autocfg-1.0.1/src/lib.rs:421:30
    |
418 | fn dir_contains_target(
    |                       - help: you might be missing a type parameter: `<OsString>`
...
421 |     cargo_target_dir: Option<OsString>,
    |                              ^^^^^^^^ not found in this scope
```

**Comment by everpcpc** [comment]
Maybe it's a toolchain missing problem, can you try `rustup show` in the project root?

**Comment by doki23** [comment]
My toolchain seems ok:
```
Default host: aarch64-apple-darwin
rustup home:  /Users/doki/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2022-04-03-aarch64-apple-darwin
nightly-aarch64-apple-darwin

active toolchain
----------------

nightly-2022-04-03-aarch64-apple-darwin (overridden by '/Users/doki/FreeProjects/databend/rust-toolchain.toml')
rustc 1.61.0-nightly (76d770ac2 2022-04-02)
```

**Comment by doki23** [comment]
I compare my stable toolchain with my nightly-2022-04-03 toolchain and found that the nightly toolchain missed the rust-std component. So I think it's the problem.
