### ISSUE TITLE
Bug: `select *` should not return results 

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#4728]
### What's Wrong?

`select *` returns results 
```
mysql> select *;
+-------+
| dummy |
+-------+
|     1 |
+-------+
1 row in set (0.03 sec)
```

### What You Expected?

`select *` reports error;
```
postgres=# select *;
2022-04-07 07:56:53.698 CST [17886] ERROR:  SELECT * with no tables specified is not valid at character 8
2022-04-07 07:56:53.698 CST [17886] STATEMENT:  select *;
ERROR:  SELECT * with no tables specified is not valid
LINE 1: select *;
```

**Comment by BohuTANG** [comment]
Like postgres's user-friendly error message :heart:

**Comment by sundy-li** [comment]
If select query has no SourcePlan, it will add a dummy source plan `system.one`.

So  `select *` is rewritten into `select * from system.one`.
It's better to throw exceptions, but it's really trivial.

**Comment by xudong963** [comment]
> It's better to throw exceptions, but it's really trivial.

Yeah, just a corner case.
