### ISSUE TITLE
Feature: Support column `position` for table system.columns

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#4745]
**Summary**

Could we support a column `position` for table system.columns?

It like `ORDINAL_POSITION` in MySQL's information_schema.columns or `position` in ClickHouse's system.columns.
 
> In [MySQL](https://dev.mysql.com/doc/refman/8.0/en/information-schema-columns-table.html) ORDINAL_POSITION
> 
> The position of the column within the table. ORDINAL_POSITION is necessary because you might want to say ORDER BY ORDINAL_POSITION. 
> 
> Unlike [SHOW COLUMNS](https://dev.mysql.com/doc/refman/8.0/en/show-columns.html), [SELECT](https://dev.mysql.com/doc/refman/8.0/en/select.html) from the [COLUMNS](https://dev.mysql.com/doc/refman/8.0/en/information-schema-columns-table.html) table does not have automatic ordering.

> In [ClickHouse](https://clickhouse.com/docs/en/operations/system-tables/columns/) position
> 
> position ([UInt64](https://clickhouse.com/docs/en/sql-reference/data-types/int-uint/)) — Ordinal position of a column in a table starting with 1.

**Comment by wubx** [comment]
Did you mean add snowflake select support  
```
[ ... ]
SELECT [ { ALL | DISTINCT } ]
    {
          [{<object_name>|<alias>}.]*
        | [{<object_name>|<alias>}.]<col_name>
        | [{<object_name>|<alias>}.]$<col_position>
        | <expr>
        [ [ AS ] <col_alias> ]
    }
    [ , ... ]
[ ... ]
```

$col_position
Specifies the position of the column (1-based) as defined in the [FROM](https://docs.snowflake.com/en/sql-reference/constructs/from.html) clause. If a column is referenced from a table, this number can’t exceed the maximum number of columns in the table.

https://docs.snowflake.com/en/sql-reference/sql/select.html

**Comment by TCeason** [comment]
> Did you mean add snowflake select support
> 
> ```
> [ ... ]
> SELECT [ { ALL | DISTINCT } ]
>     {
>           [{<object_name>|<alias>}.]*
>         | [{<object_name>|<alias>}.]<col_name>
>         | [{<object_name>|<alias>}.]$<col_position>
>         | <expr>
>         [ [ AS ] <col_alias> ]
>     }
>     [ , ... ]
> [ ... ]
> ```
> 
> $col_position Specifies the position of the column (1-based) as defined in the [FROM](https://docs.snowflake.com/en/sql-reference/constructs/from.html) clause. If a column is referenced from a table, this number can’t exceed the maximum number of columns in the table.
> 
> https://docs.snowflake.com/en/sql-reference/sql/select.html

Yes we should support position first, so that we can support position on select query. Like this:

select top 1000
  Col_1, Col_18, Col_50, Col_117, *
from
  TableWithTonsOfCols
order by
  1, 4 desc, 3

**Comment by TCeason** [comment]
Now we do not have this feature, so we can close it tmp.
