### ISSUE TITLE
Flaky test:  test_stateless_cluster_linux failed occasionally

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#4754]
**Summary**

Flaky test: job **test_stateless_cluster_linux**

1.
--- /workspace/tests/suites/0_stateless/03_dml/03_0011_select_from_system_processes.result	2022-04-08 01:48:46.398157207 +0000
+++ /workspace/tests/suites/0_stateless/03_dml/03_0011_select_from_system_processes.stdout	2022-04-08 02:02:30.453283229 +0000
@@ -1 +1,2 @@
 Query	default
+Query	default

2. 
02_0032_function_strings_strcmp:                                        [ FAIL ] - Timeout!

https://github.com/datafuselabs/databend/runs/5878583472?check_suite_focus=true

**Comment by Xuanwo** [comment]
Not reproduced so far.
