### ISSUE TITLE
bug: desc view not work

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

`desc INFORMATION_SCHEMA.COLUMN` returns empty results.

### What You Expected?

Works like mysql.

### How to Reproduce?

```
MySQL [(none)]> desc INFORMATION_SCHEMA.COLUMNS;
Empty set (0.023 sec)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Enrich issue description with detailed information.
