### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#477]
**Summary**

To support performance tests in ci. Thus we can find performance drawbacks while introducing new features.

**Comment by BohuTANG** [comment]
ClickHouse:
https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/performance-comparison

Example page:
https://clickhouse-test-reports.s3.yandex.net/0/0c1e897e80a3924d209f6c5053cf388e2897f8c2/performance_comparison/report.html

**Comment by sundy-li** [comment]
conbench:    https://github.com/ursacomputing/conbench

**Comment by BohuTANG** [comment]
conbench better fit our needs.

**Comment by BohuTANG** [comment]
Databend has `/runperf master` for the CI performance.
