### ISSUE TITLE
'|' in the show create table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4782]
**Summary**

```
mysql> create table t1(a Int8);
Query OK, 0 rows affected (0.06 sec)
Read 0 rows, 0 B in 0.019 sec., 0 rows/sec., 0 B/sec.

mysql> show create table t1;
+-------+-----------------------------------------------+
| Table | Create Table                                  |
+-------+-----------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` Int8,
) ENGINE=FUSE | -- This is a redundant symbol 
+-------+-----------------------------------------------+

```

**Comment by cadl** [comment]
@BohuTANG  After some research, this appears to be the behavior of MySQL. And It seems to be normal to have`|` at the tail in MySQL client.

I tested MySQL server 5.7 via MySQL client, here is the screenshot.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1629582/162656386-dcc97331-063c-44d9-b562-e624b360dd88.png">


ref: related code https://github.com/mysql/mysql-server/blob/8.0/client/mysqlshow.cc#L770

**Comment by BohuTANG** [comment]
Thank you @cadl for the great research! Closing.
