### ISSUE TITLE
For a historical reason, `Cmd` does not utilize `XXXReq`. But instead in our codebase it manually converts `XXXReq` to a corresponding `Cmd`.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#4834]
For a historical reason, `Cmd` does not utilize `XXXReq`. But instead in our codebase it manually converts `XXXReq` to a corresponding `Cmd`.

It would be convenient to let `Cmd` have a variant that includes an `XXXReq` in it. E.g.: 
```rust
enum Cmd {
    CreateShare(CreateShareReq),
}
```

This would save a lot of trouble. :D

_Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/pull/4816#discussion_r848332518_

**Comment by youngsofun** [comment]
is refactor like this enough? 

https://github.com/youngsofun/databend/commit/0e844ab05001a49c43752d7bc893053abf2a5b5f

**Comment by drmingdrmer** [comment]
> is refactor like this enough （apply on all cmds that has XXXReq ）?
> 
> [youngsofun@0e844ab](https://github.com/youngsofun/databend/commit/0e844ab05001a49c43752d7bc893053abf2a5b5f)

It looks good:D.
Feel free to fire a **draft** PR instead of a single commit. A PR would be much easier to review and discuss.
