### ISSUE TITLE
Empty query: /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4860]
**Summary**

This is ok:
```
mysql> /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */ select 1;
+------+
| 1    |
+------+
|    1 |
+------+
1 row in set (0.06 sec)
Read 1 rows, 1 B in 0.007 sec., 140.82 rows/sec., 140.82 B/sec.
```

Error:
```
mysql> /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
ERROR 1105 (HY000): Code: 1005, displayText = Empty query.
```

Server error log:
```
2022-04-14T10:20:06.409763Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */
2022-04-14T10:20:06.414387Z ERROR databend_query::servers::mysql::writers::query_result_writer: OnQuery Error: Code: 1005, displayText = Empty query.

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::SyntaxException
             at common/exception/src/exception_code.rs:36:66
   1: databend_query::sql::plan_parser::PlanParser::build_plan::{{closure}}
             at query/src/sql/plan_parser.rs:57:24
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   3: databend_query::sql::plan_parser::PlanParser::parse_with_hint::{{closure}}
             at query/src/sql/plan_parser.rs:48:80
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   5: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:276:88
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   7: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase<W>::do_query::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:262:5
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
   9: <databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorker<W> as opensrv_mysql::AsyncMysqlShim<W>>::on_query::{{closure}}
             at query/src/servers/mysql/mysql_interactive_worker.rs:177:47
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/future.rs:124:9
  12: opensrv_mysql::AsyncMysqlIntermediary<B,S>::run::{{closure}}
             at /home/bohu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:513:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
  14: opensrv_mysql::AsyncMysqlIntermediary<B,S>::run_with_options::{{closure}}
             at /home/bohu/.cargo/git/checkouts/opensrv-2d23bfb068524349/967477f/mysql/src/lib.rs:250:17
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll

```

**Comment by BohuTANG** [comment]
Looks we should add a `EmptyInterpreter` for the Empty query which parsed to the EmptyPlan.

**Comment by cadl** [comment]
> Looks we should add a `EmptyInterpreter` for the Empty query which parsed to the EmptyPlan.


@BohuTANG I am a little confused about this.

For the  query `/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;`, MySQL will follow `!40101` command to execute the remaining comment part. 
Without `/*!40101*/`, MySQL will also return an `No query specified` error. 


Do we have a function like `MySQL /*!40101*/`? If not,  do we need to always return `Query OK, 0 rows affected` in the databend like this?
```
mysql> ;
0 row in set (0.01 sec)
```

**Comment by BohuTANG** [comment]
> > Looks we should add a `EmptyInterpreter` for the Empty query which parsed to the EmptyPlan.
> 
> @BohuTANG I am a little confused about this.
> 
> For the query `/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;`, MySQL will follow `!40101` command to execute the remaining comment part. Without `/*!40101*/`, MySQL will also return an `No query specified` error.
> 
> Do we have a function like `MySQL /*!40101*/`? If not, do we need to always return `Query OK, 0 rows affected` in the databend like this?

This is not a function, it is from some MySQL tools such as mysqldump.
For the query: `MySQL /*!40101*/`
1. mysql client send to databend-query
2. databend-query parse and build plan with https://github.com/datafuselabs/databend/blob/6e8d115db94010f00f9d705eb2fb7e9a0e4df93c/query/src/sql/plan_parser.rs#L57
3. (TODO) add a EmptyInterpreter for EmptyPlan
... ... 
4. Returns OK in EmptyInterpreter

> ```
> mysql> ;
> 0 row in set (0.01 sec)
> ```

This 'query' is not send to the server, it handled by the mysql client, it's different from `MySQL /*!40101*/` case.

**Comment by BohuTANG** [comment]
Hi @cadl 

This issue has some architecture background that may be a bit challenge for `good first issue`, so I made a workable patch for it for your reference: https://github.com/BohuTANG/datafuse/commit/a43013c7bcdea4fc6dd8d1b84e88f763ece475f3

**Comment by cadl** [comment]
> Hi @cadl
> 
> This issue has some architecture background that may be a bit challenge for `good first issue`, so I made a workable patch for it for your reference: [BohuTANG@a43013c](https://github.com/BohuTANG/datafuse/commit/a43013c7bcdea4fc6dd8d1b84e88f763ece475f3)

Thanks so much!! ❤️

**Comment by BohuTANG** [comment]
@cadl 

Hi, any plan on this issue? If you don't mind, I'll continue this work today and try to put it in tomorrow's release :D

**Comment by cadl** [comment]
> @cadl 
> 
> 
> 
> Hi, any plan on this issue? If you don't mind, I'll continue this work today and try to put it in tomorrow's release :D

sorry，A little busy past two days🙈. I will push A PR today
