### ISSUE TITLE
Two frequently failed case

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#4864]
and the following 2 always fail

```
    meta_node::meta_node_all::test_meta_node_snapshot_replication
    meta_node::meta_node_kv_api::test_meta_node_kv_api
```

_Originally posted by @youngsofun in https://github.com/datafuselabs/databend/issues/4859#issuecomment-1099778093_

**Comment by Xuanwo** [comment]
Has been addressed. Let's close.
