### ISSUE TITLE
Feature: allow passing a endpoint list to the metasrv client in a HA manner

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#4865]
**Summary**

it may resembles with the etcd-client:

https://github.com/etcd-io/etcd/tree/main/client/v3#get-started

an endpoint list can ensure the high availability of metasrv without any intermediate load balancer or virtual ip. when an endpoint dies, the client may simply retry another living endpoint.

**Comment by BohuTANG** [comment]
metasrv should add a new api for the grpc client in databend-query to fetch all the nodes of the metasrv, then roll next if the current metasrv endpoint is not work.
The user never care about the vip which front of metasrv cluster anymore.

cc @drmingdrmer @ariesdevil

**Comment by drmingdrmer** [comment]
Agree.
And let me elaborate it:

The endpoint list is not for HA, it is for easy maintenance.
A node will be added to a cluster or removed from it. The list will finally become outdated.

The HA is achieved with a `ForwardToLeader` response from an etcd/metasrv node, to inform the client to connect to the current effective leader.

The endpoint list is only used when starting up: to reduce the chances that a client connects to a removed node.




> metasrv should add a new api for the grpc client in databend-query to fetch all the nodes of the metasrv, then roll next if the current metasrv endpoint is not work. The user never care about the vip which front of metasrv cluster anymore.

Good idea.

**Comment by flaneur2020** [comment]
> A node will be added to a cluster or removed from it. The list will finally become outdated.

outdated is not really a problem with a static endpoint list in practise, the client endpoint list might looks like `etcd01:36001,etcd02:36002,etcd03:36003`, each endpoint is a DNS instead of hostname or ip. each DNS name like `etcd01` can be changed to another host on removing/adding a node in the cluster.

in the system administrator side, she can schedule a cluster maintaince with a DNS change on replacing a node or the entire cluster, without updating any client's config.

**Comment by BohuTANG** [comment]
@flaneur2020 ,
It looks not a normal user case, it's administrator case:
1. You should always know the all the metasrv nodes and configured them to databend-quey.toml
2. DNS is also another part the user need to care or maintaining, why we need it? :D

Let's keep it more simple.

**Comment by flaneur2020** [comment]
in the VM or phsical machine case, people rarely removes/add a host, she can put down the zk01, upgrade, then add it back, so the DNS is not really needed in a simple deployment.

in the kubenetes environment, we can keep the host name consistent with the StatefulSet, each pod with a standalone IP may leaves or joined into the cluster, but the Pod name with a DNS name would always keep consistent.
