### ISSUE TITLE
Feature: using enum_dispatch to represent data_type

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4868]
**Summary**

Description for this feature.

https://docs.rs/enum_dispatch/latest/enum_dispatch/index.html

Pros to use `enum_dispatch`:

1. Better performance (static dispatch, [compiler_optimized](https://docs.rs/enum_dispatch/latest/enum_dispatch/index.html#compiler_optimized)).
2. Avoid using `typetag::serde` to serde.
3. Automatic `From` and `TryInto` implementations (No downcast  unwrap anymore)
4. attribute support for enum

Tasks:
- [ ] DataTypePtr -> DataTypeImpl (Maybe a better name)
- [ ] ColumnRef -> ColumnImpl
- [ ] `Box<TypeSerializer>` -> TypeSerializerImpl
- [ ] `Box<TypeDeserializer>`  -> TypeDeserializerImpl

These tasks could lead many codes to be refactored.  You can pick it if you enjoy refactoring codes :)

Performance in databend:

```
data_type_ptr_create              time:   [52.972 ns 53.001 ns 53.033 ns]                                 
data_type_enum_create              time:   [53.507 ns 53.535 ns 53.563 ns]                                 

data_type_ptr_dummy               time:   [3.3817 ns 3.3830 ns 3.3843 ns]                                 
data_type_enum_dummy              time:   [430.82 ps 430.94 ps 431.09 ps]                                 

data_type_ptr_dummy2              time:   [1.0795 ns 1.0803 ns 1.0811 ns]                                  
data_type_enum_dummy2             time:   [430.57 ps 430.61 ps 430.66 ps]                                  

data_type_ptr_dummy2_compiled     time:   [1.2825 ns 1.2827 ns 1.2829 ns]
data_type_enum_dummy2_compiled    time:   [214.03 ps 214.06 ps 214.10 ps]
```

**Comment by Xuanwo** [comment]
It's really cool!

**Comment by PsiACE** [comment]
/assignme

I believe it will help me understand more about datavalues

**Comment by PsiACE** [comment]
After a short discussion with sundy, we will consider [RFC: Formal Type System](https://github.com/datafuselabs/databend/discussions/5438). Now let's close this issue.
