### ISSUE TITLE
http reset api not log the error

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4876]
**Summary**

1) Start the databend-query
2) Send a  request
```
curl --request POST '127.0.0.1:8000/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "create table t1(a smallint unsigned)"}'
```
Response:
```
{"id":"b9fd8222-cb5e-4b16-bf04-083db76ec814","session_id":null,"schema":null,"data":[],"state":"Failed","error":{"code":1005,"message":"sql parser error: Expected ',' or ')' after column definition, found: unsigned","backtrace":"   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::SyntaxException\n             at 
```

The server log:
```
2022-04-15T10:51:14.757363Z  INFO databend_query::servers::http::v1::http_query_handlers: receive http query: HttpQueryRequest { session: New(HttpSessionConf { database: None, max_idle_time: None }), sql: "create table t1(a smallint unsigned)", pagination: PaginationConf { wait_time_secs: 1 } }
```

We should log the error to databend-query log not return it to the client(maybe the client only need the error message not the stacktrace), then it will be analyzed by our monitor system.

**Comment by youngsofun** [comment]
@BohuTANG 

>  client only need the error message not the stacktrace

agree

----
> log the error to databend-query log 

it may overlap with `system.query_log`

currently,  for http handler,  mainly 3 type of errors:

##  bad http request (bad json, auth fail ...),   

http not return 200
there will be a WARN log， should I turn it to ERROR?

```
2022-04-16T02:59:30.619276Z  WARN databend_query::servers::http::middleware: http request error: status=400 Bad Request, msg=parse: key must be a string at line 1 column 2
```

## interperter error

we already have error info (including backtrace) in `system.query_log`

## others( most sql parse error)

currently neither in error log nor  `system.query_log`


# suggest

what about add another type of  `system.query_log` (other than 1.start, 2.end) that  record parser error.
no matter the handle it used.

**Comment by BohuTANG** [comment]
@youngsofun 
* system.query_log has error column but we no used it yet, we can set the error to this field.
* Each http request if the status is not 200 we should log it.

**Comment by youngsofun** [comment]
> ` Each HTTP request if the status is not 200 we should log it.`   

already done ( SQL parse/execute error will still return 200.)

- [ ]  `4.end -- error during the query execution.`
- [ ] `3.start -- error before the query execution`
