### ISSUE TITLE
Feature: add deps.rs badge to README to keep track about dependencies outdated

### ISSUE THREAD

**Issue by DCjanus** [datafuselabs/databend#4879]
There this a public service `deps.rs` to track Rust project dependencies.

If everything is ok, there would be a green badge, if there is dependencies is outdated, the badge would be yellow, and if any dependency found CVE, badge would be red and everyone who seeing this would found it and fix it.

Introduce the badge is easy:

[![dependency status](https://deps.rs/repo/github/datafuselabs/databend/status.svg)](https://deps.rs/repo/github/datafuselabs/databend)

PS: click the badge and open the page, it should tell you the detail.

**Comment by DCjanus** [comment]
I've noticed that location of badges in README is in HTML, which means that is been designed, I'm not sure where would be able to add this badge

**Comment by sundy-li** [comment]
Good idea, but [chrono ](https://deps.rs/crate/chrono/0.4.19) is insecure.

We did not find any better crate to replace it.

**Comment by PsiACE** [comment]
for outdated: https://databend.rs/doc/faq/routine-maintenance

for  audit: https://github.com/datafuselabs/databend/blob/176f3256f0c0a10fabd00f658aa6a8349aa7bc69/.github/actions/check/action.yml#L39
