### ISSUE TITLE
bug: metadata  error 

### ISSUE THREAD

**Issue by oslet** [datafuselabs/databend#4890]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main: 
commitid: d6fe2d1e17ae4ebc984eb44be48201115350c725
tag: v0.7.20-nightly

### What's Wrong?

````
2022-04-17T00:07:53.557980Z ERROR openraft::core: quit RaftCore::main on error err=StorageError(IO { source: StorageIOError { subject: Logs, verb: Read, source: common_meta_types::meta_storage_errors::MetaStorageError: serde json se/de error: Error("missing field `if_not_exists`", line: 1, column: 228), backtrace: "<disabled>" } })
````

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Hi, @oslet 

Thank you for the information.
When your metadata created first time?

Is there any way to get the metadata version and time in the disk? cc @drmingdrmer

**Comment by drmingdrmer** [comment]
It must be upgraded and the data format has been changed in:
- #4816

**Comment by drmingdrmer** [comment]
This upgrade added field `if_xxx_exist` to metadata.
Let me find a way to solve this issue 🤔

**Comment by oslet** [comment]
It is recommended to add scheduled backup functions, such as hourly backup configuration to the object storage directory

**Comment by drmingdrmer** [comment]
If you are using a single-node metasvr a backup may be necessary.

But a backup should be considered only for data durability. It may not help in case data format is changed.:(

**Comment by BohuTANG** [comment]
@oslet 

Agreed.
The metadata is small now(only table schema, user and fuse engine root snapshot), but it's very very important, I think the metasrv cluster for HA and Data Reliability, but this is not enough, the data maybe corruption by the metasrv bug.

I agree with you to backup metadata to object or other places with version, this is a solid last resort for the metasrv.

**Comment by BohuTANG** [comment]
@drmingdrmer 
metasrv also need to add some tests to check the version compatibly for the current version with the previous version of metadata changed.
cc @drmingdrmer

**Comment by BohuTANG** [comment]
Hi @oslet 

We have made databend-meta forward compatible from v0.7.22, please use https://github.com/datafuselabs/databend/releases/tag/v0.7.22-nightly
