### ISSUE TITLE
Simplify date/datetime datatypes

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4912]
### Discussed in https://github.com/datafuselabs/databend/discussions/4909

<div type='discussions-op-text'>

<sup>Originally posted by **sundy-li** April 18, 2022</sup>
Proposal:

1.  Union `Date`(`Date16`)    `Date32` to be `Date` type, which uses i32 as physical datatype.
2.   Union `DateTime` (`DateTime32`), `DateTime64` to be `DateTime` type, which uses i64 as physical datatype.</div>

**Comment by BohuTANG** [comment]
I will do some tasks afater this issue done:
1. Rename the datetime functions from xY to x_y
2. Datetime type conversion and bound-check in stateless test

**Comment by Veeupup** [comment]
For now, our parser do not support `DateTime(3)/Datetime(6)/DateTime(9)`, for common parse when pasring datatypw. 

So now using `DateTime_3/Datetime_6/DateTime_9` to display differnet precision. And for `DateTime_0` has a alias to `DateTime`.
