### ISSUE TITLE
New data type display for the user

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4914]
**Summary**

All General-Purpose Data Types after refine(including datetime #4912 ):

| Syntax               | Size(Bytes)      | Min Value              | Max Value   | Description |
----------------------| --------- | ---------------------- | ----------- | -------|
| BOOLEAN              | 1 |                   | | Logical boolean (true/false)
| TINYINT              | 1 |  -128                  |  127 |
| SMALLINT             | 2 |  -32768                |  32767 |
| INT                  | 4 |  -2147483648           |  2147483647 |
| BIGINT               | 8 |  -9223372036854775808  |  9223372036854775807 |
|  FLOAT    | 4 |  -3.40282347e+38          | 3.40282347e+38 |
|  DOUBLE   | 8 |  -1.7976931348623157E+308 | 1.7976931348623157E+308 |
|  DATE      | 4 |  1925-01-01            | 2283-11-11                    | YYYY-MM-DD             |
|  DATETIME  | 8 |  1970-01-01 00:00:00   |  2283-11-11 23:59:59.99999999          | YYYY-MM-DD hh:mm:ss.ff    |

If the type is unsinged, append suffix `UNSIGNED`.

For example:

```
mysql> create table test(a TINYINT, b VARCHAR, c INT);
```

Now:
```
mysql> desc test;
+-------+--------+------+---------+
| Field | Type   | Null | Default |
+-------+--------+------+---------+
| a     | Int8   | NO   | 0       |
| b     | String | NO   |         |
| c     | Int32  | NO   | 0       |
+-------+--------+------+---------+


mysql> show create table test\G;
*************************** 1. row ***************************
       Table: test
Create Table: CREATE TABLE `test` (
  `a` Int8,
  `b` String,
  `c` Int32,
) ENGINE=FUSE
```

New:
```
mysql> desc test;
+-------+--------+------+---------+
| Field | Type   | Null | Default |
+-------+--------+------+---------+
| a     | TINYINT   | NO   | 0      |
| b     | VARCHAR | NO   |    |
| c     | INT  | NO   | 0   |
+-------+--------+------+---------+


mysql> show create table test\G;
*************************** 1. row ***************************
       Table: test
Create Table: CREATE TABLE `test` (
  `a` TINYINT,
  `b` VARCHAR,
  `c` INT,
) ENGINE=FUSE
```

**Comment by sundy-li** [comment]
> If the type is unsinged, append suffix UNSIGNED.

How about making unsigned datatypes out of datatype as MySQL/Snowflake/Firebolt/Postgresql ?

`unsigned` is just a constraint and we should validate the values before insertion.

**Comment by BohuTANG** [comment]
Agreed, unsigned bus a constraint not a general data type.

**Comment by sundy-li** [comment]
It's a little complicated to remove unsigned datatypes.

1. `cast(x as unsigned)` is a little difficult to implement as we don't have unsigned types/columns.
2. The SQL parser already has unsigned datatype.
3. Some function may need this unsigned datatypes, like `abs`.

So let's keep them.

I created pr to better display the datatype more like MySQL.
