### ISSUE TITLE
Feature:  Databend is expected to support changing database names

### ISSUE THREAD

**Issue by Chasen-Zhang** [datafuselabs/databend#4917]
**Summary**
Databend now does not support changing database names

expected outcome:

RENAME DATABASE test_database_name TO test_database_name_new;
OR
ALERT DATABASE test_database_name RENAME TO test_database_name_new;

RENAME...TO...
ALERT...RENAME TO...

**Comment by wubx** [comment]
duplicate https://github.com/datafuselabs/databend/issues/4839
