### ISSUE TITLE
bug:  Drop table OOM

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4922]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

https://repo.databend.rs/databend/v0.7.21-nightly/databend-v0.7.21-nightly-x86_64-unknown-linux-gnu.tar.gz

### What's Wrong?

MySQL [wubx]> drop table sbtest1_bak;

ERROR 2013 (HY000): Lost connection to server during query

demsg:

> [641809.800366] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-2.scope,task=databend-query,pid=3364036,uid=1000
[641809.800469] Out of memory: Killed process 3364036 (databend-query) total-vm:35160204kB, anon-rss:19546332kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:47324kB oom_score_adj:0
[641810.211717] oom_reaper: reaped process 3364036 (databend-query), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

### How to Reproduce?

drop big table 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dantengsky** [comment]
closed by 
-  #4523

currently, `drop table` will not delete the data.  To reclaim the storage space, please
- first `truncate table T`
    which will mark the table as empty logically.
-  and then, `optimize table purge`
    which will delete data from storage (almost the same of the before `Drop table`)
