### ISSUE TITLE
create table show `comment`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4925]
**Summary**

```
mysql> create table t1(a INT comment 'acomment') comment='mytable';
Query OK, 0 rows affected (0.03 sec)
Read 0 rows, 0 B in 0.007 sec., 0 rows/sec., 0 B/sec.

mysql> show create table t1;
+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `a` Int32, -- no comments here
) ENGINE=FUSE COMMENT='mytable' |
+-------+------------------------------------------------------------------+

```

**Comment by sunisdown** [comment]
got the root cause.
seems that `plan_parser` doesn't handle the column comments 
https://github.com/datafuselabs/databend/blob/2ca3014d8a8dc41b5ef0ec16780ea4c69e164ece/query/src/sql/statements/statement_create_table.rs#L167-L178

will add it.  
by the way, this is a perfect issue for me, as it made me look in both the `parse` and `query plan` code, two areas I hadn't touched before.

**Comment by BohuTANG** [comment]
@sunisdown 
Sorry, I missed this comments, glad to see that you found it.

**Comment by wubx** [comment]
```
MySQL [(none)]> create table t1(a INT comment 'acomment');
ERROR 1105 (HY000): Code: 1022, displayText = COMMENT 'acomment' column option is not supported, please do not specify them in the CREATE TABLE statement.
MySQL [(none)]> select version();
+-----------------------------------------------------------------------------------------+
| @@version()                                                                             |
+-----------------------------------------------------------------------------------------+
| 8.0.26-v0.7.74-nightly-a556243-simd(rust-1.63.0-nightly-2022-06-06T16:24:09.098868778Z) |
+-----------------------------------------------------------------------------------------+
1 row in set (0.002 sec)
```

**Comment by BohuTANG** [comment]
@wubx 
This issue has not started yet.

**Comment by wubx** [comment]
I see you can create a table with comments, but my databend version can't do that.  
Do I need a new issue?

**Comment by sunisdown** [comment]
> e you can create a table with comments, but my databend version can't do that.
> Do I need a new issue?

It's the same issue, we can create table with table comments, but column comments are not support @wubx

**Comment by johnhaxx7** [comment]
Seems like this issue is resolved in the linked ticket, good to close?

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/pull/5952
