### ISSUE TITLE
Tracking issue: metasrv maintenance 

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#4931]
### Backward compatible upgrade:

- [x] #4901 
- [x] #4918 
- [x] #4949
- [x] #4948
- [x] #7189
- [x] #4950
- [x] #4952

### Maintenance

There are already APIs providing cluster config info such as leader and member.
Needs more load metrics

- [x] #4938
- [x] #4988

### Doc: 
- [x] #4920

**Comment by drmingdrmer** [comment]
@lichuang @ariesdevil any suggetions? 🤔

**Comment by ariesdevil** [comment]
Logical backup that @BohuTANG mentioned

**Comment by lichuang** [comment]
add Compatibility data unit test into daily CI, every time upgrade the format, MUST add corresponding unit test.

add more metrics of metasrv, like etcd.

**Comment by drmingdrmer** [comment]
> Logical backup that @BohuTANG mentioned

Backup has been implemented with `metactl`. Did you mean something else?
