### ISSUE TITLE
Feature: introducting tenant_id in JWT CustomClaims

### ISSUE THREAD

**Issue by Junnplus** [datafuselabs/databend#4936]
**Summary**

Consider introducing an `InjectContext` in JWT `CustomClaims`:
```rs
pub struct InjectContext {
    pub tenant_id: String,
}

pub struct CustomClaims {
    pub inject_context: Option<InjectContext>,
}
```

Now the query node in management mode cannot switch tenant, we can achieve it through `InjectContext`.

**Comment by Junnplus** [comment]
Any ideas? @flaneur2020 @BohuTANG @ZhiHanZ

**Comment by flaneur2020** [comment]
is it feasible to put a plain `tenant_id` field into the `CustomClaims` instead of nested inside an InjectContext? 

(sort of Law of Demeter?  >v<)

**Comment by Junnplus** [comment]
> is it feasible to put a plain tenant_id field into the CustomClaims directly instead of introduce an new struct InjectContext?

Like `EnsureUser` in JWT `CustomClaims`, it is necessary to introduce a separate structure.

**Comment by flaneur2020** [comment]
is it the restriction from jwt library? q.q

**Comment by Junnplus** [comment]
> is it the restriction from jwt library? q.q

We discussed this issue offline, it is determined that the `tenant_id` is directly placed in CustomClaims without introducing a new structure.
