### ISSUE TITLE
metrics API providing requests/sec, active watchers, outstanding(uncommitted) raft logs, number of raft logs, state machine size etc.

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#4938]
- [x] #5601
- [x] #5841
- [x] #5977
- [x] #6070
- [x] #6082

**Comment by everpcpc** [comment]
How about providing raft index and db size like etcd?
https://etcd.io/docs/v3.5/tutorials/how-to-check-cluster-status/

**Comment by drmingdrmer** [comment]
Is it time to close this issue?
