### ISSUE TITLE
Feature: Supports Table Clone in Databend

### ISSUE THREAD

**Issue by Chasen-Zhang** [datafuselabs/databend#4940]
**Summary**
Databend now doesn't support Table Clone 

**Expected:**
`CREATE TABLE test_table_clone CLONE test_table;`
After executing this statement, we can copy both the table structure and data of test_table to test_table_clone, although the kernel may reuse the same data.

**Comment by xudong963** [comment]
This feature in the issue clones two tables, is it will affect each other, such as the clone table to modify the data will affect the original table.

If not, I think we can use `create table clone_table () as select * from origin_table`;

**Comment by sundy-li** [comment]
If it's fuse engine, we just need to set the snap_loc to the source table without data copy.

**Comment by BohuTANG** [comment]
@xudong963 
Create table clone is a zero-copy clone:
1. create a table schema from the original table
2. fork a new snapshot of the original data's

Then the cloned table is a fork branch like git branch, and you can do everything on your new branch:such as insert new data or change the table schema, but the original table no affected.

**Comment by sundy-li** [comment]
we already have  `CREATE TABLE test_table_clone  as select * from  test_table;  `
