### ISSUE TITLE
bug: copy from stage only 10000 rows 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#4953]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

MySQL [wubx]> select version();
+--------------------------------------------------------------------------+
| @@version()                                                              |
+--------------------------------------------------------------------------+
| 8.0.26--87f4250-simd(rust-1.61.0-nightly-2022-04-19T16:18:44.241013412Z) |
+--------------------------------------------------------------------------+
1 row in set (0.001 sec)

### What's Wrong?

```
wc -l 0419.csv
997708 0419.csv

curl -v  -H "stage_name:my_init_stage" -F "upload=@./archive/0419.csv"  -XPUT http://localhost:8000/v1/upload_to_stage

MySQL [wubx]> COPY INTO sbtest1_v1 FROM '@my_init_stage' files=('0419.csv') file_format = (type = 'CSV' field_delimiter = '\t'  record_delimiter = '\n' skip_header = 0);
Query OK, 0 rows affected (0.030 sec)
Read 10000 rows, 2.02 MB in 0.026 sec., 384.38 thousand rows/sec., 77.65 MB/sec.

MySQL [wubx]> select count(*) from sbtest1_v1;
+---------+
| count() |
+---------+
|   10000 |
+---------+
1 row in set (0.005 sec)

```

Same file use stream load:
```
curl -v  -XPUT 'http://localhost:8000/v1/streaming_load' -H 'insert_sql: insert into wubx.sbtest1_v2 format CSV' -H 'skip_header: 0'  -H 'field_delimiter:\t' -F 'upload=@./archive/0419.csv'

{"id":"68ac1ac4-e579-4353-aef2-34a38e31b215","state":"SUCCESS","stats":{"rows":997708,"bytes":201538616},"error":null}

```

### How to Reproduce?

table schema like this: 
```
CREATE TABLE `sbtest1` (
  `id` INT,
  `k` INT DEFAULT '0',
  `c` VARCHAR DEFAULT '',
  `pad` VARCHAR DEFAULT '',
) ENGINE=FUS;
```

file : https://datafuse-1255499614.cos.ap-beijing.myqcloud.com/0419.csv.gz

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
There is a bug inside `StageSource`  cc @GrapeBaBa.

I'll create a pr to fix this.

**Comment by wubx** [comment]
copy into from external_stage_name with the same issue.

**Comment by GrapeBaBa** [comment]
> There is a bug inside `StageSource` cc @GrapeBaBa.
> 
> I'll create a pr to fix this.

haha, @sundy-li  maybe you can point it. I can add a new test case.
