### ISSUE TITLE
Feature: the same level of e2e test coverage in http api handler

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#4955]
**Summary**
During platform integration, we heavily rely on http handler, but test coverage is not enough comparing to mysql case.
Need the following parts:
1. DDL related, CREATE, DROP, ALTER on DATABASE, TABLE etc
2. DSL related on different database or table
3. Security related, especially for mTLS and JWT

- [ ] http api stateless test
- [ ] http api stateful test
- [ ] http api mTLS test
- [ ] http api JWT test

**Comment by BohuTANG** [comment]
Better way is to make the `databend-test` support http client and send the stateless sql and check result:
https://github.com/datafuselabs/databend/blob/077b349822578676854a64e6844d5e58ef008934/tests/databend-test#L637-L641

**Comment by BohuTANG** [comment]
Does this issue related to #4958?

**Comment by flaneur2020** [comment]
hmm, seems duplicated

**Comment by sundy-li** [comment]
> Better way is to make the databend-test support http client and send the stateless sql and check result

It might be incorrect. Http client can't send multi-query at once. But we need multi-query at once to respect the settings inside the SQL file.

**Comment by ZhiHanZ** [comment]
> > Better way is to make the databend-test support http client and send the stateless sql and check result
> 
> It might be incorrect. Http client can't send multi-query at once. But we need multi-query at once to respect the settings inside the SQL file.

I think we could split sql to single query array and aggregate result file?

**Comment by Xuanwo** [comment]
The new sql logic test framework has covered this. Let's close.
