### ISSUE TITLE
What will the datetime data type

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4994]
@sundy-li @Veeupup 

What's the databend final datetime data type is？
In some database systems(snow, [bigquery](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type), [duckdb](https://duckdb.org/docs/sql/data_types/timestamp), [cockroachdb](https://www.cockroachlabs.com/docs/stable/timestamp.html)), they are introduce only one type: timestamp(datetime may be a aliases name in some of them), and the range:
```
0001-01-01 00:00:00 to 9999-12-31 23:59:59.999999 UTC
```
Supports precision levels from 0 (seconds) to 6 (microseconds) .

I suggest the default is TIMESTAMP(6), what do you think?

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/pull/4982#issuecomment-1105896600_

**Comment by sundy-li** [comment]
I think `TIMESTAMP` is alias to `DATETIME`.

Cockroachdb has custom precision, `Timestamp(n)`:
eg:

```
CREATE TABLE timestamps (a INT PRIMARY KEY, b TIMESTAMP(3));
```

**Comment by BohuTANG** [comment]
OK.
Then the problem is what the default date time value is?

**Comment by sundy-li** [comment]
I checked `bigquery` and `Cockroachdb `, we can make the default precision to be `6`.  @Veeupup 

The range of precision is `[0, 9]` is ok.
