### ISSUE TITLE
Consider change the text result check to goldenfile

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5001]
**Summary**

There are many `assert_blocks_sorted_eq` in databend rust code, to make life easier, let's change to goldenfile.
goldenfile example:
https://github.com/datafuselabs/databend/blob/f25c34917b415ab42308a99637b5513aa4ea76df/common/ast/tests/it/rule.rs#L120-L137

**Comment by Xuanwo** [comment]
Already implemented.
