### ISSUE TITLE
Bump arrow2&parquet2 to the new version

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5008]
**Summary**

**Comment by ygf11** [comment]
Hi, @BohuTANG. Currently databend use the `databend` branch of `datafuse-extras/parquet2`.

Does this means we need to merge main into `databend` branch of parquet2?

**Comment by dantengsky** [comment]
hi @ygf11 ,

For backward compatiablity, `datafuse-extras/parquet2` allows reading of legacy compression `LZ4` (not LZ4Raw), not sure if it is easy to merge with upstream.

let me check it out ...

**Comment by dantengsky** [comment]
@ygf11 

`datafuse-extras/parquet2` has been rebased on to `parquet2` v0.12, at:

branch : https://github.com/datafuse-extras/parquet2/commits/parquet2-0.12
commit : 7a0254f2db01f689b288748017cd23391dabe21d ( use commit hash in Cargo.toml is preferred)

pls let me know If any troubles bumping the `parquet2` crate.

**Comment by ygf11** [comment]
> datafuse-extras/parquet2 has been rebased on to parquet2 v0.12

Thanks, let me try it.

**Comment by ygf11** [comment]
@dantengsky 

To make `PageReader`(`PageIterator`) easy to use in databend, I make a pr to upstream. 

Pls help to merge this patch to our working branch.

https://github.com/jorgecarleitao/parquet2/pull/136#issue-1222143426

**Comment by dantengsky** [comment]
> @dantengsky
> 
> To make `PageReader`(`PageIterator`) easy to use in databend, I make a pr to upstream.
> 
> Pls help to merge this patch to our working branch.
> 
> [jorgecarleitao/parquet2#136 (comment)](https://github.com/jorgecarleitao/parquet2/pull/136#issue-1222143426)

Rebased onto upstream(https://github.com/jorgecarleitao/parquet2):main, please take a look at:

https://github.com/datafuse-extras/parquet2/commits/parquet2-0.12-patch1

**Comment by dantengsky** [comment]
@ygf11 

This is a "hot upgrading" of arrow2 today,

- https://github.com/datafuse-extras/arrow2/commit/2d70fbf46fd37f4ef532945c588be69a71998e44

thus, I have to start the task of bumping dependencies of arrows2, and parquet2 is upgraded as well. Hope you have not done lots of coding yet, sorry for that.

And if possible, please help review the upcoming PR of this issue (especially the `PageMetaData` and `PageReader` pars). Thanks!

**Comment by ygf11** [comment]
> This is a "hot upgrading" of arrow2 today,
 
@dantengsky  Ok:)
