### ISSUE TITLE
Consider change the datavalues DataTypePtr trait to DataTypeImpl enum

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5015]
**Summary**

For better ser/deser, the enum looks better than trait, in DataField.data_type is a trait:
Change 
https://github.com/datafuselabs/databend/blob/253618087a10925fdf0afc448998a86d094c74b5/common/datavalues/src/data_field.rs#L30

to
https://github.com/datafuselabs/databend/blob/253618087a10925fdf0afc448998a86d094c74b5/common/datavalues/src/types/data_type.rs#L52-L73

We can use more serde attribute on the enum type(such as the rename).

**Comment by sundy-li** [comment]
Related to #4868
