### ISSUE TITLE
Make the DataField.default_expr to raw sql

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5016]
**Summary**

Now, the default_expr is serialized representation from PlanExpression, it's very hard to make it backward compatible.

**Comment by sundy-li** [comment]
I found a problem to make `default_expr` as raw sql.

When we need it to be PlanExpression, for example in:

https://github.com/datafuselabs/databend/blob/63e151db8cd38c4d0697c0d41128d43a9dc4bfd0/query/src/pipelines/new/processors/transforms/transform_addon.rs#L54-L65


1. We need to parse the raw SQL to be `sqlparser::Expr`  (AST struct)
2. `ExpressionAnalyzer::analyze` to transform `Expr` to be `Expression`


But the second step is async function, it's strange to call async function just in deserialization...

**Comment by BohuTANG** [comment]
I think we should do the raw expression sql to plan expression in the meta api like get_table, not the place who want use it.

**Comment by BohuTANG** [comment]
> I think we should do the raw expression sql to plan expression in the meta api like get_table, not the place who want use it.

This is need a new struct looks not a good way.
Prefer to change the create function from sync to async：
https://github.com/datafuselabs/databend/blob/63e151db8cd38c4d0697c0d41128d43a9dc4bfd0/query/src/pipelines/new/processors/transforms/transform_addon.rs#L43

**Comment by zhang2014** [comment]
> I think we should do the raw expression sql to plan expression in the meta api like get_table, not the place who want use it.

+ 1, Changing sync to async may not be a good idea. When a function is async, we need to be careful of its executor.

**Comment by BohuTANG** [comment]
> > I think we should do the raw expression sql to plan expression in the meta api like get_table, not the place who want use it.
> 
> +1, Changing sync to async may not be a good idea. When a function is async, we need to be careful its executor.

If using this way, we can do it in `query/catalog/get_table`:
https://github.com/datafuselabs/databend/blob/0e489b32970ddc373d1ea14a6076df1d85d080db/query/src/catalogs/impls/mutable_catalog.rs#L203-L215

**Comment by sundy-li** [comment]
>  one for serialization(with raw_sql) and one for business use(deserialize to expression).

This will lead too many overlaps with AST parser, better to reuse the parser crate to do it.

The second problem is  `TableInfo` in `meta/types` can't depend on crate `Planner`.

**Comment by BohuTANG** [comment]
@sundy-li 
Right :cry:

**Comment by BohuTANG** [comment]
But still have ugly solutions.

DataValues/DataField:
```
pub struct DataField {
    name: String,
    default_expr: Option<Vec<u8>>, -- raw-sql now
    #[ignore_malloc_size_of = "insignificant"]
    data_type: DataTypePtr,
}
```

And define another DataFieldWithExpr in query:
```
pub struct DataFieldWithExpr {
    name: String,
    default_expr: Expression,
    data_type: DataTypePtr,
}
```

Convert DataField to DataFieldWithExpr in query/catalog/get_table, we still need another DataSchema to lwrap the `DataFieldWithExpr`.


The problems here seems that `meta/types/TableMeta` has too much nesting:
TableMeta:
```
pub struct TableMeta {
    pub schema: Arc<DataSchema>,
    pub engine: String,
    pub engine_options: BTreeMap<String, String>,
    pub options: BTreeMap<String, String>,
    // TODO(sundy): Save this as AST format
    pub order_keys: Option<Vec<u8>>,
    pub created_on: DateTime<Utc>,
}
```
--> DataSchema:
```
pub struct DataSchema {
    pub(crate) fields: Vec<DataField>,
    pub(crate) metadata: BTreeMap<String, String>,
}
```

-->DataField:
```
pub struct DataField {
    name: String,
    /// default_expr is serialized representation from PlanExpression
    default_expr: Option<Vec<u8>>,
    #[ignore_malloc_size_of = "insignificant"]
    data_type: DataTypePtr,
}
```

**Comment by sundy-li** [comment]
Yes, a new dataschema in query level like: https://github.com/ClickHouse/ClickHouse/blob/f17d1bc7a5593ef31db864df6426c995b0787233/src/Storages/StorageInMemoryMetadata.h
