### ISSUE TITLE
Feature(function): add scalar function  humanize

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5035]
**Summary**

Description for this feature.

## Context:
```
databend > select sum(length(stack_trace)), sum( length(session_settings) ), sum(length(query_text )) from system.query_log;
+--------------------------+-------------------------------+-------------------------+
| sum(length(stack_trace)) | sum(length(session_settings)) | sum(length(query_text)) |
+--------------------------+-------------------------------+-------------------------+
|                        0 |                          6375 |                     734 |
+--------------------------+-------------------------------+-------------------------+
```

We can add `humanize` function to display the size for better reading.

- Function:  `humanize`
- ReturnType: String 
- Example:

```
databend > select humanize(1024);

+------------+
|  humanize(1024) |
+------------+
|       1.00 KiB |

```
- Refer Docs:  https://github.com/datafuselabs/databend/blob/790ddcde7fefee3795103bd503f8df57796e1bb1/docs/doc/100-faq/40-how-to-write-scalar-functions.md
- Utils: https://github.com/datafuselabs/databend/blob/3a1a529c1d8839db84c62004b7223b1f7390ad77/common/io/src/utils.rs

**Comment by cadl** [comment]
@sundy-li 

The helper [convert_byte_size(num: f64)](https://github.com/datafuselabs/databend/blob/3a1a529c1d8839db84c62004b7223b1f7390ad77/common/io/src/utils.rs#L22) return `KB/MB` not `KiB/MiB`. 
Is ok to return KB not KiB for `humanize`?

**Comment by cadl** [comment]
The term "humanize" may not only fit in byte size.  
How about creating two functions? The `humanize_size` convert 1000 to "1KB", and `humanize_number` convert 1000 to "1 thousand"?

**Comment by sundy-li** [comment]
> The helper [convert_byte_size(num: f64)](https://github.com/datafuselabs/databend/blob/3a1a529c1d8839db84c62004b7223b1f7390ad77/common/io/src/utils.rs#L22) return KB/MB not KiB/MiB.
Is ok to return KB not KiB for humanize?

It's ok.  `humanize_size ` + `humanize_number ` is good idea.
