### ISSUE TITLE
duplicate field: select number + 1 as number, number + 1 as b, b + 1 c from numbers(1)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#504]
**Describe the bug**

```
--------------
select number + 1 as number, number + 1 as b, b + 1 c from numbers(1)
--------------

+--------+------+------+
| number | b    | c    |
+--------+------+------+
|      0 |    2 |    3 |
+--------+------+------+
```

**Expected behavior**
```
+--------+------+------+
| number | b    | c    |
+--------+------+------+
|      1 |    2 |    3 |
+--------+------+------+
```

Reference:
https://github.com/datafuselabs/datafuse/blob/3865311575472887149498d7a2465f3da263a352/tests/suites/0_stateless/03_0000_select_aliases.result#L59-L72

**Comment by jyizheng** [comment]
Just tried the SQL on current mater branch. Got the error below:

ERROR 1105 (HY000): Code: 1002, displayText = Invalid argument error: Unable to get field named "b". Valid fields: ["number"].
