### ISSUE TITLE
Feature: Cast to `Timestamp/Datetime` with precision

### ISSUE THREAD

**Issue by Veeupup** [datafuselabs/databend#5043]
**Summary**

support cast to `timestamp/datetime` with precison like:
* `select toTimestamp('xxxx-xx-xx xx:xx:xx', 3)` or `select toTimestamp('xxxx-xx-xx xx:xx:xx', 6)`.

**Comment by johnhaxx7** [comment]
Hi @youngsofun, are you still working on this issue or can I take it?

**Comment by johnhaxx7** [comment]
Hi @BohuTANG, I'm new to expression framework and I'm looking at https://github.com/datafuselabs/databend/blob/main/src/query/expression/src/types/timestamp.rs and related code. Can you please share some pointers/basic ideas on what I should change for this except parser?

**Comment by BohuTANG** [comment]
Hi @johnhaxx7 ,

@sundy-li will help us with it :)
