### ISSUE TITLE
Feature: impl `Debug` for `SExpr` 

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5047]
**Summary**

Implement `Debug` for `SExpr` to facilitate debugging during implementation of new planner.

Can refer to the `Debug` implementation of `PlanNode` in the old planner.

**Comment by leiysky** [comment]
`SExpr` had implemented `Debug` before, but it was removed in the last refactor of binder.

I was going to introduce a structual representation for both `SExpr` and `MExpr`, which can be serialized into JSON or other formats.

What do you think of this?

**Comment by xudong963** [comment]
Nice, looking forward!
