### ISSUE TITLE
It would be better move the test to `suites/0_stateless/03_dml` like a new name: `03_0021_select_distinct.sql`.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5051]
It would be better move the test to `suites/0_stateless/03_dml` like a new name: `03_0021_select_distinct.sql`.

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/pull/5036#discussion_r857617543_

**Comment by lexcao** [comment]
I found this issue is resolved by [this commit](https://github.com/datafuselabs/databend/commit/f799b6e6114d00cb48d49f9c611105c052bf78de), so it should be closed.
