### ISSUE TITLE
Combine datetime interval add&subsruct  to one DATE_ADD

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5076]
**Summary**

Syntax:
```
​​DATE_ADD('<unit>', <interval>, <date_or_time_expr>)
```

`<unit>`: `SECOND`, `MINUTE`, `HOUR`, `DAY`, `WEEK`, `MONTH`, `YEAR`
`<interval>`: Number, this can be negative for substract
`<date_or_time_expr>`:  The expression evaluate to a date, time, or timestamp

Example:
```
SELECT toDate(18875), DATE_ADD('YEAR', 2, toDate(18875));
+---------------+-----------------------------+
| 2021-09-05    | 2023-09-05                  |
+---------------+-----------------------------+

SELECT toDate(18875), DATE_ADD('YEAR', -2, toDate(18875));
+---------------+-----------------------------+
| 2021-09-05    | 2019-09-05                  |
+---------------+-----------------------------+
```

**Comment by BohuTANG** [comment]
If possible, we can rename all the datetime funtion name from `xxYY` to `XX_YY`, like :`toMonth` to `TO_MONTH`

**Comment by sundy-li** [comment]
for `toStartOfTenMinutes`, which style shall we use?

1. to_start_of_ten_minutes
2. to_startoftenminutes

**Comment by sundy-li** [comment]
This function is not commonly used if the interval covers more units.

I suggest to use  `date` add/substract `interval-type`.


For Example:

```
select to_date ('2019-02-28') + interval '1 day, 1 year';

+---------------------------------------------------+
| TO_DATE ('2019-02-28') + INTERVAL '1 DAY, 1 YEAR' |
|---------------------------------------------------|
| 2020-03-01                                        |
+---------------------------------------------------+
```

**Comment by BohuTANG** [comment]
> 2\. to_startoftenminutes

If the name is long, how about `to_startoftenminutes`?

**Comment by BohuTANG** [comment]
> This function is not commonly used if the interval covers more units.
> 
> I suggest to use `date/datetime` add/substract `interval-type`.
> 
> For Example:
> 
> ```
> select to_date ('2019-02-28') + interval '1 day, 1 year';
> 
> +---------------------------------------------------+
> | TO_DATE ('2019-02-28') + INTERVAL '1 DAY, 1 YEAR' |
> |---------------------------------------------------|
> | 2020-03-01                                        |
> +---------------------------------------------------+
> ```

We can do it as:
```
DATE_ADD('day', 1, DATE_ADD('year', 1, TO_DATE ('2019-02-28'))
```

Interval syntax is a bit complex for the user.

**Comment by sundy-li** [comment]
Snowflake's interval syntax: https://dwgeek.com/snowflake-interval-data-types-and-conversion-examples.html/
Duckdb's interval syntax: https://duckdb.org/docs/sql/functions/interval

**Comment by sundy-li** [comment]
> DATE_ADD('day', 1, DATE_ADD('year', 1, TO_DATE ('2019-02-28'))

This is ok, but it needs two loops to calculate the results, so the performance may drop a two times.

**Comment by BohuTANG** [comment]
`Interval` seems another `function` to do that(the complex unit), but snow also has `date_add` :
https://docs.snowflake.com/en/sql-reference/functions/dateadd.html

I think they are two different functions, one for a simple unit(only one of `day`, `month` ...) and another for the complex unit(`day and year` ...).

**Comment by BohuTANG** [comment]
BTW, in duckdb, [interval](https://duckdb.org/docs/sql/data_types/interval) is a base data type.

**Comment by sundy-li** [comment]
We also have `interval` base data type. 

```
:) select typeof( interval '1' year),  interval '1' year;
+----------------+------+
| typeof(1)      | 1    |
+----------------+------+
| INTERVAL(YEAR) |    1 |
+----------------+------+
1 row in set (0.02 sec)
Read 1 rows, 1 B in 0.003 sec., 301.44 rows/sec., 301.44 B/sec.

```

**Comment by BohuTANG** [comment]
Have experienced with `interval`:
```
mysql> SELECT DATE '1992-03-22' + INTERVAL '5' DAY;
+----------------------------------+
| (cast('1992-03-22' as Date) + 5) |
+----------------------------------+
| 1992-03-27                       |
+----------------------------------+
1 row in set (0.06 sec)
Read 1 rows, 1 B in 0.011 sec., 90.55 rows/sec., 90.55 B/sec.

mysql> SELECT DATE '1992-03-22' + INTERVAL 5 DAY;
ERROR 1105 (HY000): Code: 1005, displayText = sql parser error: Expected literal string, found: 5.
mysql> SELECT DATE '1992-03-22' + INTERVAL '5 DAY';
ERROR 1105 (HY000): Code: 1002, displayText = invalid digit found in string (while in analyze select projection).
```

Seems the operator is not the same with snow or PostgreSQL:
```
{ + | - } INTERVAL '<integer> [ <date_time_part> ] [ , <integer> [ <date_time_part> ] ... ]'
```

DuckDB or MySQL style:
```
{ + | - } INTERVAL <integer> [ <date_time_part> ] [ , <integer> [ <date_time_part> ] ... ]
```
