### ISSUE TITLE
`Select sleep(1)` can't be parserd in new parser

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5079]
The case will fail in the parser phase:
```
  --> SQL:1:16
  |
1 | SELECT sleep(1)
  | ------         ^ expected token <FROM>
  | |
  | while parsing `SELECT ...`

```
cc @andylokandy

_Originally posted by @xudong963 in https://github.com/datafuselabs/databend/pull/5027#discussion_r860459101_

**Comment by andylokandy** [comment]
I have an ongoing PR that will implement it.
