### ISSUE TITLE
cargo test failed to pass `http_query_handlers`

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5090]
**Summary**
- Run `cargo test` in `query` folder works fine.

```
test servers::http::http_query_handlers::test_simple_sql ... ok
...
```

Run tests by clicking test button on vscode (or run following test cmd):

```
 cargo test --package databend-query --test it --all-features -- servers::http::http_query_handlers --nocapture 


...

failures:
    servers::http::http_query_handlers::test_async
    servers::http::http_query_handlers::test_http_handler_tls_server
    servers::http::http_query_handlers::test_http_service_tls_server_mutual_tls
    servers::http::http_query_handlers::test_http_session
    servers::http::http_query_handlers::test_simple_sql
    servers::http::http_query_handlers::test_system_tables

test result: FAILED. 10 passed; 6 failed; 1 ignored; 0 measured; 265 filtered out; finished in 2.81s
```

I do not know whether this is a bug or not. 

@youngsofun  do you know why?

**Comment by youngsofun** [comment]
only servers::http::http_query_handlers::test_async fail on my mac

**Comment by youngsofun** [comment]
test_simple_sql failed too...

**Comment by youngsofun** [comment]
rm  interpreter.finish() and interpreter.start(). make test_simple_sql pass

**Comment by youngsofun** [comment]
most tests in http_query_handlers use a long-pulling with  timeout of 1 sec, 
I think it is long enough for simple queries.

`interpreter.finish()` and `interpreter.start()` is the biggest extra time-consumer I can think of.
maybe also involve the overhead of talking to meta?

**Comment by youngsofun** [comment]
why need `backtrace initialization`?

**Comment by youngsofun** [comment]
test_simple_sql do not involve any ` wrong SQL`..

but seems you are right,  test_simple_sql only fail when I test itself

**Comment by sundy-li** [comment]
I disable `ENABLE_BACKTRACE`, the tests are stable now (except test_query_log which need backtrace).

So it's the cause of Backtrace.
