### ISSUE TITLE
bug: string function "trim" not work

### ISSUE THREAD

**Issue by jiahui-97** [datafuselabs/databend#5122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest

### What's Wrong?

String function ltrim and rtime work well, but trim not work.

```sql
MySQL [(none)]> select trim('  aaa  ');
ERROR 1105 (HY000): Code: 1005, displayText = Unsupported expression: TRIM('  aaa  '), type: Trim { expr: Value(SingleQuotedString("  aaa  ")), trim_where: None } (while in analyze select projection).

MySQL [(none)]> select ltrim('   aaa  ');
+-------------------+
| ltrim('   aaa  ') |
+-------------------+
| aaa               |
+-------------------+
1 row in set (0.05 sec)

MySQL [(none)]> select rtrim('  aaa  ');
+------------------+
| rtrim('  aaa  ') |
+------------------+
|   aaa            |
+------------------+
```

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Good catch.

1. Trim is taken as `Expr::Trim` in sqlparser, we should map it into `ExprRPNItem::function` like  [`Expr::Extract `](https://github.com/datafuselabs/databend/blob/594347a83bfcc6534f413947d375fbaa37460ad1/query/src/sql/statements/analyzer_expr.rs)

2. Add stateless tests for `trim` function.  https://github.com/datafuselabs/databend/blob/c63ea0a3c65f56f3c501c6a1e39d6448384c8a6f/tests/suites/0_stateless/02_function/02_0020_function_strings_ltrim.sql 

It's an easy task, would you like to try ? @jiahui-97

**Comment by jiahui-97** [comment]
Yeah, thank you. I will try to fix it.
