### ISSUE TITLE
Considering write table schema with snapshot

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5147]
**Summary**

Now we can time travel the data under our snapshot design, but we can not travel the table schema at that point in time.
```
T1: t1(a INT, b INT) --Snapshot1@2022_05_03
 |
 | Table alter
 |
 \/
T2: t1(a INT)  -- Snapshot2@2022_05_04
```

If we time travel to `T1(Snapshot1@2022_05_03)`, the table schema is inconsistent with the data, the metasrv only stores the latest table schema: T2.

**Comment by dantengsky** [comment]
> There is a `schema` field in the snapshot file:
> 
> ```
> {"format_version":1,"snapshot_id":"45133708-4465-4873-b701-99ceafdf93c7","prev_snapshot_id":["ca34a1ba-7287-4b7e-8afa-2b0e82a78649",1],"schema":{"fields":[{"name":"a","default_expr":null,"data_type":{"type":"Int32"}}],"metadata":{}},"summary":{"row_count":6,"block_count":3,"uncompressed_byte_size":24,"compressed_byte_size":522,"col_stats":{"0":{"min":{"Int64":1},"max":{"Int64":6},"null_count":0,"in_memory_size":24}}},"segments":[["53/132/_sg/9db9c989656e4b46912f5316565f3523_v1.json",1],["53/132/_sg/0071dcb1ddd74087a47d3eb8fb48c7da_v1.json",1],["53/132/_sg/11cd0deef6d344aab7de38e4ad0f93c1_v1.json",1]]}
> ```
> 
> Can we use it? @dantengsky

Yes, we can use it. sorry for the late response.
