### ISSUE TITLE
bug: Error: Code: 2001, displayText = MetaStoreNotFound.

### ISSUE THREAD

**Issue by kulame** [datafuselabs/databend#5160]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

➜  databend ./databend-meta --version              
databend-meta 0.1.0

### What's Wrong?

2022-05-04T16:16:39.286841Z  INFO common_meta_raft_store::state::raft_state: open: Some(()), create: None
Error: Code: 2001, displayText = MetaStoreNotFound.

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::MetaServiceError::{{closure}}
             at /project/common/exception/src/exception_code.rs:37:109
      core::bool::<impl bool>::then
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/bool.rs:47:24
      common_exception::exception_code::<impl common_exception::exception::ErrorCode>::MetaServiceError
             at /project/common/exception/src/exception_code.rs:37:30
   1: common_meta_types::meta_errors_into::<impl core::convert::From<common_meta_types::meta_errors::MetaError> for common_exception::exception::ErrorCode>::from
   2: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/result.rs:2106:27
      databend_meta::main::main_impl::{{closure}}
             at /project/metasrv/src/bin/metasrv.rs:52:21
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/future/mod.rs:91:19
      tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
      tokio::coop::with_budget::{{closure}}
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
      std::thread::local::LocalKey<T>::try_with
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/local.rs:442:16
      std::thread::local::LocalKey<T>::with
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/thread/local.rs:418:9
      tokio::coop::with_budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
      tokio::coop::budget
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
      tokio::park::thread::CachedParkThread::block_on
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
      tokio::runtime::enter::Enter::block_on
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
      tokio::runtime::handle::Handle::block_on
             at /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/handle.rs:355:9
      common_base::runtime::Runtime::block_on
             at /project/common/base/src/runtime.rs:137:9
      databend_meta::main
             at /project/metasrv/src/bin/metasrv.rs:90:7
   4: core::ops::function::FnOnce::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/ops/function.rs:227:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/sys_common/backtrace.rs:122:18
   5: std::rt::lang_start::{{closure}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/rt.rs:145:18
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/76d770ac21d9521db6a92a48c7b3d5b2cc535941/library/std/src/rt.rs:128:20
   7: main

### How to Reproduce?

i follow this document.

https://databend.rs/doc/deploy/local

``` 
mkdir databend && cd databend
curl -LJO https://github.com/datafuselabs/databend/releases/download/v0.7.32-nightly/databend-v0.7.32-nightly-x86_64-unknown-linux-musl.tar.gz
tar xzvf databend-v0.7.32-nightly-x86_64-unknown-linux-musl.tar.gz
echo "dir = "metadata/_logs"
admin_api_address = "127.0.0.1:8101"
grpc_api_address = "127.0.0.1:9101"

[raft_config]
id = 1
single = true
raft_dir = "metadata/datas"" >> databend-meta.toml
./databend-meta -c ./databend-meta.toml




### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by drmingdrmer** [comment]
```
mkdir databend && cd databend
curl -LJO https://github.com/datafuselabs/databend/releases/download/v0.7.32-nightly/databend-v0.7.32-nightly-x86_64-unknown-linux-musl.tar.gz
tar xzvf databend-v0.7.32-nightly-x86_64-unknown-linux-musl.tar.gz
echo "dir = "metadata/_logs"

```
I am not quite sure what you are doing with the `echo`. Can you show me the `databend-meta.toml` you were using?
