### ISSUE TITLE
BUG(fuse): Found that `bytes_compressed` is larger than `bytes_uncompressed` cc @dantengsky

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#5174]
> > Found that `bytes_compressed` is larger than `bytes_uncompressed` cc @dantengsky
> 
> how is the data of table `test` generated? Tring to re-produce this scenario.

```
create table test(a INT);
insert into test select * from numbers(20000000);
```

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/5172#issuecomment-1118474975_

------------

HOW TO RE-PRODUCE:

~~~
mysql> create table test(a INT);
Query OK, 0 rows affected (0.04 sec)
Read 0 rows, 0.00 B in 0.021 sec., 0 rows/sec., 0.00 B/sec.

mysql> insert into test select * from numbers(20000000);
Query OK, 0 rows affected (0.97 sec)
Read 20000000 rows, 152.59 MiB in 0.946 sec., 21.13 million rows/sec., 161.22 MiB/sec.

mysql> select * from fuse_snapshot('default', 'test')\G
*************************** 1. row ***************************
         snapshot_id: 3bcdfb12527d4e81adf228199df96cb3
   snapshot_location: 1/6/_ss/3bcdfb12527d4e81adf228199df96cb3_v1.json
      format_version: 1
previous_snapshot_id: NULL
       segment_count: 16
         block_count: 32
           row_count: 20000000
  bytes_uncompressed: 80000000
    bytes_compressed: 80320752
1 row in set (0.06 sec)
Read 1 rows, 176.00 B in 0.007 sec., 149.03 rows/sec., 25.61 KiB/sec.
~~~

if we use ctas form, the  number of `bytes_compressed` and `bytes_uncompressed` seem to be OK

```
mysql> create table test1 select * from numbers(20000000);
Query OK, 0 rows affected (1.41 sec)
Read 20000000 rows, 152.59 MiB in 1.392 sec., 14.36 million rows/sec., 109.58 MiB/sec.

mysql> select * from fuse_snapshot('default', 'test1')\G
*************************** 1. row ***************************
         snapshot_id: 6e609befa33f4ddf947f7043598a59ff
   snapshot_location: 1/5/_ss/6e609befa33f4ddf947f7043598a59ff_v1.json
      format_version: 1
previous_snapshot_id: NULL
       segment_count: 16
         block_count: 32
           row_count: 20000000
  bytes_uncompressed: 160000000
    bytes_compressed: 80036452
1 row in set (0.02 sec)
Read 1 rows, 176.00 B in 0.006 sec., 163.21 rows/sec., 28.05 KiB/sec.
```

**Comment by dantengsky** [comment]
Turns out that the two tables have different schemas, and unfortunately, the four bytes `INT` col type seems to be `a bad fit for LZ4` (which we currently use for column compression).

https://github.com/lz4/lz4/issues/649#issuecomment-463028671

For this scenario, we need other compression algos or proper column [encoding](https://github.com/apache/parquet-format/blob/master/Encodings.md)s


~~~
mysql> desc test;
+-------+------+------+---------+-------+
| Field | Type | Null | Default | Extra |
+-------+------+------+---------+-------+
| a     | INT  | NO   | 0       |       |
+-------+------+------+---------+-------+
1 row in set (0.05 sec)
Read 0 rows, 0.00 B in 0.003 sec., 0 rows/sec., 0.00 B/sec.

mysql> desc test1;
+--------+-----------------+------+---------+-------+
| Field  | Type            | Null | Default | Extra |
+--------+-----------------+------+---------+-------+
| number | BIGINT UNSIGNED | NO   | 0       |       |
+--------+-----------------+------+---------+-------+
1 row in set (0.03 sec)
Read 0 rows, 0.00 B in 0.004 sec., 0 rows/sec., 0.00 B/sec.
~~~

**Comment by BohuTANG** [comment]
> we need other compression algos or proper column

How can we change the lz compression to others?

**Comment by DCjanus** [comment]
I don't think this is a BUG, according to [Shannon's first theorem](https://en.wikipedia.org/wiki/Noisy-channel_coding_theorem), any compression algorithm on an infinite input space, there must be some cases produce larger output.

LZ4 is a dictionary-based compression algorithm, to compress data, the algorithm have to find repeated parts and mark as a short index to a table. And the size of parts has to be large enough, otherwise index would be larger than data.

Most LZ4 implementions find those repeate parts via sliding window in 4 byte. In this case, sequence of u32 wouldn't be able to find common parts in 4 byte sliding window. But for sequence of u64, there would be.

I hope this would be a pic to explain this.

ref: https://en.wikipedia.org/wiki/LZ4_(compression_algorithm)
ref: https://www.jianshu.com/p/824e1cf4f920

**Comment by DCjanus** [comment]
In this case, Huffman based algorithm may work better, and worse in other cases. Which means I don't think we should 'fix' this.

**Comment by BohuTANG** [comment]
Yes, let's close

**Comment by sundy-li** [comment]
Let's create the task `Adaptive compression method for various column`
