### ISSUE TITLE
Implement type checking of functions

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5205]
In databend, we have a vectorized query execution framework.

Every scalar expression will be compiled into a static-typed `Function`. For instance, the arithmetic binary operator `+` will be translated to `ArithmeticPlusFunction`. 

During type checking, it will try to find a overload of function which fits both argument types and required type. If not found, it will raise an semantic error.

Example:

```sql
select 1 + 1; -- plus(int, int)

select 1 + '1'; -- plus(int, int) , this case is special, postgres allows implicit cast from string literal to numeric type

select 1 + '1.1'; -- failed, '1.1' cannot be parsed into integer

select 1.1 + '1.1'; -- plus(float, float)

select int32_column + int64_column; -- plus(int32, int64)

select 1 + string_column; -- failed, no overload for plus(int, string)

select string + string; -- failed, no overload for plus(int, string)

select string_column = int_column + 1; -- failed, no overload for equal(string, int)
```

**Comment by andylokandy** [comment]
https://github.com/datafuselabs/databend/issues/5430

**Comment by leiysky** [comment]
Tracked in https://github.com/datafuselabs/databend/issues/6547
