### ISSUE TITLE
Test: create/drop/rename table has to increment the seq of db_meta

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5220]
Add standalone tests to ensure that when create/drop/rename a table, the seq of the belonging db_meta will be increased.

Reference:
https://github.com/datafuselabs/databend/blob/eb07b393c769b152ef742c0b8f91032de5c98562/common/meta/api/src/schema_api_test_suite.rs#L946-L960

The tests should be added as part of `schema_api_test_suite.rs` and should be called somewhere else a `SchemaAPI` is implemented, such as 

https://github.com/datafuselabs/databend/blob/eb07b393c769b152ef742c0b8f91032de5c98562/metasrv/tests/it/grpc/metasrv_grpc_schema_api.rs#L104-L114

**Comment by drmingdrmer** [comment]
@RinChanNOWWW
Maybe you will be interested in this small issue?

**Comment by RinChanNOWWW** [comment]
Thanks, I'll take a look.

**Comment by RinChanNOWWW** [comment]
\assignme
