### ISSUE TITLE
Feature: `explain` for new planner

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5235]
**Summary**

Description for this feature.

**Comment by leiysky** [comment]
For now, we doesn't have explain for `Plan` yet. The `EXPLAIN` operation will print the structure `Pipeline`, which isn't a part of migration. 

We can provide different kind of `EXPLAIN`, for example `EXPLAIN ANALYZE` for `Pipeline` and `EXPLAIN` for physical plans.

**Comment by BohuTANG** [comment]
Databend now `EXPLAIN` shows the logical plan, `EXPLAIN PIPELINE` shows the physical plan.

**Comment by xudong963** [comment]
> The `EXPLAIN` operation will print the structure `Pipeline`, which isn't a part of migration.

Got it

**Comment by leiysky** [comment]
> > The `EXPLAIN` operation will print the structure `Pipeline`, which isn't a part of migration.
> 
> Got it

I'm out of date... @BohuTANG  is right, we still need to implement `EXPLAIN` now.

**Comment by xudong963** [comment]
I misunderstood, I know we need to implement it, I thought you were just saying not to put it in our migration tasks this time 🤣

**Comment by leiysky** [comment]
> I misunderstood, I know we need to implement it, I thought you were just saying not to put it in our migration tasks this time 🤣

You got the point, I've put it in the tasks list again.

**Comment by BohuTANG** [comment]
Would like to add a new feature for `EXPLAIN`:
`EXPLAIN AST` -- Dump the AST
```
explain ast select number+1 as n1, number -1 as n2 from numbers(10);

EXPLAIN AST
SELECT
    number + 1 AS n1,
    number - 1 AS n2
FROM numbers(10)

Query id: 8cf8faec-74d3-410e-863b-1fb537858932

┌─explain─────────────────────────────────────┐
│ SelectWithUnionQuery (children 1)           │
│  ExpressionList (children 1)                │
│   SelectQuery (children 2)                  │
│    ExpressionList (children 2)              │
│     Function plus (alias n1) (children 1)   │
│      ExpressionList (children 2)            │
│       Identifier number                     │
│       Literal UInt64_1                      │
│     Function minus (alias n2) (children 1)  │
│      ExpressionList (children 2)            │
│       Identifier number                     │
│       Literal UInt64_1                      │
│    TablesInSelectQuery (children 1)         │
│     TablesInSelectQueryElement (children 1) │
│      TableExpression (children 1)           │
│       Function numbers (children 1)         │
│        ExpressionList (children 1)          │
│         Literal UInt64_10                   │
└─────────────────────────────────────────────┘

```

cc @leiysky

**Comment by xudong963** [comment]
> Would like to add a new feature for `EXPLAIN`:
> `EXPLAIN AST` -- Dump the AST

cc @andylokandy

**Comment by leiysky** [comment]
@xudong963  I suggest to leverage this to implement `EXPLAIN`. https://github.com/datafuselabs/databend/issues/5491
