### ISSUE TITLE
bug: `select *` can't work due to duplicate name in new planner 

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5236]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```sql
mysql> select * from numbers(1000) as t inner join numbers(1000) as t1 on t.number = t1.number;
ERROR 1105 (HY000): Code: 1002, displayText = Duplicate alias name :number (while in processor thread 0).
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leiysky** [comment]
@xudong963  The root cause of this issue is `ExpressionExecutor` doesn't allow duplicated names.

I'm going to refactor that after migrated to new planner.

**Comment by xudong963** [comment]
> I'm going to refactor that after migrated to new planner.

Nice!
