### ISSUE TITLE
Feature: support limit tenant quota

### ISSUE THREAD

**Issue by junnplus** [datafuselabs/databend#5249]
**Summary**

For example, we can limit the number of databases and tables created.

**Comment by junnplus** [comment]
@BohuTANG Any suggestions for storing tenant quota information?

**Comment by BohuTANG** [comment]
How do we set/update the quota?

**Comment by junnplus** [comment]
> How do we set/update the quota?

maybe use `CALL`?

**Comment by BohuTANG** [comment]
Make sense.
@drmingdrmer @dantengsky any suggestions?

**Comment by BohuTANG** [comment]
The limit CALL should be only allowed in the management mode, so if in the normal mode, we don't check the limits for the DDL, right? @junnplus

**Comment by BohuTANG** [comment]
The limit CALL `set/update` should be only allowed in the management mode.

**Comment by drmingdrmer** [comment]
Great.

On the metasrv side, just adding another quota assertion and quota update to SchemaAPI create/drop-db/table. No problem.
