### ISSUE TITLE
bug: `where` can't identify alias in new planner

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```
mysql> SELECT MAX(number) AS max FROM numbers_mt(10) where max > 8 GROUP BY number%3;
ERROR 1105 (HY000): Code: 1065, displayText = column "max" doesn't exist.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leiysky** [comment]
This is not actually a bug. We had a detailed discussion in https://github.com/datafuselabs/databend/issues/1553.

**Comment by xudong963** [comment]
> This is not actually a bug. We had a detailed discussion in #1553.

Oh, last time you also showed me, I forgot...

**Comment by leiysky** [comment]
I think we can just close this issue.
