### ISSUE TITLE
Insert into Array<T>  type panic

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5304]
**Summary**

```
create table t1(a Array(INT));
insert into t1 values ([1], [2,3], [4,5,6]);
```

Server error:
```
2022-05-11T12:45:15.666578Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: insert into t1 values ([1], [2,3], [4,5,6])
2022-05-11T12:45:15.671460Z ERROR common_tracing::panic_hook: panicked at 'index out of bounds: the len is 1 but the index is 1'
```

**Comment by b41sh** [comment]
SQL syntax has an error.
insert multi values should use this sql.
```sql
insert into t1 values ([1]), ([2,3]), ([4,5,6]);
```

**Comment by sundy-li** [comment]
fixed in #5306

**Comment by BohuTANG** [comment]
Does the out of index error is by design?
`ERROR 1105 (HY000): Code: 1006, displayText = Index out of array column bounds: the len is 1 but the index is 2 (while in processor thread 0).`

```
insert into t1 values([1]), ([2,3]);
Query OK, 0 rows affected (0.07 sec)
Read 2 rows, 36.00 B in 0.036 sec., 54.89 rows/sec., 988.06 B/sec.

mysql> select * from t1;
+--------+
| a      |
+--------+
| [1]    |
| [2, 3] |
+--------+
2 rows in set (0.06 sec)
Read 2 rows, 36.00 B in 0.012 sec., 163.89 rows/sec., 2.88 KiB/sec.

mysql> select a[0] from t1;
+------+
| a[0] |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.08 sec)
Read 2 rows, 36.00 B in 0.013 sec., 156.83 rows/sec., 2.76 KiB/sec.

mysql> select a[2] from t1;
ERROR 1105 (HY000): Code: 1006, displayText = Index out of array column bounds: the len is 1 but the index is 2 (while in processor thread 0).

```

**Comment by BohuTANG** [comment]
Snow returns null instead:
`If the index points outside of the array boundaries, or if the indexed element does not exist (in a sparse array), then this function returns NULL.`

https://docs.snowflake.com/en/sql-reference/functions/get.html

cc @b41sh @sundy-li

**Comment by sundy-li** [comment]
> If the index points outside of the array boundaries, or if the indexed element does not exist (in a sparse array), then this function returns NULL.

I think it's better to throw exceptions rather than null. 

- Nullable types are contagious which will hurt the performance of the query
- Nullable implicitly hides unreasonable query parameters

**Comment by BohuTANG** [comment]
I think it's not performance; it's the use case.
For example: 
If the user wants to get the array[2] result, they can't do it if an array only has one item.

**Comment by sundy-li** [comment]
> If the user wants to get the array[2] result,

Users can specify other values with if function  

-  `if( length(array) <  2,  123,  array[2])   `
- `if( length(array)  >=  2,  array[2],  123 )`

**Comment by sundy-li** [comment]
BTW, the index starts with zero, not one.

**Comment by BohuTANG** [comment]
Oops, it's not work:
```
sql> select if( length(a) < 2, 123, a[1]) from t1;
ERROR 1105 (HY000): Code: 1006, displayText = Index out of array column bounds: the len is 1 but the index is 1 (while in processor thread 0).

```

I think we should add more bound case in stateless test for the `array` function.
cc @b41sh

**Comment by sundy-li** [comment]
since the index starts with zero, not one.

so `select if( length(a) < 2, 123, a[0]) from t1;` can work

**Comment by BohuTANG** [comment]
```

mysql> select * from t1;
+--------+
| a      |
+--------+
| [1]    |
| [2, 3] |
+--------+



mysql> select if( length(a) < 2, 123, a[0]) from t1;
+--------------------------------+
| if((length(a) < 2), 123, a[0]) |
+--------------------------------+
|                            123 |
|                              2 |
+--------------------------------+
2 rows in set (0.07 sec)
Read 2 rows, 36.00 B in 0.014 sec., 142.35 rows/sec., 2.50 KiB/sec.

mysql> select if( length(a) < 2, 123, a[1]) from t1;
ERROR 1105 (HY000): Code: 1006, displayText = Index out of array column bounds: the len is 1 but the index is 1 (while in processor thread 0).
```

My purpose is to get the `array[1]` if it has.

**Comment by sundy-li** [comment]
Two way to resolve this:

1. Make `array[index]` support null return if the index is out of bounds (Snowflake/pg did)
2. Make `array[index]` return the default value if the index is out of bounds, can specify other return value with if function  (ClickHouse/firebolt did)

@BohuTANG  what do you think?

**Comment by b41sh** [comment]
I think returning null is more appropriate, the default value can be misleading

**Comment by BohuTANG** [comment]
Agree with @b41sh .
Returns NULL will tell the user this item is out of the index, not the default value.
