### ISSUE TITLE
[metasrv] unify kv_service and meta_service

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#5323]
**Summary**
Since we now use kv-api for all meta data, there is no need to distinguish kv-api and meta-api. cc @Xuanwo @drmingdrmer @lichuang 
ref: https://github.com/datafuselabs/databend/discussions/5320

**Comment by drmingdrmer** [comment]
There is only one `try_get_meta_store()` method now in `MetaStoreProvider`
