### ISSUE TITLE
Confusing behavior of string literal value with `\`

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5355]
```
MySQL [(none)]> select '\\%';
+------+
| '\%' |
+------+
| \%   |
+------+
1 row in set (0.031 sec)

MySQL [(none)]> select '\%';
+------+
| '\%' |
+------+
| \%   |
+------+
1 row in set (0.032 sec)

MySQL [(none)]> select '%' like '\\%';
+-----------------+
| ('%' like '\%') |
+-----------------+
|               1 |
+-----------------+
1 row in set (2.422 sec)

MySQL [(none)]> select '%' like '\%';
+-----------------+
| ('%' like '\%') |
+-----------------+
|               1 |
+-----------------+
1 row in set (1.368 sec)
```

This is the current behavior of databend, which is the same with MySQL.

But it looks the literal value `'\%'` and `'\\%'` should be defferent, even it's a regex.

The behavior of Postgres:
```
leiysky=# select '%' like '\%';
 ?column?
----------
 t
(1 row)

leiysky=# select '%' like '\\%';
 ?column?
----------
 f
(1 row)
```

The behavior of Snowflake:
![image](https://user-images.githubusercontent.com/22445410/168256637-932c0095-a51b-4ea3-b2e8-b306fdc9a1d2.png)

We can see that the behavior of Postgres is the same with Snowflake.

cc @BohuTANG @sundy-li

**Comment by BohuTANG** [comment]
Follow the Postgre/Snow way :)

**Comment by leiysky** [comment]
> Follow the Postgre/Snow way :)

Fortunately, new planner has been in this way.
