### ISSUE TITLE
Feature: Support SQL dialect in new parser

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5372]
Since SQL is not a well-defined language, the implementations are quite different.

It's impossible to design a SQL dialect which is compatible with all the mainstream SQL dialects, but we can adapt some basic concept from them.

The identifier quote style compatibility will be involved first. In MySQL, identifiers are quoted with \`a\`. And in Postgres, identifiers are quoted with "a". We can expose some configurations to switch between these styles.

**Comment by andylokandy** [comment]
Should the dialect be selected by the connection frontend?

**Comment by leiysky** [comment]
> Should the dialect be selected by the connection frontend?

Yes, determined when instantiating a parser object.

**Comment by youngsofun** [comment]
@leiysky can these issues be handler with  dialect?  https://github.com/datafuselabs/databend/issues/6127

**Comment by leiysky** [comment]
> @leiysky can these issues be handler with dialect? #6127

I don't think so. The dialect is mostly about the lexical element of SQL, e.g. identifier quote style.

**Comment by Xuanwo** [comment]
Dialect has been added. Let's close.
