### ISSUE TITLE
Support read compressed files in COPY statement

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5380]

**Comment by Xuanwo** [comment]
This issue is blocked by integrating with the new format trait.

The original opendal design will decompress the IO stream in async runtime which is not expected by the new processor.

I'm working on it to make it possible:

- IO on async runtime
- Decompress (which is CPU bound) on sync runtime

**Comment by Xuanwo** [comment]
Have a discussion with `async-compression`: https://github.com/Nemo157/async-compression/issues/150

**Comment by Xuanwo** [comment]
Sorry to keep you waiting, let's set sail!

In PR https://github.com/datafuselabs/databend/pull/5655, we got this works.
