### ISSUE TITLE
Feature: Efficient way to combine multiple filters

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5382]
Do we have a efficient way to combine multiple filter columns(i.e. `BooleanArray`), like `combine_validities`？

cc @sundy-li

**Comment by sundy-li** [comment]
It can be a performance improvement in [and.rs](https://github.com/datafuselabs/databend/blob/b9ea557c4a060b4622c1287bc7af71e126e609be/common/functions/src/scalars/logics/and.rs). 

We can use `combine_validities` to  merge the filters.

**Comment by TCeason** [comment]
> It can be a performance improvement in [and.rs](https://github.com/datafuselabs/databend/blob/b9ea557c4a060b4622c1287bc7af71e126e609be/common/functions/src/scalars/logics/and.rs).
> 
> We can use `combine_validities` to merge the filters.

Maybe I can continue to do this issue?
