### ISSUE TITLE
[test-infra] Test framework

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#540]
**Summary**

CI(Continuous Integration)  framework
CD(Continuous Delivery) framework

**Comment by zhang2014** [comment]
BDD: https://github.com/cucumber/cucumber-jvm

**Comment by ZhiHanZ** [comment]
some test frameworks I used before seems clear and concise,

for Unit tests to check code behavior, abseil could provide parameterized approach
https://github.com/abseil/abseil-py/blob/master/absl/testing/parameterized.py
and for Behavior Driven tests, ginkgo seems well.
https://github.com/onsi/ginkgo#tldr, 

for rust native UT framework, fluid seems promising to me, but seems like it still in alpha stage
https://docs.rs/fluid/0.4.1/fluid/wiki/index.html

**Comment by BohuTANG** [comment]
Rust:
https://github.com/enokson/laboratory

**Comment by BohuTANG** [comment]
Nightly release bot works.
https://github.com/datafuselabs/fusebots/commit/1a53e3d55a4ed9497a9e297dd6e89ff2ad6e5a96

**Comment by Xuanwo** [comment]
Implemented in #2647
