### ISSUE TITLE
Display human readable error if metasrv started without `--single` or `--join`

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5407]
**Summary**

**Comment by BohuTANG** [comment]
Databend config needs a friendly hint for the user if it doesn't work, @Xuanwo may have(plan) some ideas on it.

**Comment by Xuanwo** [comment]
@drmingdrmer If we must choose one of `--single` and `--join`, how about taking `--single` as default?

**Comment by drmingdrmer** [comment]
> @drmingdrmer If we must choose one of `--single` and `--join`, how about taking `--single` as default?

Sounds great!
