### ISSUE TITLE
replace macro todo()! with ErrorCode::UnImplement() when  possible

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#5418]
not friendly to users.
especially for HTTP handler clients, which will receive 500.

cc @ZeaLoVe 

we have about 50 `todo!()` in code base.

**Comment by youngsofun** [comment]
@BohuTANG git blame say you introduced    `UnImplement(1002),`  
is it the intended usage? e.g.
https://github.com/datafuselabs/databend/blob/main/common/datavalues/src/types/serializations/struct_.rs#L73

**Comment by BohuTANG** [comment]
cc @sundy-li
