### ISSUE TITLE
Null can't save in query result

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5434]
I found another， SELECT Null + 1, Null - 1, Null * 1, Null / 1;  
Mysql handler get ok：
+------------+------------+------------+------------+
| (NULL + 1) | (NULL - 1) | (NULL * 1) | (NULL / 1) |
+------------+------------+------------+------------+
|       NULL |       NULL |       NULL |       NULL |
+------------+------------+------------+------------+

Http handler get error：
"code": 1010,    ->  BadDataValueType(1010)
"message": "Ops is not support on datatype: Null"

cc @sundy-li @youngsofun

_Originally posted by @ZeaLoVe in https://github.com/datafuselabs/databend/issues/4976#issuecomment-1129523883_

**Comment by ZeaLoVe** [comment]
more:
SELECT TRY_INET_ATON(NULL);

**Comment by sundy-li** [comment]
I will support `max(null)` in the aggregate function.
