### ISSUE TITLE
metasrv: Make `--single` as default flag

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5447]
@drmingdrmer If we must choose one of `--single` and `--join`, how about taking `--single` as default?

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/5407#issuecomment-1129946591_

**Comment by drmingdrmer** [comment]
Hmm... with `--single`, it's a little bit redundant, but I am hoping it will be more explicit about what is going on for a user:

In case a user forgets to specify either `--single` or `--join` when bringing up a cluster of 3, he will boot up 3 clusters, each of which has only one node in it with:
```
# on node A:
databend-meta &

# on node B:
databend-meta &

# on node C:
databend-meta &
```

If either `--single` or `--join` has to be specified, a user must re-think what he wants.

**Comment by Xuanwo** [comment]
To me, it's easier to understand:

> Use `--join` to start a cluster, if not, I'm starting a local node

Instead of

> I need to choose between `--join` and `--single`, `--join` means xxx, `--single` means xxx.

---

For reference:

`crdb` has a separate command to bootstrap a cluster. To start a cluster, users need to:

```shell
cockroach init
cockroach start --join <xxxx>
```

`crdb` doesn't allow the user to start a single node cluster:

> cockroach start must be run with the --join flag. To start a single-node cluster, use cockroach start-single-node instead.

**Comment by drmingdrmer** [comment]
The point is that crdb has two explicit commands for single-mode and cluster-mode.

In our case, these two commands are `databend-meta --single` or `databend-meta --join xxx`.

I worry that a user does not read the doc and starts it with a single `databend-meta`. 🤔

**Comment by Xuanwo** [comment]
I got your concern! Let's keep them as-is until we find better UX.

**Comment by drmingdrmer** [comment]
> I got your concern! Let's keep them as-is until we find better UX.

:DDD
