### ISSUE TITLE
Feature: Format `SExpr` into string

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5491]
To implement `EXPLAIN`, we need a mechanism to format a plan into string.

I propose a tree-like structure to store the formated string of each plan node, and provide serialization interface to satisfy different need.

**Comment by xudong963** [comment]
> I propose a tree-like structure to store the formated string of each plan node, and provide serialization interface to satisfy different need.

Could you please describe it by more straightforward way?  Such as a simple example/picture.
