### ISSUE TITLE
doc: add how to monitor with Prometheus

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5515]
**Summary**

databend-query and databend-meta both have the exporter for Prometheus, should add a document on how to do it.

**Comment by hantmac** [comment]
I want to take it, but I found it seems that [this pr](https://github.com/datafuselabs/databend/pull/5602) have fixed this issue?

**Comment by BohuTANG** [comment]
5602 is for databend-meta, we also need to monitor the databend-query.

**Comment by rahul3002** [comment]
If this issue is open, I'd love to tackle it head-on!

**Comment by PsiACE** [comment]
> If this issue is open, I'd love to tackle it head-on!

https://databend.rs/doc/monitor/tools/prometheus-and-grafana 

We have already added the corresponding document before. Thank you for helping us find this issue, I will close it.
