### ISSUE TITLE
[docs] Deploy sample minio failed according to the docs 

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#5524]
When I want to deploy databend in k8s cluster, I need to install minio first, but I got the following error:
```
running "VolumeBinding" filter plugin for pod pod has unbound immediate PersistentVolumeClaims
```

<img width="1812" alt="image" src="https://user-images.githubusercontent.com/7600925/169780383-8dff61c9-3c3c-4646-80b3-ea3b32264056.png">

In the same time, the `pvc` is in Pending status.

Because there are no files to install `storageClass` and `PV`.
https://github.com/datafuselabs/databend/blob/eb07b393c769b152ef742c0b8f91032de5c98562/scripts/kubernetes/minio-sample.yaml#L9

**Comment by BohuTANG** [comment]
Thanks for the report!

**Comment by everpcpc** [comment]
Installing via helm chart is recommend: https://github.com/datafuselabs/helm-charts
Maybe you cound try this instead.
