### ISSUE TITLE
bug:  test_run_shuffle_action_with_scatter has been running for over 60 seconds

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#5529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

the ci run for a long time(55m 59s), cancel it, see this in the end of the log

https://github.com/datafuselabs/databend/runs/6551932830?check_suite_focus=true

test api::rpc::flight_dispatcher::test_run_shuffle_action_with_scatter has been running for over 60 seconds

### How to Reproduce?

ci

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Fixed, let's close.
