### ISSUE TITLE
failures in test-compat(compatibility test)

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5540]
One of them is:

https://github.com/datafuselabs/databend/runs/6565250395?check_suite_focus=true

```
--- /workspace/tests/suites/0_stateless/20+_others/20_0001_planner_v2.result	2022-05-24 00:50:34.010517793 +0000
+++ /workspace/tests/suites/0_stateless/20+_others/20_0001_planner_v2.stdout	2022-05-24 00:55:07.021903333 +0000
@@ -1,3 +1,4 @@
+ERROR 1105 (HY000) at line 79: Code: 1006, displayText = Unable to get field named ""number"_0". Valid fields: ["\"salary\"_1", "\"user_name\"_2"].
 ====SELECT_FROM_NUMBERS====
 0
 1
@@ -92,7 +93,6 @@
 0
 2
 5	5
-1
 4950
 100
 1
```

The failed SQL statement is:

https://github.com/datafuselabs/databend/blob/5648b5b5508c97adbb2b482d66ae889459167512/tests/suites/0_stateless/20%2B_others/20_0001_planner_v2.sql#L90

**Comment by drmingdrmer** [comment]
This failure happened in the compatibility test, in which it was using an old query: https://github.com/datafuselabs/databend/releases/tag/v0.7.57-nightly, and the latest metasrv.

I do not know if this affects this test.

**Comment by leiysky** [comment]
This test is introduced in https://github.com/datafuselabs/databend/pull/5538, and should have been fixed by this PR. Maybe it failed due to the old query.

**Comment by drmingdrmer** [comment]
Ok. I limited the test cases in test-compat to just ddl-related. I'll close this issue if it passed.
