### ISSUE TITLE
Feature: stage quota limit

### ISSUE THREAD

**Issue by junnplus** [datafuselabs/databend#5558]
**Summary**

followup https://github.com/datafuselabs/databend/issues/5249

Add `max_stages` in `TenantQuota` and check it.
https://github.com/datafuselabs/databend/blob/main/common/meta/types/src/tenant_quota.rs#L22-L28
```
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Default)]
#[serde(default)]
pub struct TenantQuota {
    pub max_databases: u32,
    pub max_tables_per_database: u32,
    pub max_stages: u32,
}
```

**Comment by ZhiHanZ** [comment]
I think it should not be a good first issue as it needs to communicate a lot with maintainer members to push it forward, and should be labeled as cloud

**Comment by sundy-li** [comment]
Will the external stage follow this quota limitation?

**Comment by BohuTANG** [comment]
> Will the external stage follow this quota limitation?

I think it is.
This quota number can be large at first(For example 100, and we can set it for one tenant).
We also need a  `max_files_per_stage` to limit the max file numbers of one stage.

**Comment by junnplus** [comment]
It seems that @sundy-li  is supporting getting stage files via meta, check `max_files_per_stage` may need to rely on it.
