### ISSUE TITLE
Potential race condition when SessionManager::reload_config()

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5577]
When a new config is being reloaded, the fields that depend on `config` are updated one by one.

There is a chance of getting one field with the old config and another one with the new config.

E.g., running these two statements `let a = get_storage_cache_manager(); let b = get_storage_operator()` while reloading config taking place. Especially as reloading config involves several `.await` calls, which may take dozen of millisecond to complete.

https://github.com/datafuselabs/databend/blob/f98207f882db08a023a6dd784b1af83a3262aaed/query/src/sessions/session_mgr.rs#L354-L384

**Comment by Xuanwo** [comment]
There is no reload anymore.
