### ISSUE TITLE
Feature: support setting `null_string`

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5586]
**Summary**

Description for this feature.

Add a new setting named `null_string`, which defaults to `\N`.

[nullable deserialization](https://github.com/datafuselabs/databend/blob/c0f745c3c06c632ec346db631896616908aa4466/common/datavalues/src/types/deserializations/nullable.rs)

and

[nullable serialization](https://github.com/datafuselabs/databend/blob/70e4acd8255a07f396ece09165c193af670328d8/common/datavalues/src/types/serializations/nullable.rs)  should respect this setting

**Comment by LiuYuHui** [comment]
> I want it.

Hi @wubx , Do you want to implement it or do you just want this feature? If you just want this feature, I think I can help implement it.

**Comment by sundy-li** [comment]
> Do you want to implement it or do you just want this feature? If you just want this feature, I think I can help implement it.

I think he just wants to have this feature. It's assigned to you, good luck!

**Comment by wubx** [comment]
Very much looking forward to this feature.
Maybe changing \N to null or NULL is a good way.

**Comment by JialuGong** [comment]
@wubx I'm sorry for that I am fighting with my final exams and  maybe I have no spare time to finish this issue until July 15th : (

**Comment by sundy-li** [comment]
> I'm sorry for that I am fighting with my final exams and maybe I have no spare time to finish this issue until July 15th :

It's ok, thanks for your information, we will take it.
