### ISSUE TITLE
Hide password in query log

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#5599]
Password in query log will be displayed in plain text. It should be replaced with something like `***`:
```
   68 2022-05-26T05:53:51.880269Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: create user 'myadmin'@'%' identified by 'aaaaaa'
```

**Comment by Xuanwo** [comment]
Is this issue still valid?

**Comment by drmingdrmer** [comment]
It looks like it is:
https://github.com/datafuselabs/databend/blob/f59efc05bc080e762846fbe8bac24c806e432a75/src/query/service/src/servers/mysql/mysql_interactive_worker.rs#L335

@youngsofun

**Comment by youngsofun** [comment]
- [ ] mysql handler
    - [ ] should let client send hash？ 
- [ ]  http handlers
   - [ ]  middleware
- [ ] parser: turn into hash in plan

**Comment by BohuTANG** [comment]
Done
