### ISSUE TITLE
Feat: catalog.drop_table_by_id

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5626]
> Is there a consistency issue that `drop_table` at line 79 and `truncate()` at line 86 will take place on different tables?
> 
> _Originally posted by @drmingdrmer in https://github.com/datafuselabs/databend/pull/5619#discussion_r883231426_

------------------

- [ ] introduce `drop_table_by_id` method to catalog
    which ... drops a table by id :)
- [ ] refine the impl of `drop all`
    use `drop_table_byd_id` instread of drop table -> 
https://github.com/datafuselabs/databend/blob/797c1acb205ea7cdcdc37d5adabf97139580a135/query/src/interpreters/interpreter_table_drop.rs#L79
    just follow the `tbl.get_table_info`, and find the table's id

**Comment by drmingdrmer** [comment]
> /assignme

Thanks man!

**Comment by LiuYuHui** [comment]
Hi @dantengsky, I am confused about why drop_table at line 79 and truncate() at line 86 will take place on different tables? it seems like `drop_table` and `truncate` use the same table name, it should operate on the same table. Could you please help me understand this? Thanks a lot.

**Comment by drmingdrmer** [comment]
> Hi @dantengsky, I am confused about why drop_table at line 79 and truncate() at line 86 will take place on different tables? it seems like `drop_table` and `truncate` use the same table name, it should operate on the same table. Could you please help me understand this? Thanks a lot.

When a table is dropped, another table with the same table can be created, in this interval of time, just before the second usage of this name.

**Comment by LiuYuHui** [comment]
If we need to implement `drop_table_by_id` to catalog, it seems like we need to add `drop_table_by_id` to `SchemaApi`? or my understanding is not correct, there is an easy way to do this?

**Comment by drmingdrmer** [comment]
> If we need to implement `drop_table_by_id` to catalog, it seems like we need to add `drop_table_by_id` to `SchemaApi`?

Yes:)

> or my understanding is not correct, there is an easy way to do this?

This seems to be the only way :(

**Comment by johnhaxx7** [comment]
Hi @BohuTANG , seems like this is still open and no update, can you please help transfer to me if it's ok? Thanks!

**Comment by BohuTANG** [comment]
@dantengsky do we still need this api now?
