### ISSUE TITLE
Feature: support `HashMethodKind::KeysU128, KeysU256`

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5630]
**Summary**

Description for this feature.

**Comment by xudong963** [comment]
Seems we should push `arrow2` to support `u128` and `u256`? @sundy-li

**Comment by sundy-li** [comment]
arrow2 will not support u128, u256 since it's not the goal as readme described.

> MUST NOT implement any logical type other than the ones defined on the arrow specification, [schema.fbs](https://github.com/apache/arrow/blob/master/format/Schema.fbs).

But we can use u128(u256) in memory and serialize the `Vec<u128>` into binary column.
