### ISSUE TITLE
Documentation of tuple types

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5639]
Seems there is no document of tuple types in databend.rs

![image](https://user-images.githubusercontent.com/22445410/170733820-5aa13ec5-5db5-48cd-ba32-6e5514b19160.png)

**Comment by leiysky** [comment]
cc @BohuTANG

**Comment by BohuTANG** [comment]
If we document the new `tuple`  data type to the user, how do they use for? 
I think the array data type can do that.
duckdb and snowflake do not have the `tuple` data type, and they suggest using `array` instead.
cc @sundy-li

**Comment by sundy-li** [comment]
`Tuple` is not stable so we did not have tuple documents.

Tuple can't be replaced by `array<T>` datatype, it's a special datatype of `StructType`, every field in this datatype can be different.

**Comment by BohuTANG** [comment]
Oh, not ARRAY<T>, compares with ARRAY semi-structured type, it can have different type item too.

**Comment by sundy-li** [comment]
> Oh, not ARRAY<T>, compares with ARRAY semi-structured type, it can have different type item too.

It's not statically dispatched if we use `ARRAY semi-structured` type to represent tuple.  So users must cast the column into a specific column in the following query:

```
select sum(  cast(arr.1  as Int) )   from table
```

It can work. Yet:

1. Its performance is really poor than true tuple-based query.
2. Users should know the cast may throw errors if `arr.1` is not an integer.

**Comment by wubx** [comment]
@BohuTANG  Can I take this issue?

**Comment by BohuTANG** [comment]
I rember tuple only used for internal not a data type, cc @sundy-li

**Comment by sundy-li** [comment]
Tuple could be used as datatype now.

**Comment by wubx** [comment]
```
mysql> desc t_table;
+-------+-------------------------+------+----------------------------------+-------+
| Field | Type                    | Null | Default                          | Extra |
+-------+-------------------------+------+----------------------------------+-------+
| event | (0 TIMESTAMP, 1 STRING) | NO   | (1970-01-01 00:00:00.000000, "") |       |
+-------+-------------------------+------+----------------------------------+-------+
1 row in set (0.02 sec)
Read 0 rows, 0.00 B in 0.004 sec., 0 rows/sec., 0.00 B/sec.

mysql> select event.0 from t_table;
ERROR 1105 (HY000): Code: 1065, displayText = tuple index is starting from 1, but 0 is found.
mysql> select event.1 from t_table;
+----------------------------+
| event.1                    |
+----------------------------+
| 2023-02-14 08:00:00.000000 |
+----------------------------+
1 row in set (0.03 sec)
Read 1 rows, 8.00 B in 0.006 sec., 171.09 rows/sec., 1.34 KiB/sec.
```
The elements of a Databend tuple can be accessed by their indices, which start from 1.  But desc table tuple elements from 0,  Whether this is expected or not? @sundy-li

**Comment by sundy-li** [comment]
Will fix that.
