### ISSUE TITLE
website: Twitter card doesn't display correctly

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5658]
As reported by @wey-gu, databend.rs 's page doesn't have a correct Twitter card.

![image](https://user-images.githubusercontent.com/5351546/170854561-34b30f0f-e334-4a89-bb7c-3329a4772a92.png)

I think https://docusaurus.io/ should already handle this.

Ping @Chasen-Zhang to take a look, thanks!

**Comment by Chasen-Zhang** [comment]
Is the picture not showing up? @Xuanwo

**Comment by BohuTANG** [comment]
I think the card is something like this:
![image](https://user-images.githubusercontent.com/172204/170900348-d8d47b0e-42e5-4796-b17e-dd29a8f992b8.png)

**Comment by BohuTANG** [comment]
https://github.com/facebook/docusaurus/issues/4260

**Comment by Xuanwo** [comment]
For reference: https://docusaurus.io/docs/next/api/themes/configuration#meta-image
