### ISSUE TITLE
RFC: Unify Session API

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5679]
# Background
For now, the execution of a query is driven by query handler. There are some disadvantage of this scheme:

- The API is restricted by specific protocol(e.g. mysql, clickhouse), which makes it very hard to implement some new features
- Redundant implementation of query execution. There are multiple versions of `do_query` implemented for clickhouse handler, mysql handler and http handler, which are actually doing the same thing

To resolve the issues, and to provide better extensibility, I propose a unified `Session` API in this RFC.

As we know, database is a typical software in client/server model. Every user will connect to database server with a client(e.g. mysql shell, ODBC driver). Once the connection established, a `Session` will be assigned to user, which stores the state of current
database connection including user information, opened database, session variables and so on.

When user types a query, it will be send to database server via `Session`. As soon as the query execution is finished, the result will be send back to user via `Session` as well.

So we can have a `Session` object like:
```rust
trait Session {
    fn get_variables(&self) -> Result<Vec<Variable>>;
    fn set_variable(&mut self, name: &str, value: &str) -> Result<()>;

    fn execute(&mut self, query: &str) -> Result<DataBlockStream>;
    fn execute_async(&mut self, query: &str) -> Result<QueryID>;
    fn prepare(&mut self, query: &str) -> Result<()>;
}
```

The benifits of a unified `Session` API are:
- No duplicated implementations, all in one
- Possible to have customized features

# Design detail
**WIP**

**Comment by youngsofun** [comment]
apps like snowflake worksheet may have diff requirements for `session`: not binding to connection, 
the session state (settings, vars) is not stored on databand-query,  so without loss of session we can achieve:

1. suspend in a few minutes
2. query can dispatch to diff server for HA and LB.

**Comment by leiysky** [comment]
> apps like snowflake worksheet may have diff requirements for `session`: not binding to connection, the session state (settings, vars) is not stored on databand-query, so without loss of session we can achieve:
> 
> 1. suspend in a few minutes
> 2. query can dispatch to diff server for HA and LB.

The persist mechanism will be discussed in this RFC. But the storage and load scheme of session won't be involved now.

**Comment by BohuTANG** [comment]
Yes.
@zhang2014 used to try to unify them (http/clickhouse/mysql).

**Comment by BohuTANG** [comment]
Outdated.
