### ISSUE TITLE
Feature: support explict `cross join` syntax

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5714]
**Summary**
Parser doesn't seem to understand the syntax.

```sql
mysql> select * from t1 cross join t2;
ERROR 1105 (HY000): Code: 1005, displayText = error:
  --> SQL:1:31
  |
1 | select * from t1 cross join t2
  |                               ^ expected `(`, `.`, `AT`, <Ident>, <QuotedString>, `AS`, or 2 more ...

.
```
cc @andylokandy @leiysky

**Comment by leiysky** [comment]
@andylokandy By the way, we'd better flat `,` concatened cross join into `Vec<TableReference>`, since we may support lateral join semantic later.

**Comment by andylokandy** [comment]
Why lateral join need flattened table references?
