### ISSUE TITLE
Feature: store stage information into meta service

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5723]
**Summary**

Description for this feature.

Command "list @stage_name" should only list from meta service if the stage is internal.

**Comment by BohuTANG** [comment]
@TCeason ,
I set this task to high priority, the cloud stage feature needs it :) 

cc @Xuanwo @Chasen-Zhang , for the stage list we don't need to start a warehouse anymore.

**Comment by junnplus** [comment]
https://github.com/datafuselabs/databend/pull/5857
