### ISSUE TITLE
Would you mind flaten the cross join here into `Vec<TableReference>`, and join them together in a right-deep fashion in binder?

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5734]
Would you mind flaten the cross join here into `Vec<TableReference>`, and join them together in a right-deep fashion in binder?
https://github.com/datafuselabs/databend/blob/51b93882138a1301dfd5840773af9b1f47d46632/common/ast/src/parser/query.rs#L63-L74

_Originally posted by @leiysky in https://github.com/datafuselabs/databend/issues/5730#issuecomment-1143773625_

**Comment by andylokandy** [comment]
I have a local branch that has done this work, but I realized that recusive algorithm works better on resolving cross join and latetal join.

**Comment by leiysky** [comment]
@andylokandy You are right, let's just close the issue.
