### ISSUE TITLE
bug: dababend -V version is wrong

### ISSUE THREAD

**Issue by enmotplinux** [datafuselabs/databend#5747]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

version: 0.7.65-nightly
min-compatible-client-version: 0.7.57

### What's Wrong?

[root@szth-24-4-107 bin]# ./databend-meta -V
databend-meta 0.1.0

./databend-meta -V 

[root@szth-24-4-107 bin]# ./databend-meta --cmd ver
version: 0.7.65-nightly
min-compatible-client-version: 0.7.57

### How to Reproduce?

./databend-meta -V

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Thanks for the report.

`-V` is the rust package version, now all the version is  `0.1.0` in databend, I think we can remove this flag from databend, please ignore it.
`--cmd ver` is the service version, we use this version to trace the binary.
