### ISSUE TITLE
NULLIF function

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5769]
**Summary**

Category: Conditional Functions

The `NULLIF()` function compares two expressions and returns NULL if they are equal. Otherwise, the first expression is returned.
Syntax:
```
NULLIF( <expr1> , <expr2> )
```

Reference:
https://docs.snowflake.com/en/sql-reference/functions/nullif.html

**Comment by RinChanNOWWW** [comment]
Need some help. Is there any comparison method that can accept NULL?

I'm now using:

```rust
let eq_func = ComparisonEqFunction::try_create_func("eq", args)?;
let eq_col = eq_func.eval(func_ctx.clone(), columns, input_rows)?;
```

to compute the equality of two columns.

But it seems that there is a little trouble when meet with NULL.

Or I need to compare the row values one by one on my own?

**Comment by RinChanNOWWW** [comment]
Another problem is, when I use this SQL:

```sql
SELECT NULLIF(1,1);
```

```rust
fn eval(
        &self,
        func_ctx: FunctionContext,
        columns: &ColumnsWithField,
        input_rows: usize,
    ) -> Result<ColumnRef>;
````

It seems the value of `columns[0].column().is_const()` is `false`.

**Comment by RinChanNOWWW** [comment]
> Need some help. Is there any comparison method that can accept NULL?
> 
> I'm now using:
> 
> ```rust
> let eq_func = ComparisonEqFunction::try_create_func("eq", args)?;
> let eq_col = eq_func.eval(func_ctx.clone(), columns, input_rows)?;
> ```
> 
> to compute the equality of two columns.
> 
> But it seems that there is a little trouble when meet with NULL.
> 
> Or I need to compare the row values one by one on my own?

Solved.

**Comment by sundy-li** [comment]
Do not need to create a new function. We can transform the expression into:

`if ( a == b, null, a)`

**Comment by RinChanNOWWW** [comment]
Can you tell me more detail about this?  Is there any example about rewrite one function by another?   @sundy-li

**Comment by sundy-li** [comment]
https://github.com/datafuselabs/databend/blob/4190591fbfb7cd0ae8ec15e5f061f6ebaceb62dd/query/src/sql/planner/semantic/type_check.rs#L412-L436

You can implement it in new planner framework like `Position` expr.

**Comment by RinChanNOWWW** [comment]
Do I also need to modify sqlparser-rs ? @sundy-li

**Comment by RinChanNOWWW** [comment]
Do I need to modify sqlparser_rs? @sundy-li

**Comment by RinChanNOWWW** [comment]
Do I also need to modify sqlparser_rs?  @sundy-li

**Comment by sundy-li** [comment]
> Do I also need to modify sqlparser_rs? @sundy-li

No need, you just need to modify the new parser in `common/ast`. We are moving from the old parser/planner to the new  now.

**Comment by RinChanNOWWW** [comment]
Is there any detail document about the new planner framework? I modify the parser but it seems not work.

**Comment by sundy-li** [comment]
New parser is in `common/ast`, new planner is in `query/sql/plan`.

I think you just to modify new parser & `TypeChecker`.

You  may need enable it via `set enable_planner_v2 = 1;`  Like https://github.com/datafuselabs/databend/blob/5a00c5ded62467a1e9947e058d9b74b50a035fdb/tests/suites/0_stateless/20+_others/20_0001_planner_v2.sql

**Comment by RinChanNOWWW** [comment]
> You may need enable it via set enable_planner_v2 = 1;

This works, thank you.
