### ISSUE TITLE
Migrate all statements to new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5773]
# Timeline

We're going to deliver this work in about two weeks(i.e. finish before **June 17th, 2022**).

# Task list

- Table DDL
  - [x] #5774
- Database DDL
  - [x] #5775
- Stage DDL
  - [x] #5776
- User DDL
  - [x] #5777
- UDF(user-defined function) DDL
  - [x] #5778
- View DDL
  - [x] #5779
- `INSERT`
  - [x] #5780
- `COPY INTO`
  - [x] #5781 
- System `SHOW`
  - [x] #5799
# Guide

Here's a sample PR which implements `CREATE TABLE` statement in new planner #5771 .

The steps to migrate a statement can be summarized into:
- Check if the new parser has supported the corresponding statement, implement it manually if necessary.
- Implement the `bind_xxx_statement` method for `Binder`, and add a `Plan::XxxStatement` variant.
- Try to reuse the implementation of `XxxInterpreter`. This should work for most of the DDL statements.
- Add the supported statement to `InterpreterFactoryV2::check` and `InterpreterFactoryV2::get`, so we can execute the statement with new planner when it's enabled

**Comment by Xuanwo** [comment]
Updated description to adopt Github's tracking issue feature

![image](https://user-images.githubusercontent.com/5351546/172074735-c0eecf23-80e0-4d43-97bb-e789e20e0aef.png)

**Comment by leiysky** [comment]
After discussing with @sundy-li , we decide to set up a time requirement for this task. The timeline information is added to the description of this issue.

**Comment by Xuanwo** [comment]
All statements have been migrated.
