### ISSUE TITLE
Migrate `USER` related DDL statements to new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5777]
## User related
- [x] `CREATE USER` https://github.com/datafuselabs/databend/pull/5802
- [x] `DROP USER` https://github.com/datafuselabs/databend/pull/5813
- [x] `ALTER USER`https://github.com/datafuselabs/databend/pull/5823
- [x] `SHOW USERS` https://github.com/datafuselabs/databend/pull/6016

## Role related
- [x] `CREATE ROLE` https://github.com/datafuselabs/databend/pull/5935
- [x] `DROP ROLE` https://github.com/datafuselabs/databend/pull/5935
- [x] `SHOW ROLES` https://github.com/datafuselabs/databend/pull/6016

## Privilege related
- [x] `GRANT <privileges>` https://github.com/datafuselabs/databend/pull/6049
- [x] `GRANT ROLE` https://github.com/datafuselabs/databend/pull/6049
- [ ] `REVOKE <privileges>` https://github.com/datafuselabs/databend/pull/6066
- [ ] `REVOKE ROLE` https://github.com/datafuselabs/databend/pull/6066
- [x] `SHOW GRANTS` https://github.com/datafuselabs/databend/pull/6049

**Comment by junnplus** [comment]
Related to my work, I will finish it.
