### ISSUE TITLE
Migrate `UDF` related DDL statements to new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5778]
- [x] #5904
- [x] https://github.com/datafuselabs/databend/issues/6317
- [x] https://github.com/datafuselabs/databend/issues/6325
- [x] #5899

**Comment by TennyZhuang** [comment]
I’d like to try it .

**Comment by Xuanwo** [comment]
https://github.com/datafuselabs/databend/issues/5904 has been merged.

Is there other statements we have to address?

**Comment by TennyZhuang** [comment]
> > Is there other statements we have to address?
> 
> We have `ALTER FUNCTION` and `DROP FUNCTION` left. @TennyZhuang Would you like to finish the rest of them?

I can do it but I’m busy recently so that I can’t give a promise when to finish them. If others are interested, feel free to take over the issue.

**Comment by Xuanwo** [comment]
Let me take this so that we can finish the migration this week.

**Comment by Xuanwo** [comment]
All UDF DDL statements have been migrated.
