### ISSUE TITLE
Feature: random Table Engine

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#5811]
**Summary**

This is very useful for testing.

```
create table t ( a int, b varchar, ....) Engine = Random;

select * from t limit 10; -- will generate ten rows random data .
```

Thus we can use this engine to generate random data and use them to test other features.

**Comment by RinChanNOWWW** [comment]
How about inserting, deleting and query without limit? Just throw an error?

**Comment by sundy-li** [comment]
Just throw unsupported errors.
