### ISSUE TITLE
Feature: create table on databend use MySQL grammar

### ISSUE THREAD

**Issue by enmotplinux** [datafuselabs/databend#5819]
**Summary**

Description for this feature.

1. Support  COMMENT "xx"
2. int bigint(x) varchar(x)  display 
3. Support decimal(18,2) type
4. display ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci

definitely goal: use mysqldump dump schema can recover databend.

**Comment by wubx** [comment]
https://github.com/datafuselabs/databend/issues/5829

**Comment by leiysky** [comment]
Duplicated with https://github.com/datafuselabs/databend/issues/4712
