### ISSUE TITLE
parser support clickhouse insert format all in http body

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#5824]
https://clickhouse.com/docs/en/interfaces/http/

> Send the request as a URL ‘query’ parameter, or as a POST. Or send the beginning of the query in the ‘query’ parameter, and the rest in the POST (we’ll explain later why this is necessary). The size of the URL is limited to 1 MiB by default, this can be changed with the http_max_uri_size setting.

example:

- https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/src/infi/clickhouse_orm/database.py#L226
- https://github.com/apache/apisix/blob/a933c0bda43c275f7cd832511c85b8322c506d80/apisix/plugins/clickhouse-logger.lua#L106

@sundy-li  @leiysky

**Comment by leiysky** [comment]
I think it's possible to support the syntax now, but the rest part need more investigation.

@sundy-li What do you think of this?

**Comment by sundy-li** [comment]
I have talked with @andylokandy , he will support it in the new parser. 

I'll make it work in the old parse with the next pr.
