### ISSUE TITLE
bug: date function has bug.

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#5837]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

Server version: 8.0.26-v0.7.73-nightly-c2b82c5-simd(rust-1.63.0-nightly-2022-06-07T11:33:52.424430797Z) 0

### What's Wrong?

https://github.com/datafuselabs/databend/blob/594347a83bfcc6534f413947d375fbaa37460ad1/common/functions/src/scalars/dates/simple_date.rs#L44

utc is now.

```
impl NoArgDateFunction for Today {
    fn execute() -> i32 {
        let utc: Date<Utc> = Utc::now().date();
        let epoch = NaiveDate::from_ymd(1970, 1, 1);

        let duration = utc.naive_utc().sub(epoch);
        duration.num_days() as i32
    }
}
```

### How to Reproduce?

```SQL
'root'@mysqldb 13:37:48 [(none)]> set timezone='America/Vancouver';
Query OK, 0 rows affected (0.04 sec)
Read 0 rows, 0.00 B in 0.003 sec., 0 rows/sec., 0.00 B/sec.

'root'@mysqldb 13:37:57 [(none)]> select today();
+------------+
| today()    |
+------------+
| 2022-06-08 |
+------------+
1 row in set (0.06 sec)
Read 1 rows, 1.00 B in 0.004 sec., 236.41 rows/sec., 236.41 B/sec.

'root'@mysqldb 13:37:59 [(none)]> select now();
+----------------------------+
| now()                      |
+----------------------------+
| 2022-06-07 22:38:03.750760 |
+----------------------------+
1 row in set (0.04 sec)
Read 1 rows, 1.00 B in 0.005 sec., 194.96 rows/sec., 194.96 B/sec.

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
date has no related to timezone.

**Comment by TCeason** [comment]
Gain a lot.

[Time zones](https://en.wikipedia.org/wiki/Time_zone) in ISO 8601 are represented as local time (with the location unspecified), as [UTC](https://en.wikipedia.org/wiki/UTC), or as an offset from UTC.

Date: The standard uses the [Gregorian calendar](https://en.wikipedia.org/wiki/Gregorian_calendar), which "serves as an international standard for civil use.

That's different.
