### ISSUE TITLE
MySQL Handler ignore :SHOW COLLATION

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#5853]
**Summary**
```
MySQL [(none)]> SHOW COLLATION;
ERROR 1105 (HY000): Code: 1005, displayText = sql parser error: Expected show statement, found: COLLATION.
```
Please ignore it.

**Comment by BohuTANG** [comment]
This is a federated query, we can refer and return None instead of error.

https://github.com/datafuselabs/databend/issues/5851 This issue can be implemented in one patch, make 'SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())' federated query always return ''
