### ISSUE TITLE
Feature: add doc about `join`

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#5854]
**Summary**

Now, we have supported some join types, how about adding them to our doc? cc @BohuTANG

**Comment by soyeric128** [comment]
Hi @xudong963 
Can you provide more information about this feature, such as which JOIN types we currently support? 
Thank you.

**Comment by soyeric128** [comment]
Hi @xudong963 
Thanks for the reply above. 
Could you pls review this PR https://github.com/datafuselabs/databend/pull/5957 for the doc update?
Thanks.
