### ISSUE TITLE
improve `show tables` performance.

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#5858]
improve `show tables` performance

![middle_img_v2_4db868f0-2665-4ba4-8905-1526f48ad43g](https://user-images.githubusercontent.com/1998569/172744099-2922e7e4-2715-4072-9289-439304693b52.jpg)

**Comment by lichuang** [comment]
> /assignme

we have found the reason why the performance is poor, and @ariesdevil is fixing this issue, thank you.

**Comment by dust1** [comment]
> > /assignme
> 
> we have found the reason why the performance is poor, and @ariesdevil is fixing this issue, thank you.

ok, I will look for other issues
