### ISSUE TITLE
Main branch test failed: 03_0003_select_group_by

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#5893]
Workflow: https://github.com/datafuselabs/databend/runs/6828139973?check_suite_focus=true

```
03_0003_select_group_by:                                                [ FAIL ] - result differs with:
--- /workspace/tests/suites/0_stateless/03_dml/03_0003_select_group_by.result	2022-06-10 09:10:14.764289559 +0000
+++ /workspace/tests/suites/0_stateless/03_dml/03_0003_select_group_by.stdout	2022-06-10 09:14:02.491482577 +0000
@@ -8,8 +8,6 @@
 0
 1
 2
-1	ahash
-1	ahash
 ==GROUP BY Strings==
 0	0	5
 0	4	5
```

**Comment by Xuanwo** [comment]
@zhyass, Can you take a look into?

**Comment by zhyass** [comment]
> @zhyass, Can you take a look into?

SELECT count(1), name FROM system.credits WHERE name='ahash' GROUP BY name;

**Comment by Xuanwo** [comment]
Happened again at https://github.com/datafuselabs/databend/runs/6854985882?check_suite_focus=true

**Comment by Xuanwo** [comment]
Should we disable the test case for now?

**Comment by leiysky** [comment]
> Happened again at https://github.com/datafuselabs/databend/runs/6854985882?check_suite_focus=true

I encountered this in https://github.com/datafuselabs/databend/runs/6855283254?check_suite_focus=true

**Comment by BohuTANG** [comment]
cc @sundy-li

**Comment by ZeaLoVe** [comment]
@zhyass What to do with this issue? The same SQL in logic test cause failed in a production workflow https://github.com/datafuselabs/databend/actions/runs/2491969620.

**Comment by sundy-li** [comment]
This bug may be related to `cargo_metadata`, but I do not know the reason.

I think we can disable this in logictests.

**Comment by Xuanwo** [comment]
Let's close this issue.
