### ISSUE TITLE
Decorrelate `EXISTS` subqueries

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5913]

**Comment by AngleNet** [comment]
@leiysky  HI, are you working on this issue? If not, I would like to take it. Thank you!

**Comment by leiysky** [comment]
> @leiysky  HI, are you working on this issue? If not, I would like to take it. Thank you!

Sorry, I have been working on this.

This is an urgent task, I'm afraid that I have to finish it by myself.

**Comment by AngleNet** [comment]
I would like to work on the optimizer  stuff. Is there any issue I could work on? @leiysky

**Comment by leiysky** [comment]
> I would like to work on the optimizer stuff. Is there any issue I could work on? @leiysky

https://github.com/datafuselabs/databend/issues/6017 There is a issue about column pruning, maybe you can take a look at it?

**Comment by AngleNet** [comment]
Great! I will try this out.
