### ISSUE TITLE
Blog update time

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5917]
**Summary**

https://databend.rs/blog/

![image](https://user-images.githubusercontent.com/172204/173229329-0989d0b0-5e67-4d28-9e4c-b27eac0b825d.png)

**Comment by BohuTANG** [comment]
It seems we should add a `date` to the blog markdown. @Xuanwo

**Comment by BohuTANG** [comment]
On my local test with `yarn start`, it works well, this is strange:
![image](https://user-images.githubusercontent.com/172204/173230227-445bfe07-59b3-4c2a-b338-51b7548dce11.png)

**Comment by Xuanwo** [comment]
Maybe specify the slug will break docusaurus auto-post date extraction feature.

Specifying the date in the front matter will be more reliable.
