### ISSUE TITLE
Add session settings to documention

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5927]
**Summary**

```
show settings;
```

![image](https://user-images.githubusercontent.com/172204/173267751-a4f50987-421c-4ac7-a084-df8296342a27.png)

Need a new `Setting Commands` to document get/set/description session settings.

**Comment by soyeric128** [comment]
Hi @BohuTANG 
Could you pls provide an example of running "show settings;" that I can add to the document?
Thanks.

**Comment by BohuTANG** [comment]
It's easy to do that, deploy a databend-query with local fs, and run the 'show setting s'.

**Comment by PsiACE** [comment]
https://databend.rs/doc/reference/sql/setting-commands
