### ISSUE TITLE
select-clause add  at

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#5941]
**Summary**
https://databend.rs/doc/reference/sql/query-syntax/dml-select#select-clause

select * from tb at(snapshot=>'snapshort_id');

**Comment by wubx** [comment]
https://databend.rs/doc/reference/sql/query-syntax/dml-at

**Comment by soyeric128** [comment]
hi @wubx 
Pls review this PR: https://github.com/datafuselabs/databend/pull/6293
