### ISSUE TITLE
Feature: Support `CASE ... WHEN` expression

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#5951]
`CASE` expression is a conditional expression with multiple branches.

You can specify branches with `WHEN ... THEN ...` subexpressions, and end the `CASE` expression with `END`.

Besides, you can define a default branch with `ELSE`, otherwise the default value is `NULL`.

For example:
```sql
select case cond when 1 then 1 when 2 then 2 end;
```

cc @BohuTANG @sundy-li

**Comment by sundy-li** [comment]
could be routed to a new function `multi_if`.

**Comment by leiysky** [comment]
> could be routed to a new function `multi_if`.

Yes, I recall that ClickHouse implemented case in this way.
