### ISSUE TITLE
Feature: Support to show tenant quota in management mode admin api

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#5967]
**Summary**
Current we support to run call procedure like
```sql
call stats$tenant_tables(<tenant_id string array>)
```
to show current tenants' stats such as total number of tables.
Those apis could be wrapped into management mode admin api
with uri like
/v1/quota/<tenant_id>
to probe on tenant stats info.
It could have several benefits:
1. get avoid of session leakage
2. cache tenant , database and other tenant level quotas to reduce meta layer visit frequency

**Comment by flaneur2020** [comment]
how about just a `/v1/tenant/<tenant_id>` to represent some metadata about the tenant? it may includes some info about quota, current tables count, etc

**Comment by ZhiHanZ** [comment]
> how about just a `/v1/tenant/<tenant_id>` to represent some metadata about the tenant? it may includes some info about quota, current tables count, etc

LGTM, I think we could also support POST approach for batch tenant array processing and get avoid of a lot of short lived connections

**Comment by flaneur2020** [comment]
I think short lived connections are ok, especially for the low rate requests. short-lived connections is much easier to program, and eaiser to load balance.

however, we'd take care about conntrack: if one enabled conntrack in iptables, some short-lived connections could drain the conntrack records, thus the node would suffers lost packet if the conntrack got full.
