### ISSUE TITLE
Using Databend as a Sink for Vector got an error

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#5975]
**Summary**
I use databend as a sink for vector according [this doc](https://databend.rs/doc/learn/analyze-nginx-logs-with-databend-and-vector), but got an error as following:

```
2022-06-14T08:09:11.389765Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 404 Not Found component_kind="sink" component_type="clickhouse" component_id=nginx_access_log_to_databend component_name=nginx_access_log_to_databend
^C2022-06-14T08:09:25.772967Z  INFO vector: Vector has stopped.
```

![s00nMrBw98](https://user-images.githubusercontent.com/7600925/173555561-12a941de-3cb7-42c6-b066-be4f2cb193a3.png)

Although it does not affect the result of data import, it certainly affects the user experience.

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/7600925/173556187-4ad82a66-8156-4741-9972-cee18d888052.png">

**Comment by hantmac** [comment]
According this disscussion https://github.com/vectordotdev/vector/discussions/13136, the maintainer of vector said the healthcheck endpoint of Clickhouse isn't working. Do we have health check endpoint of Clickhouse?

**Comment by youngsofun** [comment]
@hantmac I will fix it tomorrow

**Comment by youngsofun** [comment]
@hantmac  you can try the newest main
https://github.com/vectordotdev/vector/blob/master/src/sinks/clickhouse.rs#L175

I guess it is fixed by @sundy-li  yesterday  in https://github.com/datafuselabs/databend/pull/5933

**Comment by youngsofun** [comment]
@hantmac is this fixed?

**Comment by hantmac** [comment]
> @hantmac is this fixed?

Sorry, I will test it today. BTW, is there released binary package that I can use to test? Or I use source code directly ?

**Comment by hantmac** [comment]
@youngsofun I use the latest `databend-query` and  the latest `vector`, still has the problem. 🤔
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/7600925/174008825-1bb77d98-6559-404f-9673-9b267856dadb.png">
