### ISSUE TITLE
[test-infra] FuseBots

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#601]
**Summary**

If you have any needs for [FuseBots](https://github.com/datafuselabs/fusebots) in the development of Datafuse, please comments

FuseBots fetaures:
1. Auto Label, [example](https://github.com/datafuselabs/datafuse/pulls?q=is%3Apr+is%3Aopen+label%3Apr-feature)
2. Auto Nightly release, [example](https://github.com/datafuselabs/datafuse/releases)
3. Auto Merge, [example](https://github.com/datafuselabs/datafuse/pull/636#issuecomment-849408422)
4. Assign to me, [example](https://github.com/datafuselabs/datafuse/issues/663#issuecomment-851260591)
5. PullRequest context(CLA, Changelog) check

**Comment by drmingdrmer** [comment]
Separate issue and discussion: 

- Issue: progress-related information: An issue drives development, otherwise it should be a discussion.
  E.g., unexpected behavior, feature request, etc.

- Discussion: non progress-related information:
  E.g. asking questions, sharing a use case, etc.

https://docs.github.com/en/discussions/quickstart

**Comment by sundy-li** [comment]
Auto cherry-pick pr to the latest version.

**Comment by BohuTANG** [comment]
> Auto cherry-pick pr to the latest version.

Bots will support backport for `beta` branch from the nightly with `pr-bugfix` label.

**Comment by BohuTANG** [comment]
Auto merge after the assignees approved and all the CI passed

**Comment by BohuTANG** [comment]
> Auto merge after the assignees approved and all the CI passed

Done

**Comment by sundy-li** [comment]
When someone comment  `/assign` in some issues which is not assigned,  bot should assign the issue to that person.

**Comment by BohuTANG** [comment]
> When someone comments `/assign` in the issue which is not assigned, bot should assign the issue to that person.

`/assignme` done

**Comment by BohuTANG** [comment]
Robot:
Support github check runner for performance comparion between latest and the PRs.

**Comment by BohuTANG** [comment]
Robot:
Add welcome greeting for the first contributor.

**Comment by zhang2014** [comment]
Add new pr type:  `Not for changelog (changelog entry is not required)`

When used this type, the PullRequest not included in the ChangeLog.

for example: https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by BohuTANG** [comment]
> Add new pr type: `Not for changelog (changelog entry is not required)`
> 
> When used this type, the PullRequest not included in the ChangeLog.
> 
> for example: https://github.com/ClickHouse/ClickHouse/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Done.

**Comment by BohuTANG** [comment]
Bot:
Add reviewer hints.

FuseQuery: @BohuTANG @sundy-li @zhang2014 
FuseStore: @drmingdrmer @dantengsky

**Comment by BohuTANG** [comment]
Add roadmap as greeting https://github.com/datafuselabs/datafuse/issues/749

**Comment by PsiACE** [comment]
Add reviewers to the PR, and automatically @ other appropriate reviewers.

Just like `rust-highfive` did

```
r? @matthewjasper

(rust-highfive has picked a reviewer for you, use r? to override)
```

**Comment by BohuTANG** [comment]
> Add reviewers to the PR, and automatically @ other appropriate reviewers.
> 
> Just like `rust-highfive` did
> 
> ```
> r? @matthewjasper
> 
> (rust-highfive has picked a reviewer for you, use r? to override)
> ```

FuseBot Works

**Comment by drmingdrmer** [comment]
r?

**Comment by PsiACE** [comment]
> FuseBot Works

Love it.

**Comment by drmingdrmer** [comment]
> Love it.

She loves you too.
