### ISSUE TITLE
date_sub function

### ISSUE THREAD

**Issue by finalkira000** [datafuselabs/databend#6014]
**Summary**

Some benchmark tool using date_sub, but datebend does not support it now, version  v0.7.85.

**Comment by BohuTANG** [comment]
Hi,
databend already supports date_add, but it will work when the new planner is finished.

```
-- set enable_planner_v2=1;
-- select date_add(to_date(18321), 1, YEAR);
-- select date_add(to_date(18321), -1, YEAR); -- likes date_sub
-- select date_add(to_date(18321), 1, SECOND);
```

**Comment by finalkira000** [comment]
look forward to GA ASAP
