### ISSUE TITLE
Implement column pruning optimization

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6017]
After finishing all the rewrite optimization, we can perform a column pruning to eliminate the unused columns in `LogicalGet`s and `EvalScalar`s.

For example, a query:
```sql
mysql> create table t(a int, b int, c int);
Query OK, 0 rows affected (0.03 sec)
Read 0 rows, 0.00 B in 0.005 sec., 0 rows/sec., 0.00 B/sec.

mysql> explain select a from t;
+-----------------------------+
| explain                     |
+-----------------------------+
| Project: [a]                |
|     Scan: default.default.t |
+-----------------------------+
2 rows in set (0.03 sec)
Read 0 rows, 0.00 B in 0.001 sec., 0 rows/sec., 0.00 B/sec.
```

Since we only need the column `a`, while we still need to fetch `b` and `c` from our columnar storage by default. With the optimization, we can reduce I/O cost by only fetching the needed column.

Another case:
```sql
mysql> explain select a from (select a+1 as a, b+1 as b, c+1 as c from t);
+---------------------------------------------+
| explain                                     |
+---------------------------------------------+
| Project: [a,b,c]                            |
|     EvalScalar: [+(c, 1), +(b, 1), +(a, 1)] |
|         Scan: default.default.t             |
+---------------------------------------------+
3 rows in set (0.04 sec)
Read 0 rows, 0.00 B in 0.001 sec., 0 rows/sec., 0.00 B/sec.
```

The projections can be eliminated to reduce the computation cost. This is very useful if we have redundant aggregate functions.

**Comment by AngleNet** [comment]
Sorry for the late update. I'm still working on it. Hope this issue is not very urgent. I will try my best to provide a draft implementation in this weekend. :)

**Comment by leiysky** [comment]
> Sorry for the late update. I'm still working on it. Hope this issue is not very urgent. I will try my best to provide a draft implementation in this weekend. :)

This is not that urgent, please make yourself comfortable.

I've just added a phase `post_optimize`, which is a good place to put the column pruning optimization into it.
https://github.com/datafuselabs/databend/blob/d6c8161f22e3a5da88314712ad93d18d5b906ebc/query/src/sql/optimizer/heuristic/mod.rs#L77-L79

**Comment by AngleNet** [comment]
@leiysky HI. I have a problem while writing tests for it. It seems that code under `sql/optimizer/heuristic` just generates `testdata/*.test`. I have no idea how the `*.test* are executed and compared along expected query plans. Could you clear this for me ?

**Comment by AngleNet** [comment]
@xudong963 HI. I have no idea how the test framework for optimizer works. Would you help me with this?

**Comment by leiysky** [comment]
> @leiysky HI. I have a little problem. Why there is an EvalScalar plan? How is it created, optimized and evaluated? Could you help me with this?

In databend, `EvalScalar` is used to insert a new column into a set of columns(i.e. a `relation`). And we will use `Project` to remove columns from a set of columns.

For example, consider the query:
```sql
create table t(a int, b int);

select a, a+1 as c from t;
```

The query will pass through column `a` from table `t` and evaluate an expression `a+1` with alias `c`. So the plan is essentially:
```
Project: a, c
    EvalScalar: a+1 -> c
        Get: t[a, b]
```

A simplified explaination is:
- If you want to add columns into a set, you should use `EvalScalar` or `Join`
- If you want to remove columns in a set, you should use `Project`

By the way, in databend we will use `EvalScalar` to implement `Aggregate`. Before a `Aggregate`, we will evaluate the group by items and arguments of aggregate functions first, and reference them inside `Aggregate` operator. For example:
```sql
create table t(a int);
select sum(a + 1) from t group by a - 1;
```
The plan would be:
```
Project: sum(a+1)
    Aggregate: group keys: [a - 1], aggregate functions: [sum(a + 1)]
        EvalScalar: [a-1, a+1]
            Get: t[a]
```

**Comment by AngleNet** [comment]
Got it! Thank you for the detailed explanation.
