### ISSUE TITLE
Feature: dev setup for hdfs storage 

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#6018]
**Summary**

To enable the access of  [hdfs storage ](https://opendal.databend.rs/services/hdfs.html) in CI, such as the ongoing PR:

- https://github.com/datafuselabs/databend/pull/5895

Some tweaks should be made to our [`dev_setup.sh`](https://github.com/datafuselabs/databend/blob/main/scripts/setup/dev_setup.sh)

--------------

Basically, the following CI setup of opendal hdfs storage should be adopted:

https://github.com/datafuselabs/opendal/blob/d8aa1265313aad3280ec09ae9babfe9b74c64d04/.github/workflows/service_test_hdfs.yml#L24-L32

~~~
      - name: Checkout java env
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
      - name: Setup-hdfs env
        uses: beyondstorage/setup-hdfs@master
        with:
          hdfs-version: ${{ matrix.hdfs-version }}
~~~

That is 

- install JDK (not JRE)
  - export `JAVA_HOME`
- grab the hdfs jars

---------------

**Seems PR https://github.com/datafuselabs/databend/pull/5895 could be built without the following step, but we definitely need it in the upcoming phases.**

- [ ] setup JDK

  - Install JDK(not JRE) 

    https://github.com/datafuselabs/databend/blob/7de80ae8677302acbf4d5066698bb3ee4e8a0959/scripts/setup/dev_setup.sh#L201

    should be changed to `install_pkg openjdk-11-jdk-headless "$PACKAGE_MANAGER" `

  - Add "JAVA_HOME" to profile

    maybe find the JAVA_HOME by something like `readlink`, and add JAVA_HOME to `~/.profile`
 
      reference: 
        https://github.com/datafuselabs/databend/blob/7de80ae8677302acbf4d5066698bb3ee4e8a0959/scripts/setup/dev_setup.sh#L26

- [ ] grab hdfs jars & export HADOOP_HOME
     
  - grabs jars of hadoop (version 2.10.1)
  
  the github action used in opendal, for reference   https://github.com/beyondstorage/setup-hdfs
  
  - export HADOOP_HOME

**Comment by Xuanwo** [comment]
> * @Xuanwo   do we need to export other env vars, like `CLASS_PATH`

No, we don't need to. hdrs will handle `CLASS_PATH` correctly, we only need to set `HADOOP_HOME` which is the path to hadoop installation.

> where should we put the jars? Or shall we set up some env vars to indicate the location of those jars?

We can push them anywhere, for example: `/usr/lib/hadoop-2.7.3/share/hadoop`.

Yes, we can than indicate the location of hadoop by `HADOOP_HOME`.

**Comment by dantengsky** [comment]
clean staled issues.
