### ISSUE TITLE
Does datebend support delete and update?

### ISSUE THREAD

**Issue by finalkira000** [datafuselabs/databend#6019]
**Summary**
datebend不支持 delete和update数据吗，版本为 v0.7.85

mysql> select * from t2;
+------+------+
| id   | col2 |
+------+------+
|    2 | col1 |
|    3 | col2 |
+------+------+

mysql> delete from t2 where id = 2;
ERROR 1105 (HY000): Code: 1005, displayText = sql parser error: Expected an SQL statement, found: delete.
mysql> update t2 set col2 = 'col2' where id =2;
ERROR 1105 (HY000): Code: 1005, displayText = sql parser error: Expected an SQL statement, found: update.

**Comment by BohuTANG** [comment]
Now both is supports.
