### ISSUE TITLE
performance: Improve COPY INTO speed

### ISSUE THREAD

**Issue by junnplus** [datafuselabs/databend#6020]
**Summary**

It takes a long time (> 1.5h) to import successfully when copying a 60GB+ file into a table, even if we use a very large instance (**20C40G**).

![image](https://user-images.githubusercontent.com/8097526/174010259-d2f5a974-30c1-468e-b4af-e1333b95fd51.png)

From the graph, the resources of the multi-cores are not utilized.

**Comment by flaneur2020** [comment]
the 1 in the CPU graph do not means 1% but means 100% (one core, it'd be 2000% if 20 cores get utilized)

**Comment by BohuTANG** [comment]
The file is on s3? We should a metric to measure how the network cost when we read it from the s3, cc @Xuanwo

**Comment by Xuanwo** [comment]
I will work on this.

**Comment by BohuTANG** [comment]
Hi,

I have a test on EC2 Arm 32C64G with v0.7.92-nightly:
```
```
COPY INTO ontime FROM 's3://databendcloud/ontime/' pattern = 'ontime_.*csv'
file_format = (TYPE = "CSV" field_delimiter = '\t' record_delimiter = '\n'
skip_header = 1);      

Read 202687555 rows, 137.02 GiB in 390.001 sec., 519.71 thousand rows/sec., 359.75 MiB/sec. 
```

Guess your test is something wrong with the network?

**Comment by junnplus** [comment]
> I have a test on EC2 Arm 32C64G with v0.7.92-nightly

Is this an import of a single large file or multiple small files?

**Comment by Xuanwo** [comment]
This issue has been addressed.
