### ISSUE TITLE
bug: order by column not support using column number

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6022]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.88-nightly 

### What's Wrong?

![9Rb0hEej3z](https://user-images.githubusercontent.com/10904090/174014888-527b916b-05cf-487b-9bd7-b3fd26146741.jpg)

![h4taHi6fo0](https://user-images.githubusercontent.com/10904090/174014918-4eb8d53d-bd41-4491-b9c3-599f6bae2927.jpg)

SQL ... order by 1 desc  with unexpected results.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Cc @leiysky may new planner support it?

**Comment by leiysky** [comment]
> Cc @leiysky may new planner support it?

We have supported group by index, but haven't support order by index. I will open a issue for this.

**Comment by sundy-li** [comment]
Fixed in #6028
