### ISSUE TITLE
Occasionally errors occur when using "COPY INTO" to import files.

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#6035]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.88-nightly

### What's Wrong?

invalid character '<' looking for beginning of value, stats: <nil> 

### How to Reproduce?

```sql
COPY INTO ontime FROM 's3://<bucket>/m_ontime/' credentials=(aws_key_id='AWS_KEY_ID' aws_secret_key='AWS_SECRET_KEY') pattern ='.*[.]csv' file_format=(type='CSV' field_delimiter='\t' record_delimiter='\n' skip_header=1);
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PsiACE** [comment]
Initial consideration may be that a network problem was encountered during the S3 request.
1. Can a mechanism be provided for retries? COPY INTO is a query that can take a long time to execute, and it would be a bad experience to abort because of a single jitter.
2. whether there is a way to provide more efficient error info to help troubleshoot.

**Comment by Xuanwo** [comment]
Has been addressed.
