### ISSUE TITLE
Implement `IS [NOT] DISTINCT FROM` operator

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6046]
`IS [NOT] DISTINCT FROM` operator is used to compare two expression with awareness of nullability.

For example, the result of `1 IS DISTINCT FROM NULL` is `true` and the result of `1 IS NOT DISTINCT FROM NULL` is `false`, in contrast the result of both `1 <> NULL` and `1 = NULL` is a special falsy value because `NULL` is a unknown value in SQL standard.

The table of value with `IS DISTINCT FROM`:

|lhs IS DISTINCT FROM rhs|1|2|NULL|
|---|--|--|--|
|1|FALSE|TRUE|TRUE|
|2|TRUE|FALSE|TRUE|
|NULL|TRUE|TRUE|FALSE|

The table of value with `IS NOT DISTINCT FROM`:

|lhs IS NOT DISTINCT FROM rhs|1|2|NULL|
|---|--|--|--|
|1|TRUE|FALSE|FALSE|
|2|FALSE|TRUE|FALSE|
|NULL|FALSE|FALSE|TRUE|

**Comment by JialuGong** [comment]
Hi @leiysky,  Sorry that I've got a problem. I'd like to know how `static_cast` casts a `Null` value .
https://github.com/datafuselabs/databend/blob/15ba3b0a2a8852e53bc781a2157c0a6990ec6631/common/datavalues/src/columns/series.rs#L39-L44
Cause I noticed that `ComparisonFunction` compares values if they are null, I wonder if I could use `ComparisonFunction`  to implement `IS [NOT] DISTINCT FROM` operator by not wrapping the comparison result as `NullableColumn`?

**Comment by leiysky** [comment]
@JialuGong You can take a look at https://github.com/datafuselabs/databend/blob/main/common/datavalues/src/columns/null/mod.rs .

> Cause I noticed that `ComparisonFunction` compares values if they are null, I wonder if I could use `ComparisonFunction` to implement `IS [NOT] DISTINCT FROM` operator by not wrapping the comparison result as `NullableColumn`?

It's a good idea, but you can not really reuse the logic of `ComparisonFunction`. 

In databend, a `FunctionAdapter` is responsible to dispatch functions according to the `FunctionFeatures`. 

If a function is not **null-aware**(which returns null if any of the arguments is null), it will set its `FunctionFeatures::passthrough_null` to true. Then `FunctionAdapter` will unwrap the nullable arguments and wrap the result with null bitmap of those arguments.

In this case, `IS [NOT] DISTINCT FROM` is a null-aware function(the `passthrough_null` of which is false), while `ComparisonFunction` is not null-aware. I guess you have to implement a new function from scratch.

@sundy-li Do you have any suggestion?

**Comment by sundy-li** [comment]
What @leiysky  is right,  but the `ComparisionFunction` is very complex to modify.

Since `IS [NOT] DISTINCT FROM` is not used widely, I would like to go an easier way to implement it.
We can transform :

1.  `IS DISTINCT FROM` to `multi_if( is_null(lhs)  and is_null(rhs), false,    is_null(lhs)  or is_null(rhs), true,  lhs == rhs  )`
2. `IS DISTINCT FROM` to `Not(IS DISTINCT FROM)`

**Comment by JialuGong** [comment]
@sundy-li @leiysky Sorry for my late reply, cause I am too busy yesterday.

I used to add a new function feature `NotReturnNull` which means the `FunctionAdapter` should remove `Nullable` for nullable args and NOT wrap the result as `NullableColumn` and add a judge in `ComparisonFunction` to change the `FunctionFeature`. Although the result of some tests seems correct, It polluted the `ComparisonFunction` and made it no longer elegant.

And I initially implemented the operator by transforming the expr in type_checker and I am writing some tests for it. Thanks for your  patiently reply and suggestions which help me a lot : )

**Comment by sundy-li** [comment]
> NotReturnNull which means the FunctionAdapter should remove Nullable for nullable args

There is `assume_not_null` function now.
