### ISSUE TITLE
Bug: logictest sometimes encounter session variable invalidation

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6054]
https://github.com/datafuselabs/databend/runs/6947886711?check_suite_focus=true

The test case will pass in stateless test.

cc @ZeaLoVe

**Comment by ZeaLoVe** [comment]
![ObKxWtGUmO](https://user-images.githubusercontent.com/10904090/174513011-fee7478f-18e8-42f7-96c6-473ee052da3a.jpg)

![BwftynYm3T](https://user-images.githubusercontent.com/10904090/174513019-9e7572d0-c93d-45de-aef9-3447356efd9a.jpg)

Failed in http handler, it does not cause by session variable, more like the bug #5973

**Comment by leiysky** [comment]
A reproduce:
```
statement ok
set enable_planner_v2 = 1;

statement query T
select 'Hello, world!';

----
Hello, world!

statement query ok
select * from numbers(10) as t where exists (select * from numbers(3) as t1 where t.number = t1.number);

----
0
1


```

**Comment by ZeaLoVe** [comment]
cc @youngsofun  produce in latest build v0.7.92-nightly, do not appear in previous versions.

**Comment by youngsofun** [comment]
@ZeaLoVe  this may be because http handler use v2 for diff scope with mysql handler
