### ISSUE TITLE
Test output of goldenfile is not readable

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6078]
We use `goldenfile` for AST unit tests, but it will output the whole content of goldenfile while the test failed. This behavior makes it hard for debugging.

As we already print the diff, maybe we can omit the output of goldenfile's content?

![image](https://user-images.githubusercontent.com/5351546/174573651-5cca7ee4-7569-4a7f-ad58-39008172dd8c.png)

Take `test_statement` as an example, we have to `PgUp` several times to know what happened.

@andylokandy @leiysky

**Comment by Xuanwo** [comment]
Maybe we can input a `Differ` which doesn't print any content.

**Comment by andylokandy** [comment]
The assertion output is from an indirect dependent crate [`difference](https://github.com/johannhof/difference.rs/blob/54bdfa25092ebc2a1b3d86e640cf517e7dcdcb96/src/lib.rs#L167-L172). I don't have any idea to hide it without forking the `goldenfile` crate.

**Comment by PsiACE** [comment]
i think https://crates.io/crates/similar is a good choice for diff
