### ISSUE TITLE
Feature: Support projection on  [database].[table].[field]

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#6080]
**Summary**
scan from [database].[table].[field] is used for several third party integrations such as in metabase data browse
Currently we only support [table[.[field[ during scan which could be improved

example:
DDL
```sql
create table testdb(i int, j int);
insert into testdb VALUES(1,2);
```

SQL
```sql
select default.testdb.i, default.testdb.j from default.testdb;
ERROR 1105 (HY000): Code: 1058, displayText = Unknown column default.testdb.i.
```
works in table.field area
```sql
mysql> select testdb.i, testdb.j from default.testdb
    -> ;
+------+------+
| i    | j    |
+------+------+
|    1 |    2 |
+------+------+
1 row in set (0.43 sec)
Read 1 rows, 8.00 B in 0.051 sec., 19.59 rows/sec., 156.71 B/sec.
```

**Comment by leiysky** [comment]
I'll work on it, maybe we only need to support it in new planner? @BohuTANG

**Comment by BohuTANG** [comment]
There is a concern, we use `[catalog].[database].[table]`, for example:
```
select * from hive.default.t_1;
```
https://github.com/datafuselabs/databend/blob/main/tests/suites/2_stateful_hive/00_basics/00_0000_hms_basics.sql

cc  @dantengsky

**Comment by flaneur2020** [comment]
`scan from [database].[table].[field]` -> `projection on [database].[table].[field]` ?

this issue occurs on selecting fields with `[database].[table]` prefix, not really a scan on `database.table.field` i guess.

**Comment by TCeason** [comment]
#6192  Maybe this issue can also link to here.
