### ISSUE TITLE
databend-meta adds cli command to send RPC to a running meta cluster

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#6084]
E.g.:
```shell
databend-meta --grpc-api-address 1.2.7.1:8888 --cmd kvapi::upsert --key foo --value bar
# <result in json>

databend-meta --grpc-api-address 1.2.7.1:8888 --cmd kvapi::get --key foo

databend-meta --grpc-api-address 1.2.7.1:8888 --cmd kvapi::mget --key foo bar wow

databend-meta --grpc-api-address 1.2.7.1:8888 --cmd kvapi::list --prefix foo/
```

**Comment by ZhiHanZ** [comment]
I think we could also support export command and remove metactl?

**Comment by RinChanNOWWW** [comment]
I think I can take this issue.  /assignme

**Comment by RinChanNOWWW** [comment]
@databend-bot /assignme

**Comment by drmingdrmer** [comment]
> Should we return the whole reponse same as the original struct (including seq, meta etc.) ?
> 
> For example:
> 
> ```
> databend-meta --grpc-api-address 127.0.0.1:9101 --cmd kvapi::upsert --key k1 --value v1
> databend-meta --grpc-api-address 127.0.0.1:9101 --cmd kvapi::get --key k1
> ```
> 
> The second command will return:
> 
> ```json
> {
>   "seq": 1,
>   "meta": null,
>   "data": [
>     118,
>     49
>   ]
> }
> ```

The complete JSON result looks good to me.:)


> Another question is, should we convert `data: Vec<u8>` into `String` for better readablity? But I'm wondering if the data could be unreadable.

The data is likely to be a `protobuf` serialized data. Most of them can not be converted to string.

> Please make a more detail description about the commands and their results.

What's your suggestion on this?

**Comment by RinChanNOWWW** [comment]
I think it's ok.
