### ISSUE TITLE
Optimize disjunctive predicates

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6096]
The disjunction connective `OR` is an important part of query optimization. Different from conjunction connective `AND`, the rule of `OR` is much more complicated.

The basic theorems we have:

$$
\begin{equation}
    \sigma_{p_1 \lor p_2} (R) = \sigma_{p_1} (R) \cup \sigma_{p_2}(R)
\end{equation}
$$

With this we can transform a query:
```sql
select * from t where a = 1 or a = 2;
```
into:
```sql
select * from t where a = 1 union select * from t where a = 2;
```

However this transformation is always less efficient, which is rarely used in databases.

We can take tpch Q19 as a target:
```sql
select
	sum(l_extendedprice* (1 - l_discount)) as revenue
from
	lineitem,
	part
where
	(
		p_partkey = l_partkey
		and p_brand = 'Brand#12'
		and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
		and l_quantity >= 1 and l_quantity <= 1 + 10
		and p_size between 1 and 5
		and l_shipmode in ('AIR', 'AIR REG')
		and l_shipinstruct = 'DELIVER IN PERSON'
	)
	or
	(
		p_partkey = l_partkey
		and p_brand = 'Brand#23'
		and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
		and l_quantity >= 10 and l_quantity <= 10 + 10
		and p_size between 1 and 10
		and l_shipmode in ('AIR', 'AIR REG')
		and l_shipinstruct = 'DELIVER IN PERSON'
	)
	or
	(
		p_partkey = l_partkey
		and p_brand = 'Brand#34'
		and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
		and l_quantity >= 20 and l_quantity <= 20 + 10
		and p_size between 1 and 15
		and l_shipmode in ('AIR', 'AIR REG')
		and l_shipinstruct = 'DELIVER IN PERSON'
	);


```

**Comment by xudong963** [comment]
> However this transformation is always less efficient, which is rarely used in databases.

Seems we can first convert to union all, and then optimize each branch of union all?

**Comment by leiysky** [comment]
> > However this transformation is always less efficient, which is rarely used in databases.
> 
> Seems we can first convert to union all, and then optimize each branch of union all?

Unless you can share the scanning or leverage with a secondary index, it's always inefficient. We'd better find out if we can extract the common predicate and push it down for this case.

**Comment by xudong963** [comment]
> > > However this transformation is always less efficient, which is rarely used in databases.
> > 
> > 
> > Seems we can first convert to union all, and then optimize each branch of union all?
> 
> Unless you can share the scanning or leverage with a secondary index, it's always inefficient. We'd better find out if we can extract the common predicate and push it down for this case.

Ok, will try to extract common items
