### ISSUE TITLE
website menu seems empty

### ISSUE THREAD

**Issue by Sepush** [datafuselabs/databend#610]
**Describe the bug**
The menu on your website seems empty. I'm not sure it's a bug or still developing

**How to reproduce**
* open your website https://datafuse.rs/ 
* click MenuIcon you will find the menu in the drawer is empty

**Comment by BohuTANG** [comment]
It seems a bit, all the datafuse.rs source is in  https://github.com/datafuselabs/datafuse/tree/master/website/datafuse and the build action:
https://github.com/datafuselabs/datafuse/blob/master/.github/workflows/github-pages.yml

**Comment by BohuTANG** [comment]
![image](https://user-images.githubusercontent.com/172204/119429715-fcfe9a00-bd41-11eb-8ef1-a4484f7ea32b.png)

Hello Sepush,
Can you tell it in detail what the problem is?

**Comment by Sepush** [comment]
![image](https://user-images.githubusercontent.com/39197136/119459247-174f6c80-bd70-11eb-828b-aaf249096df5.png)
Just like this

**Comment by Sepush** [comment]
It's empty on the home page on my computer. but on the other pages, the menu is OK.
I use the latest version of Chrome.
I change to Firefox Developer Edition for testing met the same problem.
Maybe some edge case goes wrong.
Finally, I  turn to Edge browser there is another style, maybe a future, not a bug on Edge 
![image](https://user-images.githubusercontent.com/39197136/119461821-abbace80-bd72-11eb-8d01-af947efb198d.png)

**Comment by BohuTANG** [comment]
Thanks for the information.
The menu is ok on my Chrome(Version 90.0.4430.93 (Official Build) (64-bit)).
Guess it's a CSS adaptation problem, but not sure where caused the probelm.

**Comment by BohuTANG** [comment]
Some browser has this issue, like edge

**Comment by Xuanwo** [comment]
We have adopted new website frameworks, please feel free to submit new issues if the same problem occurs.
