### ISSUE TITLE
> * is the above categorization strategy reasonable? shall we take `PermissionDenied` as permanent error as well?

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6115]
> * is the above categorization strategy reasonable? shall we take `PermissionDenied` as permanent error as well?

Not looks good to me, opendal will convert all retryable errors (500, 502, 503, ...) to [`Interrupted`](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.Interrupted).

Take s3 as an example: https://github.com/datafuselabs/opendal/blob/main/src/services/s3/backend.rs#L1218-L1229

I think we can convert errors while `hyper send request` to `Interrupted` too so that we can retry at the `opendal` level.

> * will crate `backon` be better? seems it does not support [retry_notify](https://docs.rs/backoff/latest/backoff/fn.retry_notify.html) style API yet, which imo, is very helpful for diagnosis

I'm willing to add this API if databend is needed!

---

By the way, it's OK to get this PR merged first as it can address part of the problems. We can improve this part in the future.

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6085#issuecomment-1161702272_

**Comment by dantengsky** [comment]
Duplicated with issue 
- #6119
