### ISSUE TITLE
take `Interrupted` as transient error for transient IO fault handling

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#6119]
> * is the above categorization strategy reasonable? shall we take `PermissionDenied` as permanent error as well?

Not looks good to me, opendal will convert all retryable errors (500, 502, 503, ...) to [`Interrupted`](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.Interrupted).

Take s3 as an example: https://github.com/datafuselabs/opendal/blob/main/src/services/s3/backend.rs#L1218-L1229

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6085#issuecomment-1161702272_

**Comment by Xuanwo** [comment]
Yep, we have enabled this feature in https://github.com/datafuselabs/databend/blob/main/query/src/sessions/session_mgr.rs#L389

**Comment by dantengsky** [comment]
> Yep, we have enabled this feature in https://github.com/datafuselabs/databend/blob/main/query/src/sessions/session_mgr.rs#L389

Closing this issue since [Interrupted](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.Interrupted) already handled by opendal.

please feel free to re-open it if there are other related flaws
