### ISSUE TITLE
improve the support for hive query

### ISSUE THREAD

**Issue by FANNG1** [datafuselabs/databend#6123]
we could run simple query to hive tables with https://github.com/datafuselabs/opendal/issues/154,  #4947,  #5895 , but this's not enough. here we list the works todo to track the progress.
P1：
- [x] support predict push down
- [x] support query multi rowgroups in one file. https://github.com/datafuselabs/databend/pull/7311
- [x] support list files from dirs under table location
- [x] support partitioned hive table  https://github.com/datafuselabs/databend/pull/6906
- [x] support more hive primite types besides int&string, such as float. https://github.com/datafuselabs/databend/pull/6629
- [x] support hive array 

P2：
- [x] split file to small partition unit    https://github.com/datafuselabs/databend/pull/7311
- [ ] support hive complex types, such as struct&map
- [x] https://github.com/datafuselabs/databend/issues/7354

P3：
- [ ] support metadata cache
- [ ] support more hive file formats, such as avro, orc, json
- [ ] https://github.com/Xuanwo/hdrs/issues/71

**Comment by Xuanwo** [comment]
There is ongoing work to support using RPC instead JNI to connect HDFS:

- hdrs (the rust native client we are using now): https://github.com/Xuanwo/hdrs/issues/71
- hdfs-rpc: https://github.com/Xuanwo/hdfs-rpc

**Comment by sandflee** [comment]
planing to do:  read partition table and  read more than one rowgroup
