### ISSUE TITLE
[Track] ClickHouse driver compatibility 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6127]
Task List:

-  [ ] ~~https://github.com/datafuselabs/databend/issues/6125~~
-  [x] https://github.com/datafuselabs/databend/issues/6126
-  [ ] ~~https://github.com/datafuselabs/databend/issues/6266~~
-  [x] https://github.com/datafuselabs/databend/issues/6313
-  [x] https://github.com/datafuselabs/databend/issues/6414
-  [x] #6449

**Comment by youngsofun** [comment]
add https://github.com/datafuselabs/databend/issues/6261

**Comment by youngsofun** [comment]
add https://github.com/datafuselabs/databend/issues/6313

**Comment by sundy-li** [comment]
add https://github.com/datafuselabs/databend/issues/6414
