### ISSUE TITLE
Feature: create table with column reference as defualt

### ISSUE THREAD

**Issue by fkuner** [datafuselabs/databend#6129]
**Summary**

```
mysql> set enable_planner_v2=1;
Query OK, 0 rows affected (0.02 sec)

mysql> create table d1(n String, a UInt8 not null, b Int16 default a + 3, c String default 'c');
ERROR 1105 (HY000): Code: 1065, displayText = error:
  --> SQL:1:61
  |
1 | create table d1(n String, a UInt8 not null, b Int16 default a + 3, c String default 'c')
  |                                                             ^ column doesn't exist

.
```

**Comment by fkuner** [comment]
cc @andylokandy

**Comment by leiysky** [comment]
IMO this features looks wierd, both MySQL and Postgres doesn't support this. Default value should be a deterministic constant value.

If we need to represent a column with expression, then we should use generated column or virtual column instead.

**Comment by fkuner** [comment]
Yes, I found this test case in out test. `09_0004_remote_insert_into_select.sql`

**Comment by leiysky** [comment]
> Yes, I found this test case in out test. `09_0004_remote_insert_into_select.sql`

I recall that we have implemented this in old planner, can we deprecate it in new planner? @BohuTANG @sundy-li

**Comment by sundy-li** [comment]
I don't know if it's a must-feature in databend since we want to be more compatible with ClickHouse.   I think this feature can currently be deprecated until we find it's really helpful to users.

**Comment by flaneur2020** [comment]
maybe we can talk about this feature again since this feature can be useful for users on IoT like #10410

**Comment by sundy-li** [comment]
ClickHouse users would like this feature from my experience.

Need:

1. Refactor Planner  binder to support this
2. Check column default expression dependency (avoid cycle)
3. Check dependency in DDL

**Comment by BohuTANG** [comment]
>ClickHouse users would like this feature from my experience.

Yes, they using ClickHouse and want to try Databend :)
