### ISSUE TITLE
BUG: `SQLCommon::short_sql` does not trim insert stmt as expected

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#6132]
**Summary**

`SQLCommon::short_sql` is expected to trim `insert SQL` to string, which length is at most 64.

but, it does not.

How to reproduce:

- execute a long insert sql
- select the query log from `system.query_log`
 e.g. `select * from system.query_log where query_text like "insert%"`

**Comment by BohuTANG** [comment]
Add a new `QueryConfig` for query_log name like `query_log_enabled` (default is true)?

**Comment by BohuTANG** [comment]
> Add a new `QueryConfig` for query_log name like `query_log_enabled` (default is true)?

It seems max_query_log_size=0 can do that.
