### ISSUE TITLE
Implement `Into<PoemError> for ErrorCode`

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6137]
Maybe it's better to implement `Into<PoemError> for ErrorCode`?

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/pull/5897#discussion_r903285481_

**Comment by Xuanwo** [comment]
HTTP Handlers require an explicit handle of error transform. Implementing `Into<PoemError> for ErrorCode` may make developers' lives easier.

**Comment by youngsofun** [comment]
1. need to determine the status code reasonably
2. (maybe) sometimes need more context info

**Comment by Xuanwo** [comment]
This issue is stale, and not many supporters. Let's close.
