### ISSUE TITLE
Doc: add cloud page to deploy

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6138]
**Summary**
![image](https://user-images.githubusercontent.com/172204/174949473-0b2ada93-3dc4-4edc-ab4f-7974fb95bfe3.png)

Add a new page to introduce the `Databend Cloud`

**Comment by soyeric128** [comment]
Hi @BohuTANG 
Can you provide input on this topic?

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/pull/6179
