### ISSUE TITLE
add a config "default_catalog"

### ISSUE THREAD

**Issue by FANNG1** [datafuselabs/databend#6155]
we use databend to query hive data only now,  the sql like 'select * from hive.$db.$table',  not convenient to end users. maybe we could add a config named 'default_catalog' with the default value 'default';  if we set it to "hive",  user could use 'select * from $db.$table' to query.

**Comment by BohuTANG** [comment]
It looks reasonable. What do you think? @dantengsky

**Comment by dantengsky** [comment]
Pretty idea, thanks @sandflee

There might be other work to do, to make the 'default_catalog' config mechanism **fully** functional (or at least pass the UT/IT)

Things that I can come up with right now
- there is no `system` db, or `information_schema` for catalog other than the current default catalog
- A special table `system.one` is used in some cases

https://github.com/datafuselabs/databend/blob/a3564f25841e0c8966a8c943380553dacdce253a/query/src/sql/planner/binder/table.rs#L66-L70


https://github.com/datafuselabs/databend/blob/90792e97219d4a19bea0b80431459118133a816e/query/src/sql/planner/binder/select.rs#L63-L64

- table functions are not registered in catalogs other than the default catalog

- Maybe we should extend the `use` stmt as well, 

  `use catalog catalog_name`

    https://docs.snowflake.com/en/sql-reference/sql/use.html#syntax  (note. SF uses the naming convention of DATABASE.SCHEMA.TABLE)
    
    
It is a pretty idea, let's give it a try

**Comment by sandflee** [comment]
CATALOG_DEFAULT is used widely in databend.  seems we should replcace it with current_catalog() expcept  for the special cases such as system db & system one.

**Comment by dantengsky** [comment]
> CATALOG_DEFAULT is used widely in databend. seems we should replcace it with current_catalog() expcept for the special cases such as system db & system one.

Agree :+1:

**Comment by dantengsky** [comment]
> Is there any problem if hive catalog doesn't have "system" and "information_schema"

For stmt like `select 1=1`, a pseudo table `system.one` seems to be used. Not 100% percent sure about this. 

Lack of "information_schema" for catalog hive, should have no side effects to query node, hope it will not bring troubles to the "business logics" either.

> this may depends on how we implment hive sql support , let's leave it, keep using the default table functions?

yeah, that is not a big problem : )
