### ISSUE TITLE
split databend-query to multiple crates

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#6180]
**Summary**

Now Databend-Query is a rather large crate and we had to waste a lot of time on compiling and linking.

It's time to split it up into a few relatively small crates.

Related  https://github.com/datafuselabs/databend/pull/4399

**Comment by Xuanwo** [comment]
It's very important to do this job in a progressive way. Otherwise, we can't finish it.

**Comment by Xuanwo** [comment]
#4399 is a good example: It starts three months ago and ends with numerous code conflicts...

**Comment by PsiACE** [comment]
> It's very important to do this job in a progressive way. Otherwise, we can't finish it.

Yes, we're having trouble finding a window to do it all at once, and I think it will probably be done in two or three rounds.

**Comment by sandflee** [comment]
code one minute, cargo check ten minutes :(
