### ISSUE TITLE
Feature: Add PRESIGN support

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6215]
- [Rendered RFC](https://github.com/datafuselabs/databend/blob/main/docs/doc/60-contributing/03-rfcs/20220704-presign.md)
- [RFC PR](https://github.com/datafuselabs/databend/pull/6503)

### reqsign

- [x] https://github.com/Xuanwo/reqsign/issues/86

### OpenDAL

- [x] https://github.com/datafuselabs/opendal/discussions/406
- [x] https://github.com/datafuselabs/opendal/discussions/407
- [x] https://github.com/datafuselabs/opendal/pull/413
- [x] https://github.com/datafuselabs/opendal/issues/394
- [x] https://github.com/datafuselabs/opendal/pull/414

### Databend

- [x] https://github.com/datafuselabs/databend/pull/6503
- [x] https://github.com/datafuselabs/databend/pull/6513
- [ ] https://github.com/datafuselabs/databend/pull/6529

## Notes

- We will implement this feature for `s3` first.

## Reference

- https://docs.snowflake.com/en/sql-reference/functions/get_presigned_url.html

**Comment by Xuanwo** [comment]
Depends on opendal: https://github.com/datafuselabs/opendal/issues/394

**Comment by BohuTANG** [comment]
Btw, what is the [GET_STAGE_LOCATION](https://docs.snowflake.com/en/sql-reference/functions/get_stage_location.html) used for?

**Comment by Xuanwo** [comment]
> Btw, what is the [GET_STAGE_LOCATION](https://docs.snowflake.com/en/sql-reference/functions/get_stage_location.html) used for?

I don't know either. Seems this SQL function can be used in other SQL queries.

**Comment by Xuanwo** [comment]
Progress report:

- Implemented query sign for aws s3 in `reqsign`
- Implemented `accessor_capabilities` support in `opendal`

Next step:

- Implement `presign` support in `opendal`

**Comment by Xuanwo** [comment]
All works at the opendal's side have been done:  https://github.com/datafuselabs/opendal/pull/417

We can start adding this feature to the databend!
