### ISSUE TITLE
Result of aggregation on empty set

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6216]
According to SQL specification:

> Case:
> 
>               i) If TXA is empty, then the result is the null value.
> 
>              ii) If AVG is specified, then the result is the average of the
>                  values in TXA.
> 
>             iii) If MAX or MIN is specified, then the result is respec-
>                  tively the maximum or minimum value in TXA. These results
>                  are determined using the comparison rules specified in
>                  Subclause 8.2, "<comparison predicate>".
> 
>              iv) If SUM is specified, then the result is the sum of the
>                  values in TXA. If the sum is not within the range of the
>                  data type of the result, then an exception condition is
>                  raised: data exception-numeric value out of range.

The aggregate functions should return `NULL` except `COUNT` if the input is an empty set. Both MySQL and Postgres follows this rule.

But Databend will return the default value of input type:
```sql
mysql> select sum(number) from numbers(0);
+-------------+
| sum(number) |
+-------------+
|           0 |
+-------------+
1 row in set (0.04 sec)
Read 0 rows, 0.00 B in 0.004 sec., 0 rows/sec., 0.00 B/sec.

mysql> select sum(number::float64) from numbers(0);
+---------------------+
| sum(number::DOUBLE) |
+---------------------+
|                 0.0 |
+---------------------+
1 row in set (0.03 sec)
Read 0 rows, 0.00 B in 0.004 sec., 0 rows/sec., 0.00 B/sec.
```

Maybe we should follow the SQL standard? It's more reasonable to return `NULL` for empty set. For example, the semantic of `sum([0])` is different from `sum([])`, we should return different result to distinguish between them.

**Comment by leiysky** [comment]
cc @BohuTANG @sundy-li

**Comment by BohuTANG** [comment]
Agree.
Snowflake also follows this rule.

**Comment by sundy-li** [comment]
To make aggregation return NULL on an empty set, we should make all aggregate function's `return_type` returns Nullable data type.

1. Need extra option to wrap the aggregate state.
2. Not compatible with ClickHouse behavior.

I need to investigate the difficulty of implementation based on the current aggregate framework (It may be conflicted with `aggregate_null_adaptor`).

**Comment by BohuTANG** [comment]
I think this is not urgent :/

**Comment by xudong963** [comment]
Related to TPCH Q17
```sql
select
        sum(l_extendedprice) / 7.0 as avg_yearly
from
    lineitem,
    part
where
        p_partkey = l_partkey
  and p_brand = 'Brand#23'
  and p_container = 'MED BOX'
  and l_quantity < (
    select
            0.2 * avg(l_quantity)
    from
        lineitem
    where
            l_partkey = p_partkey
);
```

**Comment by BohuTANG** [comment]
> Related to TPCH Q17
> 
> ```sql
> select
>         sum(l_extendedprice) / 7.0 as avg_yearly
> from
>     lineitem,
>     part
> where
>         p_partkey = l_partkey
>   and p_brand = 'Brand#23'
>   and p_container = 'MED BOX'
>   and l_quantity < (
>     select
>             0.2 * avg(l_quantity)
>     from
>         lineitem
>     where
>             l_partkey = p_partkey
> );
> ```

How did this issue affects Q17?

**Comment by xudong963** [comment]
> > Related to TPCH Q17
> > ```sql
> > select
> >         sum(l_extendedprice) / 7.0 as avg_yearly
> > from
> >     lineitem,
> >     part
> > where
> >         p_partkey = l_partkey
> >   and p_brand = 'Brand#23'
> >   and p_container = 'MED BOX'
> >   and l_quantity < (
> >     select
> >             0.2 * avg(l_quantity)
> >     from
> >         lineitem
> >     where
> >             l_partkey = p_partkey
> > );
> > ```
> 
> How did this issue affects Q17?

Sorry for the confusion. I also found this when I compared the result of databend tpch17 with pg, which regretted NULL, but databend returned 0.

**Comment by Xuanwo** [comment]
Hi, please only quote the content you want to reply.
