### ISSUE TITLE
feat: PromQL handler

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6229]
**Summary**

Add a new handler for PromQL:
https://docs.rs/promql/latest/promql/
https://prometheus.io/docs/prometheus/latest/querying/basics/
https://promlabs.com/blog/2021/10/14/promql-vendor-compatibility-round-three

**Comment by flaneur2020** [comment]
the storage & query model of prometheus is quite different, I think it's ok to add a middleware proxy to translate the promql to a databend database with a specialized table schema, but it can be very hard to represent promql for any table without introducing a specialized storage engine about time series.

**Comment by rahul3002** [comment]
If this issue is open, I would love to sink my teeth into it!

**Comment by BohuTANG** [comment]
This task is not of high priority.

**Comment by BohuTANG** [comment]
Outdate, let's close.
