### ISSUE TITLE
Feature: Delay interpreting the view table

### ISSUE THREAD

**Issue by junnplus** [datafuselabs/databend#6247]
**Summary**

Before the interpreter layer, the underlying SQL of the view table will be [parsed](https://github.com/datafuselabs/databend/blob/main/query/src/sql/statements/query/query_schema_joined_analyzer.rs#L115-L132), so that the interpreter cannot obtain the information from the original table. It will be very troublesome if we want to check the permissions of the underlying SQL.

**Comment by BohuTANG** [comment]
We can do it in the new planner, cc @andylokandy @leiysky

**Comment by junnplus** [comment]
Talked to @zhang2014  yesterday, not sure if he started doing it

**Comment by zhang2014** [comment]
> Talked to @zhang2014 yesterday, not sure if he started doing it

I haven't started this task yet. it's fine if others are interested : )

**Comment by leiysky** [comment]
> f the underl

IMO, we'd better check the privilige in catalog. For example,
```sql
create table t (a int);
create view v as select * from t;

select * from v; 
```

During the binding phase, we will expand the query into `select * from (select * from t) as v`, invoke `Catalog::get_table` to get a table handle. We can pass a privilige parameter here to check if the table can be accessed in current session.

**Comment by junnplus** [comment]
Any progress?

**Comment by junnplus** [comment]
> Any progress?

ping @andylokandy @zhang2014

**Comment by zhang2014** [comment]
No update, I haven't started this task yet. maybe @andylokandy  is interested in this task?

**Comment by andylokandy** [comment]
IMO, we have better check the permission when we trying to access catalog information. This means, in this case, the sql of view should not be accessible to the binder, and thus unpermitted requests will not be passed to the interpreter.

**Comment by andylokandy** [comment]
Moved to https://github.com/datafuselabs/databend/issues/6471
