### ISSUE TITLE
[bug] MySQL connection can't be closed normally

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6263]
**Summary**

Remains too much closed_wait

How to produce:

1. start databend-query
2. use MySQL client to connect with `databend-query`
3. quit MySQL client
4. repeat 2-3

![origin_img_v2_c30cbc66-a8be-4718-bae5-e3514cfee63g](https://user-images.githubusercontent.com/3325189/176073216-e2a4c1ce-fee4-4ae5-bb35-5003218ce4cd.jpg)

**Comment by sundy-li** [comment]
Related to:

https://github.com/datafuselabs/databend/blob/61303304e4bc1fa982e4c3918555f1ed84fe1c40/query/src/servers/mysql/mysql_session.rs#L35-L38


If we comment on these codes, there will be no connection leak. `ClickHouse` session also had these codes but works fine.

**Comment by BohuTANG** [comment]
@zhang2014 any thoughts on this?

**Comment by zhang2014** [comment]
After we support asynchronous MySQL server, we should not need to convert streams to blocked streams

**Comment by ClSlaid** [comment]
I guess it's an application layer problem, the server is not aware of the termination of connection so it stayed at CLOSE_WAIT.
Take a look at servers asynchronous reading part on TcpStream?

**Comment by sundy-li** [comment]
> I guess it's an application layer problem, the server is not aware of the termination of connection so it stayed at CLOSE_WAIT. Take a look at servers asynchronous reading part on TcpStream?

But if we comment on the codes above, it works fine (connection will be closed normally). 
And the [example](https://github.com/datafuselabs/opensrv/blob/main/mysql/examples/serve_one.rs) works find too.

**Comment by ClSlaid** [comment]
> > I guess it's an application layer problem, the server is not aware of the termination of connection so it stayed at CLOSE_WAIT. Take a look at servers asynchronous reading part on TcpStream?
> 
> But if we comment on the codes above, it works fine (connection will be closed normally). 
> And the [example](https://github.com/datafuselabs/opensrv/blob/main/mysql/examples/serve_one.rs) works find too.  

Yes, you are right.
The ownership of 'TcpStream' is hold by 'Session', and whom is owned by 'SessionRef's.

Does the session dropped after killing the client? The 'SessionManager' may happend to hold a 'StreamRef'. I'll take a deeper look.

**Comment by PsiACE** [comment]
hi @ClSlaid , glad to see your survey. I have just opened a PR #6302 and removed some of the code that contained attach_session. Everything seems to be working fine. Would you mind helping to review it, I'm not sure that would be a good solution?
