### ISSUE TITLE
fake clickhouse engines

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#6266]
**Summary**

```create table ...  ENGINE = MergeTree```

https://github.com/airbytehq/airbyte/blob/62cf4418272d5d80d6e259c7e11c3e7b4014dec3/airbyte-integrations/connectors/destination-clickhouse/src/main/java/io/airbyte/integrations/destination/clickhouse/ClickhouseSqlOperations.java#L37-L51

**Comment by youngsofun** [comment]
cc @ZhiHanZ

**Comment by ZhiHanZ** [comment]
I think if we want to support airbyte, at least two things we should do, fake clickhouse engines is the first one, and the second is to improve our CSV file parser.
currently we could not insert csv file contain json field into table

**Comment by BohuTANG** [comment]
Could you give a format example of this CSV? @ZhiHanZ

**Comment by youngsofun** [comment]
@ZhiHanZ  https://github.com/datafuselabs/databend/issues/6314

**Comment by ZhiHanZ** [comment]
> Could you give a format example of this CSV? @ZhiHanZ

Could take a look at how airbyte encoding their batch insert into csv file https://github.com/airbytehq/airbyte/blob/62cf4418272d5d80d6e259c7e11c3e7b4014dec3/airbyte-integrations/connectors/destination-jdbc/src/main/java/io/airbyte/integrations/destination/jdbc/JdbcSqlOperations.java#L75-L85

Here for example data format looks like
a, {'b": "c"}, d

**Comment by youngsofun** [comment]
> The simpler way is federated regex?

@BohuTANG do you mean

match `.. create table ..  ENGINE = MergeTree .. `
rewrite it to `.. create table ..  ENGINE = fuse .. `?

**Comment by youngsofun** [comment]
@ZhiHanZ  does airbyte use clickhouse session  (SessionID)   ?

**Comment by BohuTANG** [comment]
> > The simpler way is federated regex?
> 
> @BohuTANG do you mean
> 
> match `.. create table .. ENGINE = MergeTree .. ` rewrite it to `.. create table .. ENGINE = fuse .. `?

Just deep into the code, we can rewrite the `CreateTable` engine from `MergeTree` to `Fuse` in ClickHouse HTTP handler before call the InterpreterCreateTable.
