### ISSUE TITLE
bug: big latency of show tables command

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

![wk26kVwXgP](https://user-images.githubusercontent.com/10904090/176149913-163be581-e015-4f22-a29d-82a51ebcc337.jpg)

it took 0.7s - 0.8s, is it performance degradation? cc @drmingdrmer 

### What's Wrong?

v0.7.106

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZeaLoVe** [comment]
[databend-log-all.txt](https://github.com/datafuselabs/databend/files/9000393/databend-log-all.txt)

Deploy mode: https://databend.rs/doc/deploy/local
Both query and meta logs in the txt file, this query laster  3.550 sec, from 49s - 52s .

**Comment by drmingdrmer** [comment]
I see a log of this: 
```
2022-06-28T10:51:23.912323Z DEBUG worker_loop:do_read: common_meta_grpc::grpc_client: MetaGrpcClient::do_read request req=MGetKV(MGetKVReq { keys: ["__fd_database_by_id/1"] })
```

`__fd_database_by_id` is for listing table history(`list_tables_history()`), e.g., dropped tables.

This method is called on line 51. I doubt this is the root that emits a lot of `get_table()` calls to metasrv:
https://github.com/datafuselabs/databend/blob/38ef9b7b4f2f1cc221aec78db3a3889f5b5618e3/query/src/storages/system/tables_table.rs#L42-L54

Is it by design to let `show tables` will list all tables and all table history?
@dantengsky @BohuTANG

**Comment by BohuTANG** [comment]
I think for the `show tables` we can use `list_tables` API, not `list_tables_history`.

**Comment by dantengsky** [comment]
> Is it by design to let show tables will list all tables and all table history?     by @drmingdrmer 
> I think for the show tables we can use list_tables API, not list_tables_history.   by @BohuTANG 


kind of:

The `show tables ... ` stmt uses `system.tables`, as the "underlying data source" (without predicate pushdown).

and the impl of `system.tables` will fetch all the table infors, including droppped tables.

--------------

e.g.
~~~
DROP TABLE t4;
SHOW TABLES HISTORY LIKE 't4';
+-------------------+-------------------------------+
| Tables_in_default | drop_time                     |
+-------------------+-------------------------------+
| t4                | 2022-05-25 05:56:49.622 +0000 |
+-------------------+-------------------------------+
~~~
from https://databend.rs/doc/reference/sql/show/show-tables

`SHOW TABLES HISTORY LIKE 't4'` will be translated to sth like `select * from system.tables where table_name = t4"`

--------------

For stmt `show tables`, it will be translated to `select * from system.tables where dropped_on IS NULL`.
Again, the `system.tables` does not aware of the predicates. Filter kicks in after all the table infors fetched (including dropped ones)

--------------

@BohuTANG  seems `system.tables` should handle predicate pushdowns, at least, to dynamically switch between `list_tables` and `list_tables_history`, if we keep the way of impl unchanged.

----------------

Apparently, for `show` statements that do need information on the dropped tables, the above "strategy" does not work.

**Comment by BohuTANG** [comment]
How about the time cost to show transient tables in a database?

**Comment by dantengsky** [comment]
> How about the time cost to show transient tables in a database?

Should be no big differences there, since historical snapshots are not kept in meta kv.

The (unshown, for this issue) dropped tables matter in this case.

**Comment by dantengsky** [comment]
How about let `system.tables` respects predicate pushdowns, and dynamically switch between `list_tables` and `list_tables_history` according to the related predicate?  At least, this can mitigate the situation of common case.
