### ISSUE TITLE
Refactor mysql/clickhouse handler into Actor-Model-styled code

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6306]
By the way, I think the current implementation of session management system to be too complicated, mixing Arc types and direct method call together.
I suggest refact into an Actor-Model-styled code as in [this blog](https://ryhl.io/blog/actors-with-tokio/), using channels along with message types, to avoid structure embeded `Arc` types (like those between `Session` and `SessionMgr`) and direct method calls.

_Originally posted by @ClSlaid in https://github.com/datafuselabs/databend/issues/6263#issuecomment-1169032898_

**Comment by ClSlaid** [comment]
We can begin from refacting `Session` and `SessionMgr`.

The actor model is not so perfect, message passing is not as fast as direct function calling. I raised this suggestion in consideration of reducing complexibility and erase potential session leak in #6309.
Further discussions are needed.

**Comment by BohuTANG** [comment]
Outdate, close.
