### ISSUE TITLE
Feature: support prewhere to optimize select *

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#6312]
**Summary**

ClickHouse reference: https://clickhouse.com/docs/en/sql-reference/statements/select/prewhere

CC: @sundy-li @BohuTANG

**Comment by sundy-li** [comment]
I don't think it's a good feature, `prewhere` is not suggested to used by users anymore in ClickHouse.

As it said:

```
It is enabled by default even if PREWHERE clause is not specified explicitly
```

So this is the area of optimization but not SQL syntax.

**Comment by zhang2014** [comment]
> So this is the area of optimization but not SQL syntax.

yes, + 1

**Comment by zhang2014** [comment]
Move to #7166
