### ISSUE TITLE
[Track] bugs in csv input format parser

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#6314]
**Summary**

**Comment by youngsofun** [comment]
@ZhiHanZ  ```a, {'b": "c"}, d```  is not a valid CSV,  to my understanding.   can you provide more context for it?

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ `a, {'b": "c"}, d` is not a valid CSV, to my understanding. can you provide more context for it?

That is some psedo examples, here is some temp file generated from airbyte which could be helpful
```csv
ee9e9984-083a-439b-8a1d-f9178181fb01,"{""id"":1,""topic"":""install"",""timestamp"":""2017-08-22T17:22:15Z"",""model"":""install"",""details"":""{\""name\"":\""Conferência Faturamento - Custo - Taxas - Margem - Resumo ano inicial até -2\"",\""description\"":null}""}",2021-07-08 00:58:59.889
```

**Comment by youngsofun** [comment]
CSV has options for escaping `"`:    `""`  or `\"`

**Comment by sundy-li** [comment]
Need modify 
```
 fn de_text_csv<R: BufferRead>(
        &mut self,
        reader: &mut R,
        _format: &FormatSettings,
    ) -> Result<()> {
        self.buffer.clear();
        reader.read_quoted_text(&mut self.buffer, b'"')?;

        let val = serde_json::from_slice(self.buffer.as_slice())?;
        self.builder.append_value(val);
        Ok(())
    }
```

**Comment by youngsofun** [comment]
I think csv should do know nothing about `{` or `[` ?
do we support `"` as default escape char (instead of `\`) or need to specify it before parse?

**Comment by wubx** [comment]
track: https://github.com/datafuselabs/databend/issues/5586

**Comment by wubx** [comment]
> > @ZhiHanZ `a, {'b": "c"}, d` is not a valid CSV, to my understanding. can you provide more context for it?
> 
> That is some psedo examples, here is some temp file generated from airbyte which could be helpful
> 
> ```shell
> ee9e9984-083a-439b-8a1d-f9178181fb01,"{""id"":1,""topic"":""install"",""timestamp"":""2017-08-22T17:22:15Z"",""model"":""install"",""details"":""{\""name\"":\""Conferência Faturamento - Custo - Taxas - Margem - Resumo ano inicial até -2\"",\""description\"":null}""}",2021-07-08 00:58:59.889
> ```

if support this feature, github archive file is very easy to load to databend.

**Comment by youngsofun** [comment]
@wubx @ZhiHanZ  this case is fixed by https://github.com/datafuselabs/databend/pull/6524#event-6947878136

> > > @ZhiHanZ `a, {'b": "c"}, d` is not a valid CSV, to my understanding. can you provide more context for it?
> > 
> > 
> > That is some psedo examples, here is some temp file generated from airbyte which could be helpful
> > ```shell
> > ee9e9984-083a-439b-8a1d-f9178181fb01,"{""id"":1,""topic"":""install"",""timestamp"":""2017-08-22T17:22:15Z"",""model"":""install"",""details"":""{\""name\"":\""Conferência Faturamento - Custo - Taxas - Margem - Resumo ano inicial até -2\"",\""description\"":null}""}",2021-07-08 00:58:59.889
> > ```
> 
> if support this feature, github archive file is very easy to load to databend.
