### ISSUE TITLE
Stream COPY from a directory

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6338]
**Summary**

Like:
https://docs.snowflake.com/en/user-guide/data-load-considerations-load.html#loading-older-files

Draft:
Generate a digest from metadata, including:
1. database id
2. table id
3. File etag(md5?)
4. File name

* [x] #7548
* [x] #7549
* [x] #7550
* [x] #7561

**Comment by BohuTANG** [comment]
@junnplus As seen you are working on https://github.com/datafuselabs/databend/pull/6344, are you also interested in this task?

**Comment by Xuanwo** [comment]
@junnplus May be busy on other works, let me take this.

**Comment by junnplus** [comment]
@Xuanwo I haven't started this task yet. You are free to assign.

**Comment by BohuTANG** [comment]
This is related to metasrv, such as the unique identify ID can be stored in the metasrv.
cc @lichuang

**Comment by BohuTANG** [comment]
Because databend can COPY from remote files, so the file may not be an object from s3.

**Comment by Xuanwo** [comment]
Cc @ClSlaid, can you help add the `ETag` field in StageFile?
