### ISSUE TITLE
Add function to infer schema from files(CSV/Parquet)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6345]
**Summary**

As [arrow2](https://github.com/jorgecarleitao/arrow2) has  `infer_schema`:
Parquet:
https://github.com/jorgecarleitao/arrow2/blob/5725fa3c18830f88ed0ed67067dda5c1d2080dca/src/io/parquet/read/schema/mod.rs#L23-L31

CSV:
https://github.com/jorgecarleitao/arrow2/blob/79b87b629d8fdc3fa40b5ad7abc3889c5102a52b/src/io/csv/read/infer_schema.rs#L15

We can add a function `INFER_SCHEMA` to do the schema infer, syntax like:
```
INFER_SCHEMA(
LOCATION => '{ internalStage | externalStage }'
  , FILE_FORMAT => '<format_name>'
)
```

example(from snow):
```
select * from infer_schema(location=>'@mystage/geography/cities.parquet' , file_format=>'parquet')


+-------------+---------+----------+---------------------+--------------------------+
| COLUMN_NAME | TYPE    | NULLABLE | EXPRESSION          | FILENAMES                |
|-------------+---------+----------+---------------------+--------------------------|
| continent   | TEXT    | True     | $1:continent::TEXT  | geography/cities.parquet |
| country     | VARIANT | True     | $1:country::VARIANT | geography/cities.parquet |
+-------------+---------+----------+---------------------+--------------------------+
```

Reference:
https://docs.snowflake.com/en/sql-reference/functions/infer_schema.html

**Comment by BohuTANG** [comment]
cc @Xuanwo

**Comment by Xuanwo** [comment]
I'm taking this issue now.

**Comment by Xuanwo** [comment]
Already implemented by @youngsofun
