### ISSUE TITLE
databend-query use too much sys cpu

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#6367]
## **Summary**
when do a group by query for a hive table,  the user cpu of databend query takes 30%, while sys cpu used about 50%, seems kernel too much time at memory allocation

##  databend version:  
 2a6589a7ecadabf52b5df8714b36d73e17ca322d. build with --release. (could't reproduce on debug version )
## dataset:
   ontime 
## sql: 
 select origincityname,  sum(flights*dot_id_reporting_airline) as c from databend.ontime group by origincityname order by c desc limit 100;

## go pprof
[pprof.samples.cpu.007.pb.gz](https://github.com/datafuselabs/databend/files/9019770/pprof.samples.cpu.007.pb.gz)

## perf pprof 
![databend](https://user-images.githubusercontent.com/5102100/176678308-77200681-934e-4334-abb3-e97ae8d8fc06.svg)

**Comment by sandflee** [comment]
seems  arrow2 binary decoder and group by transform allocated  memory and do memcpy  too frequently,  leading the kernel spent most time on do_page_fault. 

<arrow2::io::parquet::read::deserialize::binary::basic::BinaryDecoder<O> as arrow2::io::parquet::read::deserialize::utils::Decoder>::extend_from_state

<common_datablocks::kernels::data_block_group_by_hash::HashMethodSingleString as common_datablocks::kernels::data_block_group_by_hash::HashMethod>::build_keys

**Comment by BohuTANG** [comment]
@sandflee ,
Could you do a profile again with the latest main branch, we have a memory leak fix:https://github.com/datafuselabs/databend/pull/6354, I am not sure it is related to this issue.

**Comment by sandflee** [comment]
I tried to pre-allocate the memory in  https://github.com/datafuse-extras/arrow2/compare/main...sandflee:arrow2:memory, to prevent vec auto grow and memcpy,  but not helped too much

**Comment by sandflee** [comment]
@BohuTANG ,  I tried the lattest code with https://github.com/datafuselabs/databend/pull/6354, but takes no affect to reduce cpu :(
