### ISSUE TITLE
Feature: Support `SingleJoin` for scalar subqueries

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6425]
For now, we implement scalar subquery with `CrossApply`(for correlated) or `CrossJoin`(for uncorrelated) and `Max1Row` operator, which is not efficient.

And there is still some incorrect behavior of this implementation, for example, it won't return a `NULL` value for the subqueries that produces empty result set.

It's time to introduce `SingleJoin` operator to resolve this.

**Comment by leiysky** [comment]
cc @xudong963

**Comment by xudong963** [comment]
Oh, I have opened an issue https://github.com/datafuselabs/databend/issues/6413
