### ISSUE TITLE
Feature: Support `CREATE TABLE ... AS ...` in new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6427]

**Comment by leiysky** [comment]
cc @andylokandy

**Comment by yuuch** [comment]
I want to try it  ;)

**Comment by leiysky** [comment]
@yuuch We have supported resolving the schema of target table, but haven't integrated it with data ingestion function(i.e. `InsertInterpreterV2`).

See: https://github.com/datafuselabs/databend/blob/7cbc1c57f445f4e0b789d4e06b0d9db1fa341414/query/src/sql/planner/binder/ddl/table.rs#L271-L277

Maybe this will help.

**Comment by yuuch** [comment]
@leiysky I have almost finish the work for
```sql
CREATE TABLE `t2` AS SELECT * FROM `t1`
```



Do I need to implement CREATE TABLE with specified columns?
```sql
CREATE TABLE `t2` (i_t2 INT) AS SELECT * FROM T1
```

 :)

**Comment by xudong963** [comment]
> I have almost finish the work for

Nice work! 👍

> Do I need to implement CREATE TABLE with specified columns?

Our new planner needs to implement all old planner features, so we need to implement this, you can complete the task in the same PR or separately.

**Comment by yuuch** [comment]
BTW I fix a small bug about displaying error code, while running stateless test.
The program returned `Err::BadArgument` (1006), while the expected is `Err::UnImplement`(1002).
The log shows:
```shell
ERROR 1105 (HY000) at line 74: Code: 1054, displayText = Expected server error code: 1002 but got: Ok..
```
it should be
```shell
ERROR 1105 (HY000) at line 74: Code: 1054, displayText = Expected server error code: 1002 but got: 1006..

```
