### ISSUE TITLE
bug(meta): after restarting a follower, the Raft state of the leader and follower are confused

### ISSUE THREAD

**Issue by nickb937** [datafuselabs/databend#6433]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.7.113-nightly

### What's Wrong?

I have a 3 replica meta-server.  Node 1 is leader, nodes 2 and 3 are followers.
- Performing a rolling restart of the Meta servers puts the whole Raft cluster into an unusable state.
- Terminating all meta servers and the starting all meta servers (simulation of a power loss) also puts the Raft cluster into a state that it cannot recover from.
- Restarting a follower confuses the cluster state

### How to Reproduce?

Install 3 replica meta server on kubernetes, based on helm chart, resulting in something similar to this: 

```
$ kubectl get pods -n databend
NAME             READY   STATUS    RESTARTS   AGE
metrics-meta-0   1/1     Running   0          2m16s
metrics-meta-1   1/1     Running   0          103s
metrics-meta-2   1/1     Running   0          69s
```

metrics-meta-0: id=1
metrics-meta-1: id=2
metrics-meta-2: id=3

metrics-meta-0 is the first Pod created, so it is the leader.  Restart follower:

```
$ kubectl delete pod -n databend metrics-meta-1
```

After restart, metrics on this Pod look like this and the node is stuck in a leader/candidate state and never changes state to follower:

```
# HELP metasrv_meta_network_recv_bytes Total number of recv bytes from meta grpc client.
# TYPE metasrv_meta_network_recv_bytes counter
metasrv_meta_network_recv_bytes 0
# HELP metasrv_meta_network_req_failed Total number of fail request from meta grpc client.
# TYPE metasrv_meta_network_req_failed counter
metasrv_meta_network_req_failed 0
# HELP metasrv_meta_network_req_inflights Total number of inflight meta grpc requests.
# TYPE metasrv_meta_network_req_inflights gauge
metasrv_meta_network_req_inflights 0
# HELP metasrv_meta_network_req_success Total number of success request from meta grpc client.
# TYPE metasrv_meta_network_req_success counter
metasrv_meta_network_req_success 0
# HELP metasrv_meta_network_sent_bytes Total number of sent bytes to meta grpc client.
# TYPE metasrv_meta_network_sent_bytes counter
metasrv_meta_network_sent_bytes 0
# HELP metasrv_raft_network_active_peers Current number of active connections to peers.
# TYPE metasrv_raft_network_active_peers gauge
metasrv_raft_network_active_peers{address="10.240.1.5:28004",id="1"} 0
metasrv_raft_network_active_peers{address="10.240.1.86:28004",id="3"} 0
# HELP metasrv_raft_network_sent_bytes Total number of sent bytes to peers.
# TYPE metasrv_raft_network_sent_bytes counter
metasrv_raft_network_sent_bytes{to="1"} 55676
metasrv_raft_network_sent_bytes{to="3"} 55583
# HELP metasrv_server_applying_snapshot Whether or not statemachine is applying snapshot.
# TYPE metasrv_server_applying_snapshot gauge
metasrv_server_applying_snapshot 0
# HELP metasrv_server_current_leader_id Current leader id of cluster, 0 means no leader.
# TYPE metasrv_server_current_leader_id gauge
metasrv_server_current_leader_id 2
# HELP metasrv_server_is_leader Whether or not this node is current leader.
# TYPE metasrv_server_is_leader gauge
metasrv_server_is_leader 1
# HELP metasrv_server_leader_changes Number of leader changes seen.
# TYPE metasrv_server_leader_changes counter
metasrv_server_leader_changes 1
# HELP metasrv_server_node_is_health Whether or not this node is health.
# TYPE metasrv_server_node_is_health gauge
metasrv_server_node_is_health 1
# HELP metasrv_server_proposals_applied Total number of consensus proposals applied.
# TYPE metasrv_server_proposals_applied gauge
metasrv_server_proposals_applied 9
# HELP metasrv_server_proposals_failed Total number of failed proposals.
# TYPE metasrv_server_proposals_failed counter
metasrv_server_proposals_failed 0
# HELP metasrv_server_proposals_pending Total number of pending proposals.
# TYPE metasrv_server_proposals_pending gauge
metasrv_server_proposals_pending 0
# HELP metasrv_server_read_failed Total number of failed read request.
# TYPE metasrv_server_read_failed counter
metasrv_server_read_failed 0
# HELP metasrv_server_watchers Total number of active watchers.
# TYPE metasrv_server_watchers gauge
metasrv_server_watchers 0
```

Log file for the leader node (observe the change in logging pattern at 08:33:22, which is about the time node id=2 comes back online)

[meta-master.txt](https://github.com/datafuselabs/databend/files/9037905/meta-master.txt)

Log file for the restarted node:

[meta-id2.txt](https://github.com/datafuselabs/databend/files/9037892/meta-id2.txt)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Thanks for reporting!

cc @drmingdrmer @lichuang to take a look.

**Comment by drmingdrmer** [comment]
Oh, I see. There are logs with `candidate` because the meta-client uses a connection pool internally. The tracing-span stack will always be the one the first the connection is made, e.g., when sending a `vote` request in a `candidate` state.

So, you do not need to worry about it. Everything is all right.

**Comment by drmingdrmer** [comment]
> Note that in the logs i supplied before, that the restarted node suggests it is in "candidate" state rather than "follower" state, so I don't think that it is re-joining the cluster.

Which node do you suppose to be a follower?
The leader can be any node after restarting the entire cluster.
From the log, node-1 became a follower and node-2 became the leader.
Is there any problem with this?

A node will re-join the cluster as soon as it is started. You can see in the log, that node-2, the leader sent heartbeat RPC to node-1. Node-1 received the heartbeat RPC.

The timeout on the client is 1 sec. But the restarted cluster will spend about 2 seconds to establish a leader to serve requests from `query`.

The meta server has nothing wrong, from the log you attached.
If you believe the problem is on the query side, may you attach a log file on what happened while meta servers restarted? The time in the last piece of the log does not seem to be when the meta servers restarted.

BTW, what's going wrong indeed?

**Comment by nickb937** [comment]
I expect 1 leader and two followers and after the restart of any of the pods I would expect there to eventually be 1 leader and two followers. 

If all pods are restarted simultaneously (a power loss event) I would also expect them to recover to 1 leader and 2 followers.

I do not expect a rolling restart of the pods (for example an upgrade or a config update) to put the cluster into a state where it does not recover to 1 leader and 2 followers because that means the Query service won't work

**Comment by nickb937** [comment]
I deleted the system, started the Meta servers, ensured they were at Quorum, then started the Query server and verified a connection could be established:

```
$ mysql -h 127.0.0.1 -uroot -proot -P 3307
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.26-v0.7.113-nightly-47e20ee-simd(rust-1.64.0-nightly-2022-07-02T16:30:58.00108923Z) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show tables;
Query OK, 0 rows affected (0.198 sec)

MySQL [(none)]> Bye
```

I then rolling restarted the meta servers, ensuring that each restarted pod was back to a Running state before restarting the next:

```
kubectl delete pod -n databend metrics-meta-2
kubectl delete pod -n databend metrics-meta-1
kubectl delete pod -n databend metrics-meta-0
```

Now the Query service is unusable:

```
$ mysql -h 127.0.0.1 -uroot -proot -P 3307
ERROR 1698 (28000): Authenticate failed, user: "root", auth_plugin: "mysql_native_password"
```


Attached are log files:

[metrics-query.txt](https://github.com/datafuselabs/databend/files/9041690/metrics-query.txt)
[metrics-meta-2.txt](https://github.com/datafuselabs/databend/files/9041676/metrics-meta-2.txt)
[metrics-meta-1.txt](https://github.com/datafuselabs/databend/files/9041677/metrics-meta-1.txt)
[metrics-meta-0.txt](https://github.com/datafuselabs/databend/files/9041678/metrics-meta-0.txt)

**Comment by drmingdrmer** [comment]
> What I'm experiencing is that a rolling restart of the meta service ( which might be done for an upgrade, or a configuration update) causes the raft cluster to get into a state where it cannot re-establish a quorum. Once it is in that state it is not possible to use the Query service.

As I said, after the restart, the meta service cluster had elected a leader in the first log you attached. There is nothing wrong with the meta service cluster.

And from the last several logs you attached, actually, I do not know what's going on in your cluster. It seems like a configuration mistake:
In `meta-2.txt`(node id=3), the raft advertizes host is:
`\"raft_advertise_host\": \"10.240.0.233\`

But in `meta-1.txt`, it tries to connect to node(id=3) with: `connect: target=3: http://10.240.1.3:28004`.

My suggestion is to test meta service in a local machine, to see if it still reproduces this problem.

**Comment by nickb937** [comment]
You may not see this issue on a local machine because the service is doing to take the fixed IP that you specify in the configuration, either 127.0.0.1 or the eth0 address.  When you delete a pod on Kubernetes, it will naturally change IP address:

This confusion has happened because the published helm chart does not yet include this fix https://github.com/datafuselabs/helm-charts/commit/860245fd547a0332ff177509bed71cf300b6c815 from 14 days ago so the `raft-advertised-host` changes as the pods are restarted:


```
$ helm repo list
NAME                                  	URL                                                                   
databend                              	https://charts.databend.rs                                 

$ helm template metrics databend/databend-meta
```

Advertises the POD_IP:

```
               case ${BASH_REMATCH[2]} in
                  0)
                    echo "initialize leader node";
                    /databend-meta --id ${ID} --raft-advertise-host ${POD_IP} \
                                  --config-id ${ID} --single
                  ;;
                  *)
                    echo "initialize follower node";
                    /databend-meta --id ${ID} --raft-advertise-host ${POD_IP} \
                                  --config-id ${ID} --join ${NAME}-0.metrics-databend-meta:28004
                  ;;
                esac
```

**Comment by drmingdrmer** [comment]
Raft manages the cluster information in its own storage, which means, that once the information of a node is configured(when the first time running databend-meta with `--single` or `--join`), it will not change.

If in your environment, every time a databend-meta restarts the IP changes, you'd have to config the `raft-advertise-host` to a hostname so that other nodes will always reach this node by the hostname.

**Comment by nickb937** [comment]
I would say that after the next helm-chart release this problem wouldn't happen again for a new install
