### ISSUE TITLE
Update README deploy link

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6442]
**Summary**
After https://github.com/datafuselabs/databend/pull/6303 merged, README Deployment section links are broken.

**Comment by soyeric128** [comment]
> **Summary** After #6303 merged, README Deployment section links are broken.

Did you mean the deploy links on this page https://databend.rs/doc/guides/?

**Comment by BohuTANG** [comment]
This links also need fixed.
We can change the deployed section as the new way which you added in #6303

**Comment by soyeric128** [comment]
pls review this PR: https://github.com/datafuselabs/databend/pull/6446
