### ISSUE TITLE
Lots of INFO log: INFO databend_meta::network: connected: target=2: http://localhost:28203

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6447]
**Summary**
![image](https://user-images.githubusercontent.com/172204/177228428-21a59814-3326-46c0-bcc1-f2cd257a228e.png)

**Comment by BohuTANG** [comment]
@drmingdrmer, does this log not need `INFO` level?

**Comment by drmingdrmer** [comment]
Got it
