### ISSUE TITLE
Feature:  Output format Null

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6449]
**Summary**

Description for this feature.

Output format Null support to ignore the results.

**Comment by youngsofun** [comment]
what`s it used for? does select stmt need to aware it for optimization?

**Comment by sundy-li** [comment]
Use to check the SQL execution time but ignore the output results.

Example query is #6562

**Comment by Xuanwo** [comment]
Has been implemented by `ignore_result`.
