### ISSUE TITLE
1 vulnerability found

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6482]
**Summary**

https://github.com/datafuselabs/databend/runs/7201645811?check_suite_focus=true#step:3:1467

**Comment by dantengsky** [comment]
being addressed in https://github.com/datafuselabs/databend/pull/6067

**Comment by Xuanwo** [comment]
I cherry-pick the changes made by @dantengsky and fixed them in https://github.com/datafuselabs/databend/pull/6483
