### ISSUE TITLE
Add deepnote intergration to document

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6490]
**Summary**

Databend supports full ClickHouse  HTTP,  [deepnote](https://deepnote.com/) added ClickHouse integration  recently: https://docs.deepnote.com/integrations/clickhouse

Databend and Cloud) works fine with deepnote too, let's document it.

**Comment by Xuanwo** [comment]
cc @flaneur2020, is there any updates on our integration with deepnote?
