### ISSUE TITLE
Feature: add DATE_TRUNC function

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6528]
**Summary**

Description for this feature.

To add `DATE_TURNC` function in planner v2, we can transform the expression in `query/src/sql/planner/semantic/type_check.rs`

**Comment by soyeric128** [comment]
Hi @sundy-li 

Can you help list out which time units the first argument currently accepts? 

Thanks

**Comment by sundy-li** [comment]
```
#date_trunc: "`DATE_TRUNC((YEAR | MONTH | DAY | HOUR | MINUTE | SECOND | DOY | DOW), ...)

```

1. DOY is `day of year`
2. DOW is `day of week`

**Comment by sundy-li** [comment]
Oh,  there is something wrong, we don't support `DOY` and `DOW` in `date_trunc`.  cc @ariesdevil

**Comment by ariesdevil** [comment]
> Oh, there is something wrong, we don't support `DOY` and `DOW` in `date_trunc`. cc @ariesdevil

Got, I'll fix it soon.

**Comment by ariesdevil** [comment]
Also, I think we need support `QUARTER` as well.
