### ISSUE TITLE
display the file name in the error message of COPY INTO

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6552]
I'm loading data into databend with COPY INTO with a batch of files, but on getting this error, I can not get which file is broken:

> 2022/07/08 13:32:30 the 0 time result has error query has error: &{Code:1046 Message:Parse csv error at line 93557185, cause: CSV error: record 93557186 (line: 93557187, byte: 69916103044): found record with 100 fields, but the previous record has 105 fields (while in processor thread 3) Kind:}, stats:

it'd be better to display the file name in the error message.

**Comment by fkuner** [comment]
`streaming_load` can display the error message. Because `copy into` doesn't use the `format_csv`, it can't be diaplayed.

https://github.com/datafuselabs/databend/issues/6531

**Comment by Xuanwo** [comment]
Has been implemented.
