### ISSUE TITLE
Add compat test for fuse engine

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6557]
**Summary**
Like:
https://github.com/datafuselabs/databend/blob/main/.github/actions/test_compat/action.yml

Ensure that each of our versions is compatible with the previous ones.

**Comment by BohuTANG** [comment]
Is it possible to add a compact test for databend-query with different versions(current and previous version) to https://github.com/datafuselabs/databend/blob/main/tests/compat/test-compat.sh?

@drmingdrmer @everpcpc

**Comment by drmingdrmer** [comment]
> Is it possible to add a compact test for databend-query with different versions(current and previous version) to https://github.com/datafuselabs/databend/blob/main/tests/compat/test-compat.sh?

Suppose the query is only compatible with a limited number of history versions. In that case, the query needs two versions defined: `VER` is the version of the query executable, and `MIN_COMPATIBLE` is the oldest version this executable is compatible with.

If the query must be compatible with all history versions, `MIN_COMPATIBLE` is unnecessary.

The fuse-data-compat-test would be:
- Download an old query executable, bring it up, and write some data into it.
- Shut it down, bring up the latest executable, and run some read-only tests.

And the fuse-data-Compatability may differ slightly from the meta service compatibility.
There may be 3 versions of fuse-data: A, B, C such that B can read A, C can read A but can not read B. In other words, the fuse-data format may not evolve incrementally. Thus maybe fuse data compatibility tests have to test every possible version combinations.

**Comment by drmingdrmer** [comment]
I'm trying to build up a script that will:
- 1. Bring up databend-query of the specified version, and run a bunch of SQL to feed data;
- 2. Shut it down and bring up the latest databend-query, and run another bunch of SQL to load the data.

My question is:
What SQL statements will be enough to cover the compatibility test in these 2 phases?

**Comment by drmingdrmer** [comment]
The version to assert being compatible with the latest databend-query has to be explicitly specified:

https://github.com/datafuselabs/databend/blob/a65c8d33269008ac775f2232260d96e0750b979c/.github/actions/fuse_compat/action.yml#L29-L30
