### ISSUE TITLE
OOM on executing SELECT * FROM ontime in a 8c16g instance

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6562]
**Summary**

I'm running databend-query in a kubernetes deployment, executing `SELECT * FROM ontime` through the HTTP API may causes the pod terminated.

in my understanding, polling the result from databend-query http api is a streaming operation, do not necessary get all the output from the query into memory.

Tasks List:

- [x] make ClickHouse TCP handler support writing streaming results #6789 
- [x] make ClickHouse HTTP handler support writing streaming results  （already have）
- [x] make HTTP handler support writing streaming results （already have）
- [-]  make MySQL handler support writing streaming results （Can't have, it's MySQL protocol limited）

**Comment by BohuTANG** [comment]
cc @youngsofun

**Comment by flaneur2020** [comment]
this OOM can also be reproduced in the mysql client

**Comment by flaneur2020** [comment]
can also be reproduced in the clickhouse client:

<img width="608" alt="Screen Shot 2022-07-13 at 11 00 59 AM" src="https://user-images.githubusercontent.com/129800/178641660-dcdabc1b-a9fb-4935-a574-24872cadded9.png">

**Comment by youngsofun** [comment]
@flaneur2020  thx, clickhouse handler is streaming too,  it is easier o debug then httphandler .

**Comment by sundy-li** [comment]
`ontime` table has wide columns.   It's streaming in the pipeline execution but there may be more than 1 block in memory.

**Comment by flaneur2020** [comment]
can I take this issue?

I want have a practise about how to diagnose the OOM issue in rust :eyes:

**Comment by flaneur2020** [comment]
> `ontime` table has wide columns, so it'll take much more memory in just one block. It's streaming in the pipeline execution but there may be more than 1 block in memory.
> 
> Memory : `8 threads * N * M`: `N` is the number of blocks in the pipeline and `M` is the size of the block

can we get the metric about how many living data blocks and record it into prometheus ? 🤔

**Comment by flaneur2020** [comment]
![output](https://user-images.githubusercontent.com/129800/178975699-870e183c-baae-4475-9289-d4d6d1242b56.svg)

```
cd /mnt/data
curl http://localhost:8081/debug/mem/pprof/profile > base_profile
echo "select * from ontime;" | mysql -h 127.0.0.1  -P3308 -uroot -s  -N &
sleep 2
curl http://localhost:8081/debug/mem/pprof/profile > after_profile
jeprof /databend-query --base=base_profile after_profile --svg > output.svg
```

any idea about this?

**Comment by flaneur2020** [comment]
the mysql protocol have a `collect<>` so the output is expected, i'd try clickhouse cli

**Comment by dantengsky** [comment]
> this is the output by clickhouse-client:
> ...

does execution by clickhouse-client killed by OOM killer?

**Comment by flaneur2020** [comment]
yes, the databend-query process finally get killed by OOM killer, but it lives quite longer (7~10s) than the mysql one (2~3s)

**Comment by flaneur2020** [comment]
the both memory trace just displays the main source of memory allocation is the DataBlock, but in the streamed pulling fashion, the produced DataBlock is expected to be released as the a chunk of the result get pulled out.

during the profiling, the memory increases until get OOM killed:

https://user-images.githubusercontent.com/129800/179000934-a2f20dcc-ca6f-41b8-a53e-93ef322d56f5.mov

**Comment by dantengsky** [comment]
> yes, the databend-query process finally get killed by OOM killer, but it lives quite longer (7-10s) than the mysql one (2-3s)

would you please change the 

`clickhouse-client --query="select * from ontime" --port 9091 &`

to 

`clickhouse-client --query="set max_threads = 1; select * from ontime" --port 9091 &`

and give it another try? (no need jeprof, just test if OOM killer kicks in)

**Comment by sundy-li** [comment]
This is OOM Killed too.
```
echo "set max_threads = 1; SELECT number + 1, number + 2, number + 3, number + 4, number + 5, number + 6, number + 7, number + 8, number + 9, number + 10, number + 11, number + 12, number + 13, number + 14, number + 15, number + 16, number + 17, number + 18, number + 19, number + 20 from numbers(500000000) format CSV" |  clickhouse-client -m -n  > ~/a.csv 2>&1

```

**Comment by flaneur2020** [comment]
> 

it also get OOM Killed with set max_threads = 1

**Comment by dantengsky** [comment]
> it also get OOM Killed with set max_threads = 1

roger & thanks.

**Comment by sundy-li** [comment]
Task list update.
