### ISSUE TITLE
bug: creating table contains two same column name should not success

### ISSUE THREAD

**Issue by yuuch** [datafuselabs/databend#6564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

7cbc1c57f445f4e0b789d4e06b0d9db1fa341414

### What's Wrong?

I create a table which contains two columns have the same `name`. I think it should report  the error message, while creating table, but not later (such as select from this table).

### How to Reproduce?

```shell
mysql> create table tt (i INT, i String) ENGINE = Memory;
Query OK, 0 rows affected (0.07 sec)

mysql> desc tt;
+-------+---------+------+---------+-------+
| Field | Type    | Null | Default | Extra |
+-------+---------+------+---------+-------+
| i     | INT     | NO   | 0       |       |
| i     | VARCHAR | NO   |         |       |
+-------+---------+------+---------+-------+
2 rows in set (0.03 sec)
Read 0 rows, 0.00 B in 0.011 sec., 0 rows/sec., 0.00 B/sec.
```
But it report error, while I select data from it.

```shell
mysql> select * from tt;
ERROR 1105 (HY000): Code: 1006, displayText = Unable to get field named "1". Valid fields: ["0"].
mysql> select i from tt;
ERROR 1105 (HY000): Code: 1065, displayText = error:
  --> SQL:1:8
  |
1 | select i from tt
  |        ^ column reference is ambiguous

.

```
It should have reported the error when creating table.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
This issue happens in v2 cc @leiysky

**Comment by yuuch** [comment]
> This issue happens in v2 cc @leiysky

It happens both v2 and the old planner. But at that moment, I am using the new planner :)

For the old planner: 

```shell
mysql> create table ttt (i INT, i STRING) ENGINE = Memory;
Query OK, 0 rows affected (0.06 sec)

mysql> select * from ttt;
ERROR 1105 (HY000): Code: 1015, displayText = Logical error: same columns in ["default", "db1", "ttt"], this is a bug..
```

**Comment by BohuTANG** [comment]
Thanks for taking this issue @yuuch 

The `help bot` is offline :\

**Comment by johnhaxx7** [comment]
Hi, I think this is fixed by https://github.com/datafuselabs/databend/commit/c7bee273422d9691b749037577df7e83917068a2
```
mysql> create table tt (i INT, i String) ENGINE = Memory;
ERROR 1105 (HY000): Code: 1006, displayText = Duplicated column name: i.
```
should be good to close.

**Comment by xudong963** [comment]
thx
