### ISSUE TITLE
`value_source_v2` shoud sync with `value_source`

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6569]
`value_source_v2` shoud sync with `value_source`? In this transitional stage, all changes in `value_source` may be lost in `value_source_v2`. 

How can we guarantee it sync?

cc @sundy-li

_Originally posted by @fkuner in https://github.com/datafuselabs/databend/issues/6565#issuecomment-1181216624_

**Comment by Xuanwo** [comment]
Do we still use `value_source`? How about removing it entirely?

**Comment by fkuner** [comment]
> Do we still use `value_source`? How about removing it entirely?

We can't remove it now. Becaluse `insert` in old planner used it and `value_source` needs `sqlparser` to reparse when values have expression such as `1+1`.

**Comment by Xuanwo** [comment]
Cc @leiysky @andylokandy 

Maybe we can remove it while we are removing the old planner?
