### ISSUE TITLE
Improve performance of aggregate function distinct

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6594]
**Summary**

Description for this feature.

It's very slow to get distinct results even for one column.
```
databend > select count(distinct number) from numbers_mt(1000000);
+------------------------+
| count(distinct number) |
+------------------------+
|                1000000 |
+------------------------+
1 row in set (0.658 sec)
```

We can have specific aggregate states for commonly used columns.

**Comment by Kikkon** [comment]
🤔 Does 'commonly used columns' refer to a system table like system.numbers?

**Comment by sundy-li** [comment]
> Does 'commonly used columns' refer to a system table like system.numbers

No, the above SQL is just a simple case.


Now `AggregateDistinctState` used Vec<enum> to represent the state, this is inefficient.
```
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Hash, Clone)]
struct DataGroupValues(Vec<DataGroupValue>);

pub struct AggregateDistinctState {
    set: HashSet<DataGroupValues, RandomState>,
}
```

1. If the aggregation is to have the distinct values of primitive columns, we can have a special state like:

```
pub struct AggregateDistinctPrimitiveState<T: PrimitiveType> {
    set: HashSet<T, RandomState>,
}
```

2. If the aggregation is to have the distinct values of String columns, we can have a special state like:


```
pub struct AggregateDistinctStringState {
    set: HashSet<Vec<u8>, RandomState>,
}
```

...

**Comment by sundy-li** [comment]
@Kikkon  Hello, how is this going?   Do you need some help?

**Comment by Kikkon** [comment]
@sundy-li  Thanks for your concern.  I have been busy with work recently and I'm currently trying to do optimization for u64. I wonder that if implementing all types is a bit ugly, could I rewrite the implementation as a macro? Is there any suggestion?

**Comment by sundy-li** [comment]
> I wonder that if implementing all types is a bit ugly

You do not need implementing all types. From zero to one I suggest to cover primitive types & String Type, for other types(or distinct col larger than 1) we can fallback to using this DataGroupValues.

You can refer to `try_create_aggregate_minmax_function`.

**Comment by sundy-li** [comment]
It's done now.
