### ISSUE TITLE
slient the logs in the sqlogictest

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6596]
**Summary**

currently the sqlogic test's log is pretty big, causes hard to found the error in the github action's UI like: https://github.com/datafuselabs/databend/runs/7313929749?check_suite_focus=true

in this case, we can easily found the root cause is 'CURRENT_TIMESTAMP' in the tail of the logs output, but the log is 10mb, causing the github action UI can not easily display the output.

this is the output of a sqlogic test:

[3_Run ..githubactionstest_sqllogic_standalone_linux.txt](https://github.com/datafuselabs/databend/files/9098946/3_Run.githubactionstest_sqllogic_standalone_linux.txt)

the stateless tests only displays the test files which get executed, and SUCCESS/FAILURE about each test file. but sqlogictest displays every output of every statement, thus makes the output pretty large.

we can consider only display success/failure result of each sqlogictest file, with the output of the failed case.

**Comment by flaneur2020** [comment]
cc @ZeaLoVe

**Comment by flaneur2020** [comment]
this is the log output of the stateless test:

![Screen Shot 2022-07-14 at 10 57 56 AM](https://user-images.githubusercontent.com/129800/178888492-8da36496-1d86-48eb-8ab1-13a81a57d641.png)

it's an aggregated result in the file manner, I think we can consider a similiar representation.

**Comment by ZeaLoVe** [comment]
As the #6680 merged,  decrease half of the total logs in logic test ci.
