### ISSUE TITLE
Refactor: Disable `TransformBlockCompact` during the insert pipeline

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#6600]
**Summary**

Description for this feature.

I think it's better to remove `TransformBlockCompact` during the insert pipeline. 

It caches too much memory. We can compact the blocks in background threads #6492 

cc @dantengsky

**Comment by dantengsky** [comment]
roger.

I suggest keeping the transform, till #6492 is ready. meanwhile, I'll try to add some constraints to the parallelism of compaction.
