### ISSUE TITLE
Feature: limit the parallelism of reading S3 files

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#6603]
**Summary**

https://github.com/datafuselabs/databend/commit/f9c68cd4b042eeaf913297e0629572740b1b69ee#r78376449

This is interesting. we may consider introducing priorities for read tasks.

feature request from: @sandflee

**Comment by Xuanwo** [comment]
Related to https://github.com/datafuselabs/opendal/issues/441

As suggested by @zhang2014, seems we need a connection pool for our client.

**Comment by Xuanwo** [comment]
max_io_requests has been added.
