### ISSUE TITLE
bug:  load parquet data to databend failed  if had timestamp  columns

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#6627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

80e09b30c1d5bbdcfdc244c997a10374fd797257

### What's Wrong?

could't load parquet data to databend

### How to Reproduce?

1. create table with sql "create table mytime(id string, t_bool boolean, t_float float, t_double double,  t_timestamp timestamp, t_data date, t_array array(int));"
2. load parquet data,    curl -XPUT 'http://root:@127.0.0.1:8081/v1/streaming_load' -H 'insert_sql: insert into mytime format Parquet' -F 'upload=@"./mytime.parquet"'

parquet data:  https://github.com/sandflee/databend/blob/parquet/mytime.parquet

 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sandflee** [comment]
databend transfrom timestamp to int64 arrow type,  while the phiscal type of "t_timestamp" in parquet is int96,  this may cause the error,  any advise?

**Comment by sundy-li** [comment]
Oh, databend's timestamp is always int64.  But parquet may have `int96` timestamp.   
There is [a method]( https://github.com/jorgecarleitao/arrow2/blob/f57dbd5dbc61b940a71decd5f81d0fd4c93b158d/src/io/parquet/read/deserialize/simple.rs) to handle this, maybe we should map timestamp to arrow2's timestamp datatype.
Let me find a way to fix this.

**Comment by sandflee** [comment]
using arrow::timestamp seems  reasonable, could compatible parquet int64 and int96
