### ISSUE TITLE
bug: InSubquery returns error result

### ISSUE THREAD

**Issue by fkuner** [datafuselabs/databend#6628]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

c774f800d5e458062c5204d7822668125ff66ba9

### What's Wrong?

```
mysql> select * from numbers(10) where number in (select * from numbers(5)) order by number;
+--------+
| number |
+--------+
|      0 |
|      1 |
|      4 |
|      5 |
|      6 |
+--------+
5 rows in set (0.03 sec)
Read 15 rows, 120.00 B in 0.008 sec., 1.9 thousand rows/sec., 14.81 KiB/sec.
```

The result should be `0 1 2 3 4`.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fkuner** [comment]
cc @xudong963

**Comment by sundy-li** [comment]
related to method `mark_join_blocks`. I think it's incorrect to call `build_indexes.extend_from_slice` .
