### ISSUE TITLE
Feature: Add support for `LIST '@"my_stage"'`

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6630]
As snowflake note:
```
If the stage name or path includes spaces or special characters, it must be enclosed in single quotes (e.g. '@"my stage"' for a stage named "my stage").
```

https://docs.snowflake.com/en/sql-reference/sql/list.html

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/6624#issuecomment-1184307191_

**Comment by Xuanwo** [comment]
Cc @andylokandy, Please give me some advice.

`AtString` token only supports `@my_stage` now.

**Comment by andylokandy** [comment]
@Xuanwo We can add a token `QuotedAtString`, and a parser to extract the inner string from either `QuotedAtString` or `AtString`.
