### ISSUE TITLE
Support Timestamp, Date, Interval in new expression framework

### ISSUE THREAD

**Issue by andylokandy** [datafuselabs/databend#6635]
`Date` shares the same value type as `i32`, when `Interval` and `Timestamp` shares the one as `i64`. Therefore the tasks are simpler because we don't need to add value varients for `Scalar` and `Column`:

1. Add logical type `DataType::{Timestamp, Date, Interval}`.

2.  
   a. Add generic type `common_expression::types::number::{TimestampType, DateType, IntervalType}`, and implement `Number` trait for them. This is the current strategy using in `common_functions`.

   b. An alternative is to add the generic types `common_expression::types::{TimestampType, DateType, IntervalType}`, and implement `ValueType` and `ArgType` trait for them. In this way, we would introduce more duplicated code, but also unlocked the possibility to decorate the scalar to be more informative types like `std::duration::Duration` or something alike in `chrono`. cc @sundy-li 

3. Add `can_cast_to` rule and `Evaluator::cast` rule between temporal types and native number types.

**Comment by PsiACE** [comment]
I am interested in the new expression framework and would like to have a try.

**Comment by RinChanNOWWW** [comment]
Is someone working on `Date` and `Interval` now? If no, I can help to implement them.

**Comment by RinChanNOWWW** [comment]
How about not creating `common_expression::types::{DateType, IntervalType}`, but using number types directly?
