### ISSUE TITLE
Support UInt32, UInt64, Int32, Int64, Float32, Float64 in new expression framework

### ISSUE THREAD

**Issue by andylokandy** [datafuselabs/databend#6636]
There are three places new data types need to be implemented:

1. `common_expression::types::DataType`, which stores all logical data types. Since new logical data types are defined, you would like to see `common_expression::type_check::{can_cast_to, common_super_type}` to add coressponding casting rules.
2. `common_expression::values::{Scalar, ScalarRef, Column}`, which stores physical data values. And then runtime casting need to be added to `common_expression::evaluator::Evaluator::run_cast()`, which should excatly following the rules defined in `can_cast_to`.
3. `common_expression::types:::number::Number` trait, for allowing to use them in static generics API.

**Comment by jiaoew1991** [comment]
Hi @andylokandy I will try this issue

**Comment by andylokandy** [comment]
@jiaoew1991 Thank you. I've added some instructions for the task. Feel free to ask if you find anything puzzling.

**Comment by jiaoew1991** [comment]
the float32 float64 have not finished yet，should reopen it
