### ISSUE TITLE
unify input/output formats

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#6642]
**Summary**

- [x] add TSV https://github.com/datafuselabs/databend/issues/6555
- [x] fix TSV https://github.com/datafuselabs/databend/issues/6650
- [x] https://github.com/datafuselabs/databend/issues/6669
- [ ]  refactor InputState
- [ ]  pass buffer between processor without SharedData?
- [ ]  unify setting/options
- [x] Add test for TSV
- [ ] deal with size limit https://github.com/datafuselabs/databend/issues/6653
- [x] https://github.com/datafuselabs/databend/issues/6454
- [x]  carry file name/first_row/offset in the split, for error msg
- [ ]  https://github.com/datafuselabs/databend/issues/6722

**Comment by Xuanwo** [comment]
Add new task: Add test for TSV

**Comment by youngsofun** [comment]
add task: https://github.com/datafuselabs/databend/issues/6669

**Comment by youngsofun** [comment]
move to https://github.com/datafuselabs/databend/issues/7732
