### ISSUE TITLE
Feature: Cost-based optimization(CBO)

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6643]
Support cost-based optimization.

Need RFC.

**Comment by sandflee** [comment]
is there any process about CBO?

**Comment by leiysky** [comment]
> is there any process about CBO?

I'm working on this in recent days, there will be an initial implementation in early September as expected.

**Comment by sandflee** [comment]
cool!  is there any design docs or rfc?

**Comment by leiysky** [comment]
> cool! is there any design docs or rfc?

There was a rfc about the whole planner framework. https://github.com/datafuselabs/databend/blob/main/docs/doc/60-contributing/03-rfcs/20210914-new-sql-planner-framework.md

**Comment by sandflee** [comment]
after #7187 , could we support auto choose join type (shuffle join&broadcast join) and join order?

**Comment by xudong963** [comment]
@sandflee No, but on the way
