### ISSUE TITLE
Bug: `assertion failed: !column.is_empty().` when using `CASE WHEN` on empty `DataBlock`

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6682]
Only can be reproduced in debug build:
```sql
select case when number > 1 then 1 when number < 1 then 2 else 1 end from numbers(2) where false;
```

Which is caused by the `debug_assertion` [here](https://github.com/datafuselabs/databend/blob/a2cac3b10af29fd25fad65b749c46abe35392f1a/common/datavalues/src/scalars/viewer.rs#L128)

**Comment by leiysky** [comment]
cc @sundy-li

**Comment by xudong963** [comment]
https://github.com/datafuselabs/databend/issues/6659 same reason
