### ISSUE TITLE
Calculate query time cost in logic test

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6694]
### Summary

As more test cases added to logic test pipeline, any degration will cause a longer time to finish test. I think it is a good idea to
caculate query time cost in logic test, expecially average time cost of each sql in a suite file and total time cost of a suite file.

**Comment by flaneur2020** [comment]
i guess this issue can also be tracked in the tracking issue #5889

**Comment by ZeaLoVe** [comment]
> i guess this issue can also be tracked in the tracking issue #5889

hmmm.. the tracking issue focused on test coverage, this one is a experience improvement.

**Comment by Xuanwo** [comment]
> hmmm.. the tracking issue focused on test coverage, this one is a experience improvement.

Thus, please create another tracking issue for those issues.
