### ISSUE TITLE
Improve the SQL Logic Test Output

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6696]
Can we improve the output?

```shell
    results: [(<re.Match object; span=(0, 4), match='----'>, 215, '1680 222 1 112.0 674\n1826 222 1 122.0 738\n1902 222 4 127.0 760\n1985 333 4 132.0 793\n2046 222 2 137.0 827\n2202 444 2 147.0 880\n2281 333 1 152.0 905\n2432 444 1 162.0 966\n2501 333 1 167.0 1000\n2654 444 1 177.0 1057\n2728 333 3 182.0 1096\n3175 333 3 212.0 1277\n3331 222 1 222.0 1338\n3473 333 1 232.0 1391\n3553 444 1 237.0 1416\n3706 111 2 247.0 1484')],
    runs_on: {'clickhouse', 'mysql', 'http'},
```

I expect to read:

```shell
Expected:

xxx

Actual:

xxx
```

It could be better in diff-style.

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6681#issuecomment-1188626717_

**Comment by ZeaLoVe** [comment]
> ------------ Error Statement details ------------
>  Expected:
> 2021-08-30 18:47:42.000000
>  Actual:
>   2021-08-30 10:47:42.000000

Actual format as right aligned, but expected not .
