### ISSUE TITLE
SQL logic test is too slow that exceeds 10 minutes limitation

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6697]
SQL logic test is too slow that exceeds 10 minutes limitation.

We can extend this limitation to 20 or 30 minutes, but we should improve this in the future.

I expect SQL logic tests could be finished within 10 minutes (maybe we can execute them concurrently)?

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6681#issuecomment-1189028385_

**Comment by ZeaLoVe** [comment]
Relate to debug build in ci workflow, with release build only need about 4min to run.
So we can split logictest workflow into multi parts, like stateless, ydb, crdb ...
