### ISSUE TITLE
check type cast in  create table as select.

### ISSUE THREAD

**Issue by yuuch** [datafuselabs/databend#6706]
`CREATE TABLE t (d DATE) AS SELECT i, d FROM date_t`

need to check type cast.

If the data types of coulumn definition is incompatible with the select result, we may need to raise an error for that.

_Originally posted by @leiysky in https://github.com/datafuselabs/databend/pull/6618#discussion_r921824569_

Some situation, it will meet bugs , Casting `String` to `Date` will failed. 
```sql
mysql> create table t1 (i INT, d String);
Query OK, 0 rows affected (0.09 sec)

mysql> insert into t1 values (1, 'hello');
Query OK, 0 rows affected (0.07 sec)

mysql> create table t2 (j INT, d Date) as select * from t1;
ERROR 1105 (HY000): Code: 1010, displayText = Cast error happens in casting from String to Date (while in processor thread 0).
mysql> drop table t2;
Query OK, 0 rows affected (0.06 sec)

mysql> set enable_planner_v2=1;
Query OK, 0 rows affected (0.03 sec)

mysql> create table t2 (j INT, d Date) as select * from t1;
ERROR 1105 (HY000): Code: 1010, displayText = Cast error happens in casting from String to Date (while in processor thread 0).


mysql> show tables;
+----------------+
| tables_in_db20 |
+----------------+
| t1             |
| t2             |
+----------------+
2 rows in set (0.06 sec)
Read 30 rows, 4.07 KiB in 0.032 sec., 923.82 rows/sec., 125.40 KiB/sec.
```

table `t2` shouldn't be created.

I will fix it ASAP.

**Comment by yuuch** [comment]
https://github.com/datafuselabs/databend/blob/a60b88f38dd3fe49dbd3e189942a8bbba05c963b/common/functions/src/scalars/expressions/cast.rs#L83-L90


There is no `ColumnsWithField` in the binder stage, it is not a good way to eval the cast function here. Consequently, we can  catch the error in the interpreter and drop the table created.

**Comment by BohuTANG** [comment]
I think we have check now:
```
create table t2 (j INT, d Date) as select * from t1;
1006=>cannot parse to type `DATE` while evaluating function `to_date('hello')`
```
