### ISSUE TITLE
Add glob support for COPY

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6714]
> By the way, can we support set/range path pattern for s3-like scheme? PATTERN = 'regex_pattern' is not friendly for the user which document in https://databend.rs/doc/reference/sql/dml/dml-copy-into-table

Interesting idea, maybe we can add `GLOB='[100-200]'` or `GLOB_PATTERN='[100-200]'` in SQL.

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/issues/6691#issuecomment-1190332942_

**Comment by BohuTANG** [comment]
It would be great to support glob set/range pattern in the path as https scheme did.
