### ISSUE TITLE
COPY from public website seems really slow

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6722]
**Summary**

COPY from the public website seems slow

`https://repo.databend.rs/dataset/stateful/ontime_2006_100000.csv` is 41.8 MiB.

```shell
:( curl https://repo.databend.rs/dataset/stateful/ontime_2006_100000.csv -o /tmp/test.csv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.8M  100 41.8M    0     0  5231k      0  0:00:08  0:00:08 --:--:-- 8574k
```

But this query seems to hang forever:

```sql
copy into ontime200 from 'https://repo.databend.rs/dataset/stateful/ontime_2006_100000.csv'     
    FILE_FORMAT = (type = 'CSV' field_delimiter = ','  record_delimiter = '\n' skip_header = 1);
```

---

To address this problem:

- [ ] Add more debug log for file splitter
- [ ] Profile COPY

**Comment by BohuTANG** [comment]
repo.databend.rs is dns&proxy by Cloudflare. Is it related to this? cc @everpcpc @flaneur2020

**Comment by Xuanwo** [comment]
> repo.databend.rs is dns&proxy by Cloudflare. Is it related to this? cc @everpcpc @flaneur2020

I think it's a databend-query's problem.

**Comment by BohuTANG** [comment]
Seems we should add more metrics to do the profile, like the copy progress rasing from the openDAL.

**Comment by flaneur2020** [comment]
I guess we can add some metrics in the COPY progress, e.g. bytes read from source, bytes ingested

**Comment by Xuanwo** [comment]
Yep, let's do this. 

I have added mostly the features I wanted in COPY, it's time to improve the performance.

**Comment by Xuanwo** [comment]
Based on my local test, the bottleneck is the insert part.

We spent less than 1s to read 1MB of data from the source but need about 13s to start the next round of reading.

**Comment by Xuanwo** [comment]
Maybe related to https://github.com/datafuselabs/opendal/pull/474

Please give a try after merged.

**Comment by Xuanwo** [comment]
The performance has been dramatically improved by https://github.com/datafuselabs/databend/pull/6873

Thanks, @youngsofun. Let's close.
