### ISSUE TITLE
Track：All flaky error in test

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6733]
### Summary

I think we need this tracking issue to record all flaky error in sqllogic test. 
If your pr checks failed with something not related to your changes, you can check following list, if you encounter a different problem, leave a comment.

### Tasks

- [x]  https://github.com/datafuselabs/databend/issues/6614
- [x] https://github.com/datafuselabs/databend/issues/6730

**Comment by Xuanwo** [comment]
Any updates on this?

**Comment by ZeaLoVe** [comment]
> Any updates on this?

No more flaky errors, let us close it for now.
