### ISSUE TITLE
Feature: Decimal data type support for currency fields

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#6745]
**Summary**

for storing money in databend

**Comment by sundy-li** [comment]
It can be addressed in #6547

**Comment by youngsofun** [comment]
I already did some investigation after taking this issue https://github.com/datafuselabs/databend/issues/2931
I planned to add it after plan v2 is applied and new type systems are used.
@sundy-li do you mean we can add it now in `common-expression` first?

**Comment by sundy-li** [comment]
> do you mean we can add it now in common-expression first?

Yes, we can add it now, it may take some time to make it to production.

**Comment by BohuTANG** [comment]
Will databend support int128 firstly?

**Comment by youngsofun** [comment]
> Will databend support int128 firstly?
yes

**Comment by youngsofun** [comment]
dup with https://github.com/datafuselabs/databend/issues/2931， close it
