### ISSUE TITLE
Slow on loading hits data in TSV format

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#6751]
**Summary**

the query:

https://github.com/datafuselabs/databend-perf/pull/88/files#diff-a6818def0f6d7c3398474f8582833128c941fa68d8d323dca5a34e8db05d44ecR118

![Screen Shot 2022-07-22 at 2 38 19 PM](https://user-images.githubusercontent.com/129800/180378685-efaaf69c-a3fb-4b89-a3a5-1b8b8e17be4c.png)

302kb/s not a quick speed.

![Screen Shot 2022-07-22 at 2 39 11 PM](https://user-images.githubusercontent.com/129800/180378831-de59454a-b5a3-427a-b319-bebf1c60ad7b.png)

the CPU could be fully utilized (800% in a 8c instance), however only one instance in an 8 instances cluster is utilized.

**Comment by flaneur2020** [comment]
loading the ontime dataset is also dog slow:

![Screen Shot 2022-07-22 at 2 51 15 PM](https://user-images.githubusercontent.com/129800/180380864-f5ccc40e-d768-45ea-8ab8-cb3a0401c47b.png)

**Comment by Xuanwo** [comment]
seems related to https://github.com/datafuselabs/databend/issues/6722

**Comment by flaneur2020** [comment]
is this issue resolved? the ontime load seems get a bit quicker
