### ISSUE TITLE
Feature: support download server logs in ci

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#6781]
**Summary**

After CI runs, we should collect the server logs, archive and upload them to S3, and provide download.
CC: @Xuanwo @everpcpc

**Comment by Xuanwo** [comment]
For some actions, we will have `upload_artifacts` to do that:

https://github.com/datafuselabs/databend/blob/cd20049a3ce8eb9f67f418265f41f2a218afbf96/.github/actions/test_stateless_cluster_linux/action.yml#L30-L34

We can get them via Artifacts:

https://github.com/datafuselabs/databend/actions/runs/2717528935


![image](https://user-images.githubusercontent.com/5351546/180592662-e056db83-a194-47dd-9aa7-f5b51ebac4ab.png)

So far, we collected:

https://github.com/datafuselabs/databend/blob/main/.github/actions/artifact_failure/action.yml#L13-L23

Does these enough?

**Comment by zhang2014** [comment]
> Does these enough?

Ok. let's close this.
