### ISSUE TITLE
bug: unexpect error on http handler

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#6797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.7.140

### What's Wrong?

While migration stateless test 02_function in this https://github.com/datafuselabs/databend/pull/6795
This SQL in http handler get error: SELECT (1, 'a', NULL, to_date(18869), (2.1, to_datetime(1630320462000000)));

![p0LEdulBFL](https://user-images.githubusercontent.com/10904090/180707819-aead0b0c-bb7e-4003-8bbc-aed225977f08.jpg)

but mysql handler is ok.

![5ywvmJ7OUF](https://user-images.githubusercontent.com/10904090/180707919-08e4256d-fcbe-417b-baaa-1d1924b9d3cb.jpg)

cc @youngsofun  I just skip that, please take a look.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
@b41sh @leiysky @sundy-li  is there any recent changes about the planner that forgot applied to the http handler

**Comment by sundy-li** [comment]
Fixed at pr #6795.

commit https://github.com/datafuselabs/databend/pull/6795/commits/1ee45ee2dd2ebdfecd3c2fe18db021612271fcba
