### ISSUE TITLE
Deploy should add how to create user and connection

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6808]
**Summary**

https://databend.rs/doc/deploy/deploying-databend#verifying-deployment

We don't let users use the root account, root is only used for localhost, we should guide them to create a new user and connect.

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by rahul3002** [comment]
If this issue is open, I'd love to tackle it head-on!

**Comment by PsiACE** [comment]
> If this issue is open, I'd love to tackle it head-on!

https://databend.rs/doc/deploy/deploying-databend 

We have added relevant content to the document and thank you for your interest in it.
