### ISSUE TITLE
feat: MySQL client `COPY INTO` returns status 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6811]
**Summary**

```
CREATE TABLE IF NOT EXISTS blocks
(
    number            BIGINT UNSIGNED,
    hash              STRING,
    parent_hash       STRING,
    nonce             STRING,
    sha3_uncles       STRING,
    logs_bloom        STRING,
    transactions_root STRING,
    state_root        STRING,
    receipts_root     STRING,
    difficulty        STRING,
    total_difficulty  STRING,
    size              BIGINT UNSIGNED,
    extra_data        STRING,
    gas_limit         BIGINT UNSIGNED,
    gas_used          BIGINT UNSIGNED,
    timestamp         BIGINT UNSIGNED,
    transaction_count BIGINT UNSIGNED,
    base_fee_per_gas  BIGINT UNSIGNED
);

mysql> copy into eth.blocks from 'https://databendcloud-1253727613.cos.ap-singapore.myqcloud.com/eth/3090000_3099999/blocks.parquet' FILE_FORMAT = (type = 'PARQUET');
Query OK, 0 rows affected (7.56 sec) -- should 10000 rows affected

```

**Comment by Weijun-H** [comment]
\assignme

**Comment by Weijun-H** [comment]
Hi,

I am working on this issue. I started by writing a test to get the return status, but do not know how to get it. I understand the process to get the query result. However, how could we test the return status of mysql?

**Comment by BohuTANG** [comment]
Maybe we can check it from python client?

**Comment by Weijun-H** [comment]
> Maybe we can check it from python client?
In `client.py`, it only provide `run` and `run_with_output` functions. We cannot not get status from them.

**Comment by sundy-li** [comment]
> We cannot get the return status from them.

Yes, it's hard to test it via other clients. This is the only behavior of `mysql` client.

**Comment by BohuTANG** [comment]
We can skip the test :)

**Comment by Weijun-H** [comment]
> > We cannot get the return status from them.
> 
> Yes, it's hard to test it via other clients. This is the only behavior of `mysql` client.
> 
> We should modify the method `finish_with_info` in opensrv to inject the `affected_rows ` field. https://github.com/datafuselabs/opensrv/blob/e15f820f1e35ab33ce113c27878258850d1f272a/mysql/src/lib.rs#L76
> 
> Maybe we could have a wrapped struct:
> 
> ```
> Extras {
>   extra_info: String,
>    affected_rows: usize,
>   ...
> }
> 
>  pub fn finish_with_info(self, extras: &Extras) -> io::Result<()> { }
> ```

Is it the approach for test or fix?

**Comment by sundy-li** [comment]
> Is it the approach for test or fix?
For fix.

**Comment by sherlockbeard** [comment]
not able to reproduce it with mysql client . #7022 fixed this.
i believe good to close
