### ISSUE TITLE
bug: new planner tranformation not work in http handler

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#6817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.142-nightly

### What's Wrong?

COPY INTO blocks FROM '<some parquet url>' FILE_FORMAT = (type = 'parquet');

1005: File location uri unsupported, must be one of [s3]

### How to Reproduce?

Mysql handler works, only http handler and clickhouse http handler not work

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
In the MySQL handler, all query to `COPY` has been forwarded to the new planner. But HTTP handler doesn't;

**Comment by Xuanwo** [comment]
cc @youngsofun

**Comment by sundy-li** [comment]
Is that deployed using cluster mode?

**Comment by youngsofun** [comment]
@ZhiHanZ I did not reproduce the error `1005: File location uri unsupported, must be one of [s3]` 
cc @Xuanwo

**Comment by flaneur2020** [comment]
> Is that deployed using cluster mode?

yes, the workload is deployed in a kubernetes statefulset
