### ISSUE TITLE
Add load data doc from copy into ... from files by http url file

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6830]
**Summary**

Add a new load data method 'from file by http url' to 
https://databend.rs/doc/load-data

Reference:
https://databend.rs/doc/reference/sql/dml/dml-copy-into-table-url

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by Xuanwo** [comment]
Helpful references: https://github.com/datafuselabs/databend/pull/6691

**Comment by rahul3002** [comment]
If this issue is open, I'd love to tackle it head-on!

**Comment by PsiACE** [comment]
> If this issue is open, I'd love to tackle it head-on!

https://databend.rs/doc/load-data/load/http
