### ISSUE TITLE
blog: introduce how to load data to databend

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#6860]
**Summary**

It would be nice to have a new blog post about how to(/how many ways) ingest data to databend.
Load data reference:
https://databend.rs/doc/load-data

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by rahul3002** [comment]
If this issue is open, I'd love to tackle it head-on!

**Comment by PsiACE** [comment]
> If this issue is open, I'd love to tackle it head-on!

Wow, I think this will be a good start. If you are willing to write something, I can assign it to you.

**Comment by rahul3002** [comment]
Alright, my friend, listen up! I'm all set to write a fantastic blog, but here's the thing: I'm scratching my head wondering where to share it.

**Comment by rahul3002** [comment]
I'm gonna post this blog on Dev.to and Hashnode. I'm gonna whip up a fantastic blog, and you can bet your bottom dollar it'll be ready by tomorrow evening. Once it's done, I'll shoot you the document, and we'll review it togethe

**Comment by rahul3002** [comment]
here is the link: https://doc.clickup.com/9002042687/p/h/8c90h9z-724/13dc88606497c91

Hey there, I'd greatly appreciate your expert eyes on my blog post! 

Let me know what tweaks and improvements you reckon it needs. 

Your feedback means the world to me!

**Comment by BohuTANG** [comment]
https://docs.databend.com/guides/load-data/
