### ISSUE TITLE
Feature: LIMIT push down for new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6865]
In some cases, it's possible to push the `LIMIT` operator down to reduce the data to be processed.

Besides, `LIMIT` hint of `ReadDataSource` will affect the behavior of `Random` table engine.

**Comment by AngleNet** [comment]
@leiysky hi, is there any one working on this? I would like to pick this up.

**Comment by sundy-li** [comment]
Besides, LIMIT push down could affect the `Sort` Plan which has partial sort optimization.

```
#[derive(Clone, Debug)]
pub struct Sort {
    pub items: Vec<SortItem>,
+  pub limit: option<usize>
}
```

**Comment by AngleNet** [comment]
> Besides, LIMIT push down could affect the `Sort` Plan which has partial sort optimization.
> 
> ```
> #[derive(Clone, Debug)]
> pub struct Sort {
>     pub items: Vec<SortItem>,
> +   pub limit: option<usize>
> }
> ```

@sundy-li Hi. What do you mean `partial sort optimization`?

**Comment by sundy-li** [comment]
> @sundy-li Hi. What do you mean `partial sort optimization`?

https://github.com/datafuselabs/databend/blob/4d458914ab5e6fcf26d3c5fc74b830ef3c3a2d82/query/src/pipelines/pipeline_builder.rs#L381-L402

**Comment by leiysky** [comment]
@sundy-li Is it actually a `TopN` operator?

**Comment by AngleNet** [comment]
@sundy-li @leiysky Shall we implement a  TopN operator and convert an order followed by limit to a TopN operator and the limit could be pushed down further.

**Comment by leiysky** [comment]
@AngleNet I've just opened a issue https://github.com/datafuselabs/databend/issues/7015 for that.

**Comment by AngleNet** [comment]
Great! I think I could implement limit push down firstly and then introduce topn operator, refactor the limit push down to support topn finally. Is that ok?

**Comment by leiysky** [comment]
> Great! I think I could implement limit push down firstly and then introduce topn operator, refactor the limit push down to support topn finally. Is that ok?

That's good.
