### ISSUE TITLE
Bug: `trim(null)` will panic in new planner

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6876]
Error message:
```
mysql> set enable_planner_v2 = 1;
Query OK, 0 rows affected (0.02 sec)
mysql> select trim(null);
ERROR 1105 (HY000): Code: 1058, displayText = downcast column error, column type: "Null", expected column: "common_datavalues::columns::string::StringColumn" (while in processor thread 0).
```

**Comment by TianLangStudio** [comment]
Maybe we can return null when the argument is null------------------------------------------------------------------
发件人：Yu ***@***.***>
日　期：2022年07月28日 19:08:34
***@***.***>
***@***.***>
主　题：[datafuselabs/databend] Bug: `trim(null)` will panic in new planner (Issue #6876)

Error message:
mysql> set enable_planner_v2 = 1;
Query OK, 0 rows affected (0.02 sec)
mysql> select trim(null);
ERROR 1105 (HY000): Code: 1058, displayText = downcast column error, column type: "Null", expected column: "common_datavalues::columns::string::StringColumn" (while in processor thread 0).

**Comment by sundy-li** [comment]
```
 let box (trim_source, _) = self.resolve(expr, Some(StringType::new_impl())).await?;
        let args = vec![trim_source, trim_scalar];
        let func = FunctionFactory::instance()
            .get(func_name, &[&StringType::new_impl(); 2])
            .map_err(|e| ErrorCode::SemanticError(span.display_error(e.message())))?;

```

It's wrong to set `StringType::new_impl()`
