### ISSUE TITLE
Doc: update trim function related doc after enabling new planner

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#6884]
**Summary**
The syntax of `trim` between old planner and new planner is difference

So we need to update the doc after enabling new planner.

Old planner: https://databend.rs/doc/reference/functions/string-functions/trim

New planner:
```sql
select trim(leading ' ' from '      abc');

select trim(trailing ' ' from 'abc    ');

select trim(both 'ab' from 'abab');

select trim(' abc ');
```
The syntax is the same as https://www.w3resource.com/mysql/string-functions/mysql-trim-function.php

cc @soyeric128

**Comment by soyeric128** [comment]
Pls review https://github.com/datafuselabs/databend/pull/6960
