### ISSUE TITLE
New planner doesn't support `GRANT CREATE USER ON *.* TO '{}'@'{}'`

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6892]

**Comment by sundy-li** [comment]
We already support `GRANT CREATE ON *.* TO '{}'@'{}'`. So this is not an issue?

**Comment by Xuanwo** [comment]
> We already support `GRANT CREATE ON *.* TO '{}'@'{}'`. So this is not an issue?

Please close this issue and remove the related tests directly if so.
