### ISSUE TITLE
New planner doesn't support create table with select

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6894]
```rust
static TEST_CREATE_QUERY_SELECT: &str =
         "CREATE TABLE default.test_b(a varchar, x int) select b, a from default.test_a";
```

**Comment by leiysky** [comment]
The correct syntax of create table select is `CREATE TABLE default.test_b(a varchar, x int) AS select b, a from default.test_a`, we can modify the test case.

**Comment by Xuanwo** [comment]
We can update the test case:

https://github.com/datafuselabs/databend/blob/4443752e7fb0237ba33146e35b7ab201e50a9819/query/tests/it/interpreters/interpreter_table_create.rs#L65-L66
