### ISSUE TITLE
New planner doesn't support `SELECT from 'default'.'table'`

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#6903]
```sql
SELECT from 'default'.'table'
```

**Comment by leiysky** [comment]
When shall we use this?

It's not reasonable to have a query without result column. And besides, we are using double quote `"ident"` or back quote ``ident`` to represent identifiers.

**Comment by Xuanwo** [comment]
> When shall we use this?

No, they are just failed unit tests from the old planner.

If we don't intend to support a query like this, please just close as not planned.

**Comment by leiysky** [comment]
We have no plan to support this.
