### ISSUE TITLE
Feature: add io errors in meta metrics

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#6909]
**Summary**

Feature: add io errors in meta metrics

**Comment by flaneur2020** [comment]
how about also add a `metasrv_server_peer_rpc_failed` metric? which means the rpc errors among the peers.

we already have `metasrv_server_proposals_failed` metric which represents the errors in the  client side's view.

**Comment by lichuang** [comment]
> how about also add a `metasrv_server_peer_rpc_failed` metric? which means the rpc errors among the peers.
> 
> we already have `metasrv_server_proposals_failed` metric which represents the errors in the client side's view.

OK!
