### ISSUE TITLE
Feature: Columns of views in system.columns table

### ISSUE THREAD

**Issue by silentsokolov** [datafuselabs/databend#6922]
**Summary**

This will help to work with 3rd party libraries/IDEs.

```sql
CREATE TABLE t1(a INT UNSIGNED, b Varchar)
CREATE VIEW v1 AS SELECT * FROM t1;

SELECT
  name, database, table, type
FROM
  system.columns
WHERE table = 'v1';
```

**Comment by johnhaxx7** [comment]
Hi, I've been looking at this task and try to locate the cause. My understanding is, when a table is created, it's added to some metadata, and select `system.columns` will read from there, but I didn't find what's the cause.

 I'm thinking there might be some difference between `table_create` and `view_create` interpreter. I also looked at [columns_table.rs](https://github.com/datafuselabs/databend/blob/1ead3ef2b0554926044dfe7737518808d387d7ca/src/query/storages/system/src/columns_table.rs), [system_database.rs](https://github.com/datafuselabs/databend/blob/1ead3ef2b0554926044dfe7737518808d387d7ca/src/query/service/src/databases/system/system_database.rs), [schema_api_impl.rs](https://github.com/datafuselabs/databend/blob/1ead3ef2b0554926044dfe7737518808d387d7ca/src/meta/api/src/schema_api_impl.rs). 

Can someone share a hint on which module/file/function I should look at? Thank you!

**Comment by sundy-li** [comment]
View engine will not store the schema in meta. 

It just stored the query SQL.

See:  
1. CreateViewInterpreter
2. CreateViewPlan
