### ISSUE TITLE
Feature:  add resource quota

### ISSUE THREAD

**Issue by FANNG1** [datafuselabs/databend#6935]
now we use 'max_threads' to control cpu resource,  we should add other configs like 'max_query_time', 'max_mem'  to prevent bad sql ooms databend.  any plan to implement this?

- [x] max_execute_time(in millisecond) https://github.com/datafuselabs/databend/pull/7374
- [ ] max_memory_usage(in progress) https://github.com/datafuselabs/databend/pull/7290

**Comment by BohuTANG** [comment]
After the new processor and new planner tasks are finished, the resource quota task will start.

**Comment by BohuTANG** [comment]
Update:
Add a new setting `max_execute_time` to control max execution time(In milliseconds), you can set it for a session:
```
set max_execute_time=100;
```
or for a cluster:
```
set global max_execute_time=100;
```

cc @sandflee

**Comment by sandflee** [comment]
cool

**Comment by zhang2014** [comment]
`max_memory_usage` will be implemented in #7290, but it may take some time. at present, we can't track the memory usage accurately. We are try find  reasons.

**Comment by BohuTANG** [comment]
The memory limit and cpu and running queue all is supports.
