### ISSUE TITLE
Feature: tracing issue of share SQL support

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#6973]
**Summary**

Feature: tracing issue of share SQL support

- [x] #6974
- [x] #6998
- [x] #7043
- [x] #7104
- [x] #7144
- [x] #7180
- [x] #7269
- [x] #7639

**Comment by BohuTANG** [comment]
Great!

cc @soyeric128  for documenting the 🚀 `Data Sharing` feature, thanks.

**Comment by soyeric128** [comment]
Hi @lichuang , could you pls show me the new commands introduced by this feature ? 
Thanks.

**Comment by lichuang** [comment]
1. create and drop share.
```
create share test_share comment = 'comment';
DROP SHARE IF EXISTS test_share;
```
2. grant and revoke object.

```
grant USAGE on DATABASE show_shares TO SHARE test_share;
grant SELECT on TABLE show_shares.test_tb TO SHARE test_share;
```
3. alter share tenants
```
alter share test_share add tenants = 'a';
``` 
4. desc share
```
desc share test_share.
```
6. show shares
```
SHOW SHARES;
```
7. show grants on object and show grants of share_name 
```
show grants of share test_share;
show grants on DATABASE show_shares;
show grants on TABLE show_shares.test_tb;
```
9. create database from share 
```
create database db from share test_share.
```
