### ISSUE TITLE
ClickHouse http handler cannot report runtime error

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#6993]
For example:
```sql
create table t (a string);
insert into t values('abc');

select cast(a as int) from t; -- Error, cannot cast 'abc' into a integer
```

This query will throw error during execution, while `poem` has started streaming result to client. Because of this, client cannot get a reasonable error message but will get a `Connection reset` error.

**Comment by youngsofun** [comment]
it`s a known issue, 
 https://github.com/datafuselabs/databend/issues/6262

 I thought it happens in limited special cases, and is not blocking any other thing, so not fixed yet.

need to 

1.  return error like clickhouse.
2.  get parse error from clickhouse-sqlachelmy for logic test.

**Comment by leiysky** [comment]
> 2.  get parse error from clickhouse-sqlachelmy for logic test.

This is the problem I encountered.

Sometime we need to match the error code in logic test. If there is a runtime error, then the error code will be different between ClickHouse handler and the other handlers.

I'll remove error code matching for the affected test cases to get rid of this issue for now.

**Comment by youngsofun** [comment]
fixed by https://github.com/datafuselabs/databend/pull/7019
