### ISSUE TITLE
Remove docker image for logic tests

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7002]
**Summary**

It doesn't make sense to release an image for logic tests. We already have `dev-tools` to cover all depending on what is needed for logic tests.

Let's consider removing the docker images and its dockerfile for logic tests.

cc @everpcpc @ZeaLoVe @flaneur2020

**Comment by ZeaLoVe** [comment]
Any doc about dev-tools ? I know little about it.

**Comment by Xuanwo** [comment]
Cc @everpcpc for more information.

It's also a nice idea to provide a guide on how to use `dev-tools`.

**Comment by everpcpc** [comment]
I think maybe the logictest image is not tend to release test dependencies, but test cases for each release?
Then it is not suitable for build-tool image.

**Comment by Xuanwo** [comment]
> I think maybe the logictest image is not tend to release test dependencies, but test cases for each release?

Negative, please download the code from GitHub directly. We don't need to package them as an image.

```shell
wget https://github.com/datafuselabs/databend/archive/5739b3c2b53c87a6c304398ba4ad6e5e2cecc626.zip
```

**Comment by everpcpc** [comment]
> Negative, please download the code from GitHub directly. We don't need to package them as an image.
> 
> ```shell
> wget https://github.com/datafuselabs/databend/archive/5739b3c2b53c87a6c304398ba4ad6e5e2cecc626.zip
> ```

Yes, maybe we can release a separate tarball for test cases only.

**Comment by Xuanwo** [comment]
> Yes, maybe we can release a separate tarball for test cases only.

Our code is 16MiB. I think we need to add extra steps for that.

Simple is the best:

- Download code
- bend-tools python main.py

Simple, reliable, easy to understand, and no extra steps for releasing or packaging.

**Comment by everpcpc** [comment]
I think 16MiB is big enough for us to release a smaller test case package. Code and docs/website are not needed when we tend to do a logic test.

**Comment by everpcpc** [comment]
So when do we need to do a logic test outside github actions in this repo? @ZeaLoVe

**Comment by ZeaLoVe** [comment]
> So when do we need to do a logic test outside github actions in this repo? @ZeaLoVe

Only k3d test for now.

**Comment by everpcpc** [comment]
> It's also a nice idea to provide a guide on how to use `dev-tools`.

`build-tool` images are built for building & testing. And specially `build-tool:dev` is an all in one image for development with linux x86_64.
But is seems redundant with build toolchain when we only need to do a production ready sql logic test. Releasing a separate image makes it convenient for cloud platform with k3d tests(no need to install test dependencies again and again). But still, it is OK to separate an image with only test dependencies like `build-tool`, no need to publish it for every release.

**Comment by Xuanwo** [comment]
> But still, it is OK to separate an image with only test dependencies like `build-tool`, no need to publish it for every release.

`bend-dev` and `bend-test`?

**Comment by Xuanwo** [comment]
This issue is not valid anymore. Let's close.
