### ISSUE TITLE
Feature: Introduce `ConstTableScan` operator to accelerate table scan with no required columns

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#7014]
Sometimes, we have to read data from a table while none of the columns will be used in the query.

For example:
- `select count(*) from t`
- `select * from t where exists(select * from t1)`, none of column from `t1` will be used

To accelerate such queries, we can leverage with a new operator `ConstTableScan`, which will retrieve a dummy column for each row of data.

**Comment by leiysky** [comment]
cc @sundy-li

**Comment by sundy-li** [comment]
`system.zeros`
```
m1max.local :) select * from zeros limit 5;


┌─zero─┐
│    0 │
│    0 │
│    0 │
│    0 │
│    0 │
└──────┘

5 rows in set. Elapsed: 0.001 sec.
```
