### ISSUE TITLE
Remove `set enable_planner_v2 = 1` for documention

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7017]
**Summary**
After https://github.com/datafuselabs/databend/pull/6869 is merged, the documentation `set enable_planner_v2 = 1` is not needed, let's remove it.

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by Xuanwo** [comment]
Sorry to cc @soyeric128 again, can you take a check on this?

**Comment by soyeric128** [comment]
> Sorry to cc @soyeric128 again, can you take a check on this?

Hi, this issue was addressed by this PR: https://github.com/datafuselabs/databend/pull/7039

**Comment by BohuTANG** [comment]
Test also need to remove.
