### ISSUE TITLE
Feature: Add Google Cloud Storage backend support for databend

### ISSUE THREAD

**Issue by ClSlaid** [datafuselabs/databend#7023]
**Summary**

Currently, Databend does not support the Google Cloud Storage service

**Comment by BohuTANG** [comment]
Cool.
Related https://github.com/datafuselabs/opendal/issues/7

**Comment by ClSlaid** [comment]
Having accomplished [GCS support for OpenDAL](https://github.com/datafuselabs/opendal/issues/514), now awaiting its new publishment and continue work on DataBend!

**Comment by Xuanwo** [comment]
Implemented in https://github.com/datafuselabs/databend/pull/7171
