### ISSUE TITLE
`logictest` will mistake converting double quote `"` to single quote `'` in query when testing with http protocol

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#7027]
https://github.com/datafuselabs/databend/blob/43cbd00efd425c1c2eb42a1f3815282754b28873/tests/logictest/http_connector.py#L121-L129

cc @ZeaLoVe

**Comment by youngsofun** [comment]
I think we should not do manual escape here,   the SQL unchanged should remain after the JSON encode/decode, need to examine why we are relying on this escape now.

**Comment by ZeaLoVe** [comment]
> I think we should not do manual escape here, the SQL should remain unchanged after the JSON encode(client)/decode(server), need to examine why we are relying on this escape now.

The comments include some cases need this converting, maybe you can help to solve this, cc @youngsofun 

```
select "false"::boolean = not "true"::boolean;
SELECT parse_json('"false"')::boolean;  
```
