### ISSUE TITLE
logic test: classify the tests

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7087]
**Summary**

Currently, `20_0001_planner_v2` contains all kinds of tests, I think it's better to classify them.

I have picked join-related tests from `20_0001_planner_v2` to `join.test` in https://github.com/datafuselabs/databend/pull/7086

cc @ZeaLoVe

**Comment by ZeaLoVe** [comment]
LGTM, I think we can delete some repeat tests, and move related tests into a new test file.
Some test dependent on specific users and permissions needs to be split and skipped for some test scenario, for example.
select user(), currentuser(), current_user();
