### ISSUE TITLE
Feature: Add some implicit conversions

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7101]
**Summary**
Databend will eventually become a weak type like mysql, or a strong type like postgresql ?

Missing some implicit type conversions.
e.g
```sql
select (((+12.3123))OR(((1036270507)LIKE(1.123))));

ERROR 1105 (HY000): Code: 1007, displayText = Expected a string type, but got UInt32 (while in select before projection).
```
when t0.c0 is of type Boolean
```sql
t0.c0 BETWEEN 1517580277 AND 1356855360

Can not compare Boolean(Boolean) with UInt32(UInt32)
```
when t0.c1 is of type varchar
```sql
true < t0.c1

Code: 1007, displayText = Can not compare Boolean(Boolean) with String(String).
```
when t1.c0 is of type varchar
```sql
NOT t1.c0
 
Code: 1010, displayText = Cast error happens in casting from String to Boolean (while in processor thread 0).
```
when t13.c1 is Nullable(String)
```sql
-1257182980 IN (false, t13.c1)

Code: 1010, displayText = Cast error happens in casting from Nullable(String) to Int64 (while in processor thread 0).
```
when t0.c0 is of type int
```sql
select * from t0 where c0 IN(0,10,1.1);

ERROR 1105 (HY000): Code: 1104, displayText = called `Result::unwrap()` on an `Err` value: Code: 1010, displayText = Can't construct type from Int64(Int64) and Float64(Float64).
   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadDataValueType
             at /workspace/common/exception/src/exception_code.rs:31:71
   1: common_datavalues::types::type_coercion::numerical_coercion
             at /workspace/common/datavalues/src/types/type_coercion.rs:141:32
   2: <common_functions::scalar
```
when boolean type participate in arithmetic operations
```sql
select ((TIMESTAMP '1969-12-22 22:36:52' IS NOT NULL)-(12.123));
select (- (true NOT IN (0.12312, 1358368073)));
select (COT((- (true NOT IN (1.23, 1358368073)))));
---------------------error-info---------------------        
> Code: 1010, displayText = Ops is not support on datatype: Boolean (while in select before projection).
```

**Comment by sundy-li** [comment]
We have implicit conversions in new expression framework, but it's not enabled now.

https://github.com/datafuselabs/databend/blob/main/common/expression/src/type_check.rs#L350-L367

**Comment by JasonLi-cn** [comment]
> We have implicit conversions in new expression framework, but it's not enabled now.
> 
> https://github.com/datafuselabs/databend/blob/main/common/expression/src/type_check.rs#L350-L367

https://github.com/datafuselabs/databend/blob/2654c258dea36106237fafe2d59e67ae28e8d6a3/src/common/expression/src/type_check.rs#L350-L367

**Comment by hanyisong** [comment]
> 
> ```sql
> select * from t0 where c0 IN(0,10,1.1);
> 
> ERROR 1105 (HY000): Code: 1104, displayText = called `Result::unwrap()` on an `Err` value: Code: 1010, displayText = Can't construct type from Int64(Int64) and Float64(Float64).
>    0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadDataValueType
>              at /workspace/common/exception/src/exception_code.rs:31:71
>    1: common_datavalues::types::type_coercion::numerical_coercion
>              at /workspace/common/datavalues/src/types/type_coercion.rs:141:32
>    2: <common_functions::scalar
> ```
@sundy-li I think this is a bug.

**Comment by sundy-li** [comment]
works now
```
🐳 :) create table t0(a int);
processed in (0.068 sec)

🐳 :) select * from t0 where a IN(0,10,1.1);
0 row read in 0.074 sec. Processed 0 row, 0B (0 row/s, 0B/s)

🐳 :) select * from t0 where a IN(0,10,1.1);
0 row read in 0.078 sec. Processed 0 row, 0B (0 row/s, 0B/s)

🐳 :) select * from t0 where a IN(0,10,1.1);
0 row read in 0.101 sec. Processed 0 row, 0B (0 row/s, 0B/s)

```
