### ISSUE TITLE
Feature: agg distinct optimization

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7111]
**Summary**

Description for this feature.

After #7110  is done, we can introduce the improvement in optimization level to transform `count distinct agg / select distinct` into `group by`.

Refer: 

1. https://docs.pingcap.com/tidb/dev/agg-distinct-optimization
2. https://www.qubole.com/blog/presto-optimizes-aggregations-over-distinct-values

**Comment by leiysky** [comment]
We have implemented `SELECT DISTINCT` with `GROUP BY`.

The aggregate over distinct is much more complicated, we have to introduce some new relational operators, e.g. `Expand` for grouping set or a specific operator to join the result of multiple aggregate results together, which depends on the algorithm we are using.
