### ISSUE TITLE
Multi-statement transactions scope

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7121]
**Summary**

Databend supports transactions now.
But for some use cases, like:
1. 3 tables, (a, b, c)
2. Copy into three tables `a/b/c` in one transaction to make the insertion atomic.

Scope:
```
BEGIN;
COPY INTO a ...;
COPY INTO b ...;
COPY INTo c ...;
COMMIT;
```

**Comment by BohuTANG** [comment]
cc @dantengsky

**Comment by dantengsky** [comment]
got it

**Comment by BohuTANG** [comment]
This is on low priority, not in our 0.9 release plan.

**Comment by BohuTANG** [comment]
Support now.
