### ISSUE TITLE
bug: default value is not equal with expected type

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7139]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.169-nightly

### What's Wrong?

I think this statement need to get an error, it expected DEFAULT expression to have type int, but 'false' has type bool

`CREATE TABLE t (a INT DEFAULT false);`

![SDwRgGFitZ](https://user-images.githubusercontent.com/10904090/184823460-67f77453-c184-4378-8912-c357dea96746.jpg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leiysky** [comment]
Also get wrong result when insert empty values:
```sql
mysql> create table t(a int default 1);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t values();
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    0 |
+------+
1 row in set (0.04 sec)
Read 1 rows, 4.00 B in 0.019 sec., 52.61 rows/sec., 210.44 B/sec.
```

**Comment by ZeaLoVe** [comment]
![nnkvoZv5lK](https://user-images.githubusercontent.com/10904090/184828442-c14e5ce5-733d-46f1-bdc1-ab2bc0a12f96.jpg)

**Comment by xudong963** [comment]
> ![nnkvoZv5lK](https://user-images.githubusercontent.com/10904090/184828442-c14e5ce5-733d-46f1-bdc1-ab2bc0a12f96.jpg)

More work needs to do, we almost don't support default_expr currently🤣
