### ISSUE TITLE
bug: cross join empty get error

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.7.169-nightly

### What's Wrong?

![3idiwrUKIY](https://user-images.githubusercontent.com/10904090/185029017-3b59f27a-4343-45f2-a941-e7f868c3d774.jpg)

```
CREATE TABLE onecolumn (x INT NULL);
INSERT INTO onecolumn(x) VALUES (44), (NULL), (42);
CREATE TABLE empty (x INT);
SELECT * FROM onecolumn AS a(x) CROSS JOIN empty AS b(y);
```

I think here should get empty result not error.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
Let me track it @ZeaLoVe
