### ISSUE TITLE
bug:  sql becomes slow in cluster mode

### ISSUE THREAD

**Issue by FANNG1** [datafuselabs/databend#7153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

a6b27a679111b16367a05a3ff6d7ce269f8ea408

### What's Wrong?

20s in a cluster with 1 workers,  
2 min 30s in a cluster with 3 workers

many logs like 
```
^[[2m2022-08-17T08:21:13.415131Z^[[0m ^[[33m WARN^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m Very slow processor async task, processor id: NodeIndex(246), name: "ExchangeTransform", elapsed: 10.002009094s
^[[2m2022-08-17T08:21:13.682378Z^[[0m ^[[33m WARN^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m Very slow processor async task, processor id: NodeIndex(205), name: "ExchangeTransform", elapsed: 10.00223207s
```

### How to Reproduce?

1. setup a cluster with 3 workers
2. run a simple query like 'run a simple sql like ```select origincityname, destcityname, count(*) as c from ontime group by origincityname, destcityname order by c desc limit 10;```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZeaLoVe** [comment]
https://github.com/datafuselabs/databend/pull/7099#issuecomment-1216167503

The time cost of the logictest on cluster mode will help compare performance.

**Comment by zhang2014** [comment]
This is because the data send and receive are mutually blocked(in TransformExchange). I will fix this.

**Comment by sandflee** [comment]
@zhang2014 ,  do we have some performance stats about https://github.com/datafuselabs/databend/pull/7170 ?

**Comment by sandflee** [comment]
now, databend has benchmark tests, but seems only on single node mode not cluster mode,  should we do benchmark on cluster mode? cc @BohuTANG

**Comment by BohuTANG** [comment]
Yes, we do. 
https://perf.databend.rs/ is working on cluster mode.
Any problems on performance?

**Comment by sandflee** [comment]
does perf.databend.rs shows a performance decrease on cluster mode ?

**Comment by zhang2014** [comment]
> @zhang2014 , do we have some performance stats about #7170 ?

It fixes some tasks very slow, but the execution time of queries in the cluster mode is still slower than that in the standalone mode(~10%~20%). The reason is analyzing.

**Comment by sandflee** [comment]
got it, thanks~
