### ISSUE TITLE
bug: float exponent form does not support E

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.7.159-nightly-a7f2c58-simd(rust-1.64.0-nightly-2022-08-10T16:29:03.797735015Z)

### What's Wrong?

My program automatically generates a capital E
```sql
CREATE TABLE t0(c0 FLOAT NULL DEFAULT(true), c1 BOOL NULL DEFAULT(811681875));
INSERT INTO t0(c0, c1) VALUES (8.11681875E8, -568901493);

 Code: 1010, displayText = Expression size not match schema num of cols.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Now supports `INSERT INTO t0(c0, c1) VALUES (8.11681875e8, -568901493);`, we can make it work with`E` .
