### ISSUE TITLE
Feature: add prewhere optimization in fuse engine

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7166]
**Summary**

Description for this feature.

With prewhere optimization, we only read the filter columns and apply the filter operator. If there will be at least one row after the filter operator, then the other columns could be filled from the storage, otherwise, we can skip this block.

This may help in query like:

```
select * from table where url like '%google%';
```

**Comment by RinChanNOWWW** [comment]
I want to have a try on this feature.

**Comment by sundy-li** [comment]
It's not an easy task, but welcome to try it!
