### ISSUE TITLE
Remove some useless but painful tests

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7184]
**Summary**

I propose removing some trivial test cases because they hurt the development experience more than they do

1. [tests/logictest/suites/base/06_show/06_0003_show_settings](https://github.com/datafuselabs/databend/blob/e083b4da1340a768228eab0e38431840e6e6615d/tests/logictest/suites/base/06_show/06_0003_show_settings)   Developers should care to modify this test case when adding new settings each time.  New settings can be covered on his own test case

2. TODO

**Comment by hanyisong** [comment]
can i do it?
