### ISSUE TITLE
doc: query metrics doc missing

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7193]
**Summary**

https://databend.rs/

![rXmNZO2ZPl](https://user-images.githubusercontent.com/10904090/185537780-f1b8d668-580e-4e71-a70b-2870b286ec0a.jpg)

I think need some doc about query metrics just like meta-service. cc @sundy-li

**Comment by sundy-li** [comment]
Add a doc `Query Metrics `(describe the  query metrics as meta service metrics)

Need to add a description about the metric of `SELECT * FROM system.metrics;`

**Comment by ZeaLoVe** [comment]
> Add a doc `Query Metrics `(describe the query metrics as meta service metrics)
> 
> Need to add a description about the metric of `SELECT * FROM system.metrics;`

Also an example of how to get metrics from metric_api_address:  https://databend.rs/doc/manage/query/query-config#metric_api_address
