### ISSUE TITLE
bug: strings in exponential form cannot be converted to int

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7196]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.7.159-nightly-a7f2c58-simd(rust-1.64.0-nightly-2022-08-10T16:29:03.797735015Z)

### What's Wrong?

Strings in exponential form cannot be converted to int, but can be converted to float

### How to Reproduce?

```sql
select '1e10'::int;

ERROR 1105 (HY000): Code: 1010, displayText = Cast error happens in casting from String to Int32 (while in processor thread 0).
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by b41sh** [comment]
'1e10' is a float number, we should cast it to float first.
```sql
select '1e10'::float64::int64;
```
