### ISSUE TITLE
Bug in numerical_coercion of in operator

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7203]
> 
> ```sql
> select * from t0 where c0 IN(0,10,1.1);
> 
> ERROR 1105 (HY000): Code: 1104, displayText = called `Result::unwrap()` on an `Err` value: Code: 1010, displayText = Can't construct type from Int64(Int64) and Float64(Float64).
>    0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadDataValueType
>              at /workspace/common/exception/src/exception_code.rs:31:71
>    1: common_datavalues::types::type_coercion::numerical_coercion
>              at /workspace/common/datavalues/src/types/type_coercion.rs:141:32
>    2: <common_functions::scalar
> ```
@sundy-li I think this is a bug.

_Originally posted by @hanyisong in https://github.com/datafuselabs/databend/issues/7101#issuecomment-1220399398_

**Comment by hanyisong** [comment]
add：t0.c0 is of type int
