### ISSUE TITLE
ProtocolViolation error on OPTIMZE ALL after COPY INTO ontime

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#7208]
**Summary**

```
2022/08/19 12:44:33 webapi.doRequest POST url=https://test.datafusecloud.com/v1/query req={"sql":"OPTIMIZE TABLE ontime_reload ALL;"} resp={"id":"f151ef9a-5e87-459f-810e-73635d154cbe","session_id":"e674fc7e-309d-47b3-9417-672ef9b55644","session":null,"schema":{"fields":[],"metadata":{}},"data":[],"state":"Running","error":null,"stats":{"scan_progress":{"rows":0,"bytes":0},"write_progress":{"rows":0,"bytes":0},"result_progress":{"rows":0,"bytes":0},"running_time_ms":1002.43182},"affect":null,"stats_uri":"/v1/query/f151ef9a-5e87-459f-810e-73635d154cbe","final_uri":"/v1/query/f151ef9a-5e87-459f-810e-73635d154cbe/final","next_uri":"/v1/query/f151ef9a-5e87-459f-810e-73635d154cbe/page/0","kill_uri":"/v1/query/f151ef9a-5e87-459f-810e-73635d154cbe/kill"}
2022/08/19 12:54:02 the 0 time result has error query has error: &{Code:4000 Message:other error (object error: (op: read, path: tnc7yee14/24/720358/_b/1dc96d7c6c34414796eb15daaafe5a91_v0.parquet, source: sending request:  Error { kind: ProtocolViolation, context: None, source: Some(Error { description: "Server returned nothing (no headers, no data)", code: 52, extra: None }), source_type: Some("curl::error::Error"), local_addr: Some(10.1.116.200:49644), remote_addr: Some(52.219.100.66:443) })) Kind:}, stats: <nil>
```

version: 0.7.169
related link: https://github.com/datafuselabs/databend-perf/runs/7918174936?check_suite_focus=true

**Comment by youngsofun** [comment]
another error in OPTIMZE ALL 

```<Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message>```


```
object 24/714475/_b/780b1399106c4bf8a19c55d3652f734d_v0.parquet read: Custom { kind: Interrupted, error: ObjectError { op: "read", path: "24/714475/_b/780b1399106c4bf8a19c55d3652f734d_v0.parquet", source: status code: 500, headers: {"x-amz-request-id": "R062G1Q7PQ9XSHG2", "x-amz-id-2": "Lp3/xe00t65SFxRFWrCUZnNJKiqb6A9BWOXYzthLdOroULWXozi+Hi+/oX0oEyy7wNNm/6vrfSc=", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Fri, 19 Aug 2022 08:54:53 GMT", "server": "AmazonS3", "connection": "close"}, body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>R062G1Q7PQ9XSHG2</RequestId><HostId>Lp3/xe00t65SFxRFWrCUZnNJKiqb6A9BWOXYzthLdOroULWXozi+Hi+/oX0oEyy7wNNm/6vrfSc=</HostId></Error>"

```

**Comment by dantengsky** [comment]
@flaneur2020 @youngsofun 

These two categories of exceptions are highly likely to be caused by accessing AWS s3 too aggressively.

OpenDAL addressed them by the following PR:

- For the "ProtocolViolation"
    https://github.com/datafuselabs/opendal/pull/528 (and the issue https://github.com/datafuselabs/opendal/issues/525)
-  " Please try again."
    https://github.com/datafuselabs/opendal/pull/545
    
but there are not released yet (pls correct me if I am wrong  @Xuanwo ), PR 545 may need some performance evaluation works before release.    please keep tuned.

**Comment by Xuanwo** [comment]
> but there are not released yet

Yep, I expect to release them in next week.

**Comment by Xuanwo** [comment]
> another error in OPTIMZE ALL  (in databend-query log)
> 
> ```<Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message>```
> 
> 
> ```
> object 24/714475/_b/780b1399106c4bf8a19c55d3652f734d_v0.parquet read: Custom { kind: Interrupted, error: ObjectError { op: "read", path: "24/714475/_b/780b1399106c4bf8a19c55d3652f734d_v0.parquet", source: status code: 500, headers: {"x-amz-request-id": "R062G1Q7PQ9XSHG2", "x-amz-id-2": "Lp3/xe00t65SFxRFWrCUZnNJKiqb6A9BWOXYzthLdOroULWXozi+Hi+/oX0oEyy7wNNm/6vrfSc=", "content-type": "application/xml", "transfer-encoding": "chunked", "date": "Fri, 19 Aug 2022 08:54:53 GMT", "server": "AmazonS3", "connection": "close"}, body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>R062G1Q7PQ9XSHG2</RequestId><HostId>Lp3/xe00t65SFxRFWrCUZnNJKiqb6A9BWOXYzthLdOroULWXozi+Hi+/oX0oEyy7wNNm/6vrfSc=</HostId></Error>"
> 
> ```

OpenDAL should have retried them automanticlly.

**Comment by dantengsky** [comment]
> OpenDAL should have retried them automanticlly.

Yeah. I think @youngsofun is just trying to remind us that there are these error logs, to help us investigate this issue.
