### ISSUE TITLE
Not properly handling integer overflow

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7213]
**Summary**

**Databend**

```sql
CREATE TABLE large_numbers (a INT8);

INSERT INTO large_numbers VALUES (9223372036854775807),(1);

SELECT sum(a) FROM large_numbers;

----
0
```

**For MySQL and PostgreSQL**, it will panic when inserting overflow integer

```sql
postgres=# CREATE TABLE large_numbers (a smallint);
CREATE TABLE
postgres=# INSERT INTO large_numbers VALUES (9223372036854775807),(1);
ERROR:  smallint out of range
```

**Snowflake**
For all INTEGER data types, the range of values is all integer values from -99999999999999999999999999999999999999 to +99999999999999999999999999999999999999 (inclusive).

So

```sql
CREATE TABLE large_numbers (a SMALLINT);
INSERT INTO large_numbers VALUES (9223372036854775807),(1);
SELECT sum(a) FROM large_numbers;
--
9223372036854775808

```

**Comment by xudong963** [comment]
cc @sundy-li @BohuTANG

**Comment by sundy-li** [comment]
Snowflake's `smallint` aliased to numeric.

> INSERT INTO large_numbers VALUES (9223372036854775807),(1);

We can add checker in deserialization.
