### ISSUE TITLE
doc: deploy databend on k8s

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7229]
**Summary**

Before the deploy refines, we already have a post about how to deploy databend cluster on k8s.
Let's bring them back to https://databend.rs/doc/deploy

**Comment by BohuTANG** [comment]
Done https://github.com/datafuselabs/databend/pull/7234

**Comment by soyeric128** [comment]
I saw it's already back this morning. I just added some fixes to make it seem better: https://github.com/datafuselabs/databend/pull/7240
