### ISSUE TITLE
bug: const types and nullable types are orthogonal

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.4-nightly-87ecd91-simd(rust-1.64.0-nightly-2022-08-21T16:33:10.834077235Z)

### What's Wrong?

Code: 1058, displayText = downcast column error, column type: "Const(Nullable(Primitive))", expected column: "common_datavalues::columns::nullable::NullableColumn" (while in processor thread 3).

### How to Reproduce?

```sql
CREATE DATABASE databend6;
USE databend6;
CREATE TABLE t0(c0 VARCHAR NULL DEFAULT(0.6883473878718107), c1 INT NOT NULL DEFAULT(1344832732));
CREATE TABLE t1(c0 VARCHAR NULL);

SELECT SUM(count) FROM (SELECT (((-1496301598 BETWEEN -426740132 AND -1105232984) IS NOT NULL AND (-1496301598 BETWEEN -426740132 AND -1105232984)) ::BIGINT)as count FROM t1 LEFT  JOIN t0 ON ((4.87945184e8)<(0.10443958640098572))) as res;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
It's fixed in the latest version.
