### ISSUE TITLE
Insert into empty shouldn't return default value

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7259]
**Summary**
```sql
mysql> CREATE TABLE t(a INT);
Query OK, 0 rows affected (0.03 sec)

mysql> insert into t values();
Query OK, 0 rows affected (0.04 sec)

mysql> select * from t;
+------+
| a    |
+------+
|    0 |
+------+
1 row in set (0.03 sec)
Read 1 rows, 4.00 B in 0.007 sec., 147.57 rows/sec., 590.28 B/sec.
```

Table t doesn't have an explicit default value for a, but it got 0 when inserted empty.

The reason why it got 0 is because https://github.com/datafuselabs/databend/blob/main/src/common/io/src/buffer/buffer_read_number_ext.rs#L81

We should get error when executing ` insert into t values();`.

Directly changing the logic of https://github.com/datafuselabs/databend/blob/main/src/common/io/src/buffer/buffer_read_number_ext.rs#L81 seems unreasonable, because it'll affect other code places.

**Comment by xudong963** [comment]
@sundy-li

**Comment by sundy-li** [comment]
This behavior is the same as ClickHouse:

```
CREATE TABLE t(a INT) Engine = Log;
insert into t values();

select * from t;

┌─a─┐
│ 0 │
└───┘

```

If we do not have default expr in the column definition, it defaults to zero/empty string.
