### ISSUE TITLE
Feature: introduce buffer pool(aka memory manager) to avoid OOM for some opeartors

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7271]
**Summary**

When input data is large, some operators(such as join, sort and so on) will  OOM.

It's necessary to introduce a memory manager to avoid OOM

- let users specify memory size to avoid OOM
- Memory manager in charge of spilling for join, sort, group by...
- ...

cc @zhang2014

**Comment by sandflee** [comment]
does "some operator" include table scan operator?

**Comment by zhang2014** [comment]
> does "some operator" include table scan operator?

We will use global allocator to track and limit memory usage. the processor level memory trace is still in the todo list.
