### ISSUE TITLE
bug: natural join match error

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7283]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.4-nightly-87ecd91-simd(rust-1.64.0-nightly-2022-08-21T16:33:10.834077235Z)

### What's Wrong?

error-info：`ERROR 1105 (HY000): Code: 1007, displayText = Can not compare Boolean(Boolean) with Float64(Float64).`
I think that when natural join matches the same column, you can add the type judgment, so as to avoid the comparison between boolean and double

### How to Reproduce?

```sql
DROP DATABASE IF EXISTS databend5;
CREATE DATABASE databend5;
USE databend5;
CREATE TABLE t0(c0 VARCHAR NULL DEFAULT('1914744'), c1 DOUBLE NULL DEFAULT(0.7262787818908691), c2 BOOL NULL);
CREATE TABLE t55(c0 VARCHAR NOT NULL DEFAULT('96381'), c1 BOOLEAN NULL, c2 BOOL NULL DEFAULT(false));

SELECT true FROM t55 NATURAL JOIN t0;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
I think it's reasonable, `boolean` and `float64` did not have a supertype to cast.
