### ISSUE TITLE
Feature: support function generate_series will be helpful

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7284]
**Summary**

Many OLAP systems support functions generate_series like crdb and duckDB. Example

`CREATE TABLE integers AS SELECT a as a, a as b FROM generate_series(1, 5, 1) tbl(a); `

Databend doe not support and get an error:

`ERROR 1105 (HY000): Code: 1025, displayText = Unknown table function generate_series.`

cc @sundy-li

**Comment by sundy-li** [comment]
@zhang2014 

I prefer to add a new  table function `generate_series` table function rather than extend `numbers` table function?
What do you think?

**Comment by leiysky** [comment]
> @zhang2014
> 
> I prefer to add a new table function `generate_series` table function rather than extend `numbers` table function.
> 
> What do you think?

`generate_series` is not only a table function but a SRF(Set Returning Function), it can be used in both `FROM` clause and `SELECT` clause.
```sql
leiysky=# select generate_series(1,3) from generate_series(1, 3);
 generate_series
-----------------
               1
               2
               3
               1
               2
               3
               1
               2
               3
(9 rows)
```

We should implement `ProjectSet` operator to support using SRFs in `SELECT` clause.

I'm wondering shall we support this?

**Comment by PsiACE** [comment]
https://github.com/datafuselabs/databend/pull/10697
