### ISSUE TITLE
bug: type cast result unexpected

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7295]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.6-nightly-d06cc14-simd(rust-1.64.0-nightly-2022-08-23T16:28:05.696476615Z) 

### What's Wrong?

![nmnkK9pTRJ](https://user-images.githubusercontent.com/10904090/186616963-7c5f6144-b3c8-4471-ba1d-a66a289b2e96.jpg)

expect -inf.

![IAeEOMNIiq](https://user-images.githubusercontent.com/10904090/186617016-6a8c22ff-087a-438e-8995-11a4e7b09cde.jpg)

expect -1 and 1.

cc @andylokandy  maybe the new type system will solve these, the test suites in duckdb is helpful. https://github.com/duckdb/duckdb/tree/master/test/sql/cast

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
```

🐳 :)  select '-1e308'::float;
┌───────────────────┐
│ '-1e308'::float32 │
│      Float32      │
├───────────────────┤
│              -inf │
└───────────────────┘
1 row read in 0.033 sec. Processed 1 row, 1B (30.04 rows/s, 30B/s)
```
