### ISSUE TITLE
feat: external location for fuse engine 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7297]
**Summary**

If we `create table ... engine=fuse`and write some data, the progress like:
1. Put the table schema to meta service
2. Read config from `storage.s3` and create a storage operator
3. Write parquet file to storage
4. Commit the snapshot to meta service

This is how databend fuse engine work now: fuse engine data will write to the storage configured in the databend-query.toml.

If we support(The syntax only for proposal):
```
create table ... engine=fuse <externalLocation>

externalLocation ::=
  's3://<bucket>[<path>]'
  CONNECTION = (
        ENDPOINT_URL = 's3[gcp]://<endpoint-URL>'
        ACCESS_KEY_ID = '<your-access-key-ID>'
        SECRET_ACCESS_KEY = '<your-secret-access-key>'
        REGION = '<region-name>'
        ENABLE_VIRTUAL_HOST_STYLE = true|false
  )
```

Things are changed: we can write fuse engine data to an external location that is controlled by the user, and the user can read the parquet file created by the fuse engine since they are all parquet format!

**Comment by BohuTANG** [comment]
Cc @soyeric128  for documentation. Thanks.

**Comment by soyeric128** [comment]
> Cc @soyeric128 for documentation. Thanks.

So this option stores the table's snapshots, segments, and blocks to an external s3 location other than the default one configured in the [storage.s3]?
