### ISSUE TITLE
[test] add unit test for transform_remote and arrow flight client

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#730]
**Description**
 Add unit test for transform_remote and arrow flight client

https://github.com/datafuselabs/datafuse/pull/725#discussion_r645540817

**Comment by Xuanwo** [comment]
@zhang2014 Hi, is this issue still going on?

**Comment by zhang2014** [comment]
Yes, let‘s continues

**Comment by zhang2014** [comment]
We have moved the cluster to the new framework and remove old code. Let's close it.
