### ISSUE TITLE
performance degradation of "select count(*) from t" in new planner

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#7306]
**Summary**

Exec of the statement "select count(*) from t" now falls back to full table scan, which is rather slow.

Table relies on some pushdown hints to enable the "shortcut", which returns 
- an empty list of parts to be scanned
- the row number of the whole table
by reading snapshot metadata only:

the hints/criteria:
- push_down.projection is None
- (and) push_down.filters is None

For stmt `select count() from t`, the new planner is passing the following pushdown:

`{ projection: Some([0]), filters: [], limit: None, order_by: [] }`

which requires the table to scan the first column of the table.

maybe we should 

- Pass a `None` projection in these case
- Or optimize this stmt by using `Table::statistics` directly?

**Comment by dantengsky** [comment]
> Or optimize this stmt by using `Table::statistics` directly?

please ignore this, this is not gonna work

**Comment by leiysky** [comment]
Maybe related to #7267

**Comment by dantengsky** [comment]
> Maybe related to #7267

:+1:  

duplicate of #7267
