### ISSUE TITLE
Feature: Support using `DEFAULT` to fill default value in `INSERT` statement

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#7312]
Sometimes we want to fill the value of some of the fields with its default value, in `PostgreSQL` we can achieve that with:

```sql
create table temp (a int default 2, b int);
insert into temp values(default, 1);
```

**Comment by RinChanNOWWW** [comment]
How about there isn't a specific default value. For example, int type, should we consider 0 as a default value?

**Comment by sundy-li** [comment]
> For example, int type, should we consider 0 as a default value?

Yes, and the nullable type will default to null.
