### ISSUE TITLE
Documents about sql behavior in databend

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7318]
**Summary**

We should add some documents to help users understand the SQL behavior in databend.

- [ ] DataType  DataType cast/coercion rules   @sundy-li 
- [x] SQL identifiers syntax   @TCeason 
- [x] DataType Nulable and null @b41sh

**Comment by TCeason** [comment]
> DataType DataType cast/coercion rules

I can help to finish it.

**Comment by rahul3002** [comment]
Hey there!

So, you wanna know if these rules will work for coercion, huh?

Check them out:

- Data Compatibility
- Explicit Coercion
- Implicit Coercion

Now, let's talk Decimal type casting:

- Implicit Decimal Type Casting
- Explicit Decimal Type Casting
- Avoiding Data Loss and Precision Issues
- Considerations for Artistic Expression

**Comment by rahul3002** [comment]
Hey there!

I've put together some seriously kick-ass documentation about DataType cast/coercion rules. It's got all the juicy details you need to know. Now, here's the deal: I'd be thrilled if you could take a look at it and let me know what changes you reckon should be made. Your feedback is pure gold to me, so don't hold back!

https://doc.clickup.com/9002042687/p/h/8c90h9z-684/7a7a00ce89a3f0d

**Comment by sundy-li** [comment]
Great, you can create a pr to improve this [doc](https://github.com/sundy-li/fuse-query/blob/write-progress/docs/doc/13-sql-reference/10-data-types/70-data-type-conversion.md)

**Comment by rahul3002** [comment]
Hey there! Have you taken a peek at the documentation I crafted for you? 

If any tweaks or adjustments are needed, I'm all ears and ready to make it perfect!

**Comment by sundy-li** [comment]
> Hey there! Have you taken a peek at the documentation I crafted for you?

I can't open that document, you can create a draft pr and we will comment on that pr.
