### ISSUE TITLE
mac: make: taplo: No such file or directory

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7331]
**Summary**

```
make setup
```

```
make lint

make: taplo: No such file or directory
```

`cargo install taplo-cli` is ok, not sure why rust-tools.txt does not work.

**Comment by Xuanwo** [comment]
https://github.com/datafuselabs/databend/blob/9e41e25011fe98a0806c94290f3cbc60db2b5ca6/scripts/setup/dev_setup.sh#L517-L529

We need to use `make setup -c`

**Comment by Xuanwo** [comment]
Not an issue.
