### ISSUE TITLE
Feature: nullable pruner in fuse engine

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7336]
**Summary**

Description for this feature.

For example

```
select a, b from t where a is null and b is not null
```

We can use the `null_count` in  [`ColumnStatistics`](https://github.com/datafuselabs/databend/blob/fc868936df12e06f5c907c335ac813e950c3eb8b/src/query/storages/fuse-meta/src/meta/common.rs)  to prune the partition

```
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Eq, PartialEq)]
pub struct ColumnStatistics {
    pub min: DataValue,
    pub max: DataValue,

    pub null_count: u64,
    pub in_memory_size: u64,
}

```

**Comment by RinChanNOWWW** [comment]
Null pruner was implemented by #2256 partially, which makes this task easier.
