### ISSUE TITLE
refactor the date_add arguments

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7338]
**Summary**

To be consistent of other popular DBMS:

https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions/#date_add
https://docs.snowflake.com/en/sql-reference/functions/dateadd.html

1. refactor date_add to be `date_add(unit, value, date)`: 
	`date_add(date, 1, year) ` to `date_add(year, 1, date)`, 
	
2. refactor date_add to be `date_sub(unit, value, date)`

3. refactor date_trunc to be `date_trunc(unit, value)`  (seems it's already in the style now)

4. add documents about these functions.

**Comment by wubx** [comment]
cc @xudong963   https://github.com/datafuselabs/databend/tree/main/tests/suites/0_stateless/13_tpch
cc @soyeric128    Update doc later.
