### ISSUE TITLE
feat: Update

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7349]
**Summary**

After `delete` supported, it's time for `update`.

**Comment by BohuTANG** [comment]
Put this task to the v0.9 milestone, cc @dantengsky

**Comment by zhyass** [comment]
## Syntax
```
UPDATE <table> SET <column> = <expr> [, <column> = <expr> , ... ] [WHERE condition]
```

## Task
- [ ] ast syntax and planner support
- [ ] interpreter and storage support

**Comment by BohuTANG** [comment]
https://docs.databend.com/sql/sql-commands/dml/dml-update
