### ISSUE TITLE
we have a BloomIndexMetaCache, which caches `FileMetaData`, but is dedicated to bloom filter index files now.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7353]
we have a BloomIndexMetaCache, which caches `FileMetaData`, but is dedicated to bloom filter index files now.

https://github.com/datafuselabs/databend/blob/1b576fbe78552ca5d024205ee356af70b5b9edf1/src/query/storages/fuse-meta/src/caches/cache.rs#L41.

https://github.com/datafuselabs/databend/blob/26c74149b6b97b7152288b41ea0564114d617aaf/src/query/storages/fuse-meta/src/caches/memory_cache.rs#L50

maybe we could do the refactor in another dedicated PR?

_Originally posted by @dantengsky in https://github.com/datafuselabs/databend/pull/7311#discussion_r956983132_

**Comment by dantengsky** [comment]
part of 
- issue #7354
