### ISSUE TITLE
sqlancer: expression expansion error

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7360]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.12-nightly-74d0287-simd(rust-1.64.0-nightly-2022-08-27T03:09:50.519081067Z)

### What's Wrong?

expression expansion error, expected value should be NULL

### How to Reproduce?

```
MySQL [databend1]> select NOT (NULL BETWEEN NULL AND NULL);
+--------------------------------+
| NOT NULL BETWEEN NULL AND NULL |
+--------------------------------+
|                              1 |
+--------------------------------+
1 row in set (0.003 sec)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Bug of the new parser.
