### ISSUE TITLE
doc: to_date(expr) and to_datetime(expr) function

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7363]
**Summary**

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by wubx** [comment]
There are normalized date functions. 

Eg: how to cast  ' 2014-12-02 17'   to date or timestamp ?

**Comment by BohuTANG** [comment]
> Eg: how to cast ' 2014-12-02 17' to date or timestamp ?

Databend can not do it now, this is not a normal format :/

**Comment by TCeason** [comment]
We just support cast iso 8601 date/time format to date or datetime.

Can reference https://github.com/datafuselabs/databend/blob/main/tests/logictest/suites/base/11_data_type/11_0001_data_type_date_time and https://github.com/datafuselabs/databend/blob/main/tests/logictest/suites/base/11_data_type/11_0005_data_type_date

**Comment by TCeason** [comment]
BTW, MySQL supports this format, but I think that's wrong. DateTime split with date and time part. I think time part should not split again.

And maybe MySQL still has some bug with this format. I don't think we should be compatible with this format unless we have special requirements

```sql
root@mysqldb 19:22:11 [db]> 
root@mysqldb 19:22:11 [db]> desc t;
+-------+----------+------+-----+---------+-------+
| Field | Type     | Null | Key | Default | Extra |
+-------+----------+------+-----+---------+-------+
| t1    | datetime | YES  |     | NULL    |       |
+-------+----------+------+-----+---------+-------+
1 row in set (0.02 sec)

root@mysqldb 19:22:26 [db]> delete from t;
Query OK, 2 rows affected (0.01 sec)

root@mysqldb 19:22:41 [db]> insert into t values('2014-12-02 17');
Query OK, 1 row affected (0.01 sec)

root@mysqldb 19:22:45 [db]> insert into t values('2014-12-02 17+08:00');
Query OK, 1 row affected, 1 warning (0.01 sec)

root@mysqldb 19:22:52 [db]> select * from t;
+---------------------+
| t1                  |
+---------------------+
| 2014-12-02 17:00:00 |
| 2014-12-02 17:08:00 |
+---------------------+
2 rows in set (0.00 sec)

root@mysqldb 19:22:56 [db]> select version();
+-----------+
| version() |
+-----------+
| 8.0.29    |
+-----------+
1 row in set (0.01 sec)

root@mysqldb 19:23:06 [db]> insert into t values('2014-12-02 17:08:00+08:00');
Query OK, 1 row affected (0.02 sec)

root@mysqldb 19:23:34 [db]> select * from t;
+---------------------+
| t1                  |
+---------------------+
| 2014-12-02 17:00:00 |
| 2014-12-02 17:08:00 |
| 2014-12-02 09:08:00 |
+---------------------+
3 rows in set (0.00 sec)


```

**Comment by soyeric128** [comment]
@BohuTANG 
I found TO_DATE and TO_DATETIME also accept an integer as the argument in the examples part of these pages: https://databend.rs/doc/reference/functions/datetime-functions/tostartofmonth
https://databend.rs/doc/reference/functions/datetime-functions/toyyyymmddhhmmss

Can you help explain how they treat the integer when parsing the expression?

Thanks!

**Comment by BohuTANG** [comment]
The argument is expression, expression can be integer or string.

**Comment by soyeric128** [comment]
SF documents how they process the integer in the link below:
https://docs.snowflake.com/en/sql-reference/functions/to_date.html#usage-notes

What are our rules to do the calculation?

**Comment by BohuTANG** [comment]
Ping @TCeason :/

**Comment by TCeason** [comment]
```sql
'root'@mysqldb 08:35:42 [(none)]> select to_date(1);
+------------+
| to_date(1) |
+------------+
| 1970-01-02 |
+------------+
1 row in set (0.05 sec)
Read 1 rows, 1.00 B in 0.006 sec., 178.16 rows/sec., 178.16 B/sec.

'root'@mysqldb 08:35:48 [(none)]> select to_datetime(1);
+----------------------------+
| to_datetime(1)             |
+----------------------------+
| 1970-01-01 00:00:01.000000 |
+----------------------------+
1 row in set (0.05 sec)
Read 1 rows, 1.00 B in 0.005 sec., 187.76 rows/sec., 187.76 B/sec.

'root'@mysqldb 08:35:51 [(none)]> select to_datetime(2);
+----------------------------+
| to_datetime(2)             |
+----------------------------+
| 1970-01-01 00:00:02.000000 |
+----------------------------+
1 row in set (0.04 sec)
Read 1 rows, 1.00 B in 0.005 sec., 185.87 rows/sec., 185.87 B/sec.

```

the int in to_date is the day after `1970-01-01`, 

the int in to_datetime is the second after `1970-01-01 00:00:00`.

**Comment by soyeric128** [comment]
Please review https://github.com/datafuselabs/databend/pull/7454
