### ISSUE TITLE
bug: Code: 4000, displayText = block pruning failure, task 1050895 panicked.

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.12-nightly-74d0287-simd(rust-1.64.0-nightly-2022-08-27T03:09:50.519081067Z)

### What's Wrong?

Code: 4000, displayText = block pruning failure, task 1050895 panicked.

### How to Reproduce?

```sql
DROP DATABASE IF EXISTS databend1;
CREATE DATABASE databend1;
USE databend1;
CREATE TABLE t0(c0BOOLEAN BOOLEAN NULL DEFAULT(true));
CREATE TABLE t1(c0FLOAT DOUBLE NULL DEFAULT(0.8522535562515259), c1VARCHAR VARCHAR NULL);
INSERT INTO t1(c0float) VALUES (0.48751503229141235);
INSERT INTO t1(c0float, c1varchar) VALUES (0.8522535562515259, NULL);
INSERT INTO t1(c1varchar) VALUES ('2'), ('78');
INSERT INTO t0(c0boolean) VALUES (false), (false), (true);
INSERT INTO t1(c0float) VALUES (0.8522535562515259), (0.48751503229141235);
INSERT INTO t1(c0float, c1varchar) VALUES (0.48751503229141235, '7555834'), (0.7298239469528198, '8');

SELECT t0.c0boolean, t1.c1varchar FROM t1, t0 WHERE (((((((0.7881649136543274 BETWEEN 2.69507072E8 AND 0.964137852191925))and((('68107560')like('2')))))OR(NULL)))or(false)) GROUP BY t0.c0boolean, t1.c1varchar UNION SELECT t0.c0boolean, t1.c1varchar FROM t1, t0 WHERE (NOT (((((((0.7881649136543274 BETWEEN 2.69507072E8 AND 0.964137852191925))AND((('68107560')LIKE('2')))))OR(NULL)))or(false))) GROUP BY t0.c0boolean, t1.c1varchar UNION SELECT t0.c0boolean, t1.c1varchar FROM t1, t0 WHERE (((((((((0.7881649136543274 BETWEEN 2.69507072E8 AND 0.964137852191925))AND((('68107560')like('2')))))OR(NULL)))or(false))) IS NULL) GROUP BY t0.c0boolean, t1.c1varchar;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Thanks a lot 👍 

There are some bugs in pruning, panicked at:
https://github.com/datafuselabs/databend/blob/5634318ca33d7ea445811552d9b00a0aa9e2c3e0/src/query/storages/fuse/src/pruning/pruning_executor.rs#L151

**Comment by zhyass** [comment]
SELECT t0.c0boolean, t1.c1varchar
FROM t1, t0
WHERE false OR NULL
GROUP BY  t0.c0boolean, t1.c1varchar;

mysql> SELECT t0.c0boolean, t1.c1varchar
FROM t1, t0
WHERE false OR NULL
GROUP BY  t0.c0boolean, t1.c1varchar;

ERROR 1105 (HY000): Code: 4000, displayText = block pruning failure, task 1939 panicked.
