### ISSUE TITLE
read_bloom_filter_index() take 2min for ontime

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#7379]
can we accelerate it？

cc @dantengsky

**Comment by dantengsky** [comment]
yes

- enable table cache 
  bloom filter index will be cached (by col) if table cache is enabled

  but apparently, it only works after warming up

- allow more concurrency in pruning
 

https://github.com/datafuselabs/databend/blob/869344f106c69552ff61835c69da471f4de40f95/src/query/storages/fuse/src/pruning/pruning_executor.rs#L103-L106

  
btw, how many parts and rows for the test set?

**Comment by youngsofun** [comment]
> btw, how many parts and rows for the test set?

202687555 rows.

how to show num of parts?

**Comment by youngsofun** [comment]
![image](https://user-images.githubusercontent.com/5782159/187580179-196f6f5a-b168-4798-a78a-6c05e659e7df.png)

**Comment by dantengsky** [comment]
got it , thanks!

**Comment by BohuTANG** [comment]
It would be better to create a bloom-filter index for `STRING` types only? cc @dantengsky

**Comment by BohuTANG** [comment]
@drmingdrmer is working on this to make it faster 🤗

**Comment by BohuTANG** [comment]
@drmingdrmer is working on this to make it faster 🤗

**Comment by drmingdrmer** [comment]
Oh, man. Thanks for reminding me.

I'm trying to dig deeper to grasp what's going on inside the fuse table with the bloom filter.

I will give a refactoring proposal ASAP.

**Comment by BohuTANG** [comment]
@youngsofun 
Can you try with the main branch?
I think we have some improvements with this patch: https://github.com/datafuselabs/databend/pull/7870

**Comment by youngsofun** [comment]
the problem is originally for Q10 on ontime. on a test cluster.
and I found  simply` SELECT count(*) FROM default.ontime WHERE `depdel15`=1; ` is abnormal: slow with many log about bloom filter 

----


can not open test.datafusecloud.com now

**Comment by BohuTANG** [comment]
I think the time cost is small now, let's close, if you find the time is still long please re-open next time.
