### ISSUE TITLE
Feature:  additional http handler for copy into command

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#7384]
**Summary**
Currently we support streaming load and COPY INTO sql command, and we could support additional http handler to process copy into command, the main reason is to control copy into command permission, currently our access control model is in early stage, and incur some unwanted permission leakages.

**Comment by ZhiHanZ** [comment]
cc @youngsofun could you take a look?

**Comment by youngsofun** [comment]
@ZhiHanZ  do we still need this？

**Comment by ZhiHanZ** [comment]
> @ZhiHanZ  do we still need this？

I think it could be closed
