### ISSUE TITLE
bug: cast from string with space error

### ISSUE THREAD

**Issue by ZeaLoVe** [datafuselabs/databend#7389]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.14-nightly-07bbba3-simd(rust-1.64.0-nightly-2022-08-28T16:42:58.855611921Z) 

### What's Wrong?

`SELECT CAST('   1e1' AS DOUBLE);`

I expect to get 10.0 but get an error.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
We can trim it firstly and cast to others.
