### ISSUE TITLE
Feature: add any agg function

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7397]
**Summary**

Description for this feature.

first(arg) | Returns the first value of a column. | syntax |
-- | -- | -- 
any(arg) | Returns any value of a column. | any(A)

<br class="Apple-interchange-newline">

Though some dbms support `first`, `last`, but the order is not stable in databend, so we do not need to support them

**Comment by RinChanNOWWW** [comment]
`any` cannot pass the parser, why?

```
mysql> select ANY(NULL);
ERROR 1105 (HY000): Code: 1005, displayText = error: 
  --> SQL:1:12
  |
1 | select ANY(NULL)
  | ------ --- ^^^^
  | |      |   |
  | |      |   expected `(`, `UNION`, `EXCEPT`, `INTERSECT`, `SELECT`, or `WITH`
  | |      |   while parsing `SELECT ...`
  | |      while parsing `(SELECT ...)`
  | |      while parsing expression
  | while parsing `SELECT ...`
```

**Comment by sundy-li** [comment]
It's a `is_reserved_function_name` ?

**Comment by RinChanNOWWW** [comment]
> It's a `is_reserved_function_name` ?

Yes. So just remove it from the reserve list?
