### ISSUE TITLE
doc: add system functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7409]
**Summary**

Add a new category, `System Functions ` to:
https://databend.rs/doc/reference/functions/

System functions:
https://github.com/datafuselabs/databend/tree/2654c258dea36106237fafe2d59e67ae28e8d6a3/src/query/service/src/procedures/systems

Snow system functions:
https://docs.snowflake.com/en/sql-reference/functions-system.html

**Comment by soyeric128** [comment]
@BohuTANG Where can I find some examples showing how these functions work?

**Comment by BohuTANG** [comment]
You can search the function and find them in the sql file :)

**Comment by soyeric128** [comment]
> You can search the function and find them in the sql file :)

In which SQL file ?

**Comment by BohuTANG** [comment]
It may be in the markdown file(If you can not find them, please connect with the PR author to get more information). For example, search `CLUSTER_INFORMATION`:

![image](https://user-images.githubusercontent.com/172204/187807970-89fc35c3-01d9-47e7-ba61-b6ecf9a979f6.png)

**Comment by wubx** [comment]
In Databend every function has test cases. You can find it in the test dir.
