### ISSUE TITLE
Refactor `PartitionQueue` and introduce task scheduler

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#741]
There should be some mechanism like a instace level `TaskManager` to host the metadata of query and schedule the tasks.

So far, tasks(i.e. partitions) are represented as a `PartitionQueue` bind with `FuseQueryContext`, cons of which is:

- `PartitionQueue` is shared in context-level, thus if we want to process multiple tables(join) in a same query, we have to create a new `FuseQueryContext` for each Pipeline, otherwise the partitions of different tables will be mixed together.
- We can hardly schedule tasks properly without a global view.

The current design of `PartitionQueue` will soon not satisfy our requirement, so I suggest making the refactor work high priority.

**Comment by leiysky** [comment]
cc @BohuTANG

**Comment by BohuTANG** [comment]
Hi @leiysky 
By design, each query(session) shares one context no matter it's a join or others subquery, we shouldn't create new context inside.
For join, maybe we need multiple partition queues?

Could you give an example to help us understand the requirements?
Thanks

**Comment by leiysky** [comment]
> Hi @leiysky
> By design, each query(session) shares one context no matter it's a join or others subquery, we shouldn't create new context inside.
> For join, maybe we need multiple partition queues?
> 
> Could you give an example to help us understand the requirements?
> Thanks

https://github.com/datafuselabs/datafuse/blob/2e32a4d98149d220296119fa0d343ed4531bf355/fusequery/query/src/pipelines/processors/pipeline_builder.rs#L283-L292

For example, if I don't create a new `FuseQueryContext` for each sub-pipeline, then the `left_pipeline` and `right_pipeline` will share the same `PartitionQueue`, which will bring unexpected random result.

Introduce multiple partition queue like `HashMap<String, PartitionQueue>` can fix this issue, but still have other issues.

My point is that **a local `PartitionQueue` isn't a good idea**, we can figure out a better way.

**Comment by BohuTANG** [comment]
Hi @leiysky 
Good example!
What's the better way? 💯

**Comment by BohuTANG** [comment]
By the way, the partition queues should be fetch by a <id,stage_id> tuple

**Comment by leiysky** [comment]
IMHO, every fuse-query process can have a `TaskManager`(or `PipelineManager`, `StageManager`, whatever), which we call it `scheduler` here.

For each `Pipeline`, we will register it in `scheduler` with a unique id like `<id, stage_id>` . At the same time, `scheduler` will maintain a `PartitionQueue` for each `Pipeline`, which is similar to the current design. The difference is most work of resource management will be delegate to `scheduler` but not `context`.

The benefit of this architecture is that `scheduler` always has a global view of all local `Pipeline`s, so it can do some fancy scheduling rather than a simple future executor. For example, we can separate `ReadSource` task from `Pipeline` and let the `Pipeline`s with same `ReadSource` share partition buffer.

**Comment by BohuTANG** [comment]
The session manager similar did it, but need some improvements to archive the requirements.

**Comment by zhang2014** [comment]
As far as I know, for distributed queries, we will build a global partition queue on the first requested node, and then split the partition queue to all nodes.

**Comment by zhang2014** [comment]
It's a great idea to create scheduler with multiple queries to share. It can bring many benefits, but it may also bring us some problems. For example, 
- it changes the current code a little bit. 
- We need to get a lock for each partition.
- We don't know what kind of partition queue is more suitable for us

I voted to use HashMap<String, PartitionQueue > to solve this problem quickly.

**Comment by zhang2014** [comment]
Hope is helpful:
After #931, we split the state of context:
1. query execute state
https://github.com/datafuselabs/datafuse/blob/27c3ab92726d1372f17c8a103475e0ecea668d2c/fusequery/query/src/sessions/context.rs#L33-L38
2. query shared state https://github.com/datafuselabs/datafuse/blob/27c3ab92726d1372f17c8a103475e0ecea668d2c/fusequery/query/src/sessions/context_shared.rs#L30-L41

Example of multi table query
``` rust
// Build left pipeline 
fn left_pipeline(query_context: FuseQueryContextRef, plan: &PlanNode) -> Result<Pipeline> {
    let left_query_context = FuseQueryContext::new(query_context);
    let left_pipeline_builder = PipelineBuilder::create(left_query_context);
    left_pipeline_builder.build(plan)
}

// Build right pipeline 
fn right_pipeline(query_context: FuseQueryContextRef, plan: &PlanNode) -> Result<Pipeline> {
    let right_query_context = FuseQueryContext::new(query_context);
    let right_pipeline_builder = PipelineBuilder::create(right_query_context);
    right_pipeline_builder.build(plan)
}

```

**Comment by BohuTANG** [comment]
This issue has many improved and outdated, let's close.
