### ISSUE TITLE
Suggest:  add more debug logs to query executors

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#7415]
**Summary**
now how tasks are scheduled& executed are a black box, suppest to add more debug logs to show when tasks are scheduled, how long time it spends.

**Comment by sandflee** [comment]
hi, @zhang2014 , are u doing some work? if not , I not , I'd like to do this.

**Comment by zhang2014** [comment]
> hi, @zhang2014 , are u doing some work? if not , I not , I'd like to do this.

I haven't started yet. You can implement it if you're interested : )
