### ISSUE TITLE
Need a common `Catalog` abstraction

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#742]
To improve the SQL planner, we need a `Catalog` abstraction to help resolve symbols to concrete database items(e.g. table, column, session variable).

**Comment by dantengsky** [comment]
Appreciate it! and I'm with you on that. 
 
We have some initial design of catalog, table format, rules of schema evolution, tx & cc, etc. Things are not totally settled down and need some more time to refine/check the relevant design.

**Comment by leiysky** [comment]
> Appreciate it! and I'm with you on that.
> 
> We have some initial design of catalog, table format, rules of schema evolution, tx & cc, etc. Things are not totally settled down and need some more time to refine/check the relevant design.

Shall we support `DDL` in future? If so, this is going to be a much tougher work...

**Comment by dantengsky** [comment]
`DDL` should be supported. it will be a tough but joyful journey. ;-)

**Comment by leiysky** [comment]
By the way, how can I follow up the progress? Do you have any periodic report or tracking mechanism like JIRA?

**Comment by BohuTANG** [comment]
I will try to create an issue later to  track it.

**Comment by leiysky** [comment]
> I will try to create an issue later to  track it.
> 
> 

Nice. But this is one of the tasks, I'd also like to follow up other tasks.

It will be good if there is a central place(e.g. GitHub Project) for them.

**Comment by BohuTANG** [comment]
we will try to use issue not project to track tasks first

**Comment by BohuTANG** [comment]
@leiysky 

Have add an track issue: https://github.com/datafuselabs/datafuse/issues/745

But it still needs to be improved.
