### ISSUE TITLE
doc: dml command copy into need to optimize

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#7437]
**Summary**
https://databend.rs/doc/reference/sql/dml
```
copy into <location>
copy into from staged
copy into from remote
```
they are support: csv, json, ndjson, parquet and formatTypeOptions, but the document content is not uniform. 

Example section(https://databend.rs/doc/load-data) missing json, ndjson example.

**Comment by wubx** [comment]
@soyeric128

**Comment by Xuanwo** [comment]
Already addressed.
