### ISSUE TITLE
Upgrade rust-toolchain to nightly-2022-09-02

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#7466]
rust-1.63 is released, and the new nightly(2022-09-02) introduces different APIs:
- `std::Error::backtrace()` is replaced with `provider` style API: `request_ref::<Backtrace>()`.
- `std::Simd` API changes that affect `arrow2`: [a draft update](https://github.com/datafuse-extras/arrow2/pull/6) is fired for illustration.

The changes about `Error` affect several third-party crates too, such as `thiserror`, in [1.0.33](https://github.com/dtolnay/thiserror/releases/tag/1.0.33) it switched to the provider style API to retrieve backtrace.

[openraft](https://github.com/datafuselabs/openraft/tree/v0.7.2) is updated and is ready to upgrade to nightly-2022-09-02.

Once these modifications are ready, it's time to upgrade to the new nightly 2022-09-02.

@sundy-li @Xuanwo @PsiACE 
Opinion? Suggestions? 🤔

**Comment by Xuanwo** [comment]
I tried this a couple of days ago, which was blocked by https://github.com/datafuselabs/openraft/pull/546

It LGTM to upgrade nightly-2022-09-02 now!

**Comment by xudong963** [comment]
Any update?

**Comment by xudong963** [comment]
I'm solving the issue  @Xuanwo

**Comment by Xuanwo** [comment]
Here are some links that may be helpful to you: https://databend.rs/doc/faq/routine-maintenance
