### ISSUE TITLE
[roadmap-track] Query cluster

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#747]
Query cluster.

# Main tasks

| Task                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [Shuffle framework #469](https://github.com/datafuselabs/datafuse/issues/469)| DONE  |  v0.4 | @zhang2014   |
| [Shuffle GroupBy #469](https://github.com/datafuselabs/datafuse/issues/469)| DONE  |  v0.4 | @zhang2014   |
| [Broadcast subquery #1059](https://github.com/datafuselabs/datafuse/issues/1059)| DONE | v0.5 | @zhang2014  |
| [Cancelable #204](https://github.com/datafuselabs/datafuse/issues/204)| DONE  |  v0.5 |  @zhang2014   |
| [Cluster management #883](https://github.com/datafuselabs/datafuse/issues/883)| DONE  |  v0.5 |   @zhang2014  |
| [Version for flight rpc talking #1247](https://github.com/datafuselabs/datafuse/issues/1247)| PLANNING | v0.5 |  |
| Shuffle Sort | PLANNING  |  v0.5 |   |
| Performance measures | PLANNING  |  v0.5 |   |
| Reliability tests | PLANNING  |  v0.5 |   |

# References
- [x] [shuffle design doc](https://databend.rs/dev/rfcs/query/data-shuffle)
- [x] [join design doc](https://databend.rs/dev/rfcs/query/join-framework-design)

**Comment by drmingdrmer** [comment]
@BohuTANG mind track progress with a project? https://github.com/datafuselabs/datafuse/projects/21

**Comment by BohuTANG** [comment]
@drmingdrmer 
not mind, we can have a try.
Personally, issue track keep all the history and status in one table, it's more clearly for the contributors to know our roadmap at first time.
Like to use project for development not roadmap track.
We should try and choose one best way.

**Comment by zhang2014** [comment]
Add: implement broadcast distributed query
CC: @jyizheng

**Comment by BohuTANG** [comment]
Add:
[Cluster management #883](https://github.com/datafuselabs/datafuse/issues/883)

**Comment by BohuTANG** [comment]
Add:
[Version for flight rpc talking #1247](https://github.com/datafuselabs/datafuse/issues/1247)

**Comment by liukun4515** [comment]
> 

 shuffle design doc
 join design doc
These two docs are invalid.
@BohuTANG

**Comment by BohuTANG** [comment]
Updated, thank you @liukun4515

**Comment by BohuTANG** [comment]
We have moved to the new processor now, let's close this issue, if you need to track them again, please open the new one. cc @zhang2014
