### ISSUE TITLE
bug:  Code: 1058, displayText = downcast column error

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#7483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.23-nightly-cbaedce-simd(rust-1.64.0-nightly-2022-09-02T16:39:41.032000394Z)

### What's Wrong?

 Code: 1058, displayText = downcast column error

### How to Reproduce?

```sql

DROP DATABASE IF EXISTS databend3;
CREATE DATABASE databend3;
USE databend3;
CREATE TABLE t0(c0BOOLEAN BOOLEAN NULL, c1FLOAT DOUBLE NULL);
CREATE TABLE t16(c0BOOLEAN BOOL NULL DEFAULT(true));
INSERT INTO t0(c1float, c0boolean) VALUES (0.27563244104385376, false), (0.7913353443145752, false);

MySQL [databend3]> select * from t16 right join t0 on false;
ERROR 1105 (HY000): Code: 1058, displayText = downcast column error, column type: "Const(Nullable(Boolean))", expected column: "common_datavalues::columns::nullable::NullableColumn" (while in processor thread 0).

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hanyisong** [comment]
@BohuTANG @sundy-li

**Comment by BohuTANG** [comment]
Thanks for the great bug report! @hanyisong 
cc @xudong963
