### ISSUE TITLE
Feature: Implement top-down optimization for cascades optimizer

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#7508]
Currently, the cascades optimizer of databend is implemented in a recursive fashion instead of top-down, which is easy to maintain but can not really enumerate all the search space.

Besides, we can hardly implement lower bound optimization without top-down optimization.

**Comment by leiysky** [comment]
@youngsofun Have you started the related work? I'm going to work on this in recent days.

**Comment by youngsofun** [comment]
just read related paper and code, not started the coding yet.  I was intended to but blocked by the RightMarkJoin pr. 
you can take it if you want.
