### ISSUE TITLE
Feature:  fast finish pipeline if leaf processor finished.

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#7509]
**Summary**
 we found simple select query with `max_thread = 60`  is  more slower than the same query with `max_thread =1 `.  besides the factor of network band, the pipeline could't be finished when limit node (leaf node) finished, for now it waits the finish of all node, especially for waiting for the HiveEngineSource to read data.  I think we could fast finish the pipeline exeutor if the leaf node finished. 

```
+------------------------------------------------------------+
| explain                                                    |
+------------------------------------------------------------+
| LimitTransform × 1 processor                               |
|   Merge (Rename × 60 processors) to (LimitTransform × 1)   |
|     Rename × 60 processors                                 |
|       Project × 60 processors                              |
|         HiveEngineSource × 60 processors                   |
+------------------------------------------------------------+

```

**Comment by sandflee** [comment]
this's useful when the table scan operator is slow, seems numbers func are generated in memory.

**Comment by zhang2014** [comment]
> this's useful when the table scan operator is slow, seems numbers func are generated in memory.

I got it. We should stop all running tasks after the limit is finished, right?

**Comment by sandflee** [comment]
yes

**Comment by sandflee** [comment]
after #7515 , the query time reduces from 5.1s to 2.9s!   thanks @zhang2014  ,cc @BohuTANG

**Comment by sandflee** [comment]
it takes 150ms to stop the last HiveEngineSource after  PullingExecutorSink is finished, is this expected? 
```
^[[2m2022-09-08T09:18:57.459972Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(184), name:"PullingExecutorSink", event: 542ns
^[[2m2022-09-08T09:18:57.459976Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(184), name:"PullingExecutorSink", event: Finished
^[[2m2022-09-08T09:18:57.471249Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(2), name:"HiveEngineSource", event: 28.234182ms
^[[2m2022-09-08T09:18:57.471268Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(2), name:"HiveEngineSource", event: Finished
^[[2m2022-09-08T09:18:57.471916Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(3), name:"HiveEngineSource", event: 26.937254ms
^[[2m2022-09-08T09:18:57.471931Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(3), name:"HiveEngineSource", event: Finished
^[[2m2022-09-08T09:18:57.573126Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(4) name: "HiveEngineSource", elapsed:361.629151ms
^[[2m2022-09-08T09:18:57.573156Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(4), name:"HiveEngineSource", event: Finished
^[[2m2022-09-08T09:18:57.604177Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(9) name: "HiveEngineSource", elapsed:817.965946ms
^[[2m2022-09-08T09:18:57.607275Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(8) name: "HiveEngineSource", elapsed:820.914478ms
```

**Comment by zhang2014** [comment]
> it takes 150ms to stop the last HiveEngineSource after PullingExecutorSink is finished, is this expected?
> 
> ```
> ^[[2m2022-09-08T09:18:57.459972Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(184), name:"PullingExecutorSink", event: 542ns
> ^[[2m2022-09-08T09:18:57.459976Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(184), name:"PullingExecutorSink", event: Finished
> ^[[2m2022-09-08T09:18:57.471249Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(2), name:"HiveEngineSource", event: 28.234182ms
> ^[[2m2022-09-08T09:18:57.471268Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(2), name:"HiveEngineSource", event: Finished
> ^[[2m2022-09-08T09:18:57.471916Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_worker_context^[[0m^[[2m:^[[0m sync processor, node id:NodeIndex(3), name:"HiveEngineSource", event: 26.937254ms
> ^[[2m2022-09-08T09:18:57.471931Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(3), name:"HiveEngineSource", event: Finished
> ^[[2m2022-09-08T09:18:57.573126Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(4) name: "HiveEngineSource", elapsed:361.629151ms
> ^[[2m2022-09-08T09:18:57.573156Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::executor_graph^[[0m^[[2m:^[[0m node id:NodeIndex(4), name:"HiveEngineSource", event: Finished
> ^[[2m2022-09-08T09:18:57.604177Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(9) name: "HiveEngineSource", elapsed:817.965946ms
> ^[[2m2022-09-08T09:18:57.607275Z^[[0m ^[[34mDEBUG^[[0m ^[[2mdatabend_query::pipelines::executor::processor_async_task^[[0m^[[2m:^[[0m async processor, node id NodeIndex(8) name: "HiveEngineSource", elapsed:820.914478ms
> ```

The async task may not be killed immediately.
