### ISSUE TITLE
[performance] Improve the state serialize for aggregate function.

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#751]
**Summary**

Currently we have `fn accumulate_result(&self) -> Result<Vec<DataValue>>` in  trait IAggregateFunction.

It's aimed to get the state to make it represent as  `Vec<DataValue>` . 
And then we serialize the  `Vec<DataValue>` to ColumnBinary in `groupByTransform`  for future merge.

![image](https://user-images.githubusercontent.com/3325189/120971337-18848e80-c79f-11eb-86b3-e7fa0d582594.png)

It will produce extras memory copy during the first two phases. And we can merge them into one to improve that.

 As ClickHouse did.

https://github.com/clickhouse/clickhouse/blob/master/src/AggregateFunctions/IAggregateFunction.h#L101-L102

```
 /// Serializes state (to transmit it over the network, for example).   

virtual void serialize(ConstAggregateDataPtr __restrict place, WriteBuffer & buf) const = 0
```

**Comment by Xuanwo** [comment]
@sundy-li Is this issue still valid?

**Comment by sundy-li** [comment]
Yes, it's done.
