### ISSUE TITLE
Feature:  remove the host conf from flight_api_address  to simple deploy databend

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#7510]
**Summary**
now we must specify the host ip to flight_api_address, which means we could't simple spread the config file to multi machines.

databend master could parse the real ip from the connection,  it may not works for private networks, but maybe we could add a config option?

**Comment by zhang2014** [comment]
Network topology is always complex (for example, multiple network interface, multiple routes, docker provides multiple network ways). We do not want to detect any network topology.

**Comment by sandflee** [comment]
1.  I deployed trino& starrocks , no need to care about host ip,  and could be simplely deployed in cluster.
2. yes,  network is alway complex, but in the most common cases, k8s and local cluster, user had to detect the machine ip, not friendly.
