### ISSUE TITLE
Feature: Versioning Databend's Documents

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend#7516]
**Summary**

After the release of 0.8, we plan to version the documentation.

We now plan to use a similar approach to docusaurus:
- keeping only the latest version
- providing permanent links to older versions

ref: https://docusaurus.io/

**Comment by Xuanwo** [comment]
Let's defer this issue until we release v0.9

https://github.com/datafuselabs/databend/pull/7688#pullrequestreview-1111485359

**Comment by PsiACE** [comment]
> Let's defer this issue until we release v0.9

Perhaps it should be tagged with `v0.9` to hint that we need to finish the job eventually.

**Comment by Xuanwo** [comment]
> Perhaps it should be tagged with `v0.9` to hint that we need to finish the job eventually.

Added into v0.9 milestone.
