### ISSUE TITLE
bug:  query-cluster.yaml contains wrong env variables

### ISSUE THREAD

**Issue by loloxiaoz** [datafuselabs/databend#7532]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

dd12fdfe84e06572f2295d5784c5e1280d00e72f

### What's Wrong?

followed this [wiki](https://databend.rs/doc/deploy/deploying-databend-on-kubernetes) to deploy databend on Kubernetes and occured this error

<img width="2269" alt="sc_20220908203139" src="https://user-images.githubusercontent.com/6119077/189122548-de2fff6b-3532-4757-bc9c-9101be00a0bc.png">

when i rollbacked this commit, the query service got back to normal

<img width="803" alt="image" src="https://user-images.githubusercontent.com/6119077/189124747-b8692c4b-97ad-470c-8bea-7116a2f124b0.png">

### How to Reproduce?

followed this [wiki](https://databend.rs/doc/deploy/deploying-databend-on-kubernetes) to deploy databend on Kubernetes

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
You seem to be using a very old version. You can use our latest version. And can refer to: https://databend.rs/doc/deploy

**Comment by loloxiaoz** [comment]
the yaml in main branch is using a very old verion, which is located in https://raw.githubusercontent.com/datafuselabs/databend/main/scripts/kubernetes/query-cluster.yaml .  it's versy misleading for greenhand
<img width="700" alt="sc_20220909185231" src="https://user-images.githubusercontent.com/6119077/189334908-cfd37e8c-d466-476b-9116-19312db27517.png">

**Comment by Xuanwo** [comment]
Already fixed.
