### ISSUE TITLE
Simple query cluster mode is slower than standalone mode

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#7552]
I run a simple select query like 'select * from lineorder limit 100000',  totally it works fine with a litter minor problems, but we could trace it in another issues.
1.  it takes 1.2s in local mode, 1.4~.1.5s in cluster mode. a little expensive (for starrocks takes 1.0 in local mode, 0.7 in cluster mode)
2. limit is not pushed down to the worker node,   worker node keeps reading and sending data.

_Originally posted by @sandflee in https://github.com/datafuselabs/databend/issues/7542#issuecomment-1241789866_

**Comment by BohuTANG** [comment]
Outdated.
