### ISSUE TITLE
quick-xml is yanked

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#7578]
```
Crate:         quick-xml
Version:       0.23.0
Warning:       yanked
Dependency tree: 
quick-xml 0.23.0
```

Opendal's dependency is yanked. CC: @Xuanwo

_Originally posted by @zhang2014 in https://github.com/datafuselabs/databend/issues/7542#issuecomment-1244831924_

**Comment by Xuanwo** [comment]
Should be fixed in https://github.com/datafuselabs/databend/pull/7577
