### ISSUE TITLE
[roadmap-track] functions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#758]
Main issue tracking for functions.

# Functions

| Task                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [VERSION() #762 ](https://github.com/datafuselabs/datafuse/issues/762) | DONE  | v0.5  |  Thanks @PsiACE |
| [SLEEP() #802](https://github.com/datafuselabs/datafuse/issues/802)| DONE | v0.5  | |
| [LIKE/NOT LIKE #784](https://github.com/datafuselabs/datafuse/issues/784)| DONE | v0.5  | Thanks @b41sh |
| [Conditional Functions #918](https://github.com/datafuselabs/datafuse/issues/918) |DONE| v0.5 | |
| [window funnel function #966](https://github.com/datafuselabs/datafuse/issues/966) |DONE| v0.5 | |
| [Type Conversion Functions #967](https://github.com/datafuselabs/datafuse/issues/967) |DONE| v0.5 | Thanks @wangzhen11aaa  |
| [std  #967](https://github.com/datafuselabs/datafuse/issues/1469) |DONE| v0.5 |   |
| [runningDifference #1787](https://github.com/datafuselabs/datafuse/issues/1787)| DONE|v0.5  | |
| [Date/DateTime track #853](https://github.com/datafuselabs/datafuse/issues/853) |PROGRESS|v0.5  |Very useful for timeseries queries |
| [more functions working with number #2563](https://github.com/datafuselabs/datafuse/issues/2563) |PROGRESS| | |
| [EXTRACT #428](https://github.com/datafuselabs/datafuse/issues/428)| PLANNING| v0.5 | |
| [IN (...) #826](https://github.com/datafuselabs/datafuse/issues/826)| PLANNING|v0.5  | |
| [Encryption functions #2162](https://github.com/datafuselabs/datafuse/issues/2162)| PLANNING|v0.5  | |
| [MATERIALIZE]| PLANNING| | |

**Comment by zhang2014** [comment]
Add:
sleep(N seconds) for test:  sleep function allows to suspend the query for N seconds
materialize([column1, column2, ...]) for performance test: materialize function allows Scalar columns to convert  to Array columns. useful for performance testing.

**Comment by BohuTANG** [comment]
Add:
`like` `not like`

**Comment by BohuTANG** [comment]
Add:
`EXTRACT` https://github.com/datafuselabs/datafuse/issues/428

**Comment by zhang2014** [comment]
Add:
IN Operator #826

**Comment by zhang2014** [comment]
Add:
toStartOfInterval: https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/#tostartofintervaltime-or-data-interval-x-unit-time-zone

**Comment by BohuTANG** [comment]
Add:
Date/DateTime : https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/

**Comment by BohuTANG** [comment]
Add:
[Conditional Functions #918](https://github.com/datafuselabs/datafuse/issues/918)

**Comment by BohuTANG** [comment]
Add:
[window funnel function #966](https://github.com/datafuselabs/datafuse/issues/966)

**Comment by BohuTANG** [comment]
Add:
[Type Conversion Functions #967](https://github.com/datafuselabs/datafuse/issues/967)

**Comment by BohuTANG** [comment]
Add:
 [runningDifference #1787](https://github.com/datafuselabs/datafuse/issues/1787)|

**Comment by BohuTANG** [comment]
Add:
Encryption functions #2162

**Comment by Xuanwo** [comment]
Are we still tracking functions on this issue not?

- If true, we need to do some update
- If not, I prefer to close this issue.

**Comment by zhang2014** [comment]
Most the items in the list have been finished or there are other issues to track them. yes. Let's turn it off.
