### ISSUE TITLE
Feature:  delay start the worker when processing a simple select query.

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#7594]
**Summary**
when query the hive data with `select * from xx limt 10w`, it takes about 3s and mainly caused by hive source operator(about 2.5s),  the network is fullfilled by 60 hive source workers (`max_threads` is set to 60).
for a simple select query , we may start workers one batch by another, not start all at once, this lead two benefits:
1. reduce the query process time,  in our test , it reduced from 3s to 1.2s. (depends on the bussiness of  network band width)
2. reduce the resource cost, ideally we just need to read partical data to satisfy the limit .

**Comment by sandflee** [comment]
inital implemented in #7595 ,  but not a beautiful solution,
1. only support for hive engine, not a generic way
2. could't get groupby&order by info in `is_simple_select_query`

any advice & thought?

**Comment by zhang2014** [comment]
Maybe we can implement pushdown limit for hive table?
By the way, in the executor, when the number of returned parts decreases, we will reduce the number of threads

FuseTable example:
https://github.com/datafuselabs/databend/blob/c3abc4ad08f763feba898cfa77e829fc04a58cc5/src/query/storages/fuse/src/pruning/pruning_executor.rs#L113-L145

**Comment by sandflee** [comment]
> Maybe we can implement pushdown limit for hive table? 
thanks for you advice, limit pushdown is a good solution,  but seems it could't applied to hive unfortunately，because in hive storage we just have table&partition meta not file&block meta in planing phase.
