### ISSUE TITLE
[arrow] Disable arrow-testing when building arrow

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#760]
**Summary**
When we building arrow, the submodule arrow-testing(test datas) will be download automatically, datafuse should disable it because we don't need.

**Comment by PsiACE** [comment]
Caused by git submodule? Wait for arrow to be published to crates.io, or maintain a fork without test data.

**Comment by BohuTANG** [comment]
Yes, it's the submodule.

**Comment by Xuanwo** [comment]
@BohuTANG Is this issue still going on?
