### ISSUE TITLE
bug: databend.rs blog Edit url not work

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7619]
**Summary**

https://databend.rs/blog/json-datatypes
![image](https://user-images.githubusercontent.com/172204/190303378-284a703b-96d9-4fb2-8cc5-f03fddaf2d29.png)

Such as this blog post, the `Edit this page` will go to https://github.com/datafuselabs/databend/edit/main/databend/blog/blog/2022-09-14-json-datatype.md

**Comment by Xuanwo** [comment]
Let's me fix this.
