### ISSUE TITLE
bug: copy into @s3 from table cannot be executed after version 0.8.34

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#7620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

above 0.8.33

### What's Wrong?

![image](https://user-images.githubusercontent.com/30121694/190304778-38742c9c-8627-452a-98cf-989bc6c93fbc.png)
![image](https://user-images.githubusercontent.com/30121694/190304914-0cd19f6e-6d8d-43af-b6e5-54b0eaf0270d.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yufan022** [comment]
This problem will not occur in version 0.8.33

**Comment by Xuanwo** [comment]
Hi, can you share the welcome message that printed by `databend-query` while starting?

**Comment by yufan022** [comment]
```
Databend Query

Version: v0.8.35-nightly-cd2b77e-simd(rust-1.64.0-nightly-2022-09-14T16:38:40.248371429Z)
Log:
    File: enabled=true, level=DEBUG, dir=/server/logs
    Stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=INFO
Meta: connected to endpoints [
    "172.xxx:9191",
    "172.xxx:9191",
    "172.xxx:9191",
]
Storage: s3://bucket=xxx,root=,endpoint=https://s3.xxx.amazonaws.com

Admin
    listened at 0.0.0.0:8081
MySQL
    listened at 0.0.0.0:3307
    connect via: mysql -uroot -h0.0.0.0 -P3307
Clickhouse(http)
    listened at 0.0.0.0:8125
    usage:  echo 'create table test(foo string)' | curl -u root: '0.0.0.0:8125' --data-binary  @-
echo '{"foo": "bar"}' | curl -u root: '0.0.0.0:8125/?query=INSERT%20INTO%20test%20FORMAT%20JSONEachRow' --data-binary @-
Databend HTTP
    listened at 0.0.0.0:8001
    usage:  curl -u root: --request POST '0.0.0.0:8001/v1/query/' --header 'Content-Type: application/json' --data-raw '{"sql": "SELECT avg(number) FROM numbers(100000000)"}'
```

**Comment by Xuanwo** [comment]
Today we merged some fixes that related to our underlying storage driver. Can you try upgrading the databend to today's releases?

I have tested the following query that works as expected:

```sql
copy into @test_copy from test_table FILE_FORMAT=(TYPE=NDJSON);
```

---

If this still does not work, we need to analyze your logging to investigate.

**Comment by yufan022** [comment]
![image](https://user-images.githubusercontent.com/30121694/190546603-e84cae33-2eae-4665-9aaf-0cc668ebb208.png)
it still can't work in version `v0.8.36`

**Comment by Xuanwo** [comment]
> it still can't work in version `v0.8.36`

Ok, something must be wrong here.

- How large about your table?
  - Does COPY with `limit` work?
    ```sql
    COPY INTO @stage 
         FROM (select name, age, id from test_table limit 100) 
         file_format = (type = 'ndjson')
    ``` 
- Can you provide the databend-query's log to us? You can send a mail to `xuanwo@datafuselabs.com`
- Is the simplest casework?
  ```sql
  -- Create a table
  CREATE TABLE test_table (
       id INTEGER,
       name VARCHAR,
       age INT
  );
  
  -- Insert data into the table
  insert into test_table (id,name,age) values(1,'2',3), (4, '5', 6);
  
  -- Create an internal stage
  CREATE STAGE s2;
  
  
  -- Unload the data in the table into the stage as a CSV file
  copy into @s2 from test_table FILE_FORMAT = (type = 'CSV');
  ```

**Comment by yufan022** [comment]
![image](https://user-images.githubusercontent.com/30121694/190547634-88014ed1-1556-4c84-964a-4371db94c1e3.png)

**Comment by yufan022** [comment]
```
[log]
level = "DEBUG"
dir = "/server/logs"
query_enabled = true
```
Is that of this directory?

**Comment by Xuanwo** [comment]
> Is that of this directory?

Yes. Logs generated under `DEBUG` could be huge. Please cleanup and start a new one to run the simplest case. And than send me the compressed logs.

**Comment by yufan022** [comment]
Log has been sent

**Comment by Xuanwo** [comment]
Hi, what meta-services version are you using? Are they work correctly? I read a lot logs like the following: `connection error: connection error: not connected`

Please try to start a new query that uses the embed meta to run the same query for the test.

**Comment by yufan022** [comment]
meta version: 
```
Databend Metasrv

Version: v0.8.36-nightly-acd4841-simd(1.64.0-nightly-2022-09-15T16:36:10.903466034Z)
Log:
    File: enabled=true, level=INFO, dir=/server/logs1
    Stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=INFO
Id:
Raft Cluster Name: foo_cluster
Raft Dir: /server/meta1
Raft Status: join [
    "172.21.41.122:28103",
]

HTTP API
   listened at 0.0.0.0:28101
gRPC API
   listened at 0.0.0.0:9191
```

**Comment by yufan022** [comment]
I didn't find these logs `connection error: connection error: not connected` in `0.8.33`.

**Comment by yufan022** [comment]
Some new clues:
In version 0.8.36, If I start more than one query node, the `copy into @s2 from test_table` command will fail, and got these logs `connection error: connection error: not connected`.

**Comment by Xuanwo** [comment]
> In version 0.8.36, If I start more than one query node, the `copy into @s2 from test_table` command will fail, and got these logs `connection error: connection error: not connected`.

Thanks for the report. I reproduced this problem.

---

@zhang2014 Can you take a look? Seems related to our cluster.

Reproduce steps (on databend cloud):

- Prepare data
  ```sql
  -- Create a table
  CREATE TABLE test_table (
       id INTEGER,
       name VARCHAR,
       age INT
  );
  
  -- Insert data into the table
  insert into test_table (id,name,age) values(1,'2',3), (4, '5', 6);
  
  -- Create a test stage
  CREATE STAGE test;
  ```
- COPY INTO on `Medium` (the cluster mode) will hang forever
  ```sql
  copy into @test from test_table FILE_FORMAT = (type = 'CSV');
  ```
- COPY INTO on `small` (the standalone mode) will work
  ```sql
  copy into @test from test_table FILE_FORMAT = (type = 'CSV');
  ```

**Comment by sundy-li** [comment]
Version 0.8.34 release notes:

Thoughtful Bug Fix 🔧
fix(cluster): stop tasks in cluster when select limit by @zhang2014 in https://github.com/datafuselabs/databend/pull/7542
fix(cluster): do not to kill the query when the query recv finished. by @zhang2014 in https://github.com/datafuselabs/databend/pull/7590

**Comment by Xuanwo** [comment]
Hi, @yufan022. Thanks for your bug report again. Here is our final response.

The bug you reported has been addressed in https://github.com/datafuselabs/databend/pull/7679, which is included in releases `v0.8.38-nightly`. Please upgrade to any versions new than `v0.8.38-nightly` for verification.

To make bugs like this not happen again (thanks @zhang2014 for the quick fix):

- Added a SQL logic test case for `COPY INTO table`.
- Added a stateful cluster test that covered all COPY cases.

Feel free to report any bugs. Databend is much better with you.

**Comment by Xuanwo** [comment]
Reopen this issue to wait for the verification from @yufan022.

**Comment by yufan022** [comment]
Awesome. I'll confirm later.

**Comment by yufan022** [comment]
It has been fixed in the latest version.
