### ISSUE TITLE
[roadmap-track] queries 

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#765]
Main issue tracking for queries.

# Queries

| Queries                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [SHOW PROCESSLIST #1061](https://github.com/datafuselabs/datafuse/issues/1061) | DONE  | v0.5  | |
| [SHOW CREATE TABLE #901](https://github.com/datafuselabs/datafuse/issues/901)  | DONE  | v0.5  | Thanks @b41sh |
| [EXISTS #426](https://github.com/datafuselabs/datafuse/issues/426) | DONE | v0.5 | Thanks @jyizheng  |
| [Aggregate Function Cominators #768](https://github.com/datafuselabs/datafuse/issues/768) | DONE | v0.5 | |
| [Scalar subquery #1060](https://github.com/datafuselabs/datafuse/issues/1060) | DONE| v0.5 | |
| [ClickHouse insert #965](https://github.com/datafuselabs/datafuse/issues/1148)|DONE| v0.5 | |
| [http server handler #1359](https://github.com/datafuselabs/datafuse/issues/1359) | PROGRESS| v0.5 | @flaneur2020 @youngsofun  |
| [KILL QUERY]| DONE | v0.5 | Related: https://github.com/datafuselabs/datafuse/issues/204 |
| [MySQL DataType syntax]| DONE| v0.5 | |
| [ClickHouse DataType syntax]| DONE| | |
| [memory usage #1148](https://github.com/datafuselabs/datafuse/issues/1148) | DONE| v0.5 | |

**Comment by BohuTANG** [comment]
Exists issue:
https://github.com/datafuselabs/datafuse/issues/426

**Comment by BohuTANG** [comment]
Add:
SHOW CREATE TABLE #901

**Comment by zhang2014** [comment]
Add:
Support scalar subquery #1060

**Comment by BohuTANG** [comment]
Add:
[memory usage #1148](https://github.com/datafuselabs/datafuse/issues/1148) |

**Comment by sundy-li** [comment]
Add 
ClickHouse insert #965

**Comment by BohuTANG** [comment]
Add:
[http server handler #1359](https://github.com/datafuselabs/datafuse/issues/1359)

**Comment by BohuTANG** [comment]
Done!
