### ISSUE TITLE
Feature: Allow COPY FROM IPFS

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7659]
**Summary**

OpenDAL already has IPFS support. Databend can implement copy from ipfs now:

```sql
COPY INTO my_table FROM 'ipfs://QmHash' FILE_FORMAT=( TYPE = 'JSON' );
```

**Comment by Xuanwo** [comment]
Cc @ClSlaid, can you take this feature a look?

IPFS should be considered a read-only service, so we don't need to support using IPFS as backend, only need to be used as a stage.

**Comment by ClSlaid** [comment]
> For testing, please use:
> 
> ```sql
> COPY INTO ontime FROM 'ipfs://QmcG4khwaGZRsd8X11jbx9Y74SVas5NMDdvAyvLFnsyFwY'
>     FILE_FORMAT=( TYPE = 'CSV')
> ```
> 
> This path includes a `ontime_2006_100000.csv` dataset.

This is a directory and is pretty hard to implement, since `QmcHash`s doesn't tell whether it's a file or a directory.

To make the implementation simple, let's force the directories' ending with a '/'.
