### ISSUE TITLE
Feature: use goldenfile for logictest file

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7666]
**Summary**

Small changes may require modification of multiple logic tests results

Manually changing them one by one is too painful :(

**Comment by hanyisong** [comment]
can i do it?

**Comment by hanyisong** [comment]
> **Summary**
> 
> Small changes may require modification of multiple logic tests results
> 
> Manually changing them one by one is too painful :(

for example?

**Comment by hanyisong** [comment]
@xudong963 Can I understand that part of the goldenfile is ported to sqllogictest for unified maintenance?

e.g. I compared https://github.com/datafuselabs/databend/blob/main/src/query/functions-v2/tests/it/scalars/variant.rs and https://github.com/datafuselabs/databend/blob/main/tests/logictest/suites/base/02_function/02_0048_function_semi_structureds_parse_json and found that their test content is the same, I think goldenfile can be deleted directly

**Comment by xudong963** [comment]
> Can I understand that part of the goldenfile is ported to sqllogictest for unified maintenance?

No.

The current situation is that the logic test files need to be modified each time manually.

For the golden file, we can just generate a new test result file with `REGENERATE_GOLDENFILES=1`, and then just check if the new result is reasonable, which can significantly reduce the cost of maintaining the test.
