### ISSUE TITLE
test: move https://github.com/youngsofun/clickhouse-sqlalchemy/archive/ to https://github.com/datafuse-extras

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7673]
**Summary**

Databend logictest test docker used: `https://github.com/youngsofun/clickhouse-sqlalchemy/archive/a116e3162c699c12e63a689385b547f639c13018.zip`
https://github.com/datafuselabs/databend/blob/e4c371cf49830765e4abcca775248bf030e9e7ce/tests/logictest/Dockerfile#L18

We should move the zip to datafuse-extras.

**Comment by youngsofun** [comment]
clickhouse handler not tested any more, no longer need the dep
