### ISSUE TITLE
crate: move github.com/<personal> source code dep to datafuse-extras

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7696]
**Summary**

To make Databend dependencies more robust, we need to move these source code deps  into https://github.com/datafuse-extras if they cant not publish as a crate.

1. `ordered-float = { git = "https://github.com/andylokandy/rust-ordered-float.git", branch = "as", features = ["serde"] }`
2. `http-types = { git = "https://github.com/Xuanwo/http-types", rev = "106fc6d" }`

**Comment by BohuTANG** [comment]
cc @andylokandy , @Xuanwo

**Comment by Xuanwo** [comment]
I will revert http-types to upstream after the toolchain is bumped, which will happen this week.

**Comment by Xuanwo** [comment]
> 1. ordered-float = { git = "https://github.com/andylokandy/rust-ordered-float.git", branch = "as", features = ["serde"] }

Related to https://github.com/reem/rust-ordered-float/issues/111

**Comment by Xuanwo** [comment]
https://github.com/reem/rust-ordered-float/releases/tag/v3.1.0

v3.1.0 has been released.

Cc @xudong963, please upgrade this crate during toolchain bump.
