### ISSUE TITLE
doc: add more inforamtion for FUSE_BLOCK

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7715]
**Summary**
https://databend.rs/doc/reference/functions/system-functions/fuse_block

FUSE_BLOCK is very useful, users can read a fuse engine parquet file list under a snapshot, allowing downstream to continue consuming this data.

**Comment by BohuTANG** [comment]
cc @soyeric128

**Comment by soyeric128** [comment]
I'm a little confused about the differences between **fuse_block** and **fuse_segment**. Can you help confirm if these descriptions are correct:

- Databend stores the history data for the snapshots in both formats: parquet and JSON. 
- **fuse_block**: returns the parquet file locations.
- **fuse_segment**: returns the JSON file locations.

Thanks @BohuTANG @zhyass
