### ISSUE TITLE
Docs: Add show users  & show grants 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#7726]
**Summary**
https://databend.rs/doc/reference/sql/ddl/user

list databend current user list:
```
show users;
```

Check user:  'wubx'@'%'  privileges:
```
show grants for 'wubx'@'%';
```

**Comment by Xuanwo** [comment]
Cc @soyeric128, can you help with this issue?

**Comment by soyeric128** [comment]
> Cc @soyeric128, can you help with this issue?

Sure
