### ISSUE TITLE
count distinct bug

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#7743]
```SELECT COUNT(DISTINCT SearchPhrase) FROM hits ```  return 3744 rows
``` SELECT COUNT(DISTINCT SearchPhrase) FROM hits``` return 3756， （diff num for each query）

how to reproduce:
-----

1. pull this pr  and start standalone
2.  serve http file local

```
curl https://repo.databend.rs/dataset/stateful/hits_100k.tsv
python -m  http.server 80
```
3. sql

```
COPY INTO hits FROM 'http://loaclhoust/hits_100k.tsv' FILE_FORMAT = ( type = 'tsv' record_delimiter = '\n' skip_header = 1 )
```

-----

``` SELECT COUNT(DISTINCT SearchPhrase) FROM  (select SearchPhrase from hits order by SearchPhrase) ```   is 3744

`set max_threads=1`  before copy fix it, so it is a bug COUNT DISTINCT with multi partition

_Originally posted by @youngsofun in https://github.com/datafuselabs/databend/issues/7613#issuecomment-1251790261_

**Comment by sandflee** [comment]
we encountered ` count distinct ` too,  waiting to be fixed
