### ISSUE TITLE
Tracking issue of bloom filter refactoring

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#7748]
## Problems

- Bloom filter index takes too much storage space, e.g., about 50% of the original data size.
- With a bloom filter index, an exact-match query from 10 billion rows still takes minutes.

The goals are:
- to try to accelerate queries, at least for explicitly simple queries.
- to reduce index size if possible.

Issues:

- #7379
- #7674

Let me know if there are any other issues related bloom filter.:)

## Status

- 2022-09-20: It's still under investigation and I can not tell for now what will be done:(

**Comment by drmingdrmer** [comment]
@BohuTANG @dantengsky @sundy-li @youngsofun

**Comment by BohuTANG** [comment]
@drmingdrmer 

We will first try the XOR filter instead of the old raw bloom filter, then @dantengsky will help me to adapt the raw bloom filter to the new XOR filter.
The new XOR filter is here:
https://github.com/datafuselabs/databend/pull/7860

From my test, it looks great, let's try :)

**Comment by BohuTANG** [comment]
@drmingdrmer 

I have moved the issues related to the index(not only the bloom filter) to https://github.com/datafuselabs/databend/issues/7823. Let's close this :)
