### ISSUE TITLE
CopyInterpreterV2.list_files can be same with InterpreterCommon.list_files

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7755]
### Discussed in https://github.com/datafuselabs/databend/discussions/7754

<div type='discussions-op-text'>

<sup>Originally posted by **BohuTANG** September 20, 2022</sup>

https://github.com/datafuselabs/databend/blob/d7a43c9d56ec1acc9751768146b4c3fff9770459/src/query/service/src/interpreters/interpreter_copy_v2.rs#L158-L211

https://github.com/datafuselabs/databend/blob/d7a43c9d56ec1acc9751768146b4c3fff9770459/src/query/service/src/interpreters/interpreter_common.rs#L182-L274

</div>

**Comment by BohuTANG** [comment]
Fixed #7762
