### ISSUE TITLE
chore: disable old interpreter create

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7757]
**Summary**

It's time to disable the old interpreter create:

https://github.com/datafuselabs/databend/blob/6fdcc087431b9f9625c9352f6a6a5e987531656c/src/query/service/src/interpreters/interpreter_factory.rs#L54-L66

**Comment by BohuTANG** [comment]
@zhang2014 @Xuanwo 

I think it's time to remove them, what do you think?

**Comment by Xuanwo** [comment]
I'm willing to remove them? @zhang2014 do you still need?
