### ISSUE TITLE
[Store] Add test: raftmeta: check to-non-voter replication when leader transfered.

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#776]
**Summary**

Test replication to non-voters works as expected when raft leader changes. Reference:

https://github.com/datafuselabs/datafuse/blob/fbe6bd8d3f761736ca03a1c932753320cd54e1b8/fusestore/store/src/meta_service/raftmeta_test.rs#L208-L238

Note:
async-raft does not store non-voters. A leader adds non-voters after when it is established.

**Comment by Xuanwo** [comment]
If this issue still going on or should be transferred to OpenRaft?

**Comment by drmingdrmer** [comment]
The next version of openraft stores non-voter persistently. There is already a test for such a case. But databend has not yet upgraded openraft to the latest version.

It's gonna be closed when upgrade finished.

**Comment by Xuanwo** [comment]
openraft has been bumped many times since last comments. Closing now.
