### ISSUE TITLE
try avoid compactor for copy into/streaming load with row-based format

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#7760]
for copy into/streaming load with row-based format, the best place to cut rows to blocks is block builder.

compactor can be avoided (not need to remove this processor,  only not do any real compact is enough)

need to: 

1.  get the 3 related tables options (but fuse table only) of the writing table,  and let the deserialize processor of  StageTable know it
2. able to estimate the size (not rows) of a building block. (but a cost to check it after each row append,  check it in an adaptive interval: estimate row size,  )

I will start with  use DEFAULT_ROW_PER_BLOCK * 0.8 ( try not to exceed size limit)

----

another choice is to produce small block from stageTable. guess merging tables is faster than splitting it?

@zhyass @dantengsky

**Comment by youngsofun** [comment]
the problem of  `estimate the size ` is solved  in #7927 
even better than expected.

**Comment by dantengsky** [comment]
> compactor can be avoided (not need to remove this processor, only not do any real compact is enough)

:+1:   great insight!
@zhyass is working on a task that splits the operations of a table into fine-grained `processors`,  which I think will provide more composability,  e.g. remove the `compactor` processor from the pipeline, or customize it.

**Comment by youngsofun** [comment]
done
