### ISSUE TITLE
feat: make `table.read_partitions` distributed

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#7805]
**Summary**

`table.read_partitions` may do many IO operations, such as the min-max index filter or bloom filter index filter.
If a table has many partitions, the `read_partitions` will be very slow.

For distributed, we can:
1. `read_partitions` return segments instead of partition if the segments > 1000
2. Distribute the `Partitions` to cluster
3. In `read2`, to check file is `segment` or `partition` file

**Comment by BohuTANG** [comment]
cc @dantengsky

**Comment by Xuanwo** [comment]
I expect to decouple `ReadDataSourcePlan` from the `Table` API in https://github.com/datafuselabs/databend/issues/7816.

Please let me know if anything I can help with. @zhang2014

**Comment by BohuTANG** [comment]
Impl in https://github.com/datafuselabs/databend/pull/7867 cc @zhang2014
