### ISSUE TITLE
`Database` trait add table API.

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#7819]

**Comment by BohuTANG** [comment]
@lichuang Could you give more background about this issue?

**Comment by lichuang** [comment]
> @lichuang Could you give more background about this issue?

In order to support `share database` query tables.

In API such as `catalog.get_table(tenant, db_name, table_name)`, catalog just pass `(tenant,db_name,table_name)` to meta, if it is a normal table, it will works fine.

But if `(tenant,db_name,table_name)` is a shared table, it may happen that this meta service has no share table meta.

So we need to add table API into Database trait, move all Table API in catalog route to Database trait. 

Take the `catalog.get_table(tenant, db_name, table_name)` API for example:

1. first get Database trait impl(now has only default database impl, but there will be share database impl for Database trait).
2. And if found Database is a share database, the share database impl for Database trait will route the table request to the meta which the provider located.
