### ISSUE TITLE
[function] Add Description and Example for function

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#783]
**Summary**

1. Add description and example to function trait
```
 fn description(&self) ->&str {        
    "returns the minimum value in a set of values"
 }

 fn example(&self) ->&str {        
    "SELECT MIN(*) FROM numbers(3)"
 }
```

2. system.functions
mysql> select * from system.functions;

| name   |      is_aggregate      |  return_type |  description | example |
|----------|:-------------:|------:|------:|------:|

**Comment by sundy-li** [comment]
So we can generate the docs for functions from sql.

**Comment by BohuTANG** [comment]
Good idea @sundy-li

**Comment by BohuTANG** [comment]
This is useful for user, they can only find all the usage from the system.functions instead of going back to the documentation.

**Comment by zhang2014** [comment]
Cool!, anything is SQL

**Comment by PsiACE** [comment]
Love it.

**Comment by PsiACE** [comment]
#3258
