### ISSUE TITLE
rm (while in processor thread 0) in error message?

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#7839]
some tests expect exact error message

while the number 0 may change for each run.

---

it useless to user https://github.com/datafuselabs/databend/issues/8094

cc @zhang2014

**Comment by Xuanwo** [comment]
Can we check error code?

**Comment by youngsofun** [comment]
1.  sometimes we want to give a pretty error message, like SQL syntax error,  which point out where is the error,  what I encounter is format error, although not need to be as pretty as sql syntax error.
2.  the are error like the sql syntax error or format can not have an error code for each case

currently I use `| grep -c 'somekeyword'`  or `| head -c N` to work around
