### ISSUE TITLE
flaky test test_alter_recluster_interpreter

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#7849]
flaky test test_alter_recluster_interpreter
https://github.com/datafuselabs/databend/actions/runs/3112438121/jobs/5045863994

cc @zhyass

_Originally posted by @youngsofun in https://github.com/datafuselabs/databend/issues/7843#issuecomment-1256122602_

**Comment by youngsofun** [comment]
fail again https://github.com/datafuselabs/databend/actions/runs/3128514569/jobs/5076454171

**Comment by Xuanwo** [comment]
Seems stable now, let's close.
