### ISSUE TITLE
CopiedFileTable could be updated even copy failed

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7856]
**Summary**

`CopiedFileTable` could be updated even when we met an error during the copy. And users can't copy the same file again because the ETag matches and been filtered.

Cc @lichuang

**Comment by zhang2014** [comment]
https://github.com/datafuselabs/databend/actions/runs/3149439345/jobs/5121266930

**Comment by Xuanwo** [comment]
Has been fixed.
