### ISSUE TITLE
bug: `COPY INTO` command cannot import data from s3 with massive files or directories

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#7862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.39

### What's Wrong?

`COPY INTO` command cannot import data from s3 with massive files or directories.

dev s3:
![image](https://user-images.githubusercontent.com/30121694/192090536-6f206278-48b4-45fc-8b53-c036454d7814.png)

We have many files and directories in s3, the structure is as follows:
```
s3://xx/1/20220923/xxx001.json
s3://xx/1/20220923/xxx002.json
...
s3://xx/1/20220924/xxx001.json

s3://xx/2/
s3://xx/3/
...
s3://xx/99999999/...
```

```
COPY INTO xx
  FROM 's3://xx'
  credentials=(aws_key_id='xx' aws_secret_key='xx')
  pattern ='.*[.]json'
  file_format = (type = 'ndjson');
```

The `COPY INTO` command is currently unavailable and cannot start importing data

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Should be fixed.
