### ISSUE TITLE
bug: high latency of SQL request

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#7878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.47-nightly

### What's Wrong?

high latency of SQL request

### How to Reproduce?

```
mysql> create database db;
Query OK, 0 rows affected (0.52 sec)

mysql> use db;
Database changed
mysql> create table tb (a int);
Query OK, 0 rows affected (1.44 sec)

mysql> show tables;
+--------------+
| tables_in_db |
+--------------+
| tb           |
+--------------+
1 row in set (2.32 sec)
Read 26 rows, 3.62 KiB in 0.925 sec., 28.11 rows/sec., 3.91 KiB/sec.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by johnhaxx7** [comment]
Hi @drmingdrmer , I think maybe this can be closed?
