### ISSUE TITLE
Streaming COPY

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#7889]
## Background

Databend will list all files before copying data:

https://github.com/datafuselabs/databend/blob/46da962d5637b35555e8f3f49885d1b58211ab41/src/query/service/src/interpreters/interpreter_copy_v2.rs#L399-L460

This will lead to:

- https://github.com/datafuselabs/databend/issues/7862

We need to introduce streaming copy which will copy simultaneously during the listing.

## Problems

- GetTableCopiedFileReply will return all files
- UpsertTableCopiedFileReq requires update all copied files at once

We need to change them to streaming-friendly. For example, only check a batch of files.

## Tasks

- [x] https://github.com/datafuselabs/databend/issues/7892
- [ ] Copy file streamingly

**Comment by Xuanwo** [comment]
Cc @lichuang

**Comment by BohuTANG** [comment]
Before this work, I think we should finished https://github.com/datafuselabs/databend/issues/7755

**Comment by ClSlaid** [comment]
further update on this?

**Comment by Xuanwo** [comment]
Wait for https://github.com/datafuselabs/databend/issues/7892

**Comment by lichuang** [comment]
> Wait for #7892

#7892 will be processed after finishing share table impl

**Comment by lichuang** [comment]
https://github.com/datafuselabs/databend/issues/7892 has been closed.

**Comment by Xuanwo** [comment]
There are other works to finish on copy side. Let's reopen it.

**Comment by BohuTANG** [comment]
I will take this, we need to consider more situations:
If `COPY` will be distributed, streaming reading files in `StageTable:read_partitions` is hard.
For now, it looks better to follow the current mechanism for copying. If a bucket has many files, now *slow*(list files) is by design.

cc @Xuanwo

**Comment by Xuanwo** [comment]
> streaming reading files in `StageTable:read_partitions` is hard.

Partitions scanning and data reading are different kinds of workloads that can be executed at the same time. Adding this feature will also improve the performance of `FuseTable`.

**Comment by BohuTANG** [comment]
New COPY design will be use StageTable as table engine and re-use the planner& pipeline distribution:
https://github.com/datafuselabs/databend/issues/8635
