### ISSUE TITLE
bug: optimize get/upsert copied file info

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#7892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

current version

### What's Wrong?

bug: optimize get/upsert copied file info.
when `copy into table` has many files, there will be some problem if get/upsert copied file once time.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
This issue related to https://github.com/datafuselabs/databend/issues/7943?
