### ISSUE TITLE
[plan] Add set_description for plan and actions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#790]
**Summary**

Like ClickHouse does, shows each step or action in more detail for the explain or log dump.

Example:
![image](https://user-images.githubusercontent.com/172204/121305128-cd4db580-c92f-11eb-92ae-63f7046ab68a.png)

https://github.com/ClickHouse/ClickHouse/blob/7e610b54771e15cb2e701165d2e2c8b315a7da42/src/Interpreters/InterpreterSelectQuery.cpp#L2446-L2448

**Comment by jyz0309** [comment]
I have no idea about adding set_description for planner. Do I just need to add it in planBuider?

**Comment by BohuTANG** [comment]
Hi @jyz0309 
I think this issue is a low priority and does not appear to be used at the moment.
It would be more appropriate to start this task when the planner refactoring https://github.com/datafuselabs/databend/issues/1217 is complete.

**Comment by Xuanwo** [comment]
Closing for this task is not useful.
