### ISSUE TITLE
Add stateful test for copy files from FTP

### ISSUE THREAD

**Issue by ClSlaid** [datafuselabs/databend#7902]
**Summary**

Copying files via FTP and FTPS has been added by #7844, but the PR missed stateful tests on the protocol.

**Comment by ClSlaid** [comment]
we could test with:

ftp://dtn.rc.colorado.edu/shares/snow-today/WY2022/SWESummary/SnowToday_USwest_20220901_SWEsummary.txt

**Comment by Xuanwo** [comment]
Interestingly, there are so many living FTP servers...
