### ISSUE TITLE
bug: unreasonable parser error reporting

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#7904]
**Summary**
table `pairs` has column `a`, but the following SQL reports **column doesn't exist**
<img width="762" alt="image" src="https://user-images.githubusercontent.com/41979257/192283194-e9281e15-279b-43e0-b9a9-8ac9e40a87ee.png">

Maybe it should report `semi join` isn't supported in parser

**Comment by xudong963** [comment]
cc @andylokandy

**Comment by andylokandy** [comment]
this error is reported from binder, cc @leiysky

**Comment by leiysky** [comment]
We don't support `SEMI JOIN` syntax. This query will be treated as `select * from "pairs" as "semi" join square on pairs.a = square.n`.

I think this is as expected, maybe we can close the issue? @BohuTANG @andylokandy

**Comment by andylokandy** [comment]
maybe we can reserve semi.

**Comment by xudong963** [comment]
Maybe after finishing https://github.com/datafuselabs/databend/issues/7906, the error reporting will be reasonable.

**Comment by xudong963** [comment]
solved
