### ISSUE TITLE
Feature:  `optimize compact` performance improvement

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#7914]
**Summary**

Execution of `Optimize table x compact` statement is rather conservative, utilization of CPU / Bandwidth is rather low.

**Comment by BohuTANG** [comment]
`compact` read segment files is not parallel, so it's slow:
https://github.com/datafuselabs/databend/blob/main/src/query/storages/fuse/src/operations/mutation/compact_mutator.rs#L95-L155

**Comment by BohuTANG** [comment]
Another improvement is to compact by batch instead read all the segments one by one compact.

**Comment by BohuTANG** [comment]
I am trying to read segments in parallel using `read_segments`
