### ISSUE TITLE
Feature: support auth with aliyun RRSA OIDC Token

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#7917]
**Summary**

ref: https://www.alibabacloud.com/help/zh/container-service-for-kubernetes/latest/use-rrsa-to-enforce-access-control

**Comment by Xuanwo** [comment]
To implement this support, we need to:

- [ ] Add aliyun support for reqsign @Xuanwo 
- [ ] https://github.com/datafuselabs/opendal/issues/372

**Comment by mozillazg** [comment]
@Xuanwo Is there any update on this feature?

**Comment by Xuanwo** [comment]
> @Xuanwo Is there any update on this feature?

All required features has been implemented now.

**Comment by mozillazg** [comment]
> > @Xuanwo Is there any update on this feature?
> 
> All required features has been implemented now.

@Xuanwo Glad to hear that 👍. Do you have any plans to support this feature?

**Comment by Xuanwo** [comment]
Oh, all features already implemented in databend😂

Are you meeting problems while using them?

**Comment by mozillazg** [comment]
> Oh, all features already implemented in databend😂
> 
> Are you meeting problems while using them?

😂 I haven't tried it yet, I just want to confirm the current status of this issue.
Perhaps we can consider closing this issue if the feature is already supported?
