### ISSUE TITLE
Feature: support `ignore` in COPY

### ISSUE THREAD

**Issue by ClSlaid** [datafuselabs/databend#7919]
**Summary**

https://databend.rs/doc/reference/functions/other-functions/ignore

`INSERT INTO` supports IGNORE, but `COPY INTO` doesn't. This will make copying from some casually formed datafiles possible.

**Comment by Xuanwo** [comment]
We used to have an `ignore-errors` in COPY. Cc @BohuTANG

**Comment by BohuTANG** [comment]
We should use Copy Options to do that, not the statement keyword, see snow [Copy Options](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table.html#copy-options-copyoptions):
```
ON_ERROR = CONTINUE | SKIP_FILE | SKIP_FILE_num | 'SKIP_FILE_num%' | ABORT_STATEMENT
```
