### ISSUE TITLE
bug: copy from ndjson file OOM

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#7923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.8.45

### What's Wrong?

```
mysql> COPY INTO xx
    ->   FROM 's3://xx/xx/'
    ->   credentials=(aws_key_id='xx' aws_secret_key='xx')
    ->   pattern ='123.output'
    ->   file_format = (type = 'ndjson');
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

```
[ec2-user@query1 ~]$ journalctl -k
...
Sep 27 10:43:02 query1 kernel: Out of memory: Kill process 26362 (databend-query) score 980 or sacrifice child
Sep 27 10:43:02 query1 kernel: Killed process 26362 (databend-query) total-vm:110402676kB, anon-rss:41238024kB, file-rss:0kB, shmem-rss:0kB
Sep 27 10:43:04 query1 kernel: oom_reaper: reaped process 26362 (databend-query), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

```
create table xx(
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x BIGINT UNSIGNED NULL,
    x BIGINT UNSIGNED NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x OBJECT NULL,
    x OBJECT NULL,
    x VARCHAR NULL,
    x VARCHAR NULL,
    x VARCHAR NULL
);
```
![image](https://user-images.githubusercontent.com/30121694/192515318-7929a87f-97a4-44de-bc19-4c25007bf904.png)

EC2: 16c40g c5n.4xlarge

The source file is about 1.1 million lines, each row is a NDJSON.

OOM when using the COPY command to import a single 35GB file from S3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
it is my fault,  current impl accumulate 800K rows before writing each block. 
it should consider the size too


https://github.com/datafuselabs/databend/blob/v0.8.45-nightly/src/query/pipeline/sources/src/processors/sources/input_formats/input_context.rs#L46


related issue https://github.com/datafuselabs/databend/issues/7760
