### ISSUE TITLE
Feature: support Array functions

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#7931]
**Summary**

Description for this feature.

## common functions for array   @TCeason 

- [x] #9803
- [x] length
- [x] array_contains(arr, elem)  alias `array_has`
- [x] #9839
- [x] array_slice(array, offset[, length])
- [x] #9940
- [x] array_reverse_sort(array) // array_sort now contains this feature.

## aggr combinators  @b41sh 

- [x] array_unique(array)   Counts the unique elements of a list.
- [x] array_distinct(array) Removes all duplicates and NULLs from a list.
- [x] array_aggr(array, 'agg'), aka `array_<aggr>(array)`,  eg: `array_aggr([1,2,3], 'sum')`, `array_aggr([1,2,3], 'avg')`, `array_sum([1,2,3]`
- [x] array_prepend(element, array)
- [x] array_append(array, element)
- [x] array_any_value(array)

## low-priority tasks:

- [x] array_transform(array, lambda)    (low-priority), eg: `array_transform([1,2,3], x -> x + 1)`
- [x] array_filter(array, lambda)    (low-priority), eg: `array_filter([1,2,3], x -> x > 1)`
- [ ] python style array comprehension (low-priority), eg: `select [x+3 for x in [1,2,3]]`
- [ ] array_join(array)
- ...

**Comment by BohuTANG** [comment]
Comments by @sundy-li :
1. https://duckdb.org/docs/sql/functions/nested
2. After the new expression is done.(Middle of November)

**Comment by BohuTANG** [comment]
@sundy-li 

There are two array-related aggregate functions are required from the user:
- [ ] array_reduce https://clickhouse.com/docs/en/sql-reference/functions/array-functions/#arrayreduce
- [ ] group_array_moving_avg https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparraymovingavg/

ClickHouse SQL like:
```
select UserID,  c, arrayReduce('count',RequestNum1) from (  
  select UserID, count(RequestNum) as c, groupArrayMovingAvg(50)(RequestNum) as RequestNum1 from
    (select UserID, RequestNum from hits_v1 order by RequestNum DESC)  
  group by UserID order by c DESC limit 1000)
```

Or are these two functions easy to use window functions?

**Comment by sundy-li** [comment]
we have `array_<aggr>` which covert `arrayReduce` function.

`group_array_moving_avg ` can be implemented after we have window aggr function.
