### ISSUE TITLE
bug: unknown reasons caused the query to get stuck.

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#7945]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.52

### What's Wrong?

```
mysql> select version();
+-----------------------------------------------------------------------------------------+
| version()                                                                               |
+-----------------------------------------------------------------------------------------+
| 8.0.26-v0.8.52-nightly-9261eca-simd(rust-1.66.0-nightly-2022-09-28T03:51:50.509403405Z) |
+-----------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select count(1) from xx;
+-----------+
| count(1)  |
+-----------+
| 263307900 |
+-----------+
1 row in set (0.10 sec)
Read 1 rows, 1.00 B in 0.034 sec., 29.52 rows/sec., 29.52 B/sec.

mysql> select snapshot_id, segment_count, block_count, row_count from fuse_snapshot('default', 'xx');
+----------------------------------+---------------+-------------+-----------+
| snapshot_id                      | segment_count | block_count | row_count |
+----------------------------------+---------------+-------------+-----------+
| c867dfea85d44bdcb5581714151a8fb8 |            56 |       24310 | 263307900 |
| b8543c04843f489094ea66651e353cf2 |         15716 |       34764 | 263307900 |
+----------------------------------+---------------+-------------+-----------+
2 rows in set (0.60 sec)
Read 2 rows, 460.00 B in 0.585 sec., 3.42 rows/sec., 786.00 B/sec.

top - 10:52:55 up 16:07,  7 users,  load average: 15.28, 15.82, 14.49
Tasks: 223 total,   2 running, 118 sleeping,   0 stopped,   0 zombie
%Cpu0  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  : 99.7 us,  0.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu7  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu8  :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu9  : 47.7 us,  2.7 sy,  0.0 ni, 49.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu10 : 99.7 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu11 :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu12 : 98.0 us,  0.7 sy,  0.0 ni,  1.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu13 : 99.7 us,  0.3 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu14 : 59.0 us,  0.3 sy,  0.0 ni, 40.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu15 :100.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 42226780 total,  9024232 free, 32427480 used,   775068 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  9351928 avail Mem

```

![image](https://user-images.githubusercontent.com/30121694/192762336-8d078db9-aecf-49d4-93be-429f2c03acb0.png)

jaeger:
![image](https://user-images.githubusercontent.com/30121694/192781490-e5e46a56-55b5-4da1-bb4c-e6cb80c6ff91.png)
![image](https://user-images.githubusercontent.com/30121694/192778038-619e51a1-2aa9-4b4c-b76b-a616188d06eb.png)
![image](https://user-images.githubusercontent.com/30121694/192778190-e5647321-396e-4eb6-a805-6a9dfa54b3ff.png)

s3:
![image](https://user-images.githubusercontent.com/30121694/192780271-033b0b35-54c1-42df-9bc0-f51fa1b028cc.png)
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/30121694/192781022-fa43699f-3136-4b3a-9c61-ea31349fd172.png">
![image](https://user-images.githubusercontent.com/30121694/192781274-bcc24256-a7af-4bf6-9524-27a4a2fa9c44.png)

I checked these large files over 1G, and the last modified dates are basically from the 20th to the 23rd.

### How to Reproduce?

1. This table was created a week ago
2. Use `COPY INTO` load many 150MB files to this table
3. The load lasted all night.
4. Following morning, I tried to `select * from xx limit 1;`, it doesn't work.
5. Try `optimize table xx purge`, `optimize table xx compact`. Still can't finish the execution.
6. Kill databend-query process and restart
7. A few days later, deploy new version
8. Execute `select * from xx limit 1` commands, I found this problem

For the 1-5 steps, I may have used `v0.8.39` or earlier. for 8 step i use `v0.8.52`.

`optimize table purge/compact` or `select limit 1`
For these commands, Im not sure how many times I have executed them during this period.
But according to my understanding, these commands should be idempotent, no matter how many times they are executed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Because one segment file size is too larger: 1.5GB, normally it's 5MB.
Could you give more information about how you did on the table?

**Comment by yufan022** [comment]
> Because one segment file size is too larger: 1.5GB, normally it's 5MB. Could you give more information about how you did on the table?

I tried to recall the steps of reproduction, but I am not sure if it is accurate. This problem was triggered by me during the discovery of the #7861

**Comment by BohuTANG** [comment]
Outdated.
