### ISSUE TITLE
[roadmap-track] observability track

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#795]
Main issue tracking for observability.

# Tasks

| Task                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [http profiling #794 ](https://github.com/datafuselabs/datafuse/issues/794) | DONE  |  v0.5 |   |
| [http tracing #805 ](https://github.com/datafuselabs/datafuse/issues/805) | DONE  |  v0.5 |   |
| [system.tracing #873 ](https://github.com/datafuselabs/datafuse/issues/873) | DONE  | v0.5  |   |
| [add custom panic hook #792 ](https://github.com/datafuselabs/datafuse/issues/792) | DONE  | v0.5  |   |
| [metrics #1004 ](https://github.com/datafuselabs/datafuse/issues/1004) | PROGRESS  | v0.5  |   |
| [http backtrace #1085 ](https://github.com/datafuselabs/datafuse/issues/1085) | PLANNING  |  |   |

**Comment by BohuTANG** [comment]
Add:
system.tracing #873

**Comment by BohuTANG** [comment]
Add:
[metrics #1004 ](https://github.com/datafuselabs/datafuse/issues/1004)

**Comment by BohuTANG** [comment]
Add:
 [http backtrace #1085 ](https://github.com/datafuselabs/datafuse/issues/1085)

**Comment by jyz0309** [comment]
I have done #792 and worked for #1004 for a long time. And it seems that #1085 is working in progress.

**Comment by BohuTANG** [comment]
#1085 worked as a demo show, still need to make it works, welcome to take it :/

**Comment by Xuanwo** [comment]
Most works on this tracking issue have been done. And no one works in this now. Let's close.
