### ISSUE TITLE
bug: cannot kill drop table xx all

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#7961]
A test:

Case1: if the compact deal with block, we can abort: -- can be aborted
```
mysql> optimize table t7861 compact;
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
^C^C -- query aborted
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed.
```

Case2: drop table xx all; -- can not be aborted
It seems we can't deal with block, so this case can not abort.

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/7959#issuecomment-1261944878_

**Comment by BohuTANG** [comment]
For drop table, we should pass the `ctx` to the `gc.rs` and check `ctx.get_abroting` at:
https://github.com/datafuselabs/databend/blob/b2f421b140c82d7d54306d13475d2a66d2cf6078/src/query/storages/fuse/src/operations/gc.rs#L180-L193
