### ISSUE TITLE
Feature: semantic session_id/query_id/request_id for http query

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8013]
# 1. background

1. a http query may involve multi http request
2. currently query id and session id are generated be server until necessary and  independently. 

# 2. goals

1.  logs before query_id is create can be associated with the id 
2. associate session_id with query_id
3. add semantic request_id
4. share id between gateway log and query log
5. semantic session_id

# 2. propose

goal 1,2,3:

1. get request_id from request or http middleware
2. query_id = <session_id>_{seq_in_session}
3. request_id = <query_id>_{seq_in_query}

more generel:

```
<session>-<query>-<process>-<state/stage>
```
process like:

- http_req_seq
- processor

goal 4,5:

client would better provide  `request_id` in header, 
for the initial post request:  `<session_id>_0_0`

## security issue？ 

1. flag in conf to enable?
3. signed the ID?

**Comment by youngsofun** [comment]
cc @flaneur2020

**Comment by Xuanwo** [comment]
Maybe we can use the same request-id as tracing-id

**Comment by ZhiHanZ** [comment]
currently opentelemetry tracing /span id does not clearly separated by query, we should improve this part

**Comment by flaneur2020** [comment]
let me have a try about this (if this change is not hard
