### ISSUE TITLE
Feature:  queuing/scheduler of queries

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8021]
**Summary**

 currently,  each query try use max_threads cpus.

problem with it:
 
1. cpu overused, may even cause no response from client side.
2. all queries slows down
3. missing scheduler and resource management across queries.

todo

1. estimate overhead 
     2. begin with distinguishing query types: Query, Insert/Copy, DDL 
     3. timely response to some queries are needed for management (status/query_log/..)
4. queue or reject query accordingly

**Comment by sandflee** [comment]
It's very useful in the product env.  resource management and scheduling is delicate and  expecting to see process and  detail design.

**Comment by BohuTANG** [comment]
Done.
