### ISSUE TITLE
flaky test stateful `00_0000_copy_into_stage` 

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8024]
seems related to https://github.com/datafuselabs/databend/pull/7910

cc @sundy-li 

        The `00_0000_copy_into_stage` failed, rerun passed. cc @Xuanwo link:https://github.com/datafuselabs/databend/actions/runs/3176090156/jobs/5175133601#step:4:318

_Originally posted by @ariesdevil in https://github.com/datafuselabs/databend/issues/8023#issuecomment-1265802119_

**Comment by Xuanwo** [comment]
Fixed.
