### ISSUE TITLE
This pr broke the ci which results in unstable `read_bytes`.

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#8040]
This pr broke the ci which results in unstable `read_bytes`.

https://github.com/datafuselabs/databend/actions/runs/3208938508/jobs/5245282509

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/7867#issuecomment-1272214960_

**Comment by youngsofun** [comment]
maybe not unstable, just changed?
I`m updating the expect result in #8033

**Comment by youngsofun** [comment]
seems fixed by https://github.com/datafuselabs/databend/pull/8033
