### ISSUE TITLE
Feature: add `markdownlint.yaml`

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8078]
sorry for the aggressive re-linting of the markdown. It seems that there is no `.markdownlint.yaml` so my linter just applied some defaults. Do you wish to add one?

_Originally posted by @rdettai in https://github.com/datafuselabs/databend/issues/8071#issuecomment-1272491809_

**Comment by rdettai** [comment]
I guess this also goes with adding the lint check in the CI and fix the current .md files.
