### ISSUE TITLE
bug: insert tpch dataset failed

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

main

### What's Wrong?

```
➜  tpch-databend git:(main) ✗ sh insert_data.sh
customer
execute fail: fail to parse CSV customer.tbl:1 expect 8 fields, only found 5   (while in processor thread 1)lineitem
execute fail: fail to parse CSV lineitem.tbl:1 expect 16 fields, only found 1   (while in processor thread 0)nation
execute fail: fail to parse CSV nation.tbl:1 expect 4 fields, only found 1   (while in processor thread 1)orders
execute fail: fail to parse CSV orders.tbl:1 expect 9 fields, only found 1   (while in processor thread 0)partsupp
execute fail: fail to parse CSV partsupp.tbl:1 expect 5 fields, only found 3   (while in processor thread 0)part
execute fail: fail to parse CSV part.tbl:1 expect 9 fields, only found 1   (while in processor thread 0)region
execute fail: fail to parse CSV region.tbl:1 expect 3 fields, only found 1   (while in processor thread 0)supplier
execute fail: fail to parse CSV supplier.tbl:1 expect 7 fields, only found 2   (while in processor thread 1)%
```

Dataset is normal, such as nation.tbl:
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/41979257/194816995-e7c4a11a-aa18-46c1-b958-c5f2e11427eb.png">

### How to Reproduce?

https://databend.rs/blog/2022/08/08/benchmark-tpc-h

First three steps

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
try

```
    curl -XPUT 'http://root:@127.0.0.1:8000/v1/streaming_load' -H 'insert_sql: insert into tpch.'$t' format CSV' -H 'format_field_delimiter:|' -F 'upload=@"./'$t'.tbl"'

```

**Comment by xudong963** [comment]
@youngsofun cool, it works, thanks!  I'll update our blog.

Btw, what's the difference between `format_field_delimiter` and `field_delimiter`?

**Comment by xudong963** [comment]
cc @soyeric128 doc needs to be updated. 
`field_delimiter` -> `format_field_delimiter`.

**Comment by youngsofun** [comment]
@xudong963 done https://github.com/datafuselabs/databend/pull/8096
