### ISSUE TITLE
Feature:  remove settings from meta 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#8099]
**Summary**
```
set global  xx=default;
```

this command removes xx settings from the meta-server. 

Resolve change settings name for upgrade:
```
mysql -u root -P 3307 -h 127.0.0.1 -p
Enter password:
ERROR 1815 (HY000): Unknown variable: "max_concurrent_prune"
```

**Comment by zhang2014** [comment]
Maybe `SET GLOBAL xx TO DEFAULT` is better(is diff with set statement).

**Comment by BohuTANG** [comment]
'set global  xx=default' -- this is same as MySQL to reset a setting to default.

**Comment by TCeason** [comment]
> 'set global xx=default' -- this is same as MySQL to reset a setting to default.

maybe we can support unset command like sf?https://docs.snowflake.com/en/sql-reference/sql/unset.html?

Sf use UNSET to drop session variable, We can use UNSET to set the settings with default.
