### ISSUE TITLE
bug: unload data to stage OOM  

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#8121]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.68-nightly-81a205e-simd(rust-1.66.0-nightly-2022-10-10T16:31:22.570744493Z)

### What's Wrong?

vm: 16c32g

oom:
mysql> copy into @cos_csv_stage from  tb1 FILE_FORMAT = (type = 'csv' compression=gzip) SIZE_LIMIT=1000000;
mysql> copy into @cos_csv_stage from  tb1 FILE_FORMAT = (type = 'csv') SIZE_LIMIT=1000000;
mysql> copy into @cos_csv_stage from  tb1 FILE_FORMAT = (type = 'tsv') SIZE_LIMIT=1000000;
mysql> copy into @cos_csv_stage from  tb1 FILE_FORMAT = (type = 'ndjson') SIZE_LIMIT=1000000;

work：
mysql> copy into @cos_csv_stage from  tb1 FILE_FORMAT = (type = 'Parquet') SIZE_LIMIT=1000000;

### How to Reproduce?

```
CREATE TABLE `tb1` (
  `id` INT,
  `c1` INT,
  `c2` VARCHAR,
  `c3` VARCHAR
) ENGINE=FUSE
```
insert into tb1 select number, number, number,number from numbers(200000000);
insert into tb1 select * from tb1;
insert into tb1 select * from tb1;

mysql> select count(*) from tb1;
+-----------+
| count(*)  |
+-----------+
| 800000000 |
+-----------+
1 row in set (0.00 sec)

Execute unload command.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
try `max_file_size` instead of `size_limit`?

**Comment by wubx** [comment]
> try `max_file_size` instead of `size_limit`?

Sounds good :)

I tried the following case:
1.  copy into @cos_csv_stage from tb1 FILE_FORMAT = (type = 'csv');   --> OOM  
2. copy into @cos_csv_stage from tb1 FILE_FORMAT = (type = 'csv' compression='gzip') max_file_size=0; --> OOM
max_file_size = 0 default file size 5G ，but it's OOM.

3. copy into @cos_csv_stage from tb1 FILE_FORMAT = (type = 'csv') max_file_size=1000000000; --> OOM
use max_file_size 1G （ It's a little tricky to calculate, MyBe support  max_file_size=1G is better)

4. copy into @cos_csv_stage from tb1 FILE_FORMAT = (type = 'csv') max_file_size=500000000;  --> work 
Finally, it's work. I think we are better to change max_file_size from 5G to 500M or 256M.

**Comment by youngsofun** [comment]
what is the total size of file when it success？

the max mem size is num of threads plus max file size

**Comment by youngsofun** [comment]
adjust the two setting to a little small then memory limit to see if it work as expect

**Comment by wubx** [comment]
> 

mysql> copy into @cos_csv_stage from tb1 FILE_FORMAT = (type = 'csv') max_file_size=500000000;
Query OK, 0 rows affected (1 min 43.14 sec)
file number: 67 
file total size: 31.13G

**Comment by BohuTANG** [comment]
Does PR https://github.com/datafuselabs/databend/pull/8132 fix this?

**Comment by youngsofun** [comment]
still OOM if user set a large max_file_size.

https://github.com/datafuselabs/databend/issues/8134 will finally fix this.
