### ISSUE TITLE
feat: reset for LRUCache

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8157]
**Summary**

When `optimize table xx purge` will purge many segments and blocks from the cache, it would be better to reset/clear all the LRUCache.

**Comment by Xuanwo** [comment]
Let me take this. I'm working on https://github.com/datafuselabs/databend/issues/6803 now.

**Comment by BohuTANG** [comment]
Found LRU have a `clear`:

```
    /// Removes all key-value pairs from the cache.
    fn clear(&mut self) {
        self.map.clear();
        self.current_measure = Default::default();
    }
```
