### ISSUE TITLE
bug: need to optimize the memory usage of `optimize purge/fuse_snapshot` 

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#8163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.69

### What's Wrong?
Continuously importing data for a period of time seems to produce a large number of snapshots.

ec2 16c 40GB
```
mysql> select * from fuse_snapshot('default', 'xx') limit 1;
ERROR 2013 (HY000): Lost connection to MySQL server during query

or

MySQL [(none)]> select count(1) from fuse_snapshot('default', 'xx');
ERROR 2013 (HY000): Lost connection to MySQL server during query

then

Caused oom
```
![image](https://user-images.githubusercontent.com/30121694/195279134-e4f20ba3-2969-4a83-891e-401d04171479.png)

![image](https://user-images.githubusercontent.com/30121694/195278587-1eb2f433-8fb8-4af2-a949-38396f8c1dd0.png)
![image](https://user-images.githubusercontent.com/30121694/195278663-292e7086-fc98-4741-af1b-73c6d892a892.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yufan022** [comment]
track https://github.com/datafuselabs/databend/pull/8158

**Comment by sundy-li** [comment]
Now we have CompactedSegment.
