### ISSUE TITLE
doc: OPTIMIZE TABLE T PURGE break the time travel

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8185]
**Summary**

Such as 
```
OPTIMIZE TABLE T PURGE
```
will do:
1. collect all the snapshots/segments/blocks except the latest snapshot
2. Compactor tries to remove block/segment files,s not in the latest snapshot
3. Compactor tries to remove the snapshot file 
4. This is *By Design*, if you want time travel, please don't do `OPTIMIZE TABLE T PURGE` or `OPTIMIZE TABLE T ALL`

After PURGE, the time travel can only go back to the latest snapshot.

**Comment by BohuTANG** [comment]
We should add the warning to https://databend.rs/doc/reference/sql/ddl/table/optimize-table 
cc @soyeric128

**Comment by wubx** [comment]
Let's try a different approach.
Here's what I think snowflake does:
1. user uses data -> active data, which will be timely compact.
2. time travel data is stored independently.  just data （not index ) only use for time travel.  compact can be done according to the specified time.   

<img width="724" alt="image" src="https://user-images.githubusercontent.com/320680/195740528-a5f97151-b593-4d4c-ae32-c542ff4632e6.png">

**Comment by BohuTANG** [comment]
Please *NOTE* `purge` is not `compact`, if you want time travel please don't use `pruge`.

**Comment by wubx** [comment]
> 


Yeah,  Please ignore.
My proposal may require a discussion.
