### ISSUE TITLE
Optimize BlockFilter creation

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#8196]
**Summary**

BlockFilter building takes a lot time.

Add benchmark of current xor8 filter building for `i64` and `string` of
length 16 to 32.

Benchmark shows that with `Column::to_values()`, which potentially is an
unnecessary overhead, the time cost for every key is:
```
- i64:    210ns/key
- string: 240ns/key
```

And the benchmark of xor8-filter shows that building a `i64` key takes
about 180 ns/key, which means without modifying xor8-filter, the max
performance boost would be about 25%.

![img_v2_0c93db10-cb5b-44ba-9878-5d1693bc69ag](https://user-images.githubusercontent.com/44069/195539565-34031905-5f35-4257-83cb-b6af01d60c3f.png)

TODO:

- [x] #8225 
- [x] Avoid using `Column::to_values()`, which allocates a lot memory (https://github.com/datafuselabs/databend/pull/9053)
- [ ] #8233

**Comment by BohuTANG** [comment]
I think we can close this issue now :)
