### ISSUE TITLE
Hangs on the first query after databend-query start up

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#8197]
**Summary**

version:  DatabendQuery v0.8.70-nightly-2a99bb5-simd(rust-1.66.0-nightly-2022-10-12T08:04:39.226103432Z)

query: SELECT 1

![Screen Shot 2022-10-13 at 16 17 13](https://user-images.githubusercontent.com/129800/195542044-1b5562e6-bb32-4356-8be9-19792043a6c4.png)

the warehouse have already resumed, however the query ID not get responded after start executing.

it seems get hanged.

**Comment by flaneur2020** [comment]
same issue exits in 0.8.65

**Comment by flaneur2020** [comment]
0.8.59 did not hangs

**Comment by Xuanwo** [comment]
Fixed by https://github.com/datafuselabs/databend/pull/8239
