### ISSUE TITLE
bug:databend-query can't connect minio during startup

### ISSUE THREAD

**Issue by zeusYi** [datafuselabs/databend#8200]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

[root@test-node1 databend]# ./bin/databend-meta --version
databend-meta v0.8.72-nightly-7d6536e-simd(1.66.0-nightly-2022-10-13T02:21:06.151411655Z)

### What's Wrong?

root@test-node1 databend]# ./bin/databend-query -c ./configs/databend-query.toml
Error: Code: 4000, displayText = other error (backend error: (context: {"bucket": "databend"}, source: sending request: http://10.50.101.129:9900/databend: Custom { kind: Other, error: Transport { kind: ProxyConnect, message: None, url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(10.50.101.129)), port: Some(9900), path: "/databend", query: None, fragment: None }), source: None } })).

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zeusYi** [comment]
[root@test-node1 databend]# cat ./configs/databend-query.toml 
# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9090"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8080"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7070"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8124

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
# http_handler_port = 8000
http_handler_port = 8888

tenant_id = "test_tenant"
cluster_id = "test_cluster"

table_engine_memory_enabled = true
database_engine_github_enabled = true

table_cache_enabled = true
table_memory_cache_mb_size = 1024
table_disk_cache_root = "_cache"
table_disk_cache_mb_size = 10240

[log]
level = "ERROR"
dir = "./.databend/logs"
query_enabled = true

[meta]
# To enable embedded meta-store, set address to "".
embedded_dir = "./.databend/meta_embedded_1"
address = "0.0.0.0:9191"
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

# Storage config.
[storage]
# fs | s3 | azblob | obs
type = "s3"

# Set a local folder to store your data.
# Comment out this block if you're NOT using local file system as storage.
#[storage.fs]
#data_path = "./.databend/stateless_test_data"

# To use S3-compatible object storage, uncomment this block and set your values.
[storage.s3]
bucket = "databend"
endpoint_url = "http://10.50.101.129:9900"
access_key_id = "root"
secret_access_key = "mypassword"

# To use Azure Blob storage, uncomment this block and set your values.
# [storage.azblob]
# endpoint_url = "https://<your-storage-account-name>.blob.core.windows.net"
# container = "<your-azure-storage-container-name>"
# account_name = "<your-storage-account-name>"
# account_key = "<your-account-key>"

# To use OBS object storage, uncomment this block and set your values.
# [storage.obs]
# bucket = "<your-bucket-name>"
# endpoint_url = "<your-endpoint>"
# access_key_id = "<your-key-id>"
# secret_access_key = "<your-account-key>"

**Comment by zeusYi** [comment]
[root@test-node1 minio]# mc ls myminio
[2022-10-13 10:12:22 UTC]     0B databend/

**Comment by zeusYi** [comment]
[root@test-node1 databend]# ps axu |grep minio
root      70644  0.3  4.8 1146320 194468 pts/0  Sl+  10:22   0:02 minio server --address :9900 ./data
root      71812  0.0  0.0 112808   976 pts/1    S+   10:34   0:00 grep --color=auto minio



[root@test-node1 databend]#  mc stat myminio
Name      : databend/
Size      : 0 B    
Type      : folder 
Metadata  :
  Versioning: Un-versioned
  Location: us-east-1
  Policy: none

**Comment by Xuanwo** [comment]
Hi, can you give the output of `export`? Do you have set `http_proxy`?

**Comment by zeusYi** [comment]
已解决
minio 之前的启动方式为 “minio server --address :9900 ./data” 监听所有网卡，更换成“minio server --address 10.50.101.129:9900 ./data” 监听固定Ip以后就好了
