### ISSUE TITLE
remove `next_url` `final_url` `kill_url`

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8206]
**Summary**

benefits:

1.  clients have more control，e.g use parameters for next_url/final_url
2. easier to adopt open API

steps

- [ ] add `next_page` to replace `next_url`
- [ ] check/modify callers then
    - [ ] cloud
    - [ ] logistic test
    - [ ] unit test
- [ ] remove them, change docs

@flaneur2020

**Comment by flaneur2020** [comment]
I guess next_url is better than next_page, because it have a loose-coupling with the pagination logic.

You can change to pagination by pagination token in the future without touching the client code.

**Comment by flaneur2020** [comment]
> clients have more control，e.g use parameters for next_url/final_url

more infomation about the new control features?

**Comment by flaneur2020** [comment]
after discussion, we'd hope to close this issue. future work:

- get the state machine diagram of a query's lifetime into docs
- clear the semantics about calling final_uri when client wishes exits the iterator after it thinks itself get enough data

**Comment by youngsofun** [comment]
replaced by https://github.com/datafuselabs/databend/issues/8271
