### ISSUE TITLE
bug: `SELECT` command is stuck.

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#8210]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.73-nightly-3523b80-simd

### What's Wrong?

A table with 5 billion rows is in s3.

![image](https://user-images.githubusercontent.com/30121694/195756543-20f5ac8c-82ea-44c0-8503-7ab41baea575.png)
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/30121694/195756624-62b2ff75-0801-4f09-8e36-e7198cd70d1e.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/30121694/195756666-2ad07daf-b45a-492f-83d6-c7c9e92edb9c.png">
![image](https://user-images.githubusercontent.com/30121694/195757254-f24f7ba3-14ea-4d32-b13c-4b5cd0af8586.png)

Found that many logs like the following will not stop
```
{"v":0,"name":"databend-query-test_tenant-test_cluster","msg":"[CONNECTION - EVENT] send","level":20,"hostname":"databend_query1_ec2","pid":4981,"time":"2022-10-14T03:28:33.309671822Z","target":"h2::codec::framed_write","line":232,"file":"/opt/rust/cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.14/src/codec/framed_write.rs","frame":"Data { stream_id: StreamId(1) }"}
{"v":0,"name":"databend-query-test_tenant-test_cluster","msg":"[CONNECTION - EVENT] send","level":20,"hostname":"databend_query1_ec2","pid":4981,"time":"2022-10-14T03:28:33.310726573Z","target":"h2::codec::framed_write","line":232,"file":"/opt/rust/cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.14/src/codec/framed_write.rs","frame":"Data { stream_id: StreamId(1) }"}
{"v":0,"name":"databend-query-test_tenant-test_cluster","msg":"[CONNECTION - EVENT] received","level":20,"hostname":"databend_query1_ec2","pid":4981,"time":"2022-10-14T03:28:33.311405485Z","target":"h2::codec::framed_read","line":354,"file":"/opt/rust/cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.14/src/codec/framed_read.rs","frame":"Data { stream_id: StreamId(1) }"}
{"v":0,"name":"databend-query-test_tenant-test_cluster","msg":"[CONNECTION - EVENT] received","level":20,"hostname":"databend_query1_ec2","pid":4981,"time":"2022-10-14T03:28:33.312414528Z","target":"h2::codec::framed_read","line":354,"file":"/opt/rust/cargo/registry/src/github.com-1ecc6299db9ec823/h2-0.3.14/src/codec/framed_read.rs","frame":"Data { stream_id: StreamId(1) }"}

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Cc @drmingdrmer `h2::codec` seems the connection to metasrv (s3 only have http/1.1 support). Do you know what happened here?

**Comment by drmingdrmer** [comment]
The data frame is sent/received every 500ms, and there is only one `500ms` timer in our codebase:
https://github.com/datafuselabs/databend/blob/32faa1406809eaf83a47c63d02b5053c4186957d/src/query/service/src/api/rpc/exchange/statistics_receiver.rs#L73

And the flight service is also grpc over http2, IMHO.
So, may it be some heartbeat rpc between query nodes in flight protocol? @zhang2014

**Comment by drmingdrmer** [comment]
These h2 logs are progress synchronization messages between databend-query nodes when a sql-query is running, as confirmed by @zhang2014 🤔
