### ISSUE TITLE
sql failed with message "(1105, 'Code: 1067, displayText = error reading a body from connection: connection reset (while in processor thread 6).')"

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#8221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0a106b34e2702d0913133e48663acb9bcd8749f4

### What's Wrong?

I run batch of sqls in cluster mode,  some sql failed with such message,  the failed sql are not fixed and could't be reproduced, so maybe not related to sql pattern.
```
(1105, 'Code: 1067, displayText = error reading a body from connection: connection reset (while in processor thread 6).')
```

could't find any useful logs  in all cluster nodes :(

### How to Reproduce?

1. set a cluster with 3 nodes
2. run batch of sqls

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Xuanwo** [comment]
Can you also paste the error log with a backtrace for this error?

**Comment by sandflee** [comment]
unfortunately, I could't find any error message

**Comment by sandflee** [comment]
seems read data from remote server failed.

**Comment by Xuanwo** [comment]
Can you try with enable `RUST_LOG=debug` and find the error log? We need to know where is this error from.

**Comment by Xuanwo** [comment]
```
AsyncInsertTimeoutError(1105),
```

Have you enabled async insert feature?

**Comment by sandflee** [comment]
> AsyncInsertTimeoutError(1105),
Have you enabled async insert feature?

no, I just runing hive sqls

>Can you try with enable RUST_LOG=debug and find the error log?

I tried but failed to reproduce after enable `RUST_LOG=debug`, seems  pipeline processor erorrs not logged now, I'll try to add some to debug.

**Comment by Xuanwo** [comment]
I'm guessing it's the same problem with https://github.com/datafuselabs/databend/issues/7986

I added some more error messages for `tonic::Status`. Welcome to share your error message while reproduced.

**Comment by sandflee** [comment]
```
Code: 1067, displayText = error reading a body from connection: connection reset, source: Some(hyper::Error(Body, Error { kind: Io(Kind(ConnectionReset)) }))
```
cc @Xuanwo  @zhang2014

**Comment by sandflee** [comment]
also some error mesg:
```
 (1105, 'Code: 1068, displayText = Cannot send flight data to endpoint, because sender is closed..')
```

**Comment by sandflee** [comment]
@zhang2014 @Xuanwo  is there any progress?  this making sql failed on cluster mode.
