### ISSUE TITLE
feat: add prefix of the UUID to unlimit s3 quota

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8229]
**Summary**

From the s3 throttling documentation(https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-limit-avoid-throttling/):
```
You can send [3,500 PUT/COPY/POST/DELETE or 5,500 GET/HEAD requests](https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html) per second per prefix in an Amazon S3 bucket. There are no limits to the number of prefixes that you can have in your bucket.
```

This is a problem for databend , the fuse engine table file prefixes are as follows:
```
/<db_id>/<table_id>/_ss/  -- All snapshot files
/<db_id>/<table_id>/_sg/  -- All segment files of the snapshot
/<db_id>/<table_id>/_b/  -- All block files of the segment
/<db_id>/<table_id>/_i_b_v2/ -- All index files of the segment
```
For example, we have a full table scan SQL in a large cluster(Such as 100 databend-query nodes), and each databend-query will send amount IO request to S3, and the prefix limitation is easy to reach.

To make the  `prefix` more unique, we can:
```
/<db_id>/<table_id>/_ss/<3-byte-prefix-of-snapshot-file-uuid>/  -- All snapshot files
/<db_id>/<table_id>/_sg/<3-byte-prefix-of-segment-file-uuid>/   -- All segment files of the snapshot
/<db_id>/<table_id>/_b/<3-byte-prefix-of-block-file-uuid>/   -- All block files of the segment
/<db_id>/<table_id>/_i_b_v2/<3-byte-prefix-of-inex-file-uuid>/  -- All index files of the segment
```

[For Amazon S3 request rates, what's the difference between prefixes and nested folders? How many prefixes can I have in an S3 bucket?](https://aws.amazon.com/premiumsupport/knowledge-center/s3-prefix-nested-folders-difference/)

Said:
```
. For example, if an object (123.txt) is stored as BucketName/Project/WordFiles/123.txt, the prefix might be “BucketName/Project/WordFiles/123.txt”. 
```

What's the prefix is confusing 😢 , welcome to comments...

**Comment by Xuanwo** [comment]
prefix is the full path that we passed during request.

**Comment by BohuTANG** [comment]
By our file layout design, there is no limit, cc @dantengsky
