### ISSUE TITLE
bug: dal_context write should use observe_write

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8237]
**Summary**

https://github.com/datafuselabs/databend/blob/0025df6601953408662a9e2f1614f9cbf65904aa/src/common/contexts/src/dal/dal_context.rs#L116-L139

**Comment by BohuTANG** [comment]
cc @Xuanwo

**Comment by Xuanwo** [comment]
That's expected. Because we can only observe write by observing the reader's options.
