### ISSUE TITLE
After docker deploys databend-query, the connection using mysql fails

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#8238]
**Summary**
github action and local environment are the same result.
mysql client version: `mysql  Ver 8.0.30 for Linux on x86_64 (MySQL Community Server - GPL)`

set up databend：[fix: unstable deployment databend · sqlancer/sqlancer@872e718 (github.com)](https://github.com/sqlancer/sqlancer/actions/runs/3254996778/jobs/5343854334#step:5:19)
```bash
docker pull datafuselabs/databend-query
docker run -p 3307:3307 datafuselabs/databend-query --mysql-handler-host 0.0.0.0 &
```
error message：[fix: unstable deployment databend · sqlancer/sqlancer@872e718 (github.com)](https://github.com/sqlancer/sqlancer/actions/runs/3254996778/jobs/5343854334#step:6:9)
![(C~%@~S_%$6%I$46SCY4)9G](https://user-images.githubusercontent.com/71937758/195979491-bb20846e-b517-43cb-8fc6-2a540148695b.png)

**Comment by hanyisong** [comment]
cc @Xuanwo

**Comment by BohuTANG** [comment]
You should use root@localhost inside the docker.

**Comment by hanyisong** [comment]
> You should use root@localhost inside the docker.
cc @BohuTANG 
Thanks, I found relevant information: https://databend.rs/doc/deploy/deploying-databend#verifying-deployment
I'm not very familiar with docker, I read the docker documentation, but still have the following questions:
`docker run -p 3307:3307 datafuselabs/databend-query --mysql-handler-host 0.0.0.0 &`
This command exposes the databend service to the host. I think it is necessary to enter the databend-query container to download mysql-client and then execute the command to create a user. It's this step that I don't know how to do it elegantly. If you can answer it, I would be very grateful.

**Comment by hanyisong** [comment]
> > You should use root@localhost inside the docker.
> 
> cc @BohuTANG Thanks, I found relevant information: https://databend.rs/doc/deploy/deploying-databend#verifying-deployment I'm not very familiar with docker, I read the docker documentation, but still have the following questions: `docker run -p 3307:3307 datafuselabs/databend-query --mysql-handler-host 0.0.0.0 &` This command exposes the databend service to the host. I think it is necessary to enter the databend-query container to download mysql-client and then execute the command to create a user. It's this step that I don't know how to do it elegantly. If you can answer it, I would be very grateful.

My main purpose is to deploy databend-query more stably in github action, I downloaded it in https://github.com/datafuselabs/databend/releases/ before, however it is not stable: https://github.com/sqlancer/sqlancer/issues/585#issuecomment-1275835940

I'm relatively unfamiliar with databend's compilation and tried and failed, so I chose to try the docker way, and then I have this problem.

**Comment by Xuanwo** [comment]
Let me help fix this.

The CI failed because databend depends on Github Action to build releases. It's possible that the release is not ready for the latest tag.

**Comment by hanyisong** [comment]
Changing `docker run -p 3307:3307` to `docker run --net=host` solved the problem
