### ISSUE TITLE
feat: CREATE CATALOG

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8252]
> If so, we can do it as a hive table in databend: new catalog and new table engine.

Using a catalog in hive way is not good for me. We should allow users use to configure the catalog for the iceberg. For example, specify the iceberg location by SQL instead of static config.

In this way, we need to introduce a `create catalog` like:

```sql
CREATE CATALOG my_icerberg TYPE='iceberg' CONNECTION=(URL='s3://my_bucket')
SELECT * from my_iceberg.db.table;
```

_Originally posted by @Xuanwo in https://github.com/datafuselabs/databend/pull/8215#discussion_r996606560_

**Comment by Xuanwo** [comment]
cc @sandflee for comments.

**Comment by BohuTANG** [comment]
I am not sure what the statement on the hive table to replace the static config, could you give an example?  @dantengsky @Xuanwo

**Comment by Xuanwo** [comment]
databricks supports create catalog:

```sql
CREATE CATALOG [ IF NOT EXISTS ] catalog_name
    [ USING provider_name . share_name ]
    [ COMMENT comment ]
```

https://docs.databricks.com/sql/language-manual/sql-ref-syntax-ddl-create-catalog.html

**Comment by Xuanwo** [comment]
> I am not sure what the statement on the hive table to replace the static config, could you give an example? @dantengsky @Xuanwo

```sql
CREATE CATALOG my_hive TYPE='hive' CONNECTION = (URL='<hive-meta-store>');
SELECT * FROM my_hive.db.table;
```

**Comment by Xuanwo** [comment]
We can defer the hive support after we confirm that it works well on the iceberg.

**Comment by Xuanwo** [comment]
I'm working an RFC for this issue.
