### ISSUE TITLE
Support IN Operator

### ISSUE THREAD

**Issue by jyizheng** [datafuselabs/databend#826]
**Summary**

Support 

- IN (value1, value2, ...)
- IN (SELECT STATEMENT);

**Comment by BohuTANG** [comment]
After `exists` #764 done, it's time for this task to start :dancing_women

**Comment by jyizheng** [comment]
Yes, that is my plan. I have discussed the design with @zhang2014  and @sundy-li,
I am trying to make those thoughts more concrete.

**Comment by Veeupup** [comment]
I'm interested in this issue, and I will try to follow it. @jyizheng

**Comment by jyizheng** [comment]
@Veeupup  Go for it.
