### ISSUE TITLE
Feature: add more subquery types to doc

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8297]
**Summary**

Currently, our [doc](https://databend.rs/doc/reference/sql/query-operators/operators-subquery) only has exists subquery introduction.

It's better to add `SCALAR`, `IN/NOT IN`, `ANY`, `SOME`, and `ALL` subquery types introduction.

FYI: https://www.postgresql.org/docs/current/functions-subquery.html

**Comment by soyeric128** [comment]
PR for scalar subqueries: https://github.com/datafuselabs/databend/pull/8373

**Comment by soyeric128** [comment]
PR for IN / NOT IN: https://github.com/datafuselabs/databend/pull/8394

**Comment by soyeric128** [comment]
PR for ANY (SOME): https://github.com/datafuselabs/databend/pull/8407

**Comment by soyeric128** [comment]
PR for ALL: https://github.com/datafuselabs/databend/pull/8408
