### ISSUE TITLE
further compact blocks when insert/load data with many threads

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8311]
**Summary**

already compacted in each threads.

**Comment by youngsofun** [comment]
```
compactor----------->SinkBigBlock-------------------+
                                                    |
                                                    |
                                                    v
                                                 compactor--------->Sink
                                                    ^
                                                    |
                                                    |
compactor----------->SinkBigBlock-------------------+
```

Sink to encode block to parquet and write to s3.

this is already used in unloading to file.
we can extract this as a shared code (`Sink` as a type parameter)


@sundy-li  @zhyass @dantengsky

**Comment by youngsofun** [comment]
related

https://github.com/datafuselabs/databend/issues/7760

https://github.com/datafuselabs/databend/issues/8353

**Comment by youngsofun** [comment]
because a processor has only one output,  have to choose 1 of the 2:

1. merge compactor into Sink ( call compactor inside)
2. add a flag to the DataBlock indicating whether to SinkBigBlock should process it or pass it to downstream

**Comment by sundy-li** [comment]
> because a processor has only one output

why not use resize the processor into one ?

**Comment by youngsofun** [comment]
@sundy-li  I mean SinkBigBlock do not have information for branching: sink at once or pass it to downstream (compactor and final sink, resized to 1)
