### ISSUE TITLE
bug: fuse table lost DalContext layer bind

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8331]
**Summary**

After refactoring a few days ago, now the fuse table storage operator init:
https://github.com/datafuselabs/databend/blob/c0030eb977b4e2fee50d464c749f240ed044ad0f/src/query/storages/fuse/src/fuse_table.rs#L88-L113

We can not get the metrics from DalContext.

By design, it should be:
https://github.com/datafuselabs/databend/blob/c0030eb977b4e2fee50d464c749f240ed044ad0f/src/query/service/src/sessions/query_ctx.rs#L311-L319

After refactoring, putting dal_ctx  in the query context is not right, it looks every operator(DataOperator/CacheOpeartor) should have his metrics and get them from the Query Context.

**Comment by BohuTANG** [comment]
cc @Xuanwo @ariesdevil

**Comment by BohuTANG** [comment]
We can put an operator context with metrics like this to get fuse engine read/write metrics:
```
query_ctx.build_table_by_table_info --> catalog.get_table_by_info --> fuse_storage.get_table --> fusetable.try_create
```

**Comment by Xuanwo** [comment]
@BohuTANG Are you still working on this?

**Comment by Xuanwo** [comment]
Https://github.com/datafuselabs/databend/issues/8345 should address this issue.

**Comment by BohuTANG** [comment]
> @BohuTANG Are you still working on this?

No.
