### ISSUE TITLE
Bug: full outer join abort

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8352]
**Summary**

Run sql in https://github.com/datafuselabs/databend/pull/8351/files#diff-84732f671e927431feb54f246b093cd139f5dfc4e3aec92bbc592dbb9b535b85

Got `ERROR 1105 (HY000): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed..`

Expected:
https://github.com/datafuselabs/databend/pull/8351/files#diff-9ea25e7f2ca64bd84f2e6bbca384b5d4a0dd63f22b08082db607791758851f16

**Comment by xudong963** [comment]
cc @zhang2014

**Comment by xudong963** [comment]
Test in my local, still abort

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/41979257/196939816-7b46d325-45db-46de-89bc-d77d9825ac72.png">

cc @zhang2014

**Comment by xudong963** [comment]
https://github.com/datafuselabs/databend/actions/runs/3289226767/jobs/5420649311

**Comment by zhang2014** [comment]
fixed in #8364
