### ISSUE TITLE
bug: move `upsert_table_copied_file_info` function call into finish callback will hang

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#8356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

new

### What's Wrong?

In pr https://github.com/datafuselabs/databend/pull/8328, there is an optimization that move `upsert_table_copied_file_info` function call into finish callback, after that copy parquet file from s3 into table will be hang, like:

```
copy into ontime from 's3://testbucket/admin/data/' connection=(aws_key_id='minioadmin' aws_secret_key='minioadmin' endpoint_url='http://127.0.0.1:9900') PATTERN = 'ontime.*parquet' FILE_FORMAT = (type = 'PARQUET')
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @zhang2014
