### ISSUE TITLE
Feature: User-level stage

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#8357]
**Summary**

We can considering add a stage for each user which naming as `@~`.

So SDKs can directly depends on the user's stage without care about the stage management stuff at all. 

We can then make a SDK do data ingest like this: https://github.com/ClickHouse/clickhouse-go/blob/main/examples/std/batch.go#L59

The user whom using this SDK do not need to care about the stage, all her need is to prepare her data in her favorite language. The data would be put into the user-level stage with a temporary file name, then passed to COPY INTO seamlessly.

**Comment by flaneur2020** [comment]
cc @Xuanwo

**Comment by Xuanwo** [comment]
Implemented
