### ISSUE TITLE
feat: get the system open file limits and set

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8374]
**Summary**

```
MySQL [(none)]> SELECT SUM(AdvEngineID), COUNT(*), AVG(ResolutionWidth) FROM hits;
ERROR 1105 (HY000): Code: 4000, displayText = uncategorized error (object error: (op: read, path: 1/318/_b/1a25136fa5524916a36e999e5f78851b_v0.parquet, source: Too many open files (os error 24))).
```

It would be great to give a warn log for databend-query when starting if the max open file limit is less than 65535.

**Comment by TszKitLo40** [comment]
I want to try this issue. But I can't figure out where the databend-query starts.

**Comment by sundy-li** [comment]
> I am new here and want to try this issue. But I can't figure out where the databend-query starts.

Thanks,  it's in https://github.com/datafuselabs/databend/blob/04ac812d02e906fba8f99435f55465a02ec05193/src/binaries/query/main.rs

More docs :  https://mp.weixin.qq.com/s/5snnRuOLdCdWEktRFcwwug

**Comment by BohuTANG** [comment]
Closed  https://github.com/datafuselabs/databend/pull/8388
