### ISSUE TITLE
Feature: a SQL can output nothing.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#8379]
**Summary**

Sometime, we just want to test the performance of a SQL and don't care about the output table. 
Like `do_something > /dev/null`.

We can introduce such a syntax:

```sql
SELECT * FROM t FORMAT NULL;
```

The result will be like:

```
mysql> select 1;
+------+
| 1    |
+------+
|    1 |
+------+
1 row in set (0.02 sec)
Read 1 rows, 1.00 B in 0.002 sec., 592.23 rows/sec., 592.23 B/sec.

mysql> select 1 FORMAT NULL;
1 row in set (0.02 sec)
Read 1 rows, 1.00 B in 0.002 sec., 592.23 rows/sec., 592.23 B/sec.
```

In the future, we can also add other output format .

**Comment by youngsofun** [comment]
for example， we can not use ` format csv` in mysql handler

**Comment by RinChanNOWWW** [comment]
In #8390, I only introduce `FORMAT NULL` for mysql handler.

**Comment by youngsofun** [comment]
what about  `select .. limit 0` but limit not pushed down when it is `0`.

**Comment by leiysky** [comment]
This is usually achieved by using `EXPLAIN ANALYZE`.
