### ISSUE TITLE
bug: external table syntax need key workds check

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#8380]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

```
MySQL [(none)]> select version();
+------------------------------------------------------------------------------------+
| version()                                                                          |
+------------------------------------------------------------------------------------+
| 8.0.26-v0.8.80-nightly-d0006ac(rust-1.66.0-nightly-2022-10-19T09:51:51.600643433Z) |
+------------------------------------------------------------------------------------+
1 row in set (0.017 sec)

```

### What's Wrong?

```
MySQL [(none)]> create table tb101 (id int ,c1 datetime) 's3://wubx/tb101' connection=(aws_key_id='minioadmin' aws_ssecret_key='minioadmin' endpoint_url='http://127.0.0.1:9900');

ERROR 1105 (HY000): Code: 3901, displayText = current configured storage is not available: config: S3(StorageS3Config { endpoint_url: "http://127.0.0.1:9900", region: "", bucket: "wubx", root: "/", disable_credential_loader: true, enable_virtual_host_style: false, role_arn: "", external_id: "", access_key_id: "******min", secret_access_key: "", security_token: "", master_key: "" }), cause: object error: (op: list, path: /, source: status code: 403, headers: {"accept-ranges": "bytes", "content-length": "259", "content-security
MySQL [(none)]> 
````
this error root cause: aws_secret_key be written into aws_ssecret_key 
So I think  there need  key workds check.

### How to Reproduce?

above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ayushthe1** [comment]
hey i would like to work on this issue but im new to this .Could you please elaborate what i need to do.

**Comment by wubx** [comment]
@Xuanwo   Can you give @ayushthe1  some hint?

**Comment by Xuanwo** [comment]
> hey i would like to work on this issue but im new to this .Could you please elaborate what i need to do.

Oh, sorry for the lateness.

We build the `StorageParams` via `UriLocation` here, we can add some checks here:

https://github.com/Xuanwo/databend/blob/54ae0e6f716c0e372752ec611e7b02d61448d3c1/src/common/storage/src/location.rs#L56

For example, for s3 services, we can allow `region`, `access_key_id`, `aws_secret_key`,..., and reject all other keys

**Comment by BohuTANG** [comment]
As @ariesdevil is working on COPY, it could help to improve the COPY syntax checking.
