### ISSUE TITLE
bug: OOM during `OPTIMIZE TABLE COMPACT` execution

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#8414]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.83

### What's Wrong?
16c40g ec2
set global max_storage_io_requests=100;
![image](https://user-images.githubusercontent.com/30121694/197442905-161a1750-8be7-4ca7-9a1d-95b54aa46c76.png)
![image](https://user-images.githubusercontent.com/30121694/197442946-813a882f-98f8-497c-835a-01380aef5cb2.png)
![image](https://user-images.githubusercontent.com/30121694/197442966-5bf9bffd-1598-4cd5-8913-a5f830a9a084.png)
![image](https://user-images.githubusercontent.com/30121694/197443123-397e4de6-cb57-4b5a-a540-0ea514820e29.png)
It's unpredictable. When I first executed it, it OOM immediately. When I execute it twice later, OOM will not occur until some time later.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Fixed https://github.com/datafuselabs/databend/pull/8451
