### ISSUE TITLE
bug:  range_filter may drop parquet blocks if query a string column with int value

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#8424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

xxx

### What's Wrong?

a parquet string column named s may has min value '10' and max value '9',  if we query with the filter 'a = 8', databend droped the block because min_v > 8.  cc @sundy-li 

### How to Reproduce?

see the ut: https://github.com/datafuselabs/databend/commit/5745751f8c19939bb695586692d483af0f5dc6c3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
`cast` is not monontic.

**Comment by sandflee** [comment]
any advise to solve this?
