### ISSUE TITLE
Push down filter through `Aggregate`

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#8439]
Some filters can be pushed down through `Aggregate` operator, for example:
```sql
select * from t group by a having a > 1;
```

Since the `HAVING` predicate `a > 1` is applied on the group item `a`, it's possible to rewrite the query into `select * from t where a > 1 group by a`, which is much more efficient.

**Comment by johnhaxx7** [comment]
Hi @leiysky, is this open for community to take? If so, can you please help evaluate the effort?

**Comment by sundy-li** [comment]
Yes, It's ready to have this Transformation.
