### ISSUE TITLE
add distinct value counting to table meta

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#8465]
- [x] #8766
- [x] #8776

**Comment by Xuanwo** [comment]
What's HLL means?

**Comment by lichuang** [comment]
> What's HLL means?

HyperLogLog  https://en.wikipedia.org/wiki/HyperLogLog

**Comment by Xuanwo** [comment]
Thanks for the quick response. So my new question is, what does adding HLL (an algorithm) in table meta mean?

**Comment by Xuanwo** [comment]
I updated the issue title to reflect the real task. Please feel free to update it again @lichuang
