### ISSUE TITLE
Feature:  databend compatible with hive functions

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#8476]
**Summary**
there’re  litte difference between databend and hive, such as
1. substr(0, xx) in hive is acts like substr(1, xx),    it'll return null in databend
2. null is the smallest value in hive,  but biggest in databend.

maybe we could add a setting like 'hive-compatible-mode' , if enabled, we could rewrite the ast, any advise?

**Comment by sandflee** [comment]
@BohuTANG @leiysky ,  hoping your suggestions on implementing this function.

**Comment by BohuTANG** [comment]
Ping @sundy-li for suggesstions :)

**Comment by sundy-li** [comment]
It's a big change to be compatible with hive functions in databend.  I did not have good ideas.
