### ISSUE TITLE
bug: unload -> max_file_size not take effect in parquet type

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#8488]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.8.89-nightly-aacf694(rust-1.66.0-nightly-2022-10-26T05:22:17.08435006Z)

### What's Wrong?

copy into @w_data/tpch100parquet/customer/ from customer file_format=(type='parquet') max_file_size=134217728;

output file:

![cbad76a1-ccc9-4f28-b5c5-4150dab02eae](https://user-images.githubusercontent.com/320680/198211493-7418a1d8-d0fe-446b-aa3b-7f2f1aede238.jpeg)

It's very small.  The csv type file work ok.

Another issue:
unload file can't use copy into load databend

copy into customer1 from @w_data/tpch100parquet/customer/ pattern='*parquet'  file_format=(type='parquet');

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by youngsofun** [comment]
partitially fixed in https://github.com/datafuselabs/databend/pull/15596
