### ISSUE TITLE
meta: Cleaning up keys should not affect the state in other key spaces

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#8490]
Clean up several expired keys(e.g. at most hundreds) every time a new log is applied to state-machine.

With openraft-0.7, expired keys can be deleted only when a new log is applied because the meta-store must use the time embedded in a log entry to expire keys, in order to keep consistency across raft nodes.

In a new version of openraft, the leader periodically appends a blank log, so that expired keys will be cleaned at a relatively fixed interval.

Cleaning up keys should not affect the state in other key spaces.I.e., a meta-node that expires keys and a meta-node that does not expire keys should have the same key-value states(the generic-kv key space).

**Comment by Xuanwo** [comment]
Updated issue's title for better reading, feel free to update it again cc @drmingdrmer
