### ISSUE TITLE
Feature: `COPY INTO` Idempotent key need elimination strategy

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#8514]
**Summary**
Databend already supports idempotent import. Maybe we should consider the idempotent key elimination strategy to prevent the large-scale import from causing too many keys

**Comment by BohuTANG** [comment]
The copies file key in metasrv have a expired time  cc @lichuang

**Comment by drmingdrmer** [comment]
- #8425

**Comment by lichuang** [comment]
https://github.com/datafuselabs/databend/pull/8524, set the default expire time as 7 day.
