### ISSUE TITLE
[functions] Functions Working with Date/DateTime

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#853]
From  https://clickhouse.tech/docs/en/sql-reference/functions/date-time-functions/

prio order from high to low
- [x] now (#1648)
- [x] today (#1648)
- [x] yesterday (#1673)
- [x] tomorrow (#1673)
- [x] toDate, toDateTime    (cast number/string into Date/DateTime)  
- [x] timeSlot (#1715)
- [x] toYYYYMM (#1726)
- [x] toYYYYMMDD (#1767)
- [x] toYYYYMMDDhhmmss (#1767)
- [x] toStartOfYear (#1826)
- [x] toStartOfISOYear (#1826)
- [x] toStartOfQuarter #1848
- [x] toStartOfMonth  #1848
- [x] toStartOfWeek (#1942) 
- [x] toStartOfDay (#1715)
- [x] toStartOfHour (#1715)
- [x] toStartOfMinute (#1715)
- [x] toStartOfSecond (#1715)
- [x] toStartOfFiveMinute (#1715)
- [x] toStartOfTenMinutes (#1715)
- [x] toStartOfFifteenMinutes  (#1715)
- [x] toMonth (#2042)
- [x] toDayOfYear (#2050)
- [x] toDayOfMonth (#2050)
- [x] toDayOfWeek (#2050)
- [x] toHour (#2309)
- [x] toMinute (#2309)
- [x] toSecond (#2309)
- [x] toMonday (#2317)

Low priority:
- timeZone
- toTimeZone
- timeZoneOf
- timeZoneOffset
- toStartOfInterval
- toYear
- toQuarter
- toUnixTimestamp
- toTime
- toRelativeYearNum
- toRelativeQuarterNum
- toRelativeMonthNum
- toRelativeWeekNum
- toRelativeDayNum
- toRelativeHourNum
- toRelativeMinuteNum
- toRelativeSecondNum
- toISOYear
- toISOWeek
- toWeek
- toYearWeek
- date_trunc
- date_add
- date_diff
- date_sub
- timestamp_add
- timestamp_sub
- addYears
- subtractYears
- timeSlots
- formatDateTime
- dateName
- FROM_UNIXTIME
- toModifiedJulianDay
- toModifiedJulianDayOrNull
- fromModifiedJulianDay
- fromModifiedJulianDayOrNull

**Comment by gauss1314** [comment]
Let me implement `toStartOfYear` function.

**Comment by dust1** [comment]
Hello i am interested. 
Does this mean I need to implement the above functions in the `SELECT` statement like the clickhouse example : `SELECT toDateTime('2016-06-15 23:00:00') AS time,  toDate(time) AS date_local, toDate(time, 'Asia/Yekaterinburg') AS date_yekat, toString(time, 'US/Samoa') AS time_samoa` ?

**Comment by sundy-li** [comment]
> Does this mean I need to implement the above functions in the SELECT statement like the clickhouse example

Yes, but we must introduce Date/DateTime datatypes in previous

**Comment by dust1** [comment]
> Yes, but we must introduce Date/DateTime datatypes in previous

A bit challenging. Maybe I can try it. 
Can you give me some reference about how to introduce Date/DateTime datatypes ?
And it's a task lists, Can I submit a PR of a certain function separately ?

**Comment by sundy-li** [comment]
> Can you give me some reference about how to introduce Date/DateTime datatypes ?

Since Datafuse runtime compute system is base on arrow2, so we are considering  help to add custom logic datatypes in arrow2.  Refer:  https://github.com/jorgecarleitao/arrow2/issues/326

**Comment by sundy-li** [comment]
@gauss1314  @dust1   

Now we have `Date16`, `Date32`, `DateTime32` types, and we have an example function `now`, `today` in  https://github.com/datafuselabs/datafuse/tree/master/common/functions/src/scalars/dates

You can continue this task now. Let's implement it in order by priority.

**Comment by dust1** [comment]
> You can continue this task now. Let's implement it in order by priority.

ok

**Comment by ygf11** [comment]
@sundy-li I am interested in these task.
To avoid conflict, which one should I task?

**Comment by sundy-li** [comment]
> @sundy-li I am also interested in these task.
> To avoid conflict, which one should I task?

Thanks, You can try these three first

```
 toYYYYMM
 toYYYYMMDD
 toYYYYMMDDhhmmss
```

**Comment by ygf11** [comment]
> Since they are all return numbers, so better to design it as a generic function or something like LogicFunction

ok.

**Comment by TCeason** [comment]
/assign 

Could I try to impl the func `timezone`?

**Comment by sundy-li** [comment]
> Could I try to impl the func timezone?

Yes, but we better add timezone into DateTime Type in previous, you can try this task #1680

**Comment by taiyang-li** [comment]
/assignme

Could I try `toDate` and `toDateTime`  ? @sundy-li

**Comment by taiyang-li** [comment]
> /assignme
> 
> Could I try `toDate` and `toDateTime` ? @sundy-li

I just found `toDate`  and `toDateTime` is already implemented in newest master version.

But I probably found a bug about `toDateTime`. Reproduce as follow:

```
datafuse :) select  toDateTime(1630320462), toUInt32(toDateTime(1630320462))  = 1630320462;

SELECT 
    toDateTime(1630320462),
    toUInt32(toDateTime(1630320462)) = 1630320462


Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from 127.0.0.1:9000


[2021-09-05T12:46:09Z INFO  datafuse_query::sessions::context] Create DatafuseQueryContext
thread 'tokio-runtime-worker' panicked at 'not implemented', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-srv-0.3.1/src/types/column/chrono_datetime.rs:88:9
```

**Comment by dust1** [comment]
> > /assignme
> > Could I try `toDate` and `toDateTime` ? @sundy-li
> 
> I just found `toDate` and `toDateTime` is already implemented in newest master version.
> 
> But I probably found a bug about `toDateTime`. Reproduce as follow. I will try to solve it.
> 
> ```
> datafuse :) select  toDateTime(1630320462), toUInt32(toDateTime(1630320462))  = 1630320462;
> 
> SELECT 
>     toDateTime(1630320462),
>     toUInt32(toDateTime(1630320462)) = 1630320462
> 
> 
> Exception on client:
> Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from 127.0.0.1:9000
> 
> 
> [2021-09-05T12:46:09Z INFO  datafuse_query::sessions::context] Create DatafuseQueryContext
> thread 'tokio-runtime-worker' panicked at 'not implemented', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-srv-0.3.1/src/types/column/chrono_datetime.rs:88:9
> ```

It looks like the service is not started?
run `make clean` and try again?

**Comment by sundy-li** [comment]
`clickhouse-srv` has some unimplemented function in datetimes, please use `mysql-client` for testing.
I'll create an other issue to track this.

**Comment by GrapeBaBa** [comment]
@sundy-li cool, which one can i try?

**Comment by sundy-li** [comment]
> @sundy-li cool, which one can i try?

You can try from toMonth --> toMonday

**Comment by GrapeBaBa** [comment]
> > @sundy-li cool, which one can i try?
> 
> You can try from toMonth --> toMonday

@sundy-li I saw this items with WIP label, Is somebody doing these?

**Comment by sundy-li** [comment]
> > > @sundy-li cool, which one can i try?
> > 
> > 
> > You can try from toMonth --> toMonday
> 
> @sundy-li I saw this items with WIP label, Is somebody doing these?

I set it to wip mean you are assigned of this, I'll update the assigners

**Comment by dust1** [comment]
Next, do I implement the `oStartOfYear` and `toStartOfISOYear` functions or other?

**Comment by dust1** [comment]
toStartOfQuarter
toStartOfMonth
toStartOfWeek

**Comment by dust1** [comment]
The toStartOfInterval function only needs to be implemented `INTERVAL x year`, `INTERVAL x month`, `INTERVAL x day`, ` `INTERVAL x minute `,`INTERVAL x house`,Will there be others?

**Comment by Xuanwo** [comment]
Is this issue still going on?

**Comment by sundy-li** [comment]
Let's close it, thanks for all the contributors.
