### ISSUE TITLE
refactor: add a function to concat multi DataBlocks

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8537]
**Summary**

more efficient then concat 2 each time.

**Comment by youngsofun** [comment]
with this optimization, we can assume that 1 is faster than 2:

1.  deserialize to DataBlocks in multi-thread, then join them into one
2. deserialize in one thread.

**Comment by sundy-li** [comment]
Yes, the first one could be faster, but it wastes lots of temp memory.

**Comment by youngsofun** [comment]
with the same block thresholds,  don`t they use (nearly) the same size of temp memory?

**Comment by youngsofun** [comment]
what is the problem with s3 multi-part for sink (to reduce memory usage)?

**Comment by Xuanwo** [comment]
Here are some s3 multipart's limitations:

- All parts must be larger than 4MiB (unless it's the last part)
- At most 10000 parts
- Parts must be complete in order (For example, complete part [1,4,2] will be wrong, [1,3,5] is ok)

**Comment by sundy-li** [comment]
we can add `concat_multi` in the new expression framework. The builder can push the entire column into.

**Comment by youngsofun** [comment]
done
