### ISSUE TITLE
performance: read_escaped_string_text when COPY TSV file

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8572]
**Summary**

How to bench:
https://github.com/BohuTANG/bendlog/blob/main/scripts/README.md

When the `request_body`&`response_body` column length is 2048 random string, `read_escaped_string_text` is the CPU bottleneck.

```
perf record -g -p <databend-query-pid-when-copy>
perf report -g
```
![813097a2-f8ba-4386-80f7-099f8036c16a](https://user-images.githubusercontent.com/172204/199173858-d0648a22-aaf5-4cc1-a981-aeb09e683e77.jpeg)

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/172204/199174524-3d926c5d-4401-4c50-be15-42868345561e.png">

**Comment by BohuTANG** [comment]
cc @youngsofun @sundy-li

**Comment by BohuTANG** [comment]
Copy parquet file perf:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/172204/199176779-8508e052-e16e-4aa7-990b-6e78558d871d.png">

**Comment by youngsofun** [comment]
caused by https://github.com/datafuselabs/databend/issues/8486
