### ISSUE TITLE
idea: Adopt async-backtrace for efficiently track and view the state of asynchronous tasks

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend#8573]
**Summary**

Reference: https://tokio.rs/blog/2022-10-announcing-async-backtrace

We can start with applying them for our pipelines

**Comment by jswrenn** [comment]
I'm the maintainer of `async-backtrace`. If anyone picks up this issue, I'd love to hear how it goes. The `async-backtrace` is early in its development, and input from early-adopters is essential for shaping the future of the crate.

**Comment by Xuanwo** [comment]
Let me build the simplest example so others can explore `async-backtrace` in the databend~

**Comment by Xuanwo** [comment]
Hi, @jswrenn, I have added the basic integration with async-backtrace in https://github.com/datafuselabs/databend/issues/8573.

In that PR, I add `#[async_backtrace::framed]` for our async IO functions, and add a new HTTP handler `/debug/async_backtrace` to get the output.

However, I can't get the expected async_backtrace like in the example.

- No changes in `tokio-console` (maybe I missed something?)
- HTTP GET `/debug/async_backtrace` always returns empty.

Questions:

- Is this usage matches your expectation?
- Can we have a `level` idea on async backtrace? (so we can reduce some cost in critical path)

**Comment by Xuanwo** [comment]
Implemented by @zhang2014
