### ISSUE TITLE
[build] support RISC-V build

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#860]
(you don't have to strictly follow this form)

**Describe the bug**
```
cargo install cross
cross build --target riscv64gc-unknown-linux-gnu
```

Error:
```
error[E0432]: unresolved import `alignment::ALIGNMENT`
  --> /cargo/git/checkouts/arrow-rs-f55612a56b22f079/6e2f684/arrow/src/alloc/mod.rs:31:9
   |
31 | pub use alignment::ALIGNMENT;
   |         ^^^^^^^^^^^^^^^^^^^^ no `ALIGNMENT` in `alloc::alignment`

```

https://github.com/apache/arrow-rs/blob/6e2f68420e03fe6926e8c2ffbd4441fc8cc1aeab/arrow/src/alloc/alignment.rs
missing the `cfg(target_arch = "riscv")` for ALIGNMENT

**Comment by Xuanwo** [comment]
Not used so far. Let's closing.
