### ISSUE TITLE
Feature: replace `RwLock<HashMap>` and `Mutex<HashMap>` by using DashMap

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#8601]
**Summary**

Using [DashMap](https://github.com/xacrimon/dashmap) will bring two advantages

- code will be cleaner
- potential performance improvement.

**Comment by ClSlaid** [comment]
May I take a look?

**Comment by xudong963** [comment]
@ClSlaid seems the issue was solved?

**Comment by ClSlaid** [comment]
Looks so, we can close this.
