### ISSUE TITLE
[store] testing: move integration tests into standalone crates

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#861]
**Summary**

Currently all tests are compiled within crate `fuse-store`. Every single change results in a complete re-compile.

Goal: 
Move integration tests, such as that bring up a small cluster, to some **tests** crate, i.e., put them in the `tests/` so that every file is compiled into a standalone testing crate.

**Comment by Xuanwo** [comment]
Seems we have done it via `tests/it`. Are there any other actions needed to take for this issue?
