### ISSUE TITLE
Feature:  replace current logic test sql driver with databend-py

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#8634]
**Summary**

Currently we adopted a hacked clickhouse sql-alchemy driver for our logic tests, thus far our official python driver is released https://github.com/databendcloud/databend-py, and we could adopt it in our logic test

**Comment by ZhiHanZ** [comment]
cc @hantmac @flaneur2020

**Comment by Xuanwo** [comment]
We need separate compatilbe tests after this change.

- databend-py for logic tests
- mysql, clickhouse's driver for compatible tests to make sure users can connect databend.
