### ISSUE TITLE
feat: Support `ON_ERROR = CONTINUE | ABORT_STATEMENT` in the CopyOptions when do COPY INTO

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8642]
COPY supports new option:
```
ON_ERROR = CONTINUE | ABORT_STATEMENT
```

* CONTINUE: any files will skip and let the copy continue
* ABORT_STATEMENT: abort the copy operation if any errors happends

**Comment by ariesdevil** [comment]
related with https://github.com/datafuselabs/databend/issues/8920
