### ISSUE TITLE
[sqlparser] better sql parser?

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#866]
**Summary**

[sqlparser-rs](https://github.com/ballista-compute/sqlparser-rs)  is not easy to extend and we are looking for a good alternative(if have), comments are welcome

Reference:
https://github.com/datafuselabs/datafuse/blob/36dce2064742a1d64bfcf9a7cd308d0f5a3e4eb5/fusequery/query/src/sql/sql_parser.rs

**Comment by BohuTANG** [comment]
[nom-sql[(https://github.com/ms705/nom-sql) but no update for a long time

**Comment by PsiACE** [comment]
It seems that sqlparser lacks good alternatives. If necessary, we may need to maintain one by ourselves.

[quaint](https://github.com/prisma/quaint) is not a parser, but
- An AST for building dynamic SQL queries.
- Visitors for different databases to generate SQL strings.

[toydb-parser](https://github.com/erikgrinaker/toydb/tree/master/src/sql/parser) is the parser for toydb

**Comment by sundy-li** [comment]
How about parsers from yacc rules?

**Comment by dantengsky** [comment]
FYI : 

lalrpop: an lr(1) parser generator   (lexer could be customized)

repo: https://github.com/lalrpop/lalrpop
doc: http://lalrpop.github.io/lalrpop/

-  never exercise it before
-  seems it lacks precedence/association rules declaration (again I am not sure.)

After googling around, I found a SQL parser using it:

https://github.com/hmwill/vervolg/blob/main/src/sql.lalrpop

**Comment by leiysky** [comment]
> [nom-sql](https://github.com/ms705/nom-sql)
> but no update for a long time

`nom` is a nice parser combinator, with which we can extend SQL syntax easily.

I think we can fork [nom-sql](https://github.com/ms705/nom-sql) or make one from scratch(not a big deal).

Here's a `nom` [Cypher parser](https://github.com/leiysky/tigraph/blob/master/src/parser/parser.rs) I wrote at a Hackathon, which only cost me about few hours :rofl: . FYI.

**Comment by BohuTANG** [comment]
> How about parsers from yacc rules?

https://github.com/lalrpop/lalrpop is rust yacc

**Comment by leiysky** [comment]
Based on my experience, working with bison(yacc) is suffering.

Here's the MySQL's yacc file, which has about 17,000 LOC.

https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy

Imagine that coding in a extremely huge plain text file without lint tool(no jump, no high light, no auto format), what a pain.

**Comment by PsiACE** [comment]
> Based on my experience, working with bison(yacc) is suffering.

You are right, I also prefer a handwritten parser

**Comment by tlightsky** [comment]
> Based on my experience, working with bison(yacc) is suffering.
> 
> Here's the MySQL's yacc file, which has about 17,000 LOC.
> 
> https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy
> 
> Imagine that coding in a extremely huge plain text file without lint tool(no jump, no high light, no auto format), what a pain.

yes, hard to make changes to it

**Comment by abhikjain360** [comment]
If writing your own, maybe something like [`pest`](https://github.com/pest-parser/pest) can be used as well. [Tensorbase](https://github.com/tensorbase/tensorbase) uses it (see [here](https://github.com/tensorbase/tensorbase/blob/main/crates/lang/src/bql.pest)), and it seems pretty maintainable?

**Comment by BohuTANG** [comment]
@abhikjain360 Thanks for the information, cool

**Comment by zhang2014** [comment]
Maybe our sql parser is support multi dialect

- When users use the ClickHouse protocol to access DataFuse, we may be ClickHouse style (syntax, function name)
- When users use the MySQL protocol to access DataFuse, we should use MySQL style(syntax, function name)

**Comment by leiysky** [comment]
> Maybe our sql parser is support multi dialect
> 
> * When users use the ClickHouse protocol to access DataFuse, we may be ClickHouse style (syntax, function name)
> * When users use the MySQL protocol to access DataFuse, we should use MySQL style(syntax, function name)

@zhang2014 Maybe we can disscuss this in #1218

**Comment by LeeMaster** [comment]
maybe handwritten parser is a good approach

**Comment by BohuTANG** [comment]
> maybe handwritten parser is a good approach

Hi!
There are 2 main purposes for the parser re-design: Extendibility and Maintainability.
For Maintainability, the handwritten parser is hard to matain(what's clickhouse does), so not recommand here.
For the parser, I would like it based on some rusty parser framework such as [pest](https://github.com/pest-parser/pest) or others.
Good/New ideas are always welcome~

**Comment by leiysky** [comment]
As we discussed in #1492 , the main idea about SQL grammar is based on PostgreSQL. Here's a reference of PostgreSQL grammar https://www.postgresql.org/docs/13/sql-select.html.

So the last problem is technical selection.

**Comment by BohuTANG** [comment]
Nice, @leiysky which one(or list) do you personally preferred?

**Comment by leiysky** [comment]
> Nice, @leiysky which one(or list) do you personally preferred?

I prefer parser combinator like `nom`, the benifits of which are better maintainability and better extensibility. 

Thanks to its declaritive style, the parser written with parser combinator follows the grammar specification, which means you can add your own syntax element easily(generally you need to modify the grammar specification first to make sure it's well defined).

**Comment by sundy-li** [comment]
`nom` seems to be a very good parser combinators library, but  LocustDB replaced nom parser by `sqlparser-rs`.

https://togithub.com/cswinter/LocustDB/pull/42/files

**Comment by leiysky** [comment]
> `nom` seems to be a very good parser combinators library, but LocustDB replaced nom parser by `sqlparser-rs`.
> 
> https://togithub.com/cswinter/LocustDB/pull/42/files

IMHO, it's because they don't have enough motivation to maintain a SQL parser by themselves.

**Comment by BohuTANG** [comment]
Ok, make sense to use nom.

**Comment by ives9638** [comment]
https://github.com/rrevenantt/antlr4rust

**Comment by ives9638** [comment]
https://github.com/peterhal/presto_rs/

Hope it helps

**Comment by leiysky** [comment]
> https://github.com/rrevenantt/antlr4rust

Antlr is a powerful parser framework as well. I didn't involve it since AFAIK currently there is no official rust target.

Seems this library has been used by some projects, I'll take a look at it.

Thanks very much.

**Comment by hustnn** [comment]
> IMHO, it's because they don't have enough motivation to maintain a SQL parser by themselves.

What is the major motivation to replace `sqlparser-rs` with own parser based on `nom' ? I played with `nom` recently, it is more like LEGO but still some effort.

**Comment by leiysky** [comment]
> > IMHO, it's because they don't have enough motivation to maintain a SQL parser by themselves.
> 
> 
> 
> @leiysky What is the major motivation to replace `sqlparser-rs` with own parser based on `nom` ? I played with `nom` recently, it is more like LEGO but still need a lot of effort.

Hi, @hustnn.

Actually, we haven't decided which scheme to use yet. `nom` is one of the candidates.

We'd like to have a more maintainable SQL, which is easy for us to support new SQL syntax.

Do you have any suggestion about this?

**Comment by hustnn** [comment]
I am implementing a demo to show the possibility of the sql parser on top of nom but I feel the effort is still quite high even it already provides some combinators for usage.

The biggest benefit of have a own parser is more flexible like you can define the ASTs structure you want. Also nom did provide some powerful combinators so we can leverage them when building own parser. I feel can try implement own parser based on nom in long term, but I suggest to focus on other high priority tasks first with existing parser. 

How do you think? @leiysky

**Comment by leiysky** [comment]
@hustnn Sorry for replying so late. 

> The biggest benefit of have a own parser is more flexible like you can define the ASTs structure you want. Also nom did provide some powerful combinators so we can leverage them when building own parser.

You actually get the point. We do have a set of AST structure defined by ourselves, with which I'm doing some refactor. These AST structures can be directly transformed from `sqlparser-rs`'s AST, so one day we can replace sqlparser-rs with our own parser.

`nom` is a good choice. We're glad to have you as collaborator on this work. Please let me know if you need any help.

**Comment by leiysky** [comment]
> https://github.com/rrevenantt/antlr4rust

I've recently taken a look at this project. It's in a very early stage, and the author hasn't put much effort into it.

Besides, antlr relies on java to run the code generator, which may bring unnecessary complexity for our development workflow.

**Comment by jiangzhe** [comment]
> @hustnn Sorry for replying so late.
> 
> > The biggest benefit of have a own parser is more flexible like you can define the ASTs structure you want. Also nom did provide some powerful combinators so we can leverage them when building own parser.
> 
> You actually get the point. We do have a set of AST structure defined by ourselves, with which I'm doing some refactor. These AST structures can be directly transformed from `sqlparser-rs`'s AST, so one day we can replace sqlparser-rs with our own parser.
> 
> `nom` is a good choice. We're glad to have you as collaborator on this work. Please let me know if you need any help.

I've implemented [a simple SQL parser](https://github.com/jiangzhe/xngin/tree/main/xngin-frontend) using nom, including complex SELECT(except WINDOW clause) and simple INSERT/DELETE/UPDATE. 
The total effort is about 3 weeks in part-time, so not very large, I guess. I didn't count the extra work on DDL.
One note is about expression parsing. The parser combinator is not very good for handling operator precedence. I used pratt parsing technique, which is simple and clear, and works well with combinator.

**Comment by andylokandy** [comment]
The new parser is now tracking by https://github.com/datafuselabs/databend/issues/1218
