### ISSUE TITLE
Migrate semi-structure `get_path` from `sqlparser` to new parser

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8663]
- [ ] Migrate semi-structure `get_path` from `sqlparser` to new parse, cc @b41sh

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/8622#issuecomment-1304945973_

**Comment by Xuanwo** [comment]
The issue's title has been updated to meet our requirements.
