### ISSUE TITLE
Feature: Support merge update operation

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#8685]
**Summary**
compare and update target table based on reference table

example:
```sql
merge into target_table using source_table 
    on target_table.id = source_table.id
    when matched then 
        update set target_table.description = source_table.description;
+------------------------+
| number of rows updated |
|------------------------|
|                      1 |
+------------------------+
```
Ref:
https://docs.snowflake.com/en/sql-reference/sql/merge.html

**Comment by hantmac** [comment]
`dbt` snapshot depends on `merge into`.

**Comment by ZhiHanZ** [comment]
> `dbt` snapshot depends on `merge into`.


dbt adapter documentation suggests that we could use delete + insert to replace merge operations. I think that may worth trying

**Comment by flaneur2020** [comment]
I'd like to take this issue to have an investigation about whether it's hard or not to implementing MERGE INTO statement in our code base.

An investigation is prioritized first, the implementation may be seperated in serveral issues.

**Comment by flaneur2020** [comment]
MERGE statement have some complexities about handling JOINs. To make the CDC solutions, making UPSERT may be a easier path: https://github.com/datafuselabs/databend/issues/9861

the UPSERT statement do not need integration with JOIN, and can process batched CDC streams.

but UPSERT have some limitations when compared with the MERGE statment:

- can not run some basic ETL (like extract fields from json) in the SQL like the merge statement
- can not handle DELETE
