### ISSUE TITLE
should we accept `81.00` for int field in file formats?

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8724]
**Summary**

column `DepDelay` is Int in the ontime table schema.

-  in ontime200.csv, values are floats like 81.00
-  in ontime200.ndjson,  values are ints like 81

there are many other column with the same problem.

questions:

- is  the  ontime200.csv wrong,  how was it generated?
- is the schema in ontime.sql wrong? 
- should we accept `81.00` for int field in file formats?

this lead to ci failures
 https://github.com/datafuselabs/databend/actions/runs/3426993563/jobs/5709630704
the error is raised because the crate lexical_core think  `81.00` can not be parsed as int

it could pass because there was a bug in the original BufReader, which is fix in this pr https://github.com/datafuselabs/databend/pull/8716

**Comment by youngsofun** [comment]
cc @BohuTANG @wubx @sundy-li

**Comment by youngsofun** [comment]
according to the clickhouse reference:
https://clickhouse.com/docs/en/getting-started/example-datasets/ontime

 the `.00` exists in the original data https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_1987_1.zip

and the type used in clickhouse is Int

**Comment by sundy-li** [comment]
I think we can ignore the numbers after the point.

Seems we already cover this in `read_int_text`.

**Comment by youngsofun** [comment]
yes, I add a new new commit, new read_int_text only ingore zeros after the point.

we should not allow `-2.33333` as in the original read_int_text.

> I think we can ignore the numbers after the point.
> 
> Seems we already cover this in `read_int_text`.
