### ISSUE TITLE
bug:  UNION ALL query read all columns 

### ISSUE THREAD

**Issue by BeSky** [datafuselabs/databend#8727]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.96-nightly-eee948d

### What's Wrong?

sql "select a from test1  UNION ALL select a from test2"  read all columns of table1 and table2;

create table test1(a int, b int, c int);
create table test2(a int, b int, c int);

MySQL [(none)]> explain select a from test1;
+--------------------------------------------------+
| explain                                          |
+--------------------------------------------------+
| TableScan                                        |
| ├── table: default.default.test1                 |
| ├── output_schema: [0]                           |
| ├── read rows: 0                                 |
| ├── read bytes: 0                                |
| ├── partitions total: 0                          |
| ├── partitions scanned: 0                        |
| └── push downs: [filters: [], limit: NONE]       |
+--------------------------------------------------+

MySQL [(none)]> explain select a from test2;
+--------------------------------------------------+
| explain                                          |
+--------------------------------------------------+
| TableScan                                        |
| ├── table: default.default.test2                 |
| ├── output_schema: [0]                           |
| ├── read rows: 0                                 |
| ├── read bytes: 0                                |
| ├── partitions total: 0                          |
| ├── partitions scanned: 0                        |
| └── push downs: [filters: [], limit: NONE]       |
+--------------------------------------------------+

MySQL [(none)]> explain select a from test1  UNION ALL select a from test2;
+--------------------------------------------------------+
| explain                                                |
+--------------------------------------------------------+
| UnionAll                                               |
| ├── TableScan                                          |
| │   ├── table: default.default.test1                   |
| │   ├── output_schema: [0, 1, 2]                       |
| │   ├── read rows: 0                                   |
| │   ├── read bytes: 0                                  |
| │   ├── partitions total: 0                            |
| │   ├── partitions scanned: 0                          |
| │   └── push downs: [filters: [], limit: NONE]         |
| └── TableScan                                          |
|     ├── table: default.default.test2                   |
|     ├── output_schema: [3, 4, 5]                       |
|     ├── read rows: 0                                   |
|     ├── read bytes: 0                                  |
|     ├── partitions total: 0                            |
|     ├── partitions scanned: 0                          |
|     └── push downs: [filters: [], limit: NONE]         |
+--------------------------------------------------------+

select a from test1  UNION ALL select a from test2  read all columns of table1 and table2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Seems we need to handle ` RelOperator::UnionAll(_)` in `prune_unused_columns`

**Comment by sandflee** [comment]
@leiysky @sundy-li , is there any progress?

**Comment by xudong963** [comment]
@sandflee I'll try to fix it on the weekend.
