### ISSUE TITLE
refactor: use AsyncReadPartition instead of lazy_init_segments in fuse read_data

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8731]
**Summary**

https://github.com/datafuselabs/databend/blob/1fd671735e493e6165e0768030ca97bb8192d223/src/query/storages/fuse/fuse/src/operations/read_data.rs#L127-L168

We can impl a `AsyncSource`(use data block `MetaInfo`) and add it to the pipeline before the FuseSource.

**Comment by zhang2014** [comment]
move to https://github.com/datafuselabs/databend/issues/10981
