### ISSUE TITLE
Consider revert DashMap

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#8744]
**Summary**
DashMap will introduce gc threads. If it's not necessary, maybe we should consider revert it.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/8087042/201253737-2c3e7362-fd1d-48d7-8588-b2a83ad2e966.png">

**Comment by PsiACE** [comment]
> DashMap will introduce gc threads. If it's not necessary, maybe we should consider revert it.

https://github.com/moka-rs/moka 

It looks like a moka problem

**Comment by Xuanwo** [comment]
We can fix this on the opendal side. @PsiACE Do you want to do this?

**Comment by PsiACE** [comment]
> We can fix this on the opendal side. @PsiACE Do you want to do this?

OK, I'll check it out and it looks like I can add a new parameter to the `Builder`

**Comment by Xuanwo** [comment]
> OK, I'll check it out and it looks like I can add a new parameter to the `Builder`

We can just disable it directly and add it back if users need this.

**Comment by PsiACE** [comment]
> We can just disable it directly and add it back if users need this.

oops, it looks like we're using `moka::future::Cache`, this option doesn't work, I'll check again. :cry: :

**Comment by Xuanwo** [comment]
Maybe we can replace `future::Cache` with [sync::SegmentedCache](https://docs.rs/moka/0.9.6/moka/sync/struct.SegmentedCache.html) or [dash::Cach](https://docs.rs/moka/0.9.6/moka/dash/struct.Cache.html)

**Comment by Xuanwo** [comment]
Already addressed.
