### ISSUE TITLE
query clusters(node1 and node2),  node2 run , node1 doesn't run

### ISSUE THREAD

**Issue by jackjoesh** [datafuselabs/databend#8791]
**Summary**
mysql connects to node1,  run: select * from log where request_time > 1668326959000  and request_time < 1668413359000 and user_id = 221720994  limit 1;
node2 run , node1 doesn't run

mysql> select * from fuse_snapshot('default', 'log') limit 1 \G;
*************************** 1. row ***************************
         snapshot_id: ded68536adfb4d9992ba70897ddf5eda
   snapshot_location: 1/966698/_ss/ded68536adfb4d9992ba70897ddf5eda_v1.json
      format_version: 1
previous_snapshot_id: 20e328b51ee34a87a0b1cde97cde1da3
       segment_count: 1786
         block_count: 2800429
           row_count: 25286795150
  bytes_uncompressed: 309449658357001
    bytes_compressed: 303676916077197
          index_size: 491731182205
           timestamp: 2022-11-14 08:41:25.925007
1 row in set (2.31 sec)
Read 1 rows, 231.00 B in 2.213 sec., 0.45179839911472086 rows/sec., 104.37 B/sec.

![0](https://user-images.githubusercontent.com/28348638/201628640-a947b7d4-4380-4811-82e5-9a6dbb806e7b.jpg)

**node 1 doesn't run**
![1](https://user-images.githubusercontent.com/28348638/201628692-987d9314-d3aa-4297-bedd-f001ffef3b8c.jpg)

**node2 run**
![2](https://user-images.githubusercontent.com/28348638/201628712-ff7b33d6-b0a3-4f37-a2fe-66d15a94e04b.jpg)

**Comment by BohuTANG** [comment]
Outdated.
