### ISSUE TITLE
Feature: consider implement databend-client

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#8809]
**Summary**

reference:
- mysql: https://dev.mysql.com/doc/refman/8.0/en/mysql.html
- clickhouse: https://clickhouse.com/docs/en/integrations/sql-clients/cli
- snowflake: https://docs.snowflake.com/en/user-guide/snowsql-start.html

**Comment by zhang2014** [comment]
CC: @BohuTANG @sundy-li

**Comment by everpcpc** [comment]
We already have https://github.com/databendcloud/bendsql

**Comment by johnhaxx7** [comment]
Seems like this is good to close?
