### ISSUE TITLE
Feature:  add per segment number of blocks info to snapshot

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#8817]
**Summary**

suggested by @sundy-li @BohuTANG :

add per segment number_of_blocks at table snapshot level, to make the partition shuffle more fine-grained balanced.

**Comment by sundy-li** [comment]
It's not in a hurry, maybe we can do it next month after we have new expression.

**Comment by BohuTANG** [comment]
It's not hard to do, @dantengsky plans to work on it :)

**Comment by dantengsky** [comment]
We have already implemented block-level shuffle. we can reopen it in case the optimization of data compaction or re-clustering requires "per segment block number" at the snapshot level.
