### ISSUE TITLE
[deployment] painless deployment

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#882]
**Summary**

For a  quick installation of datafuse, it might be useful  to  integrate the deployment with `cargo-deb` and `cargo-rpm`

https://github.com/iqlusioninc/cargo-rpm
https://github.com/mmstick/cargo-deb

**Comment by BohuTANG** [comment]
Maybe we need a deploy tool(DatafuseUP) like [tiup](https://docs.pingcap.com/zh/tidb/stable/production-deployment-using-tiup) for both on-premise and on-cloud.
cc @ZhiHanZ

**Comment by BohuTANG** [comment]
This maybe useful:
https://github.com/sagiegurari/cargo-make
