### ISSUE TITLE
Bug:  compact_final of BlockCompactorNoSplit should take block size threshold into account

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#8823]
**Summary**

during `compact_final`, the threshold of block size should be taken into account, instead of simply concating all the data blocks passed in. 

https://github.com/datafuselabs/databend/blob/3abd39ce2d6bb5d8cbb44788fb767399e01cdd8d/src/query/pipeline/transforms/src/processors/transforms/transform_block_compact_no_split.rs#L99-L114

otherwise, if lots of fragments are gathered at this phase,  the simple concating strategy may lead to blocks of huge size.

**Comment by youngsofun** [comment]
each time a block is added， `compact_partial` tries to make sure sum of datablocks in compactor is below threshold

**Comment by dantengsky** [comment]
> each time a block is added， `compact_partial` tries to make sure sum of datablocks in compactor is below threshold

does this mean that during `compact_final`, the total size of blocks being contacted, is guaranteed to be less than block size threshold?

**Comment by youngsofun** [comment]
> does this mean that during compact_final, the total size of blocks being contacted, is guaranteed to be less than block size threshold?

I think so...maybe there is something I missed

**Comment by dantengsky** [comment]
this issue is more likely to be a false alarm.  sorry for bothering you guys  : )
