### ISSUE TITLE
In that case can fuse engine be accessible via arrow flight? Would be nice to run query engine via databend and the results are sent via arrow flight.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8846]
In that case can fuse engine be accessible via arrow flight? Would be nice to run query engine via databend and the results are sent via arrow flight.

_Originally posted by @kesavkolla in https://github.com/datafuselabs/databend/discussions/8842#discussioncomment-4181687_

**Comment by shamb0** [comment]
@BohuTANG . I'm interested in working on this feature. Could you please assign it to me? Thankyou

**Comment by shamb0** [comment]
Thanks for update @BohuTANG
