### ISSUE TITLE
feat: add icon for different build binaries

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8861]
**Summary**

From lighthouse project:
https://github.com/sigp/lighthouse/blob/stable/.github/workflows/release.yml#L267-L282

https://github.com/sigp/lighthouse/releases/tag/v3.2.1
![image](https://user-images.githubusercontent.com/172204/202904301-79b01191-d1ab-4c5e-b73d-4257cb5beeab.png)

**Comment by BohuTANG** [comment]
cc @everpcpc @Xuanwo

**Comment by Xuanwo** [comment]
Is this issue still valid?
