### ISSUE TITLE
bug: COMPACT is slow and cpu load is low

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#8878]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.8.117-nightly

### What's Wrong?

Compact execution is slow and cpu load is low.

![image](https://user-images.githubusercontent.com/30121694/203035154-ff46c336-676c-4959-b931-e6a4e03b364f.png)
![image](https://user-images.githubusercontent.com/30121694/203035199-c10d4be0-8300-495f-b35a-f031cddfa07d.png)
block information:
![image](https://user-images.githubusercontent.com/30121694/203035333-d118a3bf-f061-4b20-91ea-252ff164cdfc.png)
![image](https://user-images.githubusercontent.com/30121694/203035389-0e64f1bd-fbd3-4ff6-8315-f5c575f0e570.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Addressed and working in progress.

**Comment by yufan022** [comment]
![image](https://user-images.githubusercontent.com/30121694/204072122-145571c6-a293-4b13-8c0a-e14dd4280477.png)
OOM occurred and there are many `xxx.parquet.cache not found` in the log.
