### ISSUE TITLE
Feature: Support pass a staged file path in the POST /v1/query args

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#8889]
**Summary**

On ingesting huge amount of data, staged file is the first choice, it have the lowest price.

We can consider adding a parameter like `valuesStagePath` which allows take a stage file's path as the payload of the data.

like:

```
{
  "sql": "INSERT INTO books VALUES",
  "valuesStagePath": "~/books.csv"
}
```

The insert SQL can be same as the clickhouse handler or the `insert_sql` in the streaming load api, the code may be reused among these handlers. The only exception is it takes a s3 staged path instead of reading in http streams.

It can auto purge the staged file by default.

**Comment by flaneur2020** [comment]
after this feature supported, we can remove some hacks in the python driver to make dbt integration easier.

**Comment by Xuanwo** [comment]
What's the difference between calling `COPY FROM ~/books.csv INTO books`?

**Comment by flaneur2020** [comment]
> What's the difference between calling `COPY FROM ~/books.csv INTO books`?

it's hard for COPY to make queries like this:

```
>>> client.execute(
... 'INSERT INTO test (x) VALUES (%(a)s), (%(b)s), ...',
... {'a': 1, 'b': 2, ...}
... )
```

IMHO, COPY cares about files (I already have got a file, want load it into databend), however INSERT INTO cares about data (I have a bunch of data, want insert it into databend, I do not care about what's the transport layer at all)
