### ISSUE TITLE
bug: `copy into` return meta retry too many times

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#8897]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest version

### What's Wrong?

`copy into` return meta retry too many times.

![img_v2_be19b64b-e6c3-4dcb-9a7a-995ba59302dg](https://user-images.githubusercontent.com/1998569/203314588-1886968f-3daa-4d2d-aab3-58031ab10913.jpg)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
Does this issue cause https://github.com/datafuselabs/databend/issues/8877?

**Comment by lichuang** [comment]
> #8877

no, just run meta in embed mode can reproduce this error.
