### ISSUE TITLE
feat: add compression option to create table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8903]
**Summary**

```
create table t1(a int) [compression="LZ4|SNAPPY"]
```
Default is `LZ4`

**Comment by johnhaxx7** [comment]
Hi @BohuTANG , is the `LZ4` only default for fuse engine? 
https://github.com/datafuselabs/databend/blob/dd27715c11c26e9c7a441a459c3adbc48fe1069e/src/query/storages/fuse/src/io/write/write_settings.rs#L35
 I'm not really sure but does other storage engine support `lz4` as default as well? In other words, what's the scope of this task, is it just plug in the optional parameter from query to back end?

**Comment by BohuTANG** [comment]
@johnhaxx7 Thanks for the remind.
We have support compression option for the table, and the default compression is change it from lz4to zstd, so here I need a checking.

**Comment by BohuTANG** [comment]
The table compression option was implemented: https://github.com/datafuselabs/databend/pull/9370
The `write_settigs.rs` table_compression fixed at: https://github.com/datafuselabs/databend/pull/9982
