### ISSUE TITLE
Feature: improve bulk insert speed 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#8911]
**Summary**
```
insert into tb values(1,'a','databend'),(2,'a','databend'),(3,'a','databend'),...
```

Maybe we could add settings to support inserts that don't degenerate into single inserts.

cc @sundy-li

**Comment by BohuTANG** [comment]
cc @TCeason

**Comment by sundy-li** [comment]
We already have `FieldDecoderValues`. 

We can add `SyncSource` trait implements for `ValueSource` and introduce a setting `insert_values_disable_expression`.
