### ISSUE TITLE
[roadmap-track] RBAC track

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#894]
**Summary**

Main issue tracking for Access Control and Account Management.

# Tasks

| Task                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [user API for query #869](https://github.com/datafuselabs/datafuse/issues/869) | DONE  |  v0.5 |   |
| [ user and password auth for MySQL/ClickHouse handler #1704](https://github.com/datafuselabs/datafuse/issues/1704) | DONE  |  v0.5 |  |

**Comment by BohuTANG** [comment]
Add:
[ user and password auth for MySQL/ClickHouse handler #1704](https://github.com/datafuselabs/datafuse/issues/1704)

**Comment by Xuanwo** [comment]
Closing for all task finished.
