### ISSUE TITLE
bug:  mysql jdbc read data failed for the num larger than 2^31

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#8940]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

mysql jdbc version:  5.1.40

### What's Wrong?

jdbc exception:  `com.mysql.jdbc.exceptions.jdbc4.MySQLDataException: '2.233763636E9' in column '1' is outside valid range for the datatype INTEGER.`
```
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.ResultSetImpl.throwRangeException(ResultSetImpl.java:7074) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.ResultSetImpl.parseIntAsDouble(ResultSetImpl.java:6352) ~[mysql-connector-java-5.1.40.jar:5.1.40]
```

databend parser mark  2233763636  as  Uint32, and converted to MYSQL_TYPE_LONG (is a integer) when sending to mysql client.
```rust
        fn convert_field_type(field: &DataField) -> Result<ColumnType> {
            match remove_nullable(field.data_type()).data_type_id() {
               TypeID::UInt32 => Ok(ColumnType::MYSQL_TYPE_LONG),
         }
```

mysql jdbc read MYSQL_TYPE_LONG as integer and checks for min/max. exception happens.

```java
   private void checkForIntegerTruncation(int columnIndex, byte[] valueAsBytes, int intValue) throws SQLException {
        if (this.jdbcCompliantTruncationForReads) {
            if (intValue == Integer.MIN_VALUE || intValue == Integer.MAX_VALUE) {
                String valueAsString = null;

                if (valueAsBytes == null) {
                    valueAsString = this.thisRow.getString(columnIndex, this.fields[columnIndex].getEncoding(), this.connection);
                }

                long valueAsLong = Long.parseLong(valueAsString == null ? StringUtils.toString(valueAsBytes) : valueAsString);

                if (valueAsLong < Integer.MIN_VALUE || valueAsLong > Integer.MAX_VALUE) {
                    throwRangeException(valueAsString == null ? StringUtils.toString(valueAsBytes) : valueAsString, columnIndex + 1, Types.INTEGER);
                }
            }
        }
```

MYSQL_TYPE_xx seems does't have a unsigned integer, so for safety, we parse the value larger than 2^31 as  Uint64?

### How to Reproduce?

1. run the sql `select 2233763636 as a;`
2. using mysql jdbc to read the data

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @TCeason

**Comment by TCeason** [comment]
```rust
fn make_column_from_field(field: &DataField) -> Result<Column> {
            convert_field_type(field).map(|column_type| Column {
                table: "".to_string(),
                column: field.name().to_string(),
                coltype: column_type,
                colflags: ColumnFlags::empty(),
            })
        }
```

Now the colflags is empty. I think it's better to add this.

https://docs.rs/mysql_common/latest/mysql_common/constants/struct.ColumnFlags.html#associatedconstant.UNSIGNED_FLAG

**Comment by TCeason** [comment]
![image](https://user-images.githubusercontent.com/33082201/203757775-704aca1e-935e-4914-bab6-5719ac2dec06.png)
I think maybe should use `getLong` to get this 2233763636 value?

**Comment by sandflee** [comment]
> I think maybe should use getLong to get this 2233763636 value?

this may be confusing for jdbc users, for the column is integer,  but we must get the result by `getLong` not `getInt`.  [UNSIGNED_FLAG] seems reasonable.

**Comment by TCeason** [comment]
> > I think maybe should use getLong to get this 2233763636 value?
> 
> this may be confusing for jdbc users, for the column is integer, but we must get the result by `getLong` not `getInt`. [UNSIGNED_FLAG] seems reasonable.

Yes, actually use MySQL jdbc getInt get MySQL unsigned int it also err. And I try to add flag unsigned_int flag the jdbc do not care the flag.

**Comment by TCeason** [comment]
So it maybe a MySQL jdbc bug. And I think we can judge the column type to choose use getInt or getLong?

If the column type has `unsigned` maybe can use getInt first, if catch exception `com.mysql.jdbc.exceptions.jdbc4.MySQLDataException` try to use getLong?
