### ISSUE TITLE
Feature: remove FormatSettings.

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8949]
**Summary**

only JsonAST  really use it.

1. new. JsonASTDecoder
2. new JsonASTEncoder.

Description for this feature.

**Comment by youngsofun** [comment]
@b41sh  

I will remove a direct use of serialize_json_values later,  after that serialize_json_values is only used by serialize_json_object
and serialize_json_object_suppress_error.
the only need of FormatSettings is the timezone in it.

can you explain them briefly? 
 I see they are impl for a few types why?  impl for TS but not Date.
 will they call each other?  need two JsonASTEncoder?


```
pub trait TypeSerializer<'a>: Send + Sync {
    fn serialize_json_values(&self, _format: &FormatSettings) -> Result<Vec<Value>>;

    fn serialize_json_object(
        &self,
        _valids: Option<&Bitmap>,
        _format: &FormatSettings,
    ) -> Result<Vec<Value>>;

    fn serialize_json_object_suppress_error(
        &self,
        _format: &FormatSettings,
    ) -> Result<Vec<Option<Value>>>;
}
```

**Comment by b41sh** [comment]
@youngsofun `serialize_json_values` is used to convert other data types to `JSON` values in some functions. `function-v2` no longer uses this function, we can remove it after the Expression migration is complete.
