### ISSUE TITLE
[mysql] add progress values response to mysql client

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#896]
**Summary**
add progress values response to mysql client

```
mysql> select sum(number) from numbers(100000);
+-------------+
| sum(number) |
+-------------+
|  4999950000 |
+-------------+
1 row in set (0.01 sec)
Read 131010 rows, 1023.52 KiB in 0.008378132 sec., 15637137 rows/sec., 119.30 MiB/sec.

```

Refer in clickhouse,  https://github.com/ClickHouse/ClickHouse/blob/master/src/Processors/Formats/Impl/MySQLOutputFormat.cpp#L63-L87

**Comment by BohuTANG** [comment]
Cool feature.
But it not a task to do it, mysql-svr needs a patch like:
https://github.com/BohuTANG/msql-srv/commit/4c3331f6cb07c0d48d968b4394c7f0e932503aba
