### ISSUE TITLE
bug: embedded_dir and address will use embedded_dir

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8975]
**Summary**

databend-query.toml(The old defualt config we recommend):
```
[meta]
embedded_dir = "./.databend/meta_embedded_1"
address = "127.0.0.1:9191"
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60
```

Because we deprecated `address` in #8924 , the old default config will start with `embedded_dir`:
https://github.com/datafuselabs/databend/blob/fd92d54952527b04c399db0bd312ce1965a1e91f/src/query/config/src/inner.rs#L268-L274

```
Databend Query

Version: v0.8.127-nightly-3223ccb(rust-1.67.0-nightly-2022-11-25T12:41:15.167115982Z)

Logging:
    file: enabled=true, level=ERROR, dir=./.databend/logs, format=json
    stderr: enabled=false(To enable: LOG_STDERR_ON=true or RUST_LOG=info), level=INFO, format=text
Meta: embedded at ./.databend/meta_embedded_1
```

**Comment by BohuTANG** [comment]
Can we let user not use the deprecated config? cc @Xuanwo @lichuang

**Comment by Xuanwo** [comment]
> Can we let user not use the deprecated config? cc @Xuanwo @lichuang

Remove `#[serde(default)]` will let `try_into` fail.
