### ISSUE TITLE
[cluster] add executor interface

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#898]
**Summary**

For distributed query, fuse-query first to check the cluster nodes is empty or not.
If nodes is not empty, the plan will add some remote stages and create a new one:
https://github.com/datafuselabs/datafuse/blob/d51f8dad4997049a68c07e969f9c4949ccfaa025/fusequery/query/src/interpreters/plan_scheduler.rs#L36-L45

It would be better&clear to wrap an abstract layer, executor:
```
#[derive(Debug)]
pub struct ExecutorNode {
    pub namespace: String,
    pub name: String,
    pub priority: u8,
    pub address: Address,
    pub local: bool,
    pub sequence: usize,
}

pub trait Executor {
  pub fn add_executor_node(&self) -> Result<()>;
  pub fn remove_executor_node(&self) -> Result<()>;
  pub fn get_executor_nodes(&self) -> Result<Vec<Arc<ExecutorNode>>>;
}
```

In context:
```
pub struct FuseQueryContext {
    executor: Arc<RwLock<Executor>>,
    ... ...
}
```

The method:
```
   pub fn try_get_cluster(&self) -> Result<ClusterRef> {
        let cluster = self.cluster.read();
        Ok(cluster.clone())
    }
```

can be change to:
```
   pub fn try_get_executors(&self) -> Result<Vec<Arc<ExecutorNode>>> {
        let executor = self.executor.read();
        Ok(executor.get_executor_nodes())
    }
```

This is one part of cloud service which discussed in:
https://github.com/datafuselabs/datafuse/issues/883

cc @zhang2014

**Comment by BohuTANG** [comment]
This is in discussion, comments are welcome :dancers:

**Comment by jovany-wang** [comment]
Sorry for being not so familiar with the details. Is `ExecutorNode` you mentioned above is a physical pod or a logical node of plan?

**Comment by BohuTANG** [comment]
> Sorry for being not so familiar with the details. Is `ExecutorNode` you mentioned above is a physical pod or a logical node of plan?

 physical pod, it tells where the remote plan to executed.

**Comment by Xuanwo** [comment]
@BohuTANG Is this still valid?

**Comment by BohuTANG** [comment]
Outdated.
