### ISSUE TITLE
Feature(VIP):  unify format options and remove `format_` settings

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#8995]
# background

we need many options for diff formats https://github.com/datafuselabs/databend/issues/8914

suppose we want to load a file with file format CSV and field delimiter "|".
we have 3 ways:

streaming load handler

```
curl  -u root: \
-H "insert_sql:insert into t1 format CSV"  \
-F "upload=@foo.csv"  \
-H "format_field_delimter=|" \
-XPUT http://127.0.0.1:8000/v1/streaming_load
```

clickhouse handler 

```
 curl 'http://localhost:8123/?query=insert%20into%20t1%20format%20CSV?format_field_delimter=| \
 --data-binary @foo.csv
```

copy SQL

```
copy into t1 from 's3://mybucket/foo.csv'
 FILE_FORMAT = (type = 'CSV'  field_delimiter = '|')
```

for the first two `format_field_delimter` is actually apply to the settings of the session (for the HTTP request).
 we can also pass any other settings the same way.
 

 So to summarize
 
 we have two repr for  "file format with format option"
 
 - SQL clause `FILE_FORMAT = (type = 'CSV'  some_option = '|')``,  for copy
 - SQL clause `FORMAT CSV` and the `format_xxx` settings, for insert with clickhouse and streaming load
 
 
 # what`s wrong with it
 
 
 Firstly, settings is  essentially **not ** suitable to store format option.
 
1.  the ·(type = 'CSV'  some_option = '|')` is a whole, should be set/update atomicly
2. setting must have one default value, 2 problem:
    1. we can not tell if it is set by user on purpose or set (global) by other users or just default.   in contrast, in `FILE_FORMAT = (type = 'CSV'  some_option = '|')`, it is clear weather an option 
  not appeared. and we have the `type = 'CSV` as context.
    2. diff format has diff default value

  
  
 
 
 Secondly, no good for compatiblily.

 1. for streaming load, we are free to design our style.
 2. for clickhouse, we are still not  compatible with
  clickhouse about the settings be cause the set of settings are different.
 
 thirdly, hard to use.
 
 1. not unified
 2. `format_` prefx make it long and easy to forget
 3. there will be many options later, add to a lot of settings.
 2. http header is hard to check and http param need escape.

 
 fourthly, hard to maintain.
 
 1. harder to check and report error
 2. need more code to add an option and test them
 
 
 # propose
 
 **only** use the snowflake style in any place (insert copy and "select from stage" later):
 
- `FILE_FORMAT = (type = 'CSV'  some_option = '|')`
- `FILE_FORMAT = (format_name = 'MyCustomCSV')`

 `FORMAT CSV` is retained for the ClickHouse handler.
 
 MyCustomCSV is created using SQL like 
 https://docs.snowflake.com/en/sql-reference/sql/create-file-format.html

 but the `format_xxx` setting will be removed.
 we may occasionally add one of settings from [clickhouse](https://clickhouse.com/docs/en/operations/settings/settings)
 if a wide-use need it, and deal it specially at the clickhouse handler, 
 in fact, we rarely need them.
 
 # steps 
 
 
 1. support `FILE_FORMAT = (type = 'CSV'  some_option = '|')` in insert too
 2. deprecate the use of `format_xxx` settings.
 3. parse result in `FormatOptionsInput{ field_delitmer: Option<String> }` but may still  store`FormatOptionst{ field_delitmer: String }` (not option) in meta because the value store should be  fixed and explicit.
 4. support `alter stage`, because there may be problems with
  FILE_FORMAT part of old stage store in meta, and their may be `copied file`
   binded to the stage object so we can not simply delete and create stage.
 5. support `FILE_FORMAT = (format_name = 'MyCustomCSV')` and `create file format` 

update
---

there was a typo in steps. 4,  changed to `FormatOptionst{ field_delitmer: String }` (no Option) 

a question is we now use `FILE_FORMAT` in copy and `FORMAT` in insert (for compatibility with clickhouse, do we need to unify them to one?

another topic is `FORMAT TSV ( field_delimiter = '|', ) `, vs   `FORMAT ( type = "TSV",  field_delimiter = '|', ) ` 

- the 1st is  more readable, and friendly to SQL parser and compatiblily with current insert  and the clickhouse style
- the 2nd, copy needs no change, same with snowflake.

**Comment by youngsofun** [comment]
related isues


https://github.com/datafuselabs/databend/issues/8604
https://github.com/datafuselabs/databend/issues/8986
https://github.com/datafuselabs/databend/issues/8541
https://github.com/datafuselabs/databend/issues/8100

**Comment by youngsofun** [comment]
cc @sundy-li @Xuanwo @andylokandy @wubx @BohuTANG

**Comment by wubx** [comment]
From the view of snowflake, the Copy into command is very complicated. We can refer to its parameter planning and use method on the whole, which can reduce the risk of getting lost in this area.

This can also learn a good habit to use.

**Comment by youngsofun** [comment]
there was a typo in steps. 4, changed to FormatOptionst{ field_delitmer}: String (no Option)

a question is we now use FILE_FORMAT in copy and FORMAT in insert (for compatibility with clickhouse, do we need to unify them to one?

another choice is FORMAT TSV ( field_delimiter = '|', ) , which is more readable, and friendly to SQL parser too. and FORMAT_NAME "MyCoustomFormat"

**Comment by wubx** [comment]
```
FORMAT ( type = "TSV", field_delimiter = '|', )
```
looks better. 

Here I think of a good proposal to improve our product,  more parameters are supported to support CSV introduced formats.

This work has the main consideration of SQL and streaming load.

clickhouse http handler in the backup when we get the native driver out, it's going to fade more and more.
