### ISSUE TITLE
bug:  sql generate different result at each attempt  in cluster mode.

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#9010]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

1340868f7c82eb353fd02e09a008ff864c941a9b

### What's Wrong?

sql may generate different  wrong result in cluster mode at different attempts.  while sql result is right in local cluster.

### How to Reproduce?

sql
```
SELECT count(*) AS sqlrewriter0
FROM
  (SELECT product_name,
          sum(cost_total) AS t
   FROM xxx
   WHERE p_date = '20221110'
   GROUP BY product_name
   HAVING t > 100000) AS a
ORDER BY sqlrewriter0
LIMIT 100
;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sandflee** [comment]
@sundy-li  the problem still exists on the latest version :(

**Comment by sandflee** [comment]
there're some other sqls, seems they all have more than one select and group by clauses.

**Comment by sandflee** [comment]
seems `sipHash` is used in `HashFlightScatter`, this may cause randomness.  
```
impl HashFlightScatter {
      let hash_functions = scalars
            .iter()
            .map(|k| FunctionFactory::instance().get("sipHash", &[&k.data_type()]))
            .collect::<Result<Vec<_>>>()?;
}
```

**Comment by BohuTANG** [comment]
@sandflee 

Thank you for your troubleshooting. 
Can you change `sipHash` to `md5` and re-run the query?

**Comment by sundy-li** [comment]
> @sandflee
> 
> Thank you for your troubleshooting. Can you change `sipHash` to `md5` and re-run the query?

we can't use md5, it generates string but we need u64 here.

we can use `xxhash64` instead. 

But seems siphash is using fixed seeds now.

```
impl DefaultHasher {
    /// Creates a new `DefaultHasher`.
    ///
    /// This hasher is not guaranteed to be the same as all other
    /// `DefaultHasher` instances, but is the same as all other `DefaultHasher`
    /// instances created through `new` or `default`.
    #[stable(feature = "hashmap_default_hasher", since = "1.13.0")]
    #[inline]
    #[allow(deprecated)]
    #[rustc_const_unstable(feature = "const_hash", issue = "104061")]
    #[must_use]
    pub const fn new() -> DefaultHasher {
        DefaultHasher(SipHasher13::new_with_keys(0, 0))
    }
}
```

**Comment by sandflee** [comment]
`xxhash64` and `ahash` takes no effect.  but if I could reproduce it by changing `max_storage_io_requests` (hive implemented) and `max_threads` , will review the related logic latter.

**Comment by sandflee** [comment]
I can reproduce it by changing the `max_thread` larger than `255`, a magic number. seems not related to `max_storage_io_requests`. cc @zhang2014
