### ISSUE TITLE
Feature:  range filter not support "in"

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#9038]
**Summary**

hive sql use range filter to prune partitions, runing sql like  select * from xx where a in (xx,xx,xx);  range filter could't take affect and may read all partition datas.

cc @sundy-li

**Comment by sundy-li** [comment]
Ok, range filter will be rewritten after we have the new expression by @andylokandy 

Please take your time with this feature.

**Comment by sandflee** [comment]
hi, @andylokandy , is any  expected time to do this?

**Comment by andylokandy** [comment]
It should be done at the time when `expression` branch is merged into main.

**Comment by sandflee** [comment]
so, when the expression branch is merged into main ?
