### ISSUE TITLE
Using the same mpcs::channle for the query and store

### ISSUE THREAD

**Issue by jyizheng** [datafuselabs/databend#904]
We can use the mpcs::channel in the query and store code.

https://github.com/datafuselabs/datafuse/blob/2fcec9447d54e0a1aa9e196f4487218394bf6f51/common/flights/src/store_client.rs#L320

https://github.com/datafuselabs/datafuse/blob/8a3008010501dca0a1613b60eee95df5b3b53ea1/fusequery/query/src/api/rpc/flight_dispatcher.rs#L18

**Comment by PsiACE** [comment]
I recommend using `futures::channel`

**Comment by Xuanwo** [comment]
Any updates about this issue? What actions should we take?

**Comment by Xuanwo** [comment]
Closing for no updates so far.
