### ISSUE TITLE
Feature: read_parquet table function

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#9048]
**Summary**

Description for this feature.

duckdb has a useful [parquet table function](https://duckdb.org/docs/data/parquet.html), we can have it in databend.

It may be duplicated with Stage Table Function in  https://github.com/datafuselabs/databend/issues/7211.

But it's much easy to implement a parquet table function because it's easy to infer schema from parquet files.

**Comment by BohuTANG** [comment]
Likely, It's same as stage table what @youngsofun is working.

**Comment by sundy-li** [comment]
> Likely, It's same as stage table what @youngsofun is working.

Yes, we have discussed this,  `read_parquet` could be more lightweight for developers to test the performance without loading into databend.  The code could be reused when we implement StageTable.
