### ISSUE TITLE
bug:  like '%_xxx'  mismatch content

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#9077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

xx

### What's Wrong?

`like '%_SIP'` mismatch contents like `IRxxSIPD`. but I run sqls like `select 'IRxxSIPD' like '%_SIP'`, the result is 0.
```
  (SELECT irid
   FROM xxx
   WHERE 
      irid LIKE '%_SIP')
ORDER BY irid
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
If want to match IRxxSIPD, I think the pattern should be “%_SIPD”

**Comment by TCeason** [comment]
https://github.com/datafuselabs/databend/blob/main/src/query/functions/src/scalars/comparisons/comparison_like.rs#L145
 

https://github.com/datafuselabs/databend/blob/main/src/query/functions/src/scalars/comparisons/comparison_like.rs#L64

bug in here, if contains _, should skip string search optimize.

**Comment by TCeason** [comment]
op(like(x, rhs))

Now we can use this func directly.

**Comment by sandflee** [comment]
thanks @TCeason , a little question,  why `select 'IRxxSIPD' like '%_SIP'` works fine?  they had different func internal?

**Comment by TCeason** [comment]
> thanks @TCeason , a little question, why `select 'IRxxSIPD' like '%_SIP'` works fine? they had different func internal?

yes, select string like pattern; will use vector_ vector in there https://github.com/datafuselabs/databend/blob/main/src/query/functions/src/scalars/comparisons/comparison_like.rs#L28
