### ISSUE TITLE
Proposal: add specific dir in doc about Performance Tuning

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9084]
**Summary**

We support **broadcast join** last week and I tested in my local with 100G tpch dataset and some SQLs can improve 2x performance.

However, it needs a switch to open, for our users, may not know it, even more, they don't know we support broadcast join.

So when they meet performance problems with cluster join, they'll feel depressed.

I prosal we add specific dir in doc about **Performance Tuning**, such as the **Query Acceleration** part in https://docs.starrocks.io/en-us/latest/using_starrocks/.

Then we can add some cases to it, such as **broadcast join**.

**Comment by xudong963** [comment]
cc @soyeric128 @Xuanwo @wubx @BohuTANG

**Comment by Xuanwo** [comment]
> However, it needs a switch to open, for our users, may not know it, even more, they don't know we support broadcast join.

The first problem comes into my mind is databend (planner) don't know when to enable them?

> I prosal we add specific dir in doc about **Performance Tuning**, such as the **Query Acceleration** part in

*The link is broken, correct one should be https://docs.starrocks.io/en-us/latest/using_starrocks/Cost_based_optimizer*

This idea LGTM. 

As we does need docs for users who want to go deeper of databend. We can provide a `user guide` like snowflake: https://docs.snowflake.com/en/user-guide/ui-query-profile.html

**Comment by xudong963** [comment]
> The first problem comes into my mind is databend (planner) don't know when to enable them?

Ideally, planner should choose the smallest cost to generate an executable plan, but that's not 100% dependable.

> We need docs for users who want to go deeper into databend. We can provide a `user guide` like snowflake: https://docs.snowflake.com/en/user-guide/ui-query-profile.html. In this guide, we don't teach users the detailed SQL or features but teach them how to use databend in better ways.

LGTM.
