### ISSUE TITLE
Feature: add a enableFinalUri parameter to HTTP Query API

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#9087]
**Summary**

the query below may make a session leak for 10 seconds:

```
curl -X POST .../v1/query -d '{"sql": "SELECT 1"}'
```

this is because we keeps tracks the query related resource until the query finalizer is called( by requesting the `final_uri`).

on many management scenaries, the queries are simple enough which do not need any pagination, like `SHOW USERS`, `SHOW TABLES`. On these queries, we can simplify avoid calling the `final_uri` by specifying a parameter like `enableFinalUri: false`.

**Comment by youngsofun** [comment]
> the queries are simple enough which do not need any pagination


@flaneur2020 



`enableFinalUri` can save a request,  but it only goes so far.
the client still needs to assume multi roundtrips, and make sure all of them are route to the same server.

even not work for the sample SQLs,  "simple" doesn`t mean it fast, any SQL about meta can be as slow as 2-3 secs.
while the long pulling timeout is 1 secs by default
