### ISSUE TITLE
[optimizer] support limit push down

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#910]
(you don't have to strictly follow this form)

**Describe the bug**

Start fuse-query:
```
FUSE_QUERY_LOG_LEVEL="TRACE" ./target/debug/fuse-query
```

clickhouse client:
```
select * from system.tracing limit 1;
```

Can not get the push down limit in the ReadSourcePlan `push_downs`, patch(Not merge to master yet):
https://github.com/datafuselabs/datafuse/pull/908/files#diff-5e1c887fc51d586402e26b76fb7b5a03765d6808f6eef3fb4ddb119f381b1745R108

**Comment by BohuTANG** [comment]
We can take the limit push down back:
https://github.com/datafuselabs/datafuse/pull/216/files#diff-70bcd68dc7c167f86978e44910638689745d00f1bf646d0d39fcf14abeb5b48d

I forgot why took it off from the optimizer.

cc @jyizheng

**Comment by jyizheng** [comment]
sound good

**Comment by Xuanwo** [comment]
@BohuTANG Is this issue still valid? I thought we have supported `limit`

**Comment by BohuTANG** [comment]
Done.
Let's close, thanks for reminding.
