### ISSUE TITLE
bug:  select from view return 'Unknown table'

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#9112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.8.143

### What's Wrong?

select * from "comments_stg";  and "comment_stg" is a view but return an error `Unknown table '_airbyte_raw_comments''`.

### How to Reproduce?

create view view_3 AS WITH source as (SELECT * FROM not_exist) SELECT * from source;

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
Let me try to fix it.

**Comment by xudong963** [comment]
```sql
mysql> create view view3 as with source as (select * from t1) select * from source;
Query OK, 0 rows affected (0.03 sec)

mysql> select * from view3;
+------+------+
| a    | b    |
+------+------+
|    1 |    2 |
|    3 |    4 |
+------+------+
2 rows in set (0.05 sec)
Read 2 rows, 16.00 B in 0.011 sec., 188.62 rows/sec., 1.47 KiB/sec.

mysql>
```

I can't reproduce, could you please give a specific demo?

**Comment by xudong963** [comment]
any thoughts? @hantmac

**Comment by hantmac** [comment]
> any thoughts? @hantmac

These days I am not working on dbt, I will call you when I reproduce it.

**Comment by hantmac** [comment]
Can't reproduce, closed.
