### ISSUE TITLE
[roadmap-track] Cost based optimizer(CBO)

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#915]
Main issue tracking for Cost based optimizer.

# Queries

| Queries                                         | Status    | Release Target | Comments        | 
| ----------------------------------------------- | --------- | -------------- | --------------- | 
| [count(*) with table statistics #914](https://github.com/datafuselabs/datafuse/issues/914)  | DONE  | v0.5  | |
| [exact min/max with table statistics #997](https://github.com/datafuselabs/datafuse/issues/997)  | PLANNING  | v0.5  | |

**Comment by zhang2014** [comment]
reference about cockroachdb CBO:
https://github.com/petermattis/opttoy
https://github.com/cockroachdb/cockroach/tree/master/pkg/sql/opt/norm/rules
https://www.cockroachlabs.com/blog/building-cost-based-sql-optimizer

**Comment by BohuTANG** [comment]
Add:
[exact min/max with table statistics #997](https://github.com/datafuselabs/datafuse/issues/997)

**Comment by leiysky** [comment]
Already tracked in #6643
