### ISSUE TITLE
bug: Not found Camel-Case table name or column at unquoted_ident_case_sensitive = 0 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#9169]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

all version

### What's Wrong?

```
set unquoted_ident_case_sensitive = 0; -- Databend default
create table `Email_01`(
    `SubId` Bigint,
    `EmaillAddress` varchar
);

select * from Email_01;
ERROR 1105 (HY000): Code: 1025, displayText = Unknown table 'email_01'.


create table `email_02`(
    `SubId` Bigint,
    `EmaillAddress` varchar
);
Query OK, 0 rows affected (0.014 sec)

MySQL [wubx]> insert into email_02 values(750879,'wubx@databend.com');
Query OK, 0 rows affected (0.022 sec)
MySQL [wubx]> select * from email_02 where SubId=750879;
ERROR 1105 (HY000): Code: 1065, displayText = error:
  --> SQL:1:30
  |
1 | select * from email_02 where SubId=750879
  |                              ^^^^^^^^^^^^^^ column doesn't exist

.

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
maybe `unquoted_ident_case_sensitive ` should be set in global.

I  did not have a good idea how to improve this, @leiysky  do you have good ideas?

**Comment by leiysky** [comment]
This behavior is as expected. The table is created with quoted identifier, so it's case-sensitive by default, and should be accessed with quoted identifier.

Maybe what you need is `set quoted_ident_case_sensitive = 0`?
