### ISSUE TITLE
Feature: Support timezone config in config file

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#9173]
**Summary**
Databend query need specify a timezone startup
support env and databend-query.toml support timezone

**Comment by TCeason** [comment]
Now the timezone is a setting.

```
Session settings are used for the current session.

Global settings are used for global cluster and other new sessions.

Default settings are the default value of the setting.
```

If we introduce a new config `timezone` in query.toml, maybe can get out of hand.

for example, if the user executes `unset timezone`, now the value of timezone will be set to the default value.

But if the settings also can be set in the config file, the value should be default or written in the config file?

**Comment by TCeason** [comment]
If we really need this, I think we can set the default value of the timezone as the config file set.

introduce a new param conf in default_settings

cc @sundy-li Can we modify as this?

```rust
pub fn default_settings(tenant: &str, conf: &Config) -> Result<Arc<Settings>> {
SettingValue {
    default_value: UserSettingValue::String(conf.query.timezone),
    user_setting: UserSetting::create(
        "timezone",
        UserSettingValue::String("UTC".to_owned()),
    ),
    level: ScopeLevel::Session,
    desc: "Timezone, default value: \"UTC\".",
    possible_values: None,
},
}

```

**Comment by sundy-li** [comment]
I think we can introduce more default user settings in the config file.

```
[settings]
timezone = "UTC"
...
```

The settings block could override the default setting.

**Comment by sandflee** [comment]
`timezone ` in settings is enough for us now, it seems confusing to add another set in config file.

**Comment by wubx** [comment]
> `timezone ` in settings is enough for us now, it seems confusing to add another set in config file.

You are right. 'timetzone' is only set up once, other databend-query startups will get it from meta.

**Comment by TCeason** [comment]
> I think we can introduce more default user settings in the config file.
> 
> ```
> [settings]
> timezone = "UTC"
> ...
> ```
> 
> The settings block could override the default setting.

In this pr https://github.com/datafuselabs/databend/pull/9181, we just add timezone. Other settings will support on the next.

**Comment by sundy-li** [comment]
> timezone in settings is enough for us now, it seems confusing to add another set in config file.

Seems reasonable, we already have global settings in meta, the setting in the config file is really useless!!!

This could make the codes much complicated.

@BohuTANG  Can we close this ?

**Comment by sundy-li** [comment]
Using config:

1. Will make the setting value inconsistent if we have multiple query nodes.
2. Should modify N times if we want to change the default value.

So `set global timezone = 'UTC'`  is always better than static config.
