### ISSUE TITLE
Bug: Unknown database in query without relation to this database

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9231]
**Summary**
```sql
mysql> create database test1;
Query OK, 0 rows affected (0.03 sec)

mysql> use test1;
Database changed
mysql> drop database test1;
Query OK, 0 rows affected (0.03 sec)

mysql> create database test2;
Query OK, 0 rows affected (0.04 sec)

mysql> create table test2.t(a int);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into test2.t values(1);
ERROR 1105 (HY000): Code: 1003, displayText = Unknown database 'test1'.
mysql>
```

It's strange that create table in database test but can't insert data ...  😅 

Ideally, we should avoid drop database in current database, so when `drop database test1;`, we should get error: ` cannot drop the currently open database`;

**Comment by xudong963** [comment]
After fixing the issue, I believe many current tests need to be changed, please be careful @ariesdevil

**Comment by sundy-li** [comment]
Yes， but the behavior is not friendly to users if we want to execute other commands after this drop SQL.

The connection/session is started based on the current database, it will throw an error if the current database is dropped, we should better throw it at the drop statement. Postgresql did it better behavior, we can follow this.

https://www.postgresql.org/docs/current/sql-dropdatabase.html

**Comment by Xuanwo** [comment]
It's more like a bug to me that using `ctx.get_current_database()` instead of the database from the plan.

https://github.com/datafuselabs/databend/blob/1a1e45ce4464ac2427f8cb385abaaacc532d4b9c/src/query/storages/fuse/fuse/src/operations/truncate.rs#L72

However, adding database in table info will make many logic simpler. So I'm second to this change.

**Comment by Xuanwo** [comment]
> Maybe we need to update the `database` of query context while users have specified database. The same rule will also apply to `catalog`.

For example, `QueryContext`'s `get_current_database` should be implemented as:

```rust
fn get_current_database(&self) -> String {
    match self.current_database {
        Some(db) => db.to_string(),
        None => self.shared.get_current_database()
    }
}
```

And current_database should be updated during parsing or binding.

**Comment by ariesdevil** [comment]
> For example, `QueryContext`'s `get_current_database` should be implemented as:↳
> 
> ```rust
> fn get_current_database(&self) -> String {
>     match self.current_database {
>         Some(db) => db.to_string(),
>         None => self.shared.get_current_database()
>     }
> }
> ```
> 
> And current_database should be updated during parsing or binding.

I considered this way but I think the current_database will hard to locate in complex query.

**Comment by Xuanwo** [comment]
> I considered this way but I think the current_database will hard to locate in complex query.

Oh, nice catch. You are right, it's required to have database in table info.

**Comment by Xuanwo** [comment]
> The `TableInfo` have tenant name but no database which weird to me. If anyone knows what the historical reasons are, please telling : )

We used to plan to support moving tables between databases like https://clickhouse.com/docs/en/sql-reference/statements/alter/update. So database's id and name could be changed.
