### ISSUE TITLE
Tracking: enable more test suits from cluster

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9270]
**Summary**

Currently, only `base`, `query`, `mode/cluster` are enabled for cluster in sqllogictest.

It is too weak...

**Comment by sandflee** [comment]
this's very important ,  
1. cluster mode is more like used in product.
2. and the prs are always tested on singe-worker mode not cluster mode.

**Comment by xudong963** [comment]
Yes, after https://github.com/datafuselabs/databend/pull/9150 merged, will start the issue!
