### ISSUE TITLE
Build sqllogictest binary in build step

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend#9287]
**Summary**

Then we do not need the extra 4~5min build for every sqllogictest job.

cc @Xuanwo @xudong963

**Comment by Xuanwo** [comment]
I prefer to release as a new crate and install it the same as `sccache`.

**Comment by xudong963** [comment]
@Xuanwo Would you like to do it 🙈?

**Comment by Xuanwo** [comment]
How about release as `databend-sqllogictest`?

**Comment by xudong963** [comment]
> How about release as `databend-sqllogictest`?

LGTM!

**Comment by xudong963** [comment]
The issue is completed?

**Comment by Xuanwo** [comment]
Let's close.
