### ISSUE TITLE
performance: add pre-fetch for block reader

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9308]
**Summary**

For sync read:
https://github.com/datafuselabs/databend/blob/523e2190c275d481c707f8ee35972fc7290cba38/src/query/storages/fuse/fuse/src/io/read/block_reader.rs#L380-L390

https://github.com/datafuselabs/databend/blob/523e2190c275d481c707f8ee35972fc7290cba38/src/query/storages/fuse/fuse/src/io/read/block_reader.rs#L389-L389

If we have many indices may be a waste because their offset may be adjacent (note: not sequentially connected, there may be some gaps, like the gap <1KB), converts small fragmented reads into one large read,  so we can merge the reading them all in one:
```
let (merge_read_offset, merge_read_length) = ...;
let result = Self::sync_read_column(op.object(&location), merge_read_offset, merge_read_length); 
-- Strip out (offset, length) data from result
```

**Comment by BohuTANG** [comment]
cc @sundy-li @RinChanNOWWW

**Comment by sundy-li** [comment]
sync_read_column will respect fs cache if they are adjacent.

**Comment by BohuTANG** [comment]
async read from the second object store, like s3, the pre-fetch will be helpful.

The query:
```
SELECT * FROM hits  WHERE URL LIKE '%google%' ORDER BY EventTime LIMIT 10;
```

I print all read costs for each column of a partition:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/172204/208875076-9780f799-1067-4037-96f7-91e8af010bf5.png">


Read 30086bytes took: 114 ms. It's almost the same as reading 890095 bytes took: 111 ms. It's network latency bounded, not io-bounded.

FYI @Xuanwo
