### ISSUE TITLE
bug: case when not  woking as expected

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#9320]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

all

### What's Wrong?

```

create table tb01(d int);
insert into tb01 values(0),(2),(3);
select * from tb01;

select case when d > 0 then 
10/d 
else 
100
end 
from tb01;
```

1006: / by zero

### How to Reproduce?

above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
select multi_if(d>0, 10/d, 100) from tb01;

1006: / by zero

**Comment by TCeason** [comment]
`if(d > 0, 10/d, 100)`

This if function has two inner function:

1. >
2. DivFunctionImpl

Now in src/query/functions/src/scalars/function_adapter.rs will calc this two inner.eval.

> input_rows is [0, 2, 3]

and Div function input_rows also is [0, 2, 3].

That will cause this bug.

**Comment by TCeason** [comment]
Done with https://github.com/datafuselabs/databend/pull/10439
