### ISSUE TITLE
bug: Subqueries that query the same table will be translated into join.

### ISSUE THREAD

**Issue by xieguangkun** [datafuselabs/databend#9329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

xxx

### What's Wrong?

problem1:
Subqueries that query the same table will be translated into join.
<img width="273" alt="截屏2022-12-21 19 57 09" src="https://user-images.githubusercontent.com/41321181/208899930-2836f877-6de0-4237-b4c8-05ac7a243adf.png">

like:
![image](https://user-images.githubusercontent.com/41321181/208899189-b1fc7845-9e74-4d19-841f-bd956bbe383b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
@xieguangkun What's the error info? It's reasonable that subquery is translated to join
