### ISSUE TITLE
doc: maybe need some hint about how to debug locally

### ISSUE THREAD

**Issue by Layamon** [datafuselabs/databend#9372]
**Summary**
For me, never write rust before and use docker rarely, I want to learn datafuse internal by debug it locally; After reading README, I build it successful, but spent some time to find a simple way to run it locally; After asking community, I know [here](https://github.com/datafuselabs/databend/blob/main/scripts/ci/deploy/config/databend-query-embedded-meta.toml) are some useful config.
Maybe there are people like me also spent time to find this files, so it may be good to put in doc;

```
// --- a/docs/doc/90-contributing/00-building-from-source.md
// +++ b/docs/doc/90-contributing/00-building-from-source.md
// @@ -23,14 +23,17 @@ Databend is written in Rust, to build Databend from scratch you will need to ins
//  git clone https://github.com/datafuselabs/databend
//  cd databend
//  ```
// -### Run make
// +### Make and Run
//
//  ```shell
//  make build-release
//  ```
//
//  `databend-query` and `databend-meta` will be placed in the `target/release` directory.
// -
// +If you just want debug it locally, [There](https://github.com/Layamon/databend/tree/main/scripts/ci/deploy/config) are some useful configuration to run your interested module locally, for example, below com
// +```shell
// +databend-query -c databend_query_config_spec.toml
// +```
//
//  ### Build With Docker Image
```

**Comment by zhang2014** [comment]
CC: @soyeric128

**Comment by soyeric128** [comment]
Thanks for opening this issue and letting us know your concerns. That would be a good addition to the documentation. 
I just added a note about the sample configuration files, and I hope that can help. 
Happy Holidays!
