### ISSUE TITLE
[CLI] bendctl: databend cli

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#938]
**Summary**

Tasks:
- [ ] #1434

**Comment by BohuTANG** [comment]
@ZhiHanZ I will have a try in Rust first, what do you think?

**Comment by ZhiHanZ** [comment]
I think worth trying, although go provide official client go support in https://github.com/kubernetes/client-go, we desire simplified approach to deploy applications in multi-cloud and local environment and needs rust native approach for cargo related part, for k8s related development, we could use https://github.com/clux/kube-rs, as far I know krustlet works fine with it https://github.com/deislabs/krustlet.

**Comment by Xuanwo** [comment]
Based on the discussion at #4426, maybe we need to close this issue?
