### ISSUE TITLE
Feature: migrate hash functions into functions-v2

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#9385]
**Summary**

Description for this feature.

Migrate these hash function into functions-v2
```
md5
sha
sha1
sha2
blake3
xxhash32
xxhash64
siphash64
siphash
city64WithSeed
```

**Comment by TCeason** [comment]
Now have these todo. I will continue to do it tomorrow.

```
xxhash32
xxhash64
siphash64
siphash
```

**Comment by TCeason** [comment]
Done with https://github.com/datafuselabs/databend/pull/9402
