### ISSUE TITLE
Document downgrade procedure (if supported)

### ISSUE THREAD

**Issue by zamazan4ik** [datafuselabs/databend#9388]
**Summary**
After reading the section about [Upgrade](https://databend.rs/doc/deploy/upgrade/upgrade) procedure it's not clear - is the downgrade process supported or not? E.g. during the update, I found an issue with the newer version, and I want to fall back to the previous version. Could I do it? Could I do it without downtime?

**Comment by Xuanwo** [comment]
> is the downgrade process supported or not?

No, we don't support downgrade at this stage.
