### ISSUE TITLE
quoted indent is not supported 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#9421]
Flaky test:

```
statement error Duplicated column name
create table t("A" int, "A" int)
```

MySQL [(none)]> create table t("A" int, "A" int);
ERROR 1105 (HY000): Code: 1005, displayText = error:
  --> SQL:1:16
  |
1 | create table t("A" int, "A" int)
  | ------         ^^^
  | |              |
  | |              expected <Ident>
  | |              while parsing `<column name> <type> [DEFAULT <default value>] [COMMENT '<comment>']`
  | while parsing `CREATE TABLE [IF NOT EXISTS] [<database>.]<table> [<source>] [<table_options>]`

_Originally posted by @sundy-li in https://github.com/datafuselabs/databend/issues/9419#issuecomment-1367688326_

**Comment by leiysky** [comment]
This should work, maybe the setting `sql_dialect` is set to `MySQL` instead of default value?
