### ISSUE TITLE
Bug: 403 on creating stage without a trailing slash

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#9431]
**Summary**
SQL:
```
CREATE STAGE tpch100_data url='oss://wubx-bj01/data/tpch100_single_gz' 
  connection = (
        ENDPOINT_URL = 'https://oss-cn-beijing-internal.aliyuncs.com'
        ACCESS_KEY_ID = '---'
        ACCESS_KEY_SECRET = '--'
  );
list @tpch100_data/; -- 403
```

however replace the url with `'CREATE STAGE tpch100_data url='oss://wubx-bj01/data/tpch100_single_gz/'`, the 403 could be fixed.

**Comment by Xuanwo** [comment]
There are two problems here:

- Create stage with a path not ends with `/` should be disallowed
- Visiting this path should not be 403
