### ISSUE TITLE
Feature: The idea of ​​operator appling rules

### ISSUE THREAD

**Issue by dusx1981** [datafuselabs/databend#9512]
**manage rule by bitmap**

my gporca article: (https://blog.csdn.net/dusx1981/article/details/124553274)

Regarding determining the rules used by Operator, GPORCA's solution is to use bitmaps to manage Rules, and define a RuleFactory to manage all Rules in a unified manner. And classify Rule into Exploration and Implementation. Operator holds a bitmap of the rules that can be applied. When applying a rule, take the bitmap in Operator and all the bitmaps in RuleFactory and to determine the final applied rule, then traverse and apply the rule. After the Exploration stage is completed, all equivalent expressions are generated, and a new tree is generated with Pattern. Is this more efficient? I Translated GPORCA from C++ to Go，And IT works fine。

```
type RuleFactory struct {
	// range of all rules
	IdToRule map[RuleId]Rule

	// bitset of exploration rules
	ExplorationSet RuleSet

	// bitset of implementation rules
	ImplementationSet RuleSet
}

// Logical Operator
type Logical interface {
	Operator

	// rules can be applied to this operator
	CandidateRules() RuleSet
}
```

```
impl CascadesOptimizer {
    pub fn create(ctx: Arc<dyn TableContext>) -> Result<Self> {
        let explore_rules = if ctx.get_settings().get_enable_cbo()? {
            get_explore_rule_set()
        } else {
            RuleSet::create_with_ids(vec![]).unwrap()
        };
        ......
    }
}

fn explore_self(
    &mut self,
    optimizer: &mut CascadesOptimizer,
    scheduler: &mut Scheduler,
) -> Result<ExploreExprEvent> {
    ......

    // Check all rules ?
    for rule in optimizer.explore_rules.iter() {
        let apply_rule_task = ApplyRuleTask::with_parent(
            rule.id(),
            m_expr.group_index,
            m_expr.index,
            &self.ref_count,
        );
        scheduler.add_task(Task::ApplyRule(apply_rule_task));
    }

    ......
}

/// Doesn't check if children are matched
pub fn match_pattern(&self, _memo: &Memo, pattern: &SExpr) -> bool {
    if pattern.is_pattern() {
        return true;
    }

    if self.arity() != pattern.arity() {
        return false;
    }

    self.plan.rel_op() == pattern.plan().rel_op()
}
```

**Comment by dusx1981** [comment]
```
pub fn get_explore_rule_set() -> RuleSet {
    RuleSet::create_with_ids(vec![
        RuleID::CommuteJoin,
        RuleID::LeftAssociateJoin,
        RuleID::RightAssociateJoin,
    ])
    .unwrap()
}
```

are these going to be added?
```
    pub fn create_rule(&self, id: RuleID) -> Result<RulePtr> {
        match id {
            RuleID::EliminateEvalScalar => Ok(Box::new(RuleEliminateEvalScalar::new())),
            RuleID::PushDownFilterUnion => Ok(Box::new(RulePushDownFilterUnion::new())),
            RuleID::PushDownFilterEvalScalar => Ok(Box::new(RulePushDownFilterEvalScalar::new())),
            RuleID::PushDownFilterJoin => Ok(Box::new(RulePushDownFilterJoin::new())),
            RuleID::PushDownFilterScan => Ok(Box::new(RulePushDownFilterScan::new())),
            RuleID::PushDownLimitUnion => Ok(Box::new(RulePushDownLimitUnion::new())),
            RuleID::PushDownLimitScan => Ok(Box::new(RulePushDownLimitScan::new())),
            RuleID::PushDownSortScan => Ok(Box::new(RulePushDownSortScan::new())),
            RuleID::PushDownLimitOuterJoin => Ok(Box::new(RulePushDownLimitOuterJoin::new())),
            RuleID::RulePushDownLimitExpression => Ok(Box::new(RulePushDownLimitExpression::new())),
            RuleID::PushDownLimitSort => Ok(Box::new(RulePushDownLimitSort::new())),
            RuleID::EliminateFilter => Ok(Box::new(RuleEliminateFilter::new())),
            RuleID::MergeEvalScalar => Ok(Box::new(RuleMergeEvalScalar::new())),
            RuleID::MergeFilter => Ok(Box::new(RuleMergeFilter::new())),
            RuleID::NormalizeScalarFilter => Ok(Box::new(RuleNormalizeScalarFilter::new())),
            RuleID::SplitAggregate => Ok(Box::new(RuleSplitAggregate::new())),
            RuleID::FoldCountAggregate => Ok(Box::new(RuleFoldCountAggregate::new())),
            RuleID::NormalizeDisjunctiveFilter => {
                Ok(Box::new(RuleNormalizeDisjunctiveFilter::new()))
            }
            ......
        }
    }
```

**Comment by BohuTANG** [comment]
@leiysky is more familiar with this, looking forward to the answer :)

**Comment by leiysky** [comment]
> are these going to be added?

Yes. We haven't introduced rule bitmap in `Group` and `GroupExpression` because there are only a few exploration rules now.

In the databend optimizer, rules are categorized as transformation, exploration, and implementation rules. The implementation rules are deprecated recently in a refactor #9452.

For the transformation rules, we only use them in the `HeuristicOptimizer`, which is an optimizer that performs some heuristic optimization and produces exactly one optimal relational expression. For each transformation rule, exactly one substitution will be produced if the rule is applied successfully so we can replace the original sub-expression with the optimal one.

For the exploration rules, we only use them in the `CascadeOptimizer`. Each exploration rule may produce multiple substitutions, and we will memoize the substitutions in the struct `Memo`, expressions with the same output are stored in the same `Group`. After finishing the exploration, we will extract the optimal relational expression with the lowest cost.

**Comment by dusx1981** [comment]
Therefore, the optimization is divided into three stages, and an optimizer is used in each stage. In the stage that Cascades is responsible for, because there are fewer rules applied, Bitmap management is not required ？

**Comment by dusx1981** [comment]
And if need the bitmap feature, i can try to add it.

**Comment by dusx1981** [comment]
OK，i will try to finish it

**Comment by leiysky** [comment]
> OK，i will try to finish it

That's nice. I've just opened an issue for this https://github.com/datafuselabs/databend/issues/9536, you can assign it to yourself.

**Comment by leiysky** [comment]
I think we can close this issue now.
