### ISSUE TITLE
bug: native format does not support Tuple column.

### ISSUE THREAD

**Issue by lichuang** [datafuselabs/databend#9566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

current Version

### What's Wrong?

fail to query data from a Tuple column

### How to Reproduce?

fail to query data from a Tuple column:

```SQL
drop database u;

create database u;

use u;

create table a(b Tuple(Bool, Int64)) ENGINE=FUSE STORAGE_FORMAT='native';

insert into a values((true,2));

select b.1,b.2 from a;

select * from a;
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by b41sh** [comment]
fixed in PR #9798
