### ISSUE TITLE
bug: http handler return different result

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#9577]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

DatabendQuery v0.8.176-nightly-c44fcae(rust-1.67.0-nightly-2023-01-04T16:24:32.660387075Z)

### What's Wrong?

I use databend http handler to execute query, but I found different SQL return different response structure. For example, the following SQL
```
SELECT "column2","column3","column4","column5","column6","column7" FROM airbyte_integration_dnvcdtfusz;
```
got the result and the `field` as following:

![yRheBQ4lXW](https://user-images.githubusercontent.com/7600925/212019648-cbbb95a2-3f64-42f8-b368-fd5d2c879083.png)

But the next SQL 

```
SELECT table_name, column_name, data_type, is_nullable FROM information_schema.columns  WHERE table_name NOT IN (SELECT table_name FROM information_schema.tables WHERE table_type IN ('EXTERNAL', 'CATALOG'));
```

got the next result and the `field` as following:

![yhcevfiJ4k](https://user-images.githubusercontent.com/7600925/212020982-bfca2929-580b-41a7-853a-463c29278bc4.png)

We can see that different SQL return different structure.

### How to Reproduce?

Call databend query http handler and use the above SQL to reproduce.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
What's the difference?

**Comment by hantmac** [comment]
> What's the difference?
> 
> "column2" is the column name of the first query, it's right.

The `fields` field is different. The first one is “data_type”:{"type":"NULLABLE", "inner":{"type":"Boolean"}} the column type of it is `Bool` and the second one is "data_type":{"type":"String"} the column type of it is `VARCHAR`.

**Comment by Xuanwo** [comment]
> The `fields` field is different.

I didn't get it, why they need to be the same?

**Comment by hantmac** [comment]
Maybe a discussion is more reasonable.
