### ISSUE TITLE
Feature: refresh memory cache.

### ISSUE THREAD

**Issue by RinChanNOWWW** [datafuselabs/databend#9632]
**Summary**

When querying, Databend can cache some information. Some of them are immutable, such as `SegmentInfo`, `TableSnapshot`; some of them are mutable, such as `FileMetaData` needed by `read_parquet`.

We should provide a command to refresh the memory cache for the mutable information.

Possible syntax:

```
refresh 'location';

refresh 'CACHE_NAME';
```

cc @sundy-li

**Comment by BohuTANG** [comment]
> We should provide a command to refresh the memory cache for the mutable information.

Why should we refresh the memory cache?

**Comment by RinChanNOWWW** [comment]
We will enable cache for `read_parquet` in #9630.

The location of each parquet file will be cached.

But if the parquet file of that location is changed, we cannot get the right data before the cache is refreshed.

**Comment by BohuTANG** [comment]
By design, the cache item key must be unique and the content is immutable, remove them if changed or no used anymore instead of refreshing them.

**Comment by RinChanNOWWW** [comment]
Databend cannot know whether the parquet file is changed.

Can we remove the cache manually?

**Comment by BohuTANG** [comment]
> Databend cannot know whether the parquet file is changed.
> 
> Can we remove the cache manually?

We can not do that, you cannot know the parquet file is changed too.

**Comment by BohuTANG** [comment]
The file's `etag` from opendal may be helpful here, we can append it to the key.

**Comment by RinChanNOWWW** [comment]
As an alternative, I think we can add a parameter for `read_parquet` to determine whether use the cache?

**Comment by sundy-li** [comment]
> As an alternative, I think we can add a parameter for `read_parquet` to determine whether use the cache?

I do agree with it. Let's just add it for `read_parquet`.

**Comment by RinChanNOWWW** [comment]
> The file's `etag` from opendal may be helpful here, we can append it to the key.

Fs backend does not support `etag`.

Similarly, we can use location + modified time as the cache key.
