### ISSUE TITLE
handle correlated subquery  properly 

### ISSUE THREAD

**Issue by jyizheng** [datafuselabs/databend#964]
**Summary**

Need to report error for correlated subquery like below for Exists or redesign the solution:

SELECT column1, column2, ....
FROM table1 outer
WHERE column1 Exists
                    (SELECT column1, column2
                     FROM table2
                     WHERE expr1 = 
                               outer.expr2);

**Comment by Xuanwo** [comment]
@leiysky @andylokandy Is this issue still valid?

**Comment by leiysky** [comment]
This is supported in new planner now, we can close this.
