### ISSUE TITLE
Feature:  remove keyword CREDENTIALS as an alias of CONNECTION

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#9658]
**Summary**

```
            let mut conns = connection_opt.map(|v| v.2).unwrap_or_default();
            conns.extend(credentials_opt.map(|v| v.2).unwrap_or_default());
```

**Comment by ZhiHanZ** [comment]
would it introduce some breaking changes on copy into SQL?

**Comment by youngsofun** [comment]
not sure,  CREDENTIALS not in the current doc.

**Comment by youngsofun** [comment]
> not sure, CREDENTIALS not in the current doc.

it has been removed from doc for 2.5 years.
https://github.com/datafuselabs/databend/pull/6633/files
