### ISSUE TITLE
bug: Copy into from csv failed

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend#9659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.5

### What's Wrong?

copy into from stage failed on csv json data

### How to Reproduce?

```sql
CREATE TABLE IF NOT EXISTS t8 (i int, a Variant, b string) ENGINE = FUSE
```
data named complex.csv

```csv
0, '{"str_col": 9, "int_col": 9}','hello'
```

```sql
COPY INTO t8 FROM @test_stage/jdbc/c2/ PATTERN = 'complex.csv' FILE_FORMAT = ( type = 'CSV' ) 
```

error:

Query failed (#ee387cea-2560-437b-90e2-677bf0607546): too many fields, expect 3, got 4, split jdbc/c2/complex.csv(42 bytes), row=0=0+0, offset=0=0+0, options=FileFormatOptionsExt { stage: FileFormatOptions { format: Csv, skip_header: 0, field_delimiter: ",", record_delimiter: "\n", nan_display: "NaN", escape: "", compression: None, row_tag: "", quote: "\"" }, ident_case_sensitive: false, headers: 0, json_compact: false, json_strings: false, timezone: UTC }, schema=[TableField { name: "i", default_expr: None, data_type: Number(Int32) }, TableField { name: "a", default_expr: None, data_type: Variant }, TableField { name: "b", default_expr: None, data_type: String }]

it seems to be a CSV parsing issue since it works on the following csv data
```csv
0, '{"str_col": 9}','hello'
```

NOTICE:
change table schema to String would report the SAME error
```sql
CREATE TABLE IF NOT EXISTS t18 (i int, a String, b string) ENGINE = FUSE
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZhiHanZ** [comment]
cc @youngsofun could you take a look on the issue when you are available?

**Comment by youngsofun** [comment]
because `{"str_col": 9, "int_col": 9}'` has `,` in it, it should be quoted：

```
0, "'{"str_col": 9, "int_col": 9}'",'hello'
```

**Comment by youngsofun** [comment]
`FILE_FORMAT = ( type = CSV, quote='\'')`

**Comment by ZhiHanZ** [comment]
I've found that CSV should NOT have space in field delimiter quote, otherwise it would report error
