### ISSUE TITLE
feat: unified EXPLAIN and EXPLAIN FRAGMENTS formats

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9679]
**Summary**

If we have cluster A with 3 nodes and add another 3 query nodes to cluster A, the query performance is not improved, it's very hard to check where the problem is.

So if we add more stats(like cost estimate for each fragment) to `explain fragment`, it's easy to address where the problem is, and we should choose which exchange method and the join-order.

cc @xudong963 @leiysky

**Comment by leiysky** [comment]
@BohuTANG We can display the estimated rows for `EXPLAIN FRAGMENT`, but for this issue, I think what we need is the `EXPLAIN ANALYZE` statement which collects the runtime profiling information and display the time cost of each operator(e.g. I/O wait, CPU processing, idle)

**Comment by BohuTANG** [comment]
> We can display the estimated rows for EXPLAIN FRAGMENT

Yes.

> I think what we need is the EXPLAIN ANALYZE statement which collects the runtime profiling information and display the time cost of each operator(e.g. I/O wait, CPU processing, idle)

This is what @zhang2014 will do in the profiling parts.

**Comment by leiysky** [comment]
@BohuTANG I noticed that we are using different formats in `EXPLAIN` and `EXPLAIN FRAGMENTS`, what about unifying them?

For example:
```
# Before
mysql> explain fragments select * from numbers(10);
+-----------------------------+
| explain                     |
+-----------------------------+
| Fragment 0:                 |
|   TableScan: [''.'numbers'] |
+-----------------------------+
2 rows in set (0.04 sec)
Read 0 rows, 0.00 B in 0.002 sec., 0 rows/sec., 0.00 B/sec.

# After
mysql> explain fragments select * from numbers(10);
+--------------------------------------------------+
| explain                                          |
+--------------------------------------------------+
| Fragment 0:                                      |
| TableScan                                        |
| ├── table: default.system.numbers                |
| ├── read rows: 10                                |
| ├── read bytes: 80                               |
| ├── partitions total: 1                          |
| ├── partitions scanned: 1                        |
| ├── push downs: [filters: [], limit: NONE]       |
| └── estimated rows: 10.00                        |
|                                                  |
+--------------------------------------------------+
10 rows in set (0.17 sec)
Read 0 rows, 0.00 B in 0.002 sec., 0 rows/sec., 0.00 B/sec.
```

**Comment by BohuTANG** [comment]
@leiysky This is what I need, I changed the issue titles.
