### ISSUE TITLE
bug: Server is not starting up

### ISSUE THREAD

**Issue by kesavkolla** [datafuselabs/databend#9695]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.8-nightly-08e9ebd-simd(1.68.0-nightly-2023-01-20T08:57:24.995823415Z)

### What's Wrong?

When I add the following in the query.toml file the server fails to start:

```toml
[storage]
type = "fs"
allow_insecure = true
[storage.fs]
data_path = "/var/lib/databend/query"
```

Here is the error message:

```
HTTP API
   listened at 127.0.0.1:28002
gRPC API
   listened at 127.0.0.1:9191

==> /tmp/std-query.log <==
Databend Query start failure, cause: Code: 1002, displayText = redefinition of table `storage.fs` for key `storage.fs` at line 43 column 1, source: None
redefinition of table `storage.fs` for key `storage.fs` at line 43 column 1.

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 

```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by everpcpc** [comment]
When volume an external `query.toml` into the docker container,  env `QUERY_CONFIG_FILE` should also be set.

And, yes we can improve the generation process for default query config to avoid this.

**Comment by kesavkolla** [comment]
I didn't mount this file. I just copied the file into /etc/databend folder inside container.

**Comment by everpcpc** [comment]
Oh, that's the similar thing.
Whenever the query config is changed manually, `QUERY_CONFIG_FILE` should be set to ensure we do not automatically modify it.

**Comment by everpcpc** [comment]
#9696 has been merge, and new nightly release will be in one hour.
