### ISSUE TITLE
bug: read_parquet OOM when reading 1.7G parquet file

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9735]
**Summary**

lineitem.parquet(1.7G):
```
curl -L 'https://drive.google.com/uc?export=download&id=18gv0Yd_a-Zc7CSolol8qeYVAAzSthnSN&confirm=t' > lineitem.parquet
```

query(EC2 with 32GB):
```
select * from read_parquet('/root/bench/lineitem.parquet')  order by l_shipdate ignore_result;
```

It would be OOM soon.

**Comment by RinChanNOWWW** [comment]
There is memory leak in `order by`.

**Comment by BohuTANG** [comment]
`select * from read_parquet('/root/bench/lineitem.parquet') order by l_shipdate ignore_result;`:

memory profiling:
![orderby](https://user-images.githubusercontent.com/172204/215263597-839feaa4-a653-4c21-98ff-c647145ab5af.svg)

cc @RinChanNOWWW @sundy-li

**Comment by BohuTANG** [comment]
Resolved.
