### ISSUE TITLE
databend/Cargo.toml  openraft v0.7.4-alpha.3

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9741]
**Summary**

https://github.com/datafuselabs/databend/blob/349c38e2ac1e87a25f180d88739ad5212dfb28e2/Cargo.toml#L86

Why we do not publish the tag `v0.7.4-alpha.3` on `datafuselabs/openraft`?

cc @drmingdrmer

**Comment by drmingdrmer** [comment]
It just can be published, but not yet.

Other breaking changes might be introduced soon to address the requirements put forth by meta-service.

What's the matter, sir?

**Comment by BohuTANG** [comment]
Ok, thanks.

> What's the matter, sir?

Just curious when the compiling :)
