### ISSUE TITLE
Better to return specific error info instead of `Unimplemented`

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#9764]
Btw, it's better to return specific error info instead `Unimplemented`

_Originally posted by @xudong963 in https://github.com/datafuselabs/databend/discussions/9763#discussioncomment-4808163_

**Comment by sherlockbeard** [comment]
i tried to replicate its throwing 
```ERROR 1105 (HY000): UnknownTable. Code: 1025, Text = Unknown table 't1'.```
so its throwing specific error code and message I believe its good to close .
