### ISSUE TITLE
[build] snmalloc broken the arm release

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#977]
**Summary**
https://github.com/datafuselabs/datafuse/actions/runs/994172052

And we should add arm build check to PR build CI

**Comment by SchrodingerZhu** [comment]
Ouch. `snmalloc` should support `aarch64` and `armv7` targets. I would like to look into this but seems that the CI did not give the detailed error message from the compiler?

cc @mjp41.

**Comment by mjp41** [comment]
The issue appears to be
```
aarch64-linux-gnu-g++: error: unrecognized command line option '-mcx16
```
The `-mcx16` flag should be gated behind x86 targets. Is this compiling on Arm for Arm, or cross compiling?

**Comment by SchrodingerZhu** [comment]
oh, I just found that.

Basically, cmake detects the processor type based on the host; but we haven't provided any way to detect the target specified by cargo.

I assume maybe built by `cc` can be another choice here? but I haven't got a chance to try that yet.

**Comment by SchrodingerZhu** [comment]
@mjp41 it is possible to do it the following way:
```
check_cxx_compiler_flag(-mcx16 TARGET_MCX16_SUPPORTED)
```
Then, postpone the correctness checking to `C++` macro.
maybe a better choice than using cmake detection since it was hard to do cross-compiling?

**Comment by mjp41** [comment]
@SchrodingerZhu that sounds good to me.  Want to PR that into snmalloc?

**Comment by SchrodingerZhu** [comment]
sure. will do that
