### ISSUE TITLE
bug: return wrong result set

### ISSUE THREAD

**Issue by hanyisong** [datafuselabs/databend#9820]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.19

### What's Wrong?

return wrong result set
```sql
SELECT t0.c0float, t0.c1varchar, t0.c2int FROM t0 WHERE (NOT (((- t0.c2int))+((+ t0.c2int)))); -- 0
```

### How to Reproduce?

```sql
DROP DATABASE IF EXISTS databend16;
CREATE DATABASE databend16;
USE databend16;
CREATE TABLE t0(c0FLOAT DOUBLE NOT NULL DEFAULT(9.06575104E8), c1VARCHAR VARCHAR NULL, c2INT INT16 NOT NULL DEFAULT(-779019258));
INSERT INTO t0(c0float) VALUES (9.06575104E8);
INSERT INTO t0(c0float) VALUES (0.0591878779232502);
INSERT INTO t0(c0float) VALUES (2.13990016E9);

SELECT t0.c0float, t0.c1varchar, t0.c2int FROM t0 WHERE (NOT (((- t0.c2int))+((+ t0.c2int)))); -- 0
SELECT SUM(count) FROM (SELECT (((NOT (((- t0.c2int))+((+ t0.c2int)))) IS NOT NULL AND (NOT (((- t0.c2int))+((+ t0.c2int))))) ::BIGINT)as count FROM t0) as res -- 3
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by momi15075** [comment]
DROP DATABASE IF EXISTS databend16;
CREATE DATABASE databend16;
USE databend16;
CREATE TABLE t0(
  c0 DOUBLE NOT NULL DEFAULT 9.06575104E8, 
  c1 VARCHAR(255) NULL, 
  c2 INT NOT NULL DEFAULT -779019258
);
INSERT INTO t0(c0) VALUES (9.06575104E8);
INSERT INTO t0(c0) VALUES (0.0591878779232502);
INSERT INTO t0(c0) VALUES (2.13990016E9);

SELECT t0.c0, t0.c1, t0.c2 FROM t0 WHERE (NOT (((- t0.c2))+((+ t0.c2)))); 
SELECT SUM(count) FROM (SELECT (((NOT (((- t0.c2))+((+ t0.c2)))) IS NOT NULL AND (NOT (((- t0.c2))+((+ t0.c2))))) AS count FROM t0) as res;


Let me know if this helps

**Comment by BohuTANG** [comment]
Now databend will return error:
```
1001: number overflowed while evaluating function `to_int16(-779019258)`
```
