### ISSUE TITLE
bug: OBJECT/JSON not supported in SQL CREATE stmts

### ISSUE THREAD

**Issue by haydenflinner** [datafuselabs/databend#9826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.18-nightly-e0899c0

### What's Wrong?

[This page](https://databend.rs/doc/sql-commands/ddl/table/ddl-create-table ) says that OBJECT is a valid type name, but it's not in `databend/src/query/sql/src/planner/semantic/type_check.rs`. JSON doesn't seem to be there either.

### How to Reproduce?

```
mysql -h 127.0.0.1 --user root -P 3307
MySQL [(none)]> CREATE TABLE has_obj(x OBJECT);
ERROR 1105 (HY000): Code: 1001, displayText = Invalid type name 'Object'.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
`OBJECT`, `JSON`, `VARIANT` are same types. 

We will update the documents and support them in SQL parser.
