### ISSUE TITLE
bug: information_schema.columns data_type is inconsistent between versions 0.8 and 0.9

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#9842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v0.9.17

### What's Wrong?

We have made some internal enhancements to `Sharding-jdbc` to be compatible with `Mariadb`, `Aurora` and `MySQL`. Currently, we use `Sharding-JDBC` to connect `Databend` to implements read-write separation and sharding-table(just temporary, Will be merged after supporting cluster-key and cache).

After PR https://github.com/datafuselabs/databend/pull/9583, everything works well.

Recently, we found some problems with data types after upgrading to 0.9.X:
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/30121694/216051338-b4aa6ed2-6136-49f9-874f-242fcbc92fbd.png">
VARCHAR changed to VARCHAR NULL in information_schema.columns.

0.8.X like this:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/30121694/216049908-f85611ff-2f0f-48ca-8ec2-32fe25601690.png">

I guess this is due to the TableMeta data conversion from 0.8 to 0.9.

In our framework, we have some logic to detect data type from target database, VARCHAR NULL is a little weird, and it caused some exception.
<img width="899" alt="image" src="https://user-images.githubusercontent.com/30121694/216051200-f4b61b8f-578e-41b9-a70c-bc12d61c05af.png">
They cannot be matched.

And i tested it in MySQL, data_type doesn't contain NULL:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/30121694/216058227-df109a20-c19a-4a45-8448-02666e46a416.png">

So, can I cut off string to remove `NULL` in data_type column of information_schema.columns view table? Or is there any other methods?
https://github.com/datafuselabs/databend/blob/005b10c0906fbbb2111503fcdd4e4e65b93a2989/src/query/storages/information-schema/src/columns_table.rs#LL39C16-L39C16
Ensure that data_type is only data type, I think this should be reasonable.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
I think we should remove this null in `information_schema.columns` since we already have is_nullable datatype.
