### ISSUE TITLE
bug: connection: connection reset, source: Some(hyper::Error(Body, Error { kind: Io(Kind(ConnectionReset))

### ISSUE THREAD

**Issue by Data-bytes305** [datafuselabs/databend#9860]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v0.9.21-nightly-54eb098

### What's Wrong?

![image](https://user-images.githubusercontent.com/83893570/216285454-89628a4e-d5a0-48af-a0d5-88a0b0acd548.png)

ods_nwms.nwms_om_deliver_d:  92678646条
ods_nwms.nwms_om_deliver_m:  1236546条
ods_nwms.nwms_bm_defcust:    196855条
ods_nwms.nwms_bm_defarticle: 2752577条

![image](https://user-images.githubusercontent.com/83893570/216285852-615a3b8b-8efa-4963-8176-de996c094350.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment]
Seems it's related to fetch large data from storage.  Can you get the results after serval retrys of the query?

**Comment by Xuanwo** [comment]
> Seems it's related to fetch large data from storage

The error is not error returned by OpenDAL. Maybe in data exchange between cluster.

**Comment by zhang2014** [comment]
This error is unexpected. We will try to find root cause and fix it.

By the way, databend is not retrying the query when error. maybe we need should add retry in client.

**Comment by Data-bytes305** [comment]
![image](https://user-images.githubusercontent.com/83893570/216812318-e7e3a838-aa8b-4d1d-aa98-0053748db658.png)
@Xuanwo  You are right.  I tested it 10 times
