### ISSUE TITLE
Feature: Support `upsert` in databend

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend#9861]
**Summary**

Description for this feature.

Tapdata Cloud will perform an upsert operation. If the target already has data, it will recognize it and update it according to the source. If the slave table data is completely new, it will not be affected.

**Comment by BohuTANG** [comment]
UPSERT is on the plan, will do it after real-time update is done, cc @zhyass

**Comment by flaneur2020** [comment]
upsert may requires some extra infomation about the deduplication key, i created a seperated issue about this: https://github.com/datafuselabs/databend/issues/9909

**Comment by BohuTANG** [comment]
Databend has 'repalce into' instead of upsert.
