### ISSUE TITLE
Allow PlanNode::Empty as input

### ISSUE THREAD

**Issue by TennyZhuang** [datafuselabs/databend#988]
**Summary**

Currently `SELECT 1` will generate a dummy `PlanNode::ReadDataSource` from system.one, which is confusing and ugly in code. See plan_parser.rs

Can we remove the dummy read, and just leave empty? (It will failed on pipeline now).

**Comment by sundy-li** [comment]
But `select 1` should return 1. If it changes to an empty read, it will be empty result ?

**Comment by TennyZhuang** [comment]
> But `select 1` should return 1. If it changes to an empty read, it will be empty result ?

In fact that `SELECT 10` will also generate dummy read on system.one, the constant is generated from `PlanNode::Expression`, and the `PlanNode::ReadDataSource` is meaningless.

```
// explain select 10;
| Projection: 10:UInt8
  Expression: 10:UInt8 (Before Projection)
    ReadDataSource: scan partitions: [1], scan schema: [dummy:UInt8], statistics: [read_rows: 1, read_bytes: 1] |
```

**Comment by TennyZhuang** [comment]
Make `ExpressionPlan.input` to `PlanNode::Empty` will cause pipeline failed. I've not investigated it now.

**Comment by sundy-li** [comment]
Yes, because no data is available upstream, so the expression will not execute.

Expressions are executed block by block, if there is no block from upstream, so there will be no expression result.

**Comment by TennyZhuang** [comment]
So How to fix it? EmptyPlan should produce an empty block?

sundyli ***@***.***>于2021年7月5日 周一13:16写道：

**Comment by TennyZhuang** [comment]
Or we can change PlanNode.input to Option<> ?

**Comment by leiysky** [comment]
> Or we can change PlanNode.input to Option<> ?

It's a really big change I've tried before but gave up at last, which is not reasonable.

I think what you need is a `DualTable` plan.

**Comment by sundy-li** [comment]
> So How to fix it? EmptyPlan should produce an empty block?

If we wanna a one-row result, we must feed a one-row input, so an empty block will not work, a one-row block will work.

1. Currently,  if there is no input source plan, we generate a dummy plan from `system.one`, this is a kind of ClickHouse way.
2. If we want to keep the `EmptyPlan` and make the pipeline works, we can introduce a new option in `EmptyPlan`, like `produce_one_row`,  **arrow-datafusion**  did [this way](https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/empty.rs#L37-L41)

> I think what you need is a DualTable plan.
It could, but it also needs to implement a source plan which generates one dummy row.


:),  I don't know how mysql/tidb/... handle this case, I just a little familiar with clickhouse, so I choose the first option to implement it.

**Comment by BohuTANG** [comment]
`system.one` is a special data source for dummy, guess it same as `DualTable`

**Comment by Xuanwo** [comment]
Is this issue still valid? @leiysky

**Comment by Xuanwo** [comment]
We have migrated to the new planner. Let's close.
