### ISSUE TITLE
test_sqllogic_query_cluster_linux test is hang

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#9892]
`Dev Linux / test_sqllogic_query_cluster_linux ` test is hang

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/9883#issuecomment-1415460965_

**Comment by BohuTANG** [comment]
After re-tried, it works again.

**Comment by zhang2014** [comment]
fixed in main.
