### ISSUE TITLE
[profiling] change pprof library to rust-lang/measureme

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#990]
**Summary**

Use rustc's self-profiling:
https://github.com/rust-lang/measureme

**Comment by jyz0309** [comment]
I have tried to change it. But unfortunately I failed. I found that `measureme` need a file to show flamegraph. And I think it's more complex that `pprof`(maybe just I have not understood it well 😔)

**Comment by jyz0309** [comment]
I have tried to change it. But unfortunately I failed. I found that `measureme` need a file to show flamegraph. And I think it's more complex that `pprof`(maybe just I have not understood it well 😔)

**Comment by Xuanwo** [comment]
@BohuTANG Do we still need this change anymore?

**Comment by BohuTANG** [comment]
I think no it need now, let's close it.
