### ISSUE TITLE
bug: type assertion failed on decorrelate subquery

### ISSUE THREAD

**Issue by andylokandy** [datafuselabs/databend#9934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

fdaba30184

### What's Wrong?

assertion failed on decorrelate subquery

### How to Reproduce?

```sql
MySQL root@localhost:(none)> select 1 < ANY(SELECT NULL)
(1105, 'Code: 1104, displayText = assertion failed: `(left == right)`\n  left: `Null`,\n right: `Nullable(Number(UInt8))`: column datatype mismatch at index: 0, expr: lt(TRY_CAST(1 AS UInt8 NULL), subquery_2 (#2)) blocks: \n\n+----------+\n| Column 0 |\n+----------+\n| NULL     |\n+----------+.')
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xudong963** [comment]
Seems the bug is introduced in the latest main. I test in my local with yesterday's main, no bug, but after I update my local, the bug occurs 🤣
