### ISSUE TITLE
[optimizer][CBO] exact min/max with table statistics

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#997]
**Summary**

Like count:
https://github.com/datafuselabs/datafuse/issues/914

Add min/max exact optimizer support with table statistics

**Comment by leiysky** [comment]
IMHO, this work should be done with query cache or columnar rough index.

Statistics should be approximated and lazily updated.

Use statistics to produce query result potentially requires statistics to be strongly consistent with data. As soon as we support real-time modifying or transaction, the management of statistics will become a disaster.

**Comment by BohuTANG** [comment]
Right, min/max is set from the store(or others data sources) side and they are from the columnar index, so here is exact.
