### ISSUE TITLE
Feature:  select from <uri>

### ISSUE THREAD

**Issue by youngsofun** [datafuselabs/databend#9974]
**Summary**

flattern [externalStageParams](https://databend.rs/doc/sql-commands/ddl/stage/ddl-create-stage#externalstageparams) into args of   `uri table function`

```
select table1.c1 from 's3://'  (AWS_KEY_ID => '<string>' ,  AWS_SECRET_KEY =>  '<string>',  file_format => 'parquet') table1
```

does this look good to you? @leiysky :

```
from 'uri'
from @stage_name
from table_name
from `table_name`
from "table_name" (deps on dialect)
```

alter_native is :

```
select table1.c1 from URI('s3://' , AWS_KEY_ID => '<string>' ,  AWS_SECRET_KEY =>  '<string>',  file_format => 'parquet') table1
```

**Comment by youngsofun** [comment]
cc @sundy-li @BohuTANG @Xuanwo

**Comment by sundy-li** [comment]
args flattern seems natural.

**Comment by Xuanwo** [comment]
I like `select * from 's3://abc'`, the semantic is really clear.
