### ISSUE TITLE
Feature: delete with subquery

### ISSUE THREAD

**Issue by Data-bytes305** [datafuselabs/databend#9986]
**Summary**

![image](https://user-images.githubusercontent.com/83893570/218259165-7cc71ad9-cd72-4f17-b43e-024b38412ee6.png)

**Comment by xudong963** [comment]
Dup with https://github.com/datafuselabs/databend/issues/9852.

By the way, If you need this feature urgently, I can raise the priority. Please tell me. @Data-bytes305

**Comment by BohuTANG** [comment]
> Dup with #9852.
> 
> By the way, If you need this feature urgently, I can raise the priority. Please tell me. @Data-bytes305

This is useful, let's do it.
